### ISSUE TITLE
Maximising a ribbon window with DWM enabled results in it not maximising properly

### ISSUE THREAD

**Issue by redwyre** [fluentribbon/Fluent.Ribbon#10]
You can see the top window border.

This has been happening since upgrading to 3.0.0, 3.0.3 samples still have the issue
![ribbon](https://cloud.githubusercontent.com/assets/431728/4912841/1a2f9964-64a5-11e4-9c4c-e55091b79b43.png)

**Comment by redwyre** [comment]
I'll see if I can have a look into this

**Comment by batzen** [comment]
I don't know how to fix the current issues, including this one, related to the microsoft WindowChrome class. Any suggestions from anyone?

**Comment by redwyre** [comment]
Is the only real solution to re-implement WindowChrome?

**Comment by batzen** [comment]
I got no time to re-implement it...
Any other suggestions?

**Comment by batzen** [comment]
Could anyone have a look if it's fixed in version 4.0 (develop branch)?
I don't have a windows 7 machine at hand.

**Comment by batzen** [comment]
Tested this myself and as far as I can tell everything works as it should now.
