### ISSUE TITLE
Can't Drag 'n Drop from InRibbonGallery

### ISSUE THREAD

**Issue by sborkman** [fluentribbon/Fluent.Ribbon#100]
I'm following the Drag 'n Drop tutorial found on this page:
http://wpftutorial.net/DragAndDrop.html

I'm trying to drag an item from a control in an InRibbonGallery.
Even the simplest examples don't work. Try this:

		<fluent:Ribbon AutomaticStateManagement="True" Grid.Row="0">
			
			<fluent:RibbonTabItem Header="tab item">

				<fluent:RibbonGroupBox Header="group box">
					<fluent:InRibbonGallery Width="500" >
						<Label PreviewMouseLeftButtonDown="UIElement_OnPreviewMouseLeftButtonDown" MouseMove="UIElement_OnMouseMove" >this is a label in the gallery</Label>
					</fluent:InRibbonGallery>
				</fluent:RibbonGroupBox>

			</fluent:RibbonTabItem>
			
		</fluent:Ribbon>

And here's the C# code behind:

		protected Point myDragStartPoint;

		private void UIElement_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			myDragStartPoint = e.GetPosition(null);
		}

		private void UIElement_OnMouseMove(object sender, MouseEventArgs e)
		{
			Point mousePos = e.GetPosition(null);
			Vector diff = myDragStartPoint - mousePos;

			if (e.LeftButton == MouseButtonState.Pressed &&
				(Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance ||
				 Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance)
				)
			{

				// Initialize the drag & drop operation
				//DataObject dragData = new DataObject(Globals.ITEM_DRAG_N_DROP, item);
				//DragDrop.DoDragDrop(this, dragData, DragDropEffects.Copy);

				System.Diagnostics.Debug.Print(System.Diagnostics.Stopwatch.GetTimestamp().ToString() + " Dragging an item.");
			}
			else
			{
				System.Diagnostics.Debug.Print(System.Diagnostics.Stopwatch.GetTimestamp().ToString() + " Not dragging an item. " +
					(e.LeftButton == MouseButtonState.Pressed).ToString() + " " +
					(Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance).ToString() + " " +
					(Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance).ToString());
			}
			

		}

The PreviewMouseLeftButtonDown even fires ok.
The OnMouseMove event only seems to fire when the mouse button isn't pressed. This makes it impossible to detect a drag. It's like the gallery swallows up the events in this case.

I had the same problem in a fluent:Gallery as well. If the label is not in a gallery (placed directly in a RibbonGroupBox or outside of the ribbon altogether), drag 'n drop worked ok.

Is there a way to make this work?

**Comment by sborkman** [comment]
Looks like I might have answered my own question. I found a work-around that seems to get the job done. 

		protected Point myDragStartPoint;

		private bool setMouseMoveEventHandler = false;

		private void UIElement_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			myDragStartPoint = e.GetPosition(null);
			Control control = sender as Control;

			if (control != null)
			{
				Fluent.InRibbonGallery gallery = control.Parent as Fluent.InRibbonGallery;

				if (gallery != null)
				{
					GalleryItem galleryItem = (GalleryItem) gallery.ItemContainerGenerator.ContainerFromItem(sender);

					if (!setMouseMoveEventHandler)
					{
						setMouseMoveEventHandler = true;
						galleryItem.MouseMove += UIElement_OnMouseMove;
					}
				}

			}
		}

The key is to subscribe to the MouseMove event on the container that's generated internally to hold the Label (or whatever) in the InRibbonGallery, rather than trying to get MouseMove events from the Label directly. I'm able to detect a drag that way.

**Comment by sborkman** [comment]
I should add that if you're populating the InRibbonGallery by binding the ItemsSource and using an ItemTemplate (rather than adding controls to the InRibbonGallery manually), your controls in the InRibbonGallery won't be part of the logical tree (in my experience from just a moment ago), so you'll have to traverse the visual tree to find a reference to the InRibbonGallery from the sender object in the PreviewMouseLeftButtonDown event handler. In my example above, I used the logical tree to find the owning InRIbbonGallery.

**Comment by batzen** [comment]
So your request is to get a working logical tree in "InRibbonGallery"?

**Comment by sborkman** [comment]
No, it's to get the MouseMove event to work for controls inside an InRibbonGallery (such as the Label in my example). Currently, the MouseMove event doesn't fire if the left button is pressed. This isn't really an issue for me anymore, because I have a work-around, but it might still be something worth addressing.

**Comment by batzen** [comment]
Ok, then I misunderstood that part. Made the logical tree working now anyway.
Feel free to address that issue further, I won't as I don't need it.

Do you want to address it further or can we close this issue?

Maybe I should create a "Known issues" section for this kind of issue.

**Comment by sborkman** [comment]
Thanks, that's good news about the logical tree. And yes, I think a known issues section might be a good idea for gotchas like this one. I think we can close this issue, as I have a work-around. Thanks.
