### ISSUE TITLE
RibbonContextualTabGroup not working with Mahapps.MetroWindow

### ISSUE THREAD

**Issue by sachabruttin** [fluentribbon/Fluent.Ribbon#1005]
I try to display RibbonContextualTabGroup on a MetroWindow.
I followed the https://fluentribbon.github.io/documentation/interop_with_MahApps.Metro guide, but when displaying a ContextualTabGroup, the Context Header is not visible.

Moreover, when binding the Visibility to property to my ViewModel, I'm not able to show/collapse it. 
It is very frustrating as I have see that I work correctly on your ShowCase application. 

Can you check my repro application on https://github.com/sachabruttin/FluentRibbonTest and tell me why it is not working correctly.

Many thanks in advance.

---
### Environment

- Fluent.Ribbon __v9.0.3__
- Windows __10__
- .NET Framework __6.0__

**Comment by batzen** [comment]
It doesn't work, as far as i can judge from my phone, because your window does not implement IRibbonWindow.

**Comment by sachabruttin** [comment]
Just added the IRibbonWindow interface and know it works perfectly. 

Thanks a lot.
