### ISSUE TITLE
Visual Studio 2022 Designer and Fluent

### ISSUE THREAD

**Issue by langeth** [fluentribbon/Fluent.Ribbon#1006]
Hello, I had change my fluent ribbon project to Visual Studio 2022. It will work fine with Visual Studio 2019. If i open the MainMenue.xaml at Designer in VS 2022 the Ribbon will not show.

![image](https://user-images.githubusercontent.com/20537969/151977148-f612603b-3ee9-4357-8190-af51c8d3f343.png)

Does anybody have any Ideas?

---
Windows 10

- Fluent.Ribbon __v9.0.3__
- Windows __10__
- .NET Framework __4.8__

**Comment by langeth** [comment]
Using <Fluent:Ribbon.ContextualGroups>
            <Fluent:RibbonContextualTabGroup x:Name="TestGroup">
and at Fluent:RibbonTabItem  Group="{Binding Source={x:Reference TestGroup}}"/> will reproduce the problem at a new project at VS 2022

**Comment by batzen** [comment]
The designer in Visual Studio is still horribly broken, even in VS2022.
Trying to open the showcase content in the designer even tells me that TextBox does not have a `IsReadOnly` property...

So there is not much, more like nothing, i can do to fix this.
You should report this to the Visual Studio team, through their feedback function to get it fixed.
Feel free to point them to this repo, and especially the showcase application, when asked for a repro.

**Comment by langeth** [comment]
Hi batzen, i had send feedback to Microsoft.

**Comment by batzen** [comment]
MS claims to have fixed this in the latest VS preview.
