### ISSUE TITLE
Markdown documentation

### ISSUE THREAD

**Issue by petsuter** [fluentribbon/Fluent.Ribbon#101]
Are you interested in contributions to add more documentation to the wiki pages on Github?

I started creating some wiki pages ([Foundation](https://github.com/fluentribbon/Fluent.Ribbon/wiki/Foundation), [Resizing](https://github.com/fluentribbon/Fluent.Ribbon/wiki/Resizing), [Tips](https://github.com/fluentribbon/Fluent.Ribbon/wiki/Tips)), converting content from the PDF walkthrough document.

Next steps would be:
- adding the remaining content (Galleries, Toolbars)
- adding missing screenshots
  - the ones from the walkthrough PDF
  - Office 2013 and Windows 8 theme (main window and backstage)
  - Question: Should they be added to the main repository (like the existing ones)? Or to the wiki repository? (not possible via pull requests)
- document new features
  - I think a link to the wiki documentation for each feature in the [Feature List](https://github.com/fluentribbon/Fluent.Ribbon#feature-list) would be nice.
  - So create these wiki pages (and subsections for each feature):
    - Backstage (& Application Menu)
    - Tabs (& Groups)
    - Controls
    - Quick Access Toolbar
    - Galleries
  - (are there other new features?)

Does that make sense? Or are there already other plans for updating the documentation?

**Comment by batzen** [comment]
My plan for an updated/reworked documentation was to keep it with the source code and not use the wiki. The advantages of that way would be:
- we are not tied to github that much
- it's versionened with the source and can be updated by pull requests

**Comment by batzen** [comment]
I also planned to extend the "how to contribute" section in readme.md and adding a new section "knows issues" somewhere to prevent people from running into known problems/issues which won't or can't be fixed (mostly windchrome related stuff can't be fixed entirely by us).

**Comment by batzen** [comment]
Sorry for the delay, didn't notice you created a PR.

**Comment by batzen** [comment]
The screenshot on https://github.com/fluentribbon/Fluent.Ribbon/blob/master/Doc/RibbonResizing.md is missing.

**Comment by batzen** [comment]
And one screenshot on https://github.com/fluentribbon/Fluent.Ribbon/blob/master/Doc/Screenshots.md is also missing.

**Comment by wstaelens** [comment]
I'm new to Git and the pull request stuff (i'm a TFS user).
but I've started index.md in the Doc section as a starter for documentation.

I follow the simple but very useful documentation structure of caliburn.micro ( http://caliburnmicro.com/documentation/ )

**Comment by batzen** [comment]
Nice that you are interested in helping.
Will comment on your PR.
