### ISSUE TITLE
Ribbon menu not fully displayed after minimized

### ISSUE THREAD

**Issue by leixao** [fluentribbon/Fluent.Ribbon#1014]
After the Ribbon menu is minimized, the right side of the content cannot be covered when the menu is displayed .
Like this:

![image](https://user-images.githubusercontent.com/59323065/156286565-fab515ab-ec79-4e94-ab26-97a340d7c0e9.png)
---
### Environment

- Fluent.Ribbon __v9.0.3__
- Windows __11__
- .NET Core __3.1__

**Comment by batzen** [comment]
I can't reproduce your issue.
Which locale are you using?

**Comment by leixao** [comment]
> I can't reproduce your issue. Which locale are you using?

hi, the OS language is Simplified Chinese(win 11)

**Comment by leixao** [comment]
Could it be due to DPI scaling?
The problem does not reproduce when the system scaling is 100% 
Is this a WPF bug?
But it was normal in old version of Showcase (8.0.3)

**Comment by batzen** [comment]
Argh. This was caused by wrong changes made for #919

**Comment by batzen** [comment]
Will release to nuget later today.
