### ISSUE TITLE
ControlzEx 5 dependency not set for .NET 6

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#1036]
I'm using .NET 6 and it brought in ControlzEx 4.4.0.50. The DLL fails to load for Fluent Ribbon 9.0.4:

> System.IO.FileLoadException: Could not load file or assembly 'ControlzEx, Version=5.0.0.0, Culture=neutral, PublicKeyToken=69f1c32f803d307e'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

I think it's because the NuGet package doesn't have a dependency entry for .NET 6:
![image](https://user-images.githubusercontent.com/9450861/173220958-2a96c77b-1001-4f18-bfb7-9fdfd1ab286f.png)

**Comment by RandomEngy** [comment]
The odd thing is that it gives me the 5.0.1.15 version of ControlzEx.dll in the Debug/Release folder when I build from Visual Studio. But I have a publish profile set up like this where it puts ControlzEx.dll 4.4.0.50 in the publish folder:

![image](https://user-images.githubusercontent.com/9450861/173221387-d21abadf-7a21-433b-8e0d-96e68c522eb6.png)

**Comment by batzen** [comment]
As Fluent.Ribbon itself targets .NET 5 the dependencies are also for .NET 5 and that's totally valid.
The most plausible cause for this is that you have another project that references either a different version of Fluent.Ribbon or ControlzEx.
That's the reason why I switched to central package versions everywhere a long time ago.

**Comment by RandomEngy** [comment]
Yeah, you're right. I just made a brand new project and it picks the right version of the DLL when publishing. Though oddly I don't have references to either Fluent ribbon or ControlzEx in any other project.

**Comment by RandomEngy** [comment]
Central package management didn't fix (but is pretty cool). But deleting the `bin` and `obj` folders did. Guess I should have tried that first, whoops.

**Comment by batzen** [comment]
Ah, yeah. That also bit me some time ago.
Forgot to mention it as i totally forgot about having had that issue.
Glad you solved it.
