### ISSUE TITLE
Non-DWM fullscreen window is not fullscreen

### ISSUE THREAD

**Issue by petsuter** [fluentribbon/Fluent.Ribbon#104]
When Windows is personalized to use a Basic theme (not an Aero theme) Fluent Ribbon applications maximized to fullscreen are not quite fullscreen. One row of pixels at the top seems to be missing. This is quite annoying as the mouse clicks through to applications below the top application, closing or dragging with the mouse positioned at the tope of the screen closes or drags the application below!

**Comment by batzen** [comment]
Details?
Which Ribbon version?
Which Ribbon theme?
Which .NET version?
Which Windows version?

**Comment by petsuter** [comment]
Ribbon 3.4.0
Office 2010 Blue Theme
.NET 4.5.2
Windows 7
