### ISSUE TITLE
MenuItem CreateQuickAccessItem should create ToggleButton

### ISSUE THREAD

**Issue by andersforsgren** [fluentribbon/Fluent.Ribbon#1041]
The Fluent.MenuItem class when there are no child menu items, produces a regular Button as its QuickAccessItem. 

This means the MenuItem.IsChecked is not reflected as the toggle state on the QAT button.

current impl in MenuItem.cs
```csharp
else // no child items 
{
    var button = new Button();
    RibbonControl.BindQuickAccessItem(this, button);
    return button;
}
```

I suggest this should instead return a ToggleButton. The rationale being that a MenuItem, being checkable, is more similar to a ToggleButton than a Button.

So basically instead, this:

 ```csharp
 else // no child items 
 {
     var button = new ToggleButton();
     RibbonControl.Bind(this, button, nameof(this.IsChecked), IsCheckedProperty, BindingMode.TwoWay);
     RibbonControl.BindQuickAccessItem(this, button);
     return button;
 }
```

If this looks reasonable I’m happy to supply a PR 

---
### Environment

- Fluent.Ribbon __v9..0.4__
- Windows __10 21H2__
- .NET Framework __4.8__

**Comment by batzen** [comment]
Actually both would be wrong alone, as the result should depend on the check ability of the menu item. 😉

**Comment by andersforsgren** [comment]
Yes I suppose the correct way would be to make it conditional on IsCheckable and make either a Button or a ToggleButton?

I will give it a try
