### ISSUE TITLE
Black screen with isolated RibbonWindowColorized example

### ISSUE THREAD

**Issue by jensdenbraber** [fluentribbon/Fluent.Ribbon#1050]
**Place your issue description here.**
When I put the "RibbonWindowColorized" from the showcase in a separate project/solution I get a black window. Does someone know what the problem would be?

---
### Environment

- Fluent.Ribbon __v9.0.4__
- Windows __10__
- .NET Framework __.NET 5.0 / .NET 6.0__

**Comment by jensdenbraber** [comment]
@batzen do you have an idea what could cause this? :)

**Comment by batzen** [comment]
Sorry, totally forgot to answer.

I guess you are missing some resource dictionary.
Could you attach your project? That's the easiest way to find the issue.

**Comment by jensdenbraber** [comment]
When I run the application the screen remains black. The project can be found here:

[FluentRibbonSimplifiedRibbonWindowTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/9419583/FluentRibbonSimplifiedRibbonWindowTest.zip)

**Comment by batzen** [comment]
You have to include the XAML resource from Fluent.Ribbon somewhere.
The best place, most of the time, is your `App.xaml`.
Just add:
```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/Fluent;component/Themes/Generic.xaml" />
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

**Comment by jensdenbraber** [comment]
Thanks that did the trick! :D
