### ISSUE TITLE
Adding HwndHost as child of Border causes border area to become transparent

### ISSUE THREAD

**Issue by zachmakesgames** [fluentribbon/Fluent.Ribbon#1054]
Adding an HwndHost as a child to a Border control causes the entire border area to become transparent (i.e. desktop is visible behind the application) and the HwndHost content is not displayed. Adding AllowsTransparency="True" to the window XAML negates the transparent issue but the HwndHost content still is not displayed. Replacing the Fluent:RibbonWindow with a standard Window causes the HwndHost to act as expected and the content is displayed properly so I expect it's a styling issue.

---
### Environment

- Fluent.Ribbon __v9.0.4__
- Windows __10__
- .NET Framework __6.0__

**Comment by batzen** [comment]
Could you attach a sample application?

**Comment by batzen** [comment]
@zachmakesgames Could you attach a sample application?
