### ISSUE TITLE
Issue with MahApps styling + Backstage

### ISSUE THREAD

**Issue by SkinnySackboy** [fluentribbon/Fluent.Ribbon#1059]
Hi,

Firstly, thank you for creating this great project, it's really good.

At the moment we have solved most of our outstanding issues but one. We are trying to theme things programmatically to be in sync with MahApps but have come across an issue. The issue is basically that if we programmatically set a custom accent colour, when opening the Backstage/BackstageTabControl, not all of the styling works (some things are not styles, buttons have no mouse over effect, etc.

Using MahApps, we are doing the following. it works and styles the Fluent.Ribbon correctly.

```csharp
protected override void OnStartup(StartupEventArgs e)
{
    base.OnStartup(e);

    var theme = new Theme("MahAppsRoyalDark", "MahAppsRoyalDark", ThemeManager.BaseColorDark, "Red", Colors.MediumPurple, Brushes.MediumPurple, true, false);
    ThemeManager.Current.ChangeTheme(this, theme);
}
```

The problem we've got is that we do not want to use one of the standard Microsoft colours but wish instead to provide our own.

```csharp
protected override void OnStartup(StartupEventArgs e)
{
    base.OnStartup(e);

    var customColor = new Color
        {
            R = 116,
            G = 70,
            B = 185
        };

    var theme = new Theme("MahAppsRoyalDark", "MahAppsRoyalDark", ThemeManager.BaseColorDark, "Red", customColor, new SolidColorBrush(customColor), true, false);
    ThemeManager.Current.ChangeTheme(this, theme);
}
```

This time this *sort of* works, but the behaviour is a little unexpected, with the styling partially applied (the button mouse hovering etc. does not work as expected). TLDR; if I use a standard Microsoft colour to change the theme accent, all is ok. If I use my own, it isn't.

By any chance have you come across this issue before? Is it something I'm doing incorrectly?

Thanks in advance.

---
### Environment

- Fluent.Ribbon 9.0.4
- Windows 10 21H1
- .NET 6

**Comment by batzen** [comment]
That sounds really strange.
Could you attach a small repro project?

**Comment by SkinnySackboy** [comment]
Certainly, attached. 
[ReprooFluetnRibbon.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/9484663/ReprooFluetnRibbon.zip)

If you open App.xaml.cs there are two colours. If swap between them you can see what I'm saying. When we use the standard Windows colour, both MahApps and Fluent.Ribbon get styled correctly.

If you switch to the custom colour that is not a standard windows colour, only MahApps gets styled correctly (Fluent.Ribbon sort of gets half styled, because the buttons do not get their mouse over effect and the section headers are also not coloured correctly).

Our goal here is to be able to style both MahApps and Fluent.Ribbon programmatically. If you could shed some light as to whether we are doing something wrong or whether it is a bug that needs fixing it would be greatly appreciated.

Thanks again!

**Comment by batzen** [comment]
Well, the color you are supplying is fully transparent. ;-)
Didn't notice this till trying your repro and using Snoop to inspect the border background for the buttons.
That showed a color starting with `#00`.

Certain parts of MahApps would also have shown no color.
Just add `A = 255,` to your color and it works fine.

**Comment by SkinnySackboy** [comment]
Brilliant thanks @batzen it works now!

**Comment by batzen** [comment]
You are welcome.
