### ISSUE TITLE
BackStage should be 1 px higher

### ISSUE THREAD

**Issue by QuantumDeveloper** [fluentribbon/Fluent.Ribbon#106]
![image](https://cloud.githubusercontent.com/assets/6085009/7440924/98a1bcb8-f0d8-11e4-89a8-96fe9ecbdb09.png)

On the image you can see that the bottom part of backstage is 1 px higher than the window.

I think they should be the same:

OS - win 8.1
Theme - office 2013

**Comment by chdft** [comment]
I can reproduce this issue with the FluentTest application. But at least in my own applications, every ribbont window has a status bar which makes this issue invisible/look like a 1px border in accent color. But as far as I can tell, Microsoft Office applications (tested in Outlook, Word, PowerPoint) have this 1px border only when they are not maximized.

**Comment by batzen** [comment]
The problem is not that the backstage has a missing pixel but the window border has the wrong Z-Index.
