### ISSUE TITLE
Question: is it possible to add a watermark to a textfield?

### ISSUE THREAD

**Issue by jensdenbraber** [fluentribbon/Fluent.Ribbon#1063]
**For an application I'm looking for the possibility to add a watermark to a textfield.**

For example something like this: 
![](https://code.4noobz.net/wp-content/uploads/2016/10/watermark.png) 
Here the watermark is "Enter your first name here...".

Unfortunately, the urls _https://fluentribbon.github.io/documentation/controls/_ and _https://fluentribbon.github.io/documentation/controls//textfield_ give a 404 for documentation on the component giving a property overview of some sort.

**Comment by batzen** [comment]
There is currently no built in watermark support in Fluent.Ribbon.
If you need such a feature now you can either use MahApps.Metro and re-style/re-template the TextBox from Fluent.Ribbon or build your own watermark code/triggers and re-style/re-template the TextBox from Fluent.Ribbon.
The template for the TextBox is "only" 81 lines, so it's not that much.
If you decide to re-template you have to keep an eye on the original template in case of updates.

I might add built in watermark support in a later version of Fluent.Ribbon.

May i ask where you got the links from?
The only documentation root that exists is at https://fluentribbon.github.io/documentation/ and there are no 404 links on there.
