### ISSUE TITLE
Fluent.Ribbon tabItem not showing 

### ISSUE THREAD

**Issue by abdou31** [fluentribbon/Fluent.Ribbon#1069]
Hello,

I'm facing a big issue when trying to create a Fluent.Ribbon tabItem , however the window cannot show anything ( not in design mode and not in runtime ) , I'm using Fluent.Ribbon and Mah app Metro libraries.

![image](https://user-images.githubusercontent.com/19480228/193559752-5d2251fe-2d8d-4e08-9872-f0ddd2578b59.png)

this my xaml code:

     <Fluent:Ribbon Grid.Row="1" >
            
            <Fluent:Ribbon.Menu>
                <Fluent:Backstage>
                </Fluent:Backstage>
            </Fluent:Ribbon.Menu>

            
            <Fluent:RibbonTabItem Header="Home" IsOpen="True" IsMinimized="False">
                <Fluent:RibbonGroupBox Header="Group">
                    <Fluent:Button Header="Red" Icon="RibbonMetroTest;component/Images/RedS.png" LargeIcon="RibbonMetroTest;component/Images/RedL.png" />
                    <Fluent:Button Header="Green" Icon="RibbonMetroTest;component/Images/GreenS.png" LargeIcon="RibbonMetroTest;component/Images/GreenL.png" />
                    <Fluent:Button Header="Blue" Icon="RibbonMetroTest;component/Images/BlueS.png" LargeIcon="RibbonMetroTest;component/Images/BlueL.png" />
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
        </Fluent:Ribbon>

---
### Environment

- Fluent.Ribbon __v7.0.0
- Windows 10 x64
- .NET Framework 4.8

**Comment by batzen** [comment]
Did you add the Generic.xaml from Fluent.Ribbon to your App.xaml?

**Comment by abdou31** [comment]
I think that the problem is related to Mah app Metro library, however , it require using a Metro window to display the controls .

**Comment by abdou31** [comment]
What is Generic.xaml ???

**Comment by batzen** [comment]
That's strange.
Could you share your project?

**Comment by abdou31** [comment]
It's not strange because the dll won't be loaded and it shows always an exception of cannot find Fluent

**Comment by batzen** [comment]
It is strange because you didn't mention any exception so far.
Could you share your project or a small repro showing your issue?

**Comment by batzen** [comment]
@abdou31 Could you share your project or a small repro showing your issue?

**Comment by tolgahandikmen** [comment]
Hi, I have very similar problem and I didn’t add the Generic.xaml. Could you explain how to add the Generic.xaml please?

**Comment by batzen** [comment]
@tolgahandikmen it has to be added to your App.xaml like in https://github.com/fluentribbon/Fluent.Ribbon/blob/05b32a4c1ae88f30cc0494754833d6c5855fa406/Fluent.Ribbon.Showcase/App.xaml#L8-L13

**Comment by batzen** [comment]
@abdou31 Did you solve the issue on your own?
