### ISSUE TITLE
Separators no longer shown in Backstage

### ISSUE THREAD

**Issue by MarcelVersteeg** [fluentribbon/Fluent.Ribbon#1070]
I just upgraded Fluent.Ribbon from version 8.0.1 to version 9.0.4. Now my separators are no longer shown in the Backstage and the tab headers are also no longer aligned (they indent further with every separator).

In my XAML I use a styled `System.Windows.Controls.Separator` for the separator. Even if I do not set the `Style` attribute, the separator is not shown and the tab header do not align correctly in version 9.0.4 while it was with version 8.0.1. If I replace the `System.Windows.Controls.Separator` with an unstyled `Fluent.SeparatorTabItem`, the separators do show in the default color and the items correctly align, but I want to give the separators another color. Setting the `Foreground` or `Background` properties of the `SeparatorTabItem` does not work and if apply the style I previously used for the `System.Windows.Controls.Separator` (changing the type to apply it to to `Fluent.SeparatorTabItem`), the separator disappears again and the items are no longer aligned.

How can I change the color of the separator in the backstage?

---
### Environment

- Fluent.Ribbon 9.0.4
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
You can still use a regular `Separator`.
You just have to set `DockPanel.Dock="Top"` on them.

The panel for the backstage was changed to be a `DockPanel` while fixing #936.
I totally forgot to add this to the list of breaking changes, as setting the dock alignment is now mandatory, as the default in WPF is `Left`.

**Comment by MarcelVersteeg** [comment]
That indeed did the trick. Thank you for the quick response!

**Comment by batzen** [comment]
I will change the code to automatically set the default dock value for all items added to the backstage.
That way people don't have to set it, if they want the default layout (top to bottom).
