### ISSUE TITLE
Some of the issues used in.NET 6

### ISSUE THREAD

**Issue by Waiwai-Zhang** [fluentribbon/Fluent.Ribbon#1073]
Hello, when I transferred the project from. NET framework is migrated to. NET 6, the ribbon fails to work properly and shows IsMinimized IsOpen attribute binding failure in RibbonTabItem. How do I solve this?
### Environment

- Fluent.Ribbon __v9.0.4_
- Windows __10__
- .NET __6__

**Comment by batzen** [comment]
Could you create a repro project which showcases your issue?
The showcase application of Fluent.Ribbon works without any issues on .NET 6.

**Comment by batzen** [comment]
Will have a look in about a week as i am on vacation.

**Comment by Waiwai-Zhang** [comment]
Thank you. Have a great holiday!

**Comment by Waiwai-Zhang** [comment]
I have found the problem, which was caused by my carelessness. Thank you very much.
