### ISSUE TITLE
Window Border Issue on Windows 7/8 (only in alpha version)

### ISSUE THREAD

**Issue by andyld97** [fluentribbon/Fluent.Ribbon#1079]
Hi!

I am really a big fan of `Fluent.Ribbon`, because it just looks really nice and I am using it in my app a few years already! 
While I was testing with the alpha version recently, I noticed some weird behaviour with the window border, but I am not sure
if this problem belongs here or if it is related to `ControlzEx`. In my project I am also using `MahApps.Metro`, but it doesn't really matter,
because the same behaviour occurs in the sample app. 

The issue ONLY occurs when using older `Windows`-systems like `Windows 7` and `Windows 8`. Since `Fluent.Ribbon` supports still `.NET 4.6.2`, my guess is that those Windows versions should be still supported, or am I wrong?

So, in the current release the issue don't occur. I just downloaded the showcase-application from current release and also from the latest alpha build and put them togehter (left alpha, right current release):

**Windows 7:**
![Windows 7](https://user-images.githubusercontent.com/10423894/201478819-f69bc9d2-a224-4115-81c4-cab3c2cb1bb3.png)

**Windows 8:**
![Windows 8](https://user-images.githubusercontent.com/10423894/201478822-baaf1896-6782-4a67-8284-6a957c3995a6.png)

So to quickly summerize the behaviour, using Windows 7 or Windows 8 leads to a weird border like you can see in the screenshots (left). And previously there was no such `Windows`-Border, as you can see in the pictures on the right.

---
### Environment

- Tested with Fluent.Ribbon __10.0.0-alpha0196__ and Fluent.Ribbon __10.0.0-alpha0188__
- Windows 7, 8
- .NET Core 5 (but the issue also occurs using .NET 6 and .NET 7)

**Comment by batzen** [comment]
Only OS versions that are still supported by Microsoft are supported by ControlzEx and Fluent.Ribbon, i think the same goes for MahApps.Metro.
So currently that would be Windows 8.1, Windows 10 and Windows 11.

Could you try to set WindowStyle=None?
The default was changed from None to SingleBorderWindow, which might cause issues on older OS versions.

**Comment by andyld97** [comment]
Okay, good to know. But the issue also occurs on Windows 8.1, because I am using Windows 8.1 already (forget to mention that). 
I just tried to set WindowStyle to None, but it's still the same effect ...
