### ISSUE TITLE
Application bar top color and alignment

### ISSUE THREAD

**Issue by MrNorth35** [fluentribbon/Fluent.Ribbon#108]
Hi!

Our customer has special needs for their ribbon app, and I am doing my best to accomplish this. If you look at the attached picture you can see what I am currently struggling with. When the RibbonBar is set to another background color than default, the ApplicationMenu looks really strange. I expected the top right white rectangle to use the same color as the ribbon bar, because it 's purpose as I understand it is to cover the ribbon tabs. Do I have to derive a custom control template for this as well? 

Also, there seems to be an alignment problem, because it should align perfectly with the ribbon bar, but looks when running it 1 or 2 pixels far down. If I somehow can change the top rectangle to blue, it will not align properly with the blue ribbon background, and will look strange as well.

![visual_bug](https://cloud.githubusercontent.com/assets/12223736/7451564/67ea044c-f252-11e4-8ba7-6c7a0d10830f.png)

**Comment by chdft** [comment]
I think the difference in color is the intended behavior. 
Other applications by Microsoft that use application menus (i.e. explorer in Windows 8.1) use the application menus background color (#F6F7F8) rather than the ribbons background color (#FFFFFF) for that rectangle.
The gray line in the application menu should line up with the border of the tabs in the ribbon bar (it does that in FluentTest and Windows explorer), but the ribbon tabs in your application seem to have no border at all.
Could it be, that you haven't added any tabs to your ribbon yet?

**Comment by batzen** [comment]
To change the color of that rectangle you have to overwrite "RibbonBackgoundBrush" at least in the scope of the ApplicationMenu like so
```
<Fluent:ApplicationMenu.Resources>
	<SolidColorBrush x:Key="RibbonBackgoundBrush" Color="Red"/>
</Fluent:ApplicationMenu.Resources>
```

**Comment by batzen** [comment]
Will have to have a look at the alignment.

**Comment by MrNorth35** [comment]
Thank you for the quick and detailed answers! My team feels this control is of extremly high quality and it is well suited to our needs in terms of functionality, which we have already implemented. There are just some minor issues with styling we are trying to pick off one by one. 

I changed the RibbonBackgroundBrush as recommented, and it worked great, however it did produce some nasty side effects that is illustrated in the picture.

![border_issue](https://cloud.githubusercontent.com/assets/12223736/7467891/c55073be-f301-11e4-85b2-53aaa9e54922.png)

**Comment by batzen** [comment]
That border color can be changed by overwriting "ContextMenuBarBorderBrush" but that will probably cause side effects on other controls contained in the menu.
The only real way to change this without side effects and without overwriting the template would be to introduce a new property like "PopupBorderBrush".

Feel free to implement such a property, change all themes accordingly and send me a pull request.

**Comment by RedshirtMB** [comment]
> To change the color of that rectangle you have to overwrite "RibbonBackgoundBrush" at least in the > scope of the ApplicationMenu like so

I hate to ask here because I know it's an inappropriate use of the issue tracker but... Is there a list anywhere of what resources are linked to what controls. I'm especially interested in changing the StatusBar color and the color used for the highlight of a checked ToggleButton.

**Comment by batzen** [comment]
The best lists I can offer are the xaml files. There is no dedicated separated list which lists what you want.

**Comment by batzen** [comment]
Any news on this one?

**Comment by batzen** [comment]
Any news?

**Comment by batzen** [comment]
Any news?
