### ISSUE TITLE
Menu items not showing when open second RibbonWindow on different screen with different DPI

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#1090]
### Discussed in https://github.com/fluentribbon/Fluent.Ribbon/discussions/1089

<div type='discussions-op-text'>

<sup>Originally posted by **kezara** December 14, 2022</sup>
Hello,
I've created Ribbon menu as a UserControl with IsMinimized = true, which bindes to main window view model property. Main window view is RibbonWindow, and it works like a charm, until when on secondary display I open another RibbonWindow which does not have Ribbon menu at all. When second RibbonWindow is opened and maximized clicking on Ribbon menu header expands ribbon but doesn't show menu items. When second RibbonWindow is minimized everything's working fine, and clicking on header expands ribbon and menu items are visible and functional.
Is it possible that we can't have two RibbonWindows, where one window has ribbon menu and other does not have it, opened at the same time, or I'm doing something really wrong.</div>

**Comment by batzen** [comment]
@kezara
After some investigation i think it might be a bug in WPF or Windows as the Popup partially receives different DPI information than it should and that seems to be caused if the secondary window has it's X position at the exact edge of the first monitor.
Using `SecondaryStartLocation = SystemParameters.PrimaryScreenWidth + 1;` in your code prevents that issue.

After some more investigation it's really caused by a bug in WPF/Windows.
You can either use the workaround i posted above or you can declare your application as per monitor DPI aware.
The bug in WPF/Windows only happens if your application is not declared as per monitor DPI aware.

I am still very surprised that this is not done by the default WPF application template...

To declare your application as per monitor DPI aware add `<ApplicationManifest>app.manifest</ApplicationManifest>` to any property group in your csproj file.
The content of the `app.manifest` should be something like
```
<?xml version="1.0" encoding="utf-8"?>
<asmv1:assembly manifestVersion="1.0"
                xmlns="urn:schemas-microsoft-com:asm.v1"
                xmlns:asmv1="urn:schemas-microsoft-com:asm.v1"
                xmlns:asmv2="urn:schemas-microsoft-com:asm.v2"
                xmlns:asmv3="urn:schemas-microsoft-com:asm.v3"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <assemblyIdentity version="1.0.0.0"
                      name="My application"/>
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
        <security>
            <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
                <requestedExecutionLevel level="asInvoker"
                                         uiAccess="false" />
            </requestedPrivileges>
        </security>
    </trustInfo>

    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
        <application>
            <!-- A list of all Windows versions that this application is designed to work with. Windows will automatically select the most compatible environment.-->
            <!--The ID below indicates application support for Windows Vista -->
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
            <!--The ID below indicates application support for Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <!--The ID below indicates application support for Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
            <!--The ID below indicates application support for Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!--The ID below indicates application support for Windows 10 -->
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
        </application>
    </compatibility>

    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings>
            <!-- Per Monitor V1 [OS >= Windows 8.1] Values: False, True, Per-monitor, True/PM -->
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True/PM</dpiAware>
            <!-- Per Monitor V1 [OS >= Windows 10 Anniversary Update (1607, 10.0.14393, Redstone 1)] Values: Unaware, System, PerMonitor -->
            <!-- Per Monitor V2 [OS >= Windows 10 Creators Update (1703, 10.0.15063, Redstone 2)] Value: PerMonitorV2 -->
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor, System</dpiAwareness>
            <!-- If you want to see Windows crash with a kernel error trap, enable gdiScaling -->
            <!--<gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>-->
        </windowsSettings>
    </application>

    <!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->
    <dependency>
        <dependentAssembly>
            <assemblyIdentity
                type="win32"
                name="Microsoft.Windows.Common-Controls"
                version="6.0.0.0"
                processorArchitecture="*"
                publicKeyToken="6595b64144ccf1df"
                language="*" />
        </dependentAssembly>
    </dependency>
</asmv1:assembly>
```

**Comment by kezara** [comment]
@batzen 
Thanks for your time and effort, app.manifest indeed solves the issue.
