### ISSUE TITLE
BackstageTabItem tooltip shows on content hover

### ISSUE THREAD

**Issue by cbra-caa** [fluentribbon/Fluent.Ribbon#1096]
When adding a tooltip to a BackstageTabItem, the tooltip will show when hovering the mouse over the items content. Expected to only show when hovering the 'button' part. You can assign the issue to me.

Example:
![BackstageTabItemToolTip](https://user-images.githubusercontent.com/47817657/211764185-4cfd54b9-19ae-4f6d-a9b4-0eb1a7611a25.gif)

---
### Environment

- Fluent.Ribbon: 9.4
- Windows: Version	10.0.19044 Build 19044
- .NET Framework

**Comment by batzen** [comment]
Fixed by merging.
