### ISSUE TITLE
DropDownButton closes for no reason (only for one end user)

### ISSUE THREAD

**Issue by DaveInCaz** [fluentribbon/Fluent.Ribbon#1100]
One of my end users has reported a strange problem that I can't reproduce, so I thought I'd post here just in case anyone has seen this before and can offer advice.

My application has several Fluent:DropDownButton controls on a ribbon. For this one user, all have the same problem which is that _the dropdown portion closes before they can click on it_. Apparently just moving the mouse into the dropdown region causes this to happen.

It consistently occurs, even if the window is closed & reopened, or even the entire application. The user says he has tried on the touchpad, touch screen, and the mouse.  All have the same behavior, so it doesn't seem like a hardware glitch.

There is no code related to these controls handling mouse events at all. And there are apparently no other users having this same problem. Other similar controls like standard Win32 menus do not reproduce the same thing.

Any suggestions would be very helpful! Thanks

---
### Environment

- Fluent.Ribbon v9.0.4
- Windows __10__ (guess)
- .NET Framework __4.8__

**Comment by batzen** [comment]
That sounds really strange.

Any chance you can debug on the users machine?
If debugging is not possible the only thing that could help is add tracing code to a custom build of Fluent.Ribbon and log when `OnIsDropDownOpenChanged` is called with `false`. The log should of course include the current stacktrace to narrow down what causes to popup to be closed.

**Comment by DaveInCaz** [comment]
Sorry I had not replied. We never got an opportunity to access the end user PC. If this ever comes up again I'll do my best to get that kind of access & info!
