### ISSUE TITLE
disable ribbon display option

### ISSUE THREAD

**Issue by sami-soft** [fluentribbon/Fluent.Ribbon#1106]
![000](https://user-images.githubusercontent.com/37217976/219118621-e9fb5d47-a76b-4a48-8614-95207fa2e486.jpg)
How do I disable this disable ribbon display option?

**Comment by batzen** [comment]
Which option do you mean?

If you want to hide the display options button you can set `IsDisplayOptionsButtonVisible` on your ribbon to `false`.

**Comment by sami-soft** [comment]
> Which option do you mean?
> 
> If you want to hide the display options button you can set `IsDisplayOptionsButtonVisible` on your ribbon to `false`.

IsDisplayOptionsButtonVisible  was not found in property ribbon !!!

**Comment by batzen** [comment]
Which option do you mean?

Which version are you using?

**Comment by sami-soft** [comment]
> Which option do you mean?
> 
> Which version are you using?

last version : 9.0.4

i will set IsDisplayOptionsButtonVisible to false but not found !

 <Fluent:RibbonWindow x:Class="form_1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
 `       xmlns:d="http://schemas.microsoft.com/expression/blend/2008"`
 `       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"`
 `       xmlns:Fluent="urn:fluent-ribbon"`
 `       xmlns:mscorlib="clr-namespace:System;assembly=mscorlib"`
 `       xmlns:local="clr-namespace:form_1"`
 `       mc:Ignorable="d"`
 `       WindowState="Maximized"`
`        WindowStartupLocation="CenterScreen"    `
`        ResizeMode="CanMinimize"  `
`        Title="form_1" FontFamily="vazir"  Height="450" Width="800" Closing="Window_Closing" Loaded="Window_Loaded">`
`    <DockPanel>        `
 `       <Grid>`
`            <Fluent:Ribbon IsDisplayOptionsButtonVisible="false" > `
`          //tabs	`	  
`        </Fluent:Ribbon> `
 `       </Grid>      ` 
 `   </DockPanel>`
`</Fluent:RibbonWindow>`

**Comment by batzen** [comment]
That's because that property was introduced in version 10 and is not available in version 9.
