### ISSUE TITLE
Child sizes are not updated when user switches between Classic/Simplified Ribbon while Ribbon is minimized

### ISSUE THREAD

**Issue by yassinMi** [fluentribbon/Fluent.Ribbon#1107]
if i do the following:
- Minimize the Ribbon
- Toggle Simplified/Classic layout to the opposite state
- Maximize the Ribbon again

the RibbonGroupBoxs and their ancestors appear with the correct new size but the child items (in my case buttons) don't.

![image](https://user-images.githubusercontent.com/40385634/219112261-0e5c1966-4f63-437b-b581-aa2f43573824.png)

---
### Environment

- Fluent.Ribbon __v9.0.4__
- .NET Framework __4.6__

**Comment by batzen** [comment]
@nishy2000
