### ISSUE TITLE
Rounded corners are missing in recent alpha builds

### ISSUE THREAD

**Issue by andyld97** [fluentribbon/Fluent.Ribbon#1111]
Hi,

recently I kept upgrading the nuget packages for my app since I am using the alpha versions anyway, but my `RibbonWindow` has no more rounded corners (setting `CornerPreference="Round"` helps neither).
I know that it worked with the following versions:
- Fluent.Ribbon 10.0.0-alpha0197
- MahApps.Metro 3.0.0-alpha0414

If I am switching back to **both** "old" versions, my rounded corners are back.

How it looks currently:
![grafik](https://user-images.githubusercontent.com/10423894/222958164-fe3c7319-14de-4234-af08-0424a93f2bb7.png)

---
### Environment

- Fluent.Ribbon 10.0.0-alpha0250
- MahApps.Metro 3.0.0-alpha0453
- Windows 11 Insider Preview (Build: 25300.1000/25309.1000) and Windows 11 Home 22H2 (no Insider Preview)
- .NET Core 7.0.3

**Comment by batzen** [comment]
Can't reproduce using the current dev version.
Just published a new preview (10.0.0-alpha0256).
Could you try that one?

**Comment by batzen** [comment]
Ah, just notice that you already used the version from the appveyor feed.
Could you have a look at which ControlzEx version got resolved in your case?
I published a new preview of that to nuget a few minutes ago.

**Comment by andyld97** [comment]
I just tested `Fluent.Ribbon.Showcase-v10.0.0-alpha0256` and there are rounded corners. 
The version of ControlzEx is 6.0.0.272.

I think I have a clue, I compared the ShowCase `MainWindow.xaml` with mine and I noticed that I had set `WindowStyle="None"` due to the last issue with the window border. If I am removing it, my rounded corners are back. So I guess it's related to the WindowStyle (None).

**Comment by batzen** [comment]
WindowStyle = None means, no native window border.
If you still want to have a border you'll have to use the glow border.
Just set `PreferDWMBorderColor="False"` and `CornerPreference="DoNotRound"`.
The glow border does not support rounded corners.

**Comment by andyld97** [comment]
Thank you for claryfing this, so removing `WindowStyle="None"` works just fine for me!
