### ISSUE TITLE
Is it possible to access ResizeableContentControl from another assembly?

### ISSUE THREAD

**Issue by ychumpov** [fluentribbon/Fluent.Ribbon#1124]
I'm trying to make my own style for the SplitButton based on default SplitButton style. However it looks like ResizeableContentControl  which is part of the default SplitButton style is not accessible from outside.

### Environment

- Fluent.Ribbon __9.0.4__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
`ResizeableContentControl` was introduced in version 10, so it's not available in version 9.
I am currently struggling to find time to finish version 10, but you can already use the preview version.

**Comment by ychumpov** [comment]
Thanks! In preview version it is OK.
