### ISSUE TITLE
Ribbon starts with no active tab selected

### ISSUE THREAD

**Issue by IdanBismut** [fluentribbon/Fluent.Ribbon#113]
I'm using Fluent version 3.4.0 on VS2012 & .NET framework 4.

I have ribbon with empty backstage (so far) & 3 tabs.
Even though the designer loads it's OK (shows "tab1"),
when the GUI runs, there is no active tab selected !

I've tried to set on XAML the "IsSelected" property on the first tab, but that did not solve it.

I've placed on the app.xaml.cs inside OnStartup() function a line that "toggles" this, by doing:
app.ribbonTab.SelectedTabIndex = 1;
app.ribbonTab.SelectedTabIndex = 0;

That seemed to solve it only to find out caused another deeper bug - 
now eventhough the firts tab is selected, no event are fired at all, till I select different tab & re-select back the first tab.

The mainWindow xaml code looks as follows:

[CODE]
<Fluent:Ribbon x:Name="ribbonTab" Grid.Row="0" Grid.ColumnSpan="2" Height="143" SelectedTabIndex="0">

            
            <Fluent:Ribbon.Menu>
                <Fluent:Backstage>
                </Fluent:Backstage>
            </Fluent:Ribbon.Menu>

<Fluent:RibbonTabItem Header="tab1" IsSelected="True">

// ... trimmed for clearity of question

 </Fluent:RibbonTabItem>

<Fluent:RibbonTabItem Header="tab2">

// ... trimmed for clearity of question

 </Fluent:RibbonTabItem>

<Fluent:RibbonTabItem Header="tab3">

// ... trimmed for clearity of question

 </Fluent:RibbonTabItem>

</Fluent:Ribbon>
[/CODE]

Any ideas ??

regards,
Idan

**Comment by batzen** [comment]
It works perfectly in the showcase application and in my own applications.
Would you mind posting a repro?

**Comment by IdanBismut** [comment]
Yes I can.
I'm sorry took me a while to respond back - I was away on vacation :)
I've uploaded to my google drive ZIP file with entire solution.
The IDE used to create it was VS2013.
https://drive.google.com/file/d/0B-3bSyUf3WULT0hEd3MtTUM3WTA/view?usp=sharing

Notice when running GUI.exe (or either doing F5 from within visual studio),
window loads, but no active tab is selected, unless we hover with mouse over the tab & then it's shown...

Setting IsSelected="true" does not work either...

Would appreciate if you can tell me what i'm doing wrong that cause this "bug"/"feature".

Thanks.

**Comment by PaleyX** [comment]
I have the same problem. No button icons show in the designer and when run no tab is selected unless I hover the mouse over a tab or resize the window etc

**Comment by batzen** [comment]
This only happens when using the office 2010 theme.
The short time workaround would be to switch to the office 2013 theme by replacing
```
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
```
with
```
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
```

**Comment by PaleyX** [comment]
same here

**Comment by batzen** [comment]
This issue is related to state loading and the weird mechanism behind it.
Will have to refactor state loading.

**Comment by dalpert-korewireless** [comment]
this is happening for me also in one app but not another, and using the 2013 theme does not impact it. still looking into differences between the one where it works and the one where it does not.

**Comment by dalpert-korewireless** [comment]
so I realized that this was working properly when I navigated from `app.xaml` to `mainview.xaml` by setting the `StartUpUri` in `app.xaml`:
````
<Application x:Class="MyApp.Desktop.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="Screens/MainWindow.xaml">
    <Application.Resources>
        <!--Attach Default Fluent Control's Theme-->
        <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
    </Application.Resources>
</Application>
````

When I removed the `StartupUri` attribute:
````
<Application x:Class="MyApp.DesktopClient.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             >
    <Application.Resources>
        <!--Attach Default Fluent Control's Theme-->
        <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
    </Application.Resources>
</Application>
````

and showed my main view in the `App` constructor
````
    public partial class App : Application
    {
        public App()
        {
            var bootstrapper = new AppBootstrapper();
            bootstrapper.Bootstrap();
        }
    }
````

then no tabs showed as open on startup.

Moving that `MainWindow.Show()` command from the `App` constructor to the `OnStartup` method made it work properly again:

````
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            var bootstrapper = new AppBootstrapper();
            bootstrapper.Bootstrap();
        }
    }
````

**Comment by batzen** [comment]
My guess, without testing, is that the resources are not fully loaded when you create your window in the apps constructor resulting in some things not working as expected.
