### ISSUE TITLE
Selected Tab on first render has a black border

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#1134]
Not sure if this counts as bug or feature, but the first impression is "weird". When you create a RibbonWindow with a selected tab, a black border appears around it:

![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/756703/581486c4-8e35-4051-abd8-e2facb7f9bd7)

To reproduce just press this button in your sample app:
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/756703/be3352a8-b063-446a-bee0-dc3e77085f99)

IMHO the black border makes sense for keyboard navigation (accessibility...), but in this case no keyboard navigation has happend and the ribbon is clearly selected anyway.
After clicking around the border disappears.

---
### Environment

- Fluent.Ribbon __v10__
- Windows __11__
- .NET Framework __4.8__

**Comment by Mark-yunshengLiu** [comment]
RibbonTabItem  set  Focusable = "False" , 

<Fluent:RibbonTabItem Header="home" Focusable="False">
