### ISSUE TITLE
Is it possible to show special keys titles in Menu Item?

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#114]
Is it possible to show special keys titles in Menu Items (marked in red) with Fluent Ribbon? 
http://s11.postimg.org/wv1t8m7ir/Show_Special_Keys.png

If not.. how I can achieve that, what easiest way? 

Thanks for any help.

**Comment by batzen** [comment]
There is no built in way to show attached shortcut keys.
The easiest way to show those would most probably be to include the text in the header of your buttons.

**Comment by Drasius2** [comment]
I created simple how to feature request. Add this feature by editing existing template:
https://github.com/fluentribbon/Fluent.Ribbon/issues/120
