### ISSUE TITLE
Rounded corners toolbar and tab item style change

### ISSUE THREAD

**Issue by kevwkev** [fluentribbon/Fluent.Ribbon#1140]
Hi @batzen I would like to know if it's possible to customize the current theme template in order to achieve two changes: making the toolbar background have rounded corners and the tab item background to have an underline, similar to the example displayed in the screenshot. Thank you in advance for your assistance.

![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/1664903/7a2fb4bd-a257-4346-84c0-0e54a0b64c0d)

**Comment by batzen** [comment]
It's possible, but I haven't yet decided if I should follow that rounded/non-rounded rabbit hole again.
Microsoft changes their mind every few years if things should be rounded or not, keeping up with that and changing the layout every time they change their mind requires a lot of work every single time.

Maintaining different styles/templates for rounded/non-rounded looks is completely off the table, as that requires even more maintenance and the community here decided it's better if i spend my time on more important stuff than maintaining different stylings.

This was all discussed in #957 and some todos were noted in https://github.com/fluentribbon/Fluent.Ribbon/issues/957#issuecomment-1143773848

**Comment by kevwkev** [comment]
> It's possible, but I haven't yet decided if I should follow that rounded/non-rounded rabbit hole again.
> 
> Microsoft changes their mind every few years if things should be rounded or not, keeping up with that and changing the layout every time they change their mind requires a lot of work every single time.
> 
> 
> 
> Maintaining different styles/templates for rounded/non-rounded looks is completely off the table, as that requires even more maintenance and the community here decided it's better if i spend my time on more important stuff than maintaining different stylings.
> 
> 
> 
> This was all discussed in #957 and some todos were noted in https://github.com/fluentribbon/Fluent.Ribbon/issues/957#issuecomment-1143773848

Thank you for your response! I'm glad to hear that it's possible to incorporate these UI changes with the library. I agree that Microsoft has been inconsistent with their UI design in the past. However, it's promising to see the modernization of core apps in Windows 11, such as Explorer, Notepad, and Paint, with the new toolbar/ribbon and rounded corners. It seems they have settled on the UI look for at least a few years and have fully embraced the rounded corners.

I personally believe it would be exciting to provide a fresh style for this library. Most licensed UI libraries such as Syncfusion, DevExpress, Telerik, ComponentSource have been offering the latest Office style as an option for the Ribbon control, so having a new approach for this one and only open source project would be attractive for many. The Fluent Ribbon project, in particular, is a wonderful initiative. I genuinely hope you will reconsider the idea of giving it a fresh look or at least allowing customization options like rounded corners for the ribbon tab background, adjustable button margins, or different styles for tab items with underlines. Another option could be to create a community vote to gather opinions.

Thank you once again for your exceptional work!

**Comment by batzen** [comment]
Closing this in favor of #957 

@kevwkev Sad you deleted your last comment. It had quite a few valid points.

**Comment by kevwkev** [comment]
> Closing this in favor of #957 
> 
> 
> 
> @kevwkev Sad you deleted your last comment. It had quite a few valid points.

Just saw your latest update in #957, it looks really great! 
Weird, I didn't delete my previous comment, I can still see it from my end. Thanks again!

**Comment by batzen** [comment]
Strange. Now your comment that seemed deleted shows up...
