### ISSUE TITLE
The ribbon tab header's border is lost after opening the backstage

### ISSUE THREAD

**Issue by vmarinov32** [fluentribbon/Fluent.Ribbon#1144]
The thin black stroke of the ribbon header gets lost after opening the backstage (File button)

Before opening the backstage
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/76511906/3cb609e4-1f46-40dd-a68b-03e26f810c0b)

After opening the backstage
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/76511906/12994c7b-c567-4e6e-b20e-8013dd325bea)

### Environment
- Fluent.Ribbon _v10.0.0
- Windows 10 Pro 22H2 Build 19045.3086
- .NET 6.0

**Comment by batzen** [comment]
That's the keyboard focus border.
When opening the backstage it takes the keyboard focus, but doesn't restore it to the previous focused control when being closed.

**Comment by vmarinov32** [comment]
Yeah, I noticed it re-appears when I hold "Alt". 
Is there a way to make the selected tab always have this border even if it doesn't have keyboard focus?
It is very appealing visually and makes the selected tab pop out, currently it's hard to tell which is the selected tab,
which is maybe my fault - should have styled it better.

**Comment by batzen** [comment]
> Is there a way to make the selected tab always have this border even if it doesn't have keyboard focus?

You could provide your own style, but that, most likely, requires work on your side when updating etc..

The visual appearance of selected tabs will, most likely, change with version 11.
To get an idea of what it will look like you can have a look at https://github.com/fluentribbon/Fluent.Ribbon/issues/957#issuecomment-1594494175
