### ISSUE TITLE
when mouse move in right pane, the  submenus disappear

### ISSUE THREAD

**Issue by befreeH** [fluentribbon/Fluent.Ribbon#1147]
**Place your issue description here.**
hello I write a xaml file like this 

                 <Fluent:ApplicationMenu Header="File" Size="Middle" >
                    <Fluent:MenuItem Header="New" Icon="WpfAppFluentTest;component/Resources/New.png" Size="Middle" >
                        <Fluent:MenuItem Header="Pump" />
                        <Fluent:MenuItem Header="Fan"/>
                    </Fluent:MenuItem>
              </Fluent:ApplicationMenu>

  when my mouse move in the New menu the submenus appear, but when mouse move in right pane, the  submenus disappear.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/138503351/44502756-03a2-4be1-bb6f-b65e65e61286)
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/138503351/78b6c14a-2ef1-4762-89c4-220fb3c7046f)

 Any help would be greatly appreciated！
**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon v10.0.0
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
I can't reproduce your issue on my machine.
Could you provide a repro project?

**Comment by befreeH** [comment]
来信已收到！

**Comment by befreeH** [comment]
来信已收到！
