### ISSUE TITLE
Fluent Ribbon Window with round corners

### ISSUE THREAD

**Issue by chayaw** [fluentribbon/Fluent.Ribbon#1148]
I want to use Floent RibbonWindow, with round corners (like windows 11).
I tried to set CornerPreference = Round, but it is not working.\also in ShowCase i cannot see it work.

---
### Environment

- Fluent.Ribbon __v10.0
- Windows10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Rounded corners are only supported on Windows 11, but not Windows 10 as the feature relies on support for this in the operating system itself.
