### ISSUE TITLE
Simple App in Powershell

### ISSUE THREAD

**Issue by oliwex** [fluentribbon/Fluent.Ribbon#1149]
Hi,

i am a PowerShell developer and for my day to day tasks i develop scripts for automating. Lastly i have a task to create app for my coworkers to automate their and i want to use Fluent.Ribbon.
The problem is i do not have enough experience to use Fluent.Ribbon in PowerShell.(Just learning). 
Could you please create sample PowerShell app with all Fluent.Ribbon functionalities to demonstrate power of Fluent.Ribbon i PowerShell?
---
### Environment

- Fluent.Ribbon [last version]
- Windows 7 to 11
- .NET Framework 4 to 8(last .NET version)

**Comment by batzen** [comment]
I won't write a sample PowerShell app as I don't use Fluent.Ribbon there.

There are quite a lot of samples showing how to do this with MahApps.Metro and as it's not that different, regarding the initial setup etc., you could take those as a starting point for writing scripts that use Fluent.Ribbon.
I hope this helps.

**Comment by oliwex** [comment]
Nope. That not helps. Many of WPFlibraries has PowerShell samples, so i thnk it will be perfect to do the example, but if you do not know how to use own product with PowerShell then i must try it on my own by trying and maybe the script will work.
