### ISSUE TITLE
MenuItem: IsSplited="True" gray line issue

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#115]
Hello. I created MenuItem with atribute IsSplited="True". The main button is fine, but in sub menu there is gray line. And menu icons has to be big. How I can remove/hide this line in sub menu?

![issplited gray line issue](https://cloud.githubusercontent.com/assets/3475668/7744417/e7817820-ff9a-11e4-955e-c96f2486b669.png)

**Comment by batzen** [comment]
Will have a look at this next week.

**Comment by Drasius2** [comment]
My XML code:

     <fluent:MenuItem x:Name="SaveAsDocumentButton"
                                 Command="ApplicationCommands.SaveAs"
                                 Header="{Binding RelativeSource={RelativeSource Self}, Path=Command.Text}"
                                   Icon="/Arieso.Gui.Wpf.Resources;Component/Images/SaveAsDocument_32x32.png"
                                 IsSplited="true">
                        <StackPanel >
                            <TextBlock Text="Save a copy of the document" Padding="8,4" Background="Gainsboro" FontWeight="Bold"></TextBlock>
                            <fluent:MenuItem Header="Document" Description="The default file format."                                              
                                             Command="ApplicationCommands.SaveAs" CommandParameter="Document"
                                             ToolTip="{x:Null}"
                                             Size="Large"
                                             Icon="Images/GeoDocument32.png" />

                            <fluent:MenuItem Header="Template" Description="A template that can be used to format future documents." 
                                             SnapsToDevicePixels="True"
                                             Command="ApplicationCommands.SaveAs" CommandParameter="Template"
                                             Icon="Images/GeoTemplate32.png" />

                            <fluent:MenuItem Header="Report" Description="A read-only report when you want to publish results." 
                                             SnapsToDevicePixels="True"
                                             Command="ApplicationCommands.SaveAs" CommandParameter="Report"
                                             Icon="Images/GeoReport32.png" />
                        </StackPanel>
                    </fluent:MenuItem>

**Comment by Drasius2** [comment]
This line is in SplitedApplicationMenuItemTemplate template, commenting  "<Path Fill="{x:Null}" ..." node solves the problem, the line is not shown.


    <ControlTemplate x:Key="SplitedApplicationMenuItemTemplate"
                     TargetType="{x:Type fluent:MenuItem}">
    ...
        <Popup x:Name="PART_Popup"
    ...
            <Path Fill="{x:Null}"
                                      Stretch="Fill"
                                      Stroke="#FFE2E4E7"
                                      HorizontalAlignment="Left"
                                      Margin="24,0,0,0"
                                      Width="1"
                                      Height="Auto"
                                      Data="M0,0L0,1"
                                      Grid.RowSpan="2"
                                      Visibility="Visible" />

**Comment by batzen** [comment]
Could you create a PR for this fix?

**Comment by Drasius2** [comment]
Created. It is my first time (with Git Hub...), so I hope everything done right.
