### ISSUE TITLE
ComboBox Popup MinWidth too large

### ISSUE THREAD

**Issue by matteoaldera** [fluentribbon/Fluent.Ribbon#1151]
Upgrading from _v9.0.4_ to _v10.0.0_ the property `InputWidth` is missing from `Fluent.Spinner` and `Fluent.ComboBox`.
_XLS0413	The property 'InputWidth' was not found in type 'Spinner'_
_XLS0413	The property 'InputWidth' was not found in type 'ComboBox'_

I don't see anything about this break change in the changelog. I've missing somethings?

Thansk a lot!

---
### Environment

- Fluent.Ribbon __v10.0.0__
- Windows 10
- .NET 6__

**Comment by matteoaldera** [comment]
Thanks! I've fixed my code but there is a problem...

This is what i get with _v9.0.4_
![9 0 4](https://github.com/fluentribbon/Fluent.Ribbon/assets/57939178/45e0acd5-5d86-4dc9-8da4-5a4ec41b8c21)

And this with _v10.0.0_
![10 0 0](https://github.com/fluentribbon/Fluent.Ribbon/assets/57939178/b38f650b-9d54-47be-9755-3adfec5750e5)
Rewriting the value in debug to fire a hot reload fix this issue.

**Comment by batzen** [comment]
That looks strange.
Could you provide a repro for that?

**Comment by matteoaldera** [comment]
What informations do you need?

**Comment by batzen** [comment]
The XAML code you used for the problematic ribbon button in your screenshot or a small project containing everything needed to reproduce the issue.

**Comment by matteoaldera** [comment]
This is the code of my `RibbonTabItem`. I omitted some groupboxes but mentioned them because they are used in `ReduceOrder`.
```xaml
<fluent:RibbonTabItem Header="{DynamicResource Lang.Ribbon.Home}" Name="homeRibbon" ReduceOrder="GroupBox1,GroupBox1,GroupBox1,
                             GroupBox2,GroupBox2,GroupBox2,
                             GroupBox3,GroupBox3,GroupBox3,
                             GroupBox4,GroupBox4,GroupBox4,
                             Miscellaneous,Miscellaneous,Miscellaneous">
   <fluent:RibbonGroupBox Name="Miscellaneous" Header="{DynamicResource Lang.Miscellaneous}" IsLauncherVisible="True" LauncherCommand="{Binding ShowMiscellaneousPanelCommand}">
      <!-- GroupBox1-->
      <!-- GroupBox2-->
      <!-- GroupBox3-->
      <!-- GroupBox4-->
      <!-- Miscellaneous -->
      <fluent:RibbonGroupBox Name="Miscellaneous" Header="{DynamicResource Lang.Miscellaneous}" IsLauncherVisible="True" LauncherCommand="{Binding ShowMiscellaneousPanelCommand}">
         <fluent:ComboBox fluent:InputControlProperties.InputWidth="110" Header="{DynamicResource Lang.Purge}" ItemsSource="{Binding VM.PurgeMode}" SelectedItem="{Binding VM.PurgeMode}" IsEditable="False" ItemTemplate="{StaticResource TranslatedEnumComboBox}" SizeDefinition="Large"/>
         <fluent:ComboBox fluent:InputControlProperties.InputWidth="110" IsEditable="false" Header="{DynamicResource Lang.Speed}" ItemsSource="{Binding VM.PrinterSpeeds}" SelectedItem="{Binding VM.PrinterSpeed}" ItemTemplate="{StaticResource TranslatedEnumComboBox}" SizeDefinition="Large" />
   </fluent:RibbonGroupBox>
</fluent:RibbonTabItem>
```
