### ISSUE TITLE
MenuItem: When the description is long the MenuItem does not expands in Width or Height, does not wrap text

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#116]
MenuItem: When the description is long the MenuItem does not expands in Width or Height, does not wrap text.
See image:
![description issue cut off](https://cloud.githubusercontent.com/assets/3475668/7744958/5c3a4d32-ff9f-11e4-97e0-7a55111e392a.png)

**Comment by Drasius2** [comment]
For first problem I found that you can insert in text "&#10;" and this will place text to next row. But that still  leaves the problem "2"

**Comment by batzen** [comment]
Will have a look at this next week.

**Comment by Drasius2** [comment]
Another way to "fix" (avoid) this problem is increasing width of  Application Menu item:

       <fluent:ApplicationMenu  RightPaneWidth="480">
