### ISSUE TITLE
RibbonBackButton - Localization Mix

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#1161]
The "BackButton" on the Backstage has a flaw, that it mixes languages and the localization is "not ideal".

This button here:
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/756703/8e239e25-7c79-45f1-b55b-005f9e561f92) 
... work with a screenreader since [this change](https://github.com/fluentribbon/Fluent.Ribbon/issues/1125). 

Unfortunately the German translation is "not ideal", because of the Wording "Backstage schließen".
"Backstage" itself is used by Microsoft even in German support sites, but our accessibility tester doesn't allow this, because NVDA, Jaws & the Windows Narrator have a weird pronunciation of it.

I checked if I could change the title myself to "Menü schließen", which doesn't sound too bad, but the screenreader will read "Menü schließen - Button - Open Backstage", which is weird.

The "Open Backstage" originates from the RoutedUICommand:

![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/756703/afba7aac-1297-4050-8876-ffc1c4718636), which is currently hardcoded:

```
public static class RibbonCommands
{
    /// <summary>
    /// Gets the value that represents the Open Backstage command
    /// </summary>
    public static readonly RoutedCommand OpenBackstage = new RoutedUICommand("Open backstage", nameof(OpenBackstage), typeof(RibbonCommands));
}
```

The "easiest" fix would be to change the "Backstage" to "Menü" (for the German translation) and somehow use the same text for the RoutedUICommand, but I'm not even sure if this is needed or if the text could be removed anyway.

---
### Environment

- Fluent.Ribbon __v10__
- Windows __11__
- .NET Framework __4.8__

**Comment by robertmuehsig** [comment]
@batzen Ah - the "ESC" Key makes sense in this area, but the button text is still "Backstage schliessen" - any chance that you might switch to "Menü schliessen" instead?

**Comment by batzen** [comment]
You can overwrite that text by changing BackButtonUid. 😉

**Comment by robertmuehsig** [comment]
Stupid question: How can I access this property from my code? In the past I used something to traverse the WPF control tree, but this seems “dirty”.


Am 22.08.2023 um 22:05 schrieb Bastian Schmidt ***@***.***>:

﻿

You can overwrite that text by changing BackButtonUid. 😉

**Comment by batzen** [comment]
It's a property on BackstageTabControl.

**Comment by robertmuehsig** [comment]
@batzen Thanks - didn't noticed it, but works! Any chance that you might publish the 10.0.3 soon?

**Comment by batzen** [comment]
Will try to publish tomorrow.
