### ISSUE TITLE
Not enough quota when using Ribbon inside BusyIndicator (or just using IsEnabled = false in some cases)

### ISSUE THREAD

**Issue by AlexeiScherbakov** [fluentribbon/Fluent.Ribbon#1164]
When Ribbon is used as Content inside BusyIndicator pattern (Content, Overlay rectangle, BusyContent) on Windows 10 'Not enough quota' exception is throwing inside WPF. On Windows 11 all works as expected.

Exception is raised when ContentControl inside RibbonWindow where Ribbon is located received ```false``` value to IsEnabled property.
RibbonWindow->BusyIndicator->Grid->Ribbon

I tested 9,10 Fluent.Ribbon versions - all show same error on Windows 10 (22.H2 10.0.19045.3393)

This can be related to https://github.com/fluentribbon/Fluent.Ribbon/issues/634 
Also I found description of this type of problems [here](https://stackoverflow.com/questions/12584619/mysterious-not-enough-quota-is-available-to-process-this-command-in-winrt-port) and [here](https://social.msdn.microsoft.com/Forums/en-US/d778c6e0-c248-4a1a-9391-28d038247578/mysterious-8220not-enough-quota-is-available-to-process-this-command8221-in-winrt-port-of?forum=winappswithcsharp)
 
For workaround this BusyIndicator should not disable Content, just hide it with overlay rectangle.
---
### Environment

- Fluent.Ribbon 10.0.3
- Windows 10 22.H2
- .NET Core 7

**Comment by batzen** [comment]
If it works on Windows 11, but not on Windows 10 it's most likely a bug in .NET or Windows itself.
There is no Windows version specific code in Fluent.Ribbon itself.
