### ISSUE TITLE
ScreenTip is not DPI aware

### ISSUE THREAD

**Issue by yordans** [fluentribbon/Fluent.Ribbon#1165]
Ribbon-aligned ScreenTips are not positioned under the ribbon on DPIs different from 100%, e.g. on 125% DPI the ScreenTip is displayed inside the ribbon.

### Environment
- Fluent.Ribbon 10.0.0
- Windows 10
- .NET Framework 4.8

**Comment by yordans** [comment]
Hello, when 10.0.4 is planned to be released?

**Comment by batzen** [comment]
@yordans Just released it.

**Comment by yordans** [comment]
@batzen Thank you for letting me know.

**Comment by batzen** [comment]
You are totally right.
I shouldn't have scaled the popup height.
