### ISSUE TITLE
BackstageTabControl BackButton no animation when mouse hover

### ISSUE THREAD

**Issue by smile-zyk** [fluentribbon/Fluent.Ribbon#1171]
BackstageTabControl BackButton no animation when mouse hover
[TestBackStage](https://github.com/smile-zyk/TestBackStage)

- Fluent.Ribbon __v10.0.3
- Windows 10
- .NET 6

**Comment by batzen** [comment]
I don't fully understand as it has a hover effect.
Do you mean that there is no distinction between keyboard focus and mouse hover?
