### ISSUE TITLE
MenuItems, having a submenu, do not stay highlighted when MenuItem from the submenu is highlighted

### ISSUE THREAD

**Issue by yordans** [fluentribbon/Fluent.Ribbon#1183]
The default Windows behavior for Header MenuItem is that the MenuItem stays highlighted when its submenu item is highlighted as shown in the  screenshot:

![ContextMenu](https://github.com/fluentribbon/Fluent.Ribbon/assets/42739501/a790a977-8e28-43b6-9054-e075dd5cc758)

Fluent.MenuItem behavior:

![FluentMenuItem](https://github.com/fluentribbon/Fluent.Ribbon/assets/42739501/6b903e99-18d5-41b7-8d45-6ec9c0657056)

### Environment

- Fluent.Ribbon 10.0.4
- Windows 10
- .NET Framework 4.8

**Comment by batzen** [comment]
Good catch.
Never noticed that. 🤦‍♂️
