### ISSUE TITLE
Text not disapearing

### ISSUE THREAD

**Issue by korneliuscode** [fluentribbon/Fluent.Ribbon#1187]
I want to reduce middle sized items to label-less icons when the window is too narrow.
```

<Fluent:Button Header="{x:Static res:Resources.CreateRule}" SizeDefinition="Middle, Small, Small" 
						   ToolTip="{Binding Header, RelativeSource={RelativeSource self}}" 
						   x:Name="btnCreateRule" 
						   Icon="/RibbonIcons/16px/Rules.png" 
						   Command="{Binding CreateRuleCommand}"/>
					
```
What am I missing?
---
### Environment

- Fluent.Ribbon 10.0.4
- Windows 11
- .NET Framework 8

**Comment by batzen** [comment]
Have you set an `ReduceOrder` on `RibbonTabItem`?
You can read a bit about it at https://fluentribbon.github.io/documentation/concepts/sizing

**Comment by korneliuscode** [comment]
Ah, that was it. Thanks a lot. I did not get it at first but now it makes sense.
