### ISSUE TITLE
Content-Control of DropDownButton has unwanted MinHeight

### ISSUE THREAD

**Issue by IrgendwerA8** [fluentribbon/Fluent.Ribbon#1191]
When having only one or two items assigned to a drop-down button, the styling forces a minimum height, leaving lines empty on the screen. Also visible in the showcase app:
![grafik](https://github.com/fluentribbon/Fluent.Ribbon/assets/20503363/aad35591-f8d6-44f1-bfcc-5289af8ecec2)

Older versions didn't had that problem.

A fix may consist in changing line 143 of DropDownButton.xaml to
MinHeight="0".

**Comment by batzen** [comment]
Uh, that's a copy/paste mistake from the ComboBox code.

**Comment by IrgendwerA8** [comment]
Thanks!

**Comment by VratislavBelsky** [comment]
the same thing SplitButton

**Comment by VratislavBelsky** [comment]
SplitButton.xaml line 125
