### ISSUE TITLE
wpf calendar size issu in dropdown button

### ISSUE THREAD

**Issue by mijq1** [fluentribbon/Fluent.Ribbon#1193]
I've added a wpf calendar to a dropdown button.

On first dropdown the calendar is more than 5 times a wide as high. The size reverts to square after first date selection.
I have tried to use a viewbox to set the size (normal tactics for the calendar), but with no luck.

 <Fluent:DropDownButton Width="70" Header="Sel" ClosePopupOnMouseDown="True" DropDownHeight="200">
     <Viewbox Stretch="Fill" Width="200">
         <Calendar x:Name="cal" DisplayMode="Month" DisplayModeChanged="cal_DisplayModeChanged"/>
     </Viewbox>
 </Fluent:DropDownButton>

I would really appreciate if you could help me set the normal size and aspect ratio on first dropdown.

Best regards

Mikkel

---
### Environment

- Fluent.Ribbon __v10.0.4__
- Windows __11__
- .NET Framework __?.net 8.0_

**Comment by batzen** [comment]
Added a DropDownButton with a Calendar inside to the showcase application and everything appears normal.
Maybe that's related to my changes regarding the default container for elements inside the DropDownButton, which was MenuItem before the changes and is now ContentPresenter.

**Comment by mijq1** [comment]
Thank you for your help. 
I have used the Fluent ribbon in many of my applications over the years.
