### ISSUE TITLE
Fluent 11 Quick Access panel

### ISSUE THREAD

**Issue by VratislavBelsky** [fluentribbon/Fluent.Ribbon#1195]
Fluent 11v Backstage does not work adding a button to the Quick Access panel

- Fluent.Ribbon __v11_
- Windows __11__
- .NET Framework _4.62__
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32303088/869e0c70-c592-4145-bebf-287a48c8b375)
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32303088/322916a3-f6df-43ea-bff8-883960e0a3da)

**Comment by batzen** [comment]
Fixed in develop branch.
