### ISSUE TITLE
GroupName causes the selected ToggleButton to no longer trigger the click event

### ISSUE THREAD

**Issue by tp1415926535** [fluentribbon/Fluent.Ribbon#1196]
I'm working on a drawing board tool that requires single selection menus and supports repeat selection tools. 
But I realized that after set **GroupName** to Fluent:ToggleButton, both Click and Command no longer trigger when it checked .

---
### Environment

- Fluent.Ribbon __v10.1.0__
- Windows __10__
- .NET Framework __4.7.2/.Net6.0__

**Comment by batzen** [comment]
That's by design as it would cause no button in the group to be selected anymore see #481.
It exactly the same behavior you get from a `RadioButton`.
The real issue here is that the base `ToggleButton` class has an `OnToggle` which can't be overridden because it's `protected internal`.

**Comment by batzen** [comment]
Ah. I could just manually raise the event and call the command.
