### ISSUE TITLE
Using the Fluent.Ribbon with Prism

### ISSUE THREAD

**Issue by Yucca771** [fluentribbon/Fluent.Ribbon#1200]
### Discussed in https://github.com/fluentribbon/Fluent.Ribbon/discussions/1199

<div type='discussions-op-text'>

<sup>Originally posted by **Yucca771** April 18, 2024</sup>
When I try and use the Fluent.Ribbon with Prism it will not render and gives the following error: -

System.InvalidOperationException: 'Window must be the root of the tree. Cannot add Window as a child of Visual.'

Is there a working example anywhere or can anyone help?</div>

**Comment by batzen** [comment]
I don't use Prism, but judging from the exception you are trying to use a RibbonWindow as the content for some other ui element which is not allowed in WPF.
