### ISSUE TITLE
Incorrect window close button style

### ISSUE THREAD

**Issue by Roel84** [fluentribbon/Fluent.Ribbon#1214]
**Place your issue description here.**

The background color of the window's close button is incorrect when hovered over: 

![image](https://github.com/user-attachments/assets/0d857650-977c-46f0-b6e0-daf9caf04e39)

It seems that this issue was already fixed with https://github.com/fluentribbon/Fluent.Ribbon/commit/a8bf790a1139be91cc49f758ca0bad93705051f0 but didn't make in the v10.1.0 release.

---
### Environment

- Fluent.Ribbon __v10.1.0__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
This is fixed in v11 and i don't plan to release another 10.X version.
Will try to release v11 during October.
