### ISSUE TITLE
The CanAddToQuickAccessToolBar="False"  property not work correctly for "MenuItem"

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#122]
Office 2010 theme.
When you set the flag for any "Menu Item" control CanAddToQuickAccessToolBar="False" .
The context menu "Add Menu to Quick Access Toolbar" is still visible, it only does not do anything (the item does not apear in QAT when you click it). For buttons it works correctly - the menu item is not visible.

![canaddtoquickaccesstoolbar bug](https://cloud.githubusercontent.com/assets/3475668/7860180/825b0750-053e-11e5-9ff6-645c574e4bb3.png)

**Comment by Drasius2** [comment]
More related bugs about not correctly working ContextMenu and QAT. See details in image:
![canaddtoquickaccesstoolbar bug 2](https://cloud.githubusercontent.com/assets/3475668/7877973/8e456ee8-05d9-11e5-9f11-610fc36195af.png)

**Comment by batzen** [comment]
Will have a look at this after your PR is merged.

**Comment by batzen** [comment]
Should be fixed with the changes I made today. 
Could you please check it and tell me if it's really fixed?

**Comment by batzen** [comment]
Any chance you could give me feedback by tomorrow so I can safely release the next version? Otherwise I would have to delay the next version till you tested my changes.
I also tested them but I feel safer if someone else tested them too. ;-)

**Comment by Drasius2** [comment]
Hello, sorry for long time to response. I checked and now it works fine, Thanks.

**Comment by Drasius2** [comment]
P.S. Only colapse/Expand icon still can be added to menu. Not sure how to customize it to add this flag. It was great that for collpase/Expand button this flag (CanAddToQuickAccessToolBar="False") were specified by default and no need to customize.
