### ISSUE TITLE
Icon property values of controls are translated by the translation tools like catalyst 

### ISSUE THREAD

**Issue by avikramaditya** [fluentribbon/Fluent.Ribbon#1222]
Icon property of various controls is considered as a string value that need to be translated by translation tools like catalyst, ..., because of this, an icon property value is listed in the table of strings that needs translation.

Usually a psuedo translation is done on the strings listed by translation tools before sending to professional translators by the development teams to test every text in the application is supported for translation, for example, a value of /Images/xxx.ico with psuedo translation would end up something like 'tr_/images/xxx.ico_tr', since this will break the paths to icons, application will crash. Even with the professional translators, unless they know what these texts are, they could translate to locale they intend to translate something like '/bilder/xxx.ico' for a swedish locale which leads to application crash

Icon property of controls should be marked as non localizable to avoid this.

---
### Environment

- Fluent.Ribbon 10.1.0
- Windows 10
- .NET Framework 4.8

**Comment by avikramaditya** [comment]
@batzen Is version 11 released soon? I wanted to use the nuget package instead on building the source myself.

**Comment by batzen** [comment]
Will try to get it released tomorrow.
But there is usually no need to compile it yourself.
There is a nuget feed from the CI builds and pre-releases are published to nuget on a, more or less, regular basis.
