### ISSUE TITLE
Checkboxes don't draw right if FlowDirection="RightToLeft"

### ISSUE THREAD

**Issue by ahmedsafan86** [fluentribbon/Fluent.Ribbon#123]
I tested the ribbon control it is nice, but the checkbox don't draw the mark right if i set the window FlowDirection="RightToLeft", It shows reverted like this
![fluentribbonrtlproblem](https://cloud.githubusercontent.com/assets/6296474/7894063/ec9f1544-0664-11e5-8e0b-1d13c00c03d7.png)
it works fine for the microsot ribbon like this
![standardribbonok](https://cloud.githubusercontent.com/assets/6296474/7894110/84eefd64-0665-11e5-917d-107dfb5b483c.png)

By the way I found another problem in the gallery with numbers when shown in RightToLeft it uses inidi numbers by default as a part of arabic local it shows first like this
![fluentribbonrtlproblemgallery](https://cloud.githubusercontent.com/assets/6296474/7894153/dc4ba3fa-0665-11e5-88ae-ffc4a4e88d04.png)

After I clicked the arrow below scroll down of group and show all it draw fine like this
![fluentribbonrtlproblemgallerytrue](https://cloud.githubusercontent.com/assets/6296474/7894178/2b1ac29a-0666-11e5-879a-b5ec5d601694.png)

**Comment by batzen** [comment]
As I am very busy right now, would you mind fixing this?

**Comment by ahmedsafan86** [comment]
I Wish to have the honor of contribution in this nice tool tell if fixing bugs, but I want a key or tip to start, what do you think caused this? is it a style related issue? if so how to handle language direction to add a new style? I can detect direction of current culture like Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft, then set FlowDirection property.

**Comment by batzen** [comment]
Sorry for responding so late.
I got no experience with RTL layout myself. Everything related to RTL was done by the initial project owners. Maybe a bit googling or binging can give you starting point. The original wpf themes are also a good starting point. You should be able to find the wpf themes in a path like this "C:\Program Files (x86)\Microsoft Visual Studio 14.0\DesignTools\SystemThemes\Wpf" please note that the path depends or your OS bitness and the visual studio versions currently installed.

**Comment by batzen** [comment]
Any news?

**Comment by batzen** [comment]
Any news?

**Comment by batzen** [comment]
Any news? @ahmedsafan86

**Comment by ahmedsafan86** [comment]
I tried to fix it in hurry but I failed, so I stopped searching for it. but I think that the problem is in mirroring it in response to Direction RightToLeft, and also I think that overriding the Direction property of the checkbox to keep it  LeftToRight, will fix this bug. please if you can try this if it fix? just let us know.

**Comment by batzen** [comment]
Will have a look at the checkbox styles myself then.
Will also try to understand whats happening in the gallery control.
