### ISSUE TITLE
Possible to disable collapsing?

### ISSUE THREAD

**Issue by myoKun345** [fluentribbon/Fluent.Ribbon#126]
Hi, I am looking for a way to disable collapsing the ribbon by either forcing it to be open all the time or by removing the collapse button. I am relatively new to using WPF, so I admittedly don't really know how to find everything that I can do with a control, but I haven't been able to find a way to disable collapsing on my own.

Otherwise, is there a way I can track whether or not the ribbon is collapsed and scale the main content in my window with it instead?

Thanks.

**Comment by batzen** [comment]
The property you are looking for is not called IsCollapsed but IsMinimized instead.
To disable minimizing you would have to search for "PART_MinimizeButton" in the RibbonTabControl. There is currently no easier way to disable minimizing the ribbon.

**Comment by batzen** [comment]
Can we close this or do you have further questions?
