### ISSUE TITLE
Group Binding Error

### ISSUE THREAD

**Issue by morganenglish** [fluentribbon/Fluent.Ribbon#128]
Hi,

Thanks for the great library guys. I'm having a weird issue trying to bind Ribbon Tab Item to contextual tab groups. I'm trying to use some of the example code from fluent test to get it working but nothing seems to be doing it.

XAML Markup (Cutdown): 

```xaml
<Fluent:Ribbon Name="ribbon_MainRibbon" AutomaticStateManagement="True">
                    <Fluent:Ribbon.ContextualGroups>                        
                      <Fluent:RibbonContextualTabGroup Name="tabGroup1"
                                                 BorderBrush="Magenta"
                                                 Background="Magenta"
                                                 Foreground="Purple"
                                                 Header="Test"                                                         
                                                 Visibility="Visible" />
 </Fluent:Ribbon.ContextualGroups>

<Fluent:RibbonTabItem Name="test02" Group="{Binding ElementName=tabGroup1, Mode=OneWay}" Header="Test" Visibility="Visible" />

</Fluent:Ribbon>
````

Binding Error in VS2013 Output:

System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=tabGroup1'. BindingExpression:(no path); DataItem=null; target element is 'RibbonTabItem' (Name='test02'); target property is 'Group' (type 'RibbonContextualTabGroup')

**Comment by maurosampietro** [comment]
How did you solve this? I'm facing the same issue.
In my app I noticed that if I assign a RibbonContextualTabGroup to RibbonTabItem.Group instead of reference it by ElementName you get the same result as if you set HideContextTabs =True with Snoop on the ShowCase app: 

![image](https://cloud.githubusercontent.com/assets/15122144/14956705/6adcaca6-1081-11e6-863f-da29e6cf6bcd.png)

Is the title bar simply overlaying the upper part of the context tab group?

**Comment by morganenglish** [comment]
Embarrassingly, the issue was because I had set the data-context of the ribbon to my view model, and the XAML markup was looking for the group binding within the view model instead of directly in the XAML. 

I solved it by creating a RibbonContextualTabGroup property in my view model and referencing them that way.

**Comment by JD-Robbs** [comment]
@morganenglish I know this is rather historic, but could you elaborate on your solution? I think I'm having the same issue. I tried stopping DataContext inheritance by setting the Ribbon's DataContext to `{x:Null}` - alas to no avail.

**Comment by JD-Robbs** [comment]
Duh, right - so I went against the Group binding that's highlighted in the documentation and instead re-created what the Showcase does `Group="{Binding Source={x:Reference MyGroupName}}` - works a charm!
