### ISSUE TITLE
DontUseDwm="True" case the window corner unpainted

### ISSUE THREAD

**Issue by gossiper** [fluentribbon/Fluent.Ribbon#129]
In RibbonWindow, if you set DontUseDwm="True" to turn off aero glass effect, the window corner will be unpainted due to the corner radius. Also set CornerRadius is not working.

![capture](https://cloud.githubusercontent.com/assets/13091015/8398561/8eae7122-1da8-11e5-8123-383b2e945883.PNG)

**Comment by batzen** [comment]
Sadly this is not really fixable from our side as we rely on the WindowChrome class provided by Microsoft. Just have a look at the other issues labelled with "WindowChrome" to get a picture.

**Comment by huoyaoyuan** [comment]
A resolution: set WindowStyle="None" first and AllowsTransparency="True" next. Remember to set it back when setting DontUseDwm="False".

**Comment by batzen** [comment]
That works once. But you can't set it back as WPF does not allow that.
