### ISSUE TITLE
Button content

### ISSUE THREAD

**Issue by PaleyX** [fluentribbon/Fluent.Ribbon#132]
Is there a way to set the button content to use a rectangle with a visual brush rather than supply an icon?

**Comment by batzen** [comment]
Just set "Icon" to your desired object. As far as I can see "Icon" is of type "object" and is represented by a ContentPresenter.

**Comment by PaleyX** [comment]
That doesn't seem to work:

                    <fluent:Button>
                        <fluent:Button.Icon>
                            <Rectangle Fill="Green" Height="20" Width="20" />

                        </fluent:Button.Icon>
                    </fluent:Button>

**Comment by batzen** [comment]
You should always set Icon and LargeIcon
```
                    <Fluent:Button>
                        <Fluent:Button.Icon>
                            <Rectangle Fill="Green" Height="20" Width="20" />
                        </Fluent:Button.Icon>
                        <Fluent:Button.LargeIcon>
                            <Rectangle Fill="Green" Height="20" Width="20" />
                        </Fluent:Button.LargeIcon>                        
                    </Fluent:Button>
```

**Comment by batzen** [comment]
Can I close this, or do you have further questions?
