### ISSUE TITLE
Event before Backstage opens

### ISSUE THREAD

**Issue by ghostriderace** [fluentribbon/Fluent.Ribbon#138]
Hello,
is there the posibility to raise an event right before the Backstage opens?
I found the Click() method in BackstageButton.cs and it seems a fine place to me to settle it there if u would do that.
Thank alot for the great package.
Chris

**Comment by batzen** [comment]
The backstage has an IsOpenChanged event which is fired after the backstage is opened.
Do you really need a new event which is fired before the backstage is opened?
What are you trying to achieve?

**Comment by ghostriderace** [comment]
Thank you for your reply. I Saw the IsOpenChanged Event.
What i want to rebuild is the Window Overview like in the MS Office 2010 Information TabItem.
Further i want to be able to stop opening the Backstage in some parts.

**Comment by batzen** [comment]
I still don't know what you are trying to rebuild... But I get that you want some kind of cancelable event IsOpenChanging. As IsOpen is a dependencyproperty and I got no computer at hand I don't currently know if I can intercept the it in a cancelable way. How do you think about simply disabling the backstage button?

**Comment by ghostriderace** [comment]
Can i write here in german too? Or is it forbidden?
[Here](http://picload.org/view/iiiagww/unbenannt.jpg.html) i showed u what i meant before.
I want to capture the window.
I even are out for the Weekend and have not my own Computer, so that i can't look up how i can disable the backstage button.

**Comment by batzen** [comment]
I prefer to write in English here as others might be interested in the things we discuss here.
If you want to contact me in German the best way is probably via direct twitter messages.

Stopping the backstage from opening would be easiest achieved by just disabling it.

Showing an image of the window with a closed backstage while the backstage is open is a different story. You might want to know that there is no image shown anymore in Office 2013.

**Comment by chdft** [comment]
It is not exactly what you (ghostriderace) wanted, but this is as close as I got to a solution:
You can use the following to display a non-interactive image of a visual:
``` xaml
	<Rectangle Width="250" Height="128">
		<Rectangle.Fill>
			<VisualBrush Stretch="Uniform" Visual="{Binding ElementName=YourContent}" />
		</Rectangle.Fill>
	</Rectangle>
```
This works perfectly fine, as long as the rectangle itself isn't part of the visual that should be shown. You can show the main content of your window, but you have to exclude the Ribbon (as that would include the backstage with your preview area). That obviously also means, that you can't use the window itself as source, because that would include the ribbon...

**Comment by ghostriderace** [comment]
@batzen I didn't notice that fact in MS Office 2013 although we use this in our company. :-(

@chdft Thank you alot., I always just tried it with rendering as BitmapSource and assigning it to an Image. Now I tried your solution and it worked like a charm :-)))))
Even when I bind it to the first subelement of my window (DockPanel) it shows me the normal window content without the backstage in the opened backstage page.
Thank you very much.

For me, this can be closed.

**Comment by batzen** [comment]
Glad could make you happy and thanks @chdft for contributing.
