### ISSUE TITLE
Ribbon menu does not  work

### ISSUE THREAD

**Issue by egor-spk** [fluentribbon/Fluent.Ribbon#139]
When you try to open a menu program fails.

> Message: Object reference not set to an instance of the object..
Stacktrace:
   в Fluent.Backstage.CreateAndAttachBackstageAdorner() в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 399
   в Fluent.Backstage.Show() в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 270
   в Fluent.Backstage.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 114
   в System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   в System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   в Fluent.Backstage.set_IsOpen(Boolean value) в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 65
   в Fluent.Backstage.Click() в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 236
   в Fluent.Backstage.OnMouseLeftButtonDown(MouseButtonEventArgs e) в c:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent\Controls\Backstage.cs:строка 642
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   в System.Windows.Input.InputManager.ProcessStagingArea()
   в System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   в System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   в System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

My content code:
```c#
<UserControl x:Class="PRNSystem.View.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:Fluent="urn:fluent-ribbon"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d">
    <Fluent:Ribbon Fluent:RibbonProperties.TitleBarHeight="0" IsQuickAccessToolBarVisible="False">

        <!--  Меню  -->
        <Fluent:Ribbon.Menu>
            <Grid>
                <Fluent:Backstage Background="#18a3de" KeyTip="M">
                    <Fluent:BackstageTabControl>
                        <Fluent:BackstageTabItem Header="Настройки" KeyTip="S">
                            <Grid Width="Auto"
                                  MinWidth="0"
                                  Margin="50"
                                  HorizontalAlignment="Stretch">
                                <TextBlock MinWidth="0"
                                           HorizontalAlignment="Left"
                                           Foreground="Black"
                                           TextWrapping="Wrap">
                                    Тут будут настройки
                                </TextBlock>
                            </Grid>
                        </Fluent:BackstageTabItem>
                        <Fluent:SeparatorTabItem />
                        <Fluent:Button Header="Выход" KeyTip="E" />
                    </Fluent:BackstageTabControl>
                </Fluent:Backstage>
            </Grid>
        </Fluent:Ribbon.Menu>

        <!--  Вкладки  -->
        <Fluent:RibbonTabItem Header="Служебная записка" ToolTip="Создание и управление служебными записками" />
        <Fluent:RibbonTabItem Header="Заявка на оплату" ToolTip="Создание и управление заявками на оплату" />
        <Fluent:RibbonTabItem Header="Справочники" ToolTip="Различные справочники" />
        <Fluent:RibbonTabItem Header="Администрирование" ToolTip="Управление всей системой" />
    </Fluent:Ribbon>
</UserControl>
```

**Comment by batzen** [comment]
As far as I remember this issue was fixed a while ago.
Which version are you using? Does this happen when you use the latest version?

**Comment by egor-spk** [comment]
I use a version 3.4.1 of the nuget  package.

**Comment by batzen** [comment]
Anything special with your Window?
The only null ref exception possibly thrown in line 399 is because of a missing AdornerLayer.
Are you using our RibbonWindow or a custom one?
If you are using our RibbonWindow a repro project would be nice.

**Comment by egor-spk** [comment]
Yes, I use a non-standard window. If you find a free minute, here's an minify version of my project.
https://dl.dropboxusercontent.com/u/11499124/project.rar

**Comment by batzen** [comment]
Can't view it on mobile but even without having seen your custom window I guess you missed adding an AdornerDecorator to your template.

**Comment by batzen** [comment]
Had a look at your template and you are really missing an AdornerDecorator.

**Comment by egor-spk** [comment]
Thank you very much. Your solution helped.

**Comment by batzen** [comment]
Glad I could help you out.
