### ISSUE TITLE
Fluent Ribbon 3.4.2 fails with PEVerify

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#140]
After updating to 3.4.2 (3.4.1 worked great), I have PEVerify errors:

```
18> Orchestra.Examples.Ribbon.Fluent.NET45 -> C:\CI_WS\Ws\80590\Source\Orchestra\output\release\NET45\Examples.Ribbon.Fluent\Orchestra.Examples.Ribbon.exe
18> Verifying assembly
18>MSBUILD : error : Fody: PEVerify of the assembly failed. 
18>MSBUILD : error : 
18>MSBUILD : error : Microsoft (R) .NET Framework PE Verifier. Version 4.0.30319.33440
18>MSBUILD : error : Copyright (c) Microsoft Corporation. All rights reserved.
18>MSBUILD : error : 
18>MSBUILD : error : [IL]: Error: [C:\CI_WS\Ws\80590\Source\Orchestra\output\release\NET45\Examples.Ribbon.Fluent\Orchestra.Examples.Ribbon.exe : Orchestra.Examples.Ribbon.App::OnStartup][offset 0x00000038] Unable to resolve token.(Error: 0x80131869)
18>MSBUILD : error : [IL]: Error: [C:\CI_WS\Ws\80590\Source\Orchestra\output\release\NET45\Examples.Ribbon.Fluent\Orchestra.Examples.Ribbon.exe : Orchestra.Examples.Ribbon.Views.RibbonView::.ctor][offset 0x00000012] Unable to resolve token.(Error: 0x80131869)
18>MSBUILD : error : 2 Error(s) Verifying C:\CI_WS\Ws\80590\Source\Orchestra\output\release\NET45\Examples.Ribbon.Fluent\Orchestra.Examples.Ribbon.exe
18>MSBUILD : error : 
```

Though this isn't necessarily caused by Fluent, it's the only thing I updated.

**Comment by GeertvanHorrik** [comment]
I was thinking it might be the System.Windows.Interactivity.dll being delivered together with Fluent ribbon, but that's not the case.

**Comment by GeertvanHorrik** [comment]
It doesn't seem to affect runtime behavior though. But what could be causing this?

**Comment by GeertvanHorrik** [comment]
And it seems that NuGet screwed up again. It updated some references, but not all (although it did update packages.config).

**Comment by batzen** [comment]
I downloaded the zip file and tried PEVerify in different versions (4.0, 4.5.1 and 4.6) and all of them succeed...

**Comment by batzen** [comment]
Nice you found out.
One reason could have been that this was the first version I published by taking the appveyor artifacts (that's why you don't get 3.4.2.0 but 3.4.2.173 instead). And as far as I remember appveyor uses VS2015 to compile.

**Comment by GeertvanHorrik** [comment]
NuGet was playing up all evening yesterday. I had to fall back to MyGet mirrors in order to update packages, etc. Maybe the client screwed up something badly.

**Comment by batzen** [comment]
I guess that's one of the reasons we don't use nuget at work. ;-)
The others might be that our project files don't get touched in case we update something. I hate that part from nuget.
