### ISSUE TITLE
Add Lithuanian (lt) language support

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#141]
Hello, there is Lithuanian language Office 2010 translation.
When you have time, you can add this language to supported list :).

Language: Lithuanian
Code: lt

// Backstage button text & key tip
backstageButtonText = "Failas";
backstageButtonKeyTip = "F";

// See right-top corner... (two different tooltips must be if you press it)
minimizeButtonScreenTipTitle = "Minimizuoti juostelę (Ctrl + F1)";
minimizeButtonScreenTipText = "Juostelėje rodyti tik skirtukų pavadinimus.";
expandButtonScreenTipTitle = "Išplėsti juostelę (Ctrl + F1)";
expandButtonScreenTipText = "Rodyti juostelę taip, kad visada butų išskleista net ir spustelėjus komandą.";

// QAT tooltips and menu items            
quickAccessToolBarDropDownButtonTooltip = "Tinkinti sparčiosios prieigos įrankių juostą";
quickAccessToolBarMoreControlsButtonTooltip = "Daugiau valdiklių"; // When two arrows appear ">>"
quickAccessToolBarMenuHeader = "Tinkinti sparčiosios prieigos įrankių juostą";
quickAccessToolBarMenuShowAbove = "Rodyti virš juostelės";
quickAccessToolBarMenuShowBelow = "Rodyti po juostele";

// Click on Ribbon to show context menu
ribbonContextMenuAddItem = "Pridėti į sparčiosios prieigos įrankių juostą"; // Button
ribbonContextMenuAddGroup = "Pridėti į sparčiosios prieigos įrankių juostą";
ribbonContextMenuAddGallery = "Įtraukti galeriją į sparčiosios prieigos įrankių juostą"; // For ex., by opened font context menu
ribbonContextMenuAddMenu = "Pridėti į sparčiosios prieigos įrankių juostą";
ribbonContextMenuRemoveItem = "Šalinti iš sparčiosios prieigos įrankių juostos"; // By item in QAT
ribbonContextMenuCustomizeQuickAccessToolbar = "Tinkinti sparčiosios prieigos įrankių juostą...";
ribbonContextMenuShowBelow = "Rodyti po juostele";
ribbonContextMenuShowAbove = "Rodyti virš juostelės";
ribbonContextMenuCustomizeRibbon = "Tinkinti juostelę:";
ribbonContextMenuMinimizeRibbon = "Minimizuoti juostelę";

**Comment by batzen** [comment]
Thanks for contributing!
