### ISSUE TITLE
GalleryPanel should inherit from VirtualizingStackPanel instead of Panel

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#142]
The GalleryPanel is used as ItemsHost in the following controls:
- ComboBox
- Gallery
- InRibbonGallery

As we can't just replace the used GalleryPanel with a regular VirtualizingStackPanel as this would remove the grouping etc. we should change the inheritance of GalleryPanel from Panel to VirtualizingStackPanel.

GalleryPanel always had an "Orientation"-Property which was ignored. By changing inheritance to VirtualizingStackPanel it finally gets used.

And the best benefit we get is virtualization. The ComboBox was slow like hell without it taking nearly 4 seconds to show 5000 items on my machine (Core i7 2700k).

I am not sure if I should consider this a breaking change as no external contract is broken except that ItemContainerGenerator can't be set anymore and I don't think anyone was using the GalleryPanel themselves.

@GeertvanHorrik
As you are one of the main consumers of this library, what do you think about this being a breaking change or not?

**Comment by GeertvanHorrik** [comment]
Thanks for including me into the discussion. It doesn't look like a breaking change for us.
