### ISSUE TITLE
Button Foreground with VisualStateManager

### ISSUE THREAD

**Issue by loewnzaan** [fluentribbon/Fluent.Ribbon#144]
Hello,

when i use the RibbonWindow, and create a ButtonStyle (for regulär Buttons, not fir Fluent) with VisualStateManager in Pressed-state and set a foreground color like this:

<VisualState x:Name="Pressed">

                                        <Storyboard>

                                            <ColorAnimationUsingKeyFrames Storyboard.TargetProperty="(Control.Foreground).(SolidColorBrush.Color)" 
                                                >
                                                <EasingColorKeyFrame KeyTime="0"
                                         Value="Red" />
                                            </ColorAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>

Then i add 3-4 Buttons at the Windows Maingrid: all Buttons are red in Foreground when i pressed only one Button.. Is this a Chrome-Bug or Ribbon problem?
I use Windows 10 and VS 2015.

Thx

**Comment by batzen** [comment]
Does this only happen when using a RibbonWindow?
Could you send me a repro? 
One file containing the resources and usage would be enough.

**Comment by batzen** [comment]
Any news?

**Comment by batzen** [comment]
Any news?
