### ISSUE TITLE
Currently using Office 2013 theme, do you have a similar non-ribbon window with that theme?

### ISSUE THREAD

**Issue by TylerKalosza** [fluentribbon/Fluent.Ribbon#145]
Hi there,

I'm currently looking into switching my application that uses the Fluent RibbonWindow to the Office 2013 theme that you provide. I was wondering if there was an easy way to theme my other dialogs so they have the same window theme as the RibbonWindow.

To clarify, in the screenshot provided you'll notice that the Properties dialog still has the OS theme applied to it because it is a regular WPF Window.

![github question](https://cloud.githubusercontent.com/assets/12025660/9095842/9018d5d2-3b87-11e5-8b0f-995a8d1c99fa.png)

EDIT:  I just checked Microsoft Excel and it also performs the same way as I'm describing here, It would still be cool to make it look more modern on a Windows 7 OS though.  :)

**Comment by batzen** [comment]
You can just use the RibbonWindow. I am doing that at work and will add a sample of a RibbonWindow without a Ribbon to the showcase application. Will let you know as soon as I added it.

**Comment by TylerKalosza** [comment]
Awesome!  Thanks man!  You rock!

**Comment by batzen** [comment]
Totally forgot about this during the week. Will try to add it on monday.

**Comment by TylerKalosza** [comment]
Great thanks!  That's excellent!

**Comment by TylerKalosza** [comment]
I just tried it batzen, worked great and looked great.  Do you also get the compile time error 'Ribbon' ControlTemplate TargetType does not match templated type 'Ribbon'?  It doesn't prevent me from building or running, but it's in my error list.
