### ISSUE TITLE
Foreground colour backstage items

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#147]
in the BackstageTabControl I have several BackstageTabItems.
When I add a TabControl in a BackstageTabItems there is no problem, I see all content. However when I add a Grid with TextBlocksas direct content of a BackstageTabItem i don't see the Text of my TextBlock. I have to add Foreground="Black" to each Textblock. 

Any idea why the foreground is now default white instead of black in a backstageitem?

**Comment by batzen** [comment]
This is by mistake. Will fix it.
