### ISSUE TITLE
Caliburn.Micro + Fluent Ribbon

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#148]
Fluent Ribbon doesn't work with Caliburn Micro. Bindings using x:Name do not work.

more info: http://www.felicepollano.com/2011/07/21/UsingFluentRibbonWithCaliburn.aspx

**Comment by batzen** [comment]
I never used Caliburn Micro so I need your help to be able to investigate this potential issue.
Could you create and publish a repro of your issue?

**Comment by wstaelens** [comment]
don't have a small example right now but it is not so hard to setup. Give it a try (you will actually love it)

**Comment by batzen** [comment]
To be honest, I got no time to create my own repros for every issue...
In addition to that, I don't (and probably won't) use Caliburn.Micro, so my interest in trying it out is exactly zero.

**Comment by wstaelens** [comment]
I'll do my best to create an example but will maybe not this week.

(besides this: making it fully compatible with Caliburn.Micro could only be good for fluent:ribbon as lots of WPF developers use CM as MVVM framework.)

**Comment by batzen** [comment]
That would be good, of course.
The main problem with MVVM support in this library is that I don't need it, so I won't implement it. There is already #1, but no one seems to be interested.

**Comment by wstaelens** [comment]
maybe this should be linked to https://github.com/Caliburn-Micro/Caliburn.Micro ?

**Comment by batzen** [comment]
Don't get what you are trying to say.

**Comment by wstaelens** [comment]
sorry should be this link: https://github.com/Caliburn-Micro/Caliburn.Micro/issues/146

**Comment by batzen** [comment]
Why do you think these should be linked?

**Comment by batzen** [comment]
@wstaelens Why do you think these should be linked?

**Comment by wstaelens** [comment]
just to make it compatible with CM, nothing more.

**Comment by batzen** [comment]
I would have looked into your original reported issue, but not without a provided repro.

**Comment by vac** [comment]
If anyone still interested in using Fluent.Ribbon with Caliburn.Micro (connecting button by names with methods/actions) this is my current working solution for Caliburn.Micro 3.0.3 and Fluent.Ribbon 5.0.1:

```C#
public class MyBootstrapper : BootstrapperBase
    {
        static IEnumerable<System.Windows.DependencyObject> FluentRibbonChildResolver(Fluent.Ribbon ribbon)
        {
            foreach (var ti in ribbon.Tabs)
            {
                foreach (var group in ti.Groups)
                {
                    foreach (var obj in BindingScope.GetNamedElements(group))
                        yield return obj;
                }
            }
        }

        protected override void Configure()
        {
            //...
            BindingScope.AddChildResolver<Fluent.Ribbon>(FluentRibbonChildResolver);
            //...
        }
```

**Comment by wstaelens** [comment]
@vac thanks!
