### ISSUE TITLE
Text display: ribbon controls doesn't always seem to activate ClearType

### ISSUE THREAD

**Issue by xinyingho** [fluentribbon/Fluent.Ribbon#15]
It seems that, when WPF is left alone with ClearType activation management, WPF is really too aggressive at disabling ClearType (see http://blogs.msdn.com/b/text/archive/2010/01/15/cleartypehint.aspx).
It's really visible with the Fluent ribbon control as labels and texts are randomly changing from sharp and clear to smudged and clogged. Sometimes, it can happen simply by hovering in and out with the mouse changing the text background.
So it would probably be good to use RenderOptions.ClearTypeHint="Enabled" wherever needed.

**Comment by batzen** [comment]
Any news on this one?

**Comment by batzen** [comment]
No reaction, closed.
