### ISSUE TITLE
Menu Item Tool tip not appearing when in a datatemplate

### ISSUE THREAD

**Issue by stephendye** [fluentribbon/Fluent.Ribbon#150]
I need to have a recent files list in the application menu.  I am using the application menu's RightPaneContent for this.  My Xaml is below:

```xml
<Fluent:Ribbon.Menu>
                <Fluent:ApplicationMenu x:Uid="r:RibbonApplicationMenu_1" Header="File" Name="RibbonApplicationMenu">

  <Fluent:ApplicationMenu.RightPaneContent>
   <ItemsControl ItemsSource="{Binding Source={StaticResource DefaultFileValues}, Path=RecentFilesList}">
                                <ItemsControl.ItemTemplate>
                                    <DataTemplate>
                                        <Fluent:MenuItem Header="{Binding ShortName}"  ToolTip="{Binding FullName}" Description="{Binding FullName}"  IsEnabled="{Binding IsAccessible}" Click="RibbonHighlightingList_MostRecentFileSelected" />                                                                                
                                    </DataTemplate>
                                </ItemsControl.ItemTemplate>                               
                            </ItemsControl>
    </Fluent:ApplicationMenu.RightPaneContent>
 </Fluent:ApplicationMenu>
</Fluent:Ribbon.Menu>
```
When the click event I have attached to the menuitem fires, I can see by inspecting the tooltip property on the menuitem in debug that the tooltip content is not set, but the description property is set.  

The strange thing is that this only appears to happen when I wrap the menu items in the datatemplate.  When I just put hard coded menu items in the right pane the tooltip is displayed.  Is this a bug or does anyone have any suggestions for a workaround?

Any thoughts would be greatfully appreciated

Stephen Dye

**Comment by batzen** [comment]
I am very busy right now. Will have a look at this next week, at least I hope so.

**Comment by stephendye** [comment]
Ok thanks.  Much appreciated!!
