### ISSUE TITLE
RibbonToolBarLayoutDefinition is not compatible with some bindings?

### ISSUE THREAD

**Issue by llinyu** [fluentribbon/Fluent.Ribbon#151]
I need a SplitButton with ColorGallery, it work well in some RibbonToolBarLayoutDefinition RibbonToolBarRow, but not always.

![ribbon](https://cloud.githubusercontent.com/assets/13833645/9307586/eaac8c10-4531-11e5-9e06-69a6ed648b1e.png)

**Comment by batzen** [comment]
I am very busy right now. Will have a look at this next week, at least I hope so.
Would be nice if you could upload a repro instead of posting the code here, that would make it easier for me.

**Comment by llinyu** [comment]
https://github.com/llinyu/RibbonTest

Thank you!

**Comment by llinyu** [comment]
If modify
<SolidColorBrush Color="{Binding ThemeColor}"/> 
to
<SolidColorBrush Color="{Binding ElementName=fontColorGallery, Path=SelectedColor}"/>

All OK!

**Comment by batzen** [comment]
I guess, without having tried something, that the DataContext information is lost in SplitButton.Icon because it's defined as "object". But I will have a look at that when I got some spare time.

**Comment by llinyu** [comment]
I test 3.5.1, all work well, but visual studio still output:

System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'SolidColorBrush' (HashCode=28560354); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'SolidColorBrush' (HashCode=14103557); target property is 'Color' (type 'Color')

Thank you.

**Comment by batzen** [comment]
Sometimes in your test application or in a different application?
I don't get those messages in your test application.

**Comment by llinyu** [comment]
Both in my test application and different application.

**Comment by batzen** [comment]
"click any one" was the missing detail here. ;-)

**Comment by batzen** [comment]
And this also happens for the DropDownButton and not only the SplitButton.

**Comment by batzen** [comment]
It's caused by the ColorGallery. Will see if I can fix it.

**Comment by batzen** [comment]
Should be fixed now.
