### ISSUE TITLE
Is it possible to add separator in QAT menu?

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#152]
Is it possible to add separator in QAT menu?
If so, how need to do it?
In example (other control...)
![image](https://cloud.githubusercontent.com/assets/3475668/9331241/f13da240-45c6-11e5-84ba-2ba4b5d56339.png)

In example like this does not work:
\<fluent:QuickAccessMenuItem CanAddToQuickAccessToolBar="False">
        \<Separator />
\</fluent:QuickAccessMenuItem>

**Comment by batzen** [comment]
This is currently not possible.

**Comment by Drasius2** [comment]
Thanks for answer.
