### ISSUE TITLE
Incorrect rendering with SizeToContent="WidthAndHeight"

### ISSUE THREAD

**Issue by rhunen** [fluentribbon/Fluent.Ribbon#153]
I am trying to modify the RibbonWindowWithoutRibbon example to create auto sizing dialogs that have the same window style as the main window. It appears that rendering is incorrect when SizeToContent="WidthAndHeight".

Here is a code example that can be used to reproduce the issue in the FluentTest application:
```
<fluent:RibbonWindow x:Class="FluentTest.RibbonWindowWithoutRibbon"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     xmlns:fluent="urn:fluent-ribbon"
                     Title="RibbonWindowWithoutRibbon"
                     SizeToContent="WidthAndHeight">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <fluent:Ribbon Grid.Row="0" IsMinimized="True"
                       IsAutomaticCollapseEnabled="False"
                       IsCollapsed="True"
                       IsQuickAccessToolBarVisible="False"
                       CanCustomizeQuickAccessToolBar="False"
                       CanCustomizeRibbon="False"
                       CanQuickAccessLocationChanging="False"
                       ContentGapHeight="2" />
        <Border Grid.Row="1" Width="400" Height="400" BorderThickness="10" BorderBrush="Red"/>
    </Grid>
</fluent:RibbonWindow>
```
The image shows the rendering result:

![fluentribbonrendererror](https://cloud.githubusercontent.com/assets/13765303/9352339/d693380c-4660-11e5-9b3a-e8a4fdb63c56.PNG)

Notice the black areas at the right and at the bottom. The black areas turn white as soon as you start to resize the Window. Width and height remain wrong though.

There are no rendering artifacts with SizeToContent="Width" or SizeToContent="Height" (but then height/width is of course not as desired).

Regards,
-Roger

**Comment by rhunen** [comment]
Addition: the black areas disappear as soon as you start to resize the Window....

**Comment by batzen** [comment]
I am very busy right now. Will have a look at this next week, at least I hope so.
Take above statement for all the issues you reported so far.
