### ISSUE TITLE
Removing item (that has DropDown ) from QAT removes items in Ribbon Toolbar

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#154]
Removing items from QAT removes items in Ribbon Toolbar.
How to repeat: I am using Fluent Ribbon .Net 4.5 build (but same for .Net 4 version). Add one of the DropDown items to Quick Access Toolbar.
![image](https://cloud.githubusercontent.com/assets/3475668/9381060/0a2a6f64-473d-11e5-9e12-d9013210cbf9.png)

Then right click on QAT icon triangle [Icon "\/"] and click "Remove from Quick Access Toolbar":
![image](https://cloud.githubusercontent.com/assets/3475668/9381183/cf5ad0f8-473d-11e5-969e-e627d4c9a2da.png)

And you will see that the items from Toolbar dropdown are removed:
![image](https://cloud.githubusercontent.com/assets/3475668/9381256/536ced72-473e-11e5-989b-bf7c499cbb29.png)

**Comment by batzen** [comment]
I can't reproduce this issue locally.

**Comment by chdft** [comment]
I am able to reproduce the bug, but with different steps (using FluentTest v3.5.0.182):
1. Add a SplitButton or DropDownButton to the QAT. Keep in mind that you have to right click the drop-down-arrow-part of a SplitButton to add the drop down to the QAT.
![step1](https://cloud.githubusercontent.com/assets/6153920/9386829/ad3181c8-475d-11e5-8158-549d8ac0ddc8.png)
2. Open the drop down in the QAT.
![step2](https://cloud.githubusercontent.com/assets/6153920/9386880/e9f2efac-475d-11e5-9261-bec46cd564f2.png)
3. Right click on any item in the drop down and select "Remove from Qick Access Toolbar"
![step3](https://cloud.githubusercontent.com/assets/6153920/9386907/18edb7d8-475e-11e5-99fa-2c79862ed66d.png)
The Button is removed from the QAT, but all MenuItems in the drop-down are removed as well.
![step4](https://cloud.githubusercontent.com/assets/6153920/9386951/4bda561a-475e-11e5-89d8-0d9c38b6d625.png)

**Comment by batzen** [comment]
The important part was to click into the list and say "remove". Will have a look at this when I got time.
