### ISSUE TITLE
Important: The Ribbon QAT added icons is not saved on app close

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#156]
The Ribbon QAT added icons is not saved on app close. 
![image](https://cloud.githubusercontent.com/assets/3475668/9383324/dad7f060-4750-11e5-9276-cb4c38b6cf0b.png)
If I add some items to QAT and close program, the QAT items is gone.

**From 3.4 I upgraded to 3.5**. And now the QAT items does not stays added when you close and open program again. In console window it print: 
Saving state to memory stream...
State saved to memory stream.
In 3.4 these messages was not printed, and everything works fine. Maybe you have any Idea why it does not works and how to fix it (what changes cause it)?

**IF** I set the Ribbon property **AutomaticStateManagement="False"**  - then only the first two items always apears (TogglePropertiesViewButton and NewDataExplorerButton).
**ELSE**
If I leave default, only these items always apears: NewDocumentButton and NewDocumentButton.

    <fluent:Ribbon.QuickAccessItems>
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=TogglePropertiesViewButton}" CanAddToQuickAccessToolBar="False" Visibility="Collapsed" IsChecked="True" />
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=NewDataExplorerButton}" CanAddToQuickAccessToolBar="False" Visibility="Collapsed" IsChecked="True" />
                
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=NewDocumentButton}" CanAddToQuickAccessToolBar="False"/>
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=OpenDocumentButton}" CanAddToQuickAccessToolBar="False"/>
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=SaveDocumentButton}" CanAddToQuickAccessToolBar="False"/>
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=SaveAsDocumentButton}" CanAddToQuickAccessToolBar="False"/>
                <fluent:QuickAccessMenuItem Target="{Binding ElementName=CloseDocumentButton}" CanAddToQuickAccessToolBar="False"/>

                <fluent:QuickAccessMenuItem IsCheckable="False" Click="MenuItem_OnClick" CanAddToQuickAccessToolBar="False">
                    <fluent:Button Name="QuickAccessCollapseMenuItemButton"  Style="{StaticResource QuickAccessCollapseMenuItemStyle}"/>
                </fluent:QuickAccessMenuItem>
                
            </fluent:Ribbon.QuickAccessItems>

Maybe you know what can couse this. Why other items are not saved after close?
How to manage QAT items saving?

**Comment by batzen** [comment]
I am very busy right now. Will have a look at this next week, at least I hope so.
Take above statement for all the issues you reported so far.

I made some changes to the state management as it was very buggy. Seems like I introduced a new bug by doing so.
Could you provide a fully working repro for this issue?

**Comment by Drasius2** [comment]
In gitHub source code environment saving QAT items works fine. So it is only in my app, maybe it is because I have some custom item templates.. I will post more details tomorrow.

**Comment by Drasius2** [comment]
I finally find out what happens :). I was specified custom "OnClosed" event for ribbon window - by this the default OnClosed event functionality was not triggered and the QAT items was not saved  :+1: . So there no bug, only some invalid code :).

**Comment by batzen** [comment]
Nice you found out.
