### ISSUE TITLE
Use System.Windows.Shell

### ISSUE THREAD

**Issue by rhunen** [fluentribbon/Fluent.Ribbon#157]
Hi,

Now that FRCS no longer supports .NET 3.5 using System.Windows.Shell (part of .NET Framework 4 and later) should IMHO be preferred over Microsoft.Windows.Shell.

Regards,
-Roger

**Comment by batzen** [comment]
System.Windows.Shell is supported in .NET 4.5 but not in 4.0, or am I missing something?

**Comment by rhunen** [comment]
System.Windows.Shell is apparently supported as of .NET 4.0 (I reference it in a .NET 4 Client Profile project using Visual Studio 2012 Express for Desktop).

**Comment by batzen** [comment]
I don't see System.Windows.Shell in the references dialog and trying to just use the namespace produces compile time errors (VS 2015 Community). 
Are you really sure it's a framework reference?

**Comment by rhunen** [comment]
The System.Windows.Shell namespace is in PresentationFramework.dll so you won't see it as an assembly in the references dialog. Here is the documentation reference:
https://msdn.microsoft.com/en-us/library/vstudio/system.windows.shell%28v=vs.100%29.aspx

**Comment by batzen** [comment]
I know that it's present in PresentationFramework.dll, but not in .NET 4.0. No matter what the documentation says. If you don't believe me, try it yourself in this project.
Maybe I'm still missing something but on my machine it does not compile.
I would be very happy if I could remove the reference to Microsoft.Windows.Shell.

**Comment by QuantumDeveloper** [comment]
@batzen correct me if I am wrong, but you dont need special dll for using that namespace. You just need to connect namespace and thats all. 
MSDN says, that its available starting from .Net 4 and higher.
https://msdn.microsoft.com/en-us/library/system.windows.shell(v=vs.110).aspx

**Comment by batzen** [comment]
As I said, the MSDN is wrong, not me. ;-)

I'd really like to cancel support for .NET 4.0 but I have no clue how broadly it's used.
I wish nuget would offer statistics for that...
Announcing it on GitHub does not seem to be enough, so many people would be surprised by a version that cancels .NET 4.0 support.

**Comment by rhunen** [comment]
Really wierd... The JumpListSample program presented in the Microsoft documentation for the JumpList class compiles for me with no errors or warnings targeting .NET 4 Client Profile in VS2012 Express for Desktop. The required references are PresentationCore, PresentationFramework, System, System.Xaml and WindowsBase. Nothing else. Using a .NET dependency checker (CheckAsm) I could confirm that no other assemblies are used.

I copied the resulting program to a stock Windows 7 Pro machine with all MS patches. I then removed .NET Framework 4.5.2 from this machine leaving stock 4.0 with updates. JumpListSample.exe runs just fine.

**Comment by QuantumDeveloper** [comment]
maybe issue in that you used client profile? Because I am testing it on .Net 4 withoput client profile and it did not compile.

**Comment by batzen** [comment]
JumpList is not used in Fluent, WindowChrome is used.
Beside that, could you please, instead of insisting that a class is present when it's obviously not, try to modify the Fluent code to proof your assumptions?
All MS patches means .NET 4.5.2, which can, and i am just speculating, cause that effect because there are no separate assemblies for .NET 4.0 and .NET 4.5 and the application might just use the never PresentationFramework assembly which, in fact, contains WindowChrome.

**Comment by rhunen** [comment]
Ah, WindowChrome! This class was added in .NET 4.5. WindowChrome does not exists in the System.Windows.Shell namespace in .NET 4.0. I guess this explains it all.
