### ISSUE TITLE
Maximized RibbonWindow state error after long IO operation.

### ISSUE THREAD

**Issue by llinyu** [fluentribbon/Fluent.Ribbon#159]
When RibbonWindow is in maximized state, if the RibbonWindow is blocked by a long IO operation, the
maximized RibbonWindow state goes into error after IO completion.

![image](https://cloud.githubusercontent.com/assets/13833645/9469425/8da4d484-4b79-11e5-8a8d-677b17a503cd.png)

**Comment by llinyu** [comment]
You can check this test.
https://github.com/llinyu/RibbonTest/tree/master/RibbonTest/MaxStateTest

Thank you!

**Comment by chdft** [comment]
Your problem seems to be the same as in #80. As far as I know the only known workaround is to not do heavy work on the UI thread.

**Comment by chdft** [comment]
There seems to be another workaround: The window is rendered correctly again, if you set the `WindowsState` property of the Window to maximized again, after you have finished your long running operation on the UI thread.
Therefore you can work around the problem by executing the following after the long running code (in your example the for loop):
```
if (WindowState == System.Windows.WindowState.Maximized)
{
	WindowState = System.Windows.WindowState.Normal;
	WindowState = System.Windows.WindowState.Maximized;
}
```
I've tested this on Windows 7 with .Net 4.5.1 and it worked fine, but I recommend to outsource long running operations into background threads anyway. That way your UI doesn't lock up in the first place and users don't think your application has crashed.

**Comment by batzen** [comment]
It not always possible to use background threads.
Will have a look at this and at #80 because it recently started to affect my employers application...

**Comment by llinyu** [comment]
Yes, heavy work in background thread is a good idea.
