### ISSUE TITLE
Fluent Licencing Link

### ISSUE THREAD

**Issue by crakinshot** [fluentribbon/Fluent.Ribbon#16]
License linked via main page no longer exists. 

http://msdn.microsoft.com/en-us/office/aa973809.aspx

**Comment by batzen** [comment]
Microsoft is not interested in answering the question.
Anyone reading who got some contact at microsoft to ask this question?

**Comment by crakinshot** [comment]
Personally, I'd ignore it

"Proponents of free software, such as KDE developer Jarosław Staniek[40] have expressed beliefs that patents regarding ribbons cannot be acquired due to the ambiguity of prior art.[40] As no patent has been acquired yet, **they assert that anyone who has not signed the license can legally implement the concept in their applications without having to conform to Microsoft's requirements**.[41] Staniek notes that the ribbon concept has historically appeared extensively as "tabbed toolbars" in applications such as Sausage Software's HotDog, Macromedia HomeSite, Dreamweaver and Borland Delphi.[40] Lotus developed early ribbon UIs for its product eSuite. Screen shots are still available in an IBM redbook about eSuite (page 109ff).[42]" http://en.wikipedia.org/wiki/Ribbon_%28computing%29

**Comment by batzen** [comment]
Thanks for looking this up!
I will remove the parts referring to the license from Readme.md.
