### ISSUE TITLE
After closing and opening app again some QAT items icons is not shown (those items with was generated in runtime.)

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#162]
Hello. I have such issue. 
In ribbon toolbar i have some splitDropDown items generated and added at runtime in backend.
When I add them to QAT (some times one of them icons is not shown...).
After closing app and opening, all these added (dynamicaly generated objects) does not showing icons in QAT.
![image](https://cloud.githubusercontent.com/assets/3475668/9514456/d21ed1f8-4ca2-11e5-83e4-cc217087538b.png)

If I remove one of QAT items after they loaded the missing icons appears.

In ribbon window event Loaded I tried to add the one more QAT item and remove it like this:
 var fixButton = new ToggleButton { Name = "fixButton", CanAddToQuickAccessToolBar = true, ToolTip = "Fix Button" };
            MainRibbon.AddToQuickAccessToolBar(fixButton);
            MainRibbon.RemoveFromQuickAccessToolBar(fixButton);

but it did not worked, still icons were not shown at start point (and some times, one of them when it is added to QAT) .

Maybe you have any idea how I can fix that, maybe some parameter ?

The toolbar buttons are created like this:
private static DropDownButton CreateRibbonDropDownButton(IToolbarButtonPlugin buttonPlugin)
        {

            var dropDownButton = new DropDownButton
            {
                Header = buttonPlugin.ButtonText,
                ToolTip = buttonPlugin.ButtonText,
                LargeIcon = buttonPlugin.ButtonImage,
                Icon = buttonPlugin.ButtonImage,
                CanAddToQuickAccessToolBar = true,
            };

            AddRibbonButtonDropDownItems(buttonPlugin, dropDownButton);

            return dropDownButton;
        }

        private static void AddRibbonButtonDropDownItems(IToolbarButtonPlugin buttonPlugin, DropDownButton ribbonButton)
        {
            if (!string.IsNullOrEmpty(buttonPlugin.ButtonDropDownDisplay))
            {
                // Now add any menu items specified
                if ((buttonPlugin.MenuItems == null) || (!buttonPlugin.MenuItems.Any()))
                {
                    return;
                }

                var menuItems = new List<MenuItem>();
                foreach (var menuItem in buttonPlugin.MenuItems)
                {
                    // Create a menu item for each one
                    var ribbonMenuItem = new MenuItem
                    {
                        Header = menuItem.Text,
                        Command = menuItem.Command,
                        Icon = menuItem.ImageSource,
                        CanAddToQuickAccessToolBar = false,
                    };
                   
                    menuItems.Add(ribbonMenuItem);
                }
                
                ribbonButton.ItemsSource = menuItems;                
            }
        }

**Comment by Drasius2** [comment]
So...
Whan problem I solved. 
* When the app is closed and openet no icons are displayed in QAT.
I added Dispatcher to RibbonWindowLoaded event:

>Dispatcher.BeginInvoke(DispatcherPriority.ContextIdle, new Action(() =>
            {
                var fixButton = new ToggleButton { Name = "fixButton", CanAddToQuickAccessToolBar = true, ToolTip = "Fix Button" };
                MainRibbon.AddToQuickAccessToolBar(fixButton);
                MainRibbon.RemoveFromQuickAccessToolBar(fixButton);
            }));

But the other problem - when adding these items to QAT icon is not shown. I have 3 items with are generated dynamicaly.

And by adinng firs one - the first one item does not have icon.
Then adding second one item - the first one item icon apears, and the second added item does not show icon (and so on.. so last added item does not have icon.
If I remove the item without icon and add again - then item will apears. And this is only one time after app was started.

**Comment by Drasius2** [comment]
You can repeat this from this repo: https://github.com/Drasius2/Fluent.Ribbon/tree/%23162 #162 branch. After adding to QAT, closing app and opening again icons are not visible.
![image](https://cloud.githubusercontent.com/assets/3475668/9519984/57c23cf4-4ccc-11e5-9194-ceaa60dd6886.png).

I do not know why but I cant repeat second problem (when items are added and icon is not shown) (one time i managed to repeat on this repo..), but it does not repeats again.

**Comment by Drasius2** [comment]
Now you can repeat bouth issues in https://github.com/Drasius2/Fluent.Ribbon/tree/%23162  repo.

**Comment by Drasius2** [comment]
Is it possible to somehow fix the 2-nd one issue while fix is not available in nugget?

**Comment by batzen** [comment]
The problem with loading the controls again on application startup is caused by the implementation of QAT state management.
The code is very simple and stupid. It just saves the positions of the items and tries to grab the corresponding items when it's loaded again.
One saved item looks like this "0,3,1,0,0,3,0,0," and nothing more.
So for your dynamically added items you run into the problem that aren't part of the ribbon when the state is loaded.

I would strongly advice you to not used the included method of saving and loading QAT items as you will, most probably, change the positions of your generated or generate them in a different order in the future. The result you'll get then is that you get some "random" controls restored to QAT.

I don't use dynamic QAT and state management at all at work because our ribbon is massively generated at runtime. There is not a single fixed item in our Ribbon.
To be honest, I won't change/improve the current QAT saving and loading because I don't use it at all.

**Comment by batzen** [comment]
Your second problem is caused by WPF itself. 
We got a converter which creates a new Image and sets your BitmapImage as it's source.
When i replace your code with
```
Icon = new Image { Source = new BitmapImage(new Uri(@"Images\Green.png", UriKind.Relative)) },
```
It works as expected. 
As that's essentially exactly the same we do in our converter, I don't know why it behaves differently...

**Comment by Drasius2** [comment]
Thanks, creating icons like this:
> Icon = new Image { Source = new BitmapImage(new Uri(@"Images\Green.png", UriKind.Relative)) },

Solved both problems.

I had removed this code:
> Dispatcher.BeginInvoke(DispatcherPriority.ContextIdle, new Action(() =>
{
var fixButton = new ToggleButton { Name = "fixButton", CanAddToQuickAccessToolBar = true, ToolTip = "Fix Button" };
MainRibbon.AddToQuickAccessToolBar(fixButton);
MainRibbon.RemoveFromQuickAccessToolBar(fixButton);
}));
