### ISSUE TITLE
Binding to Backstage.IsOpen does not work from View Model

### ISSUE THREAD

**Issue by QuantumDeveloper** [fluentribbon/Fluent.Ribbon#164]
Hi. I want to set false to IsOpen from VM, but it has no effect.
At the same time if I palce some toggle button in backtage and bind in to IsOpen, it will work.

Is it possible to fix that?

**Comment by QuantumDeveloper** [comment]
Tried the same in your demo... and it works. I am sure I made everything correct regarding binding and I dont have binding errors.
Have no idea why backstage doesnt react on value changing (twoway option is active)

**Comment by batzen** [comment]
I don't know your code.
Can we close this?
