### ISSUE TITLE
Save As menu is added to QAT but does not have child items

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#165]
"Save As" menu is added to QAT but does not have the child items in drop down. The bug can be repeated from main (this) repository..
![image](https://cloud.githubusercontent.com/assets/3475668/9573365/55abcfac-4fc4-11e5-8354-c638b1101ee0.png)

![image](https://cloud.githubusercontent.com/assets/3475668/9573377/734e3a7c-4fc4-11e5-98cd-656d1967121b.png)

**Comment by Drasius2** [comment]
Please release this fix with nugget as soon as possible, because it is quit important feature. Thanks!

**Comment by batzen** [comment]
If you need a fix ASAP and it's important to you, maybe you should consider fixing this.
As I often said, I don't use the QAT feature at all so my motivation to fix issues there tends to zero.
