### ISSUE TITLE
TabItem is shown when adding a TabItem to an invisible ContextualTabGroup

### ISSUE THREAD

**Issue by nishy2000** [fluentribbon/Fluent.Ribbon#168]
TabItem is shown when adding a TabItem to an invisible ContextualTabGroup

![image](https://cloud.githubusercontent.com/assets/13976757/9626626/e306e52c-5199-11e5-8a50-2d2438eb529b.png)

proposed code is in pull request #167

**Comment by batzen** [comment]
Will have to revert your RibbonTabItemChanges as they change the current behavior and make groups visible which shouldn't be visible.
ContextGroups calculate their visibility according to the TabItems they contain.

**Comment by batzen** [comment]
Added won't fix as this is a question of who controls whom.
By adding your change we change the current behavior which would most probably break someones application.
