### ISSUE TITLE
Black RibbonWindow title bar

### ISSUE THREAD

**Issue by Enhakiel** [fluentribbon/Fluent.Ribbon#170]
Hello,
With the last version  (3.5.1.198) if RibbonWindow.WindowState = Normal  and if I maximize it manually  the whole title bar become black, no more reduce/maximize/close buttons. This is only happening when I've got a winFormHost control inside, this behavior wasn't present in 3.5.0.182 version.

Thanks.

**Comment by batzen** [comment]
Could you create a repro of this issue?

**Comment by Enhakiel** [comment]
Are you asking me if I can reproduce the error? or if I can create a "blank" app with that bug?

**Comment by Enhakiel** [comment]
https://bitbucket.org/Enhakiel/bugfluent/
A very simple example with datagrid inside a winFormHost control (in my app it's a cartographic map (dotspatial))

**Comment by batzen** [comment]
This was introduced by commit https://github.com/fluentribbon/Fluent.Ribbon/commit/76077ae567662ee84209af3bf9ad6fbd12ef7e49 which should fix #159.
Guess I will have to find a different fix for #159.

**Comment by Enhakiel** [comment]
Ok, thanks
