### ISSUE TITLE
Binding Observable Collection to InRibbonGallery causes Layout Error

### ISSUE THREAD

**Issue by MathewSachin** [fluentribbon/Fluent.Ribbon#173]
When Items are Added or Removed from an ObservableCollection Binded to a Fluent.InRibbonGallery , the original layout is lost.

My App Contains a Refresh Button, pressing which updates the Names of the Open Windows

Before Refresh:
![untitled picture](https://cloud.githubusercontent.com/assets/10654537/10170933/f861596e-66f4-11e5-93ea-0912a8c6c405.png)

After Refresh:
![untitled picture 2](https://cloud.githubusercontent.com/assets/10654537/10170952/124f5420-66f5-11e5-8d56-c640682c8460.png)

**Comment by batzen** [comment]
Could you provide a small repro?
The best way would be to add code that demonstrates your issue to our showcase application and create a pull request containing those changes.
That way we can better try to avoid the issue from reappearing in the future.

**Comment by MathewSachin** [comment]
My repository is already on GitHub: [Captura](http://github.com/Captura).

It would be great if you could check it out there

**Comment by MathewSachin** [comment]
Just press the Refresh button on the Home Tab and see the effect on Window tab

**Comment by batzen** [comment]
There are no public repositories for Captura.

**Comment by chdft** [comment]
I think he wanted to link to this repository: https://github.com/MathewSachin/Captura
