### ISSUE TITLE
Disable ESC closes backstage?

### ISSUE THREAD

**Issue by chrfin** [fluentribbon/Fluent.Ribbon#174]
At  the moment pressing the Esc key always closes the backstage:

        // Handles backstage Esc key keydown
        private void HandleWindowKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Escape)
            {
                // only handle ESC when the backstage is open
                e.Handled = this.IsOpen;

                this.IsOpen = false;
            }
        }

I have some kind of "startup-wizard" displayed in there which is not allowed to be closed before selecting some stuff -> pressing Esc breaks that logic.

Would it be possible to add a property to disable that?

**Comment by batzen** [comment]
Thanks for contributing.
