### ISSUE TITLE
Button icons don't show in backstage with Office2013 theme

### ISSUE THREAD

**Issue by junrau** [fluentribbon/Fluent.Ribbon#176]
Button icons don't show in backstage with Office2013 theme.

In App.xaml:

![app xaml](https://cloud.githubusercontent.com/assets/3798930/10252766/deb17bd0-68f6-11e5-8bdb-599306706efc.png)

In MainWindowm.xaml:

![window xaml](https://cloud.githubusercontent.com/assets/3798930/10252767/debf3f40-68f6-11e5-8a03-73b8f3b1ac02.png)

The window:

![window](https://cloud.githubusercontent.com/assets/3798930/10252765/deb17108-68f6-11e5-8d74-b8bd05ad974c.png)

**Comment by batzen** [comment]
Yes, they don't. That's intentional as there are no icons in Office 2013 too.

**Comment by batzen** [comment]
Did that answer your question?

**Comment by junrau** [comment]
I guess so, but I would argue that even though Microsoft doesn't put icons on the backstage items in Office2013, it doesn't mean the theme doesn't support icons.

**Comment by batzen** [comment]
So what would your expected behavior be?
- Reserve space for the icon always?
 - Breaks current layout for every consumer of this library.
- Collapse icon space when there is no icon?
 - Won't break current layout, but causes floating display of items when some got icons and some don't.

What's your suggestion on solving this?

**Comment by junrau** [comment]
I looked through the Office 2013 applications, and almost all of the items in the backstage are tabs, with sub-content, not buttons/menu items.  I guess I changed my mind about wanting icons there.

**Comment by batzen** [comment]
Can we close this issue, or do you have any further questions?

**Comment by junrau** [comment]
Close it.

-----Original Message-----
