### ISSUE TITLE
Color Themes for Office2013

### ISSUE THREAD

**Issue by MathewSachin** [fluentribbon/Fluent.Ribbon#177]
Excel theme is green
Word theme is blue
PowerPoint is red

Could you implement a property for the same which should affect BACKSTAGE, STATUSBAR, MENU BUTTON

**Comment by batzen** [comment]
Like this one?
```
<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">#2B579A</Color>
```

**Comment by MathewSachin** [comment]
But It should be easily changable from Ribbon

**Comment by batzen** [comment]
Why should it be?
The way it's currently implemented guarantees that every RibbonWindow you open has the same color. If you had to set it on the Ribbon or RibbonWindow you would have to do that for every instance.

**Comment by MathewSachin** [comment]
Thankyou

**Comment by batzen** [comment]
Sarcasm?

**Comment by MathewSachin** [comment]
No, I'm very sorry.
I understood the wrong way I was trying to do it
