### ISSUE TITLE
Ribbonwindow crashes

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#178]
I use a ribbonwindow. After my window is loaded I generate an error (in the window Loaded method). In the catch statement i try to show a messagebox to show the error code. But everything crashes.
If i put the code just after the Initialize metbod of the window then everything is ok. I think this is a critical bug. 

To avoid this problem I must use a normal window with the ribbon in it and avoid the RibbonWinow. However this is not as beautifull as the RibbonWindow.

**Comment by batzen** [comment]
Could you create a small repro for your issue?
Adding your code to the TestWindow in the showcase application and posting the code here would be enough for a small repro.
I tried to reproduce your issue by subscribing to the loaded event and showing a MessageBox when it's fired. Everything worked as expected.

**Comment by bochelie1000** [comment]
One more thing, it only happens if I use showdialog. I try to reproduce the error but it is difficult without luck. I make use of threads in my application, which makes it difficult to reproduce. I will keep trying to reproduce the error. I dont think there is something wrong with my application because it only happens with the RibbonWindow. Everything works fine if I use a normal window.
Crazy is that the application does not give an error it just closes.

**Comment by bochelie1000** [comment]
I get this error: Cannot perform this operation while dispatcher processing is suspended.
I can solve it by calling the window or messagebox thrue the dispatcher: Dispatcher.BeginInvoke(new Action(() => md.ShowDialog()));

This is a workaround. However I would like to know why this happens only with the RibbonWindow.

**Comment by bochelie1000** [comment]
I started looking for the problem myself. And found that the code always blocks here:
        private void UpdateWindowChrome()
        {
            var windowChrome = WindowChrome.GetWindowChrome(this);

            if (windowChrome == null)
            {
                windowChrome = new WindowChrome();
                WindowChrome.SetWindowChrome(this, windowChrome);
            }

            windowChrome.CaptionHeight = RibbonProperties.GetTitleBarHeight(this);
            windowChrome.CornerRadius = this.CornerRadius;
            windowChrome.GlassFrameThickness = this.GlassBorderThickness;
            windowChrome.ResizeBorderThickness = this.ResizeBorderThickness;
#if NET45
            windowChrome.UseAeroCaptionButtons = this.CanUseDwm;
#endif
        }

Then specialy in this row:        WindowChrome.SetWindowChrome(this, windowChrome);

I cant debug the code from this line on. If I knew how than I would do it. Maybe someone have an idea?

**Comment by bochelie1000** [comment]
It seems like the above methode is called twice. If I neglect the the SetWindowChrome methode the first time than everything works fine.

        private bool _isScndTime;
        private void UpdateWindowChrome()
        {
            var windowChrome = WindowChrome.GetWindowChrome(this);

            if (windowChrome == null)
            {
                windowChrome = new WindowChrome();
               if(_isScndTime) WindowChrome.SetWindowChrome(this, windowChrome);
            }
            _isScndTime = true;

            windowChrome.CaptionHeight = RibbonProperties.GetTitleBarHeight(this);
            windowChrome.CornerRadius = this.CornerRadius;
            windowChrome.GlassFrameThickness = this.GlassBorderThickness;
            windowChrome.ResizeBorderThickness = this.ResizeBorderThickness;
#if NET45
            windowChrome.UseAeroCaptionButtons = this.CanUseDwm;
#endif
        }

However I would like to know more and resolve the real issue. Who has any ideas?

**Comment by batzen** [comment]
So ```WindowChrome.GetWindowChrome(this)``` returns ```null``` in your application?
It should only return ```null`` on the first call of ```UpdateWindowChrome``` and it does exactly that in the showcase application.

Do you reset that property somewhere?

**Comment by bochelie1000** [comment]
No. That is not the problem.
WindowChrome.GetWindowChrome(this) does return null the first time. If i ignore it the first time, than it works.
I dont reset this property anywhere. I think maybe it try to make a call that my ShowDialog is also doong. However the window i try to show is conpletly empty. There is no code in it.

**Comment by bochelie1000** [comment]
I finaly could reproduce the error. Look in the link below for the application. 

There is also a second bug. If you go to the code behind the main window and remove the line : w1.ShowDialog(); than it wil start ok. But than try to maximize the window. You will notice that the window does crazy things when maximizing.

link: https://onedrive.live.com/redir?resid=DA6ABE46D5BCE7BE!229&authkey=!AGqpWr6bJqSH004&ithint=file%2crar

**Comment by batzen** [comment]
Will have a look at your repro next week.

**Comment by batzen** [comment]
Can't download your repro, onedrive just tells me something went wrong.

**Comment by bochelie1000** [comment]
Strange, i just tried and it worked.
I put it in my giigle drive as well. You can try thus link:https://drive.google.com/folder/d/0Bz2GgnJ4oZh1R3dMYnN5d2RNTjg/edit

**Comment by batzen** [comment]
Ok, pretty simple.
WPF runs into OnApplyTemplate of the RibbonWindow where UpdateWindowChrome is called, when calling ```WindowChrome.SetWindowChrome(this, windowChrome);``` the dispatcher seems to stop execution of the current method and raises the loaded event.

Solution: I will remove the call to UpdateWindowChrome in OnApplyTemplate because the WindowChrome is updated as soon as OnSourceInitialized is called on the RibbonWindow.
