### ISSUE TITLE
ribbon orientation

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#179]
Is somehow possible to display the ribbon vertically, let's say docked on the left side of the window?

**Comment by batzen** [comment]
It's not possible and would require a lot of effort to implement, I guess.

**Comment by batzen** [comment]
Do you have any further questions?

**Comment by maurosampietro** [comment]
Is your question sarcastic?

Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
No, just wanted to be polite and make sure that we can close this, or if you want to try to implement such a feature.
I just noticed that my wording may have been wrong in my initial answer.
It should read: "It's not currently implemented and would require a lot of effort to implement."

**Comment by maurosampietro** [comment]
Ok, I tried to apply a rotation to every element of the ribbon with success but the behavior of the part of the ribbon that can be hidden or pinned dont work well when vertical. 

Im a wpf newbie so i dont have the skills to fix that.

Thank you.

Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
Maybe you could post your solution so i could have a look?
The easiest way would probably be to just fork this project and add your style changes to the showcase application.
Maybe it's an easy fix which has to be made to the ribbon to not prevent someone from styling it that way.

**Comment by maurosampietro** [comment]
i don't have the code anymore sorry

2015-10-27 18:46 GMT+01:00 Bastian Schmidt <notifications@github.com>:

**Comment by batzen** [comment]
Will close this issue then. 
Agreed?

**Comment by maurosampietro** [comment]
Agreed 

Mauro Sampietro
Inviato da iPhone
