### ISSUE TITLE
Start application with Ribbon minimized

### ISSUE THREAD

**Issue by JacobSaugmann** [fluentribbon/Fluent.Ribbon#182]
Hi

I'm having troubles getting my application to startup with the ribbon minimized.

I'm using this code:

 <fluent:Ribbon Name="Ribbon"
                       DockPanel.Dock="Top" CanCustomizeQuickAccessToolBarItems="False" 
                       IsQuickAccessToolBarVisible="False" 
                       ShowQuickAccessToolBarAboveRibbon="False" 
                       IsMinimized="True" >

When my application startup the ribbon is not minimized?

/jacob

**Comment by batzen** [comment]
That's because of ```AutomaticStateManagement``` being true by default.
AutomaticStateManagement controls whether the last state should be saved to disk and loaded when the window is loaded.
If you minimize the ribbon, close the window/application and reopen it, the ribbon should be minimized.

**Comment by batzen** [comment]
Do you have any further questions?

**Comment by JacobSaugmann** [comment]
Hi 

Sorry, no thanks for your reply, i was hoping it was possible to start the application 1. time with the ribbon minimized.

thanks

/jacob

**Comment by batzen** [comment]
It's possible. Just set IsMinimized=true.
When your user starts the application for the first time the ribbon should be minimized.
It's just that the AutomaticStatemanagement saves the last property state to disk and loads it from there. So if your user restored the ribbon it shows restored on the next start.
