### ISSUE TITLE
office 2010 blue in windows 10

### ISSUE THREAD

**Issue by galastur** [fluentribbon/Fluent.Ribbon#183]
Hi All,

I am running windows 10, visual studio 2015 community edition and using the .net 4.0 fluent.dll version 3.5.1.0

I have added the references to the styles in the app.xaml. Please note the "an error occurred while finding the resource dictionary ..." , I have only reference the "fluent.dll", am I missing something else?

![fluent-ribbon-error](https://cloud.githubusercontent.com/assets/3416732/10643750/68cfa056-781c-11e5-82e1-6892acdc6bf0.jpg)

I just notice in the preview that it might not be easy to read, so here is the code 
````javascript
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources\BureauBlack.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2010/Blue.xaml" />
                <!--<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Windows8/Generic.xaml" />-->
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
````

And here is how it looks, note the while line between the tab text and the content of the tab
![ribbon-window](https://cloud.githubusercontent.com/assets/3416732/10643790/acc60ec6-781c-11e5-9959-2fe18ec1f270.png)

Any help will be greatly appreciate it.

Thanks

**Comment by batzen** [comment]
Are you sure it's not your own ```Resources\BureauBlack.xaml``` causing that warning?

Can't reproduce the visual issue.
Do you have different DPI settings or are you using a different font size or family?

**Comment by galastur** [comment]
Hi batzen,

Thanks for your reply.

Yes, I am incline to think that it is not my own style file causing those warnings. I have double checked and my xaml is there, i have also inspect the file and does not have any warnings/errors highlights. I have also just commented it out, clean the project, build it again and the highlight warnings are still there in reference to both fluent themes.

Regarding the visual issue, it is ok when running the .NET3.5 on the same machine, so I believe we can discard any display configuration problems

![ribbon-tabs-3-5](https://cloud.githubusercontent.com/assets/3416732/10659645/32da1e90-7899-11e5-9c53-dca96187523d.jpg)

Thanks

**Comment by galastur** [comment]
Just to definitely confirm that the warning regarding finding resource dictionary is not caused by my own resource. I have just created a new project, added the fluent.dll, added the theme reference in the application.xaml and the warning is there

![fluent-ribbon-new](https://cloud.githubusercontent.com/assets/3416732/10660174/e3b10956-789c-11e5-9033-b67c9533ebf8.jpg)

**Comment by batzen** [comment]
Regarding the visual issues: There is no .NET 3.5 version of this library anymore, do you mean .NET 4.5?

Could you try to tune the verbosity of the WPF trace? Just search for wpf in the options dialog of visual studio. That way we might find out which resource dictionary it is.

**Comment by galastur** [comment]
Hi batzen,

I still have the the 2.1.0.0 fluent.dll version . I have found out that the tab visual problem is due to this definition in my own resource, if I get rid of it, then the tab displays nicely, however this causes my labels not to be displayed nicely :

````javascript

    <Style TargetType="{x:Type Label}">
        <Setter Property="HorizontalContentAlignment" Value="Left" />
        <Setter Property="VerticalContentAlignment" Value="Top" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Label}">
                    <Grid>
                        <ContentPresenter HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}" RecognizesAccessKey="True" />
                    </Grid>
                    <ControlTemplate.Triggers>
                        <Trigger Property="IsEnabled" Value="false" />
                    </ControlTemplate.Triggers>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
````

Any ideas how I can work around this?

I will try to tune the verbosity. Will let you know how it goes! Many thanks

**Comment by batzen** [comment]
```
<Ribbon.Resources>
    <Style TargetType="{x:Type Label}"
               BasedOn="{StaticResource {x:Type Label}}" />
</Ribbon.Resources>
```

Should do the job and reset the label style back to the default one only for the ribbon.

**Comment by galastur** [comment]
Thanks batzen,

I did try your suggestion but still does not reset the label on the ribbon

```javascript
 <Fluent:Ribbon x:Name="myRibbon" Title="RIBBON" DockPanel.Dock="Top"  IsTabStop="False">
            <Fluent:Ribbon.Resources>
                <Style TargetType="{x:Type Label}"
               BasedOn="{StaticResource {x:Type Label}}" />
            </Fluent:Ribbon.Resources>
   ....
</Fluent:Ribbon>
````

**Comment by batzen** [comment]
```<Style TargetType="{x:Type Label}" />```
Should work.

**Comment by galastur** [comment]
It does! Thank you so much...

I have now set to verbose ALL the WPF trace settings, I cannot see anything in there that hints at the problem

````javascript

The thread 0x1f18 has exited with code 0 (0x0).
The thread 0x6c0 has exited with code 0 (0x0).
Loading state from isolated storage...
Saving state to memory stream...
State saved to memory stream.
State loaded from isolated storage.
Loading state from memory stream...
Saving state to memory stream...
State saved to memory stream.
State loaded from memory stream.
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: -13 / y: -13 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: -13 / y: -13 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 0 / y: 0 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: -13 / y: -13 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 0 / y: 0 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: 10 / y: 0 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: 10 / y: 0 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
Monitor-Info
Work: RECT { left: 0 / top: 0 / right: 3200 / bottom: 1720 }
Mon : RECT { left: 0 / top: 0 / right: 3200 / bottom: 1800 }
Before: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3226 / y: 1826 } }
After: MINMAXINFO { ptMaxPosition : POINT { x: 0 / y: 0 } / ptMaxSize : POINT { x: 3200 / y: 1720 } }
The thread 0x39c0 has exited with code 0 (0x0).
The thread 0x3afc has exited with code 0 (0x0).
The thread 0x26fc has exited with code 0 (0x0).
The thread 0x2ee8 has exited with code 0 (0x0).
````

Maybe it is a Visual Studio bug? The project runs and displays the appropriate theme...

**Comment by batzen** [comment]
Can't even find "an error occurred while finding the resource dictionary ..." in your posted log.
If your application starts and displays properly, the error can't be that bad.

**Comment by batzen** [comment]
Any news?

**Comment by galastur** [comment]
Hi Batzen,

None. Sorry. Both references are still highlight by VS, but the projects displays the appropriate theme...
Thanks

**Comment by batzen** [comment]
So they only get marked as erroneous in VS?

**Comment by galastur** [comment]
yes, it appears that is the case

**Comment by batzen** [comment]
There is not much I can do about that...
Can we close this then?

**Comment by galastur** [comment]
sure...thank you so much
