### ISSUE TITLE
Application item empty space when Ribbon is not in RibbonWindow

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#186]
Hallo,

I still realy like this FluentRibbon. However due to all problems im having with the RibbonWindow I am going to switch back to using the ribbon in a normal window. The RibbonWindow is still to buggy while moving it around or just maximizing it. However there is an ugly effect to this. 
In the picture below you can see how the Ribbon leaves an empty space for the application icon when not using RibbonWindow. How can I collapse this space? 

![missing icon](https://cloud.githubusercontent.com/assets/10641004/10687214/949474be-796b-11e5-8955-b46adaa3e5cb.PNG)

**Comment by batzen** [comment]
I don't know which components you are using right now, so it's difficult to answer your question.
But you might want to wait for #185?
I am teaming up with MahApps.Metro to fix all the known RibbonWindow issues we currently have.

**Comment by bochelie1000** [comment]
Instead of using a <Window I can use <Fluent:RibbonWindow ..... to have the nice window style. Because of all the bugs in the chome window I want to just use <Window..... I have no idea how long it will take you to fix #185. And I can imagine that you dont have a lot of time and thuse it will be a while before that is fixed.  That is why I am trying to avoid <Fluent:RibbonWindow.... right now.

I think what I need right now is to change the template of the QuickAccess toolbar. In that way i can collapse the space wich is reserved for the application icon. I can turn of the QuickAccess toolbar but it is such a nice toolbar that I would like to use it. And I thought that maybe there was an easier way than changing the template of the QUickAccess Toolbar. Do I have another option or should I just try to change the template of the QuickAccess Toolbar in order to collapse the space reserverd for the application icon?

**Comment by batzen** [comment]
It shouldn't take that long, I guess we are talking about 2 or 3 weeks. As the groundwork is done by the MahApps.Metro team/dev, I can't say something for sure.

To collapse the space you just have to modify the margin of PART_RibbonTitleBar on the Ribbon.

**Comment by bochelie1000** [comment]
Thanks, it works. However there are more stuff to change. I decided to not use the quickaccesstoolbar. When the problems with windowchrome are fixed I will put it back in. For now this is good enough.
