### ISSUE TITLE
Ribbonwindow not working with multitrigger

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#187]
Hallo,

It seems like I keep trying to di things no one tried before.
If I use a RibbonWindow and put some multitrigger in it. The application will not even start.

I did put a repro in my google drive: https://drive.google.com/folder/d/0Bz2GgnJ4oZh1R3dMYnN5d2RNTjg/edit

**Comment by batzen** [comment]
You should read the exceptions the debugger throws:
{"Could not load file or assembly 'Microsoft.Windows.Shell, Version=3.5.41019.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"Microsoft.Windows.Shell, Version=3.5.41019.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}

You can't just add a reference to the Fluent.dll and ignore it's dependencies.
If you are using the .NET 4.0 version you also have to reference/include Microsoft.Windows.Shell.dll and System.Windows.Interactivity.dll.
If you are using the .NET 4.5 version you also have to reference/include System.Windows.Interactivity.dll.

**Comment by bochelie1000** [comment]
Tjanks. I guess its time to take a breake im doing stupid things. Thanks a lot.

**Comment by batzen** [comment]
You'r welcome. ;-)
