### ISSUE TITLE
How to remove the area in front of MenuItems (SplitButton)?

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#188]
```xml
<Fluent:SplitButton Header="Foo" ItemsSource="{Binding FooData}">
          <Fluent:SplitButton.LargeIcon>
            <Rectangle Fill="{StaticResource imgFoo"} />
          </Fluent:SplitButton.LargeIcon>
          <Fluent:SplitButton.ItemTemplate>
            <DataTemplate>
              <Fluent:MenuItem Header="{Binding Title}">
                <Fluent:MenuItem.Icon>
                  <Rectangle Fill="{StaticResource imgFoo2}" Stretch="Uniform" />
                </Fluent:MenuItem.Icon>
              </Fluent:MenuItem>
            </DataTemplate>
          </Fluent:SplitButton.ItemTemplate>
        </Fluent:SplitButton>
```
You will see that each MenuItem has a space in front of the item. How can this space be removed?
I thought it was for some checkbox but "IsChecked" property on MenuItem does not remove the space.

Using a Gallery on a DropDownButton doesn't have this extra space in front of the MenuItems:

```xml

        <Fluent:DropDownButton Header="Bar">
          <Fluent:DropDownButton.LargeIcon>
            <Rectangle Fill="{StaticResource imgBar}" />
          </Fluent:DropDownButton.LargeIcon>
          <Fluent:Gallery ItemsSource="{Binding BarData}">
            <Fluent:Gallery.ItemTemplate>
              <DataTemplate>
                <Fluent:MenuItem Header="{Binding Title}">
                  <Fluent:MenuItem.Icon>
                    <Rectangle Fill="{StaticResource imgBar2}" Stretch="Uniform" />
                  </Fluent:MenuItem.Icon>
                </Fluent:MenuItem>
              </DataTemplate>
            </Fluent:Gallery.ItemTemplate>
          </Fluent:Gallery>
        </Fluent:DropDownButton>`
```

Is it a "style bug" that is forgotten? or do you always need to use a Gallery for SplitButton?
I could not find it in a manual or documentation.

**Comment by batzen** [comment]
It's the age old problem with ItemsControl, ItemsSource and DataTemplates.
If you want to get rid of that space you will have to use ItemContainerStyle.
Please see: http://stackoverflow.com/questions/1312895/using-a-datatemplate-for-a-menuitem-causes-extra-space-on-the-left-side-to-appea

**Comment by wstaelens** [comment]
Is it possible to update documentation with samples of how to implement a Fluent:DropDownButton / Fluent:SplitButton etc? As information seems to be scarce.
e.g. the Fluent Ribbon Control Suite Walkthrough pdf file only contains 1 example of the Fluent:SplitButton with hardcoded Fluent:MenuItem (no ItemsSource binding samples or more info).

**Comment by batzen** [comment]
The documentation is horribly outdated and the pdf wasn't updated in years.
I have to admit that i am horrible at documenting things here...

If you want to help improve it have a look at #101.

**Comment by wstaelens** [comment]
ok thanks.

**Comment by batzen** [comment]
Will close this as documentation related issues are tracked separately.
Agreed?

**Comment by wstaelens** [comment]
ok, but I would love to see you add "the" "default" way of adding items to a splitbutton to the documentation ;-) :+1:

**Comment by batzen** [comment]
Feel free to do that in one of your future documentation PRs. ;-)
As soon as the site repo is created I will add an issue for this missing part of documentation.
