### ISSUE TITLE
Visual Editor for Fluent?

### ISSUE THREAD

**Issue by blackbeard9** [fluentribbon/Fluent.Ribbon#190]
hi
is it possible to have a wysiwyg editing in visual studio? all i can see is my fist tab but i want to see my backstage menu while editing the code. is this possible?

**Comment by batzen** [comment]
I guess it's possible and would be a nice addition for newcomers, but I got no plans and no motivation to implement an editor.
If you got any ideas on how to implement such an editor I might still be interested in helping, but I won't  implement it myself.
