### ISSUE TITLE
Windows 8 Theme - Blue/black margin around the window in windows 10

### ISSUE THREAD

**Issue by blackbeard9** [fluentribbon/Fluent.Ribbon#191]
hi
i really like the windows 8 theme but in windows 10, i have a problem with a colored margin around the window (except the upper edge) - see the screenshot. is it possible to fix this by myself?

![image](https://cloud.githubusercontent.com/assets/15376305/10813418/3bd31854-7e1f-11e5-9181-6f3649687436.png)

**Comment by batzen** [comment]
You could try to modify the ResizeBorderThickness.
But that would affect the upper edge too.

The border shouldn't be that thick, it's a bug that's partially caused because we got some trouble with the WindowChrome class from Microsoft. 
I will start to fix these issues as soon as #185 is done.

**Comment by blackbeard9** [comment]
great, thanks a lot :) 
i tried your suggestion, but it changed nearly nothing (border is now white instead of blue, but not thinner). meanwhile i will use the office 2013 theme, its great as well!

**Comment by batzen** [comment]
This should be a lot better now in the develop branch.
