### ISSUE TITLE
Background of RibbonGroupBox can't be set/changed

### ISSUE THREAD

**Issue by efitAP** [fluentribbon/Fluent.Ribbon#192]
Hello everyone,
First of all i want to mention that this ribbon is really awesome. I enjoy making applications with it, but today I got problem with it. I'm using v3.6 but the problem I have is, that the background of a RibbonButton or a RibbonGroupBox can't be changed. 
Neither settings per code nor settings in the designer allow mi co change the background color of my ribbon items. 
Is there a trick to do that or isn't it fully implemented?

Thanks for your help!

**Comment by batzen** [comment]
You could try to change the RibbonBackgoundBrush to affect the background color/brush.
I haven't tried it.

RibbonGroupBox and Button, and probably most other controls, don't take the set Background into account in their corresponding templates. 
So I would say it's not fully implemented and there is currently no way, other than implementing your own templates, to override the background for a single group or button.

**Comment by batzen** [comment]
Will try to change the styles to make it possible to overwrite those colors.

**Comment by batzen** [comment]
I think i figured it out.

**Comment by efitAP** [comment]
Thank you!
