### ISSUE TITLE
Add RibbonTabControl into TitleBar?

### ISSUE THREAD

**Issue by staeff777** [fluentribbon/Fluent.Ribbon#193]
Is it somehow possible to host the RibbonTabControl directly in the TitleBar? I don't use contextual Tabs, but I would like to gain some vertical space for my application content.  

Edit: wrote RibbonWindow instead TitleBar.

**Comment by batzen** [comment]
For that to work you would have to get rid of the QuickAccessToolbar, application title and the app icon too.
Would that be worth getting 25 units of vertical space?
Currently the contextual tabs are embedded into the titlebar.
If you really want to get vertical space you can still minimize the ribbon.

**Comment by staeff777** [comment]
I don't think that this is necessary. Why not replace contextual tabs?

**Comment by staeff777** [comment]
Just as an interesting example,  WPS office integrates even both into the title and uses the title for the backstage menu button. 

http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2014/08/WPS-SpreadSheets.png

**Comment by batzen** [comment]
Looks interesting, indeed.
Will try a few things and keep you updated when I did so. 

Will take a few days as I also have to create the initial website for this library, thus having to learn how to work with jekyll...

**Comment by staeff777** [comment]
Cool. By the way,  WPS Office also has Contextual Tabs,  they put them at the end of the regular Ribbontabs and highlight them with a colored marker. 

However, I just want to state,  that those 25 pixels are no show stopper in using your library. It its indeed already great work.

**Comment by batzen** [comment]
@staeff777 As i made major changes/improvements to the way the ribbon/ribbonwindow are composed it would be nice to hear if this fits your needs.
You can now use the ribbon without a titlebar.

**Comment by batzen** [comment]
@staeff777 ping

**Comment by staeff777** [comment]
Sorry for the delay. It looks very good. Thank's a lot.
