### ISSUE TITLE
Remove SaveWindowPosition as it is broken

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#196]
SaveWindowPosition is broken for a long time now and no one seems to be using it.
The functionality of saving/restoring window positions should not be part of this library as I want to focus on the ribbon.

**Comment by chrfin** [comment]
I did not know this was even part of this library, but I am using such a functionality implemented in my own window inheriting `RibbonWindow`, which works fine (including when detaching monitors, as it is based on the native function `SetWindowPlacement` of Windows).
If you are interested I could add it to this library, but I will not if you do not want such functionality anyhow?

**Comment by batzen** [comment]
I was thinking about a new OSS project which could provide extended features independent from the ribbon.
Adding such a feature, or in this case keeping it here, feels kind of wrong because this library should focus on the ribbon itself.
As i am currently trying to share the WindowChrome code with the MahApps team I think it would be a good idea to share that feature with them too.
If I remember correctly the initial code for that feature was taken from there.
The library which will be used to shared code/features between the two projects will be https://github.com/punker76/Controlz
So maybe you could ask @punker76 if he'd like to see it being implemented there.
