### ISSUE TITLE
Ribbon IsEnabled=False via Style / DataTrigger doesnt work

### ISSUE THREAD

**Issue by blackbeard9** [fluentribbon/Fluent.Ribbon#198]
hi, i am trying to disable the ribbon when a button within the ribbon is clicked. for that i have created a style for the ribbon:

        <Style x:Key="rbnDisabled" TargetType="{x:Type Fluent:Ribbon}">
            <Setter Property= "IsEnabled" Value="True"/>
            <Style.Triggers>
                <DataTrigger Binding="{Binding ElementName=g3b2, Path=IsPressed}" Value="True">
                    <Setter Property="IsEnabled" Value="False"></Setter>
                </DataTrigger>
            </Style.Triggers>
        </Style>

the ribbon button is g3b2. If i click the button the ribbon flickers but nothing more, whats the fault?

edit: ok got it, triggers restore values when value is no longer true...

**Comment by chdft** [comment]
Just to make sure that I get that right: you want to add a button to your ribbon which disables the ribbon when it is clicked and keeps it disabled until you re-enable it programmatically.
If that is the case, you can use a ```Fluent:ToggleButton``` and its ```IsChecked``` property. That results in something like that:
```
	<Fluent:RibbonWindow.Resources>
		<Style x:Key="rbnDisabled"
			   TargetType="{x:Type Fluent:Ribbon}">
			<Setter Property="IsEnabled"
					Value="True" />
			<Style.Triggers>
				<DataTrigger Binding="{Binding ElementName=g3b2, Path=IsChecked}"
							 Value="True">
					<Setter Property="IsEnabled"
							Value="False"></Setter>
				</DataTrigger>
			</Style.Triggers>
		</Style>
	</Fluent:RibbonWindow.Resources>
	<Grid>
		<Fluent:Ribbon Style="{StaticResource rbnDisabled}">
			<!--Tabs-->
			<Fluent:RibbonTabItem Header="Tab">
				<Fluent:RibbonGroupBox Header="Group">
					<Fluent:Button Name="g3b2"
								   IsChecked="False"
								   Header="Green" />
				</Fluent:RibbonGroupBox>
			</Fluent:RibbonTabItem>
		</Fluent:Ribbon>
	</Grid>
```

Please note, that this will disable the ribbon and all controls within the ribbon. The ```Fluent:ToggleButton``` will be disabled (and therefore not clickable anymore) as well as a result, once it is clicked.

**Comment by batzen** [comment]
So we can close this?
