### ISSUE TITLE
Consider using GitFlow for a more professional development workflow

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#2]
See https://github.com/particular/gitversion for auto version generation. See https://github.com/Particular/GitVersion/wiki/GitFlow for examples.

**Comment by abdelkarim** [comment]
@batzen this [extension](https://visualstudiogallery.msdn.microsoft.com/27f6d087-9b6f-46b0-b236-d72907b54683) will help you a lot.

**Comment by batzen** [comment]
Finally decided to not use gitflow as i am the only one, most of the time, working on this project.
