### ISSUE TITLE
KeyTips in SplitButton no longer work

### ISSUE THREAD

**Issue by floele-sp** [fluentribbon/Fluent.Ribbon#200]
Consider the following SplitButton:

                    <Fluent:SplitButton Header="Test KeyTips" Fluent:KeyTip.Keys="Y">
                        <Fluent:MenuItem Fluent:KeyTip.Keys="A"  Header="1" />
                        <Fluent:MenuItem Fluent:KeyTip.Keys="B" Header="2" />
                        <Fluent:MenuItem Fluent:KeyTip.Keys="C" Header="3" />
                    </Fluent:SplitButton>

If you open it using KeyTips, the menu will look like this:
![keytipsmissing](https://cloud.githubusercontent.com/assets/15671468/11213572/f9206066-8d3c-11e5-860c-a7a9dafcfacf.png)

Expected would be this (this is what a dropdown button looks like):
![keytips](https://cloud.githubusercontent.com/assets/15671468/11213611/24c1aebe-8d3d-11e5-82ed-d290a6c0df51.png)

Reason seems to be that KeyTipAdorner.Forward() also includes the SplitButton's ToggleButton at

     var children = LogicalTreeHelper.GetChildren(element)

which is then used to create the KeyTipAdorner. Not sure how the solution should work though.

**Comment by batzen** [comment]
You are totally right.
Will change the order in which SplitButtons returns it's logical children, or even better just call base.LogicalChildren in SplitButton.

**Comment by floele-sp** [comment]
Great, thanks!
