### ISSUE TITLE
Office 2013 theme: Is there any particular reason for not centering the button labels?

### ISSUE THREAD

**Issue by floele-sp** [fluentribbon/Fluent.Ribbon#202]
Hi,

please check the layout of the buttons (normal, split, dropdown):

![center](https://cloud.githubusercontent.com/assets/15671468/11237951/f7d78c60-8de2-11e5-9424-21f84fcbf214.png)

Even without zooming in you can see that the label is obviously not centered vertically. Is there a particular reason for that? The templates contain a -1 top margin to cause this effect, which seems unnecessary.

**Comment by batzen** [comment]
No reason i can think of.
Will have a look and fix it or tell you why it's done that way.

**Comment by floele-sp** [comment]
Thanks. If you adjust the label position, please also move the drop down glyph one px to the bottom, it's not correctly centered either.
