### ISSUE TITLE
select all text in spinner button

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#203]
Hallo,

I make use of the Spinner button in the ribbon. Normaly when you doubleclick inside the spinner it should automaticaly select the whole text. However when I doubleclick in the spinner it only selects all text until or after the decimal separator. Am I missing a property or something? I think it should select all text inside the spinner. Below you see a picture of what it does now.

![untitled](https://cloud.githubusercontent.com/assets/10641004/11265396/458c22ea-8e9c-11e5-81bc-5f7719dc3d21.png)

**Comment by batzen** [comment]
That's the default WPF behavior.
In WPF a double click selects till the next "separator" and it's the same in every program I know.
Triple clicking usually selects all text, but not that's sadly not part of WPF.
If you want to get the triple click to work, try this:
```
EventManager.RegisterClassHandler(typeof(TextBox), UIElement.PreviewMouseLeftButtonDownEvent, new MouseButtonEventHandler(TextBoxPreviewMouseLeftButtonDown), true);

private static void TextBoxPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
{
    var textBox = sender as TextBoxBase;

    if (textBox == null)
    {
        return;
    }

    if (e.ClickCount == 3)
    {
        textBox.SelectAll();
    }
}
```

**Comment by bochelie1000** [comment]
That is realy new for me. I had no idea. Thanks a lot!
