### ISSUE TITLE
Creating a second QuickAccessBar?

### ISSUE THREAD

**Issue by Christian24** [fluentribbon/Fluent.Ribbon#204]
Hello,

This is a great project. I have a question: 
How do I create a second "QuickAccessBar" which is aligned right like Word does in this example?
![image](https://cloud.githubusercontent.com/assets/2406635/11300130/c2802314-8f8c-11e5-9a67-235237e769fe.png)

Thanks a lot,
Christian

**Comment by batzen** [comment]
Currently it's only possible to add additional items/controls to the right side of the minimize button.
It's also shown in the showcase application.
Just have a look for ```<Fluent:Ribbon.ToolBarItems>```.

**Comment by Christian24** [comment]
Oops. Sorry, I did not see that in the showcase application. Thank you very much, that does the trick for me.
