### ISSUE TITLE
Center alignment button inside RIbbonGroupBox

### ISSUE THREAD

**Issue by Demarsch** [fluentribbon/Fluent.Ribbon#206]
I found the question similar to mine on CodePlex and seems like author didn't asked it here on GitHub so I just copy it here:

Hi, I have the following code:
```csharp
<fluent:RibbonGroupBox Header="Table"
                       MinWidth="120"
                       HorizontalContentAlignment="Center">
               <fluent:Button Header="Создать"
                      LargeIcon="pack://application:,,,/PatientInfoModule;Component/Resources/Images/AddPatient-48x48.png"
                   SizeDefinition="Large"
                   HorizontalAlignment="Center"
                   Command="{Binding ContentViewModel.CreateNewPatientCommand}" />    
 </fluent:RibbonGroupBox>
```
In my case the header of group box is wider than button so I have to set min width. But I end up having button left aligned. If I don't set min width then group box header is clipped
![image](https://cloud.githubusercontent.com/assets/4508264/11505741/453204d6-984c-11e5-985c-8abfa25f76d1.png)
![image](https://cloud.githubusercontent.com/assets/4508264/11505820/934aab6e-984c-11e5-8cca-5e494c2c8a88.png)

How can I center align this button?

**Comment by batzen** [comment]
Currently there is no way to achieve this by the way you tried it.
I can see the use case for this so I will make it possible.
