### ISSUE TITLE
Enable DragMove on unused RibbonTabControl space like in Office 2013

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#207]
In microsoft word i can double click the ribbon on an empty area to maximizes or restore the window, and you can keep mouse down and move the window, even if clicking at tabs level. 

In fluent ribbon this behavior is achieved only if clicking on at the minimize/mazimizes/close buttons level (eg where i'd click on a standard window).

Some themes render a glass frame that do not cover the entire ribbon. This glass frame looks like a bigger titlebar and I would expect at least this to behave as the title bar but it does not.

To me ribbon looks like and extended title bar so i feel it should behave like a title bar. Microsoft in facts did this way.

Hope to help. Thank you.

**Comment by batzen** [comment]
I can't move the word window when i click, hold and move the mouse on tabs level.

Every other behavior, regarding window handling (moving, maximizing, minimizing, closing), is implemented in this library and works perfectly well.

I don't know what you mean with "Some themes render a glass frame that do not cover the entire ribbon. This glass frame looks like a bigger titlebar and I would expect at least this to behave as the title bar but it does not.". 
Could you provide a screenshot to clarify?

**Comment by maurosampietro** [comment]
A regular window has a titlebar that is visually separated from the ribbon just below it. For regular window I intend the window you can run from your FluentTest.exe -> Test->Open Regular-Window. This is the part of the window that allows move/mazimize/restore. 
In a regular window i don't expect the ribbon to extend the titlebar behavior because it looks separated.

In a RibbonWindow the titlebar and ribbon are styled so that the ribbon looks inside the titlebar. In particular if a office 2010 theme is applied the titlebar (glass frame) looks bigger and the ribbon is contained in this frame. I would expect this glass frame to extend the title bar behavior, but it does not. It works only if clicks are above the tabs (eg: on what was the titlebar in a regular window not styled) . For RibbonWindow i mean FLuentTest.exe->Test->Open Ribbon.Window (ShowDialog).

On the other hand Word can be moved/mazimized/restored if you click on the ribbon in a blank area (not on tabs), even at tabs level (mouse vertically aligned with tabs). 

![animation](https://cloud.githubusercontent.com/assets/15122144/11585083/8c805cec-9a69-11e5-9002-2c9797e6cc66.gif)

As you see i click on a blank area but the vertical position of the mouse is at the tabs level. In fluent this works only if the vertical position of the mouse is above the tabs.

**Comment by batzen** [comment]
You are right, that's not implemented in this library.
Will see what I can do.
