### ISSUE TITLE
Icons in ribbon doenst look good / scaling issue?

### ISSUE THREAD

**Issue by blackbeard9** [fluentribbon/Fluent.Ribbon#208]
hi
i have a problem with the icons in my ribbon. the look as if ther is no anti aliasing (mostly rounded icons :( ) it seems as if there is a problem with the scaling? (all icons are vectors (.ico) and high res!) see espacially the delete icon and the map pin

![image](https://cloud.githubusercontent.com/assets/15376305/11613898/5c2a95c0-9c31-11e5-9571-60def980ad50.png)

![image](https://cloud.githubusercontent.com/assets/15376305/11613899/704ff0ae-9c31-11e5-86e9-926b88fb716f.png)

**Comment by batzen** [comment]
Could you attach one of your icons to this issue?

**Comment by batzen** [comment]
Any news?

**Comment by blackbeard9** [comment]
oh, email response didnt work :/ 
got the solution, just forgot to add RenderOptions.BitmapScalingMode="Fant" to the Buttons....

**Comment by batzen** [comment]
Glad you found out what's causing your issue.
We are using the default BitmapScalingMode.
