### ISSUE TITLE
Getting error: "The name 'InitializeComponent' does not exist in the current context"

### ISSUE THREAD

**Issue by sabuncu** [fluentribbon/Fluent.Ribbon#211]
I did everything described in the Foundation wiki page, and I am getting the following error:

error CS0103: The name 'InitializeComponent' does not exist in the current context

Using VS 2010 on Windows 7.  I built Fluent Ribbon w/o any problems, and added the DLL as a reference to my project.  My window file was called MainWindow; changed it to be window.

Did a clean before a build.  Still getting the error.

**Comment by batzen** [comment]
I guess you also renamed your MainWindow class. Judging from the error your xaml and xaml.cs files are out of sync. They have to have the same class names.

It's in no way a ribbon issue.

**Comment by sabuncu** [comment]
Never claimed it was a ribbon issue.  Merely asking for help so I can proceed w/ my project.

This is my Window.xaml file;

<Fluent:RibbonWindow x:Class="Fluent.Sample.Foundation.Window"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Fluent="clr-namespace:Fluent;assembly=Fluent"
    Title="Fluent.Sample.Foundation" Width="500" Height="250" >
    <Grid>
    </Grid>
</Fluent:RibbonWindow>

This is my Window.xaml.cs file:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using Fluent;

namespace WpfApplication1
{
    public partial class Window : RibbonWindow
    {
        public Window()
        {
            InitializeComponent();
        }
    }
}

**Comment by sabuncu** [comment]
I also don't understand the purpose of the included "FluentTest dotNET 4.0" project because building it does not produce an executable showing a sample window/page that has the ribbon.  Wouldn't that be the purpose of a test project?

**Comment by batzen** [comment]
I thought that you thought it might be a ribbon issue as you opened an issue here.
Gitter might be a better place to ask this kind of questions. You can find the gitter room for this project here https://gitter.im/fluentribbon/Fluent.Ribbon

'''
x:Class="Fluent.Sample.Foundation.Window"
'''
should be 
'''
x:Class="WpfApplication1.Window"
'''

You are totally correct, FluentTest should be renamed to Fluent.Showcase. I was just too lazy to rename it after I became the lead (and only dev) of this project.
Will rename it in version 4.0 to clarify it's purpose.

But building FluentTest should produce an executable showcasing most of the features of this library and it does so on my machine.

**Comment by sabuncu** [comment]
You're right, there is a FluentTest.exe under build/bin/NET 4.0/debug - I apologize.

Also, changing the class name as you suggested fixed that problem.

Thanks again.  Will use Gitter from now on.
