### ISSUE TITLE
Assign a StringFormat binding to a RibbonGroupBox Header

### ISSUE THREAD

**Issue by 1nTheZ0ne** [fluentribbon/Fluent.Ribbon#214]
I've been trying to create a dynamic `RibbonGroupBox` with some success however I cannot find a good way to set the header to a formatted string, barring the user of a value converter.

As the Header property is an `object` rather than a `string` I cannot use a binding in XAML that has a `StringFormat` parameter.

I would like to be able to do one of the following:

```xaml
<Fluent:RibbonGroupBox Header="{Binding Path=Name, StringFormat='{}{0} Properties'}">`
</Fluent:RibbonGroupBox>
```

Or:

```xaml
<Fluent:RibbonGroupBox.Header>
    <TextBlock Text="{Binding Path=Name, StringFormat='{}{0} Properties'}" />
</Fluent:RibbonGroupBox.Header>
```

**Comment by batzen** [comment]
Damn, forget to reference in commit.
Is fixed with https://github.com/fluentribbon/Fluent.Ribbon/commit/ab241d5d1e19fc6477cfebc842654b6d78dbb90f

**Comment by batzen** [comment]
You can now use the former of your mentioned alternatives.
The latter is, currently, impossible.
