### ISSUE TITLE
Backstage placing incorrect

### ISSUE THREAD

**Issue by huoyaoyuan** [fluentribbon/Fluent.Ribbon#217]
Happens when I update v3.6.0 to v3.6.1 directly, no code changed.
Backstage will cover the title bar, so I cannot go back to main content, except using the Esc key.
Code sample:
```xml
            <ribbon:Ribbon.Menu>
                <ribbon:Backstage Header="Header" KeyTip="H">
                    <ribbon:BackstageTabControl>
                        <ribbon:BackstageTabItem Header="Options" KeyTip="O">
                            <ScrollViewer VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto">
                                <!-- content -->
                            </ScrollViewer>
                        </ribbon:BackstageTabItem>
                        <ribbon:BackstageTabItem Header="About" KeyTip="A"/>
                    </ribbon:BackstageTabControl>
                </ribbon:Backstage>
            </ribbon:Ribbon.Menu>
```
Is it a bug, or a change of usage?

**Comment by batzen** [comment]
Could be a bug as i made changes to the backstage placement. Which theme and os are you using?

**Comment by huoyaoyuan** [comment]
Windows 10 10586, Office 2010 theme. The Office 2013 theme has a back button in backstage.

By the way, sometimes changing theme will make the program no response (and crashes after some seconds), but no exception catched by Visual Studio. I put a ComboBox on the Ribbon menu for user to select theme; do I do it wrong?

**Comment by batzen** [comment]
I will have a look at this (backstage placement).

Any chance you could provide a repro for you theme change and create a new issue for that?

**Comment by batzen** [comment]
Can't reproduce your backstage placement issue on my machine.
Could you attach a repro for your issue to this issue?

**Comment by huoyaoyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/5644458/11787771/76ddbb52-a2c8-11e5-994b-01257d272ae3.png)
A screenshot for a backstage placed incorrect.

**Comment by huoyaoyuan** [comment]
Reason found for crashes when changing theme. Not your fault.
I use another control library at the same time, and it crashes in DestroyWindow for that control.

**Comment by batzen** [comment]
Glad you found the cause for your crash.

But I still can't reproduce the backstage placement issue.
Any chance you could provide a repro for that?

**Comment by huoyaoyuan** [comment]
I'm sorry, but there are some issues for my application caused by the other control I used, currently no time.
I will create a test application to represent this issue when I'm free.

**Comment by batzen** [comment]
Take your time and good luck with the other control.

**Comment by huoyaoyuan** [comment]
Reason found.(?)
The backstage is placed __wrong as default ,until I__:
    Change theme __from Office2013 to Office2010__
    Do more works(owner is RibbonWindow, copied from FluentTest):
```c#
owner.Style = null;
owner.Style = owner.FindResource("RibbonWindowStyle") as Style;
owner.Style = null;
++owner.Width;
--owner.Width;
```
FluentTest loads Office2013 theme when launching, so you can't see this issue.
I think you can provide an OnThemeChanged method to recalculate parameters(such as align), or do it in OnApplyTemplate?

**Comment by huoyaoyuan** [comment]
Another issue of Backstage, v3.6.1 only, Office2010 only too:
Backstage will disappear when changing DontUseDwm, and restores when changing another theme to Office2010.
Can be reproduced by FluentTest.

**Comment by batzen** [comment]
Will try to reproduce it later.

**Comment by batzen** [comment]
I still can't reproduce this in the develop branch.
I changed the default theme of the showcase application to Office 2010, opened the backstage and it works perfectly fine.

**Comment by huoyaoyuan** [comment]
It seems that this issue is more conditional, since my application's behavior is such unstable:
If I remove the codes above, it will have a lot of issues, such as no reply while no Exception, rendering and alignment incorrect.
If I add the code above, the placement goes correct when I __change from Office2013 to Office2010__, and goes incorrect when I __change from one color of Office2010 to another color__, or load Office2010 directly.
I haven't assigned any color to Backstage. The BackstageTabItem will be blue when placement is correct, and red when placement is incorrect. But it's always red in previous version. May these help?

Difference find in changing themes:
My application: merge all xaml to the window's ResourceDictionary.
FluentTest: merge color xaml to the window, and generic xaml to the App's ResourceDictionary.
I'm not sure if this causes anything.

**Comment by batzen** [comment]
I guess it would be easier to reproduce if you could provide a small repro demonstrating your issue.

**Comment by huoyaoyuan** [comment]
OK. I've write a simple Demo, and its behavior is same to my application, different with FluentTest.
Here is the source code:
[FluentIssueShowcase.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/68579/FluentIssueShowcase.zip)

**Comment by batzen** [comment]
Ok, can finally reproduce it using your repro.

**Comment by batzen** [comment]
The problems occurs because of these two little warnings
```
System.Windows.Data Warning: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='Fluent.Backstage', AncestorLevel='1''. BindingExpression:Path=Background; DataItem=null; target element is 'BackstageTabControl' (Name=''); target property is 'Background' (type 'Brush')
System.Windows.Data Warning: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='Fluent.Backstage', AncestorLevel='1''. BindingExpression:Path=ActualHeight; DataItem=null; target element is 'BackstageTabControl' (Name=''); target property is 'Margin' (type 'Thickness')
```

If you change 
```
InitializeComponent();

To2010White(null, null);
```
to
```
To2010White(null, null);

InitializeComponent();
```
everything works as expected.

**Comment by huoyaoyuan** [comment]
OK. But another question is: what happens when I change Office2010White theme to Office2010Black theme? This causes problem too.
And, if I merge at first and remove later, will it be correct?

**Comment by batzen** [comment]
The showcase application does exactly that.
- Add/overwrite with new theme
- Remove old theme

There seem to be some internal WPF issues when there is no resource dictionary attached. Which cause your issues.
The red color was used intentionally to point out issues regarding missing ancestor controls.
```
Value="{Binding Background, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Fluent:Backstage}}, FallbackValue=Red}" />
```

**Comment by huoyaoyuan** [comment]
Thanks. Now all the problems are clear, and I can update my application to 3.6.1 now.
I'd like to wrap themes into classes, sothat I can change theme like a 
```C#
ribbon.Theme = new Office2010BlueTheme();
```
or
```xml
<Ribbon.Theme>
    <Office2010BlueTheme/>
</Ribbon.Theme/>
```
syntax.
I'll create a fork from develop branch to do this myself.

**Comment by huoyaoyuan** [comment]
One more question. What does the code
```C#
owner.Style = null;
owner.Style = owner.FindResource("RibbonWindowStyle") as Style;
owner.Style = null;
++owner.Width;
--owner.Width;
```
do? If I don't do this, I'll have to merge the ```Themes/Generic.xaml``` together with ```Themes/Office2013/Generic.xaml```, and still gets alignment wrong.

**Comment by batzen** [comment]
The code forces WPF to re-apply the window style.
WPF does seem to be picky when it comes to implicitly changing the window style so I had to make WPF think that it changed.

The width is changed to force WPF to do a full re-layout of the whole window and changing it's size was the easiest way to achieve that.

**Comment by batzen** [comment]
So can we close this one?
If you'd like to discuss the idea of a theme manager further please open a new issue.

**Comment by huoyaoyuan** [comment]
OK. This problem is totally solved.
I've wrote some code and is facing one problem now, will try myself first.
