### ISSUE TITLE
Not displaying properly when maximized

### ISSUE THREAD

**Issue by Bennik2000** [fluentribbon/Fluent.Ribbon#218]
If I maximize the window by dragging the title bar to the top edge of the desktop or by doubleclicking on the title bar the content won't display properly (sometimes).

The window was maximized but you can see the window below.
Right now I am running Windows 8.1 and .Net 4.5.1

Here is an image:
![fluent_bug](https://cloud.githubusercontent.com/assets/8039939/11781318/426aa114-a269-11e5-80ef-fd5880792e8b.png)

I hope you understand what the problem is.

**Comment by batzen** [comment]
All WindowChrome related issues, this one is most probably WindowChrome related, should be fixed in the upcoming 4.0 release.
You can grab the updated code from the develop branch of this project if you like to try it.

**Comment by batzen** [comment]
And let me guess, you got a second monitor with different resolution?

**Comment by Bennik2000** [comment]
No, I am working on my laptop without another monitor :D

**Comment by batzen** [comment]
So any chance you could try the code from the develop branch and check if you still got that issue?

**Comment by Bennik2000** [comment]
I will give it a try!

**Comment by Bennik2000** [comment]
With the latest version (commit: 285974f8dd016ad34b5b7020343a47d012811b04, I think) the maximizing works!

**Comment by batzen** [comment]
Will close this then as it's fixed in the upcoming version 4.0.
Thanks for testing!
