### ISSUE TITLE
Switch to Visual Studio 2015 so we can use nameof etc.

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#219]
Maybe it would be better to use the nameof() operator to make the source base less error prone?
e.g. in:

https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Effects/GrayscaleEffect.cs

**Comment by batzen** [comment]
As 4.0 contains breaking changes anyway I will start using features from VS 2015.

**Comment by wstaelens** [comment]
Perfect. Could only improve code quality.
