### ISSUE TITLE
Office2013 theme undesired space between tabItem and its content when showing unpinned

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#221]
![immagine](https://cloud.githubusercontent.com/assets/15122144/11815277/49c52528-a34b-11e5-964b-b6632a7848b5.png)

This is probably caused by the theme not styling the border 
I don't know what to style to fix this issue.

Any quick workaround or style to set to fix that?

**Comment by batzen** [comment]
You got no chance, other than cloning the whole template or using code behind to fix this on your side.

**Comment by maurosampietro** [comment]
I compiled the source with this fix and ill wait for an official release to reenable Nuget. Thank you!

Mauro Sampietro
Inviato da iPhone
