### ISSUE TITLE
request: add a "Tell me what you want to do..." control like Office 2016

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#222]
Maybe add a "Tell me what you want to do..." control like Office 2016

from website:

Within Word, PowerPoint, and Excel, users will find the same menu options for File, Home, Insert, etc., but also a new “Tell me what you want to do…” search box. This long overdue addition, which first appeared in the Office Online service last year, searches Office commands with a simple keyword and activates them with a click. So a search for “pages” brings up options for inserting page breaks, viewing multiple pages, adding a cover, and more.
screenshots:
http://www.tabletpcreview.com/review/microsoft-office-2016-preview-hands-on/

**Comment by batzen** [comment]
Any ideas on how to implement this?
I currently got no plans on implementing this by myself.

**Comment by wstaelens** [comment]
hmm well i have no idea if this is something that will be a "general" feature/option for ribbons or just an addition to Office itself.

**Comment by floele-sp** [comment]
Actually, I sent you (batzen) a similar implementation of such a feature quite a long time ago, you probably never got the time to look into it. Still remember the search feature?

**Comment by batzen** [comment]
Yeah, I remembered that. But I was unable to find it. Did you send it by mail or is it somewhere on github or codeplex?

**Comment by floele-sp** [comment]
I sent it per mail. If you like, I can send you another implementation based on a more recent version of fluent. I could also make a fork but I suppose the feature needs a bit cleanup before merging into the official version.

**Comment by batzen** [comment]
If you don't care about your name not showing in the commit history of this project you could create a fork and add your changes. I will then grab the changes and do the cleanup myself.

**Comment by floele-sp** [comment]
I'm a bit busy with other issues currently, but I'll provide the code as soon as I can. I probably have to work on updating Fluent again before because of the window issues that have recently been fixed (hopefully).

**Comment by GeertvanHorrik** [comment]
This would be really cool. Let me know if you need any help, I might find some time if needed :)

**Comment by batzen** [comment]
I am still waiting for @floele-sp to provide the code.

**Comment by floele-sp** [comment]
Didn't forget, coming soon ;)

**Comment by floele-sp** [comment]
Made a rough commit here now: https://github.com/floele-sp/Fluent.Ribbon/commit/b221a469cf85aa0bee3e83f9bd97401a1fa5ea68
Feel free to merge and refine :)

**Comment by batzen** [comment]
Will have a look at this after i got v4 out of the door.

**Comment by nkrs200** [comment]
I created a control that _kind of_ replicates this feature, but it is not perfect.  **Please note:** This code works in Fluent.Ribbon Version 8, but could work in the latest version. Here is what I recommend changing in the ControlTemplate for RibbonTabControl (made in italics):
```<Fluent:RibbonScrollViewer Grid.Column="1" Visibility="{Binding AreTabHeadersVisible, Converter={StaticResource boolToVisibilityConverter}, RelativeSource={RelativeSource TemplatedParent}}" HorizontalAlignment="Left" Margin="0" Width="Auto" Style="{DynamicResource RibbonTabScrollViewer}" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Disabled" IsHitTestVisible="True" IsTabStop="False">
                                                <Grid>
                                                    <Controls:SmartTabUnderline X1="34" X2="50" Stroke="{DynamicResource Fluent.Ribbon.Brushes.AccentBaseColorBrush}" StrokeThickness="2" Height="1" VerticalAlignment="Bottom" ParentRibbon="{Binding Mode=OneWay, RelativeSource={RelativeSource TemplatedParent}}" StrokeEndLineCap="Square" StrokeStartLineCap="Square"/>
                                                    <StackPanel Orientation="Horizontal">
                                                        <Fluent:RibbonTabsContainer x:Name="PART_TabsContainer" IsItemsHost="True" Height="Auto" HorizontalAlignment="Stretch" Margin="0" KeyboardNavigation.TabIndex="1" />```
_```                                                        <Controls:RibbonSearchControl MinWidth="170" MaxWidth="170" KeyTip="Q" Loaded="SearchText_Loaded" SearchMenuItemClicked="searchMenuItemClick"/>```_
```                                                    </StackPanel>
                                                </Grid>
                                            </Fluent:RibbonScrollViewer>```
[RibbonSearchControl.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/13686805/RibbonSearchControl.zip)

Attached is the source code for the controls and C# Data Model needed to interop to make this functionality work.

**Comment by nkrs200** [comment]
I created a control that _kind of_ replicates this feature, but it is not perfect.  **Please note:** This code works in Fluent.Ribbon Version 8, but could work in the latest version. Here is what I recommend changing in the ControlTemplate for RibbonTabControl (made in italics):
<Fluent:RibbonScrollViewer Grid.Column="1" Visibility="{Binding AreTabHeadersVisible, Converter={StaticResource boolToVisibilityConverter}, RelativeSource={RelativeSource TemplatedParent}}" HorizontalAlignment="Left" Margin="0" Width="Auto" Style="{DynamicResource RibbonTabScrollViewer}" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Disabled" IsHitTestVisible="True" IsTabStop="False">
                                                <Grid>
                                                    <Controls:SmartTabUnderline X1="34" X2="50" Stroke="{DynamicResource Fluent.Ribbon.Brushes.AccentBaseColorBrush}" StrokeThickness="2" Height="1" VerticalAlignment="Bottom" ParentRibbon="{Binding Mode=OneWay, RelativeSource={RelativeSource TemplatedParent}}" StrokeEndLineCap="Square" StrokeStartLineCap="Square"/>
                                                    <StackPanel Orientation="Horizontal">
                                                        <Fluent:RibbonTabsContainer x:Name="PART_TabsContainer" IsItemsHost="True" Height="Auto" HorizontalAlignment="Stretch" Margin="0" KeyboardNavigation.TabIndex="1" />
                                                        <Controls:RibbonSearchControl MinWidth="170" MaxWidth="170" KeyTip="Q" Loaded="SearchText_Loaded" SearchMenuItemClicked="searchMenuItemClick"/>
                                                    </StackPanel>
                                                </Grid>
                                            </Fluent:RibbonScrollViewer>

Attached is the source code for the controls and C# Data Model needed to interop to make this functionality work.
[RibbonSearchControl.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/13686832/RibbonSearchControl.zip)

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
