### ISSUE TITLE
RibbonContextualTabGroup ignores Window.ResizeMode

### ISSUE THREAD

**Issue by Pendergast4Ever** [fluentribbon/Fluent.Ribbon#223]
If the ResizeMode property of a window is set to NoResize, maximizing is deactivated by double-clicking the title bar.
RibbonContextualTabGroup ignores this setting and maximizes the window.

OnMouseDoubleClick in RibbonContextualTabGroup.cs should check if maximizing the window is allowed before the WindowState is changed.

**Comment by batzen** [comment]
Will fix it in 4.0
