### ISSUE TITLE
Ribbon button click event not working

### ISSUE THREAD

**Issue by ashisbiswas** [fluentribbon/Fluent.Ribbon#225]
I am new in wpf. I want to try your Fluent ribbon that's why downloaded it from Nuget and added it to my project. here is my code:

    <Fluent:RibbonWindow x:Class="Fluent.Sample.Foundation.Window"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"     
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"     
    xmlns:Fluent="clr-namespace:Fluent;assembly=Fluent" 
    Title="Fluent.Sample.Foundation" Width="800" Height="600" WindowStartupLocation="CenterScreen" >

    <Fluent:Ribbon>
        
        <Fluent:Ribbon.Menu>
            <Fluent:Backstage></Fluent:Backstage>
        </Fluent:Ribbon.Menu>
        
        <Fluent:RibbonTabItem Header="Tab">
            <Fluent:RibbonGroupBox Header="Group">
                <Fluent:Button Name="buttonGreen" Header="Green" Icon="Images\Green.png" LargeIcon="Images\GreenLarge.png"/>
                <Fluent:Button Name="buttonGray" Header="Grey" Icon="Images\Gray.png" LargeIcon="Images\GrayLarge.png" Click="btnClick" />
            </Fluent:RibbonGroupBox>
        </Fluent:RibbonTabItem>
    </Fluent:Ribbon>
     </Fluent:RibbonWindow>  

--------------------------------------------------------------------------------------------------------------
    **MainWindow.xaml.vb**
    Class MainWindow 
    Private Sub btnClick(sender As Object, e As RoutedEventArgs)
        MsgBox("test")
    End Sub
    End Class

But i get this error.

    Type 'Fluent.RibbonWindow' is not defined.
    Type 'Fluent.Button' is not defined.
    'btnClick' is not a member of 'TestRibbon.Fluent.Sample.Foundation.Window'.

when i change **Fluent.RibbonWindow** to **Global.Fluent.RibbonWindow **and same thing with **Fluent.Button** it works well and after some time it again show the same error and i can't understand why this error occurred **'btnClick' is not a member of 'TestRibbon.Fluent.Sample.Foundation.Window'.** I am using vs2013. Can you tell me if I have done anything wrong? Thanks

![error](https://cloud.githubusercontent.com/assets/16374475/11923379/a4ac9c4c-a7c8-11e5-827f-a01f638336c0.png)

**Comment by batzen** [comment]
You also have to replace the value of x:Class in yor xaml file when you rename your class.

**Comment by ashisbiswas** [comment]
Thanks sir for your reply. Can you please clear me what is my fault? Sorry silly question, coz I am noob at wpf. I am trying to learn it.

**Comment by batzen** [comment]
You copied the sample code. The sample code contains this
```
x:Class="Fluent.Sample.Foundation.Window"
```
in the xaml file. But your class is named ```MainWindow``` and your namespace is called ```TestRibbon```.
To make it compile again in your project you need to change
```
x:Class="Fluent.Sample.Foundation.Window"
```
to
```
x:Class="TestRibbon.MainWindow"
```

**Comment by ashisbiswas** [comment]
Now I have added **<Fluent:RibbonWindow x:Class="TestRibbon.MainWindow"** as you mentioned earlier.

But the same error occurred

    ------ Build started: Project: TestRibbon, Configuration: Debug Any CPU ------
    H:\vb\TestRibbon\TestRibbon\obj\Debug\MainWindow.g.vb(95) : error BC30456: 'btnClick' is not a     member of 'TestRibbon.TestRibbon.MainWindow'.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by batzen** [comment]
Then you might have to change it to
```
x:Class="TestRibbon.TestRibbon.MainWindow"
```

I don't have your project so I have to guess.

**Comment by ashisbiswas** [comment]
Here is my test project.
[Download Link](http://www.filedropper.com/testribbon)

**Comment by batzen** [comment]
Ok, VB.NET seems to behave different. You need to use:
```
x:Class="MainWindow"
```

**Comment by ashisbiswas** [comment]
Already tried. But no luck

**Comment by batzen** [comment]
That's the only thing I changed in your project and it works perfectly fine.

**Comment by ashisbiswas** [comment]
Now its working fine. Small typing mistk. Many many thanks for your help.

**Comment by batzen** [comment]
That reference was, of course, wrong.
