### ISSUE TITLE
Option to disable the "Minimize"-Ribbon Button & Behavior

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#230]
In our application we would like to disable/hide the "Minimize"-Button from the ribbon.

![image](https://cloud.githubusercontent.com/assets/756703/11975309/b179ab2c-a96c-11e5-8843-fe88d5d75fd3.png)

The ribbon should not be "minimized" at all, so currently we do this via the VisualTreeHelper and search for the "PART_MinimizeButton" and disable it.
To prevent the minimizing via Mouse-Double click we have a EventHandler and just set  "IsMinimized=false". It is a bit dirty, but works. 

Would you accept a PR with a property like "CanMinimizeRibbon="False", which disables the "default"-ribbon behavior?

**Comment by batzen** [comment]
I would.
Please name it "CanMinimize".
There are quite a few places that enable minimizing.
The ones I found so far:
- MenuItem from ContextMenu
- Keyboard shortcut (SHIFT + F1)
- Button

You would have to modify Ribbon and RibbonTabControl and I guess you want to change the visibility of the MenuItem in the ContextMenu and the button itself based on the value of CanMinimize.

**Comment by robertmuehsig** [comment]
New PR: https://github.com/fluentribbon/Fluent.Ribbon/pull/243

**Comment by batzen** [comment]
Merged PR.
