### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by zimmybln** [fluentribbon/Fluent.Ribbon#232]
I'm trying to run the control under Windows 10 (Visual Studio 2015, .NET 4.5.2) but the thing I get is a black window without any controls I added to the window.

Best regards

**Comment by batzen** [comment]
Have you added at least one theme to your App.xaml?

**Comment by zimmybln** [comment]
Yes. I did. I took the sample from the "Fluent Ribbon... Walkthrough.pdf":

    <Application.Resources>
        
        <ResourceDictionary Source="pack://application:,,,/Fluent; Component/Fluent.Ribbon/Themes/Office2010/Silver.xaml" />
    </Application.Resources>

When I include this I receive an error message: unable to find the resource. I tried both the latest version and the pre version of Fluent.Ribbon with same results.

**Comment by batzen** [comment]
You've got to include 
```
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2010/Generic.xaml" />
```
first.
The walk-through is outdated a lot.
I will definitely have to write a new one.

**Comment by batzen** [comment]
The showcase application is, currently, a way better and updated source for information.

**Comment by zimmybln** [comment]
I agree. I took the source from the sample and now it works fine. Thanks a lot.

Best regards.

**Comment by vac** [comment]
I'v just run into the same problem.
With the current version (5.0.1) it should be:
`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />`
