### ISSUE TITLE
Disable KeyTips when Ribbon isn't Enabled

### ISSUE THREAD

**Issue by chrisklepeis** [fluentribbon/Fluent.Ribbon#234]
I have a modal popup, and when its visible I set IsEnabled to false on the Ribbon (to prevent any tabbed navigation, etc.), however, when pressing alt when the modal is visible, the keytips are also still visible (however, not functional). Not sure if there's a way to temporarily disable the display of the keytips, but I imagine that it makes sense not to show them when the Ribbon isn't enabled.

![capture](https://cloud.githubusercontent.com/assets/16291940/12038401/c6e7a7d0-ae25-11e5-9ef7-5130375a2470.PNG)

Also, if I were to press alt + Y to select Yes in the modal popup, when the modal popup closes, the keytips in the FluentRibbon remain visible until I press alt again.

**Comment by chrisklepeis** [comment]
Not sure if this fix was included in the most recent nuget prerelease (4.0.0-dev0296)... but the key tips visibility is toggled it seems on every other "alt" key press.

E.G. 
Press alt - nothing shows... as expected
Press alt again - keytips show after a second
Press alt again - keytips remain visible
Press alt again - keytips are hidden

**Comment by batzen** [comment]
Ups, i forgot to add the check to one more place...
