### ISSUE TITLE
Window size is wrong when window is maximized, backstage is closed and window should be restored to normal size

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#236]
I just downloaded v4. It seems better. However there is a bug. 

I open and close the backstage. Then doubleclick on the edge above to minimize the window. However the minimization is not correct. The window should go to the size prior to maximization. However the window stays maximized. It just does move from its position.

This always happens after opening and closing the backstage.

**Comment by batzen** [comment]
By the way, what do you mean by "seems better".
Did you encounter any issues?

**Comment by bochelie1000** [comment]
I said "better" because I always had rendering isues with windowchrome. I was waiting for v4 to see if the problem is solved. Until niw it seems ok but i need to test it on other system before knowing for sure.  Keep up the good work. I normaly avoid opensource projects but you are doing an excelent work. Thanks for all the efoirt you put into this. I realy apreciate it.

**Comment by batzen** [comment]
You're welcome. ;-)

**Comment by bochelie1000** [comment]
I tested it on different machines now. It works nice. Greate job Batzen!!!!
