### ISSUE TITLE
Ribbon Buttons with large text cut off a few pixels

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#237]
"Multiline" Button Texts are cut off - "g" and "y" are problematic:

![image](https://cloud.githubusercontent.com/assets/756703/12111252/3cb7db42-b394-11e5-892a-251413c9bf21.png)

**Comment by batzen** [comment]
Must have missed this when I recently fixed a bug in the showcase application regarding zoom and the applied textoptions.
The TextFormattingMode was accidentally was set to Display when zoom was 1.0 but it had to be Ideal (the WPF) default.

**Comment by robertmuehsig** [comment]
:+1:
