### ISSUE TITLE
Keytips should be cancelled if Alt+Num0 is pressed

### ISSUE THREAD

**Issue by pekspro** [fluentribbon/Fluent.Ribbon#241]
In a textbox you could press Alt followed by for instance 0178 on the numeric keyboard to enter special characters. If a Ribbon is used in the same window this causes some issues.

When Alt is pressed key tips are shown. This is fine. However, when 0 is pressed on the numeric keyboard the ribbon should stop listen for keys. Both Word and Explorer has this behavior.

I’ll tried to fix this myself. I figured out that something should be done in KeyTipService.OnWindowKeyDown but then I’ll gave up :-).

**Comment by batzen** [comment]
It's not only Num0 but any "Num"-Key.

**Comment by pekspro** [comment]
Your responses are insanely fast :-)

**Comment by pekspro** [comment]
Now it works like a charm! Thanks! :-)
