### ISSUE TITLE
KeyTip not working for childs of ContentPresenter

### ISSUE THREAD

**Issue by Pendergast4Ever** [fluentribbon/Fluent.Ribbon#244]
I have some ContentPresenters in my RibbonGroupBoxes that use a DataTemplateSelector to show controls depending on the type of datacontext. The KeyTip is not working for the controls in the DataTemplates.

The reason is that KeyTipAdorner is using LogicalTreeHelper,GetChildren in the method FindKeyTips. 
The use of VisualTreeHelper would solve this problem.

**Comment by batzen** [comment]
Could you attach a small repro to this issue or fork the project, add your code to the showcase application and create a PR?
That way I can fix the bug and add it to the showcase application.

**Comment by Pendergast4Ever** [comment]
I've added a RibbonGroupBox named "Bug" to the RibbonTabItem "KeyTips" in TestContent.xaml.
The RibbonGroupBox has a DataTemplate containing the Button "BugButton" with KeyTip="B".

The changed TestContent.xaml and the DataTemplateSelector class is included. Please rename the attached file to zip (upload as zip file was rejected).

[KeyTip_ContentControl_Bug.txt](https://github.com/fluentribbon/Fluent.Ribbon/files/91859/KeyTip_ContentControl_Bug.txt)
