### ISSUE TITLE
Where is the packages folder?

### ISSUE THREAD

**Issue by RockWithBoA** [fluentribbon/Fluent.Ribbon#245]
Once there is a "packages" folder containing ControlzEx and MahApps.Metro, but this folder is missing in corrent develop branch so I got this error while building: 
> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ControlzEx, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f08b075e934b7045, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."\

Build is successful by the previous branch code containing "packages" folder.

Is this folder removed by mistake or intentionally? If the latter, how to get the build successful?

**Comment by TheMegaMatt** [comment]
You just need to restore the packages from nuget
Il 17 gen 2016 4:45 AM, "RockWithBoA" <notifications@github.com> ha scritto:

**Comment by batzen** [comment]
It seems like you are using VS 2015. Opening the solution and compiling should work perfectly fine as VS 2015 restores nuget packages automatically.

The "packages" folder is missing because we are using nuget which takes care of downloading the required binaries.

**Comment by RockWithBoA** [comment]
Hi guys, thank you for your help. I've resolved my issue by restoring the packages from nuget.

**Comment by batzen** [comment]
Glad you solved it.
