### ISSUE TITLE
RibbonGroupBox.DataContext on QAT is not appropriate

### ISSUE THREAD

**Issue by nishy2000** [fluentribbon/Fluent.Ribbon#247]
When RibbonGroupBox is added to QuickAccessToolBar, RibbonGroupBox.DataContext on QAT is not appropriate. Therefore, it will not be able to use the MVVM pattern.

Proposed code for ver. 3.6.1 is pull request #246

**Comment by batzen** [comment]
Closed as PR is already merged.
