### ISSUE TITLE
Is it possible to make SplitButton look like button?

### ISSUE THREAD

**Issue by toddams** [fluentribbon/Fluent.Ribbon#248]
While clicking on SplitButton with avaliable dropdown popup items - I want to remove them and make it look like a simple Fluent:Button. Is it possible?

**Comment by batzen** [comment]
It's currently not possible with the included ControlTemplate.
You would have to create your own Style/ControlTemplate or you could use a ContentControl in combination with a TemplateSelector to display a Button or a SplitButton depending on your current data.

**Comment by batzen** [comment]
Did that answer your question @toddams?
