### ISSUE TITLE
Enable change/hide of window title foreground

### ISSUE THREAD

**Issue by cbytte** [fluentribbon/Fluent.Ribbon#250]
Hi, 

we are trying to give another font color to the title text of the RibbonWindow (Office2013)
Assuming the title is in the non-client area of the WPF window, its foreground cannot be altered in XAML.
Hence I have been trying to hide the window title, in favor of another added TextBlock with the right color.
Windows taskbar shows the original WPF window title, and this should remain.

Through the native Win32 API it should be possible to hide the title without removing it from the taskbar:
http://stackoverflow.com/questions/709391/remove-title-bar-text-of-a-window-but-keep-status-bar-text
http://blogs.msdn.com/b/wpfsdk/archive/2008/09/08/custom-window-chrome-in-wpf.aspx

Unfortunately the SetWindowThemeAttribute native function does not hide anything here in my Fluent solution.
Is there maybe a reason that I have overlooked, or does it ring a bell?

Thanks for your help.

**Comment by batzen** [comment]
Using the windows api does not work because the titlebar is drawn by some piece of xaml.
Currently there is now way to change the foreground color for the titlebar without duplicating a lot of xaml code.

Will change the title of this issue and mark it as an enhancement.

**Comment by maurosampietro** [comment]
How is called the property to hide title?

**Comment by batzen** [comment]
?

**Comment by maurosampietro** [comment]
How to hide window title foreground?

**Comment by batzen** [comment]
It's currently not possible to do this in an easy way.

**Comment by maurosampietro** [comment]
This issue was closed with fix #249, so in wondered.. 
Now i see you flagged this as enhancement on milestone 5.0

**Comment by batzen** [comment]
It was referenced by #249, not closed. ;-)
