### ISSUE TITLE
StatusBarItem HorizontalAlignment="Stretch" not working

### ISSUE THREAD

**Issue by andirinli** [fluentribbon/Fluent.Ribbon#252]
in `<fluent:StatusBar ....`

```xml
            <fluent:StatusBarItem HorizontalAlignment="Stretch" BorderBrush="Yellow" BorderThickness="5">
                <Button>Teeeeeeest</Button>
            </fluent:StatusBarItem>
```

its not showing. 
but if i change **HorizontalAlignment="Left"** or **HorizontalAlignment="Right"** its showing.
what am i doing wrong?

**Comment by batzen** [comment]
Will have a look at it.

**Comment by batzen** [comment]
I found out why this happens.
The Fluent:StatusBar contains a custom StatusBarPanel which automatically sorts children and collapses everything which has a HorizontalAlignment != left or right.

I don't completely know why this was done in 2010 as i was not part of this project at that point in time.
But from my findings i can tell that the custom StatusBarPanel automatically collapses items based on the already used width of all items. Thus taking that burden from everyone using it.

I my opinion the whole statusbar story (styles, templates, classes) could need some refactoring, but as i never had problems with it, it's not very high on my priority list.

If you absolutely need HorizontalAlignment=stretch you can still use a regular StatusBar, although you would loose the contextmenu etc..

**Comment by batzen** [comment]
Did that answer your question @andirinli?

**Comment by andirinli** [comment]
yes.
HorizontalAlignment=stretch  is not big deal for now.
thanks
