### ISSUE TITLE
Icons of buttons not aligned correctly in Office 2013 theme

### ISSUE THREAD

**Issue by floele-sp** [fluentribbon/Fluent.Ribbon#253]
See attached screenshot. The icon of the SplitButton is 1 px more to the right than the icons of other buttons (Button, DropDownButton). This probably is because of the added border. I'm not quite sure whether the SplitButton or the other buttons need to be fixed though. I believe the SplitButton should keep the 1px distance to it's border and all other buttons should use 2 px distance? 

![buttons](https://cloud.githubusercontent.com/assets/15671468/12544565/b00976da-c33b-11e5-8c73-f45c3fe6652e.png)

When comparing to Office 2013, it indeed looks like the margin can be increased because it's more than 1 px (in fact 3 px) here:

![25-01-2016 08-20-21](https://cloud.githubusercontent.com/assets/15671468/12544685/99d39566-c33c-11e5-8dde-424ca4703bbc.png)

**Comment by batzen** [comment]
I agree that it's off but honestly I am kind of fed up with fixing pixel issues...
Especially in SplitButton it's very difficult to get it right in every condition.

I might fix this, but it's very (very, very, very) low on my priority list.

**Comment by floele-sp** [comment]
If I look into that myself, which further conditions should I keep in mind?

**Comment by batzen** [comment]
- Zooming (because that changes TextFormattingMode)
- Different sizes of the control(s) (Small, Middle, Large)
- .NET 4.0 (but that's not really important as i was thinking of dropping support for it in the near future)

**Comment by batzen** [comment]
Any news on this one?

**Comment by floele-sp** [comment]
Didn't get time to look into this yet. It's still on my mind though.
