### ISSUE TITLE
startscreen immediately visible

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#259]
When you start any application and you use the StartScreen you want it to show first.
Nothing should be visible before you close it.

Currently depending on how lightweight is the content of the startscreen its visibility is delayed that is the main window content is showed and then the startscreen is opened.

Is there a way you can think of to correct this or give me an hint?

**Comment by batzen** [comment]
See https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/Backstage.cs#L276
and the comment here https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/Backstage.cs#L476

There is not much we can do here if the control is not loaded.

**Comment by maurosampietro** [comment]
ok, i try to defer content loading by my side then.
