### ISSUE TITLE
Little style bug in Office 2013 theme

### ISSUE THREAD

**Issue by Dvornik** [fluentribbon/Fluent.Ribbon#26]
Different font settings between Fluent:DropDownButton and Fluent:Button.
Different lable position:

![image](https://cloud.githubusercontent.com/assets/1733249/5201485/a63f77c8-7583-11e4-80ba-5f28a8dba8aa.png)

**Comment by batzen** [comment]
Any news on this one?

**Comment by batzen** [comment]
No reaction, closed.
