### ISSUE TITLE
When font is increased in Windows ribbon items text is cut

### ISSUE THREAD

**Issue by xperiandri** [fluentribbon/Fluent.Ribbon#260]
Fluent Ribbon does not take into account Windows font size while height calculation of its items.

<img width="366" alt="fluent ribbon large font" src="https://cloud.githubusercontent.com/assets/2365592/12655316/0641505a-c601-11e5-893c-eb1d7a80e54b.png">
<img width="635" alt="large windows font" src="https://cloud.githubusercontent.com/assets/2365592/12655370/4a587b88-c601-11e5-861f-e03aef12b6f7.png">

This happens because you use three StackPanels one inside another in button template.
Use one grid instead.

**Comment by batzen** [comment]
If it's that easy and you already had a look, why not create a PR which fixes the issues?

**Comment by xperiandri** [comment]
Fixed?

**Comment by batzen** [comment]
Did you?
