### ISSUE TITLE
Add logo to right side of fluent ribbon or RibbonTabItem

### ISSUE THREAD

**Issue by sharethl** [fluentribbon/Fluent.Ribbon#261]
Is it possible to add a image on the right side of ribbon?
Thanks.

![image](https://cloud.githubusercontent.com/assets/1747556/12690617/c6356ae8-c6b2-11e5-8227-8ad69f12ed8b.png)

**Comment by batzen** [comment]
In theory it is possible.
You could add a RibbonGroupBox without a header and add your logo to that one.

I don't know how to force the containers involved to show your content at the rightmost position.
The problem with the involved containers is that they are not supposed to layout content in that way.

**Comment by batzen** [comment]
Did that answer your question?

**Comment by sharethl** [comment]
Well, kind of. So no solutions so far.
Thanks any way :)

By Tiny Keyboard
