### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by PeterForstmeier** [fluentribbon/Fluent.Ribbon#265]
Hi,
in the sample code there is a missing reference  using WindowChrome = ControlzEx.Microsoft.Windows.Shell.WindowChrome;
Update package can't resolve the *.dll.
Also there are soms (i think) strange lines of code as for example:
 name += $" ({headeredControl.Header})"; What's about the '$' sign.
Thanks
Peter

**Comment by batzen** [comment]
Hi Peter,

you have to restore the nuget packages and you have to use Visual Studio 2015 to compile the solution.
Visual Studio 2015 should also restore the nuget packages automatically when you compile.

The "$" is new in C# 6 and allows string interpolation.
In the past you had to write string.Format("Value: {0}", value) and with string interpolation you can write $"Value: {value}".

**Comment by PeterForstmeier** [comment]
Hi,

is there any version for Visual Studio 2013?

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 7. Februar 2016 21:23
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] Sample (#265)

 

Hi Peter,

you have to restore the nuget packages and you have to use Visual Studio 2015 to compile the solution.
Visual Studio 2015 should also restore the nuget packages automatically when you compile.

The "$" is new in C# 6 and allows string interpolation.
In the past you had to write string.Format("Value: {0}", value) and with string interpolation you can write $"Value: {value}".

**Comment by batzen** [comment]
The last version not requiring Visual Studio 2015 as the development IDE is currently at https://github.com/fluentribbon/Fluent.Ribbon/tree/master
But it's the last version you can compile using Visual Studio 2013.
If you just want to try the showcase application you can grab it from https://ci.appveyor.com/project/batzen/fluent-ribbon/build/artifacts or more specifically from https://ci.appveyor.com/api/buildjobs/hsppjpys6nfs4l1i/artifacts/build/Fluent.Ribbon.4.0.0-dev0345.zip

**Comment by PeterForstmeier** [comment]
Thanks a lot

Peter

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Montag, 8. Februar 2016 07:58
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] Sample (#265)

 

The last version not requiring Visual Studio 2015 as the development IDE is currently at https://github.com/fluentribbon/Fluent.Ribbon/tree/master
But it's the last version you can compile using Visual Studio 2013.
If you just want to try the showcase application you can grab it from https://ci.appveyor.com/project/batzen/fluent-ribbon/build/artifacts or more specifically from https://ci.appveyor.com/api/buildjobs/hsppjpys6nfs4l1i/artifacts/build/Fluent.Ribbon.4.0.0-dev0345.zip
