### ISSUE TITLE
Ribbon.CanMinimize - NullRef & Initial rendering is wrong

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#268]
I found a bug in the feature that I introduced [here](https://github.com/fluentribbon/Fluent.Ribbon/pull/243).

I created a very simple ribbon and set the "CanMinimize"-property to false, e.g.:

        <fluent:Ribbon ...
                                CanMinimize="False"

At this point VS will already point to a null ref exception, this can be easily fixed:

        private static void OnCanMinimizeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var ribbon = (Ribbon)d;

            if (ribbon.TabControl != null) 
            {
                ribbon.TabControl.CanMinimize = ribbon.CanMinimize;
            }
        }

Link to the [actual code](https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/Ribbon.cs#L1055) line.

Either I forgot the ribbon:TabControl is null check or the code has changed. Now the exception is gone, but the rendering will still show the closing icon.

![image](https://cloud.githubusercontent.com/assets/756703/13048352/9992a36c-d3e5-11e5-9e4a-d5b2b281858b.png)

The problem is, that I only set the visibilty on this button when the property has changed - see [here](https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/RibbonTabControl.cs#L674).

Do I need to change the .xaml files as well to render the "intial" (without changing the CanMinimize-Property from true to false) or do you have a better solution?

To reproduce this issue just set the CanMinimize-Property to false in the Ribbon.Showcase, e.g.

        <Fluent:Ribbon AutomaticStateManagement="True" CanMinimize="False"
                       x:Name="ribbon">

I'm pretty sorry that "my" feature may cause you trouble. I try to fix it as soon as possible and hope you could point me in the right direction.

**Comment by batzen** [comment]
No worries. 
It's just a missing null-check.
As this gets more complicated now, we should remove OnCanMinimizeChanged from RibbonTabControl and handle visibility of PART_MinimizeButton in XAML.

Setting the visibility of controls in code behind just doesn't feel right in this case. ;-)

Do you want to fix this, or should I?

**Comment by robertmuehsig** [comment]
I would like to fix it, but maybe I need some guidiance. 

So, instead of this line: https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Office2013/Controls/RibbonTabControl.xaml#L343 

It should be something like this:
    <Fluent:ToggleButton x:Name="PART_MinimizeButton"
                                             Margin="0"
                                             Width="22"
                                             Height="22"
                                             Size="Small"
                                             Style="{DynamicResource RibbonTabControlToggleButtonStyle}"
                                             IsChecked="{Binding Path=IsMinimized, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}}"
                                             Visibility="{Binding Path=CanMinimize, Converter={StaticResource boolToVisibilityConverter}}" />

Would this work? Where does the "TemplateBinding HasItems" pointing to?

**Comment by batzen** [comment]
Something like that, yeah.

TemplateBinding refers to the control being templated.
So for CanMinimize you would have to use TemplateBinding instead of Binding, as Binding would refer to the current DataContext and not the the control itself.
RelativeSource TemplatedParent has to be used in cases where the binding should be TwoWay and TemplateBinding doesn't work there. I don't know why microsoft decided to disallow TwoWay for TemplateBinding...

Please don't forget do apply your changes to all themes. ;-)
