### ISSUE TITLE
Show underscore of header text on RibbonTabItem

### ISSUE THREAD

**Issue by nishy2000** [fluentribbon/Fluent.Ribbon#269]
I set "Test_test" to header text on RibbonTabItem. But displayed text is "Testtest".
RibbonTabItem has "KeyTip" attribute. Then an underscore of header text will not be used for access keys. so I think underscore should always be displayed.

Proposed code for ver. 3.6.1 is pull request #270

**Comment by batzen** [comment]
Merged.
