### ISSUE TITLE
Change Theme at Runtime with Prerelease

### ISSUE THREAD

**Issue by chrisklepeis** [fluentribbon/Fluent.Ribbon#272]
I noticed one issue with the pre-release. Since I'm using MahApps, I allow users to switch the theme, using the MahApps themes. When a user changes the theme, I set this:

`Application.Current.Resources["RibbonThemeColorBrush"] = new SolidColorBrush(Colors.Red);`

So that fluent ribbon follows the selected theme, at least with the menu background color. With the prerelease, the main menu button does change color properly, but the backstage menu background doesn't. Maybe I'm trying to change the theme at runtime the wrong way?

Thanks for all your hard work on this project, it's much appreciated.

**Comment by batzen** [comment]
That's a bug. Will have a look at it.
