### ISSUE TITLE
Office 2016 themes

### ISSUE THREAD

**Issue by frostieDE** [fluentribbon/Fluent.Ribbon#281]
Is support for the new 2016 themes planned? If not, I would like to propose this new theme.

**Comment by batzen** [comment]
I thought about dropping support for the Office 2010 theme to get more time to work on refactoring the office 2013 theme to allow better colorization.
In essence office 2016 is just office 2013 with different colors.

Deprecating office 2010 is a step which requires community consent. After 4.0 is release i will start a poll asking people what they'd like me to do:
- Keep office 2010 => leave everything as it is
- Deprecate office 2010 => introduce better colorization options for office 2013
- Deprecate office 2010 and windows 8 => Major refactoring of theming, faster releases, faster implementation of new features, unit-tests, better integration with MahApps

What would you choose?

**Comment by robertmuehsig** [comment]
I would choose the last option, because the Windows 8 Theme is not that different from the Office 2013 Theme and the older themes are... well... old. 
But I like new shiny things anyway ;)

**Comment by frostieDE** [comment]
:+1: I would agree with @robertmuehsig

**Comment by sfmc** [comment]
Also voting for this option! :+1:

**Comment by batzen** [comment]
Ok, i will try to start a poll somewhere this weekend.

**Comment by batzen** [comment]
You can vote here: https://github.com/fluentribbon/Fluent.Ribbon/issues/282

**Comment by batzen** [comment]
Will close this as there won't be any Office version specific themes anymore. Instead you will get better colorization options as soon as the vote on the future direction is closed.
