### ISSUE TITLE
Future direction of this library [Please vote]

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#282]
As I got limited time to spend on this library I would like you, the community and users of this library, to vote for it's future direction.

I will propose a few options you can vote on using the new issue +1/-1 system.

The reason for this poll/question is that the different themes come with a huge maintenance cost.
I have to maintain 3 different control templates, one for each theme and control.

Another reason to get rid of the Office 2010 and Windows 8 themes is that the RibbonWindow requires a lot of maintenance for these themes.

**Comment by batzen** [comment]
Option 1:
Keep Office 2010 and Windows 8 themes
=> Leaving everything as it is.

**Comment by batzen** [comment]
Option 2:
Deprecate Office 2010 and Windows 8 themes
=> - Introduce better colorization options for Office 2013 theme.
   - Refactor Ribbon, RibbonTitleBar and RibbonWindow so that RibbonTitleBar gets a part of RibbonWindow instead of Ribbon. This should improve integration with other libraries.
   - Faster releases.

**Comment by batzen** [comment]
Option 3:
Option 2 + deprecate .NET 4.0
- UnitTests for some parts of the library.

**Comment by jdeksup** [comment]
Ok for option 2. .net 4 is still interesting for Windows XP (and maybe Vista, i dont know if it support 4.5)

**Comment by QuantumDeveloper** [comment]
4 must gone together with XP

**Comment by robertmuehsig** [comment]
Vista supports 4.0.
If dropping .NET 4.0 support would make your life easier (besides writing unit tests for some parts of the lib ;)) - go for it. .NET 4.0 is not even supported by Microsoft itself and no even mentioning XP.

**Comment by pekspro** [comment]
I’m using the Windows 8 theme and it would be sad to see that go. However, I’m not using the RibbonWindow. Also I’m not using the .NET 4.0 so I don’t mind if that gets removed.

That said I’m quite happy how things are working right now. So I could use an older version if support for Windows 8 theme is dropped.

**Comment by batzen** [comment]
@robertmuehsig even .NET 4.5 is no longer supported. just 4.5.2 and up... it's not that i couldn't write unit tests already, but i only have limited time to spend on this library. and testing takes a LOT of time when you have to test .NET 4.0, .NET 4.5 on windows 7 (DWM on/off), windows 8, windows 8.1, windows 10, windows 10 1511, single screen, multiple screen, multiple screen (different resolutions) etc.. unit tests won't help much on this testing as i don't know how to test visual glitches. ;-)

@pekspro Essentially, the windows 8 theme is "just" a mixture of office 2010 and office 2013. as i would introduce more colorization options like in office or MahApps or materialdesign. most likely something based on accent colors etc. you should be able to easily get a windows 8 like look. i just don't want to maintain 3 control templates. especially the office 2010 ones are a mess because of all those rounded borders etc.

**Comment by floele-sp** [comment]
Having already moved to the Office 2013 theme, I don't mind deprecating older themes in order to put more effort into the newer ones. 
Dropping .NET 4.0 support should also be done at some point, in our case we can't do so just yet. Give it a a few more months of lifetime, then dropping should be fine though.

**Comment by huoyaoyuan** [comment]
There seems to be performance issues with Backstage of Office 2013 theme; but in Office 2010 and Windows 8 theme, it just appears simply without animation. That's the main reason that I'm using Office 2010 theme.

**Comment by batzen** [comment]
@huoyaoyuan If the Backstage animation causes performance issues on your side you can use IsOpenAnimationEnabled="False" on your BackstageTabControl.

**Comment by djmiller9975** [comment]
I'd like to be able to change the background color of the backstage.  No matter what I do, It's the same color blue.  I appreciate all the work you've already done, so you if you let go of supporting the older themes, that seems reasonable to me.  Your ribbon works great with mahapps, so if you wanted to track with their themes, that would be great.

**Comment by batzen** [comment]
@djmiller9975 You can change the theme color:
```
<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">#2B579A</Color>
```

**Comment by cetris** [comment]
Please keep Office 2010 and Windows 8 themes - users like them more as the newer Office 2013/2016 themes - thanks a lot!

**Comment by cetris** [comment]
Is there a possibility to set the height and width of the dorp/down - popup of the InRibbonGallery?

**Comment by maurosampietro** [comment]
It seems like user suggestion are only driven by private interest in avoiding some future work. Who uses latest themes and framework 4.5 dont mind dropping 2010 and framework 4.0. Who cannot or dont want to update to that stuff want the old stuff to be maintained.

I personally think only latest framework and modern easy to maintain themes should be kept since this is an open source project and developers use their free time and are only driven by passion. They dont live with this.
Anything they claim make their maintenence of this project easier and speed up building and catch up with new features is the right thing to do. 

Since i use old 2010 theme and franework 4 i will make my part and do anything it takes to continue working with this library.

**Comment by batzen** [comment]
@maurosampietro I get your point, but i asked the community and respect their votes.

**Comment by batzen** [comment]
So the decision is made for option 2.
Thank you all for voting!

**Comment by wstaelens** [comment]
@robertmuehsig 

> Vista supports 4.0 & all version above.
 If dropping .NET 4.0 support would make your life easier (besides writing unit tests for some parts of the lib ;)) - go for it. .NET 4.0 is not even supported by Microsoft itself and no even mentioning XP.

A LOT of enterprises still have XP (I mean thousands of PCs, trust me, I see it on a daily base). Keeping .NET 4.0 makes life at Enterprise so much easier ;-) (but indeed would be better to see it gone)
