### ISSUE TITLE
Right pane in application menu gets centered if left pane contains lots of items

### ISSUE THREAD

**Issue by pekspro** [fluentribbon/Fluent.Ribbon#283]
I’m using the application menu to show recent items. If I have a few items in the recent list and several normal menu items, the recent list could be centered:

![rightpanecentered](https://cloud.githubusercontent.com/assets/3163293/13903679/3d645bba-ee86-11e5-876a-a761bab2fe8b.png)

Seems to be like this in all themes. If this could be fixed before the Windows 8 theme is removed, I would be very happy :-).
## 
### Environment
- Fluent.Ribbon Latest source
- Theme All
- Windows 10
- .NET Framework 4.5

**Comment by batzen** [comment]
Decided that this has to wait till some other version.

There is a workaround you can use:
Set MaxDropDownHeight on your ApplicationMenu to something that fits your sizing needs.

**Comment by pekspro** [comment]
That’s works for me :-). Thanks for another brilliant answer :-).

**Comment by batzen** [comment]
The issue remains, as I had no plans to deprecate the applicationmenu. Just the office 2010 and windows 8 themes. ;-)

**Comment by batzen** [comment]
This got fixed by https://github.com/fluentribbon/Fluent.Ribbon/issues/446
