### ISSUE TITLE
MaterialDesign DialogHost issue with FluentRibbon

### ISSUE THREAD

**Issue by chrisklepeis** [fluentribbon/Fluent.Ribbon#285]
Using:
- Latest stable release of Fluent Ribbon
- .Net 4.6.1
- Office 2013 theme
- Windows 7

After my issue posted here https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/299 , I tried just using a global DialogHost ("RootDialog") that wraps my entire application, in my main xaml window file.

When using this with Fluent Ribbon, the main menu button does not work properly - it looks like it gets clicked but the menu doesn't slide out using the Office 2013 theme in Fluent Ribbon.I'm not sure if the issue is with MaterialDesign or Fluent Ribbon but I will be posting this issue in both places.

Sample project attached.

[MaterialRibbonDemo.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/185915/MaterialRibbonDemo.zip)

**Comment by ButchersBoy** [comment]
MD issue: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/307
Sample repo: https://github.com/chrisklepeis/MaterialRibbonDemo

Had a look at this, I can also reproduce by adding a Grid/AdornerDecorator directly to the root of a window (which is effectively what MD.DialogHost does):

```
    <Grid>
        <AdornerDecorator>
            <ContentPresenter>
                <ContentPresenter.Content>
                    <fluent:Ribbon Grid.Row="0" x:Name="ribbon">
                        <fluent:Ribbon.Menu>
                            <fluent:Backstage x:Name="backstage" Header="Menu (doesn't work)">
                                <fluent:BackstageTabControl x:Name="backstageTab">
                                    <fluent:Button fluent:KeyTip.Keys="L" Header="Logout" />
                                    <fluent:Button fluent:KeyTip.Keys="X" Header="Exit" />
                                </fluent:BackstageTabControl>
                            </fluent:Backstage>
                        </fluent:Ribbon.Menu>
                    </fluent:Ribbon>
                </ContentPresenter.Content>
            </ContentPresenter>
        </AdornerDecorator>
    </Grid>
```

Is this something to do with the way fluent operates with an expected adorner?

**Comment by batzen** [comment]
Thanks for having a look @ButchersBoy 
Will have a look @chrisklepeis
