### ISSUE TITLE
Maxmized Window get smaller

### ISSUE THREAD

**Issue by HamburgerJungeJr** [fluentribbon/Fluent.Ribbon#289]
Hi, 

I have a Problem with the Ribbon Window.
A few Minutes after I maximized the Window it gets smaller with a black border.
![screen](https://cloud.githubusercontent.com/assets/11501266/14059988/5afcc738-f355-11e5-93ba-e0089f34f7a5.jpg)
### Environment
- Fluent.Ribbon **latest dev (installed today with NuGet)**
- Theme **Office 2013**
- Windows **10 Pro**
- .NET Framework **4.5**

**Comment by batzen** [comment]
Will have a look at it after 3rd of april. Anything going on in your application when the black border appears (something like reported unresponsive by windows)?
Which exact version of Fluent.Ribbon are you using?

**Comment by HamburgerJungeJr** [comment]
I'm using v4.0.30319

**Comment by batzen** [comment]
There is no such version of Fluent.Ribbon.

**Comment by HamburgerJungeJr** [comment]
Right. Sorry

I've installed it from here
https://www.nuget.org/packages/Fluent.Ribbon/4.0.0-dev0345

**Comment by chdft** [comment]
Did this happen after tablet mode was enabled?
I can't reproduce it consistently, but this happens sometimes on my Surface, but only when tablet mode is enabled for some time. I've observed that this happens to other applications that modify their window chrome (like Word, Firefox, etc.) too, which makes me think that this is a bug in Windows 10.

**Comment by HamburgerJungeJr** [comment]
I cannot enable the Tabletmode on my PC. 
It does not happen in any other application.

**Comment by batzen** [comment]
So you just start your app, maximize the window, leave the app alone and the black border appears after some time?

**Comment by HamburgerJungeJr** [comment]
Correct

**Comment by batzen** [comment]
Are you on twitter? Finding out what causes issues with the window chrome can be very difficult and i don't want to have such a lengthy issue discussion again.
And we could talk in german ;-)

**Comment by batzen** [comment]
Feel free to write me a message on twitter then.

**Comment by batzen** [comment]
@HamburgerJungeJr Still waiting for you on twitter.
