### ISSUE TITLE
BackStageTabItem leftmousedown event not firing

### ISSUE THREAD

**Issue by djmiller9975** [fluentribbon/Fluent.Ribbon#291]
--
### Environment
Windows 7, Visual Studio 2013 Professional

- Fluent.Ribbon __v3.6.1.236__
- Theme __Office2013__
- Windows __7__
- .NET Framework __4.5__

The leftmouseup event fires, but I can't get the leftmousedown event to fire.  Why doesn't the BackstageTabItem have a click event?

**Comment by batzen** [comment]
LefMouseDown was set to handled, which I consider wrong. Will fix that.

It has no click event because it also has no ClickMode as ButtonBase has.
