### ISSUE TITLE
Custom icon sizes

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#298]
This is maybe related to #286.

Is there a way we can define custom (bigger than LargeIcon) icon sizes?

**Comment by batzen** [comment]
There is currently no way to that.
As noted in #286 @HendrikLynx can start implementing it as soon as i removed the office 2010 and windows 8 themes.

**Comment by thepostman2** [comment]
Meanwhile there is a workaround if you want bigger LargeIcon on your Fluent:Button. 
You can redefine LargeSize for the IconPresenter (which holds the icon) using a style definition, see example below:

 Example:

          <Style x:Key="FluentXtraLargeImageButton" TargetType="Fluent:Button">
            <Style.Resources>        
              <Style TargetType="Fluent:IconPresenter">
                <Setter Property="LargeSize" Value="120,120"/>
              </Style>
            </Style.Resources>
          </Style>

And:

          <Fluent:Button  Style="{StaticResource FluentXtraLargeImageButton}"
              LargeIcon="My Extra Big Icon.png"
              Size="Large"/>

**Comment by batzen** [comment]
Was fixed in 10.1
