### ISSUE TITLE
Rename Office 2013 theme to Generic

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#302]
As a result of the vote from #282 the Office 2013 theme will be renamed to generic.

This means there should be no trace of the name Office 2013 anymore.

**Comment by maurosampietro** [comment]
Not sure it is the right thing to do,
You should reference the Office2013.Xaml from Generic.xaml

The main advantages are that we can still have a self explaining file name for Office2013 theme and you can more easily change the default theme to a new one in the future just by changing the reference to the the resource dictionary inside Generic.xaml file

**Comment by batzen** [comment]
There won't be different themes anymore. Just different color schemes.
