### ISSUE TITLE
Combobox items will be drawn above each other on scroll down

### ISSUE THREAD

**Issue by robdg80** [fluentribbon/Fluent.Ribbon#305]
--
### Environment

- Fluent.Ribbon [__v4.0.3.394__](https://www.nuget.org/packages/Fluent.Ribbon/4.0.3.394)
- Theme __Office2013__
- Windows __7__
- .NET Framework __4.0__

Combobox shows items wrong.

on Scrolling a large list, the items would be drawn above each other:
![image](https://cloud.githubusercontent.com/assets/12692680/14600527/65570742-055d-11e6-8f19-2ea024bc43f8.png)

![image](https://cloud.githubusercontent.com/assets/12692680/14600541/782eb37e-055d-11e6-9ff6-8dd3eb06e1e4.png)

When scrolbar is at the top, all is fine:
![image](https://cloud.githubusercontent.com/assets/12692680/14600576/a53adca8-055d-11e6-967d-e0f8268e92e6.png)

This problem occures in the version from GitHb from Today (2016-04-18) or from actual version on [NuGet](https://www.nuget.org/packages/Fluent.Ribbon/4.0.3.394).

**Comment by batzen** [comment]
Will have a look.

**Comment by batzen** [comment]
I can't reproduce your exact problem. On my machine the scrolling is totally broken.
I guess the problems are related to each other.
Could you try to reproduce your issue with the latest sources from the develop branch?

**Comment by robdg80** [comment]
Thank you for your testing.

I will try to reproduce this tomorrow.
Am 19.04.2016 18:51 schrieb "Bastian Schmidt" <notifications@github.com>:

**Comment by Macry** [comment]
I'm also facing the problem and here are the codes to reproduce it:

MainWindow.xaml
```
<fluent:RibbonWindow x:Class="Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Test"
        xmlns:fluent="clr-namespace:Fluent;assembly=Fluent"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <fluent:Ribbon >
            <fluent:RibbonTabItem>
                <fluent:RibbonGroupBox>
                    <fluent:ComboBox ItemsSource="{Binding Fonts}"/>
                </fluent:RibbonGroupBox>
            </fluent:RibbonTabItem>
        </fluent:Ribbon>
    </Grid>
</fluent:RibbonWindow>
```

MainWindow.xaml.cs
```
    public partial class MainWindow : RibbonWindow
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MainViewModel();
        }
    }
```

MainViewModel.cs
```
    class MainViewModel
    {
        internal MainViewModel()
        {
            Fonts = System.Windows.Media.Fonts.SystemFontFamilies.Select(fontFamily => fontFamily.ToString());
        }

        public IEnumerable<string> Fonts { get; set; }
    } 
```

when scroll down,it occurs
![image](https://cloud.githubusercontent.com/assets/11499203/14660826/3d75f9de-06db-11e6-8aab-845548a64e11.png)

### Environment

- Fluent.Ribbon v4.0.3.394(Nuget)
- Theme Office2013
- Windows 7 Ultimate X64
- .NET Framework 4.5.2

**Comment by robdg80** [comment]
With the code from latest develop branch the problem is solved.

An unattractiveness is now, if an element is selected and the combobox is opened, the scrollbar is always at the end. As far as I can remember the normal combobox behaviour is that the selected element is in the view.

**Comment by batzen** [comment]
Ok, my fix fixes the weird drawing but also destroys virtualization.

Will have to find different solution.

**Comment by batzen** [comment]
I pushed the changes for #309, please check how it works for you.

**Comment by robdg80** [comment]
Yes, this is working if I use your suggestion:

On the ComboBox:

`ScrollViewer.CanContentScroll="False"`

itemspanel:

```
<Fluent:ComboBox.ItemsPanel>
    <ItemsPanelTemplate>
        <Fluent:GalleryPanel GroupBy="Tag"
                                ItemContainerGenerator="{Binding ItemContainerGenerator, RelativeSource={RelativeSource FindAncestor, AncestorType=ComboBox}}" />
    </ItemsPanelTemplate>
</Fluent:ComboBox.ItemsPanel>
```

**Comment by batzen** [comment]
Glad to hear that it works for you.
