### ISSUE TITLE
Crash when using normalize / maximize

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#306]
--
### Environment

- Fluent.Ribbon v4.0.2.384
- Theme: Office 2013
- Windows 10
- .NET Framework .NET 4.5 (but runtime is 4.6)

![image](https://cloud.githubusercontent.com/assets/1246444/14634236/5c0fb6e2-0621-11e6-9964-ed1c29cf06d6.png)

**Comment by batzen** [comment]
That looks like you are using multiple threads.
The ribbon itself should not start any new threads.
Could you provide a repro for that issue? I can't reproduce it locally.

**Comment by GeertvanHorrik** [comment]
I tried checking out the callstack, but it didn't lead to anything useful. The thing is that I just used the Normalize button, but it might be pure coincidence. Having a hard time reproducing it myself now as well.

**Comment by batzen** [comment]
Were you able to find out what's causing this?

**Comment by GeertvanHorrik** [comment]
No, I couldn't reproduce, let's close for now.
