### ISSUE TITLE
State loading too verbose

### ISSUE THREAD

**Issue by RaceRalph** [fluentribbon/Fluent.Ribbon#311]
I set AutomaticStateManagement property to false in my WPF application, because I don't need to save the state of the Ribbon.  Whenever I close the application the following line is written to the error output:

    State not saved to isolated storage. Because automatic state management is disabled.

State management has been intentionally disabled and it is NOT an error condition and it shouldn't be written to the diagnostic output.   Over time as users run and close the application a few times a day, hundreds of such lines are written to the log file which is only intended to contain crash information for my application.

Is there any way to disable that message?

--
### Environment

- Fluent.Ribbon __v4.0.3__
- Theme __Office2013__
- Windows __7__
- .NET Framework __4.0__

**Comment by batzen** [comment]
Will convert those trace statements to debug statements.
