### ISSUE TITLE
QuickAccessBar position

### ISSUE THREAD

**Issue by toddams** [fluentribbon/Fluent.Ribbon#312]
--
### Environment

- Fluent.Ribbon v4.0.3.394
- Theme Office2013
- Windows 10
- .NET Framework 4.5.2

I got a strange issue. My quickaccessbar always appears under the ribbon, so I have to move it to the top manually, Is there any property to set it's position?

**Comment by batzen** [comment]
The quickaccessbar should only be displayed below the ribbon if you have set `ShowQuickAccessToolBarAboveRibbon="False"` or you moved it below manually, closed your window and have `AutomaticStateManagement="True"`.

The default value for both mentioned options is `True`. So it should be displayed above the ribbon by default.

**Comment by toddams** [comment]
I tried ot set ShowQuickAccessToolBarAboveRibbon to **True ** - no effect.

But AutomaticStateManagement="False" fixed the issue

**Comment by batzen** [comment]
ShowQuickAccessToolBarAboveRibbon is ignored if you moved it below and never up again manually. That's because user state is handled after everything else is setup.
