### ISSUE TITLE
Window state buttons not updating to Windows 10 look / feel

### ISSUE THREAD

**Issue by morganenglish** [fluentribbon/Fluent.Ribbon#313]
Hi Batzen,

Great job on keeping this library up to date. 

It seems in build 4.0.3.394 the generic (Office 2013?) theme doesn't update the Window state buttons in Windows 10. In the showcase exe clicking Tests > Open Regular-Window shows them correctly (Below example shows the difference, the one in front being Windows 10 and the one behind being the generic ribbon window).

Is this an oversight, or is there a setting / theme I haven't applied? 

![image](https://cloud.githubusercontent.com/assets/6385227/14974525/0cdecd0a-1135-11e6-8a8f-6ef525617c3c.png)
## 
### Environment
- Fluent.Ribbon 4.0.3.394
- Theme Generic (Office 2013?)
- Windows Win 10
- .NET Framework 4.5

**Comment by batzen** [comment]
Those buttons are custom styled buttons as we can't rely on windows/wpf to render them they currently look the same on every OS version. Will think about a way to get them updated. One problem on updating them is that microsoft prevents the proper detection of the OS version since windows 10...

**Comment by znakeeye** [comment]
Getting the OS version should be possible in Windows 10, but you have to include a manifest and then use the `VerifyVersionInfo` method. More information [here](https://stackoverflow.com/a/36158739/419761).
