### ISSUE TITLE
ComboBox drop down scrolling problem

### ISSUE THREAD

**Issue by RaceRalph** [fluentribbon/Fluent.Ribbon#314]
The attached screenshot explains everything.
Initially the drop down content of a combo box is correct.  When I start scrolling it, the initial content stays and is overwritten by further items.
It worked in version 3.5.1.198.

--
### Environment

- Fluent.Ribbon __v4.0.3__
- Theme __Office2013__
- Windows __7__
- .NET Framework __4.0
![fontlist](https://cloud.githubusercontent.com/assets/8450609/15039281/a43263dc-12a3-11e6-89d6-a526807db18d.png)

4.0__
![Uploading fontlist.png…]()

**Comment by batzen** [comment]
You are right. This issue was already reported in #305 and is fixed with #309.
