### ISSUE TITLE
Menu button gets blurry

### ISSUE THREAD

**Issue by frostieDE** [fluentribbon/Fluent.Ribbon#315]
When enlarging the font inside the demo application, the menu button (backstage button?) gets blurry.

![fluent](https://cloud.githubusercontent.com/assets/3764924/15053147/73465cc0-1301-11e6-8a45-2a4521afb150.png)

--
### Environment

- Fluent.Ribbon v5.0.0.0 (current develop branch @9c65f30)
- Windows 10 Build 1511
- .NET Framework v4.5

**Comment by batzen** [comment]
Will have a look at that issue.
