### ISSUE TITLE
Backstage Component binding with an ObservableCollection

### ISSUE THREAD

**Issue by robingood** [fluentribbon/Fluent.Ribbon#316]
![capture](https://cloud.githubusercontent.com/assets/1123371/15152500/bd659ca8-16d5-11e6-9ad3-30e496415e21.JPG)
Hello

I want to use the Backstage with an ObservableCollection, however this doesnt seem to work.

Here is my WPF configuration

```
 <!--Backstage-->
        <fluent:Ribbon.Menu>
            <fluent:Backstage x:Name="ApplicationMenu">
                <fluent:BackstageTabControl ItemsSource="{Binding Path=DataContext.ApplicationMenuItems, ElementName=RibbonViewControl}" ItemTemplate="{StaticResource BackstageActionItemTemplate}"/>
            </fluent:Backstage>
        </fluent:Ribbon.Menu>
```

And here is the Template

```
 <DataTemplate x:Key="BackstageActionItemTemplate">
            <fluent:Button Header="{Binding Header}" 
                          LargeIcon="{Binding LargeImageSource , Converter={StaticResource imageConverter} }" 
                          Icon="{Binding SmallImageSource , Converter={StaticResource imageConverter} }"
                          Command="{Binding Path=ClickCommand}"/>
        </DataTemplate>
```

With the above configuration, all I receive is some empty buttons (active on rollover like in the screenshot) on the left pane and one bigger button on the right pane.

I also tried the following code:

```
   <fluent:BackstageTabControl>
                    <ItemsControl ItemsSource="{Binding Path=DataContext.ApplicationMenuItems, ElementName=RibbonViewControl}" ItemTemplate="{StaticResource BackstageActionItemTemplate}"/>
                </fluent:BackstageTabControl>
```

In this case, the buttons were correctly generated but all buttons were displayed on the right pane.

Could you please advise me on what I am doing wrong?

I find the Fluent.Ribbon a greate nuget package, however it seems to lack a documentation on the "Binding" part, which is also useful sometimes.

Thank you
## 
### Environment
- Fluent.Ribbon  v.4.0.3.394
- Theme **?**
- Windows  8
- .NET Framework  4.6

**Comment by batzen** [comment]
This library was not designed with bindings in mind.
As I started to become the maintainer of it I started to fill those binding gaps.
But there are still more or less large gaps in binding support.

I will have a look at your issue and see what i can do.
It would help a lot if you could send me a small repro for your issue. Repros make it much easier and less time consuming for me to fix things. ;-)

**Comment by batzen** [comment]
Any chance to get a repro from you?

**Comment by YanivFromIsrael** [comment]
Hey I am having the same issue, 

This is what I want to accomplish, I want to customize the file tab that it will look something like this:

![for_github_1](https://cloud.githubusercontent.com/assets/24633403/21293714/35500df8-c535-11e6-9a59-67b706f462a4.png)
![for_github_2](https://cloud.githubusercontent.com/assets/24633403/21293715/38213f8e-c535-11e6-9412-22aa0c1d4162.png)

The idea is that I can have several sections of menus which contain buttons: New, Open, Save, Save As, Share, each section can have a different title and icon and some of the sections could have partial list of buttons. 

I tried to achieve this, by using DataTemplate and HierarchicalDataTemplate and TreeView, it doesn't work.

This is what I see:

![for_github_the_result](https://cloud.githubusercontent.com/assets/24633403/21294341/1cd44fba-c543-11e6-8c23-26eeaf7e2e13.jpg)

Here is the code:

The xaml:
```
<UserControl xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:System="clr-namespace:System;assembly=mscorlib"
             xmlns:Fluent="clr-namespace:Fluent;assembly=Fluent"
             xmlns:Converters="clr-namespace:Fluent.Converters;assembly=Fluent"
             xmlns:local="clr-namespace:ElmoMotionControl.Ribbons.Core.View.Backstage"
             xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity" 
             xmlns:ei="http://schemas.microsoft.com/expression/2010/interactions"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <UserControl.Resources>        

        <local:FileTabOptions x:Key="FileTabOptions"/>

        <DataTemplate x:Key="level2">
            <Fluent:Button Header="{Binding Text}"/>
        </DataTemplate>
        <HierarchicalDataTemplate x:Key="level1" ItemsSource="{Binding Options}" ItemTemplate="{StaticResource level2}" >
            <Fluent:BackstageTabItem Header="{Binding Title}"/>
        </HierarchicalDataTemplate>
        
    </UserControl.Resources>
    <Fluent:Backstage x:Name="backstage" Header="File" Visibility="Visible" Background="{DynamicResource BackstageColorBrush}">

        <Fluent:BackstageTabControl DataContext="{Binding DataContext, RelativeSource={RelativeSource AncestorType={x:Type local:BackStageView}}}">

            <TreeView Grid.Column="0" Grid.Row="0" ItemsSource="{StaticResource FileTabOptions}" ItemTemplate="{StaticResource level1}">
            </TreeView>

        </Fluent:BackstageTabControl>
    </Fluent:Backstage>
</UserControl>
```


The view: 

```
using System.Windows.Controls;

namespace ElmoMotionControl.Ribbons.Core.View.Backstage
{
    /// <summary>
    /// Interaction logic for BackStageView.xaml
    /// </summary>
    public partial class BackStageView : UserControl
    {
        public BackStageView()
        {
            InitializeComponent();
        }
    }
	
	public class ObservableObject : INotifyPropertyChanged
	{
		#region INotifyPropertyChanged
		public event PropertyChangedEventHandler PropertyChanged;

		public void RaisePropertyChanged(string propertyName)
		{
			PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if (propertyChanged != null)
			{
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		#endregion
	}

    public class ToolOption : ObservableObject
    {

        public bool IsVisible = true;

        string _text;

        public string Text
        {
            get { return _text; }
            set
            {
                _text = value;
                RaisePropertyChanged("Text");
            }
        }
    }

    public class ToolsOptions : ObservableObject
    {
        public ToolsOptions()
        {
            Options = new ObservableCollection<ToolOption>
            {
                new ToolOption {Text = Properties.Resources.FileMenuNew },
                new ToolOption {Text = Properties.Resources.FileMenuOpen},
                new ToolOption {Text = Properties.Resources.FileMenuSave},
                new ToolOption {Text = Properties.Resources.FileMenuSaveAs},
                new ToolOption {Text = Properties.Resources.FileMenuShare }
            };
        }
        public string Title { get; set; }
        public ObservableCollection<ToolOption> Options { get; set; }
    }

    public class FileTabOptions : ObservableCollection<ToolsOptions>
    {
        public FileTabOptions()
        {
            this.Add(new ToolsOptions { Title = "Tool 1" });
            this.Add(new ToolsOptions { Title = "Tool 2" });
        }
    }
}
```

Could you please advise? 

Thanks,
Yaniv.

**Comment by batzen** [comment]
@YanivFromIsrael could you provide your repro as a zip file or a github project?

**Comment by YanivFromIsrael** [comment]
Hey batzen, this is part of a very big solution :)) So I only copied and pasted the relevant section, I don't have it in a separate project/solution. :)))

I currently found a workaround by inheriting BackstageTabControl and overriding the function IsItemItsOwnContainerOverride

```
    public class MyBackstageTabControl : BackstageTabControl
    {
        protected override bool IsItemItsOwnContainerOverride(object item)
        {
            return base.IsItemItsOwnContainerOverride(item) || item is System.Windows.Controls.TreeView;
        }
    }
```

I then use MyBackstageTabControl in my xaml instead of BackstageTabControl.

The thing is the style of the tree view looked at start odd, but by defining a different style I managed to make it look ok.

**Comment by batzen** [comment]
Well, the backstage was not made to work as a TreeView, in the first place. So it does not work as you expect it to be in your special case.
If you'd have used a flat list of items and added a template selector to the mix it should have yield the same graphical result. ;-)

**Comment by YanivFromIsrael** [comment]
Thanks for the help.

I think it would be great to add to the documentation an example of how to customize the backstage (with flat list of items and template selector)

For me, the workaround which I found works great, so currently I have it working ))))

**Comment by soumyanayankar** [comment]
Hi,
I have a similar requirement where I would need to bind the Backstage against an array of ViewModels and use a TemplateSelector to render the BackstageTabItems. But it does not seem to work and I am getting a list of empty buttons which become active on rollover but have no view or behavior attached with them. Can you please help. I am attaching a basic implementation with some additional DI stuff which is not relevant to the issue but would be required in my final solution.
[FluentControlsPoc.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3302273/FluentControlsPoc.zip)

**Comment by batzen** [comment]
@soumyanayankar That does not work because the `ItemTemplate` is being used for the right hand content area, in this case.
So you have to use an `ItemContainerStyle` or `ItemContainerStyleSelector` which should be inherited from `BackstageTabControlItemContainerStyleSelector` (otherwise you loose separator styling etc.).

In the style you return from the selector you can then set the content of the tab item to your liking.

The reason for all this is that the `BackstageTabControl` behaves more like a `TabControl` than an `ItemsControl` like `ListBox` for example. And the fact that the method `IsItemItsOwnContainerOverride` only works the way you want if you provide real controls instead of viewmodels.

Your last option might be to just ignore those things, inherit from `BackstageTabControl` and override things like `GetContainerForItemOverride` etc.
