### ISSUE TITLE
Fluent Button with Image from Resource

### ISSUE THREAD

**Issue by seanrobertwright** [fluentribbon/Fluent.Ribbon#317]
--
Windows with VS 2013 community Environment

- Fluent.Ribbon 4.0.3.394
- Theme Office2013
- Windows 7
- .NET Framework 4.5

I have a class library with all my images as Resources.  I am trying to use these images for Ribbon Buttons.  How do I do this?
My class library is called LRIL.Images

**Comment by batzen** [comment]
`LargeIcon="pack://application:,,,/LRIL.Images;component/Images/Exit.png"`

With "Images/Exit.png" being replaced by your resource-path should work perfectly.

**Comment by seanrobertwright** [comment]
Thanks for this - I had found an article online that mentioned just that, however, my XAML code

``<Fluent:Button x:Name="NewTemplate" Header="Template" LargeIcon="pack://application:,,,/LRIL.Images;component/Properties/Resources/Add File.png"/>``

produces the following error: 

> Cannot add part to the package.  Part names cannot be derives from another part name by appending segments to it.

I have Googled this but cannot find anything that helps - most a references to Nuget packages.

**Comment by seanrobertwright** [comment]
I have solved the issue.  It appears that the LRIL prefix in my project name is causing issues.  I removed it and the issue went away.

**Comment by batzen** [comment]
Glad you found out what was causing your issues.
