### ISSUE TITLE
How to make window resizable with Win32 content?

### ISSUE THREAD

**Issue by floele-sp** [fluentribbon/Fluent.Ribbon#319]
Hi,

if you have Win32/WinForms content located at either the right or left side of the window, it is quite difficult to change the window width.

Check the following screenshot:
![resizablearea](https://cloud.githubusercontent.com/assets/15671468/15357698/9f09131c-1d00-11e6-9cd1-fd04cbdfd1c5.png)

The red area is not resizable by default, the orange areas are not resizable because the Win32 content is displayed on top of the area that would be resizable (the content is arranged using a docking control, so there is at least some space in between the Win32 windows). This leaves very little of the window for resizing purposes.

Any suggestions for improving the situation? Office 2013 for example apparently has an invisible resize border outside the window bounds so it never conflicts with content within the window.

**Comment by batzen** [comment]
I had a fix for this which worked fine on windows 10, but caused many issues on windows 7 and 8. I currently don't have a solution for this issue. 
I have been very busy during the last few weeks and will be for a few more, but improving resizing is already on my list. But getting it to work correctly on every supported version of windows is hard...

**Comment by floele-sp** [comment]
OK, thanks, looking forward to the improvement.

**Comment by batzen** [comment]
It would be nice if you could create a repro showing your issues with Win32.
The more repros i have, the more reliable i can try to fix the issue.

**Comment by batzen** [comment]
Any chance to get a repro from you?

**Comment by floele-sp** [comment]
I wonder what exactly you expect. Just having a Dock=Full Win32 textbox inside the window would be a quite simple repo barely worth to create a demo project for?

**Comment by batzen** [comment]
That part of information should be enough. Just didn't know exactly in which situations you encounter issues.

**Comment by floele-sp** [comment]
OK. Basically it's just the WPF airspace issue, no special conditions required as far as I can see.

**Comment by batzen** [comment]
I don't know how to fix an issue that even microsoft was unable to fix since they first released WPF.
If you got any advice on how to fix this i would be very happy.

**Comment by floele-sp** [comment]
You don't be able to fix the airspace issue, sure. I was thinking about some kind of workaround, like an additional invisible border outside of the window bounds maybe. At the very least it should be possible to fix resizing within the ribbon area though.

**Comment by batzen** [comment]
I tried to add an invisible resize border using win32 stuff in ControlzEx.
Worked well on windows 8 and 10, was a disaster on windows 7.

Don't know how to fix resizing in the ribbon area either. The only way that i can imagine of is a margin and that would not work out very well...

It's so sad that microsoft does not provide a proper win32 api do achieve this.

**Comment by floele-sp** [comment]
> Worked well on windows 8 and 10, was a disaster on windows 7.

So why not keep it as feature for Win8 and later only? It's perferctly fine to argue that a certain "feature" will only be available in more recent versions of Windows.

**Comment by batzen** [comment]
Because it becomes more difficult to maintain, that win32 stuff is horribly fragile, and i can't detect win 10 in a reliable way as Microsoft changed the version api.
It was a long way to get the window to work like it does now. I don't want to add more complexity to that stuff.

**Comment by floele-sp** [comment]
Hm...looking at MS Office 2013, it seems like they use multiple separate windows around the main window for rendering the shadows and providing resize functionality:

![shadows](https://cloud.githubusercontent.com/assets/15671468/18700716/03da34b6-7fd9-11e6-837f-b8f9c4dc5e37.png)

See also: https://support.microsoft.com/en-us/kb/2821007

Maybe that is a possibility?

**Comment by batzen** [comment]
@floele-sp Took a while but i finally decided to add the GlowWindow from MahApps.Metro to ControlzEx and use it in Fluent.Ribbon. Will be available here as soon as https://github.com/ControlzEx/ControlzEx/issues/49 is done.

**Comment by floele-sp** [comment]
Thanks, looking forward to it 👍

**Comment by batzen** [comment]
GlowWindow branch + PR merged. This should be fixed now.
