### ISSUE TITLE
RegionAdapter for Prism

### ISSUE THREAD

**Issue by PeterForstmeier** [fluentribbon/Fluent.Ribbon#32]
Hi List, 
 i run Prism 5.x together with Fluent.Ribbon 2.x, all work's perfectly. After update to Fluent.Ribbon 3.xx from Nuget the RegionManger is unable to find my Regions. 
The code below works with Fluent.Ribbon 2.x

public class RibbonTabRegionAdapter : RegionAdapterBase<Ribbon>
    {
		public RibbonTabRegionAdapter(IRegionBehaviorFactory behaviorFactory)
			: base(behaviorFactory)
        {
        }
		protected override void Adapt(IRegion region, Ribbon regionTarget)
        {
 			if (region == null) throw new ArgumentNullException("Region");
            if (regionTarget == null) throw new ArgumentNullException("RegionTarget");

            region.ActiveViews.CollectionChanged += (s, args) =>
            {
                switch (args.Action)
                {
                    case NotifyCollectionChangedAction.Add:
                        {
                            foreach (Object view in args.NewItems)
                            {
                                AddViewToRegion(view, regionTarget);
                            }
                            break;
                        }
                    case NotifyCollectionChangedAction.Remove:
                        {
                            foreach (Object view in args.OldItems)
                            {
                                RemoveViewFromRegion(view, regionTarget);
                            }
                            break;
                        }
                    default:
                        {
                            // Do nothing.
                            break;
                        }
                }
            };
  		}

  	protected override IRegion CreateRegion()
        {
            return new AllActiveRegion();
        }
  		
  		
        static void AddViewToRegion(Object view, Ribbon wpfRibbon)
        {
            var ribbonTab = view as RibbonTabItem;
            if (ribbonTab != null)
                wpfRibbon.Tabs.Add(ribbonTab);
        }

        static void RemoveViewFromRegion(Object view, Ribbon wpfRibbon)
        {
            var ribbonTab = view as RibbonTabItem;
            if (ribbonTab != null)
                wpfRibbon.Tabs.Remove(ribbonTab);
        }

	}

public class TabItemRegionAdapter : RegionAdapterBase<RibbonTabItem>
	{
		public TabItemRegionAdapter(IRegionBehaviorFactory regionBehaviorFactory) : base(regionBehaviorFactory)
		{
		}

		protected override void Adapt(IRegion region, RibbonTabItem regionTarget)
		{
			region.Views.CollectionChanged += (sender, args) => ViewsOnCollectionChanged(regionTarget, args);
		}

		private static void ViewsOnCollectionChanged(RibbonTabItem regionTarget, NotifyCollectionChangedEventArgs e)
		{
			switch (e.Action)
			{
				case NotifyCollectionChangedAction.Add:
					foreach (var newItem in e.NewItems)
					{
						regionTarget.Groups.Add((RibbonGroupBox) newItem);
					}
					regionTarget.BringIntoView();
					break;
				case NotifyCollectionChangedAction.Remove:
					foreach (var oldItem in e.OldItems)
					{
						regionTarget.Groups.Remove((RibbonGroupBox) oldItem);
					}
					break;
			}
		}

		protected override IRegion CreateRegion()
		{
			return new AllActiveRegion();
		}
	}

 Any ideas 
 Thanks in advance 
 Peter

**Comment by PeterForstmeier** [comment]
Hi and a late Happy New Year,

 

can you give me a mail address to send the example code, because the zip  is a very large and me be exceed the quota.

 

Thanks

Peter

 

 

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Dezember 2014 23:23
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

Any progress on this one?

**Comment by batzen** [comment]
Just upload your repro to some public place (onedrive, dropbox etc.) so everyone can have a look. 
I don't like getting things via mail, except there would be legal issues by publishing your code.

**Comment by PeterForstmeier** [comment]
Hi Bastian,

 

http://1drv.ms/1wLLj0z

 

The sample is a little huge because it is generated. 

 

At the moment we use Fluent 2.1.0.0 as you can see in the Reference. As soon we change to the newest version of Fluent, all we get is a black screen.

 

The change the reference, use the packages folder please.

 

Thanks

Peter

 

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Mittwoch, 28. Januar 2015 20:41
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

Just upload your repro to some public place (onedrive, dropbox etc.) so everyone can have a look. 
I don't like getting things via mail, except there would be legal issues by publishing your code.

**Comment by batzen** [comment]
Maybe you should have read: https://github.com/fluentribbon/Fluent.Ribbon/blob/master/ReleaseNotes.md
Especially the bullet point starting with: Style resources have been improved.

**Comment by PeterForstmeier** [comment]
Ich sage es mal so, ‚Asche auf mein Haupt‘ werde das gleich die kommende Woche versuchen. Ansonsten melde ich mich nochmal.

 

Danke vorerst und schönen Rest Sonntag

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 1. Februar 2015 18:11
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

Maybe you should have read: https://github.com/fluentribbon/Fluent.Ribbon/blob/master/ReleaseNotes.md
Especially the bullet point starting with: Style resources have been improved.

**Comment by PeterForstmeier** [comment]
Hi,

i just download the code and get the following error:

 

Das Tag "MetroWindow" ist im XML-Namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro" nicht vorhanden. Zeile 1 Position 20. (MC3074) - D:\FluentRibbon\Fluent.Ribbon\FluentTest\MahMetroWindow.xaml:1,20

 

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 1. Februar 2015 18:11
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

Maybe you should have read: https://github.com/fluentribbon/Fluent.Ribbon/blob/master/ReleaseNotes.md
Especially the bullet point starting with: Style resources have been improved.

**Comment by batzen** [comment]
MetroWindow was only used in the pre-release versions because it was the faster way, in the first step, to implement the office 2013 theme.
You can use RibbonWindow for all themes now.

**Comment by PeterForstmeier** [comment]
Good morning,

 

I get the error in the samples code.

 

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 1. Februar 2015 22:28
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

MetroWindow was only used in the pre-release versions because it was the faster way, in the first step, to implement the office 2013 theme.
You can use RibbonWindow for all themes now.

**Comment by batzen** [comment]
You have to restore the nuget packages (currently only one) we are referencing. This is done automatically on my machine when i build. Which visual studio version are you using?

**Comment by PeterForstmeier** [comment]
Hi

Good morning,

 

Strange strange, I try it on a different machine and now it works.

I work wit VS 2012 + 13

 

Thanks

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Montag, 2. Februar 2015 18:30
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

You have to restore the nuget packages (currently only one) we are referencing. This is done automatically on my machine when i build. Which visual studio version are you using?

**Comment by batzen** [comment]
So it's working for you now, or i there still something which prevents closing of this issue?

**Comment by PeterForstmeier** [comment]
Hi,

i make only a very small test.  I can test it better and with VS 2012 earliest tomorrow, so please waout one or two days.

Thanks

Peter

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Februar 2015 14:11
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

So it's working for you now, or i there still something which prevents closing of this issue?

**Comment by batzen** [comment]
Take your time, just wanted to clarify the status.

**Comment by PeterForstmeier** [comment]
Hi,

It works.

Thanks a lot for your patient

 

Peter

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Februar 2015 19:46
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier
Betreff: Re: [Fluent.Ribbon] RegionAdapter for Prism (#32)

 

Take your time, just wanted to clarify the status.

**Comment by batzen** [comment]
Nice to hear that.
