### ISSUE TITLE
Show radiobuttons as togglebuttons

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#320]
Is there any simple way to apply the style used for ToggleButtons to RadioButtons?

I tried [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e0ce86f0-8fa3-4aa9-9617-4157326ee077/make-radiobutton-appear-as-togglebutton?forum=wpf) but it does not apply to Fluent.Ribbon.

**Comment by batzen** [comment]
Why would you want to do that?

**Comment by maurosampietro** [comment]
The toggle button look is catchy and is easy to make a group of toggle buttons act like a group of radio buttons; by the way it would be even easier and much cleaner  if we could achieve the behavior of the radio button just using a radio button :) that looks like toggle button. 

The standard radio button does not fit visually most or the times 

Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
As far as i remember you can just use ToggleButton and assign a GroupName, just like you do when using a RadioButton. ;-)

**Comment by batzen** [comment]
Did you try to use GroupName on your ToggleButton?

**Comment by maurosampietro** [comment]
i'm trying tomorrow and let you know

**Comment by maurosampietro** [comment]
i tried with GroupName but it is not resolutive by itself.
Try to bind 2 togglebuttons to the same boolean property and see the behavior.

**Comment by batzen** [comment]
Why would you bind 2 togglebuttons to the same boolean property?

**Comment by maurosampietro** [comment]
My goal is to make them act as radio buttons: just one toggled button at time in a group of togglebuttons.

The general case is that you have an enum and a serie of toggle buttons by the means of which you control which one of the enum values is currently selected. 

The most simple version of this concept is to use a bool and two toggles (i know in the case of a bool you could just toggle on/off the toggle button but for the sake of this example... )

**Comment by batzen** [comment]
If you want to achieve that behavior with ToggleButton you need more than one bool property.
If you don't want to use ToggleButton but RadioButton styled as a ToggleButton you will have to overwrite the RadioButton's style with the one from ToggleButton.
What didn't work when you tried to overwrite the style of RadioButton?

**Comment by batzen** [comment]
@maurosampietro ping

**Comment by MildanWorld** [comment]
I think the point of the question is can [this SO Answer](http://stackoverflow.com/a/5287256) be achieved using the Fluent:ToggleButton (tangent, why is there not a Fluent:RadioButton?) somehow? 

Not exactly sure but I ran into a similar problem having to group a bunch of ToggleButtons and ended up making a binding to a ViewModel function which kept track of which was selected, and whenever any of the other were clicked it would call OnPropertyChanged on each individual one..

**Comment by batzen** [comment]
> (tangent, why is there not a Fluent:RadioButton?) 

It's included, don't know what you mean.

**Comment by MildanWorld** [comment]
Okay.. But is there the same amount of control like for other buttons? Like can I add a picture to them and would it display correcly because the only thing I'm able to produce is this..

[How it looks with Fluent:RadioButton](http://i.imgur.com/p2JKFJ9.png)
[How it looks with Fluent:ToggleButton](http://i.imgur.com/0I2WJ5Z.png)

I am probably just bad and was trying to raise the point that I think was the intent from maurosampietro, and got off on a tangent. I don't have a problem using ToggleButtons, it would just be nice because I had to bind the logic of radiobuttons into the UI to account for only one ToggleButton being pressed at a given time.

**Comment by batzen** [comment]
> I don't have a problem using ToggleButtons, it would just be nice because I had to bind the logic of radiobuttons into the UI to account for only one ToggleButton being pressed at a given time.

You just have to set `GroupName` on your ToggleButton, which ensures that only one button has it's `IsChecked` set to true.
The showcase application contains a sample for this in "Tests => ToggleButton".
