### ISSUE TITLE
Can I add a vertical bar in RibbonGroupBox

### ISSUE THREAD

**Issue by TruePluto** [fluentribbon/Fluent.Ribbon#321]
I want to add a vertical bar  into a RibbonGroupBox make it looks like win10 explorer,But I don't know how to do. does anybody know ? thanks 
--
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __Office2013__
- Windows __win10__
- .NET Framework __4.6__

**Comment by batzen** [comment]
Could you add a screenshot and mark the parts you would like to add?

**Comment by TruePluto** [comment]
![default](https://cloud.githubusercontent.com/assets/19511177/15841583/f9ea29ea-2c84-11e6-9239-a78f9deb93e8.JPG)
thanks

**Comment by batzen** [comment]
"SubRibbonGroupBox" you mean and expandable popup group?
You can achieve that by setting `State="Collapsed"`.

If you just want a vertical line inside a group you can add a `<Separator />` anywhere you want.

**Comment by TruePluto** [comment]
Wonderful. 
thank you very much.
