### ISSUE TITLE
popup/menu placement for touch screens

### ISSUE THREAD

**Issue by alistair-fromnz** [fluentribbon/Fluent.Ribbon#322]
When using a touch screen the default placement of menus and popup windows is that they are right aligned with the ribbon button or right-mouse-click position.

Ribbon button:
![menualignment](https://cloud.githubusercontent.com/assets/19668607/15676838/2006d408-2748-11e6-81e1-c19edd069959.JPG)

Right-click:
![right-click](https://cloud.githubusercontent.com/assets/19668607/15677457/a675bcb4-274a-11e6-8e33-fc9725ed21b4.JPG)

The general convention to solve this is to use custom placments using code similar to this:

```
        var popup1 = new Popup
        {
            Placement = PlacementMode.Custom,
            CustomPopupPlacementCallback = (size, targetSize, offset) =>
            {
                offset.Y = 0; 
                offset.X = 0.
                return new[] { new CustomPopupPlacement(offset, PopupPrimaryAxis.Horizontal) };
            },
            //etc....
        };
```

Obviously the offsets etc would be case specific to get the popup into the correct position.

So, it would be great if the Fluent API could preferably expose this or have some options to otherwise fix it.
## 
### Environment
- Fluent.Ribbon v4.0.30319
- Windows 8?, 8.1 & 10
- .NET Framework 4.6

**Comment by batzen** [comment]
As i don't need such a feature this does not have a high priority for me.
If you need it in the near future we could discuss a possible solution and pull request from your side.

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
