### ISSUE TITLE
Themes Windows8

### ISSUE THREAD

**Issue by AtaBelsky** [fluentribbon/Fluent.Ribbon#323]
## 
### Environment
- Fluent.Ribbon 4.0.3.394
- Theme Windows8
- Windows 10
- .NET Framework 4.5.2

App.xaml
ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Windows8/Generic.xaml" #
Cannot find resource named 'ScrollBarWhite'.

Belsky

**Comment by batzen** [comment]
Can't reproduce your issue.
Could you provide a repro?

**Comment by batzen** [comment]
@AtaBelsky Any news?

**Comment by batzen** [comment]
@AtaBelsky ping

**Comment by 2piix** [comment]
I can confirm that this is going on for me:

Windows 7
Visual Studio 2015 Community

The Office 2013 theme works, but if I switch to Windows8, I get the ScrollBarWhite message.  I'm importing a project where the Designer just refused to show controls in my MainWindow, and I'm double checking every line.

**Comment by batzen** [comment]
So it's just the designer causing trouble?

The designer of Visual Studio is very buggy, even in VS 2015...

**Comment by 2piix** [comment]
I don't know if the Designer is the cause of the WhiteScrollBar error (I
think that's what it was, I'm replying from email).

I do know that:

1. The Designer was messed up before, so I
2. Made a new project, loaded up the newest nuggets, and copy pasted the
source code from the old project to the new one.
3.  The Designer problem went away.
4.  The Windows8 theme doesn't work, and the project won't build if I pick
Windows8.

I don't think/know that 1.-3. have anything to do with the problem.  I'll
try to make a minimal test case later today.

**Comment by batzen** [comment]
I would suggest that you rather switch to the office 2013 theme as the windows 8 theme is removed in version 5 of Fluent.Ribbon.
