### ISSUE TITLE
Running RibbonWindow not on the main thread.

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#325]
For reasons out of my control (involving legacy code and things like that), I want to run a RibbonWindow on another UI thread. However, because of the use of Application.Current.MainWindow in IconConverter and ObjectToImageConverter, The application obviously crash because I'm calling from another thread.

Is there a way around this that does not requires me to build my own version of Fluent.Ribbon?
If not, would a thread friendly version of those converters would be considered if submitted for contribution?

Thank you
Pierre

--
### Environment

- Fluent.Ribbon v4.0.3.394
- Theme: Office 2013
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
I would happily accept a version of those converters which is thread friendly.
Any ideas you would like to share?

**Comment by polepage** [comment]
For now my only idea is to always access the property on the main thread using an Invoke on the Application.Current.Dispatcher. However this is a bit less friendly for normal people that use the main thread as their UI thread.

I'll gladly provide more ideas as they come and I will offer my contribution when I have some actual working code.

Thanks.
Pierre.

**Comment by batzen** [comment]
Switching to the applications main thread would cause the current window, running in a different thread, to be locked until the main thread is no longer locked.
I will add checks for different threads and just disabled dpi scaling for the images if the converter is not run on the applications main thread.
