### ISSUE TITLE
Closing the backstage by code

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#328]
Is it possible to close the backstage by code? Like in Office 2013, where clicking on the browse button don't close the backstage, but actually loading a file does.

Thank you
Pierre

--
### Environment

-Fluent.Ribbon v4.0.3.394
-Theme Office 2013
-Windows 10
-.NET Framework 4.6.1

**Comment by maurosampietro** [comment]
Try setting IsOpen to false by code.

**Comment by polepage** [comment]
I tried to bind to IsOpen to no avail, but setting it to false from code works fine. Thanks a lot.
