### ISSUE TITLE
RibbonTabItem bug and fix

### ISSUE THREAD

**Issue by maurosampietro** [fluentribbon/Fluent.Ribbon#330]
When a selected TabItem changes its visibility to collapsed, the default behavior is to select the first visible TabItem.

This behavior is ok if nothing is binding to IsSelected.
If IsSelected is bound we should do nothing: it's binding business.

I suggest this fix on file 'RibbonTabItem', row 473:

replace this   

`item.TabControlParent.SelectedItem = item.TabControlParent.GetFirstVisibleItem();`

with this

```
var isSelectedIsBound = BindingOperations.GetBindingExpression( d, IsSelectedProperty ) != null;
if( !isSelectedIsBound )
    item.TabControlParent.SelectedItem = item.TabControlParent.GetFirstVisibleItem();
```

Thank you.

**Comment by maurosampietro** [comment]
Ping...

**Comment by batzen** [comment]
I don't understand why this shouldn't be done if IsSelected is bound.
Could you provide an example where the current behavior is not desired?

**Comment by maurosampietro** [comment]
For example if i have 4 tabitem and i set is selected to the 3rd and collpse the last the result is i have selected the 1st, which is weird


Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
But that's not what the code you want to be changed is supposed to do.
The code first looks if the item being collapsed is currently selected and only if it's selected the first tab gets selected. Otherwise the ribbon would show no tab selected.

You can test the behavior using the showcase application:
- Select the last tab "LAYOUT"
- Click the help button
- First tab gets selected
- Click the help button again
- Select tab "Resizing & Screentips"
- Click the help button
- "Resizing & Screentips" is still selected

**Comment by maurosampietro** [comment]
I may have not provided the best example before, since i don't have the code with me right now.

if i collapse the tab being selected i'd like to choose which tab is selected next. The default rule is to select the first tab. In my case my binding calculates it has to be the last tab stiil visible, but then the default rule kicks in. 

This is a very conservative and reasonably good fix in my opinion.
Please consider to accept it since it will cost me a while to produce an exact repro. 
By the way, if needed, monday i will provide you with a repro.

**Comment by batzen** [comment]
Why don't you just select your desired item before collapsing the currently selected item?

The problem with your solution is that it may not be the behavior most users expect. Everyone binding to IsSelected would be forced to implement his own logic for selecting tabs if the currently selected gets collapsed.

**Comment by maurosampietro** [comment]
I understand your point.

What if we introduce a property, true by default, like SelectFirstTabOnSelectedTabCollapsed instead of checking for the binding?


Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
That would do the job, but i still think that the easiest way to handle such a special case would be to handle it on your side.

Maybe i am missing something, but why don't you select your desired tab before collapsing the currently selected one?

**Comment by maurosampietro** [comment]
Because i manage that with a simple binding to a property and di not want to introduce complexity with code behind 

Mauro Sampietro
Inviato da iPhone

**Comment by maurosampietro** [comment]
My real world usage example is the following:

Multiple tabs bind their IsSelected property to my SelectedTab property which is an enum representing the tabs available. This way by setting SelectedTab i can drive what tab is being shown.

So far so good, but there's one tab that needs to be contextual that is, is shown only when EDITING tab is selected. Since i need

```
<Fluent:RibbonTabItem IsSelected="{Binding SelectedTab, Mode=TwoWay, Converter={StaticResource tabSelector}, ConverterParameter={x:Static vm:MainViewModel+SelectableTabs.LIVE}}">

<Fluent:RibbonTabItem IsSelected="{Binding SelectedTab, Mode=TwoWay, Converter={StaticResource tabSelector}, ConverterParameter={x:Static vm:MainViewModel+SelectableTabs.EDITING}}">

<Fluent:RibbonTabItem IsSelected="{Binding SelectedTab, Mode=TwoWay, Converter={StaticResource tabSelector}, ConverterParameter={x:Static vm:MainViewModel+SelectableTabs.INSERT}}">

<Fluent:RibbonTabItem IsSelected="{Binding SelectedTab, Mode=TwoWay, Converter={StaticResource tabSelector}, ConverterParameter={x:Static vm:MainViewModel+SelectableTabs.TOOLS}}">

<Fluent:RibbonTabItem x:Name="selectedDrawingTab" Header="SELECTED ITEM" IsSelected="{Binding SelectedTab, Mode=TwoWay, Converter={StaticResource tabSelector}, ConverterParameter={x:Static vm:MainViewModel+SelectableTabs.SELECTED_ITEM}"
                    Visibility="{Binding IsSelectedDrawingTabVisible, Mode=TwoWay, Converter={converters:BoolToVisibilityConverter}}" >
```

I already set the visibility BEFORE setting the new SelectedTab in code as you suggested:

```
this.IsSelectedDrawingTabVisible = this.IsSelectionMode && otherChecks;

this.SelectedTab = this.IsSelectedDrawingTabVisible ?  SelectableTabs.SELECTED_ITEM : SelectableTabs.EDIT;
```

But it does not work if i cannot avoid the execution of the line of code:

`item.TabControlParent.SelectedItem = item.TabControlParent.GetFirstVisibleItem();`

**Comment by batzen** [comment]
My suggestion was to change selection before toggling visibility.

```
var isSelectedDrawingTabVisible = this.IsSelectionMode && otherChecks;

this.SelectedTab = isSelectedDrawingTabVisible ?  SelectableTabs.SELECTED_ITEM : SelectableTabs.EDIT;

this.IsSelectedDrawingTabVisible = isSelectedDrawingTabVisible;
```

Does that work for you?

**Comment by maurosampietro** [comment]
Absoultely not working, i just tried to be sure.

By the way since it's the visibility change that triggers the selection of the first tab
it should be more conservative to perform the selection after the collpasing as i showed.

**Comment by batzen** [comment]
Will have a look at this issue this weekend.

**Comment by batzen** [comment]
I just built a repro for this and it behaves exactly as it should.
You just have to select your desired item before collapsing.

I don't get why you think its better to collapse the item before selecting your desired item.

It might be that I missed something while building my repro so it would help a lot to get a repro from you.

**Comment by batzen** [comment]
@maurosampietro ping
