### ISSUE TITLE
InRibbonGallery with MenuItem

### ISSUE THREAD

**Issue by ks-sasaki** [fluentribbon/Fluent.Ribbon#331]
--
### Environment
Visual Studio2015 
WPF

- Fluent.Ribbon __v4.0.3.394__
- Windows __8.1__
- .NET Framework __4.6.1__

```xaml

<Fluent:InRibbonGallery Header="Number"
                        Icon="{xxx}"
                        ItemsSource="NumberList"
                        IsCollapsed="True">
    <Fluent:InRibbonGallery.ItemTemplate>
        <DataTemplate>
            <MenuItem Header="{Binding Path=NumberName}" Icon="{Binding Path=NumberImage}"/>
        </DataTemplate>
    </Fluent:InRibbonGallery.ItemTemplate>
</Fluent:InRibbonGallery>

```

When I clicked MenuItem, InRIbbonGallerly didn't close.

InRibbonGallery cant use MenuItem in DataTemplate??

**Comment by maurosampietro** [comment]
Are you using it inside the backstage? What should close?

**Comment by maurosampietro** [comment]
Using Fluent.GalleryItem is not enough cause MenuItem seems to swallow the click event. I solved with a behavior like this or you:

  public sealed class BubbleClickEvent : Behavior<UIElement>
    {
        protected override void OnAttached()
        {
            base.OnAttached();
            AssociatedObject.PreviewMouseDown += AssociatedObject_PreviewMouseDown;
        }

        private void AssociatedObject_PreviewMouseDown( object sender, MouseButtonEventArgs e )
        {
            e.Handled = true;
            var e2 = new MouseButtonEventArgs( e.MouseDevice, e.Timestamp, e.ChangedButton );
            e2.RoutedEvent = UIElement.MouseDownEvent;
            AssociatedObject.RaiseEvent( e2 );
        }

        protected override void OnDetaching()
        {
            AssociatedObject.PreviewMouseDown -= AssociatedObject_PreviewMouseDown;
            base.OnDetaching();
        }
    }

use it like this:

add namespace
xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"

<Fluent:InRibbonGallery Header="Number"
                        Icon="{xxx}"
                        ItemsSource="NumberList"
                        IsCollapsed="True">
    <Fluent:InRibbonGallery.ItemTemplate>
        <DataTemplate>
             <Fluent:GalleryItem>
                   <i:Interaction.Behaviors>
                           <viewModels:BubbleClickEvent/>
                   </i:Interaction.Behaviors>
                  <MenuItem Header="{Binding Path=NumberName}" Icon="{Binding Path=NumberImage}"/>
          </Fluent:GalleryItem>
        </DataTemplate>
    </Fluent:InRibbonGallery.ItemTemplate>
</Fluent:InRibbonGallery>

**Comment by ks-sasaki** [comment]
Thank you very much!!!
I'll try it!

**Comment by ks-sasaki** [comment]
Thank you!
I can close GalleryItem.

But,
I want change only selected element's backgroundcolor.

In your code,
all clicked element's background changed...!

**Comment by maurosampietro** [comment]
I think that's a separate question; the code i provided you does not deal with backgound colors.

**Comment by batzen** [comment]
I would try to avoid using MenuItem outside of Menu as it causes many issues, at least most of the time.
How about using a re-styled button instead?

**Comment by batzen** [comment]
@ks-sasaki Do you have any further questions or can we close this issue?

**Comment by ks-sasaki** [comment]
@batzen @maurosampietro 
Thank you. I close this issue
