### ISSUE TITLE
Visual glitches in InRibbonGallery with an ObservableCollection as ItemSource

### ISSUE THREAD

**Issue by dymanoid** [fluentribbon/Fluent.Ribbon#332]
When using an ObservableColletion as an ItemSource for the InRibbonGallery, there are some drawing issues after adding new items into the source collection. The new items appear in the gallery, but they are not properly scaled and positioned (e.g. overlap the already existing items). The gallery itself doesn't resize to match the new items' count.
After opening and closing the drop-down, the gallery resizes and repaints itself and finally looks as intended.

Can be easily reproduced with the showcase app - just replace the type of the MainViewModel.DataItems (make it an ObservableCollection<GallerySampleDataItemViewModel>) and add a Button with a Click event handler to add new items into source collection. Best observed when the gallery is set to CanCollapseToButton="False" and the initial count of the items in the MainViewModel.DataItems is 1 to 3. 

--
### Environment

- Fluent.Ribbon 4.0.3.394
- Theme default (Generic)
- Windows 7 Pro
- .NET Framework 4.5.2

**Comment by dymanoid** [comment]
Seems to be fixed in the version  5.x.

**Comment by batzen** [comment]
Yes, it should be. ;-)

**Comment by batzen** [comment]
Can we close this then or do you have any further questions?

**Comment by dymanoid** [comment]
Yes, this can be closed. Actually I have should done a 5.x verification before posting this, sorry...

**Comment by batzen** [comment]
No problem ;-)
