### ISSUE TITLE
NullReference Exception app.Run

### ISSUE THREAD

**Issue by langeth** [fluentribbon/Fluent.Ribbon#333]
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __all__
- Windows __10__
- .NET Framework __4.5.2__

## I start the Application and Close the Application at MainWindow.Loaded. There I got this Error:

![image](https://cloud.githubusercontent.com/assets/20537969/16949941/e975d5be-4dbd-11e6-93c2-2dd5090ad0d6.png)

![image](https://cloud.githubusercontent.com/assets/20537969/16949944/eff83120-4dbd-11e6-886b-a84144486554.png)

**Comment by batzen** [comment]
Thats a bug in ControlzEx. Will reroute it to there.

**Comment by batzen** [comment]
This is fixed in v5 by updating ControlzEx. f0d46f8df8a7ff9d2728a92804be2725d3845c93
