### ISSUE TITLE
Select all text in Spinner on focus

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#334]
I want to imitate the behavior of Office 2013 controls, where all text in spinners and editable combo boxes is selected when it get focus. I don't see any way to do that in the current API as the textbox is obviously hidden in the implementation.

I tried to access the GotFocus and MouseDown routed events using methot outlined in issue https://github.com/fluentribbon/Fluent.Ribbon/issues/203 to no avail. In fact I don't understand where to put this kind of code to access the event.

Is there a way outside of using a different version of the control?

Thank you.
Pierre

--
### Environment

- Fluent.Ribbon v4.0.3
- Theme Office 2013
- Windows 10
- .NET Framework 4.6

**Comment by batzen** [comment]
You have to put the code at your app startup, for example in your app class.

There is currently no option in Fluent.Ribbon to select all text on focus. I will add such a property in v5.0 for you.

There is no different version of the control. We only provide one version of every control in Fluent.Ribbon.

**Comment by polepage** [comment]
1- Thanks I'll try that.
2- Thank you!
3- I meant doing my own version of your control. :)

Thank you.
