### ISSUE TITLE
Ribbon leaks CollectionChanged events

### ISSUE THREAD

**Issue by tefaye** [fluentribbon/Fluent.Ribbon#335]
In Ribbon.cs on lines 649, 706, 769 and 857 the ObservableCollection.CollectionChanged event is attached to but never released when the Window containing the ribbon is closed.

`this.contextualGroups.CollectionChanged += this.OnContextualGroupsCollectionChanged;`
`this.tabs.CollectionChanged += this.OnTabsCollectionChanged;`
`this.toolBarItems.CollectionChanged += this.OnToolbarItemsCollectionChanged;`
`this.quickAccessItems.CollectionChanged += this.OnQuickAccessItemsCollectionChanged;`

Consider using the [CollectionChangedEventManager](https://msdn.microsoft.com/en-us/library/system.collections.specialized.collectionchangedeventmanager%28v=vs.110%29.aspx) which implements the "weak event listener" pattern to attach listeners for the CollectionChanged event and prevents such leaks.

**Comment by batzen** [comment]
There is no need to release/detach the handlers because those are all private members of the ribbon itself.
How did you find out those leak?

**Comment by chdft** [comment]
[`contextualGroups`](https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/Ribbon.cs#L411) is made public with [`ContextualGroups`](https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/Ribbon.cs#L642), as a result, one could get a reference on the collection. It is possible (although quite unusual) to keep this reference longer than the one on the `Ribbon`.
I'm also interested in how @tefaye found out about this possible leak.

**Comment by batzen** [comment]
That's true, someone can get a reference to it and keep it. In that case the reference holder is responsible for freeing/releasing it or establish a weak reference.

I still see no reason to use weak references on instances created by the ribbon itself.

**Comment by batzen** [comment]
@tefaye Any news?
