### ISSUE TITLE
Changing data context of a spinner.

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#336]
I have a RibbonGroup that contains 4 spinners that represent values of a currently selected item. Each item have the same four value but not necessarily the same min and max for each.

To change selected Item, I change the data context of the group, thus changing the data context of each spinner.

However, since bindings are redone sequentially, the spinner wreak havoc on my objects during the binding process.

An example:
Item 1: A = 30, MinA = 1, MaxA = 89.
Item 2: A = 0, MinA = 0, MaxA = 0.

I currently bind in this order: Minimum, Maximum, Value.

Item 1 is currently selected. If I change the selection to Item 2:
Spinner.Minimum becomes 0, no problem.
Spinner.Maximum becomes 0, that changes Spinner.Value to 0, which in turn change Item1.A to 0 because it is still bound to that item.

If I bind Value before Min and Max, it works but it starts to fail if I change selection from Item 2 to Item 1.

Is there a way to bind Min, Max, and Value as a transaction on the spinner instead of sequentially?

### Environment

- Fluent.Ribbon 4.0.3.394
- Theme Office 2013
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
There is currently no way to achieve this in one transaction.
I don't think this is possible by using regular WPF bindings as there is no such thing as an transaction.

**Comment by polepage** [comment]
That's what I thought. I solved this by setting the property to null before setting the new value. When I set the new value, the old bindings are all null, so there is nothing to break.

**Comment by batzen** [comment]
Glad to hear that you found a way to solve the issue.
