### ISSUE TITLE
RibbonWindow Title Not Showing

### ISSUE THREAD

**Issue by changbowen** [fluentribbon/Fluent.Ribbon#338]
Hi,
Looks like the window title is drawn on the Ribbon control instead of on the title bar of the RibbonWindow? Is there any way to get the title to show **on the title bar** when I am not using the actual Ribbon (only RibbonWindow as it looks nice with the Office 2013 theme)?
Thank you!

**Comment by batzen** [comment]
There is currently no way to achieve this without using the ribbon itself.
But you can add an empty ribbon and modify some property values to only get the title to show up.
I will add a sample for this to the showcase in the next few days.

**Comment by changbowen** [comment]
Thanks for the quick response. Will try it out.

**Comment by batzen** [comment]
Will close this. The real issue will be fixed with #349
