### ISSUE TITLE
Expose GroupByAdvanced from GalleryPanel on Gallery and InRibbonGallery

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#340]
Should I actually want to use that? Is GroupByAdvanced accessible in some way from the gallery in xaml or do I need to change the gallery template to set this value on the GalleryPanel?

Thank you

--
### Environment

- Fluent.Ribbon v4.0.3.394
- Theme Office 2013
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
You can provide your own method (func<object, string>) to determine the group for a given item.

**Comment by polepage** [comment]
Actually I wanted to know if that was usable directly on the Gallery instance.

The Gallery class has a GroupBy property that I can use with a string.
The GalleryPanel class has the GroupBy property and the GroupByAdvanced property.

Since my xaml file exposes only the Gallery instance, I had to use a behavior/code behind to bind my function to the underlying GalleryPanel of the Gallery.

Is there a way to do this directly on the Gallery? And if not, is it desirable to expose this on the Gallery class?

**Comment by batzen** [comment]
Will have a look at this.
