### ISSUE TITLE
Invisible header of combobox on QuickAccessToolBar.

### ISSUE THREAD

**Issue by ryo1988** [fluentribbon/Fluent.Ribbon#344]
## 

![image](https://cloud.githubusercontent.com/assets/6487424/18154910/9b9163d8-7043-11e6-9e4b-6169763c454d.png)
### Environment
- Fluent.Ribbon v5.0.0.0(SRC)
- Theme **?**
- Windows 10
- .NET Framework **?.?**

**Comment by batzen** [comment]
That's not looking correct.

**Comment by batzen** [comment]
The problem is larger than i thought, thus can't be fixed in 5.0.
As i don't use the QuickAccessToolbar and everything related to it myself, my motivation to fix this is very low.
I am sorry for that, but my time is very limited.
If you want to give it a try, feel free to do so.

**Comment by batzen** [comment]
This might also be related to #459
