### ISSUE TITLE
RibbonWindow icon is blurry

### ISSUE THREAD

**Issue by chdft** [fluentribbon/Fluent.Ribbon#346]
With the current dev-version of Fluent ribbon, the icon of the RibbonWindow is blurry again. A similar behavior was already observed and fixed in #50 and #63, however this time, the blurry icon *is not* stretched. As you can see in the following image, all icons are 16px tall (as expected).
![fluentribbon-icons](https://cloud.githubusercontent.com/assets/6153920/18291307/678944fa-7487-11e6-87e9-70c3ce02cb69.png)
(from left to right: Windows Explorer (correctly rendered icon); .Net 4.0; .Net 4.5)

Judging based on the color of the pixels representing the border, it looks like WPF is trying to move the icon half a pixel upwards. Normally this should be prevented by setting `SnapsToDevicePixels="True"` - as is already done. Maybe setting the `Margin="4,1,0,0"` instead of `Margin="4,0,0,0"` helps, like in #63.
I'm currently unable to test this potential fix myself, since I'm still stuck with VS2013 :/

This behavior is reproducible using the Fluent.Test application. (I used the [build from appveyor](https://ci.appveyor.com/api/buildjobs/diejgsb6bx6p4y6a/artifacts/build%2FFluent.Ribbon.5.0.0-dev0430.zip))

--
### Environment

- Fluent.Ribbon __v5.0.0-dev0430__
- Theme __Office 2013__ (only available)
- Windows __7 and 10 1607 (Build 14393.10)__
- .NET Framework __4.0 and 4.5__
- DPI-Settings/Scaling __96ppi/100%__

**Comment by batzen** [comment]
Will have a look at this.

**Comment by batzen** [comment]
Changing the margin fixes the issue. Somethings WPF is a bitch...
