### ISSUE TITLE
When changing BackstageTabItem the templated UserControl do initialize again

### ISSUE THREAD

**Issue by juergschweigi** [fluentribbon/Fluent.Ribbon#347]
Im using 
- Fluent.Ribbon __v3.6.1__
- Windows __10__
- VisualStudio 2015
- .NET Framework __4.5__

In every BackstageTabItems of my BackstageTabControl i use a DataTemplate with a UserControl like:
<Fluent:BackstageTabItem Header="Start">
                    <Fluent:BackstageTabItem.ContentTemplate>
                        <DataTemplate>
                            <local:BackstageStart BackstageParent="{Binding ElementName=RibbonBackstageName}"/>
                            
                        </DataTemplate>
                    </Fluent:BackstageTabItem.ContentTemplate>
                </Fluent:BackstageTabItem>

When then application is running i saw in Debug-Mode, that every Target-UserContol goes to Initialize once more if I Change the BackstageTabItem.

Is that a BUG???

**Comment by batzen** [comment]
That's just regular TabControl behavior.
Try placing your items in a regular TabControl and you will observe the exact same behavior.

**Comment by juergschweigi** [comment]
OK thanks for the answer,
but is there a possibility, to deny the new Initialize? 
Because in my usercontrols of the BackstageTabItems I have Datagrids binded with CollectionViewSources  and special Settings and when I Change to another BackstageTabItem i don't want a new Initialize when i went back.

And how do I select BackstageTabItems programmatically???

Greetings Jürgen

**Comment by batzen** [comment]
BackstageTabControl inherits from Selector so you should be able to use SelectedItem.

**Comment by batzen** [comment]
Regarding multiple initialization: Will have to have a look and try some things by myself. Maybe i'll find some time this week.

**Comment by batzen** [comment]
Still very busy and broken internet for one week...
Why did you close this?

**Comment by juergschweigi** [comment]
I didn't Close :-( 
I have clicked the wrong Button
"Wer lesen kann ist klar im Vorteil!!!" :-)
Sorry, now i Reopen this issue

**Comment by juergschweigi** [comment]
Hallo,
i ve solved the Problem. I put all CodeBehind within a ViewModel as Singleton. So all Settings and Bindings in BackstageTabItem are fixed.
Thank you for spending your Time.

Greetings Jürgen
