### ISSUE TITLE
Windows8 Theme - MahApps BaseDark

### ISSUE THREAD

**Issue by pwoestmann** [fluentribbon/Fluent.Ribbon#348]
## 
### Environment
- Fluent.Ribbon v4.0.3
- Theme Windows8
- Windows 10
- .NET Framework 4.5.2

The Fluent.Ribbons features are pretty awesome, but
unfortunately there is no Theme with a matching background for the popular MahApps Metro "BaseDark" Theme. Is this a planned features or are there workarounds to use the Fluent.Ribbon in a dark App?

**Comment by danielearwicker** [comment]
I'm taking the approach of creating a ColorsDark to be an alternative to ColorsWhite, then building Dark.xaml as an alternative to Generic.xaml (from Dark.txt, corresponding to Generic.txt).

Seems like there are a few hard-coded colors in the XAML, so also inventing a few new brush keys also.

**Comment by batzen** [comment]
All themes, except a generic one based on the previous office 2013 theme, are gone/removed in version 5. My plan was to support the color keys from MahApps by providing a mapping.
If you like to start that mapping already i would be very happy to get some help. But please base your work on the develop branch.

**Comment by danielearwicker** [comment]
NB. not just about mapping. I've been trying various components and then going into the source and fixing all the places that say `"Black"` or `"White"` etc.

**Comment by batzen** [comment]
Yeah, that has to be done too.

**Comment by batzen** [comment]
Did you start already?

**Comment by danielearwicker** [comment]
I don't know if I'm doing what you're thinking of, as I am in a rush (of course). Here's my fork: https://github.com/danielearwicker/Fluent.Ribbon

**Comment by batzen** [comment]
You should sync your repo as i already moved some parts around.
Introducing color/brush resources for every hard coded color looks good to me.

Your changes to the project files look bad to me.
ColorsWhite does not exist anymore.

We should not introduce a new dark theme, just colors. So there is no need for dark.txt.
If someone wants to use a different color scheme he would simply include "Generix.xaml" and the desired color resources afterwards.

**Comment by danielearwicker** [comment]
Apologies I can't put further time into this (my employer just bought Telerik licences!)

**Comment by batzen** [comment]
That's sad. Will close this issue then...

**Comment by danielearwicker** [comment]
NB. I didn't open it so the fact I can't work on it is probably not a reason to close it.

**Comment by batzen** [comment]
Oh, totally forgot about that fact. Will reopen. ;-)

**Comment by batzen** [comment]
Color schemes and accents are now present in Fluent.Ribbon.
