### ISSUE TITLE
Window.Title in Ribbon

### ISSUE THREAD

**Issue by pwoestmann** [fluentribbon/Fluent.Ribbon#350]
## 
### Environment
- Fluent.Ribbon v4.0.3
- Theme Office2010 Black
- Windows 10
- .NET Framework 4.6

Hey great, great work so far!
Is it possible to show a different title than the Window.Title in the Ribbon? 
The <Fluent.Ribbon  Title="" /> property seems not to work in xaml. 
Im using the Ribbon in a MetroWindow and want to bind the "Fluent Ribbon Control Suite 1.3" to a property in code behind.

![](https://raw.githubusercontent.com/fluentribbon/Fluent.Ribbon/master/Images/Fluent.png)

Thank you in advance

**Comment by batzen** [comment]
That's currently not possible. But #349 should make it easier to use the ribbon in a MetroWindow.

**Comment by batzen** [comment]
Did that answer your question?
The titlebar is now separated from the ribbon itself.
