### ISSUE TITLE
Combobox Virtualization Broken?

### ISSUE THREAD

**Issue by changbowen** [fluentribbon/Fluent.Ribbon#353]
Hello,
Switched to version 5. Looks like the virtualization in combobox in the new version is broken?
If I set the ItemsPanel to a VirtualizingStackPanel manually in XAML then the virtualization works and the dropdown opens fast with large number of records.
Thanks!

--
### Environment

- Fluent.Ribbon v5.0.0-dev 0439
- Windows 7 x64
- .NET Framework 4.5

**Comment by batzen** [comment]
In 4.0 i made VirtualizingStackPanel the default ItemsPanel for ComboBox.
This has been reverted as it's also not the case for the default ComboBox in WPF.
If you want virtualization to work you have to use 
`
<Fluent:ComboBox.ItemsPanel>
    <ItemsPanelTemplate>
        <VirtualizingStackPanel />
    </ItemsPanelTemplate>
</Fluent:ComboBox.ItemsPanel>
`

Either in your Style or on a per instance level.
Will add a change notice to the changelog for this.

**Comment by changbowen** [comment]
OK then. Already doing so and works well. Thanks for the explanation!
