### ISSUE TITLE
Ribbon help button

### ISSUE THREAD

**Issue by scoub** [fluentribbon/Fluent.Ribbon#355]
I search the property for defining the help button place on the right of the ribbon.
I can see it in screenshot of fluent:ribbon but i can't find how to set it up.
If someone know how to define it ?

Thank's

**Comment by batzen** [comment]
There is no special help button.
It's just a button placed in `Ribbon.ToolBarItems`.

**Comment by scoub** [comment]
Thank's man, you save my day. I haven't see the ToolBarItems in the propoerties.
