### ISSUE TITLE
Fluent:Ribbon Issues

### ISSUE THREAD

**Issue by henrymcbean** [fluentribbon/Fluent.Ribbon#356]
1. Trying to set the buttons size (fluent:ToggleButton) in the RibbonGroupBox to change icon when the application change size not sure what to do. I tried setting the SizeDefintion but that did not work.
2. Create some fluent:MenuItem menus but the icon image is too small, can the size be changed.
   You did a change for this item - 3.2.0 #28, but the you reverted 3.3.0 #28, not sure if done.
3. Need to change the Fluent:Button icon at runtime, cannot change the icon by binding to it. Had a search on the internet and the problem has raised before.
   Checked your bug dixes, this has been marked as done. - 3.6.1 #201.
4. Using your latest version of the ribbon and I have a problem with the fluent:InRibbonGallery. It contains the style information (similar to Word). A style is selected, I go to another style and right click on it which will give me the menu option to modify it. I must be able to determine which style is being selected. So I am using the "Ribbon_SelectedEvent" event, in their I get the visual tree then determine which on the mouse cursor is on. Using the method below. With your new version of the ribbon **I cannot search the visual tree**. Please advice?
   private void Ribbon_SelectedEvent(object sender, EventArgs e)
   {
   IEnumerable<GalleryItem> enumGallery = styleGallery.FindChildren<GalleryItem>();
   if (enumGallery == null) throw new ArgumentNullException(nameof(enumGallery));
   var count = (from GalleryItem item in enumGallery
   select item).Count(x =>
   {
   if (x.IsMouseOver)
   {
   SelGallaryItem = (GalleryItemViewModel)x.Content;
   }
   return true;
   });
   }

**Comment by batzen** [comment]
Could you crate a small repro which includes code for all your issues?

**Comment by henrymcbean** [comment]
1.  Is it possiable to resize a fluent:Button when the application resizes, your sample has no examples?
2. Can the fluent:MenuItem height be changd icons bing displayed are too small?  
You did a change for this item - 3.2.0 #28, but the you reverted 3.3.0 #28, not sure if done.
3. Need to change the Fluent:Button icon at runtime, cannot change the icon by binding to it. Had a search on the internet and the problem has raised before.

Checked your bug dixes, this has been marked as done. - 3.6.1 #201.
4. Previous version allowed me to use styleGallery.FindChildren(); on the gallery to get all the children. I then use method below to find which one the cursor is over, not able to do this in current version FindChildren does give me the chidren. 
private void Ribbon_SelectedEvent(object sender, EventArgs e)
{
	IEnumerable enumGallery = styleGallery.FindChildren();
	if (enumGallery == null) throw new 	ArgumentNullException(nameof(enumGallery));
	var count = (from GalleryItem item in enumGallery
	select item).Count(x =>
	{
		if (x.IsMouseOver)
		{
			SelGallaryItem = (GalleryItemViewModel)x.Content;
		}
	return true;
	});
}

I have marked the one your bug report says is done just need answers and sample code for question 1.

**Comment by batzen** [comment]
1. Have a look at the showcase application. In the tab "Resizing & Screentips" are quite a few examples which show dynamically sized buttons.

**Comment by batzen** [comment]
Did that answer your question?

**Comment by batzen** [comment]
@henrymcbean ping

**Comment by batzen** [comment]
@henrymcbean ping
