### ISSUE TITLE
CanAddToQuickAccessToolBar doesn't remove Add option in context menu.

### ISSUE THREAD

**Issue by polepage** [fluentribbon/Fluent.Ribbon#358]
When setting CanAddToQuickAccessToolBar to false on a control, the option to add the control to the QAT is still present and enabled in the context menu. Note that clicking on the menu item does not actually add the control to the QAT.

This has occured both in my code and in the Showcase app.
## 
### Environment
- Fluent.Ribbon 5.0.0.0
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
On which type of control did you try this?

**Comment by batzen** [comment]
On which type of control did you try this?
I need a few more details to fix this one...

**Comment by polepage** [comment]
I'll retest it on Monday.

**Comment by polepage** [comment]
My bad. I didn't notice that setting CanAddToQuickAccessToolBar to false on a control replaced the context menu item by Add Group to QAT unless the group also had CanAddToQuickAccessToolBar to false. I thought the context menu item did not disapear.
