### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#359]
I am not sure if this is the correct place to ask a question. I could not find the forums similar to the old CodePlex site.

Anyway, if I want to add a keyboard shortcut, let's say CTRL+Z to execute the undo command, what is the right way to do this:
1. Using InputBinding + KeyBinding (at what level? Ribbon or Window?) 
2. Use Fluent.Ribbon functionality, if so, can you give a hint where to look for this.

Thanks!

--
### Environment

- Fluent.Ribbon __v4.0.3__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
Creating issues is the only way on GitHub do ask questions.
For simple questions you could also visit the fluent.ribbon gitter-channel at https://gitter.im/fluentribbon/Fluent.Ribbon

1. Use it at the level you prefer, but to make it work globally in your application/window you should attach it to the window, as using inputbinding on the ribbon only works when the ribbon has focus, as far as i remember how it works in WPF.

2. Fluent.Ribbon has no special functionality, except KeyTips, for this.

**Comment by atlastodor** [comment]
Thanks. The conclusion is:
- Use InputBinding + KeyBinding
- Put them at the Window level
