### ISSUE TITLE
Toggle Button gets a 1px red border if a IsChecked=false get set

### ISSUE THREAD

**Issue by uwebraunholz** [fluentribbon/Fluent.Ribbon#363]
If a togglebutton is set to IsChecked=false it gets a 1px red border. I cound't figure out why or how to stop it.
I suppose this is not intended to be in the unchanged default style anyhow?
How can I stop it from doing that within my xaml or codebehind?

![unbenannt](https://cloud.githubusercontent.com/assets/7031553/19625288/aba9a074-9914-11e6-967e-eaa33e29484f.PNG)

Thanks!
## 
### Environment
- Fluent.Ribbon 4.0.3.394
- Theme Office 2013
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
Do you set the value using bindings? Red borders are usually a sign for some kind of binding error.

**Comment by uwebraunholz** [comment]
Thanks for your comment. If this would be the case then it might be with the converter.
I bind it with an IValueConverter for en enum to the ViewModel

I have a couple of ToggleButtons like this:

```
<Fluent:ToggleButton GroupName="Group" Content="ABC" Header="ABC" IsChecked="{Binding Path=SelectedType, Mode=TwoWay,Converter={StaticResource enumConverter}, ConverterParameter=ABC}" />
<Fluent:ToggleButton GroupName="Group" Content="DEF" Header="DEF" IsChecked="{Binding Path=SelectedType, Mode=TwoWay,Converter={StaticResource enumConverter}, ConverterParameter=DEF}" />
```
This is the Converter.
```
   public class EnumConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value == null || parameter == null)
                return false;

            string checkValue = value.ToString();
            string targetValue = parameter.ToString();
            return checkValue.Equals(targetValue, StringComparison.InvariantCultureIgnoreCase);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value == null || parameter == null)
                return null;

            bool useValue = (bool)value;
            string targetValue = parameter.ToString();
            if (useValue)
                return Enum.Parse(targetType, targetValue);

            return null;
        }
    }
```
The issue seems to be the returning `null` at the `ConvertBack` for the unselected item.

But what should it return so the unchecked toggle button knows how to handle? Actually it works fine except for the red border.

**Comment by batzen** [comment]
ConvertBack is used to convert the value from the togglebutton back to your binding source/viewmodel.

Is "SelectedType" a nullable type?
If not, that should be your problem and you should better return the default enum value in that case.

**Comment by uwebraunholz** [comment]
Yes, that was it. As there is only one property that handlesall the togglebuttons I had to make sure the defefault value is then not acepted by the vewmodel as well as that no button is using that value. Works great now and saves me the need to ad a property for each button.

Thank you very much!

**Comment by batzen** [comment]
Glad i could help you.

Anything else i can help you with? Otherwise i would like to close this issue/question. ;-)
