### ISSUE TITLE
RibbonTabItem is not derived from ContentControl

### ISSUE THREAD

**Issue by juergschweigi** [fluentribbon/Fluent.Ribbon#364]
Hallo,
BackstageTabItem is derived from ContentControl, so you can use a UserConrol in a ContentDataTemplate for BackstageTabItem!!! All fine, but...
Why is RibbonTabItem not derived from ContentControl but only from Control??? 
So you cannot use any UserControl within a ContentDataTemplate for the RibbonTabItems.
TabItems in a normaly TabControl are derived from HeaderedContentControl.
I Need this, because I want use UserContols for RibbonTabItem.
Greetings Jürgen

**Comment by batzen** [comment]
The reason for that is pretty simple.

- BackstageTabItem is designed to display a single content element/area.
- RibbonTabItem is designed to display items which are organized in groups.

I am just wondering why you don't create a RibbonGroupBox and insert your item there. Nothing prevents you from doing so.
RibbonGroupBox inherits from ItemsControl, so you should be able to display whatever you want in there.

**Comment by juergschweigi** [comment]
Ok,
the reason for my Problem is, i want to see the RibbonTabItems with GroupBoxes in DesignTime. So i make a UserControl for each RibbonTabItem within then RibbonGroupBoxes. Then while Designing UserControl i can see the GroupBoxes with Controls in the RibbonBar, but
i have solved the Problem:
in RibbonWindow in Resources I implement ControlTemplates for each UserControl , for example:
**<ControlTemplate x:Key="TabTestUserControl" TargetType="Fluent:RibbonGroupBox">
    <Grid>
        <local:TestUserControl/>
     </Grid> 
 </ControlTemplate>**
and then in each RibbonTabItem I set:
**<Fluent:Ribbon>
   ...
   <Fluent:RibbonTabItem  Header="Test" KeyTip="T" DataContext="{Binding TestViewModel}">
       <Fluent:RibbonGroupBox Template="{StaticResource TabTestUserControl}"/>
   </Fluent:RibbonTabItem>
</Fluent:Ribbon>**

With Backstage (Ribbon.Menu) it is easier to work with UserControls.
