### ISSUE TITLE
Argument Exception in Designer: 'RibbonGroupBox' ControlTemplate TargetType does not match templated type 'RibbonGroupBox'.

### ISSUE THREAD

**Issue by Tobipz** [fluentribbon/Fluent.Ribbon#366]
I'm using VS2012 Express and Fluent Ribbon 4.0.3, with .NET 4.5 and Windows 7.

I worked about a week with Fluent Ribbon and suddenly i got the following Error Message in the Designerwindow:
ArgumentException: 'RibbonGroupBox' ControlTemplate TargetType does not match templated type 'RibbonGroupBox'.
StackTrace:
at System.Windows.Controls.ControlTemplate.ValidateTemplatedParent(FrameworkElement templatedParent)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
InnerException: None

In the XAML-Code RibbonGroupBox or BackstageTabControl Items are randomly underlined blue, as seen in the Pictures
![image](https://cloud.githubusercontent.com/assets/22940295/19923976/3752cf10-a0ea-11e6-90a5-1cf2c923c270.png)
![image](https://cloud.githubusercontent.com/assets/22940295/19923983/3cc44172-a0ea-11e6-8073-b28cc2bea5c0.png)

When i run the project, it gets compiled without any problems. Just the designerwindow finds this Exception. 

Right after opening the .sln everything works fine, but after a bit of waiting and compiling, the exception occurs.

I already tried reinstalling VS, switching .NET to different versions, Recoding the whole Project and disabling the display of Argument Exceptions. None of this worked...
When i opened the .sln on Windows 10 and VS 2015 Enterprise, i get the same Error.

Hope you can help me,
Thanks in advance,
Tobi

**Comment by batzen** [comment]
The designer in visual studio is very buggy.

Have you tried cleaning your temp directory?
Maybe that helps.

**Comment by Tobipz** [comment]
Thank you for your quick answer! 
What temp directory do you mean? "obj"?
I tried it on a different PC on a different Windows and different VS, still same exception.
I also tried the options "Clean Solution" and "Rebuild Solution" if that helps.

The Exception first occured a while after i added this extension: [wpflocalizeextension.codeplex.com](url). Maybe there is some kind of incompatibility...

**Comment by batzen** [comment]
I was talking about your temp directory reachable by %temp%.

As it works at runtime and only throws the exception after some time in the designer, it's definitely a bug in the visual studio designer and you should report that bug to microsoft.
