### ISSUE TITLE
Render Glitch when Maximizing RibbonWindow with SizeToContent Enabled

### ISSUE THREAD

**Issue by changbowen** [fluentribbon/Fluent.Ribbon#368]
I'm using the latest build from AppVeyor. Looks like there are some glitch in rendering of the RibbonWindow when SizeToContent of the RibbonWindow property is **not** set to Manual (the default value). And the problem only surfaces when maximizing the window from the maximize button on the top-right corner: instead of showing a full-screen window, a window with black bars surrounded is shown.
Double-clicking the window title maximizes the window fine, and also fixes the problem for future maximizing of the single instance of the window. A manual resize also fixes the problem temporarily.
The below issue might be related.
#153 

---
### Environment

- Fluent.Ribbon v5.0.0
- Windows 7 x64
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Will have to fix this in ControlzEx, please see details there.
