### ISSUE TITLE
Changing Foreground / Padding of ComboBox?

### ISSUE THREAD

**Issue by changbowen** [fluentribbon/Fluent.Ribbon#370]
Hi, is there any way to change the foreground, padding and perhaps other properties of combobox? I have tried and changing any of the above two properties is not working.

**Comment by batzen** [comment]
Setting the foreground should work without any problems, just tried it in the sample application.

Setting the padding is just ignored because the Fluent:ComboBox is meant to be displayed in the ribbon where padding is not meant to be used.
