### ISSUE TITLE
Dynamic Color Assignment

### ISSUE THREAD

**Issue by Zarraya** [fluentribbon/Fluent.Ribbon#371]
Hello,

I have been using Fluent for a while now and have been able to set the color theme just fine using the following code
 `<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">#1E90FF</Color>` 
in a ResourceDictionary that is then referenced in App.xaml with the line 
`<ResourceDictionary Source="FluentAlterations.xaml"/>`

Is it possible to have the value for MetroColor.ThemeColorKey set dynamically based on a property in Properties.Settings? How would one go about accomplishing this? Thank you for your time.

---
### Environment

- Fluent.Ribbon  v4.0.3
- Theme Office 2013 Generic
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
The showcase application contains a sample for this.
Have a look at `ColorViewModel.ThemeColor` to see how it's done and the button showing this on the ui is the blue underlined "A" in "Toolbars => Font".
