### ISSUE TITLE
Override default style for TextBlock change Ribbon layout

### ISSUE THREAD

**Issue by jan-schubert** [fluentribbon/Fluent.Ribbon#372]
I defined a default style for my application:

```
<Style TargetType="{x:Type TextBlock}">
  <Setter Property="Foreground" Value="Gray" />
</Style>
```

Now, all BackstageTabItem Header get the same foreground.

Is that a bug or is there a simple way to use the Foreground of the loaded theme?

**Comment by batzen** [comment]
That's not a bug, that's just what happens if you override the default style for a very basic control used everywhere.

>  is there a simple way to use the Foreground of the loaded theme?

Which theme? Your windows theme? The ribbon theme?
The foreground should match the ribbon theme by default.

**Comment by jan-schubert** [comment]
I use the "/Fluent;component/themes/office2013/generic.xaml" theme. The BackgroundColor is blue and the Foreground should be white.

**Comment by batzen** [comment]
Why do you expect the foreground to be white when you just overwrote it with gray?

The foreground for the backstage is available through "BackstageFontBrush".

**Comment by jan-schubert** [comment]
I thought the ribbon control has it own style and overrides my default style. So if I override the default style in the App.xaml it will only affect my controls.

Now, I think you are right. It was silly to expect it will not affect the ribbon.
