### ISSUE TITLE
RibbonWindow, WindowStyle="none", not working correct

### ISSUE THREAD

**Issue by WeiJiang0909** [fluentribbon/Fluent.Ribbon#373]
Place your issue description here.

Hello, I tried to build a wpf window without titlebar (no menu, no drag and move), so I set WindowStyle="none", the titlebar disappear, but I could drag/move the window, also, if right-click, the pop-up menu will show. Please help!

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.5_

**Comment by batzen** [comment]
The window has special styling applied to it.
If you want to use a window without a working titlebar i would suggest you use a regular window instead of a ribbon window.
The ribbonwindow in version 5 has set WindowStyle="none" by default.

**Comment by WeiJiang0909** [comment]
Gotta, thank you!

**Comment by batzen** [comment]
Do you have any further questions, or can we close this?
