### ISSUE TITLE
How to edit "File" tab text

### ISSUE THREAD

**Issue by bacca87** [fluentribbon/Fluent.Ribbon#376]
I would like to change the "File" tab text to uppercase (FILE), Is that possible usingi fluent?

Thanks

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __office2013__ (not needed in version 5.0 and upwards)
- Windows __7__
- .NET Framework __4.6__

**Comment by batzen** [comment]
Which "File" tab do you mean?
The `Backstage`-Button-Header?

If it's the backstage button header you can use the `Header` property on that to control the text.

**Comment by bacca87** [comment]
Yes, thank you!!!
