### ISSUE TITLE
Force DropDownButton popup to close

### ISSUE THREAD

**Issue by bacca87** [fluentribbon/Fluent.Ribbon#378]
There is a way to programmatically force the DropDownButton to close?
ClosePopupOnMouseDown it's not a solution in my case, because i need to close the popup only after a specific action.

Thank you

---
### Environment

- Fluent.Ribbon __v4.0.3.394?__
- Theme __office2013__ (not needed in version 5.0 and upwards)
- Windows __7__
- .NET Framework __4.6__

**Comment by batzen** [comment]
You could set IsOpen to false. Setting IsDefinitive to true, in case your action means a button click, should also close the DropDownButton.

**Comment by bacca87** [comment]
I guess those properties are not existing in my version. I solved this problem setting IsDropDownOpen to false.
Thank you

**Comment by batzen** [comment]
`IsDefinitive` is a property located on `Button`.
`IsOpen` is really called `IsDropDownOpen`. I answered from my mobile and had no fast way to look up the exact name, sorry for confusing you.
