### ISSUE TITLE
BackstageTabControl SelectionChanged event affected by DataGrid or Listview selection change

### ISSUE THREAD

**Issue by bacca87** [fluentribbon/Fluent.Ribbon#379]
If you put a DataGrid or Listview inside a BackstageTabItem, and then you click on a row with data, the Datagrid/Listview SelectionChanged and the BackstageTabControl SelectionChanged too are fired.
This is very annoying because I use the BackstageTabControl SelectionChanged for loading the data inside the Listview.

How can I prevent this issue?

```
<Fluent:BackstageTabControl Name="menuBackstageTabControl" SelectionChanged="BackstageTabControl_SelectionChanged">
	<Fluent:BackstageTabItem Header="Informations"/>
	<Fluent:BackstageTabItem Name="factoriesBackstageTab" Header="Factories">
		<Grid>
			<Grid.ColumnDefinitions>
				<ColumnDefinition></ColumnDefinition>
				<ColumnDefinition></ColumnDefinition>
			</Grid.ColumnDefinitions>
			<Grid.RowDefinitions>
				<RowDefinition></RowDefinition>
				<RowDefinition></RowDefinition>
			</Grid.RowDefinitions>
			<ListView Name="factoriesListView"
					  Grid.RowSpan="2" 
					  Grid.Column="0" 
					  Grid.Row="0">
				<ListView.View>
					<GridView>                                            
						<GridViewColumn Header="Name" DisplayMemberBinding="{Binding Name}" />
						<GridViewColumn Header="CompanyName" DisplayMemberBinding="{Binding CompanyName}" />
						<GridViewColumn Header="Address" DisplayMemberBinding="{Binding Address}" />
						<GridViewColumn Header="TransferType" DisplayMemberBinding="{Binding TransferType}" />
						<GridViewColumn Header="IsForfait" DisplayMemberBinding="{Binding IsForfait}" />
					</GridView>
				</ListView.View>
			</ListView>
			<Button Click="Button_Click" Grid.Row="0" Grid.Column="1"></Button>
			<Gmap:GMapControl x:Name="mapControl" Grid.Column="1" Grid.Row="1" Zoom="13" MaxZoom="24" MinZoom="1" />
		</Grid>
	</Fluent:BackstageTabItem>
	<Fluent:SeparatorTabItem />
	<Fluent:BackstageTabItem Header="Settings"/>
	<Fluent:Button Name="exitButton" Header="Exit" Click="exitButton_Click"/>
</Fluent:BackstageTabControl>
```

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __office2013__ (not needed in version 5.0 and upwards)
- Windows __7__
- .NET Framework __4.6__

**Comment by bacca87** [comment]
At the moment, for workaround this issue, i've put all the controls inside a page and then i've just added a frame inside BackstageTabItem pointing that page.
In this way the BackstageTabControl SelectionChanged event is not affected by Listview selection changes.

**Comment by batzen** [comment]
That's not an issue with Fluent.Ribbon, but an issue with WPF itself.
SelectionChanged is routed through all controls, you can prevent your issue by checking if the orginal source of the event is really the backstage or not.

That should solve your problem.
