### ISSUE TITLE
Change the hover Color of the Window Close Button

### ISSUE THREAD

**Issue by MaaadMax** [fluentribbon/Fluent.Ribbon#380]
---
Hi
is it possible to change the the color of the window close button when I hover with the mouse? In Version 4 the color was red on hover and that's the Windows standard I think. In the new Version 5.0 the color is the same as for the minimize/maximize buttons (I think its some kind of blue?)
### Environment

- Fluent.Ribbon __v 5.0
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
It hasn't changed. But you are correct, it should be red for the close button.

**Comment by floele-sp** [comment]
@batzen While I like the idea of making the close button red on hover, it should have a white X then and not a black one.

**Comment by floele-sp** [comment]
This patch works for me. Probably needs some refinement. The Foreground color handling seems a bit weird in WindowCommands.xaml because it currently binds to a foreground color that isn't even used.
[foreground.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/723332/foreground.zip)
