### ISSUE TITLE
QuickAccess Toolbar

### ISSUE THREAD

**Issue by henrymcbean** [fluentribbon/Fluent.Ribbon#381]
Hi Bastian
C# WPF application where I am using your control. It seem that when the application is selected you get the blue highlighted (active window) header, it is this causing a problem. When the header colour is changed if the fluent:Ribbon.QuickAccessItems toolbar is set to Show Above the Ribbon the control is not redrawn.

I have attached two files containing to screen capture, the first when the application starts and the second when I click on the desktop away from the application.  You can see in the bad image the QuickAccess Toolbar has not been repainted.  If I minimize and restore its fine. 

![bad](https://cloud.githubusercontent.com/assets/6997864/21234054/4e8cbb0c-c2e9-11e6-979f-d2c0622af820.png)
![good](https://cloud.githubusercontent.com/assets/6997864/21234053/4e8be312-c2e9-11e6-845b-e2917e0cee08.png)

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
It not the QuickAccessToolbar causing issues, it's the window itself.
I've seen this issue sporadically already, but never found a way to reproduce it reliably.

Are you able to reproduce it realiably?

**Comment by henrymcbean** [comment]
The problem only appeared when I used the new version of the ribbon.  One thing that I noticed is that it seem that it was overlaid with another header, to the right of the header there was another minimise button then the three buttons minimise maximise and close button.  I needed to force a repaint by minimise and maximise the application.

Sent from my iPhone

On 17 Dec 2016, at 15:37, Bastian Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


It not the QuickAccessToolbar causing issues, it's the window itself.
I've seen this issue sporadically already, but never found a way to reproduce it reliably.

Are you able to reproduce it realiably?

-

**Comment by henrymcbean** [comment]
Where would I find the ribbon version number?  Looked in file "appveyor.yml" and found version: 5.0.0-dev{build}.  Our development is done a VM machine running Windows Server 2012 R2 Standard, run the application on Windows 10.  I am experiencing the problem on both machines.  Using the .Net 4.0 version of your control.  From your documentation (Fluent Ribbon Control Suite Walkthrough.pdf) it instruct me to specify one of the Theme in the App.xaml file.  Prior to changing to you new version of the ribbon I was using the Office2013 theme.  You do not have a Office2013 theme in the solution to use, the theme does set the look of the application I am using the Generic.xaml.  Could this be causing a problem with me experiencing the header repainting problem?

**Comment by henrymcbean** [comment]
Just noticed when I click away from the application (on the desktop) the size of the application changes as well as the header not being repainted.

**Comment by batzen** [comment]
The walk through is totally outdated and will be deleted.
The different themes (office 2010, office 2013 and windows 8) are gone to ease maintenance of this library, this should not cause any WindowChrome rendering issues.

It's not the header that's causing issues, it's the WindowChrome.

So if you are working with your application everything is fine, but as soon as you click on the desktop the WindowChrome stops rendering correctly?

**Comment by henrymcbean** [comment]
Hi Bastian, Fixed the issue needed to update ControlzEx & MahApps.Metro, thanks.
