### ISSUE TITLE
Missing Border under the RibbonTabItem

### ISSUE THREAD

**Issue by MaaadMax** [fluentribbon/Fluent.Ribbon#382]
---
Hi,
in the new Version (5.0.0) there is no border anymore under the RibbonTabItems. It's difficult to explain which border I mean, so I made a picture for you:
![fluentribbonborder](https://cloud.githubusercontent.com/assets/24289066/21266593/43210f2a-c3a7-11e6-8142-596502520d5f.png)

In the old Version (4.0.3) the border was continous under the TabItems and stopped at the active TabItem. In the new Version the border stops on the first TabItem. It is also the same, when the Ribbon is collapsed.

It's not a big deal, just a fashion thing.

### Environment

- Fluent.Ribbon __v 5.0.0
- Windows __?__
- .NET Framework 4.5

**Comment by batzen** [comment]
Well, the Backstage button is also missing and the background for the selected tab item seems to broken too.

But i am unable to reproduce your issue. Everything that's missing on your screenshot is shown on my machine.

Anything you changed on your side?

**Comment by MaaadMax** [comment]
Oh yea I really changed some things. I haven't thought about that. I will test it after Christmas and will inform you about the result. 

Have a nice Christmas :)

**Comment by batzen** [comment]
You too. ;-)

**Comment by batzen** [comment]
Using wrong issue number...
