### ISSUE TITLE
W10 Universal App Platform support

### ISSUE THREAD

**Issue by Trolldemorted** [fluentribbon/Fluent.Ribbon#384]
I wanted to give Fluent.Ribbon a shot, but when installing it via NuGet for my UWP project, but the installation fails:

```
Fluent.Ribbon 4.0.3.394 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
ControlzEx 2.0.1.61 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
```

Is there a reason why it should not work on UWP?

**Comment by batzen** [comment]
I never tried to develop for UWP, so i can't say if there are reasons why it shouldn't work on UWP.

I guess the Window related stuff will cause problems, but i currently know nearly nothing about UWP.
Will install the required tooling and give it a try.

**Comment by batzen** [comment]
I just had a look.
It would cost a lot of work to actually port everything to UWP.

**Comment by Trolldemorted** [comment]
could you elaborate? i assume things like items in the title bar do not go well with UWP?


as far as i know, the windows app store is limited to UWP apps (even if you only deploy to desktops), so you might want to think about adding this feature set in the future.

**Comment by pekspro** [comment]
WPF and UWP and two totally different frameworks. WPF is targeting desktops and UWP is targeting desktop, tablets, mobile, Xbox, HoloLens etc. There are absolutely some similarities but also a lot of differences. It's no easy task to port Fluent Ribbon to UWP.

Office, Excel and PowerPoint is available in UWP. It looks a bit different compared with the classic version (especially the ribbon bar).

When it comes to Windows Store, it does support classic desktop applications, including WPF. I'm not sure if this is open for every developer yet but some applications could be downloaded right now (like Evernote).

**Comment by TheCamel** [comment]
Hi,
I had a try with my app ([CBR](https://github.com/TheCamel/CBR)) to be packaged as UWP application and it works. But it's not a truly UWP app, it's just a way of pack & deploy...btw, I think porting ribbon "design" to UWP is useless because of this type of design (that i like !) is deprecated and it will be hard to support on all screen size with very complex "ResponsiveDesign" queries
