### ISSUE TITLE
Hide (or not  display) context menu with "Add to Quick Access Toolbar" 

### ISSUE THREAD

**Issue by Davidos56** [fluentribbon/Fluent.Ribbon#385]
Hello 

I have a simply question about This Context Menu. 
How to do to "Context Menu" with "Add to Quick ..." will does not appear when I right clicked ??
Is it possible to hide or not display this ??
Thanks in advance.

### Environment

- Fluent.Ribbon __v 3.6.0__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __451__

**Comment by Davidos56** [comment]
OK I found the solution for this . Only what we can do is  add ContextMenuOpening property with handler.

<f:Ribbon ContextMenuOpening="FRibbon_ContextMenuOpening" >


and in background we have to write this function : 

 private void FRibbon_ContextMenuOpening(object sender, ContextMenuEventArgs e)
        {
            e.Handled = true;
        }

In all ribbon we deable context menu.I apologize for the problems.

**Comment by batzen** [comment]
You also could have used
`<f:Ribbon CanCustomizeQuickAccessToolBarItems="False">`
