### ISSUE TITLE
How to add/delete buttons from DevRibbonGroupBox?

### ISSUE THREAD

**Issue by VijayKamat** [fluentribbon/Fluent.Ribbon#386]
I am working on a project where I want to put the ribbons on top and modify them: Move buttons like "B" (bold) etc from one division to another etc. Anytime, I delete or add a control through the XAML the whole box goes crazy. The box disappears (in expression blend I can see it shifts outside of the window). 
What is the right way to customize (add/delete/shift) controls in the ribbons?
---
### Environment

- Fluent.Ribbon __v?.?.?__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
DevRibbonGroupBox? Never heard of that.
Are you talking about the designer experience or a, real, runtime bug?

**Comment by VijayKamat** [comment]
I have it in my project and I thought it is a component provided by the package. Anyway I figured a way to move the buttons. Just move them in the XAML part and on the next build/run the UI updates itself.

**Comment by batzen** [comment]
Glad you figured it out.
