### ISSUE TITLE
Disable/Hide the Menu-DropDown in QuickAccessToolbar

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#387]
Hi

Right now I am on a relatively small application (400 x 300 pixels) so I decided to move some of the less used functions to the `QuickAccessToolbar`. Because one of these functions is **Options** I do not want to allow the user to customize the toolbar (because of Murphy's laws it will be sure that some of the ... you know what kind of users I mean ... will disable it and call me because the options are gone ...). The most obvious way for me was to set `CanCustomizeQuickAccessToolBar="False"`. Unfortunately it seems to have no effect. Is this option not meant to hide the dropdown menu?

These are all options I use right now:
- `CanCustomizeRibbon="False"`
- `IsAutomaticCollapseEnabled="False"`
- `CanMinimize="False"`
- `CanCustomizeQuickAccessToolBar="False"`
- `CanCustomizeQuickAccessToolBarItems="False"`
- `CanQuickAccessLocationChanging="False"`
- `IsQuickAccessToolBarVisible="True"`

My current workaround is to make the `QuickAccessMenuItem` not checkable but that seems to be an ugly solution.

Thanks in advance. You do a great job with this Ribbon. It is by far the best solution I found right now.

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __Office2013__
- Windows __8.1__
- .NET Framework __4.5__

**Comment by batzen** [comment]
There is currently no way to disable the dropdown menu.

CanCustomizeQuickAccessToolBar just adds "Customize Quick Access Toolbar..." to the context menu and you have to handle the event `CustomizeQuickAccessToolbar` to actually cause something to happen. I honestly don't know why this was added/implemented.

CanCustomizeQuickAccessToolBarItems disables adding and removing items to the toolbar.

Will mark this as an enhancement as it's quite difficult to hide that button.
