### ISSUE TITLE
Issues with internationalization

### ISSUE THREAD

**Issue by afdeprado** [fluentribbon/Fluent.Ribbon#389]
I have adopted your Fluent.Ribbon component for an application I'm working on. Right now, I'm in the process of localizing it in different languages.  I'm using the Infralution localization components presented in the following link: [WPF Localization Using RESX Files](https://www.codeproject.com/Articles/35159/WPF-Localization-Using-RESX-Files?fid=1538725&df=90&mpp=25&sort=Position&spc=Relaxed&view=Normal&fr=26#xx0xx). I have stumbled on two issues:
- This component allows me to do dynamic language switching. By changing the thread's CurrentCulture, all the interface is automatically switched to the selected language (if the resources are available, of course). When I do this with labels on the Fluent.Ribbon, the Ribbon does not re-adjust correctly the sizes of the different components. I was able to solve this by doing a deep recursive traversal of the logical WPF tree, starting at the Ribbon, and issuing `InvalidateMeasure()` and `UpdateLayout()` for each of the children of type `FrameworkElement`. This solves the issue, but it is not an elegant solution.
- From what I'm gathering, the texts used by the Ribbon itself are fixed at the thread's current culture at application startup; I haven't found a way to change the language of the Ribbon once running. I think this could be a useful feature for the future...

Regards!

---
### Environment

- Fluent.Ribbon   v4.0.3.394
- Theme Office2013/Generic
- Windows 10 64bits,  .NET Framework  4.5, Visual Studio 2013

**Comment by cbytte** [comment]
We are using [WPF Localization Extension](https://wpflocalizeextension.codeplex.com/), for the same purposes. Works like a charm in combination with the Fluent Ribbon.
You can dynamically change the culture of the whole app by setting the 
`LocalizeDictionary.Instance.Culture = myCulture;`

The ribbon xaml must be completed with lex:Loc keys like
`<fluent:TextBox Header="{lex:Loc StylingNamePrefix_TextBoxHeader}" InputWidth="75" />`

**Comment by batzen** [comment]
The current localization of the ribbon can be changed on the fly in version 5.0 by using `RibbonLocalization.Current.Localization = new German();` or by using `RibbonLocalization.Current.Culture = myCulture;`

**Comment by AlexeiScherbakov** [comment]
Designer is not working (show blank window) when 'WPF Localization Extension' is referenced to project.
Event if there are no lex:Loc or lex:LocText inside window XAML (version 5.0.1.10)
Application starts and working normally,

**Comment by batzen** [comment]
Hi @AlexeiScherbakov it's not a good idea to add comments to a closed issue.

Besides that i can't reproduce your issue. Just adding a reference, but not using it, shouldn't change anything. 
Could you send me a repro showing your issue?

**Comment by batzen** [comment]
@AlexeiScherbakov ping?
