### ISSUE TITLE
Parts of the Ribbon not hidden correctly when opening backstage

### ISSUE THREAD

**Issue by sqeezy** [fluentribbon/Fluent.Ribbon#390]
When you place some parts of the backstge in seperate files, the context group headers will not be hidden when opening the backstage. 

```xaml
<fluent:Ribbon.Menu>
        <views:BackstageView DataContext="{Binding Backstage}" />
</fluent:Ribbon.Menu>
```
---
### Environment

- Fluent.Ribbon v.4.0.3.394
- Theme Office 2013
- Windows 7/10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
As far as i remember i fixed something in that area in version 5. Could you try reproducing your issue with version 5?

**Comment by batzen** [comment]
@sqeezy Ping

**Comment by sqeezy** [comment]
Sorry for not responding faster. I will try version 5 next week. Is there any kind of release for this version or do I have to compile for myself?

**Comment by batzen** [comment]
Just release a new [preview](https://www.nuget.org/packages/Fluent.Ribbon/5.0.0-dev0477). Will take a few minutes for nuget to list it for you.

**Comment by sqeezy** [comment]
I can not reproduce the issue in a quick standalone spike. Replacing version 4 with 5 in our project will take some effort so will close this for now.

**Comment by batzen** [comment]
May i ask whats requiring effort during the update?

**Comment by sqeezy** [comment]
We had to override/extend parts of the Theme we use. When we just drop the new version in now, it crashes at runtime.
We will update at some point but had more important things to do right now.
Should you be able to upgrade to version 5 in case you didn't alter fluent resources?

**Comment by batzen** [comment]
You should be able to upgrade a lot easier in that case. There are a few breaking changes listet in the changelog. The only thing you most likely have to change is the path to generic.xaml. Instead of Themes/Office2013/Generic.xaml it's just Themes/Generic.xaml now.
