### ISSUE TITLE
Change Window Title doesn't update Title length

### ISSUE THREAD

**Issue by MaaadMax** [fluentribbon/Fluent.Ribbon#392]
Hi,

I have found a bug in the newest version of the fluent ribbon. When I change the title of the ribbon window and the new title is longer than the old one, the new title isn't displayed correctly.

How reproduce:
Create a ribbon window with title "small title" and a button inside the window. On the click event of the button change the window title to "this title must be longer than the old one". Start the program and click on the button. The window title changes but will be displayed as "this titl...". When I resize the window (just 1mm is enough), the title is displayed correctly.

Here you can find the example project:
[FluentRibbonTitleTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/724315/FluentRibbonTitleTest.zip)

Regards,
Max
---
### Environment

- Fluent.Ribbon __v 5.0
- Windows 10 Enterprise LTSB
- .NET Framework 4.5.2

**Comment by floele-sp** [comment]
@MaaadMax Thanks for reporting this issue. I had a few repainting issues without obvious reason, the fix for this helps me as well.
