### ISSUE TITLE
application button with image

### ISSUE THREAD

**Issue by MannusEtten** [fluentribbon/Fluent.Ribbon#393]
i would like to have a menu button with image but i can't find how to implement it. like the office logo in the enclosed screenshot.

the documentation links are also not working by the way (404)
![ic129473](https://cloud.githubusercontent.com/assets/3999790/22366551/9b9b4444-e47d-11e6-9546-675e2556f00d.gif)

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
That's not a feature which is support by this library.
I abandoned the Office 2010 style and will never revive it.
If you need such a feature you will have to implement it by yourself.

Regarding the 404:
Yeah, i still have to invest much more time to get the documentation ready. But my time is so limited...
