### ISSUE TITLE
issues with contextual tab group

### ISSUE THREAD

**Issue by MannusEtten** [fluentribbon/Fluent.Ribbon#395]
i discover two issues with my contextual tab group

1) the tabs which belong to the contextual tab group are not shown till i resize the window
2) there is a strange red line around the first tab

see attached screenshots and i attached the xaml-code of my ribbon as well

is it also possible to remove the title of the app in the menu?
![screenhunter_63 feb 01 10 28](https://cloud.githubusercontent.com/assets/3999790/22501492/51c80736-e869-11e6-9268-443ecbfb032b.jpg)
![screenhunter_64 feb 01 10 28](https://cloud.githubusercontent.com/assets/3999790/22501493/51ca278c-e869-11e6-9d1e-06551f68c495.jpg)
![screenhunter_65 feb 01 10 28](https://cloud.githubusercontent.com/assets/3999790/22501494/51cd59b6-e869-11e6-9d16-13d9dab4829b.jpg)

---
### Environment

- Fluent.Ribbon __4.0.3.394
- Theme /Fluent;Component/Themes/Office2013/Generic.xaml
- Windows 10 anniversary edition
- .NET Framework 4.6.1

<Application
    x:Class="BicycleTripsPreparationApp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:converters="clr-namespace:Kent.Boogaart.Converters;assembly=Kent.Boogaart.Converters"
    xmlns:converters2="clr-namespace:BikeTouringGIS.Converters"
    xmlns:vm="clr-namespace:BikeTouringGIS.ViewModels"
    Startup="Application_Startup"
    StartupUri="Default.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <vm:ViewModelLocator x:Key="Locator" />
                    <converters:BooleanToVisibilityConverter x:Key="booleanVisibilityConverter" />
                    <converters:BooleanToVisibilityConverter x:Key="inverseBooleanVisibilityConverter" IsReversed="True" />
                    <converters2:NotNullToVisibilityConverter x:Key="notNullVisibilityConverter" />
                    <converters2:InverseNullToBooleanConverter x:Key="notNullConverter" />
                </ResourceDictionary>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Emerald.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
                <ResourceDictionary Source="Styles\Button.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

<UserControl
    x:Class="BikeTouringGIS.MainMenu"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Fluent="urn:fluent-ribbon"
    xmlns:System="clr-namespace:System;assembly=mscorlib"
    xmlns:converters="clr-namespace:BikeTouringGIS.Converters"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <UserControl.Resources>
        <converters:StringToIntConverter x:Key="stringToIntConverter" />
    </UserControl.Resources>
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="auto" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <Image
            Grid.Column="0"
            Width="150"
            Height="99"
            Margin="5,0,5,0"
            VerticalAlignment="Bottom"
            Source="bike touring gis splash screen.png"
            Stretch="Fill" />
        <Fluent:Ribbon
            x:Name="ribbonMenu"
            Grid.Column="1"
            AutomaticStateManagement="True">
            <Fluent:Ribbon.Menu>
                <Fluent:ApplicationMenu Header="File">
                    <Fluent:ApplicationMenu.RightPaneContent>
                        <StackPanel
                            HorizontalAlignment="Stretch"
                            VerticalAlignment="Stretch"
                            Orientation="Vertical">
                            <Border
                                HorizontalAlignment="Stretch"
                                BorderBrush="#64647F"
                                BorderThickness="0,0,0,0">
                                <TextBlock
                                    Padding="12,4,4,4"
                                    Background="#F6F7F8"
                                    FontSize="12"
                                    FontWeight="SemiBold"
                                    Foreground="#64647F"
                                    Text="Recent files"
                                    TextAlignment="Left" />
                            </Border>
                            <StackPanel Height="2" HorizontalAlignment="Stretch">
                                <Border
                                    Height="1"
                                    HorizontalAlignment="Stretch"
                                    BorderBrush="#DCDDDE"
                                    BorderThickness="1" />
                                <Border
                                    Height="1"
                                    HorizontalAlignment="Stretch"
                                    BorderBrush="#FEFEFF"
                                    BorderThickness="1" />
                            </StackPanel>
                        </StackPanel>
                    </Fluent:ApplicationMenu.RightPaneContent>
                    <Fluent:MenuItem Header="New" />
                    <Fluent:MenuItem Header="Open" />
                    <Fluent:MenuItem Header="Save As" />
                    <Separator />
                    <Fluent:MenuItem
                        Command="{Binding ExitCommand}"
                        Header="Exit"
                        KeyTip="X" />
                </Fluent:ApplicationMenu>
            </Fluent:Ribbon.Menu>
            <Fluent:Ribbon.ContextualGroups>
                <Fluent:RibbonContextualTabGroup
                    x:Name="layertab"
                    Background="DarkBlue"
                    BorderBrush="LightBlue"
                    Header="Layer"
                    Visibility="{Binding SelectedLayer, Converter={StaticResource notNullVisibilityConverter}}" />
            </Fluent:Ribbon.ContextualGroups>
            <Fluent:RibbonTabItem
                MinWidth="150"
                Header="Data"
                IsSelected="True">
                <Fluent:RibbonGroupBox Header="datasources">
                    <Fluent:Button
                        MinWidth="100"
                        CanAddToQuickAccessToolBar="False"
                        Command="{Binding Base.OpenGPXFileCommand}"
                        CommandParameter="{Binding Map}"
                        Header="open gpx-file"
                        SizeDefinition="10"
                        ToolTip="open gpx-file">
                        <Fluent:Button.LargeIcon>
                            <iconPacks:PackIconMaterial
                                Width="32"
                                Height="32"
                                Foreground="DarkGreen"
                                Kind="FileImport" />
                        </Fluent:Button.LargeIcon>
                    </Fluent:Button>
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
            <Fluent:RibbonTabItem
                Group="{Binding ElementName=layertab, Mode=OneWay}"
                Header="Properties"
                IsSelected="{Binding SelectedLayer, Converter={StaticResource notNullConverter}}"
                Visibility="Visible">
                <Fluent:RibbonGroupBox MinWidth="150">
                    <Fluent:TwoLineLabel Text="{Binding SelectedLayer.DisplayName}" />
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
            <Fluent:RibbonTabItem Group="{Binding ElementName=layertab, Mode=OneWay}" Header="Editing">
                <Fluent:RibbonGroupBox>
                    <Fluent:Button
                        MinWidth="100"
                        Command="{Binding Base.FlipDirectionCommand}"
                        CommandParameter="{Binding DataContext.SelectedLayer}"
                        Header="flip direction">
                        <Fluent:Button.LargeIcon>
                            <iconPacks:PackIconMaterial
                                Width="32"
                                Height="32"
                                Foreground="DarkGreen"
                                Kind="Rotate3d" />
                        </Fluent:Button.LargeIcon>
                    </Fluent:Button>
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
            <Fluent:RibbonTabItem
                MinWidth="150"
                Group="{Binding ElementName=layertab, Mode=OneWay}"
                Header="Splitting">
                <Fluent:RibbonGroupBox>
                    <Fluent:Button
                        MinWidth="100"
                        Command="{Binding Base.SplitRouteCommand}"
                        CommandParameter="{Binding DataContext.SelectedLayer}"
                        Header="split route">
                        <Fluent:Button.LargeIcon>
                            <iconPacks:PackIconMaterial
                                Width="32"
                                Height="32"
                                Foreground="DarkGreen"
                                Kind="ContentCut" />
                        </Fluent:Button.LargeIcon>
                    </Fluent:Button>
                    <Fluent:Button
                        MinWidth="100"
                        Command="{Binding Base.RemoveSplitRouteCommand}"
                        CommandParameter="{Binding DataContext.SelectedLayer}"
                        Header="remove split route">
                        <Fluent:Button.LargeIcon>
                            <iconPacks:PackIconMaterial
                                Width="32"
                                Height="32"
                                Foreground="DarkGreen"
                                Kind="CloseCircle" />
                        </Fluent:Button.LargeIcon>
                    </Fluent:Button>
                    <Fluent:Button
                        MinWidth="100"
                        Command="{Binding Base.SaveSplitRouteCommand}"
                        CommandParameter="{Binding DataContext.SelectedLayer}"
                        Header="save split route">
                        <Fluent:Button.LargeIcon>
                            <iconPacks:PackIconMaterial
                                Width="32"
                                Height="32"
                                Foreground="DarkGreen"
                                Kind="ContentSave" />
                        </Fluent:Button.LargeIcon>
                    </Fluent:Button>
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
        </Fluent:Ribbon>
    </Grid>
</UserControl>

**Comment by batzen** [comment]
Could try to reproduce this issue using the latest 5.0 preview/prerelease version?
If it's still broken there it would be nice to get a fully working repro attached as a zip file.

**Comment by MannusEtten** [comment]
i tried with the 5.0 version but then i get even more issues to build my project

**Comment by batzen** [comment]
What kind of issues?
One important thing is that the theme got moved one level up and is no longer `Office2013\Generic.xaml` but just `Generic.xaml` instead.

**Comment by batzen** [comment]
@MannusEtten Ping

**Comment by batzen** [comment]
@MannusEtten Ping

**Comment by batzen** [comment]
@MannusEtten Ping

**Comment by MannusEtten** [comment]
i tried today again, nothing changed, the contextual tab group titles are not shown

**Comment by batzen** [comment]
You should have added the reference to your OSS project from the start.
There is, of course, no need to provide a repro if your project is OSS.

I cloned your project but i am unable to build it because "GPXDataAnalyzer\GPX" is missing.
Is there any way you can add that project to your repo?

**Comment by MannusEtten** [comment]
the gpx-project is a clone of another OSS-project, i shall add it in a zip to my BikeTouringGIS-project, thanks already for your time and help!

**Comment by MannusEtten** [comment]
i added it to the project but clone the 1.1-branch because it is added to this branch

**Comment by batzen** [comment]
Just tried the 1.1 branch but there seem to be a few more projects with relative paths which are missing.
Could you attach a zip archive containing everything i need to build the project?
If that is not possible (i also saw some target files being referenced), it would be nice if you could provide a small repro.

**Comment by batzen** [comment]
I found a way to reproduce your issue.
That's a really strange one.
Will have a look.

**Comment by MannusEtten** [comment]
did you fix it in the end? if so, when can i expect a new version so i can release it with my app?
In the repo of my app there is now a zip-file with all sources if you still want to reproduce it.

**Comment by batzen** [comment]
@MannusEtten  Yes, this was fixed in Fluent.Ribbon.
