### ISSUE TITLE
Ribbon button labels are cut if system font size is increased

### ISSUE THREAD

**Issue by pjahr** [fluentribbon/Fluent.Ribbon#396]
If the default OS font size used in dialogs and windows is increased, some of the labels in the ribbons child controls are cut.

![image](https://cloud.githubusercontent.com/assets/3593785/22552452/4a513072-e959-11e6-9d12-b371c70ddbf4.png)

This is not related to DPI scaling (which is working fine). To reproduce, open 'Window Color and Appearance', click the message box and increase the font size. The problem seems to be the hard-coded heights in the templates of RibbonGroupBox and some of the button controls.

---
### Environment

- Fluent.Ribbon 4.0.3 (5.0.0)
- Windows 7 Pro SP1 x64
- .NET Framework 4.6.1

**Comment by batzen** [comment]
That's a thing I will, most probably, never fix. Please use a fixed font size in your app and stay with that.
