### ISSUE TITLE
Backstage Opening Animation

### ISSUE THREAD

**Issue by changbowen** [fluentribbon/Fluent.Ribbon#397]
Not a big issue. But if it is an easy fix...
The opening animation of the backstage has always been like this. Looks like the "left" part of the animation is missing. When opening, it starts from 50% and play to the end. When closing, it plays to 50% and skips to the end.
Don't know if I made myself clear...

---
### Environment

- Fluent.Ribbon reproducible with the latest showcase
- Windows 7
- .NET Framework 4.5

**Comment by batzen** [comment]
Can't reproduce this on my machine.
>  reproducible with the latest showcase

What do you mean by that? Which showcase version? Compiled from source? Downloaded from appveyor?

**Comment by changbowen** [comment]
Some visual aids :)
This is the backstage in Word 2016 (dont know if it is called that in Office) opening:
![office2016bkstgopen](https://cloud.githubusercontent.com/assets/15975872/22722689/defea42c-edf3-11e6-8180-64cb67e97c97.gif)

And this is the backstage opening in a Fluent window:
![fluentbkstgopen](https://cloud.githubusercontent.com/assets/15975872/22722753/31c78660-edf4-11e6-83ab-ea3e48d7f387.gif)

Dont know if this is by design, but it feels that the animation "starts from 50%"...
If you compare the above two gifs, in the Office animation the blue panel movement starts from the left edge. While in the 2nd gif, the red panel movement starts from a few miles west of the edge.
Same for the closing animation.

**Comment by batzen** [comment]
Ok, in slow motion it's visible.
Will have a look.

**Comment by batzen** [comment]
![fluentbackstage](https://cloud.githubusercontent.com/assets/1971030/22854437/ed24216c-f06e-11e6-9898-b047f821a7b3.gif)

@changbowen Close enough?

**Comment by changbowen** [comment]
This looks great! 👍

**Comment by changbowen** [comment]
one thought though, i see the margin animation value is hard coded. if the backstage gets wide, i think the animation will still look like the second gif.

**Comment by batzen** [comment]
I know. Binding these values would be better. Got it on my list. 
But the problem should only occur is the left panel in the backstage gets wider.
