### ISSUE TITLE
Default menu / menuitem appearance overridden by FluentRibbon

### ISSUE THREAD

**Issue by grafster** [fluentribbon/Fluent.Ribbon#400]
There seems to be something in the fluentribbon resources that is altering the appearance of Menus / MenuItems.

Without &lt;ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" /&gt; in App.xaml:-

![image](https://cloud.githubusercontent.com/assets/7203957/23031632/95bbfa68-f469-11e6-8471-1b1d46a83dae.png)

With &lt;ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" /&gt; in App.xaml:-

![image](https://cloud.githubusercontent.com/assets/7203957/23031702/d108e680-f469-11e6-8e53-ad06ae76c381.png)

---
### Environment

- Fluent.Ribbon 4.0.3
- Theme Office2013
- Windows 10
- .NET Framework 4.5

**Comment by batzen** [comment]
Will have a look next weekend.
