### ISSUE TITLE
Drop down list with scroll bar doesn't select correct item

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#402]
I thought it was fixed in v5, but installing the prerelease still gives the same behavior:

![fluent_ribbon](https://cloud.githubusercontent.com/assets/1246444/23695638/877ca638-03e0-11e7-9bdd-368e246ddf39.gif)

.NET fx 4.0
Fluent.Ribbon 5.0.0 (stable, from AppVeyor)

Will try to find the cause and update this ticket.

**Comment by GeertvanHorrik** [comment]
Even with `ClosePopupOnMouseDown` it picks the wrong item.

**Comment by GeertvanHorrik** [comment]
Basically the scrolling gets reset as soon as you focus the drop down content.

**Comment by GeertvanHorrik** [comment]
This seems to work in the demo app. Investigating why this isn't working in our component.

**Comment by GeertvanHorrik** [comment]
I can also reproduce strange scrolling behavior in the demo app. Note that I don't even click items here, just using the scroll buttons.

![fluent_ribbon_01](https://cloud.githubusercontent.com/assets/1246444/23699139/5d9ec6f8-03ee-11e7-851c-af9b3e615c6a.gif)

**Comment by GeertvanHorrik** [comment]
Found the cause. Whenever I use a `StackPanel` as ItemsPanelTemplate, this issue occurs. So this is reproducable in the app like this:

```
                    <Fluent:DropDownButton Header="Dropdown (auto close on click) g"
                                           ResizeMode="Both"
                                           Icon="pack://application:,,,/Fluent.Ribbon.Showcase;component/Icons/App.ico"
                                           LargeIcon="pack://application:,,,/Fluent.Ribbon.Showcase;component/Icons/App.ico"
                                           ClosePopupOnMouseDown="True"
                                           ClosePopupOnMouseDownDelay="250">
                        <Grid>
                            <ListBox ItemsSource="{Binding StringItems}">
                                <ItemsControl.ItemsPanel>
                                    <ItemsPanelTemplate>
                                        <StackPanel />
                                    </ItemsPanelTemplate>
                                </ItemsControl.ItemsPanel>

                                <ItemsControl.ItemTemplate>
                                    <DataTemplate>
                                        <MenuItem Header="{Binding}" Click="OnAutoCloseDropDownButtonMenuItemClick"/>
                                    </DataTemplate>
                                </ItemsControl.ItemTemplate>
                            </ListBox>
                        </Grid>
                    </Fluent:DropDownButton>
```

When I remove the custom ItemsPanelTemplate, it doesn't show this strange behavior.

**Comment by GeertvanHorrik** [comment]
For now I will close this issue since I can live without a custom ItemsPanelTemplate. Hopefully this ticket can be used as a reference for others bumping into this issue.

**Comment by batzen** [comment]
@GeertvanHorrik 
The scrolling is intentional because of `ClickMode="Hover"`.

The jumping selection is just the regular `ScrollViewer` in `ScrollViewer` problem.
Just set `ScrollViewer.CanContentScroll="False"` on your ListBox and everything is fine.
Scrolling by mouse still won't work that way.

I wonder why you even use a `ListBox` and don't rely on the `DropDownButton` already inheriting from `MenuBase`.

**Comment by GeertvanHorrik** [comment]
It's a control from an external lib which I am embedding into the ribbon. So in regular situations it would be perfect to have a ListBox inside the control.

I still find it strange that whenever I don't use an ItemsPanel, it works fine. Anyway, it's solved for now :)

And great work on v5, much appreciated!
