### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#404]
Hi

I just wanted to know if there is any built-in solution for a Help button like in Word 2013 or Windows Explorer.

Word 2013
![image](https://cloud.githubusercontent.com/assets/7498367/23792015/8f642ed8-0585-11e7-934a-0105c479d2e4.png)

Windows Explorer
![image](https://cloud.githubusercontent.com/assets/7498367/23792043/a942ab22-0585-11e7-8492-7cc3b9d57d91.png)

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __Office2013__ 
- Windows __8.1__
- .NET Framework __4.5__

**Comment by Alisaunder** [comment]
Hey Madcat try doing this It works for me just place the code in your Xaml for the window you wanrt to display the help on.
`<Fluent:RibbonWindow.WindowCommands>
        <Fluent:WindowCommands>
            <Fluent:WindowCommands.Items>
                <Fluent:Button Icon="pack://application:,,,/MHManager;Component/Resources/Images/help22x22.png" HorizontalAlignment="Left" Width="Auto" Height="Auto" Size="Small" VerticalAlignment="Center" Margin="0" ToolTip="MHManager Help (F1)" MinWidth="20" MinHeight="20" />
            </Fluent:WindowCommands.Items>
        </Fluent:WindowCommands>
    </Fluent:RibbonWindow.WindowCommands>`

**Comment by the-madcat** [comment]
Thank you for the quick answer. Works great ;)
