### ISSUE TITLE
InRibbonGallery when loaded, mouse wheel up or down cause crash. 

### ISSUE THREAD

**Issue by Yumeryu** [fluentribbon/Fluent.Ribbon#405]
I have a InRibbonGallery with a lot of data inside, when loaded, before clicking any up, down or expand button, using mouse wheel up or down cause crash, with error index out of range. 

---
### Environment

- Fluent.Ribbon __v5.0.0_dev0477_
- Theme __generic__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Some details would be nice.
Including a StackTrace, amount of data and property values on the InRibbonGallery.
The best would probably be a repro.

**Comment by Yumeryu** [comment]
I do apologize, a bit of quick trigger there. 

I actually did spend a bit more time on it. Switch off "Only My Code". And I found the issue. 

In file RibbonTabControl.cs

From Line 563:
                if (selectedIndex < visualItems.Count - 1)
                {
                    visualItems[selectedIndex].IsSelected = false;
                    selectedIndex++;
                    visualItems[selectedIndex].IsSelected = true;
                }

I believe that should be:
                if (selectedIndex >= 0 && selectedIndex < visualItems.Count - 1)
                {
                    visualItems[selectedIndex].IsSelected = false;
                    selectedIndex++;
                    visualItems[selectedIndex].IsSelected = true;
                }
