### ISSUE TITLE
Specific version for nuget references causes issues

### ISSUE THREAD

**Issue by Paley01** [fluentribbon/Fluent.Ribbon#412]
Using the latest version I get:

An exception of type 'System.IO.FileLoadException' occurred in Fluent.dll but was not handled in user code

Additional information: Could not load file or assembly 'ControlzEx, Version=2.1.4.13, Culture=neutral, PublicKeyToken=f08b075e934b7045' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by Yumeryu** [comment]
Update ControlzEx to the latest version in NuGet.

**Comment by batzen** [comment]
I made a mistake while added the reference to ControlzEx by leaving `SpecificVersion=true`.
So you have to exactly use ControlzEx Version 2.1.4.13 till i release a fixed version of Fluent.Ribbon.
Sorry for that.
