### ISSUE TITLE
TextBox, ComboBox, etc binding issues

### ISSUE THREAD

**Issue by User3290** [fluentribbon/Fluent.Ribbon#414]
After update from 3.6.1.236 to 5.0.0.8 a lot of code has been broken
Some samples that works perfect on 3.6.1.236 and not work on 5.0.0.8

In this sample binding to Text doesn't work
```
<fluent:TextBox SizeDefinition="Small"
                                            Width="40"
                                            Name="FontSizeTextBox"
                                            Text="{Binding Font.Size, Mode=TwoWay}">
                                <i:Interaction.Triggers>
                                    <i:EventTrigger EventName="TextChanged">
                                        <i:InvokeCommandAction Command="{Binding FontSizeCommand}"
                                                               CommandParameter="{Binding Text, ElementName=FontSizeTextBox, Converter={StaticResource StringToIntConverter}}" />
                                    </i:EventTrigger>
                                </i:Interaction.Triggers>
                            </fluent:TextBox>
```

In this sample binding to SelectedValue doesn't work
```
<fluent:ComboBox Name="FontFamilyCombobox"
                                             SizeDefinition="Small"
                                             Width="110"
                                             MaxDropDownHeight="500"
                                             Style="{StaticResource SystemFontCombobox}"
                                             SelectedValuePath="Source"
                                             SelectedValue="{Binding Font.Family, Mode=OneWay}">
                                <i:Interaction.Triggers>
                                    <i:EventTrigger EventName="SelectionChanged">
                                        <i:InvokeCommandAction Command="{Binding FontFamilyCommand}"
                                                               CommandParameter="{Binding ElementName=FontFamilyCombobox, Path=SelectedItem.Source}" />
                                    </i:EventTrigger>
                                </i:Interaction.Triggers>
                            </fluent:ComboBox>
```
---
### Environment

- Fluent.Ribbon v5.0.0.8
- Windows Server 2012R2
- .NET Framework 4.6.1

**Comment by batzen** [comment]
This works without problems here. So i can't reproduce your issue.
Any chance you could attach a small repro?

**Comment by User3290** [comment]
FontSizeCommand changes particularly Font.Size, and after that Text in TextBox is not being updated. The same behavior is in Combobox (FontFamilyCommand - Font.Family)

**Comment by User3290** [comment]
FontSizeCommand changes particularly Font.Size (FontFamilyCommand - Font.Family) and when we do this via ui - that's ok. But when we change Font.Size (Font.Family) from code it's not being reflected on ui.

**Comment by batzen** [comment]
Then please attach a full repro for your issue.

**Comment by User3290** [comment]
![2017-03-22_17-39-48](https://cloud.githubusercontent.com/assets/25772043/24203445/c87eed84-0f26-11e7-97dd-33f3443b2820.png)
First, when we change font size via textbox then changes are being transferred by command to target field.
Second, via increase and decrease buttons we change the same field, but after that textbox value is not being updated

**Comment by batzen** [comment]
Repro = small project containing all necessary code to reproduce your issue. 

According to what you describe the binding get's broken somehow. Without code i can't say where and why it breaks.

**Comment by batzen** [comment]
@User3290 ping

**Comment by User3290** [comment]
I will try to make a reproduction in the closest time .. Heavy load.. Wait please

**Comment by User3290** [comment]
Demo https://yadi.sk/d/nUTi4jY23HZuxm
In a nutshell, ChangeSizeCommand is being called two times during IncreaseSizeCommand execution

**Comment by batzen** [comment]
Will have a look at this as soon as i can. Which will, most probably, be next week.

**Comment by batzen** [comment]
It's correct that your `ChangeSizeCommand` is called twice.
The following happens:
1. `IncreaseSizeCommand` changes `Size` to 12
2. `TextBox.Text` is bound to `Size` so you get the `TextChanged` event
3. `TextChanged` triggers `ChangeSizeCommand`
4. `ChangeSizeCommand` gets the old value (10) of `TextBox.Text` and sets `Size` to 10
5. `TextChanged` triggers `ChangeSizeCommand`
6. `ChangeSizeCommand` gets the old value (10) of `TextBox.Text` and sets `Size` to 10
7. No `TextChanged` is triggered

Thats the current behavior and it behaves the same when using a regular `TextBox`.
I would have expected the same as you did:
When `TextChanged` is fired `TextBox.Text`, to which your `CommandParameter` is bound, the passed value should be 12 instead of 10.

Did you switch the .NET version while updating Fluent.Ribbon? Maybe it's a change which was made to .NET.
My time is very limited this weekend, but i will try to find out why the value passed to `CommandParameter` is not the current value of the `TextBox` next week.

**Comment by batzen** [comment]
It's correct that your `ChangeSizeCommand` is called twice.
The following happens:
1. `IncreaseSizeCommand` changes `Size` to 12
2. `TextBox.Text` is bound to `Size` so you get the `TextChanged` event
3. `TextChanged` triggers `ChangeSizeCommand`
4. `ChangeSizeCommand` gets the old value (10) of `TextBox.Text` and sets `Size` to 10
5. `TextChanged` triggers `ChangeSizeCommand`
6. `ChangeSizeCommand` gets the old value (10) of `TextBox.Text` and sets `Size` to 10
7. No `TextChanged` is triggered

Thats the current behavior and it behaves the same when using a regular `TextBox`.
I would have expected the same as you did:
When `TextChanged` is fired `TextBox.Text`, to which your `CommandParameter` is bound, the passed value should be 12 instead of 10.

Did you switch the .NET version while updating Fluent.Ribbon? Maybe it's a change which was made to .NET.
My time is very limited this weekend, but i will try to find out why the value passed to `CommandParameter` is not the current value of the `TextBox` next week.

**Comment by batzen** [comment]
I think i found out why this happens. The binding in the CommandParameter is updated too late. Thus invoking the command using an outdated value.
As this also happens when using a regular TextBox i don't consider this a bug in Fluent.Ribbon.
@User3290  Do you agree with that conclusion?

**Comment by User3290** [comment]
I think you don't understand me correctly.
You should check this small application on different versions of your Fluent nuget package.
Fluent 5.0.0.8 is currently installed in this application. Check and remember his behaviour. After that you should reinstalled Fluent to 3.6.1.236. And do the same. In conclusion you will be sure that the issue i described is depend on Fluent version.

We should not speak about version of .NET framework, logic of application and anything else.

**Comment by batzen** [comment]
As already said, this already happens when using a regular TextBox. The only component involved which may cause such an issue and which got updated, as far as i remember, is System.Windows.Interactivity. I will try to confirm that tomorrow as i only have my phone available right now.

**Comment by User3290** [comment]
> As already said, this already happens when using a regular TextBox.
We use only fluent:TextBox...

**Comment by batzen** [comment]
The issue is also present when using a regular TextBox. It happens with every TextBox, not just the Fluent.Ribbon one.

**Comment by User3290** [comment]
Please, check your changes made between these versions of Fluent... This very important for us to solve this problem and update fluent package in our solution.

**Comment by batzen** [comment]
I don't have to check any change as it's not caused by any code change.
It's caused by System.Windows.Interactivity which is from Microsoft.

**Comment by punker76** [comment]
@User3290 I think also this is in this scenario a problem of the Binding to the Text of the TextBox itself. I tried a little bit with your sample and find a solution. Just bind to the TextBox itself...

```xaml
<fluent:TextBox SizeDefinition="Small"
                Width="40"
                Name="FontSizeTextBox"
                Text="{Binding Size, Mode=TwoWay}">
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="TextChanged">
            <i:InvokeCommandAction Command="{Binding ChangeSizeCommand}"
                                    CommandParameter="{Binding ElementName=FontSizeTextBox}" />
        </i:EventTrigger>
    </i:Interaction.Triggers>
</fluent:TextBox>
```
```csharp
public ICommand ChangeSizeCommand { get; private set; }

private void ChangeSize(object param)
{
  var tb = (TextBox)param;
  Size = (int)Convert.ToInt32(tb.Text);
}
```
![fluent_textbox](https://cloud.githubusercontent.com/assets/658431/25954399/79c8f86c-3666-11e7-9623-196b0d421a19.gif)

**Comment by User3290** [comment]
@punker76, we use MVVM.

> I don't have to check any change as it's not caused by any code change.
It's caused by System.Windows.Interactivity which is from Microsoft.

Version of System.Windows.Interactivity is not being changed in our case. Why do you reference to textbox features, if we have different behaviour in command calling?

In version 5.0.1.10 ChangeSize method is being called two times due IncreaseSizeCommand execution, although in version 3.6.1.236 only once.

**Comment by punker76** [comment]
@User3290 fine, my solution is still MVVM...

**Comment by User3290** [comment]
Moreover, we have issues not only with textbox after update but with combobox, described in first post.

@punker76 , param as ui known element? This is not mvvm

**Comment by punker76** [comment]
@User3290 the param can be anything and it's still MVVM, why should this be related to MVVM?

**Comment by User3290** [comment]
@punker76 we can't know about view elements in view model. Generally we don't speak about MVVM :)

**Comment by batzen** [comment]
You did not update the interactivity dll yourself, but fluent.ribbon depends on it and ships it. That version was updated. So i updated it, not you. But as it belongs to Microsoft Blend and i got no right to modify it you will have to raise issues belonging to that dll at Microsoft.

**Comment by batzen** [comment]
As you are using parts from that lib in your combobox too i would guess that it's the same issue.

**Comment by User3290** [comment]
We use "Expression.Interaction" nuget package 3.0.40218 that provide System.Windows.Interactivity. Do you use anything else?

How can be previous behaviour of Fluent achieved? That's very bad, if we don't have compatibility of Fluent markup between different versions...

**Comment by batzen** [comment]
I modified your project and removed any reference to Fluent.Ribbon and the issue is still there.
Please have a look at the project and tell me if you still think the issue is caused by Fluent.Ribbon.
3.0.40218 is the exact same version of "System.Windows.Interactivity.dll" which is used by Fluent.Ribbon.

[WpfApplication2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/993717/WpfApplication2.zip)

**Comment by User3290** [comment]
Now, i agree with you. But the question of such strange behaviour is still remain opened. What version of "Expression.Interaction" has been used in Fluent 3.6.1.236? In conclusion we come to mind that the problem is in "Expression.Interaction", isn't it?

**Comment by batzen** [comment]
Could you attach your copy of System.Windows.Interactivity to this issue?
Maybe we got the same version but different content for that dll, in that case i would change the version used in fluent.ribbon.

**Comment by User3290** [comment]
https://yadi.sk/d/-xLEBH_R3J6WoL

Based on version history of nuget package only one version is available...

**Comment by batzen** [comment]
If i use your sample application and just replace the dll with the version you just provided the issue remains.
Could you send me a repro where everything works as you expect it to work?

**Comment by User3290** [comment]
https://yadi.sk/d/Sn7NYP-93J6ZNa

**Comment by batzen** [comment]
Ok, now i found out why the behavior changed.
In version 3.6 the TextBox in Fluent.Ribbon inherited from RibbonControl and contained a TextBox.
Somewhere between that version and version 5.0 the inheritance changed from RibbonControl to TextBox, thus no longer containing a separate TextBox.
This change then reveals the bug in System.Windows.Interactivity.

You can use the following code, which is a fixed/modified version of InovkeCommandAction from System.Windows.Interactivity:
```
public sealed class InvokeCommandActionEx : TriggerAction<DependencyObject>
{
    public static readonly DependencyProperty CommandProperty = DependencyProperty.Register("Command", typeof(ICommand), typeof(InvokeCommandActionEx), (PropertyMetadata)null);
    public static readonly DependencyProperty CommandParameterProperty = DependencyProperty.Register("CommandParameter", typeof(object), typeof(InvokeCommandActionEx), (PropertyMetadata)null);
    private string commandName;

    public string CommandName
    {
        get
        {
            this.ReadPreamble();
            return this.commandName;
        }
        set
        {
            if (!(this.CommandName != value))
                return;
            this.WritePreamble();
            this.commandName = value;
            this.WritePostscript();
        }
    }

    public ICommand Command
    {
        get
        {
            return (ICommand)this.GetValue(InvokeCommandAction.CommandProperty);
        }
        set
        {
            this.SetValue(InvokeCommandAction.CommandProperty, (object)value);
        }
    }

    public object CommandParameter
    {
        get
        {
            return this.GetValue(InvokeCommandAction.CommandParameterProperty);
        }
        set
        {
            this.SetValue(InvokeCommandAction.CommandParameterProperty, value);
        }
    }

    protected override void Invoke(object parameter)
    {
        if (this.AssociatedObject == null)
            return;
        ICommand command = this.ResolveCommand();

        if (BindingOperations.IsDataBound(this.AssociatedObject, InvokeCommandAction.CommandParameterProperty))
        {
            BindingOperations.GetBindingExpression(this.AssociatedObject, InvokeCommandAction.CommandParameterProperty).UpdateTarget();
        }

        if (command == null || !command.CanExecute(this.CommandParameter))
            return;
        command.Execute(this.CommandParameter);
    }

    private ICommand ResolveCommand()
    {
        ICommand command = (ICommand)null;
        if (this.Command != null)
            command = this.Command;
        else if (this.AssociatedObject != null)
        {
            foreach (PropertyInfo property in this.AssociatedObject.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public))
            {
                if (typeof(ICommand).IsAssignableFrom(property.PropertyType) && string.Equals(property.Name, this.CommandName, StringComparison.Ordinal))
                    command = (ICommand)property.GetValue((object)this.AssociatedObject, (object[])null);
            }
        }
        return command;
    }
}
```

**Comment by User3290** [comment]
Big thanks for your help. I hope everything will work fine. Now i'm on 2 weeks holidays. After them i can check your fix. We will be in touch

**Comment by batzen** [comment]
Glad i could help. Enjoy your holidays.

**Comment by User3290** [comment]
Your solution works perfect! Thanks again! I hope this topic will be useful for somebody else...
By the way, i have recently opened an issue with ColorGallery https://github.com/fluentribbon/Fluent.Ribbon/issues/413. With such fix we have predictable behaviour even in 5.0.1.10 version.

**Comment by User3290** [comment]
We have one more issue after using this solution

```
<i:Interaction.Triggers>
                                <i:EventTrigger EventName="TextChanged">
                                    <tools:InvokeCommandActionEx Command="{Binding ChangeSizeCommand}"
                                                           CommandParameter="{Binding Text, ElementName=FontSizeTextBox, Converter={StaticResource StringToIntConverter}}" />
                                </i:EventTrigger>
                            </i:Interaction.Triggers>
```
ChangeSizeCommand is not fire anymore, even though TextChanged event fires...

**Comment by User3290** [comment]
> public ICommand Command
    {
        get
        {
            return (ICommand)this.GetValue(InvokeCommandAction.CommandProperty);
        }
        set
        {
            this.SetValue(InvokeCommandAction.CommandProperty, (object)value);
        }
    }

    

> public object CommandParameter
>     {
>         get
>         {
>             return this.GetValue(InvokeCommandAction.CommandParameterProperty);
>         }
>         set
>         {
>             this.SetValue(InvokeCommandAction.CommandParameterProperty, value);
>         }
>     }

"InvokeCommandAction." should be removed

**Comment by batzen** [comment]
Yeah, sorry. That code was just a quick draft. Forget to replace every occurrence of "InvokeCommandAction" by "InvokeCommandActionEx".
It's working now?

**Comment by User3290** [comment]
One more fix is change

```
BindingOperations.GetBindingExpression(AssociatedObject, InvokeCommandAction.CommandParameterProperty)?
                .UpdateTarget();
```

to
```
BindingOperations.GetBindingExpression(this, CommandParameterProperty)?
                .UpdateTarget();
```

In a nutshell, the finally working solution is

```
public sealed class InvokeCommandActionEx : TriggerAction<DependencyObject>
    {
        #region Command

        public static readonly DependencyProperty CommandProperty = DependencyProperty.Register("Command",
            typeof(ICommand), typeof(InvokeCommandActionEx), null);

        public ICommand Command
        {
            get { return (ICommand)GetValue(CommandProperty); }
            set { SetValue(CommandProperty, value); }
        }

        #endregion

        #region CommandParameter

        public static readonly DependencyProperty CommandParameterProperty =
            DependencyProperty.Register("CommandParameter", typeof(object), typeof(InvokeCommandActionEx), null);

        public object CommandParameter
        {
            get { return GetValue(CommandParameterProperty); }
            set { SetValue(CommandParameterProperty, value); }
        }

        #endregion

        #region CommandName

        private string _commandName;

        public string CommandName
        {
            get
            {
                ReadPreamble();
                return _commandName;
            }
            set
            {
                if (CommandName == value)
                    return;
                WritePreamble();
                _commandName = value;
                WritePostscript();
            }
        }

        #endregion

        protected override void Invoke(object parameter)
        {
            if (AssociatedObject == null)
                return;
            var command = ResolveCommand();

            BindingOperations.GetBindingExpression(this, CommandParameterProperty)?
                .UpdateTarget();

            if (command == null || !command.CanExecute(CommandParameter))
                return;
            command.Execute(CommandParameter);
        }

        private ICommand ResolveCommand()
        {
            ICommand command = null;
            if (Command != null)
                command = Command;
            else if (AssociatedObject != null)
            {
                foreach (
                    var property in
                        AssociatedObject.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public))
                {
                    if (typeof (ICommand).IsAssignableFrom(property.PropertyType) &&
                        string.Equals(property.Name, CommandName, StringComparison.Ordinal))
                        command = (ICommand) property.GetValue(AssociatedObject, null);
                }
            }
            return command;
        }
    }
```
