### ISSUE TITLE
Xamarin Form support?

### ISSUE THREAD

**Issue by Suriman** [fluentribbon/Fluent.Ribbon#416]
Would it be possible to port this control to Xamarin Forms?

**Comment by batzen** [comment]
Hi, 
i never used Xamarin Forms but i guess it's possible somehow.
As i don't plan on using Xamarin Forms i won't start any porting work.

If you are interested in porting this library we could discuss details before you start working.

**Comment by pekspro** [comment]
Adding support for Xamarin Forms would be like adding support for UWP – but a lot harder. I really doubt that would be a good idea. I think it will be better to create something from scratch instead. Personally, I’m not really interested to use Fluent Ribbon in an Android device for instance. Adding support for console applications would be easier :)

**Comment by Suriman** [comment]
The idea would be to use the Ribbon control in Xamarin Forms for Mac applications and possibly for Linux, neither for Android and iOS.

**Comment by batzen** [comment]
As already said, i never used Xamarin Forms and do not plan to use it.
If anyone is interested in porting feel free to contact me.
