### ISSUE TITLE
Keytips for Splitbuttons

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#417]
Hi

Again I want to use `Keytips` but I encountered a problem with `SplitButtons`:

As it is not a `DropDownButton` it has a functionality if I press the upper half of the button and a menu that drops down if I press the lower half. But if I assign a `KeyTip` for the `SplitButton` it only opens the drop down menu but does not fire the command I bound to it.

Besides I cannot access the `MenuItems` I added to the `SplitButton` which also have a `KeyTip`.

PS: The Fluent Ribbon is by far the best Ribbon control I know with the quickes support ;)

---
### Environment

- Fluent.Ribbon __v5.0.1.10__
- Windows __8.1__
- .NET Framework __4.5__

**Comment by batzen** [comment]
Office behaves the same regarding just opening the dropdown. Any suggestion on how to enable click and opening the dropdown?

Menuitems not showing keytips after opening the dropdown is a bug and i already fixed it on my machine.

**Comment by the-madcat** [comment]
I am not sure if my solution could be called clean:

Maybe if the programmer gave a `KeyTip` to the `SplitButton` and its `MenuItems` the `DropDown` could appear when **Alt** is pressed in order to show all available `KeyTips`. In this case the user could choose if he wants to press the `KeyTip` for the `Button` or a `KeyTip` for a `MenuItem`.

**Comment by batzen** [comment]
That sounds like a bit of overhead for existing projects. What should a user expect there?
After some thinking i guess the best solution would be to autogenerate the keytips for the inner parts.
Still have to try if it's possible to implement this given the current nature of the keytip implementation.

Example:
SpliButton.Key = "A"
User presses "A" keytip to reach the SplitButton and gets the choice of "1" (Button-Action) or "2" (Open-DropDown).

**Comment by the-madcat** [comment]
Hi

Sorry for the late answer. Your solution sounds very usable. So it will look like this?

![image](https://cloud.githubusercontent.com/assets/7498367/24347575/066c389e-12d9-11e7-8a06-d42119e3777f.png)

**Comment by batzen** [comment]
That's what i had in mind.

**Comment by the-madcat** [comment]
Sry, but no ... I am quite busy right no so I have no time to get familiar with the code (that is why I am so happy that this project has such a great support ;)) this is just a modified screenshot.
