### ISSUE TITLE
Scroll button style

### ISSUE THREAD

**Issue by rpirozhkov** [fluentribbon/Fluent.Ribbon#418]
Hello. Help me pls, where i can find style of this button?
![screenshot_23](https://cloud.githubusercontent.com/assets/24272164/24555206/e8bf2596-1638-11e7-9af7-3736e6bc4e29.png)

**Comment by batzen** [comment]
It's currently called "ScrollButtonStyle".
You can find the content of both buttons (left and right) in `RibbonTabControl.xaml`.

**Comment by rpirozhkov** [comment]
Thank u very much!

**Comment by batzen** [comment]
You are welcome. ;-)
