### ISSUE TITLE
5.0.1.10 Showcase QuickAccessMenuItem doesn't work

### ISSUE THREAD

**Issue by llinyu** [fluentribbon/Fluent.Ribbon#421]
Run Fluent.Ribbon.Showcase, and click "Pink", it doesn't work.

### Environment
- Fluent.Ribbon v5.0.1.10
- Windows 10.0 x64 Enterprise
- .NET Framework 4.6

Fluent.Ribbon 5.0.1.10
Windows 10.0 x64 Enterprise
.net 

### Environment
4.0.3.0 Fluent.Ribbon.Showcase works fine in up environment.

Thank you!

**Comment by batzen** [comment]
Works in 6.0.
