### ISSUE TITLE
Set ribbon background color

### ISSUE THREAD

**Issue by DRAirey1** [fluentribbon/Fluent.Ribbon#423]
I simply want to change the background color of the ribbon to match the Windows 10 theme.  I've pulled apart the XAML and I'm still unable to figure out how this is done.  It should be as simple as

		<Fluent:Ribbon Background="Red">
                                  ...
                </Fluent:Ribbon>

---
- Fluent.Ribbon __v5.0.1.10__
- Generic.xaml
- Windows 10
- .NET Framework 4.5

**Comment by batzen** [comment]
You currently have to overwrite the resource `RibbonBackgoundBrush`.

Please note that this resource will be renamed to `Fluent.Ribbon.Brushes.Ribbon.Background` in version 6.0 and that there will be no need to overwrite it starting from version 6.0 as you can just use the code you already tried to use.

**Comment by Alisaunder** [comment]
I'm looking for a way to change the color of the ribbon part behind the tabs like in Office 365. The method you mention here changes the entire ribbon selected tab. It would also be nice if there were a way to add a graphic like they do in Office 365.

**Comment by batzen** [comment]
Could you create a new issue for this so i can track this enhancement appropriately?

**Comment by RandomEngy** [comment]
I tried all 3 approaches mentioned and nothing worked. Still stays white background, black text.

**Comment by batzen** [comment]
@RandomEngy you can see how it's done in https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon.Showcase/RibbonWindowColorized.xaml

**Comment by RandomEngy** [comment]
Interesting, though changing the foreground color in the showcase app doesn't work. The button text always stays black.

**Comment by batzen** [comment]
Could you create a new issue for that then?
