### ISSUE TITLE
Can not place <Grid> in <Fluent:RibbonWindow> with <Fluent:Ribbon>

### ISSUE THREAD

**Issue by TheColonel2688** [fluentribbon/Fluent.Ribbon#425]
I'm trying to follow the [basic setup tutorial](http://fluentribbon.github.io/documentation/basic-setup), but I'm receiving an error "The property "Content" can only be set once."

```
<Fluent:RibbonWindow x:Name="winMain" x:Class="Icon_Labeler.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Fluent="urn:fluent-ribbon"
        Title="Ben's Icon Labeler" Height="600" Width="800" Drop="WinMain_Drop" DragEnter="WinMain_DragEnter" AllowDrop="True">

    <Fluent:Ribbon>
        <!--Backstage-->
        <Fluent:Ribbon.Menu>
            <Fluent:Backstage>
            </Fluent:Backstage>
        </Fluent:Ribbon.Menu>

        <!--Tabs-->
        <Fluent:RibbonTabItem Header="Home">
            <Fluent:RibbonGroupBox Header="Group">
                <Fluent:Button Header="Green"
                            Icon="Images\Green.png"
                            LargeIcon="Images\GreenLarge.png" />
            </Fluent:RibbonGroupBox>
        </Fluent:RibbonTabItem>
    </Fluent:Ribbon>
    
    <Grid></Grid>
   
</Fluent:RibbonWindow>
```

---
### Environment

- Fluent.Ribbon v5.0.1.10
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Because you are trying exactly that, setting the content twice.
Your first content is `<Fluent:Ribbon>` and the second is `<Grid>` you have to do something like:
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <Fluent:Ribbon Grid.Row="0">
        ....
    </Fluent:Ribbon>
    <Grid>
       <TextBlock>My first window containing a Ribbon and something else.</TextBlock>
    </Grid>
</Grid>
```

**Comment by batzen** [comment]
Will change the tutorial to show the complete assembled code for a first window to prevent such starting issues in the future.

**Comment by TheColonel2688** [comment]
I figured out that there were two content items but I'm brand new to WPF, so I didn't know how to resolve it. Thank you.

**Comment by batzen** [comment]
You're welcome.
Do you have any further questions regarding Fluent or WPF?

**Comment by TheColonel2688** [comment]
The only one I can think of is; Can the list of controls be added to the VS toolbox list? This was possible for custom controls with WinForms.

**Comment by batzen** [comment]
@TheColonel2688 I don't use the designer and thus not the toolbox, but as far as i know you have to add those by yourself.
A quick search returned this https://msdn.microsoft.com/fr-fr/library/ff462023(v=vs.95).aspx which is for silverlight but the dialog also has a tab labeled "WPF components" which should be the one you have to use.
