### ISSUE TITLE
Ability to hide minimize and/or maximize window buttons?

### ISSUE THREAD

**Issue by appakz** [fluentribbon/Fluent.Ribbon#426]
I apologize if this has been asked and answered before; I searched the issues and didn't find anything.

Is it possible to hide the minimize and/or maximize buttons for the ``window`` (not the ribbon) for a window that's inheriting `RibbonWindow` ?

**Comment by batzen** [comment]
You can use `ResizeMode="NoResize"`.
That property is already provided by the `Window` base class of `RibbonWindow`.

**Comment by appakz** [comment]
Yes I know you can do that, but I still want the window to be resizable. Ideally I want to just hide the minimize button but still still allow for maximizing and manually resizing.

**Comment by batzen** [comment]
Ah. Got your question wrong.

**Comment by batzen** [comment]
There is no built in way for doing so.
One way to get this working would be to subclass `WindowCommands` and provide your own instance of that to the `RibbonWindow`. In said subclass you could then use code `OnApplyTemplate` to hide the minimize button (part is named `PART_Min`).
The user can still use the contextmenu on the titlebar and other methods to get the window minimized.

**Comment by appakz** [comment]
Ok that's the sort of info I was looking for. I'll try that out.

Thanks!

**Comment by Alisaunder** [comment]
you could instantiate the window `like
` Window1 myWindow = new Window1();
myWindow.ShowDialog();
`
this will get rid of the size buttons but still allow for you to drag the edges. but it also makes it the top form and you cannot click other forms unless you close it first.
