### ISSUE TITLE
Values from DependencyProperties with FrameworkPropertyMetadataOptions.Inherits are not properly inherited from Ribbon to Menu, StartScreen and some other children

### ISSUE THREAD

**Issue by incureforce** [fluentribbon/Fluent.Ribbon#428]
The Backstage Control does not detect a Language change in the parent Window (inheritance problem?)

Workaround:
```csharp
<f:Backstage Language="{Binding ElementName=wndName, Path=Language}" />
```

---
### Environment

- Fluent.Ribbon v5.0.1.10
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
There is no Language property on Backstage. Localization, of strings specific to this library, is done through bindings to RibbonLocalization.

There were issues regarding DataContext, and thus Bindings, in the Backstage and some other areas which are already fixed in version 6.0 which is currently in development.

**Comment by incureforce** [comment]
The Language property is inherited from Backstage > RibbonControl > Control > FrameworkElement, but somehow it isn't passed properly through the DependencyObject logical tree. My best guess is that either it is set directly in between or the inheritance chain from the DependencyProperty is disjointed. Snoop shows that on the Adorner Layer its value state is default and not inherited.

**Comment by incureforce** [comment]
Maybe it is already fixed in v6, i'll try it if available, but if not it should been noted and maybe fixed :D

**Comment by batzen** [comment]
Ah, wasn't aware of the `Language` property as i've never written localized applications and localization in Fluent.Ribbon is making use of that property.

Just tested if setting `Language` on TestWindow (in the showcase application of v6.0) gets inherited by the `Backstage` and it does so.

**Comment by batzen** [comment]
Oh, but it only gets the initial value. Changes are not inherited. Will have a look.

**Comment by batzen** [comment]
This is related to #415 but requires a different fix. That fix will make the fix done for #415 obsolete.

**Comment by batzen** [comment]
@incureforce Thanks for reporting this as this forced me to rethink my solution for #415 and finally fix the issue in a future proof way instead of fixing it the lazy way. I still have to ask someone at Microsoft why this happens, as it should not have happened initially...

**Comment by incureforce** [comment]
Thank you, for working on the weekend to fix this. 👍

**Comment by batzen** [comment]
Well, working on the weekend is often the only time i can work on this project. ;-)

**Comment by batzen** [comment]
Should be fixed. 
Could you give it a try and report back if it's really fixed?
I wrote automated tests for this, but you never know...

**Comment by incureforce** [comment]
Yes it works as it should. Thank you very much.

**Comment by batzen** [comment]
You are welcome. :-)
