### ISSUE TITLE
Ribbon does not work in VS 2017

### ISSUE THREAD

**Issue by Divemaster11** [fluentribbon/Fluent.Ribbon#429]
Environment - Windows 10 - 64 bit, VS - 2017 Professional.

Installed Fluent.Ribbon 5.0.1.10 and ControlzEx 2.2.0.4. 
Created project from Getting Started code example. Designer frame and ribbon appear. 
When try to build get the following error.
CS0263  C# Partial declarations of 'MainWindow' must not specify different base classes

**Comment by Alisaunder** [comment]
Actually it works fine I use it all the time. Show some code please.

**Comment by batzen** [comment]
Change "MainWindow : Window" to just "MainWindow" in your "MainWindow.xaml.cs" file.

**Comment by Divemaster11** [comment]
Thx. That fixed it.

 

Richard Carroll
