### ISSUE TITLE
Per-Monitor DPI-Aware

### ISSUE THREAD

**Issue by AlisterSG** [fluentribbon/Fluent.Ribbon#432]
Fluent  Window Ribbon could be Per-Monitor DPI-Aware?

[Per-Monitod DPI-Aware](https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410.aspx)

**Comment by batzen** [comment]
You can activate per monitor DPI for Fluent.Ribbon by using

```
<runtime>
    <AppContextSwitchOverrides value = "Switch.System.Windows.DoNotScaleForDpiChanges=false"/>
  </runtime>
```

But that causes some issues with controls on/in the window chrome like Minimize/Maximize/Close etc..
I will investigate those issues and fix them.

**Comment by batzen** [comment]
This depends on https://github.com/ControlzEx/ControlzEx/issues/24

**Comment by batzen** [comment]
Tested everything i implemented for this and it seems to be working fine.
You have to use the .NET 4.6.2 version currently to get this really working.

**Comment by batzen** [comment]
Location of SystemMenu on titlebar is broken...

**Comment by batzen** [comment]
After some more testing i consider this to be done.
