### ISSUE TITLE
ToggleButton not working correctly when placed in collapsed GroupBox

### ISSUE THREAD

**Issue by svendu** [fluentribbon/Fluent.Ribbon#433]
Assume you have 2 GroupBoxes with a bunch of ToggleButtons. All Buttons are in the same "toggle"-group.
Selecting one of the buttons will uncheck all the others.

If you set the state of one GroupBox to "collapsed" this does not work anymore.
You can toggle two buttons although all button are still in the same "toggle"-group

---
### Environment

- Fluent.Ribbon __5.0.1.10__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __10 Professional__
- .NET Framework __4.6__

Attached a sample project to demonstrate the issue
[RibbonGroupBoxIssue.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/992739/RibbonGroupBoxIssue.zip)

**Comment by batzen** [comment]
This is because, i can't remember why, i bound groups to a visual root scope.
This does not work in this situation.
I will remove this bounding.
