### ISSUE TITLE
RibbonGroupBox VisibilityProperty wrong Metadata

### ISSUE THREAD

**Issue by Schuttrim** [fluentribbon/Fluent.Ribbon#434]
Hey its a really short one. 

inside Fluent.Ribbon/RibbonGroupBox on line 600:
VisibilityProperty.AddOwner(typeof(RibbonGroupBox), new PropertyMetadata(OnVisibilityChanged));

as this overrides the Metadata of the VisibilityProperty, this can cause problems, when the PropertyMetadata is also overridden on visual Childs, like Grids with **FrameworkPropertyMetadata** before.

"Metadata override and base metadata must be of the same type or derived type."

Thats why you should change such things to: 
VisibilityProperty.AddOwner(typeof(RibbonGroupBox), new **FrameworkPropertyMetadata(OnVisibilityChanged)**);

I have created a small sample, have a look on CustomControl1.
[WpfApplication1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/992963/WpfApplication1.zip)

I suggest you to also change this on similar cases

### Environment

    <package id="Fluent.Ribbon" version="5.0.1.10" targetFramework="net461" />
    <package id="ControlzEx" version="2.2.0.4" targetFramework="net461" />

**Comment by batzen** [comment]
You are doing this
```
UIElement.VisibilityProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(Visibility.Hidden, OnVisibilityChanged));
```

If i remove that line there is no exception in your sample application.

I don't get why you think this is an issue beloging to Fluent.Ribbon.

**Comment by batzen** [comment]
PropertyMetadata is the most basic type i can use.
If i start to use something different from that everyone is force to use at least that...

**Comment by Schuttrim** [comment]
You are right, the issue is, that it is not possible to override a subtype with a basetype.

Sorry for wasting your time. Sadly I also need to override those metadatas, and as its static constructor is executed before the one of RibbonGroupBox, this causes an exception like in the example. I wasn't thinking about that "using the most basic type" as you said was the best thing to do. 

Again, sorry for wasting your time. You are doing a great job with this library.

You can close this issue.

**Comment by batzen** [comment]
I totally get your problem, but changing the type would just break the project of someone else...

How about accessing something from RibbonGroupBox statically before your own class is accessed? That should solve your issue.

Asking questions/raising issues here does not waste my time and there is no need to feel sorry.

**Comment by Schuttrim** [comment]
> How about accessing something from RibbonGroupBox statically before your own class is accessed? That should solve your issue.

Guess I'm gonna do this. Thanks.
