### ISSUE TITLE
Add ability to change the Window Title Background the Ribbon Bar is on in order to match the Office 365 Style.

### ISSUE THREAD

**Issue by Alisaunder** [fluentribbon/Fluent.Ribbon#435]
**Would like to enhance Fluent Ribbon to be able to do the following**

* Change the Background color of the Titlebar
* Change the Foreground color of the Titlebar
* Change the Background color of the window control buttons
* Change the Foreground color of the window control buttons
* Change the MouseOver color of the window control buttons
* Change the Background color of the non-selected Ribbon tabs.
* Change the Background color of the Ribbon tabs area that is blank with no tabs yet. AKA the Tab Control 
   Background in order to match the color of the Titlebar Background

---
### This is an Enhancement request

**Comment by batzen** [comment]
Could you have a look if the things i have done fit your needs?

**Comment by batzen** [comment]
@Alisaunder @frostieDE @gogeonhyeok ping

**Comment by batzen** [comment]
@Alisaunder ping

**Comment by batzen** [comment]
I consider this done.
