### ISSUE TITLE
RibbonTabItem align to stay always on the Right

### ISSUE THREAD

**Issue by esatp** [fluentribbon/Fluent.Ribbon#436]
**Can we set RibbonTabItem to stay always on the right of ribbon**

---
### Environment

- Fluent.Ribbon __v5.0.1__
- Theme __Generic__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.0__

**Comment by batzen** [comment]
The is no way to do this out of the box by changing one property, if that's what you mean.
You can do the following:
1. Search the visual tree of the ribbon for a control named "TabsGrid"
2. From there search for the first control of type "RibbonScrollViewer"
3. Change it's horizontal alignment to "Right"

**Comment by esatp** [comment]
Thank you for you fast response @batzen .

I tried your proposed solution but now we have a problem connecting these Tabs with Ribbon view

1. Can I get event when RibbonTab is clicked?
2. How to show Content in Ribbon when these Tabs are clicked? 

Thanks a lot

**Comment by batzen** [comment]
Oh, totally missed your answer. Will answer it tomorrow.

**Comment by batzen** [comment]
1. The `Ribbon` has an event `SelectedTabChanged` which you can subscribe to.
2. The `Ribbon` is organized in Tabs so you don't have to do anything special to display content in it other than add groups to tabs and controls to groups. The showcase application contains lots of samples for that.

**Comment by batzen** [comment]
Does that answer your question @esatp?

**Comment by batzen** [comment]
@esatp ping

**Comment by batzen** [comment]
@esatp ping

**Comment by esatp** [comment]
Hi @batzen, sorry I wasn't around.
In my specific case I needed to align right 2 tabs. But doing with your solution these two tabs were left out from Main Ribbon Tabs array so SelectedTabChanged) actually never called and even Could not show any content when these tabs are clicked. 

Currently I was testing with an app and it is not urgent for me, but I think Fluent Ribbon should have this ability to align some tabs.

However thank you very much for your help.

Best

**Comment by batzen** [comment]
So you just want to right align some tabs and created your own containers for these?

**Comment by esatp** [comment]
Right align and use these tabs as the others

**Comment by batzen** [comment]
Arranging a few items left and a few items right will require a decent amount of work.
May i ask for the use case for this?

**Comment by batzen** [comment]
@esatp ping

**Comment by batzen** [comment]
@esatp ping

**Comment by esatp** [comment]
Hi @batzen,

The use was as I explained before just to add two tabs on the right but the project is stopped now and didn’t have time to research more. Thank you in advance for taking care. Keep up the good work
