### ISSUE TITLE
"Could not load ControlzEx"

### ISSUE THREAD

**Issue by JVimes** [fluentribbon/Fluent.Ribbon#437]
If I add the Fluent.Ribbon NuGet package to a fresh WPF App, then following follow the [basic setup](http://fluentribbon.github.io/documentation/basic-setup) instructions, I get a build warning:

> Found conflicts between different versions of the same dependent assembly that could not be resolved.

And a runtime crash:

> FileLoadException: Could not load file or assembly 'ControlzEx, Version=2.1.4.13, Culture=neutral, PublicKeyToken=f08b075e934b7045' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I was able to work around the problem by updating the ControlzEx package from the default, v2.1.1.3, to the latest allowed, v2.2.0.4.

 ## More info

Detailed build output shows:

    There was a conflict between "ControlzEx, Version=2.1.1.3, Culture=neutral, PublicKeyToken=f08b075e934b7045" and "ControlzEx, Version=2.1.4.13, Culture=neutral, PublicKeyToken=f08b075e934b7045".
        "ControlzEx, Version=2.1.1.3, Culture=neutral, PublicKeyToken=f08b075e934b7045" was chosen because it was primary and "ControlzEx, Version=2.1.4.13, Culture=neutral, PublicKeyToken=f08b075e934b7045" was not.
        References which depend on "ControlzEx, Version=2.1.1.3, Culture=neutral, PublicKeyToken=f08b075e934b7045" [C:\Users\username\Documents\Visual Studio 2017\Projects\WpfApp2\packages\ControlzEx.2.1.1.3\lib\net45\ControlzEx.dll].
            C:\Users\username\Documents\Visual Studio 2017\Projects\WpfApp2\packages\ControlzEx.2.1.1.3\lib\net45\ControlzEx.dll
              Project file item includes which caused reference "C:\Users\username\Documents\Visual Studio 2017\Projects\WpfApp2\packages\ControlzEx.2.1.1.3\lib\net45\ControlzEx.dll".
                ControlzEx, Version=2.1.1.3, Culture=neutral, PublicKeyToken=f08b075e934b7045, processorArchitecture=MSIL
        References which depend on "ControlzEx, Version=2.1.4.13, Culture=neutral, PublicKeyToken=f08b075e934b7045" [].
            C:\Users\username\Documents\Visual Studio 2017\Projects\WpfApp2\packages\Fluent.Ribbon.5.0.1.10\lib\net45\Fluent.dll
              Project file item includes which caused reference "C:\Users\username\Documents\Visual Studio 2017\Projects\WpfApp2\packages\Fluent.Ribbon.5.0.1.10\lib\net45\Fluent.dll".
                Fluent, Version=5.0.1.10, Culture=neutral, PublicKeyToken=3e436e32a8c5546f, processorArchitecture=MSIL

Here's the project:
[WpfApp2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1008980/WpfApp2.zip)

And some other details on my environment:
![image](https://cloud.githubusercontent.com/assets/6148201/26173747/340147c8-3b0a-11e7-97cf-6470ec47089a.png)
![image](https://cloud.githubusercontent.com/assets/6148201/26173767/426e2d26-3b0a-11e7-91a7-0ee37f668ecb.png)

---
### Environment

- Fluent.Ribbon __v5.0.1.10__
- Windows __10__
- .NET Framework __4.6__
(Visual Studio 2017 Community)

**Comment by batzen** [comment]
I just tried the same guide and everything worked as expected.
Could you attach your project, as a zip archive, to this issue?

**Comment by JVimes** [comment]
Sure, thanks! I just added the project and some more info.

**Comment by batzen** [comment]
Missed the part where you said that you fixed the problem by updating to the latest ControlzEx version.
Will have to update the nuget package to reference the version i compile Fluent.Ribbon with.
Always forget about these versions...

**Comment by batzen** [comment]
Will fix this beginning with version 6.0

**Comment by batzen** [comment]
Fixed in v5.0.2
