### ISSUE TITLE
Titlebar icon missing left margin when maximized

### ISSUE THREAD

**Issue by JVimes** [fluentribbon/Fluent.Ribbon#438]
I followed the [Basic setup]() instructions, and it seems that when the window is maximized, its titlebar icon has no left margin:

![image](https://cloud.githubusercontent.com/assets/6148201/26173425/0120492c-3b09-11e7-838b-a999431181a6.png)

I expect it to look similar to the File Explorer window's icon, when maximized:

![image](https://cloud.githubusercontent.com/assets/6148201/26173397/e98aba4a-3b08-11e7-8f41-817f66970aef.png)

---
### Environment

- Fluent.Ribbon __v5.0.1.10__
    - ControlzEx __v2.2.0.4__
- Windows __10__
- .NET Framework __4.6__

**Comment by JVimes** [comment]
That was so fast! 😸 🎉

**Comment by batzen** [comment]
Just a coincidence as i was looking through other issues ;-)
And is was a small fix :-)
