### ISSUE TITLE
Context menu and submenu disappears after a right click

### ISSUE THREAD

**Issue by nicwe** [fluentribbon/Fluent.Ribbon#439]
If you use a application menu with submenus and do a right click on a submenu item, both, the context menu and the submenu will be closed after a short moment.

Steps to reproduce:
- Start the showcase application
- Switch to the application menu (not backstage)
- Open the application menu (Click on "File")
- Right click on "Text document" in the submenu of "New"
- Both, the context menu and the submenu will be closed after a short moment

---
### Environment

- Fluent.Ribbon __v5.0.1__
- Windows __10__
- .NET Framework __4.0__

**Comment by batzen** [comment]
That's a bug we inherit from MenuItem from WPF itself.
Will try to create a workaround for this issue.
