### ISSUE TITLE
Update from 3.5.1.198

### ISSUE THREAD

**Issue by PeterForstmeier** [fluentribbon/Fluent.Ribbon#441]
Hi,
i tr< to update my solutuion from 3.5.1.198 to5.0.5.10
After running NuGet i get the following error at Startup.
```
<Application.Resources>
<ResourceDictionary>
<ResourceDictionary.MergedDictionaries>
<ResourceDictionary x:Name="gen" Source="pack://application:,,,/Erp_Dach.Base.Resource.Themes;component/Generic.xaml"/>
<ResourceDictionary x:Name="winres" Source="pack://application:,,,/Erp_Dach.Base.Resource.Themes;component/WindowRegionResource.xaml"/>
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
</ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
</Application.Resources>
```

`IOException -> Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />`
---
### Environment

-- Theme __?__ (not needed in version 5.0 and upwards)
- Windows 10
- .NET Framework 4.5

Thanks in advance
Peter

**Comment by batzen** [comment]
Hi,
there is a list of breaking changes in the changelog which contains all the information you need.
Fluent.Ribbon is versioned according to semver which means that every major version increase contains breaking changes.
So if you upgrade from version 3 to version 5 there are two versions (4 and 5) which contain breaking changes.
Have a look at
https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#400 for breaking changes which occured in version 4 and https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#500 for breaking changes which occured in version 5.

The specific breaking change you are encountering now was announced in version 4 and done in version 5.

To make it simple:
There are no office version specific themes anymore and "Themes/Office2013/Generic.xaml" got moved to "Themes/Generic.xaml". You now have to replace `pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml` with `pack://application:,,,/Fluent;Component/Themes/Generic.xaml`
For details on why this was done see https://github.com/fluentribbon/Fluent.Ribbon/issues/282

**Comment by PeterForstmeier** [comment]
Hi,

i will try it and be back if there are more questions.

 

Thanks

peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Juni 2017 12:53
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier; Author
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update form 3.5.1.198 (#441)

 

Hi,
there is a list of breaking changes in the changelog which contains all the information you need.
Fluent.Ribbon is versioned according to semver which means that every major version increase contains breaking changes.
So if you upgrade from version 3 to version 5 there are two versions (4 and 5) which contain breaking changes.
Have a look at
https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#400 for breaking changes which occured in version 4 and https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#500 for breaking changes which occured in version 5.

The specific breaking change you are encountering now was announced in version 4 and done in version 5.

To make it simple:
There are no office version specific themes anymore and "Themes/Office2013/Generic.xaml" got moved to "Themes/Generic.xaml". You now have to replace pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml with pack://application:,,,/Fluent;Component/Themes/Generic.xaml
For details on why this was done see #282 <https://github.com/fluentribbon/Fluent.Ribbon/issues/282>

**Comment by PeterForstmeier** [comment]
Hi,

i forgott to mention: i use Fluent.Ribbon togehter with Prism 5.x

what i did:

-remove all references to Fluent 3.xxxx

-remove all entires to Fluent.ribbon in packages.config in every project

-add Fluent.ribbon with NuGet (CpntrolzEz is added automaticaly) by HuGert

 

At startup i get  FileLoadException: Die Datei ControlzEx oder eine Abhängikeit wurde nicht gefunden….  Doe gefundene Manifestdatei stimmt nicht mit dem Assembyverweis überein)

 

Thanks

Peter

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Juni 2017 12:53
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier; Author
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update form 3.5.1.198 (#441)

 

Hi,
there is a list of breaking changes in the changelog which contains all the information you need.
Fluent.Ribbon is versioned according to semver which means that every major version increase contains breaking changes.
So if you upgrade from version 3 to version 5 there are two versions (4 and 5) which contain breaking changes.
Have a look at
https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#400 for breaking changes which occured in version 4 and https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md#500 for breaking changes which occured in version 5.

The specific breaking change you are encountering now was announced in version 4 and done in version 5.

To make it simple:
There are no office version specific themes anymore and "Themes/Office2013/Generic.xaml" got moved to "Themes/Generic.xaml". You now have to replace pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml with pack://application:,,,/Fluent;Component/Themes/Generic.xaml
For details on why this was done see #282 <https://github.com/fluentribbon/Fluent.Ribbon/issues/282>

**Comment by batzen** [comment]
Thats caused by a version mistake i made. You have to update the ControlzEx package to the latest version. Will fix this issue today or tomorrow by releasing an updated version. Sorry for that.

**Comment by batzen** [comment]
Released a fixed version 5.0.2 yesterday.

**Comment by batzen** [comment]
Do you have more issues you encountered while updating?

**Comment by PeterForstmeier** [comment]
Hi,

havn’t try yet. I will try it this evening or tomorrow.

 

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Dienstag, 6. Juni 2017 22:48
An: fluentribbon/Fluent.Ribbon <Fluent.Ribbon@noreply.github.com>
Cc: Peter Forstmeier <peter.forstmeier@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update form 3.5.1.198 (#441)

 

Do you have more issues you encountered while updating?

**Comment by PeterForstmeier** [comment]
Hi,

 

the update works.

Solution starts as expected.

But Prism reports that there is no Region named ‚ProjectRegion‘ but i’m shure that this region exist’s.

 

Moving back all works as expected

 

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Juni 2017 20:19
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier; Author
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update form 3.5.1.198 (#441)

 

Thats caused by a version mistake i made. You have to update the ControlzEx package to the latest version. Will fix this issue today or tomorrow by releasing an updated version. Sorry for that.

**Comment by batzen** [comment]
I never used prism.
Can't help you there without a repro.

**Comment by PeterForstmeier** [comment]
Hi,#

I’m on holiyday for one week. When i’m back i will go further and try it once more.

 

Peter

 

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. Juni 2017 22:33
An: fluentribbon/Fluent.Ribbon
Cc: Peter Forstmeier; Author
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update form 3.5.1.198 (#441)

 

I never used prism.
Can't help you there without a repro.

**Comment by batzen** [comment]
@PeterForstmeier ping

**Comment by PeterForstmeier** [comment]
Hi,

i didn’t have time to go further on…..

Sorry

Peter

 

Von: Bastian Schmidt [mailto:notifications@github.com] 
Gesendet: Freitag, 14. Juli 2017 12:58
An: fluentribbon/Fluent.Ribbon <Fluent.Ribbon@noreply.github.com>
Cc: Peter Forstmeier <peter.forstmeier@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [fluentribbon/Fluent.Ribbon] Update from 3.5.1.198 (#441)

 

@PeterForstmeier <https://github.com/peterforstmeier>  ping

**Comment by batzen** [comment]
@PeterForstmeier ping

**Comment by batzen** [comment]
@PeterForstmeier ping

**Comment by batzen** [comment]
@PeterForstmeier ping

**Comment by batzen** [comment]
@PeterForstmeier ping
