### ISSUE TITLE
Supported Themes

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#442]
Hi

I wanted to use the Office 2010 silver theme but I cannot find a working path to add to my `App.xaml`. Is there any list of Themes and the path I need to put in in order to use them?

My code just for completeness:

```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2010/Silver.xaml" />
            <ResourceDictionary Source="/Themes/Fluent.Ribbon.Generic.xaml"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

---
### Environment

- Fluent.Ribbon __v5.0.2.46__
- Windows __8.1__
- .NET Framework __4.5__

**Comment by batzen** [comment]
That theme got removed in 5.0 which was announced before 4.0 was released.
Have a look at the changelog and #282 for details.

**Comment by the-madcat** [comment]
Thanks for the fast answer. Is there any "older looking" theme left?

**Comment by batzen** [comment]
There is only one theme left as maintaining multiple was too time consuming and error prone for me.
The only thing i can offer when version 6 is finished are different color schemes.

**Comment by batzen** [comment]
@the-madcat Did that answer your question?

**Comment by the-madcat** [comment]
@batzen sry that I did not answer :sweat:
yes that did totally answer my question.
