### ISSUE TITLE
Startsceen "shines" through backstage 

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#445]
I try to use the startscreen as a kind of "welcome" page but want to limit the navigation just to the backstage.

Unfortunately the background (from the title and the content) of the startscreen is still visible when the backstage area is open:

![bug](https://user-images.githubusercontent.com/756703/27222847-4033799e-528e-11e7-8ac6-3b0be4c0e36f.gif)

In my scenario the user should only be able to navigate between the backstage and startscreen and because the backstage has always a "back" button I just want to navigate back to the startscreen.

Office itself does something similar:

![word](https://user-images.githubusercontent.com/756703/27222851-43ab78a6-528e-11e7-9b30-3e40b0f16f3d.gif)

I created a sample repository [here](https://github.com/robertmuehsig/Fluent.Ribbon/commit/fb04572c25419e812a7c2c210f017fd1cdb6d89a).

Related:
In theory I would love to be able to just hide the backbutton on the backstage, but this seems not possible (related issue https://github.com/fluentribbon/Fluent.Ribbon/issues/374) - I even tried to use some WPF tricks, but the button is rendered "too late" so I can't get a reference without super hacky timing stuff. 
With "CanChangeIsOpen=false" on the backstage I can disable the navigation, but the button itself is still rendered. 

---
### Environment

- Fluent.Ribbon 5.02
- Windows 10 
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Of course it's possible to hide the back button. I just haven't added a property for that.
Would it fit your needs if i add `IsBackButtonVisible` to `BackstageTabControl`?

**Comment by robertmuehsig** [comment]
That would be wonderful 👍 (but the Startscreen -> Backstage stuff would be cool too 💯 )

**Comment by batzen** [comment]
Implemented everything needed to enable your usecase.

You now only have to set `Visibility` to `Collapsed` on your `StartScreen` if your `Backstage` is open.

**Comment by robertmuehsig** [comment]
\o/ This will be part of 6.0? When will it be on NuGet?

**Comment by batzen** [comment]
This is part of 6.0. First preview will probably be released this weekend. Most of the resource overhaul will hopefully be done then.

**Comment by robertmuehsig** [comment]
Everything seems to work - would you recommend using v6 now or is it still "too" alpha?

**Comment by batzen** [comment]
Most, if not all, things are done in the preview.
Will have to release a new preview as i just removed the ThemeColorKey.
I consider it mostly stable. But there might still be breaking changes. If i find anything i don't like regarding styling i will change it. But aside from styling i don't think there will be anything major.
