### ISSUE TITLE
"Fluent.MetroColors.ThemeColorKey" in v6 

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#447]
With Fluent.Ribbon v4/5 it was possible for us to set the general color just via the the "Fluent.MetroColors.ThemeColorKey"-resource - the key is still there in v6 but it doesn't appear to work anymore.

We are using this simple mechanic to change the color:

    _resourceDictionary[Fluent.MetroColors.ThemeColorKey] = skinColor;

    skinColor is of type System.Windows.Media.Color
   _resourceDictionary is of type ResourceDictionary

With this we can set any color that we want and it worked quite well (even the "lighter" colors for background or "heavier" colors for borders etc.) were correct.

Via the ThemeManager I can only choose "existing", pre-built colors, which is not that great, or do I miss something to add new colors during runtime?

Is there a way to do that with v6?

### Environment

- Fluent.Ribbon __v6.0.0-dev0087__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
You have to overwrite `Fluent.Ribbon.Colors.AccentBaseColor` instead.
But that will really only overwrite that one color and not all derived colors.
I have to admit that changing the base color got a bit more difficult, but that's the price we have to pay to get full color scheme support.

To overwrite all colors derived from that you'll have to create a new color scheme at runtime by creating a new resource dictionary. This works exactly the same as in MahApps.Metro as Fluent.Ribbon is now using the exact same `ThemeManager`.
You can call `ChangeAppStyle` with your custom created instances of `Accent` and `AppTheme` for example.

I will remove `ThemeColorKey` as it's not being used anymore.

**Comment by batzen** [comment]
You can read more about `ThemeManager` at http://mahapps.com/guides/styles.html#thememanager i will have to copy to that to the fluent documentation and adjust it a bit.
The currently available accents are located in Fluent.Ribbon\Themes\Accents.

**Comment by robertmuehsig** [comment]
Ah - I guess I need to use something (or exactly?) this https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/ThemeManagerHelper.cs?

**Comment by batzen** [comment]
Something like that. I already copied that code and will add it to the showcase.

**Comment by batzen** [comment]
Added. 
Showcase/Helpers/ThemeHelper.cs
or visually
Showcase app => Tab "Styles"

**Comment by robertmuehsig** [comment]
I guess this can be closed now - thanks!
