### ISSUE TITLE
RibbonWindow title Color changed after call OpenFileDialog

### ISSUE THREAD

**Issue by wunianqing** [fluentribbon/Fluent.Ribbon#448]
**RibbonWindow title Color changed after call OpenFileDialog**

**Before call OpenFileDialog, it looks like this.
![img_1083](https://user-images.githubusercontent.com/12225840/27894502-17fe538e-623f-11e7-8404-044629531ae5.JPG)
After called OpenFileDialog, it looks like this.
![img_1084](https://user-images.githubusercontent.com/12225840/27894518-2ac26118-623f-11e7-90c9-f09855208789.JPG)
Part of titile background turned into system color. And if you resize the window, the missed part will go to normal.
**

---
### Environment

- Fluent.Ribbon __v5.0.1.10__
- Windows __7__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
This should already be fixed in version 6.0. Could you try to reproduce your issue using the preview from nuget?

**Comment by batzen** [comment]
@wunianqing ping

**Comment by wunianqing** [comment]
Sorry, I was on a business trip. 
It did solve the previous problem, but comes another question.
Background of RibbonTabItem header dose not inherit from background of RibbonWindow. Maybe is not a problem, but it's different with the previous version.

**Comment by wunianqing** [comment]
## Fluent.6.0 Version looks like this.
![default](https://user-images.githubusercontent.com/12225840/28103365-f2b51798-6707-11e7-93a5-68be0f28258d.png)
## PPT 2016 looks like
![ppt](https://user-images.githubusercontent.com/12225840/28103375-01375f6a-6708-11e7-956c-478bbad7edcf.png)
And it works fine in Fluent.5.x.x version.

**Comment by batzen** [comment]
The background issue is tracked by https://github.com/fluentribbon/Fluent.Ribbon/issues/435.
