### ISSUE TITLE
ThemeManger Injection

### ISSUE THREAD

**Issue by Christobal25** [fluentribbon/Fluent.Ribbon#449]
Hey, 
I have a Problem with the ThemeManger, it´s in the ViewModels null. And I want to change the Theme, so do you know a way which is not in the Showcase.
Or it´s possible to inject the Manger with ninject?

Best regards,
Chris

---
### Environment

Fluent Ribbon v6.0.0-dev0087
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
ThemeManager is a static class.
Static classes can't be injected. Even if you could inject ThemeManager you would still need a reference to Fluent.Ribbon in the project using it. If you want to use a mock for unittesting you would have to write a wrapper around ThemeManager and use that in your tests.

**Comment by batzen** [comment]
Did that answer your question? @Christobal25

**Comment by Christobal25** [comment]
I tried it like the example and what I try I got a Null.ReferenzException.

![exception](https://user-images.githubusercontent.com/8293015/28498666-bc5e7416-6fa2-11e7-8213-d195ac9ff76b.JPG)

It´s a ViewModel with MVVMlite.

**Comment by batzen** [comment]
Could you provide a repro for that?
My current guess is that you didn't include the style resources at the application level. Can you confirm that you include Generic.xaml in your App.xaml?

**Comment by Christobal25** [comment]
I had my own Style, but okay with the include from the Generic.xaml it give´s not an NullReferenceException.
Thanks you.

Best Regards, 
Chris

--->Can be closed<---

**Comment by batzen** [comment]
So you omitted all fluent styles or did you just overwrite some? Maybe there is still a bug in theme detection.
