### ISSUE TITLE
How to custom a style in V5.0.1?

### ISSUE THREAD

**Issue by heyixiaoran** [fluentribbon/Fluent.Ribbon#452]
**I want to custom a style. I see the http://fluentribbon.github.io/documentation/styles#app .
But I can not use like this. I try V5.0.1 and V5.0.2 . It is different .So I want to know how to custom a style in V5.0.1.  Can I just add a custom color ResourceDictionary and don't need add the template and others ?**

---
### Environment

- Fluent.Ribbon __v5.0.1
- Windows __10__
- .NET Framework __4.5__

**Comment by batzen** [comment]
That documentation is for version 6 which should be released sometime next week.

**Comment by heyixiaoran** [comment]
@batzen 
Hi . Now the documentation is not match for version 5.0.1. So how to do for version 5.0.1 now? Because we use version 5.0.1 now. Can you show me that?Thanks.

**Comment by batzen** [comment]
Yeah, that part of the documentation is valid for version 6 only.
To answer your question: 
What do you want to customize?
As most resources got renamed or replaced in version 6 i would recommend you want till version 6 is released. 
Currently the release is delayed till i get feedback for #435 from @Alisaunder and for #431 from @Alisaunder and @robertmuehsig.

**Comment by batzen** [comment]
@heyixiaoran ping

**Comment by batzen** [comment]
@heyixiaoran ping

**Comment by batzen** [comment]
@heyixiaoran ping

**Comment by batzen** [comment]
@heyixiaoran ping

**Comment by heyixiaoran** [comment]
@batzen Thanks. I update to V6.  This issue can close. Thank you very much
