### ISSUE TITLE
RibbonWindow title not shown in correct position when using SizeToContent

### ISSUE THREAD

**Issue by Cubey2019** [fluentribbon/Fluent.Ribbon#454]
When using SizeToContent="Width" (or WidthAndHeight) the caption in the window title bar can appear offset to the right, in some cases overlapping with the minimise/maximise/close buttons. The problem corrects itself if you manually resize the window (just clicking the resize border is enough).

This is a screenshot of our application's title bar, before & after resize:
![caption](https://user-images.githubusercontent.com/26153437/29310740-e74f391a-81a6-11e7-9beb-ab571fe6663c.png)

I can also reproduce this in the showcase application (committed changes to branch 1d397719c641004d0092e22b3d3ad9f0523a5f17) although it's not as obvious:
![fluent caption](https://user-images.githubusercontent.com/26153437/29310773-0b91dada-81a7-11e7-8aa8-7c7f6acae4ae.png)

---
### Environment

- Fluent.Ribbon __v6.0.0__ (d58e607125d297e277bc9577f965633a1f368d5f)
- Windows __10__
- .NET Framework __4.7__ (using 4.6.2 build)

**Comment by Cubey2019** [comment]
@batzen I've just been checking this again and noticed I can still reproduce this issue in the current source, by maximising the window (by dragging the window to the top of the screen, other maximise methods are OK).

If I change RibbonWindow.OnStateChanged to call Measure & Arrange (in the same way as you have in OnLoaded) then it seems to be OK.

**Comment by batzen** [comment]
Will have a look again then.

**Comment by batzen** [comment]
Doing that only partially fixes all issues.
When dragging to the side the window is still not resized, but that also does not happen with a regular WPF window...
