### ISSUE TITLE
Maximising a RibbonWindow with MaxWidth or MaxHeight causes an extra border above the title bar

### ISSUE THREAD

**Issue by Cubey2019** [fluentribbon/Fluent.Ribbon#456]
If a RibbonWindow has either MaxWidth or MaxHeight set (to a value less than the screen size), when maximising the window there is an extra border along the top edge. Looking closely it appears that there's extra window chrome being shown around the edge of the ribbon window, but it's more obvious at the top edge because there are tiny minimise/maximise/close buttons in the corner separate from the ribbon's buttons.

It's colour is independent from the ribbon background so stands out on a dark theme.

I can reproduce it in the showcase application by adding MaxWidth="1000" to TestWindow.xaml.

Screenshot (the red border I added in paint to highlight where it is :))
![border](https://user-images.githubusercontent.com/26153437/29319398-d557e958-81cb-11e7-81c9-b6e1ecba4b82.png)

---
### Environment

- Fluent.Ribbon __v6.0.0__ (d58e607125d297e277bc9577f965633a1f368d5f)
- Windows __10__
- .NET Framework __4.6.2__ (4.7 installed)

**Comment by Cubey2019** [comment]
Just been testing this and #454 with your latest changes and it's looking much better thanks :)

There does still seem to be a problem though if you maximise a window with SizeToContent set (and haven't manually resized first). I wasn't sure if the problem relates to this issue or #454 (or should be raised as a separate issue entirely).

If I add `SizeToContent="WidthAndHeight"` to TestWindow.xaml and maximise, the window size docks to the top of the screen but its size is unchanged (not constrained to one monitor and the height doesn't change). The problem with the window chrome returns as well:

![sizetocontent-2monitors](https://user-images.githubusercontent.com/26153437/29519642-0e9bc302-8676-11e7-9bbe-d6eb73ac0b89.png)


When trying to reproduce to capture the above screenshot it did sometimes resize the window correctly (although I can't seem to make it happen again) but the title wasn't being centered and the window buttons were missing (or off-screen):

![sizetocontent-width](https://user-images.githubusercontent.com/26153437/29519651-1623f644-8676-11e7-9078-3259e6a969f7.png)

Finally, if I also add `MaxHeight="800"` to TestWindow.xaml (with SizeToContent) then the window height will maximise to the correct height but will render black instead of resizing the content:

![sizetocontent-maxheight](https://user-images.githubusercontent.com/26153437/29519657-1b517c72-8676-11e7-8543-a5c3a9b07da3.png)

In all these cases if you restore the window and maximise a second time then everything looks correct.

**Comment by batzen** [comment]
Will have a look as soon as i can.

**Comment by batzen** [comment]
Let's continue this issue in https://github.com/ControlzEx/ControlzEx/issues/31 as this is caused by the implementation in ControlzEx. The same issues can be reproduced using the showcase application from ControlzEx.

**Comment by batzen** [comment]
Latest version of ControlzEx fixes this.
