### ISSUE TITLE
Image doesn't shown on Fluent.Ribbon Tab in WPF application 

### ISSUE THREAD

**Issue by zeinali0** [fluentribbon/Fluent.Ribbon#458]
**
I exactly follow documentation on http://fluentribbon.github.io/documentation/basic-setup and create an application but no Image show on application not in Design mode not even app is running
**

I added Fluent from nuget with VS2017

![no-icon-problem](https://user-images.githubusercontent.com/28354390/29368703-c04ae37c-82b5-11e7-8fe0-919dbe690fac.png)

---
### Environment

- Fluent.Ribbon __v5.0.2.46__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
The images are not included in the library, you have to provide your own images.
The sample code only has them to show you how to set images.
I will change the sample code and replace those paths with a placeholder so everyone know that they have to provide their own images.
Does that answer your question?

**Comment by zeinali0** [comment]
Yes, Tanks

**Comment by batzen** [comment]
Glad i could help.
Do you have more questions about using this library or wpf in general i could help you with?

**Comment by TruePluto** [comment]
You should set **Icon** and **LargeIcon** simultaneously.
**Icon** for **SizeDefinition** ="**Small**"/"**Middle**" **LargeIcon** for **SizeDefinition** ="**Large**". When you just set Icon but not set LargeIcon, you will get a blank button just with text.
