### ISSUE TITLE
Label of the Spinner disappears, if there isn't enough place

### ISSUE THREAD

**Issue by Ergel** [fluentribbon/Fluent.Ribbon#459]
Label of the Spinner disappears, if there isn't enough place for the ribbon-group. There is an empty space between icon and Input-Field of the Spinner. If you maximize the window or make it bigger, then the label of the spinner appears.

### Environment
Windows 7 Professional / Service Pack 1
Fluent.Ribbon  6.0.0.0
.NET Framework  4.6

**Comment by batzen** [comment]
`HorizontalAlignment` has to be `Left` instead of `Right` if `Size` of `Spinner` is `Middle`.

**Comment by batzen** [comment]
This might also be related to #344
