### ISSUE TITLE
Can't install Fluent.Ribbon on my UWP Project

### ISSUE THREAD

**Issue by shayaansiddiqui** [fluentribbon/Fluent.Ribbon#462]
I created a new Project and set the target to Creator's Update then tried to install Fluent.Ribbon from NuGet Package Manager.

Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063.
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-arm).
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-arm-aot).
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-x64).
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64-aot. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64-aot. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-x64-aot).
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-x86).
Package Fluent.Ribbon 5.0.2.46 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86-aot. Package Fluent.Ribbon 5.0.2.46 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
Package ControlzEx 2.2.0.4 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86-aot. Package ControlzEx 2.2.0.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.15063 (win10-x86-aot).
Package restore failed. Rolling back package changes for.
Time Elapsed: 00:00:01.7819468
========== Finished ==========

---
### Environment

- Fluent.Ribbon __v5.0.2.46
- Windows  10 14393.1593
- .NET Framework 4.7

**Comment by batzen** [comment]
That's because this library is made for WPF and not for UWP.
I won't add support for UWP as i don't plan on using UWP.

**Comment by shayaansiddiqui** [comment]
Thanks for the quick response.

**Comment by Alisaunder** [comment]
@shayaansiddiqui  Syncfusion has a free ribbon control available for UWP. I don't use it because My UWP apps have a different interface using Page Navigation. WPF though is the best platform for Ribbon controls in my opinion and Fluent is the best free control out.
