### ISSUE TITLE
ShowQuickAccessToolBarAboveRibbon="False" causes crash

### ISSUE THREAD

**Issue by dady8889** [fluentribbon/Fluent.Ribbon#463]
As title says, it causes

```
System.InvalidOperationException: 'Specified element is already the logical child of another element. Disconnect it first.
```
Reproduction:
Put ShowQuickAccessToolBarAboveRibbon="False" into your Ribbon control. Tested on latest showcase.

---
### Environment

- Fluent.Ribbon Latest develop head
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Can't reproduce this using the latest source version.

**Comment by dady8889** [comment]
I've just recloned the repo to be sure and went to TestContent.xaml in Fluent.Ribbon 4.5 Showcase and put it in the ribbon control. The error occurs from PresentationFramework.dll and my version is v4.0.30319, probably it's a factor. I use VS 2017. I have fixed it in the code, however I doubt it's the correct way of fixing it.
![error1](https://user-images.githubusercontent.com/5238573/29637213-bdafc684-8853-11e7-8105-efff069e9bb8.png)

**Comment by batzen** [comment]
> and put it in the ribbon control.
What does that mean?

**Comment by dady8889** [comment]
I mean, when I put ShowQuickAccessToolBarAboveRibbon="False" as an attribute inside the ribbon control initial tags. I have noticed that it indeed does work when you change the attribute in the showcase using the checkbox.

**Comment by batzen** [comment]
Ah, will try to reproduce it that way tomorrow.
