### ISSUE TITLE
Clicking on hyperlink inside of ApplicationMenu causes crash

### ISSUE THREAD

**Issue by dady8889** [fluentribbon/Fluent.Ribbon#464]
So, I use hyperlinks inside of my Ribbon.Menu and when you click on them, an error occurs.
This time I've got a repro project for you.
[FluentBugHyperlink.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1248931/FluentBugHyperlink.zip)

Open the Menu and the hyperlink in the first MenuItem.

I have fixed it like this:
https://github.com/dady8889/Fluent.Ribbon/commit/83a481fff554b058688fab3e938d04fe234661df

There should be more elements like hyperlink that aren't Visuals and the code above should fix it for them too.

---
### Environment

- Fluent.Ribbon Latest
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
The fix looks like a good start.
Will fix it slightly different.
