### ISSUE TITLE
Clicking on ContextualGroup background or scrolling through ribbon will open disabled tab

### ISSUE THREAD

**Issue by dady8889** [fluentribbon/Fluent.Ribbon#465]
When you disable tabs in ribbon, you can't open them by clicking on them. If you put them into a Group you still can't click on them, but if you click above the tab on the Group background it will open the first tab, it doesn't care if the tab is enabled or disabled.

Repro:
[FluentBugContextualTabGroup.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1249016/FluentBugContextualTabGroup.zip)

Fix:
https://github.com/dady8889/Fluent.Ribbon/commit/c7208b749b25ea9198d401b401a22b0c6a68d858

However, this is a quick fix. I think it would be better to find the first enabled tab and open it, if there is no enabled tab, don't do anything.

---
### Environment

- Fluent.Ribbon Latest
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Will fix it like you suggested.
Thanks for the suggested fix.
