### ISSUE TITLE
Fluent:SplitButton IsEnabled 

### ISSUE THREAD

**Issue by TruePluto** [fluentribbon/Fluent.Ribbon#467]
I'm using a Fluent:SplitButton binding to ApplicationCommands.Undo
when the ApplicationCommands.undo is disable, the Fluent:SplitButton's Button is disabled properly.
but the DropDown still enable.
I dont know how to put a put a Image here. but the following code could represent the issue.
`            <fluent:SplitButton Icon="{StaticResource IconUndo}"
                                LargeIcon="{StaticResource IconUndo}"
                                Command="Undo"
                                Header="Undo">
`
When the ApplicationCommands.Undo is disable, put mouse hover, the button the color of the button turns blue(activing). click then the the dropdown shows. 
**I want to completedly diable the Button. what should I do.**
Sorry for my poor english.

- Fluent.Ribbon __v5.0.2.46__
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
You can use `IsButtonEnabled` to disable the DropDown.

**Comment by TruePluto** [comment]
Sorry ，I don't know what mistake I made
 `<fluent:SplitButton Icon="{StaticResource IconUndo}" LargeIcon="{StaticResource IconUndo}" Command="Undo" Header="Undo" IsButtonEnabled="False"> `
still doesn't work.

**Comment by batzen** [comment]
`IsButtonEnabled="False"` disables the button part.
`IsEnabled="False"` disables the whole `SplitButton`.

But you are right, if the command can't be executed the button is still enabled.
Will have a look at that.

**Comment by TruePluto** [comment]
thank you @batzen

**Comment by batzen** [comment]
Will have to revert this fix. 
Haven't thought about people using a command but don't want to also disable the dropdown if command can't be executed.
If you want to disable the whole control you should use `IsEnabled` instead.
