### ISSUE TITLE
RibbonTabItem or RibbonGroupBox reusing

### ISSUE THREAD

**Issue by TruePluto** [fluentribbon/Fluent.Ribbon#468]
**Hi, I want to re-use some _RibbonTabItems_ or _RibbonGroupBoxes_ in mutliple _RibbonContextualTabGroups_.**

I found that we can re-using the fluent.controls such as _fluent:Button_ . via the _QuickAccessMenuItem_ through binding the property **Targe** in _QuickAccessItems_ .
But the _RibbonTabItem_ should be binded to _RibbonContextualTabGroup_ via itself property **Group**,
why not through some _RibbonContextualTabGroupItems_  to binding it in the _RibbonContextualTabGroup_ , if so , _RibbonTabItems_   can be reused in many _ContextualTabs_ 
in fact I want to re-use the _RibbonGroupBoxes_ . I want to some _ContextualTab_ s have the same buttons such as cut copy paste. re-using _RibbonGroupBoxes_ is better. of course both are woundful.

Maybe it's not a good idea.
and sorry for my poor English

---
### Environment

- Fluent.Ribbon __v5.0.2__
- Windows __X__
- .NET Framework __4.7__

**Comment by batzen** [comment]
Any ideas on how to get this working? Keeping in mind that every control in WPF only can have one visual parent.

**Comment by TruePluto** [comment]
Yes, you are right, but I don't understand the quick access tookbar mechanism, a button can appear simultaniously RibbonGroupBox and QuickAccessItems? 
I have some RibbonTabItems that I want they have some common buttons such as cut copy paste etc.
so I have the idea. I know its hard to implement.
I will add them to every  RibbonTabItems manully. thank you.

**Comment by batzen** [comment]
They don't appear simultaniously, they are "cloned". Have a look at the CreateQuickAccessItem methods of various controls.

In theory, never tried that, you should be able to create a usercontrol inherited from RibbonGroupBox, add your items there and use that control multiple times. That way you don't have to add single items every time.

**Comment by TruePluto** [comment]
Clone is good too, at least I just need to write once  and manage them together, QuickAccessItems copy the reference element , I need some proxy class to do the same clone things. 
sorry for  bothering you so many times.
thanks again.
