### ISSUE TITLE
Backstage BackButton

### ISSUE THREAD

**Issue by polyphem** [fluentribbon/Fluent.Ribbon#47]
Hello
I put the the "Fluent:Ribbon" component in a Page. Everything works fine except the BackButton form the Backstage. The Button is visible but I can't click the button. I don't know if this is a bug or if I just can't place the  Ribbon in a Page. Hopefully you guys have a solution for me ...

**Comment by batzen** [comment]
Could you post a repro for that?

**Comment by batzen** [comment]
Could you post a repro for that?

**Comment by batzen** [comment]
Closed because no reaction from reporter.
