### ISSUE TITLE
How to modify the title of RibbonWindow to multiline text?

### ISSUE THREAD

**Issue by heyixiaoran** [fluentribbon/Fluent.Ribbon#472]
I want to modify the title of RibbonWindow to multiline text. But the title property is a string type. I also can not override the template. So how can I do it?

Like:

MainTitle
SubTitle
UserName

---
### Environment

- Fluent.Ribbon 4.0.3
- Windows  10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
That should be possible.
The only "problem" is that the header of the titlebar is currently fed by `Window.Title` which is a simple string. The `Header` of `RibbonTitleBar` is of type object an could thus contain any control.

Will think a bit about it and come back to you to suggest a solution.

**Comment by batzen** [comment]
@heyixiaoran Took me a while to get some spare time.
The easiest way to achieve this is to just make your title multiline and then adjust TitleBarHeight.
Does that fit your needs?

**Comment by heyixiaoran** [comment]
Title can‘t override the template . /r/n also can not work. So I add a part to move the title position.Thanks

**Comment by batzen** [comment]
You don't need to override the template and \r\n works fine if you increase TitleBarHeight.
