### ISSUE TITLE
RibbonWindow does not resize when Children resize and SizeToContent is used

### ISSUE THREAD

**Issue by Menic0** [fluentribbon/Fluent.Ribbon#473]
RibbonWindow does not resize when Children resize.

![image](https://user-images.githubusercontent.com/30926969/30547810-ae349cba-9c90-11e7-8ca5-dc146c8897c3.png)

![image](https://user-images.githubusercontent.com/30926969/30547814-b3b0e28e-9c90-11e7-9373-9fa7491fc422.png)

Standard WpfWindow does resize
![image](https://user-images.githubusercontent.com/30926969/30547848-c95f8360-9c90-11e7-8a37-18d8ec9f4b8a.png)
![image](https://user-images.githubusercontent.com/30926969/30547856-cd227dae-9c90-11e7-853f-690718feff65.png)

---
### Environment

- Fluent.Ribbon origin/HEAD (6. Sept)
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Will have a look at that during the next few days.

**Comment by batzen** [comment]
This is caused by the fix applied for #454.
Will try to find a different solution...
