### ISSUE TITLE
Resizing content on minimizing ribbon

### ISSUE THREAD

**Issue by wcmiller3333** [fluentribbon/Fluent.Ribbon#474]
Is there a xaml way to push the contents of the grid below the ribbon up or down depending on the size of the ribbon?

**Comment by batzen** [comment]
I don't fully understand that question. A screenshot showing what you want to achieve would help a lot here.

**Comment by batzen** [comment]
@wcmiller3333 ping

**Comment by batzen** [comment]
@wcmiller3333 ping

**Comment by batzen** [comment]
@wcmiller3333 ping

**Comment by batzen** [comment]
@wcmiller3333 ping

**Comment by batzen** [comment]
@wcmiller3333 ping
