### ISSUE TITLE
no build - error

### ISSUE THREAD

**Issue by VratislavBelsky** [fluentribbon/Fluent.Ribbon#475]
ReadBuild Solution Windows10 CZ, Visual Studio Community 2017 

Output...
1>------ Rebuild All started: Project: Fluent.Ribbon.NET 4.5, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: Fluent.Ribbon.NET 4.6.2, Configuration: Debug Any CPU ------
1>  Paket version 5.97.0
1>  Please use the new syntax: '--references-files' has been replaced by '--references-file'.
1>  Performance:
1>   - Disk IO: 31 milliseconds
1>   - Runtime: 2 seconds
1>  Systém nemůže nalézt uvedenou cestu.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: The command "SET tmpError=0
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: "D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\Themes\XamlCombine.exe" Styles.txt Styles.xaml
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: SET /a tmpError=%tmpError% + %ERRORLEVEL%
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: "D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\..\packages\XamlColorSchemeGenerator\tools\XamlColorSchemeGenerator.exe" "D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\Themes\Accents\GeneratorParameters.json"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: SET /a tmpError=%tmpError% + %ERRORLEVEL%
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: SET ERRORLEVEL=%tmpError%" exited with code 3.
.......

Error List...
The command "SET tmpError=0
"D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\Themes\XamlCombine.exe" Styles.txt Styles.xaml
SET /a tmpError=%tmpError% + %ERRORLEVEL%
"D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\..\packages\XamlColorSchemeGenerator\tools\XamlColorSchemeGenerator.exe" "D:\vs\Fluent.Ribbon-develop\Fluent.Ribbon\\Themes\Accents\GeneratorParameters.json"
SET /a tmpError=%tmpError% + %ERRORLEVEL%
SET ERRORLEVEL=%tmpError%" exited with code 3.	
Fluent.Ribbon.NET 4.5 / Fluent.Ribbon.NET 4.0 / Fluent.Ribbon.NET 4.6.2
			

- Fluent.Ribbon __v6 develop
- Windows 10 CZ
- .NET Framework 4.0 4.5 4.62

sorry no english

**Comment by batzen** [comment]
Does that happen on every build or just the first build?

**Comment by VratislavBelsky** [comment]
Every build
Belsky

a.

26. 9. 2017 v 18:34, Bastian Schmidt <notifications@github.com>:

**Comment by VratislavBelsky** [comment]
From stocking XamlCombine


Belsky

26. 9. 2017 v 18:34, Bastian Schmidt <notifications@github.com>:

**Comment by batzen** [comment]
Issue should be fixed now. 
Could you pull and retry?

**Comment by VratislavBelsky** [comment]
Thank you, it is ok


27. 9. 2017 v 16:31, Bastian Schmidt <notifications@github.com>:

**Comment by batzen** [comment]
Glad i could help.
