### ISSUE TITLE
How to hide Title bar?

### ISSUE THREAD

**Issue by kalatchev** [fluentribbon/Fluent.Ribbon#476]
**How to hide Title bar?**

Can anyone help me to hide totle bar after window has been loded? I've tried with 
```
        Me.WindowStyle = WindowStyle.None
        Me.Title = ""
        Me.MainRibbon.TitleBar.Visibility = Visibility.Hidden
        Me.Background = Brushes.Transparent
        Me.BorderThickness = New Thickness(0)
```

but **nothing of above helps**.

Here what I get:

![image](https://user-images.githubusercontent.com/10154711/31051769-15584750-a67a-11e7-950b-dc8e3a4d5b5b.png)

- Fluent.Ribbon __v5.0.2.46__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Visibility Hidden in WPF means something like "reserve space but don't render". Better try Collapsed.

**Comment by Alisaunder** [comment]
Are you placing the code in the window_loaded event?

**Comment by kalatchev** [comment]
> Better try Collapsed

Doesn't helps.

> Are you placing the code in the window_loaded event?

Yes, I place it in **Private Sub MainWindow_Loaded(sender As Object, e As RoutedEventArgs) Handles Me.Loaded** (It's VB)

**Comment by batzen** [comment]
Will have a look at this as soon as i have some spare time.

**Comment by batzen** [comment]
@kalatchev The easiest way to totally hide it is to set `TitleBarHeight` to `0`.
Does that answer your question?

**Comment by batzen** [comment]
@kalatchev ping

**Comment by batzen** [comment]
@kalatchev ping

**Comment by kalatchev** [comment]
Yes, it wors. Thanks.
