### ISSUE TITLE
Custom MinWidth of Start Screen (LeftContent)

### ISSUE THREAD

**Issue by kalatchev** [fluentribbon/Fluent.Ribbon#478]
**How can I set the width of LeftContent of StartScreen?**

I digged trough the source code, but I didn't succeed to realize how I can set the width of LeftContent in StartScreen. I saw that it inherits Backstage control. Left side of Backstage control seems to me much narrowly than same in Start Content. However, I would like to have smaller left content, and generally I would like to control the widht of it.

---
### Environment

- Fluent.Ribbon __v5.0.2.46__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Will have a look at this as soon as i have some spare time.

**Comment by kalatchev** [comment]
In fact, of course, it is possible with enumeration of the visual tree and set it manually, as follow:

`Dim g As Grid = XAMLHelpers.FindStartScreenGrid(Me)`
`g.ColumnDefinitions(0).MinWidth = 200`

where **FindStartScreenGrid** is recursive function for finding right grid. One of the problems is that Start Screen's grid has no some unique name, such as PART_StartScreenGrid or something like that. So even enumeration of visual tree is unreliable. The second is that such workaround is kind of hack, than normal use of control.

IMHO we should make two changes:

- Add property like LeftContentWidth
- Set intrinsic name of the grid like PART_xyz for firther use

**Comment by kalatchev** [comment]
In fact, of course, it is possible with enumeration of the visual tree and set it manually, as follow:

`Dim g As Grid = XAMLHelpers.FindStartScreenGrid(Me)`
`g.ColumnDefinitions(0).MinWidth = 200`

where **FindStartScreenGrid** is recursive function for finding right grid. One of the problems is that Start Screen's grid has no some unique name, such as PART_StartScreenGrid or something like that. So even enumeration of visual tree is unreliable. The second is that such workaround is kind of hack, than normal use of control.

IMHO we should make two changes:

- Add property like LeftContentWidth
- Set intrinsic name of the grid like PART_xyz for firther use

**Comment by Aitania** [comment]
just use <fluent:SeparatorTabItem MinWidth="111"/> if you don't want to update.
