### ISSUE TITLE
Windows 8 Theme

### ISSUE THREAD

**Issue by pekspro** [fluentribbon/Fluent.Ribbon#48]
I have had some thoughts to create a "Windows 8"-theme to the Fluent Ribbon project. Today I spend some hours and I've now have something that looks like this:

![win8themedemo](https://cloud.githubusercontent.com/assets/3163293/5598938/e1644f4c-92be-11e4-8a52-fdfa1fb9ffc0.png) 

This is just my playing around. Nothing serious, I just took the white Office 2010 theme and tweaked it. There is several things still that needs to be solved. I wanted to see if this is feasible to do and I think it is. But I must say that all these controls in borders in other borders that is in other borders could be confusing :-).

If I decide to do this more serious, is there a chance that this will be merged into the main project? If yes, is there any guide lines I should follow? Should I create a totally new theme or just a new "Color" to the Office 2010 theme? Just changing colors is not enough - Windows 8 theme doesn't have any gradients or rounded corners but if these things also getting theme based it might be possible.

My ambition is to have something that looks like the ribbon bar in Explorer, Wordpad and Paint in Windows 8. I can't promise that I will be able to solve everything but I think it is worth to try :-)

**Comment by batzen** [comment]
It would be less tricky if you'd base your theme on the Office 2013 theme. Most rounded corners and gradients are already removed there. Maybe it's just about changing colors when using the Office 2013 theme as a starting point.
Anyway it sounds interesting and could be merged to the main project. If you need to change more than colors this would be a new theme and not a new color scheme.

**Comment by pekspro** [comment]
Interesting idea. I will look into the 2013-theme as well. I get back to you when I understand everything more. I don’t want to start anything until we have agreed how the overall solution should be. Having the ability to merge this into the main project is important to me so I want to do this right :-).

**Comment by pekspro** [comment]
Now I’m ready to start work with this. My plan in to have the Office 2010 silver theme as a base, and copy a lot of code from the Office 2013 :-). I just I have two questions.

Which XAML-formatting setting should I use?

When should I start to make pull requests for this? Personally I want to do this quite soon so it’s possible to review and find mistakes as early as possible.

**Comment by batzen** [comment]
I don't think it's a good idea to use the Office 2010 theme as a base. The Office 2013 theme already has most gradients and corners with radius removed...

I will add a "Contributing" section to the Readme.md this week which will include those settings.

**Comment by pekspro** [comment]
It’s true, but most of the colors in the Office 2010 match better the Windows 8 theme I thought so therefore I choice that. Removing gradients and corners is not too hard I think, I will compare the controls with the Office 2013 theme. So far it goes quite well. I have started with the window, tab control and buttons and so far it looks quite good I think :-).

**Comment by batzen** [comment]
Wouldn't it be much easier to just use the Office 2013 theme and the colors from the Office 2010 theme? That way you would just have to change the colors and not everything else.

**Comment by pekspro** [comment]
Well, maybe :-). I’m actually using both. I normally start with the Office 2010, and then I compare with the Office 2013. The later theme doesn’t has any borders, and I prefer to remove code instead of guessing where to write some new :-). I’m actually surprised how very similar these two themes are in the XAML, I expected a lot more differences.

So far everything goes quite well. There are some things I haven’t been able to solve, but most things looks really good I think. My guess is that about half of the work is done. I will make a pull request in a couple of days I hope.

**Comment by batzen** [comment]
That's why i tried to avoid a third very similar theme... ;-)
But nice to hear that your work is half done.

**Comment by pekspro** [comment]
That’s understandable. Making similar changes in two themes can’t be fun, and a third one will make it worse.

Either way, I’m very close to a beta. I will probably make a pull request tomorrow evening. I have a few questions that I need some help with, but not much :-).

**Comment by batzen** [comment]
I merged your PR but i guess there are still some things to be done, so i leave this issue open for now to keep track of the progress.

**Comment by pekspro** [comment]
Thanks, that's pretty cool :-). I will do some final tweaks this weekend. But I’m quite happy with it already so it won’t be much.

**Comment by batzen** [comment]
I think we should close this bug and track further changes/additions to the Windows 8 theme in separate issues/pull requests.
Do you think so too?

**Comment by pekspro** [comment]
Yes, I agree. It seems to be stable in my opinion.
