### ISSUE TITLE
TextFormattingMode for RibbonWindow

### ISSUE THREAD

**Issue by ghord** [fluentribbon/Fluent.Ribbon#482]
Is there a reason for not setting TextFormattingMode to  `TextOptions.TextFormattingMode="Display"` for `RibbonWindow`? Without this text looks slightly blurry. Default WPF Window has this property enabled.

**Comment by batzen** [comment]
The default for WPF is `Ideal` and not `Display`.

> Default WPF Window has this property enabled.

At least not on my machines and as we don't modify that property we should inherit the WPF defaults for that. If it differs

**Comment by batzen** [comment]
@ghord ping

**Comment by ghord** [comment]
@batzen It seems you are right. I've gotten so used to having this in my projects due to 3rd party themes that all other text just sticks out as blurry to me. I guess it would be better to leave default as it is.

Just to compare the look of the text, I leave this here:
![comparison](https://user-images.githubusercontent.com/10825459/32195237-073aa992-bdbd-11e7-9b22-a3506f011178.png)

You can see slightly blurry text on default settings (strongly visible on blurry "H" in "Home")

**Comment by batzen** [comment]
Will leave the property value as it is provided by WPF defaults.
