### ISSUE TITLE
Add special style/template for MenuItem with set description

### ISSUE THREAD

**Issue by 2480258** [fluentribbon/Fluent.Ribbon#484]
Sorry, I can`t English well.

![capture](https://user-images.githubusercontent.com/19368937/31854476-03964984-b6d5-11e7-9130-d64247889468.PNG)

<Fluent:SplitButton Heaer="">
    Something I want.
</Fluent:SplitButton>

In other words, ...I want to make a menuitem(or someting smailiar) (In capture, It looks like 비교(C)...)
and I want the menuitem loaded when click split button(or something smailiar. i.e. InRiboonGallary).

Please answer me how to add the items or keyword for googling.
I tried but can`t found any possible solutions.

**Comment by 2480258** [comment]
I tried [this](https://github.com/fluentribbon/Fluent.Ribbon/issues/115) example to solve problem, but it didn`t work.

Added Menuitem just shows its Header, ignoring its Description.

**Comment by batzen** [comment]
Description is ignored because that's only implemented when using MenuItem inside ApplicationMenu.

However, you should be able to place whatever you want inside Header of MenuItem and you don't even have to use MenuItem inside SplitButton, you can use whatever control you like.

Does that answer your question?

**Comment by 2480258** [comment]
Please let me know what is the correct control to implement it. (can use with split button and can express bolded text and description. In other words, I want to make a program like above photo.)

**Comment by batzen** [comment]
Will try to prepare something for you during the next few days. Should be done by the end of the week.

**Comment by 2480258** [comment]
Thank you. I'll keep watching this. :)

**Comment by batzen** [comment]
@2480258 There you go. You can now, by using the latest source version of Fluent.Ribbon, just use the description and an 24x24 icon to get what you asked for.

**Comment by 2480258** [comment]
Thank you!!! I glad to use these functions :)
