### ISSUE TITLE
RibbonTabItem White Stripe

### ISSUE THREAD

**Issue by Mo1k** [fluentribbon/Fluent.Ribbon#487]
Hi,

i have never used a Ribbon, just a classic menu. Now i want to switch to a Ribbon menu and i have made a small test program. I want to change the background color of a RibbonTabItem if it is selected. It works fine but there is a small white stripe below the Tab Name.

Btw: How can i change the background-color of the big Ribbon under the TabItem, how can i change the background-color of a RibbonTabItem if the mouse is over it and how can i deactivate the tooltips when the mouse is over a RibbonTabItem ?

![fluentribbonproblem](https://user-images.githubusercontent.com/33346665/32370613-1580c378-c08e-11e7-9926-755aae585a21.png)

---
### Environment

- Fluent.Ribbon __v5.0.2.46__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
A lot changed in version 6 regarding colorization. So you have to use the pre-release from nuget to get this.
Have a look at the showcase application there is a sample which can be reached through the TabControl contained in the content area, on the "Tests" tab there is a button labeled "Open Ribbon-Window (colorized)" which shows different colors.
The code can be found at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon.Showcase/RibbonWindowColorized.xaml

**Comment by Mo1k** [comment]
Thanks for the tip with V6.
I tried V6 and now i can switch the background-color, but the problem with the stripe (in background-color) below the TabName is still there:
![fluentribbonv6stripe](https://user-images.githubusercontent.com/33346665/32404829-e7e6f664-c158-11e7-9e45-9dd3a4005f04.png)

**Comment by batzen** [comment]
Never noticed that stripe. Will have a look at it later.

**Comment by batzen** [comment]
Strange, i just had a look and i don't see any stripes.
Could you try that on a different machine?

**Comment by batzen** [comment]
@Mo1k ping

**Comment by batzen** [comment]
@Mo1k ping
