### ISSUE TITLE
Display border around content area of RibbonTabControl

### ISSUE THREAD

**Issue by caofali** [fluentribbon/Fluent.Ribbon#488]
How to display the vertical line on both sides like this ?

### Environment

- Fluent.Ribbon v5.02
- Windows 7
- .NET Framework 4.5

**Comment by caofali** [comment]
![image](https://user-images.githubusercontent.com/33412379/32429535-fca12c56-c305-11e7-9b47-6cf25d977e13.png)

**Comment by batzen** [comment]
Will have a look this weekend.
