### ISSUE TITLE
Where are the accents and themes?

### ISSUE THREAD

**Issue by SalehGladius** [fluentribbon/Fluent.Ribbon#490]
The [Styles Documentation](http://fluentribbon.github.io/documentation/styles),  uses accents and color bases, but now those accents aren't exist in Fluent.Ribbon v5!
        
            
            <ResourceDictionary Source="pack://application:,,,/Fluent;component/Themes/Accents/Blue.xaml" />
            
            <ResourceDictionary Source="pack://application:,,,/Fluent;component/Themes/Accents/BaseLight.xaml" />

An error accurred while finding the resource dictionary!
---
### Environment

- Fluent.Ribbon __v5.0.2.46
- Windows __10__
- .NET Framework __4.5+__

**Comment by SalehGladius** [comment]
also, I can't change colors in code directly. in dark styles, tab items text didn't display correctly!
![ribbon](https://user-images.githubusercontent.com/8124646/32733963-ef833e60-c8a5-11e7-80f9-1a4f442a5aef.jpg)

**Comment by batzen** [comment]
You have to use the prerelease of version 6 to get the accent/theme to work.

**Comment by wizkidd** [comment]
I had the same issue. Is the prerelease available through Nuget?

**Comment by wizkidd** [comment]
I had the same issue yesterday. Why doesn't the stable v5.0.2.46 have the styles?

**Comment by wizkidd** [comment]
So, I tried the prerelease and it couldn't find the BaseLight resource: 
`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Accents/BaseLight.xaml" />`

Also, the tooltips' positions are off for the Ribbon:
![fluentribbonbugimage](https://user-images.githubusercontent.com/9717700/32755684-b577015a-c893-11e7-9419-5d4c934f3b16.png)

**Comment by batzen** [comment]
It's not in a previous version because it was developed later. "BaseLight" belongs to the "Colors" folder and not to the "Accents" folder.

**Comment by wizkidd** [comment]
Ok I'll try that out, I was following the documentation for using BaseLight which shows it is in Accents folder: http://fluentribbon.github.io/documentation/styles
Does v5.0.2.46 have any themes or styles that can be used?

**Comment by batzen** [comment]
Yes, that part of the documentation is for version 6 only. Should have marked it with a hint...
Version 5 does not have these themes/styles. Themes like office 2010 etc. were removed in version 5 and version 6 adds the color/accent as a replacement for those old themes.
