### ISSUE TITLE
default windows ContextMenu is overriding Ribbon context 

### ISSUE THREAD

**Issue by MajedDH** [fluentribbon/Fluent.Ribbon#491]
When the quick access toolbar is above the ribbon default windows context menu of window's `TitleBar` is overriding ribbon context menu (remove from quick  access toolbar..  etc).
![image](https://user-images.githubusercontent.com/3973115/33024470-d924d5de-ce13-11e7-991f-0c78db8563b4.png)

---
### Environment

- Fluent.Ribbon __v6.0.0-dev0171__
- Windows 7 
- .NET Framework 4.5
- ### I'm using MahApps.Metro 1.5.0 and using ribbon the same way it is used in showcase folder in this Repo

**Comment by batzen** [comment]
You could try to use `this.ShowSystemMenuOnRightClick = false;` on the MetroWindow, but that will disable the system menu on most of the titlebar.

Will have a look on how to improve the situation out of the box.

**Comment by batzen** [comment]
Just noticed that there are no changes needed to either library, you just have to use `ShowSystemMenuOnRightClick="False"` on `MetroWindow`.
