### ISSUE TITLE
Change display order of RibbonGroupBoxes?

### ISSUE THREAD

**Issue by fireundubh** [fluentribbon/Fluent.Ribbon#492]
How do you change the display order of RibbonGroupBox elements?

**Comment by batzen** [comment]
Hi @fireundubh you mean at runtime?

**Comment by batzen** [comment]
@fireundubh ping

**Comment by fireundubh** [comment]
So, when you run the application, the RibbonGroupBox elements are sorted from left to right in alphabetical order. I'd like to customize that order.

**Comment by batzen** [comment]
They are ordered by insert order. So you can customize the order in xaml or by adding the items in your desired order by code.

**Comment by batzen** [comment]
@fireundubh Does that answer your question?

**Comment by batzen** [comment]
@fireundubh ping

**Comment by fireundubh** [comment]
> Does that answer your question?

Yes. I haven't had a chance to return to the WPF project I was working on, but I'll try your suggestion when I do. Thank you.
