### ISSUE TITLE
How to align controls such as ToggleButton, Spinner with text

### ISSUE THREAD

**Issue by TruePluto** [fluentribbon/Fluent.Ribbon#494]
I have some controls such as  ToggleButton, Spinner with text and icon, but they don't align well because the texts' length are different.. I know Grid have a property called IsSharedSizeScope, do they have some kind  of this property.

**Comment by batzen** [comment]
Could you provide a screenshot showing your issue?

**Comment by TruePluto** [comment]
![captures](https://user-images.githubusercontent.com/19511177/34546308-e4c54a32-f0ea-11e7-8487-522e322fc706.JPG)

It's hard to figure out how to post a image. but now it's ok 
 Actually I want the textboxes of CATMULLLROOM and POINT to align. and the textblocks of interpolation and sample type are right alignment.
Thanks for your response.

**Comment by batzen** [comment]
Now i get it.
Will have a look at how to enable such a feature.

**Comment by batzen** [comment]
I found a solution for this issue.
The general idea is that you'd have to set `Grid.IsSharedSizeScope="True"` for each `RibbonGroupBox` that should size headers of controls like `Spinner` and `ComboBox` equally.

@TruePluto If you place `Spinner` and `ComboBox` in on top of each other, should their header sizes be equal?

**Comment by TruePluto** [comment]
Sorry ,I can't understand the meaning of "in on top of each other"
Actually ,my code like this:

                <f:RibbonGroupBox Header="Sample"
                                  Grid.IsSharedSizeScope="True">
                    <f:ComboBox Header="Interpolation Type"
                                ItemsSource="{Binding Source={StaticResource InterpolationType}}"
                                SelectedValue="{x:Static l:Tiff16BitMetaData.DefaultInterpolationType}" />
                    <f:ComboBox Header="Sample Type"
                                ItemsSource="{Binding Source={StaticResource SampleType}}"
                                SelectedValue="{Binding Source={x:Static l:TiffDocumentViewModelOptions.Options}, Path=DefaultSampleType}" />
                </f:RibbonGroupBox>

or

                <f:RibbonGroupBox Header="Sample"
                                  Grid.IsSharedSizeScope="True">
                    <f:ComboBox Header="Interpolation Type"
                                Grid.IsSharedSizeScope="True"
                                ItemsSource="{Binding Source={StaticResource InterpolationType}}"
                                SelectedValue="{x:Static l:Tiff16BitMetaData.DefaultInterpolationType}" />
                    <f:ComboBox Header="Sample Type"
                                Grid.IsSharedSizeScope="True"
                                ItemsSource="{Binding Source={StaticResource SampleType}}"
                                SelectedValue="{Binding Source={x:Static l:TiffDocumentViewModelOptions.Options}, Path=DefaultSampleType}" />
                </f:RibbonGroupBox>

I removed the Button AutoUpdate and It didn't work.
Thank you.
![cccc](https://user-images.githubusercontent.com/19511177/35190535-f233a8a0-fe9e-11e7-8511-71582e36b82b.PNG)

**Comment by batzen** [comment]
It currently doesn't work because the code is only on my machine right now.
The first code sample you posted would be the correct one.

Will write some unit tests for the new feature and then push my changes later today so you can try it out.

**Comment by TruePluto** [comment]
It will be featured next version . that's woundful. thank you.

**Comment by batzen** [comment]
The feature will be in version 6, which is the next one.

One thing i did not understand is how you would like to align ToggleButton in this context.
Could you explain that a bit more?

**Comment by batzen** [comment]
Ok. The general layout for controls in the ribbon is 
`[Icon] [Header] {[Control]}`

The feature i am adding aligns controls that have an additional control to the right. These controls are `Spinner` and `ComboBox`.

Something like the control displaying the status in your screenshot is not part of this library.

To get exactly what you want you can, instead of adding the controls separately, just add a `Grid` to the `RibbonGroupBox` and layout the controls you add to it excatly in the way you want them. The only things you loose by doing so are things like automatic resizing.

**Comment by TruePluto** [comment]
I would like to make the ToggleButton  out of the column. I just hope the fluent:control with ICON header control can be aligned. so I think I can get it at next version. wounderful
thanks.

**Comment by batzen** [comment]
Documentation can be found at http://fluentribbon.github.io/documentation/concepts/sizing#aligningControls
