### ISSUE TITLE
titlebar or statusbar background

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#496]
How can I change the background of the titlebar or the statusbar?
I am looking for a small example but cant find any.

---
### Environment

- Fluent.Ribbon __v6.0.0.0
- Windows 7
- .NET Framework 4.5

**Comment by batzen** [comment]
You can change the background of `StatusBar` by either setting it's `Background` property or by overwriting the resource `Fluent.Ribbon.Brushes.AccentBaseColorBrush`. Overwriting `Fluent.Ribbon.Brushes.AccentBaseColorBrush` however will cause that color/brush to be overwritten everywhere.

You can change the background of the titlebar by setting `TitleBackground` on `RibbonWindow`.

**Comment by bochelie1000** [comment]
I tried many things, but nothing works. 
this.TitleBar.Background = Brushes.Red; doesnt work.
TitleBackground ="Red" in xaml doenst work.

I want to be able to change it dynamicaly.

**Comment by batzen** [comment]
The showcase application contains samples for almost everything that is supported by this project.

If you want to help, feel free to improve the documentation which lives at https://github.com/fluentribbon/fluentribbon.github.io i am very bad writing documentation and really could need a helping hand. ;-)

Glad i could help.

**Comment by bochelie1000** [comment]
Alright, I will give it a look and see if can help.
