### ISSUE TITLE
Can Searchbox added to Ribbon control?

### ISSUE THREAD

**Issue by tsgd84** [fluentribbon/Fluent.Ribbon#497]
I would want to add a search text box to the ribbon control adjacent to QuickAccessToolBar.
Is it possible to do it? If not, consider it as an enhancement.

**Comment by batzen** [comment]
You mean on the left side of the window? That's currently only possible by adding items to the `QuickAccessToolBar` itself.
However you can add items to the right side by either adding items to `Ribbon.ToolBarItems` (that would place the items to right of the minimize ribbon button) or by adding items to `RibbonWindow.WindowCommands` (that would place the items to the left of the minimize etc. buttons).

**Comment by batzen** [comment]
@tsgd84 Does that answer your question/request?

**Comment by tsgd84** [comment]
yes Sir, that should be helpful. 
Thanks for the help!
