### ISSUE TITLE
KeyTip available for disabled items

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#499]
Consider a disabled ribbon tab (or entire ribbon for that matter):
`<fluent:RibbonTabItem Header="Home" KeyTip="H" IsEnabled="{Binding IsOnline,Converter={StaticResource BooleanToVisibilityConverter}}">`

When I press Alt+H it should not display the key tip. More specifically, it should not allow me to change the active tab!
---
### Environment

- Fluent.Ribbon __v6.0.0-dev0171
- Windows 10
- .NET Framework 4.5.1

**Comment by batzen** [comment]
Can't reproduce your issue using the showcase application.
If the code you posted here is the code you are using it might be possible that your converter is just wrong.
Trying to bind bool, converted to visibility, to a bool property should just fail and do nothing.

**Comment by znakeeye** [comment]
Ah, darn! :) Using a correct binding it works.
