### ISSUE TITLE
Mousewheel for spinner

### ISSUE THREAD

**Issue by TruePluto** [fluentribbon/Fluent.Ribbon#505]
I found that fluent:spinner could not increase or decrease when i roll the mousewheel. 

so I extended the control  with the following code
```

 public class SpinnerEx : Spinner
    {
        [SuppressMessage("Microsoft.Design", "CA1062", MessageId = "0")]
        protected override void OnMouseWheel(MouseWheelEventArgs e)
        {
            base.OnMouseWheel(e);
            Value += (e.Delta / 120) * Increment;
        }
    }

```
  
But i think the control Spinner could implement the feature by itself . 
sorry for my disturbing.

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
