### ISSUE TITLE
ItemTemplate for a DropDownButton is in the wrong place

### ISSUE THREAD

**Issue by MajedDH** [fluentribbon/Fluent.Ribbon#506]
I've attached items to `ItemsSource` of `DropDownButton` using Binding, then used `ItemTemplate` to customize the items inside the popup.
when the drop down popup is visible, my ItemTemplate is inside the` Header ` of the `MenuItem`.

Shouldn't the `ItemTemplate` replace the whole `MenuItem` inside the   `DropDownButton`'s popup?

**Comment by batzen** [comment]
It behaves the same as, for example, a regular ListBox or Menu. To avoid this you have to use ItemContainerStyle.

I wish microsoft would provide a better way to deal with this kind of stuff.

**Comment by batzen** [comment]
It's asked and explained here https://stackoverflow.com/questions/29130567/wpf-contextmenu-itemtemplate-menuitem-inside-menuitem

**Comment by batzen** [comment]
@MajedDH Does that answer your question?

**Comment by batzen** [comment]
@MajedDH Does that answer your question?
