### ISSUE TITLE
Checked mark + Icon image at Menuitem

### ISSUE THREAD

**Issue by softinus** [fluentribbon/Fluent.Ribbon#509]
is it possible to show checked mark + icon image at Menuitem somehow?
I wanted to highlight the checked Menuitem which belongs to DropdownButton.
But the menuitem has icon property too. so, what I expected was like this.. 

Please refer to this screenshot, it's a capture program called picpick. I don't know what environment they adopt.
![untitled](https://user-images.githubusercontent.com/4496005/35549067-f2d5548c-05c6-11e8-9376-8d18af4cb878.png)

So I'd like to know there's any way to implement this way..
thank you :)

For reference, here's the code snippet I've tried.
 
    <Fluent:DropDownButton ...>
    <Fluent:MenuItem Header="menu1"
        IsChecked="{Binding IsCurrentControlStrokeFilled, Converter={StaticResource  BoolInverterConverter}}"
     IsCheckable="True" 
    Icon="./Resources/Images/icons8-unavailable-24.png"/>
    ...
    </Fluent:DropDownButton>

---
### Environment

- Fluent.Ribbon 5.0.2.46
- Windows 10.1709
- .NET Framework 4.5

**Comment by batzen** [comment]
Can't view the image. Page seems unavailable. You should be able to drag and drop the image directly in an comment or the issue itself.

**Comment by batzen** [comment]
Ah, now i get it.

You want the icon to represent the check state instead of a separate checkbox?
If that is what you want i will try to come up with something like that.

**Comment by batzen** [comment]
Like this:
![menuitemcheckedimage](https://user-images.githubusercontent.com/1971030/35767144-ac0dbe2c-08e6-11e8-95e5-de8a8ea4e31e.png)
