### ISSUE TITLE
Organize ribbon xaml file

### ISSUE THREAD

**Issue by cbytte** [fluentribbon/Fluent.Ribbon#51]
Our ribbon starts to have many tabs, containing many controls.
As a consequence the ribbon xaml is endless, thwarting easy navigation or search.

It would be ideal if the big xaml could be split into multiple xaml files, but alas...
Or have I missed an efficient way to organize the ribbon xaml ?

**Comment by batzen** [comment]
You could create separate controls which inherit from RibbonTabItem and use those.

**Comment by batzen** [comment]
Did that answer your question?

**Comment by cbytte** [comment]
I guess so, thank you for this good idea!
Going to try that out.
