### ISSUE TITLE
Submenus in DropDownButton are not opened each time

### ISSUE THREAD

**Issue by nicwe** [fluentribbon/Fluent.Ribbon#510]
If you use an application menu with submenus, the submenus will not open each time you move the mouse to the parent menuitem.

Steps to reproduce:

1. Start the showcase application
2. Switch to the application menu (not backstage)
3. Open the application menu
4. Move the mouse to the "File" menu (the submenu will open)
5. Move the mouse over the opened submenu to a free position in the window (not ribbon menu)
6. Click with the mouse to close the application menu
7. Open the application menu again
8. Move the mouse to the "File" menu (the submenu will NOT open)

- If you repeat the steps you will see that every second time the submenu will not be opened.
- In case the submenu will not opened, you can hover over some other menu items, then it will work.

Environment

- Fluent.Ribbon v6.0.0
- Windows 10
- .NET Framework 4.0

**Comment by batzen** [comment]
This not only affects `ApplicationMenu`. It affects every control in this library inheriting from `DropDownButton`.
