### ISSUE TITLE
Ideal text color should match the colors in the ribbon

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#512]
![image](https://user-images.githubusercontent.com/1246444/35636298-05d41934-06b1-11e8-9789-78b6ae370b23.png)

---
### Environment

- Fluent.Ribbon v6
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Which accent color did you choose?
It looks like orange/amber and on my machine the foreground for that is white, not black.

You are however correct, the arrow does currently not use the ideal foreground. Will change that.

**Comment by GeertvanHorrik** [comment]
It's working as expected (except that the arrow should also respect the ideal text color). I have worked around this by allowing to force the ideal text color manually in Orchestra.

**Comment by batzen** [comment]
Ok, so it's just the arrow color.

Will be fixed. ;-)
