### ISSUE TITLE
Hovering causes flickering of ribbon backstage menu items

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#513]
Note that this could be caused by my "wrong" transition to Fluent.Ribbon 6.0, but I think the content should always be transparent so the "open" text won't flicker.

![fluent_ribbon_hover](https://user-images.githubusercontent.com/1246444/35636462-799a4578-06b1-11e8-91c7-4180ed84b62a.gif)

---
### Environment

- Fluent.Ribbon 6
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Strange. Hovering over the button causes `IsMouseOver` on the `BackstageTabItem` to trigger...
