### ISSUE TITLE
Add options to hide the row containing RibbonTabItems

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#516]
If you don't have enough buttons to warrant having two tabs, can you remove the tab bar entirely? Both the "minimal window" example and the basic setup have the tab bar in there, so it seems like you can't. I also tried putting the RibbonGroupBox directly inside the Ribbon element but that didn't work. I also poked around on the Ribbon control and didn't see any obvious properties to hide it. If it's not possible, could this scenario be supported?

---
### Environment

- Fluent.Ribbon 6.0.0.208
- Windows 10 Fall Creator's Update
- .NET Framework 4.6.2

**Comment by batzen** [comment]
There is currently no built in way to achieve what you describe.
What would you suggest should happen to the menu (backstage)? The button to open it is in the same visual row as the tabs are.

**Comment by RandomEngy** [comment]
I wouldn't need the backstage either...

**Comment by batzen** [comment]
Ok. Will have a look during the next few days.

**Comment by batzen** [comment]
You will, as soon as i push my changes (most likely tomorrow), be able to hide the complete row showing the tab headers by:
- Setting `Ribbon.Menu` to `null` (or never assigning anything)
- Setting `Ribbon.CanMinimize` to `false`
- Setting `Ribbon.AreTabHeadersVisible` to `false`
- Setting `Ribbon.IsToolBarVisible` to `false`
