### ISSUE TITLE
Fluent 6.0: buttons inside drop downs don't seem to work when using ClosePopupOnMouseDown

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#517]
We have this issue now in a component we haven't changed in a while. Not sure if this is being caused by Fluent 6.0, will investigate and fill up this ticket.

**Comment by GeertvanHorrik** [comment]
I think I introduced this in #5

**Comment by GeertvanHorrik** [comment]
I disabled hiding for now, as you can see the buttons don't respond to anything. Will try to investigate why.

![fluent_ribbon_button_issue](https://user-images.githubusercontent.com/1246444/35922082-e61f4f3e-0c1c-11e8-9051-cc5896df5983.gif)

**Comment by GeertvanHorrik** [comment]
Can repro in the Fluent.Ribbon example repository.

**Comment by GeertvanHorrik** [comment]
See #520 for further details.

**Comment by batzen** [comment]
Removing ClosePopupOnMouseDown seems to work on my machine.
Will have a look at why ClosePopupOnMouseDown prevents the click from reaching the button.

**Comment by batzen** [comment]
It's caused by cccc1ca54b381268c2d4cc08b8a04cfd06e7dd10 and `e.Handled = false`.
Removing `e.Handled = false` fixes the issue.

**Comment by GeertvanHorrik** [comment]
Very weird, this code has always worked for us, but will test now.

**Comment by GeertvanHorrik** [comment]
Fix confirmed. Do you have an ETA for 6.1?

**Comment by batzen** [comment]
Maybe during the weekend.
Highly depends on how many issues are found till then. ;-)
