### ISSUE TITLE
Why .NET 4.6.2 and not just 4.6.0?

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#519]
Just curious, is there a reason why it uses .NET 4.6.2? I don't think this is a requirement for the lib and unnecessarily restricts the number of target fx's that can use this lib?

**Comment by batzen** [comment]
Did this because DPI-support in 4.6.2 got improved a lot and it would mean having even more projects.
Will reconsider this when #515 is done. Then it's only a "net46" more.

**Comment by GeertvanHorrik** [comment]
I think that only affects the actual app and which platform the app that uses Fluent.Ribbon targets? Or did you use .NET 4.6.2 explicit API calls?

**Comment by batzen** [comment]
Fluent.Ribbon does not call 4.6.2 apis but ControlzEx does.

**Comment by batzen** [comment]
@GeertvanHorrik Do you need a dedicated .NET 4.6 version of Fluent? I guess everything depending on Fluent and targeting .NET 4.6 just falls back to the .NET 4.5 version doesn't it?

**Comment by GeertvanHorrik** [comment]
Not really, but I choose to put all the libs for .net 4.6 on .net 4.6, so the app keeps in charge what version to target, so was just wondering why you chose 4.6.2

**Comment by batzen** [comment]
Ok. Then i won't release a dedicated version for .NET 4.6 as there's no benefit in doing so ;-)
