### ISSUE TITLE
Consider using shared projects instead of using the same files inside each project file

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#521]
Shared projects allows you to create a single "project" that contains all the files. This way, if you add a new file, you only have to add it once for all the target frameworks.

Happy to PR if you wish.

**Comment by batzen** [comment]
I got an even better solution for that in progress. Have a look at the sdk-csproj branch.

**Comment by batzen** [comment]
Duplicate of #515

**Comment by GeertvanHorrik** [comment]
Great, then it will work just fine :)
