### ISSUE TITLE
[Q] How can I change the localization?

### ISSUE THREAD

**Issue by softinus** [fluentribbon/Fluent.Ribbon#523]
It seems the localization file loads from "CultureInfo.CurrentUICulture" automatically.
is there any way to set this forcibly to specific local?

---
### Environment

- Fluent.Ribbon 5.0.2.46
- Windows 10.1709
- NET Framework 4.5

**Comment by batzen** [comment]
RibbonLocalization.Current.Localization = new German(); should work. Will add documentation for that during the next days.

**Comment by softinus** [comment]
@batzen There's one translation mistake in Korean class.
 
    public override string Automatic { get; } = "자동 번역";

should be
 
    public override string Automatic { get; } = "자동";

Every other look fine.

**Comment by batzen** [comment]
Good catch.
Even one line PRs are appreciated. ;-)

**Comment by softinus** [comment]
#524 Here is the PR.
