### ISSUE TITLE
Open a Help File to a "specific" page/window if selecting a RibbonBackstageTabItem

### ISSUE THREAD

**Issue by Aitania** [fluentribbon/Fluent.Ribbon#526]
Hallo,
is there an event when selecting a RibbonBackstageTabItem?
I want so display a chm file inside of the TabItem (that's easier) or better in a separate Window.
But i don't want to create a Button in content of TabItem wit a command. Just one icon makes no sense.

Regard,
Michael

Environment
- Windows 7
 - <package id="Fluent.Ribbon" version="5.0.2.46" targetFramework="net46" />

**Comment by batzen** [comment]
Inside `Backstage` you have `BackstageTabControl` which inherits from `Selector` so you got the event `BackstageTabControl.SelectionChanged`.

Does that answer your question?

**Comment by Aitania** [comment]
Yep!  Thank you...
