### ISSUE TITLE
Key tip for contextual tab does not work

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#528]
**If you have the same key tip - e.g. "F" - for a contextual tab as a regular tab, only the regular tab responds.** As far as I know it should show "FF" for the second occurrence (the contextual tab I guess).

---
### Environment

- Fluent.Ribbon __v6.0.0.208__
- Windows __10__
- .NET Framework __4.5.1__

**Comment by batzen** [comment]
There is no duplicate detection included in Fluent.Ribbon.
You have to avoid duplicates manually.

> As far as I know it should show "FF" for the second occurrence

Were did you get to know that?

**Comment by znakeeye** [comment]
Ah, makes sense! Consider it a feature request :P
