### ISSUE TITLE
How to change default height of a MenuItem?

### ISSUE THREAD

**Issue by ncksol** [fluentribbon/Fluent.Ribbon#531]
I am trying to modify the default height of a MenuItem. I have found the style named FluentDefaultSystemMenuItemStyle which I assume is used by all the MenuItems. But adding a simple setter with height does nothing. 
Is there something I am missing?

---
### Environment

- Fluent.Ribbon v6.1.0
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
There are different styles for MenuItem and even more ControlTemplates for MenuItem.
Setting the height on the style should work as you expect.

How did you try to set your height on the style and where did you place your style?

**Comment by ncksol** [comment]
I have copied FluentDefaultSystemMenuItemStyle from source code and added extra margin around textblock that is placed into the Header Template like this:
` 

    <Style x:Key="FluentDefaultSystemMenuItemStyle" TargetType="{x:Type MenuItem}">
    <Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto" />
    <Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Hidden" />
    <Setter Property="Background" Value="{DynamicResource Fluent.Ribbon.Brushes.MenuItem.Background}" />
    <Setter Property="Foreground" Value="{DynamicResource {x:Static themes:ResourceKeys.MainTextGreyBrush}}" />
    <Setter Property="Template" Value="{DynamicResource MenuItemTemplate}" />
    <Setter Property="HeaderTemplate">
      <Setter.Value>
        <DataTemplate>
          <TextBlock Text="{Binding}" Margin="0 4" />
        </DataTemplate>
      </Setter.Value>
    </Setter>
    <Style.Triggers>
      <MultiTrigger>
        <MultiTrigger.Conditions>
          <Condition Property="fluent:MenuItem.IsSplited"
                               Value="True" />
          <Condition Property="HasItems"
                               Value="True" />
        </MultiTrigger.Conditions>
        <Setter Property="Template"
                        Value="{DynamicResource SplitedMenuItemTemplate}" />
      </MultiTrigger>
      <MultiTrigger>
        <MultiTrigger.Conditions>
          <Condition Property="fluent:MenuItem.IsSplited"
                               Value="False" />
          <Condition Property="HasItems"
                               Value="True" />
        </MultiTrigger.Conditions>
        <Setter Property="Template"
                        Value="{DynamicResource HeaderMenuItemTemplate}" />
      </MultiTrigger>
      <DataTrigger Binding="{Binding Description, RelativeSource={RelativeSource Self}, Converter={x:Static fluent:IsNullConverter.Instance}}"
                         Value="False">
        <Setter Property="Template"
                        Value="{DynamicResource MenuItemWithDescriptionTemplate}" />
        <Setter Property="HeaderTemplate">
          <Setter.Value>
            <DataTemplate>
              <TextBlock Text="{Binding}"
                                       FontWeight="Bold" />
            </DataTemplate>
          </Setter.Value>
        </Setter>
      </DataTrigger>
    </Style.Triggers>
    </Style>
`

**Comment by ncksol** [comment]
So I have found that if I add the following to my RD the style is applied correctly:
`<Style TargetType="{x:Type fluent:MenuItem}" BasedOn="{StaticResource FluentDefaultSystemMenuItemStyle}" />`

But I've also noticed that if I have a ContentTemplate for MenuItem in that same RD, then the style is not applied to those MenuItems which Template I have overridden. Most peculiar.

**Comment by batzen** [comment]
How are you trying to set the template?

**Comment by ncksol** [comment]
I have the ControlTemplate named "MenuItemTemplate" in my custom ResourceDictionary. 
Weird thing is - after I went back to the code a day later it works.
All I needed to add is add the style FluentDefaultSystemMenuItemStyle to my RD and set Height. I also needed to put 
`<Style TargetType="{x:Type fluent:MenuItem}" BasedOn="{StaticResource FluentDefaultSystemMenuItemStyle}" />`

in the same RD.

**Comment by batzen** [comment]
So everything is working for you now?

**Comment by ncksol** [comment]
It does yeah. Thanks!
