### ISSUE TITLE
suggestion: add MAT

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#532]
Maybe you can add Microsoft MAT to manage all the projects localizations. It's a great tool, easy to maintain and it gives you a great view of how many strings you still need to localize per language.
https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308 

(+ how to convert existing resources to xlif: https://blogs.msdn.microsoft.com/matdev/2016/04/22/published-resxtoxliff-converter-project-on-github/ )

**Comment by batzen** [comment]
According to the reviews it slows down visual studio horribly...
Fluent.Ribbon doesn't even use resx files, but pure code for it's localization.

Thank you for your suggestion, but i can't see the benefit of introducing yet another tool to manage something that changes like once in 5 years 😉

**Comment by wstaelens** [comment]
here it doesn't seem to slowdown anything.

@resx, resw, whatever files used: ok I was only a suggestion. It could be easier for other to add new languages at a faster rate.

**Comment by batzen** [comment]
You mean easier than copying https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Localization/Languages/English.cs and translating it?

**Comment by wstaelens** [comment]
Yes, because it also keeps track if the original source string changed or not. This is something that normal separate translate files don't show or do

**Comment by batzen** [comment]
Ok. Didn't know it also does that.
But i currently don't see the benefit for this project as there are not even 30 strings being localized. ;-)
