### ISSUE TITLE
Issue when using templated ribbon items.

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#533]
I have a problem when using DataTemplates for Ribbon Controls. I basically want to define the buttons in a ViewModel and  add those programmatically to the ItemsSource of the RibbonGroupBox.

`  <Fluent:RibbonWindow.Resources>
    <ResourceDictionary>
      <DataTemplate DataType="{x:Type local:ButtonViewModel}">
        <Fluent:Button SizeDefinition="{Binding SizeDefinition}" Header="{Binding Header}"/>
      </DataTemplate>
    </ResourceDictionary>
  </Fluent:RibbonWindow.Resources>
`
The simplified VM looks like this:

`  public class ButtonViewModel
  {
    static int id = 0;

    public ButtonViewModel()
    {
      ID = "Button_" + id++;
    }

    public string ID { get; }

    public RibbonControlSizeDefinition SizeDefinition
    {
      get { return new RibbonControlSizeDefinition(RibbonControlSize.Large, RibbonControlSize.Middle, RibbonControlSize.Small); }
    }

    public string Header => ID;
  }
`

Generally it works, but the SizeDefinition is not considered. When I reduce the size of my window, the status of each group always changes directly from Large to Collapsed. 

Attached is a sample project.

[WpfFluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1738097/WpfFluentTest.zip)

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.5

**Comment by pschimmel** [comment]
I assume the problem lies in the SetSize method in RibbonProperties. When the size of a group is changed the element is a ContentPresenter.

The code 
`        public static void SetSize(DependencyObject element, RibbonControlSize value)
        {
            element.SetValue(SizeProperty, value);
        }`
Tries to set the Size property of the ContentPresenter, but on the ContentPresenter itself there is no such property.

Probably my DataTemplate approach is wrong.

**Comment by batzen** [comment]
Will try to have a look at this sometime during this week. MVVM support is not as good as it probably could be.

**Comment by pschimmel** [comment]
Hi!
Thank you for adding the fix to the 7.0.0 milestone. 
Unfortunately I discovered some more problems concerning the use of data templates.

When I use the same example and add a KeyTip property to the ViewModel and use data binding in the data template as before, I get an exception in RibbonGroupBoxWrapPanel.

`KeyTip="{Binding KeyTip}`

When I change the data template, that it uses an attached property

`Fluent:KeyTip.Keys="{Binding KeyTip}"`

There is no exception, but also no KeyTips shown.

I could track down that problem to the GetVisibleChildren implementation in the KeyTipAdorner. Using a VisualTreeHelper instead of the LogicalTreeHelper to find the children might work, but is probably too expensive.

**Comment by pschimmel** [comment]
Updated test project here:

[WpfFluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1811486/WpfFluentTest.zip)
