### ISSUE TITLE
Overriding Text Color on Mouse Over on RibbonTabItem

### ISSUE THREAD

**Issue by scauthen** [fluentribbon/Fluent.Ribbon#534]
I am having trouble styling the text color when a RibbonTabItem is hovered over. I have used styles to redefine several items on the Ribbon. How can I change the text color on hover to say White or another light color?
Thank you very much for your time!

```javascript
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.Background" Color="Transparent" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.Content.Background" Color="#f1f1f1" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.Content.BorderBrush" Color="Red" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.Content.Foreground" Color="Black" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.TabsGrid.Background" Color="#2b579a" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabControl.TabsGrid.Foreground" Color="Black" />

<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.Foreground" Color="White"  />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush" Color="#2b579a" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.Active.Background" Color="#f1f1f1" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Background" Color="#4067a4" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.BorderBrush" Color="#2b579a" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground" Color="#2b579a"  />
```
![menu-tab-wrongcolor](https://user-images.githubusercontent.com/970229/36502582-4f16b524-1742-11e8-92b5-6178dd23d08e.png)

If you have answered this previously, I apologize. I could not find it addressed.

---
Environment

- Fluent.Ribbon v6.1.0.233
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
There is a trigger which prevents you from overriding it the way you tried it.

Can try it right now, but the following should to the job:
```
<Style x:Key="{x:Type Fluent:RibbonTabItem}"
       TargetType="{x:Type Fluent:RibbonTabItem}">
    <Setter Property="Fluent:RibbonProperties.MouseOverForeground"
            Value="{DynamicResource Fluent.Ribbon.Brushes.HighlightBrush}" />
</Style>
```

If above does not work, a trigger on your style having the same setter should work.
If that also does not work, you definitely have to set the attached property `Fluent:RibbonProperties.MouseOverForeground` on the `RibbonTabItem` somehow.

**Comment by scauthen** [comment]
Thank you for the help. I was able to override it using the following code:
``

**Comment by batzen** [comment]
Please note that you might get problems with this when switching from BaseLight to BaseDark colors or vice versa.
