### ISSUE TITLE
BorderBush on bottom of RibbonTabItem (and Ribbon)

### ISSUE THREAD

**Issue by scauthen** [fluentribbon/Fluent.Ribbon#535]
I am trying to create a menu without the border on the top and bottom. In order to keep the Tab at the from having small notches (extension lines) at the bottom (see first image), I used the following Resource Style. This works great in removing the notches at the bottom however, how I have a border at the bottom which I would like to remove. Is this possible? Could you please advice? 
Thank you so much for your time!

``
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush" Color="#2b579a" />
``

Without Border:
![noborder](https://user-images.githubusercontent.com/970229/36503089-e8e0c86a-1743-11e8-9d4c-be3a4143c410.png)

With Border:
![withborder](https://user-images.githubusercontent.com/970229/36503083-e5590a9a-1743-11e8-830d-bf855c36cc2b.png)

---
### Environment

- Fluent.Ribbon V6.1.0.233
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Those notches shouldn't even be there.
Will have a look at this as soon as i got time.

**Comment by scauthen** [comment]
I found a work around by using the following code. Basically, I set the BorderBrush to White which matches the window area below the ribbon and then set the SolidBrushColor on the RibbonTabItem to the color of my Ribbon background.

```
<Style TargetType="{x:Type Fluent:RibbonTabItem}">
        <Setter Property="Height" Value="30" />
        <Setter Property="BorderThickness" Value="1,1,1,1" />
        <Setter Property="BorderBrush" Value="White" />
</Style>
```
```
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush" Color="{DynamicResource ColorDark}" />
```
Thank you for the quick response!
