### ISSUE TITLE
How to set up Backstage

### ISSUE THREAD

**Issue by JohnyL** [fluentribbon/Fluent.Ribbon#538]
I could not find information about what Backstage can consist of and appropriate XAML. For instance, on [Screenshots](https://github.com/fluentribbon/Fluent.Ribbon/wiki/Screenshots) page there's a screenshot of Backstage, but no XAML how to achieve. I tried the code from [documentation](http://fluentribbon.github.io/documentation/controls/ribbon), but see no triangle when using that XAML. It's a pity that such excellent tool has poor documentation.

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10 Home Edition
- .NET Framework 4.7.1

**Comment by batzen** [comment]
You don't see a triangle because there is none. I was removed years ago. Will remove those old screenshots and add some new to the documentation.

Backstage is, more or less, a restyled tabcontrol. So i can consist of everything you like. Almost all features of Fluent.Ribbon are shown in the showcase application.

And yes, documentation is poor... As i am the only maintainer of this project and i also have a few more projects it's kind of difficult...

**Comment by batzen** [comment]
You can find the sources at https://github.com/fluentribbon/Fluent.Ribbon/tree/develop/Fluent.Ribbon.Showcase and the compiled version can be downloaded from releases.

**Comment by JohnyL** [comment]
@batzen Bastian, thanks for link, but when I run the solution, I get lots of errors. Particularly, in Dependencies node the ".NET Framework 4.5" and ".NET Framework 4.6.2" are with yellow triangle. Later I will post all errors.

**Comment by batzen** [comment]
You need Visual Studio 2017 to compile the solution. Just in case you are trying it with Visual Studio 2015.

**Comment by JohnyL** [comment]
I have latest version of Visual Studio: 15.6.0 Preview 6.0. All I did is deleted `Tests`. Everything else is untouched. Here are screenshots. .NET Frameworks are installed.
![FLUENT_RIBBON_NET_FRAMEWORK](https://i.imgur.com/XAtxYsm.png)
![FLUENT_RIBBON_ERRORS](https://i.imgur.com/dSIJLGn.png)

**Comment by batzen** [comment]
Could you try to use the build script "build.ps1" and see if it works? If it works studio should be happy too.

**Comment by JohnyL** [comment]
I get error (script was run under unrestricted group policy):
```
Preparing to run build script...
The request was aborted: Could not create SSL/TLS secure channel. (Github - cached (temporarily ignore updates))
Resolve-Path : Cannot find path 'C:\Users\Sektor\Downloads\Fluent.Ribbon-develop\packages\cake\Cake' because it does not exist.
At C:\Users\Sektor\Downloads\Fluent.Ribbon-develop\Build.ps1:154 char:12
+ $CakeDir = Resolve-Path $Cake
+            ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Sektor...kages\cake\Cake:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Sektor\Downloads\Fluent.Ribbon-develop\Build.ps1:155 char:23
+ $CAKE_EXE = Join-Path $CakeDir "Cake.exe"
+                       ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Sektor\Downloads\Fluent.Ribbon-develop\Build.ps1:156 char:17
+ if (!(Test-Path $CAKE_EXE)) {
+                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Running build script...
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a
 CommandInfo object.
At line:1 char:3
+ & "" "build.cake" -target="Default" -configuration="Release" -verbosi ...
+   ~~
    + CategoryInfo          : InvalidOperation: (:String) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression
```

**Comment by batzen** [comment]
Oh. I have to update cake because github changed allowed ssl/tls things. Will reply here as soon as i updated it.

**Comment by JohnyL** [comment]
Thanks! :)

**Comment by batzen** [comment]
Updated. Wasn't cake but paket instead. Should work again now.

**Comment by JohnyL** [comment]
Errors :(

> Preparing to run build script...
> Paket version 5.145.6
> Performance:
>  - Runtime: 1 second
> Running build script...
> INFO [02/27/18 21:10:13:53] Working directory: C:\Users\Sektor\Downloads\Fluent.Ribbon-develop
> INFO [02/27/18 21:10:13:53] IsDynamicGitRepository: False
> ERROR [02/27/18 21:10:13:56] An unexpected error occurred:
> System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\Users\Sektor\Downloads\Fluent.Ribbon-develop
>    at GitVersion.GitPreparer.GetDotGitDirectory()
>    at GitVersion.GitPreparer.GetProjectRootDirectory()
>    at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
>    at GitVersion.Program.VerifyArgumentsAndRun()
> INFO [02/27/18 21:10:13:56]
> INFO [02/27/18 21:10:13:56] Attempting to show the current git graph (please include in issue):
> INFO [02/27/18 21:10:13:56] Showing max of 100 commits
> INFO [02/27/18 21:10:13:57] Could not execute 'git log' due to the following error:
> System.IO.FileNotFoundException: The executable file 'git' could not be found.
> File name: 'git' ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
>    at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
> 
> INFO [02/27/18 21:10:13:53] Working directory: C:\Users\Sektor\Downloads\Fluent.Ribbon-develop
> INFO [02/27/18 21:10:13:53] IsDynamicGitRepository: False
> ERROR [02/27/18 21:10:13:56] An unexpected error occurred:
> System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\Users\Sektor\Downloads\Fluent.Ribbon-develop
>    at GitVersion.GitPreparer.GetDotGitDirectory()
>    at GitVersion.GitPreparer.GetProjectRootDirectory()
>    at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
>    at GitVersion.Program.VerifyArgumentsAndRun()
> INFO [02/27/18 21:10:13:56]
> INFO [02/27/18 21:10:13:56] Attempting to show the current git graph (please include in issue):
> INFO [02/27/18 21:10:13:56] Showing max of 100 commits
> INFO [02/27/18 21:10:13:57] Could not execute 'git log' due to the following error:
> System.IO.FileNotFoundException: The executable file 'git' could not be found.
> File name: 'git' ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
>    at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
> 
> Error: One or more errors occurred.
>         GitVersion: Process returned an error (exit code 1).

**Comment by batzen** [comment]
If you want to build you have to clone the repo using git instead of downloading the sources as a zip file.

**Comment by JohnyL** [comment]
Beg your pardon, but I'm not that advanced with Git. As I understood, I installed GitHub Desktop and pressed "Open in Desktop" (when pressing green button "Clone or download"). After cloning it, I again run Build.ps1. Now I get the following errors (I feel that the success is close to me):

> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> Build started 27.02.2018 23:28:32.
> Project "C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln" on node 1 (restore target(s)).
> ValidateSolutionConfiguration:
>   Building solution configuration "Release|Any CPU".
> C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln.metaproj : error MSB4057: The target "restore" does not exist in the project.
> [C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln]
> Done Building Project "C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln" (restore target(s)) -- FAILED.
> 
> Build FAILED.
> 
> "C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln" (restore target) (1) ->
>   C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln.metaproj : error MSB4057: The target "restore" does
> not exist in the project. [C:\Users\Sektor\Documents\GitHub\Fluent.Ribbon\Fluent.Ribbon.sln]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.57
> An error occurred when executing task 'Restore'.
> Error: One or more errors occurred.
>         MSBuild: Process returned an error (exit code 1).

**Comment by batzen** [comment]
It's not your fault. I just switched to cake and VS2017 recently.
Could try to a "dotnet restore" in the Fluent.Ribbon directory?

**Comment by batzen** [comment]
I meant the directory where the Fluent.Ribbon.sln is located.

**Comment by JohnyL** [comment]
_dotnet restore_ worked!! Thanks! :) But running Build.ps1 generates same error. :(

**Comment by JohnyL** [comment]
I tried all tests (on "Tests" tab). _Open Ribbon-Window (new Thread)_ and _Open Ribbon-Window (with background image_ crashed app. :(

**Comment by batzen** [comment]
Yeah, those ones crash. Will have a look.

**Comment by batzen** [comment]
Fixed both issues just now.

**Comment by batzen** [comment]
Still don't know why you can't build using the build script.
Works on appveyor...
Maybe it's the preview version of vs2017 you are using.

**Comment by JohnyL** [comment]
But what's the connection between PowerShell script and Visual Studio? I'm asking because I really do not understand what do "paket", "cake" and "appveyor" mean (in fact, I'm not that familiar with Github). :) You told me to run either _dotnet restore_ or _build.ps1_.  The _dotnet restore_ worked well and VS successfully compiled and run it, but ps1 failed. Also, I confirm that those two buttons open windows without crash. Thanks!
And one more thing. I see that you use code styles inspectors, but can't find a way to switch it off.
Thanks for answers and help! :)

**Comment by batzen** [comment]
paket = enhanced nuget https://fsprojects.github.io/Paket/
cake = build automation system https://cakebuild.net/
appveyor = continuous integration https://www.appveyor.com/

The build script fails because it tries to make use of msbuild's ability to run "dotnet restore" by itself, thus trying to call msbuild with a restore target. Somehow this fails on your machine, even though your studio version is higher than mine. That's also the reason why studio is unable to build the project/solution standalone. Maybe the dotnet core workload is not fully installed on your machine or something changed in vs 15.6.
A manual dotnet restore helps in this case. ;-)

This project switched to the sdk-csproj format, which is not yet fully ready for WPF projects and needs some workarounds/additions to even build. Microsoft will add out of the box support for WPF with VS 16.0 i think.

**Comment by batzen** [comment]
And to get rid of the compile time rules you have to comment out the line with `CodeAnalysisRuleSet` in the Directory.build.props file.

**Comment by batzen** [comment]
@JohnyL Can we close this, or do you have further questions?

**Comment by JohnyL** [comment]
@batzen Yes, this can be closed. Thanks for answers!

**Comment by JohnyL** [comment]
@batzen One last question. I want to use DataTemplate for tab in Backstage. Since I will be using not Fluent:Button, is there a way to close Backstage with ordinary button?

**Comment by batzen** [comment]
@JohnyL You could add `PopupService.RaiseDismissPopupEvent(this, DismissPopupMode.Always);` in your click handler to close the backstage.

**Comment by JohnyL** [comment]
@batzen Thanks a lot! The question can be closed :)

**Comment by batzen** [comment]
Glad i could help.
