### ISSUE TITLE
Grouping Menu Items in DropDownButton

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#539]
Is it possible to group MenuItems added as Items of a DropDownButton?

I added connected the ItemsSource of a DropDownButton to a list of WPF MenuItems. This works perfectly to show a menu when the user clicks on the DropDownButton. Now I want to group those items similar to the "Arrange" button in PowerPoint.

When I add the following GroupStyle to the GroupStyle property of the DropDownButton, I only see the group headers, but no items.

`              <GroupStyle>
                <GroupStyle.ContainerStyle>
                  <Style TargetType="{x:Type GroupItem}">
                    <Setter Property="Margin" Value="0,0,0,5"/>
                    <Setter Property="Template">
                      <Setter.Value>
                        <ControlTemplate TargetType="{x:Type GroupItem}">
                          <Expander IsExpanded="True" Background="#FF112255" BorderBrush="#FF002255" Foreground="#FFEEEEEE" BorderThickness="1,1,1,5">
                            <Expander.Header>
                              <DockPanel>
                                <TextBlock FontWeight="Bold" Text="{Binding Path=Name}" Margin="5,0,0,0" Width="100"/>
                                <TextBlock FontWeight="Bold" Text="{Binding Path=ItemCount}"/>
                              </DockPanel>
                            </Expander.Header>
                            <Expander.Content>
                              <ItemsPresenter />
                            </Expander.Content>
                          </Expander>
                        </ControlTemplate>
                      </Setter.Value>
                    </Setter>
                  </Style>
                </GroupStyle.ContainerStyle>
              </GroupStyle>`

When I apply the same styling to a standard ListBox for example, it works perfectly.

**Comment by pschimmel** [comment]
Never mind. I was able to add the desired behavior by adding an ItemsControl to the DropDownButton. There I could use grouping.

**Comment by batzen** [comment]
Glad you found a solution. ;-)
