### ISSUE TITLE
XamlParseException in VS Designer when defining Generic Theme in UserControl

### ISSUE THREAD

**Issue by hybrid2102** [fluentribbon/Fluent.Ribbon#541]
Hi all,
I have a Ribbon inside a UserControl, wich will be loaded into a MetroWindow at runtime.
When I open my UserControl in VS, I can't see the ribbon because of the lacking of the Generic Theme.

If i add, temporary for designing purposes, the resource dictionary in my UC resources...
`<ResourceDictionary Source="pack://application:,,,/fluent;Component/Themes/Generic.xaml" />`
 The VS designer stops loading, with this message:

> "XamlParseException: Could not load file or assembly 'MyApplication, Culture=neutral' or one of its dependencies. The system cannot find the file specified."

I remember to be used to use this trick (temporary specify the generic theme in my uc) to actually see the ribbon in VS Designer some time ago, but from some time I can't use it anymore.
Any hints?
Thank you for the support and for the awesome project.

---
### Environment

- Visual Studio __2017 v15.5.7__
- Fluent.Ribbon __v6.1.0.233__
- Windows __Server 2012 R2__
- .NET Framework __4.7.1__

**Comment by batzen** [comment]
I don't use the designer at all... So i have no hints for you... Maybe someone else has an idea.

**Comment by pschimmel** [comment]
I also created a project where I put the Ribbon in a UserControl and had no problem.
When I add the ResourceDictionary to the Resources of the UserControl, as described above, and build my project, I can see the Ribbon in the designer.

To my experience WPF resources can be really painful. Just make sure that your project builds completely and that are all referenced dlls are there.

**Comment by hybrid2102** [comment]
Thanks for the hints, I will post any news.

Il giorno mer 14 mar 2018 alle ore 21:05 Patrick Schimmel <
notifications@github.com> ha scritto:

**Comment by hybrid2102** [comment]
Found a fix, apparently sometimes the "Project code" flag in VD Designer unchecks itself on its own... Enabling it seems to solve this problem.

![projectcode](https://user-images.githubusercontent.com/1963205/37451864-3b91896e-2833-11e8-946f-516816083d86.png)
