### ISSUE TITLE
InRibbonGallery not reducing properly

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#542]
Is there a way to use the InRibbonGallery the same way like the styles gallery in MS Word?
There the number of colums shown is flexible and depends on the available width.

**Comment by batzen** [comment]
It should do that "automatically" if the correct reduce order for the surrounding RibbonGroupBox is set.
Will fix the issue and add some documentation on how to achieve this.

**Comment by batzen** [comment]
@pschimmel I finally found a solution for this issue.
