### ISSUE TITLE
Using images that can't be found during design time crashes designer

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#543]
Hallo,

I tried to update from 6.0.0-dev0171 to a higher version and then I only get errrors. One of the errors I could detect is: 
Severity	Code	Description	Project	File	Line	Suppression State
Error		'ComboBox' ControlTemplate TargetType does not match templated type 'ComboBox'.		

I deleted all the Icons and now I get the Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Part URI cannot start with two forward slashes.	

After this I removed all LargeIcons and then my project starts again. However it seems like it cant find any normal icon path. 

I decided to try again and now I give the large Icon as:
LargeIcon=Images\past-48.png
This seems to work. However after debuging I still see an error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot locate resource 'images/past-48.png'.

---
### Environment

- from 6.0.0-dev0171 to higher
- Windows __7__
- .NET Framework __4.5__

**Comment by batzen** [comment]
Are your icons compiled as resource in your application assembly?

The converter which enables you to just say "iamges/myicon.png" checks if the file exists on disc, if the file is not on disc it just prepends "pack://application:,,,/" and tries to load that image.
As the images have to be sealed when being converted you get an exception if the resource could not be found.

**Comment by batzen** [comment]
If the images would not be sealed you risk this issue https://github.com/fluentribbon/Fluent.Ribbon/issues/493

**Comment by bochelie1000** [comment]
My images are on disk in my Images folder. If I use "pack://application:,,,/" in a DropDownButton which is the first control in a UserControl then it wont work either. 
I guess this is the same bug. 
I will wait until this is fixed prior to updating. 

Thanks Batzen!

**Comment by batzen** [comment]
#493 is fixed and causes your issue. You only get that error during design-time, or?

**Comment by bochelie1000** [comment]
It seems like that. As soon as the app starts the error is gone. When I stop the debug there it comes again.

**Comment by batzen** [comment]
Ok. Then in previous versions you just would have seen no icons in the designer. Will restore that behavior. Totally forgot about the designer on that one.

**Comment by batzen** [comment]
To clarify, this is a designer only issue.
How would you like the library to handle the case that an image could not be found during design time?
The options are:
- Just show no image at all
- Show a generic "missing image" image

**Comment by bochelie1000** [comment]
I think that showing a generic “missing image” will be more intuitive. Than you its a recognized error.
