### ISSUE TITLE
SplitButton.IsChecked is not bound 2 way by default

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#545]
So this is a rare use case, but an end-user wanted a toggle button with a list of "fine-grained" control. So they want a drop down (split button) where they could filter specific items, but the toggle button should toggle the state of all the filters.

I think this can easily be fixed by adding "BindsTwoWayByDefault", but not sure whether this is intended (I also had to search for the "IsCheckable" property as well before getting this to work).

**Comment by batzen** [comment]
Will align property metadata with that of ToggleButton.IsChecked.

If you discover something that's not that obvious, like "IsCheckable", feel free to contribute some documentation to the documentation repo. ;-)
I am bad a documenting... :-(
