### ISSUE TITLE
Office 2016/Office 365 Styles

### ISSUE THREAD

**Issue by frostieDE** [fluentribbon/Fluent.Ribbon#548]
I was wondering if we could implement the Office 2016 styles into FluentRibbon. Thus I started a list of controls which needs to be restyled. Also, it gives an overview on how to seperate different styles (and on how to enable styling at all). It also shows that we need some refactoring in order to enable those styles, I guess :wink:

## Colorful theme

Control | Background | Foreground
-- | -- | --
Title bar | accent brush | white
Menu button | accent brush | white
RibbonTabControl.TabsGrid | accent brush | -
RibbonTabItem (active) | #f1f1f1 (same as RibbonTabControl.Content) | accent brush
RibbonTabItem (mouse-over)| brightended accent brush | white
RibbonTabControl.Content | #f1f1f1 | black
RibbonGroupBox.Header | - | black
RibbonGroupBox Separator | #d2d2d2 | -
RibbonButton | transparent | black
RibbonButton (mouse-over) | #c6c6c6 | black
RibbonButton (clicked) | #b1b1b1 | black
Ribbon.Border (bottom only) | #d5d5d5 | -
ContextualGroup | darkened accent brush | accent brush with some transparency
Tabs withing a ContextualGroup (not active) | same darkened accent brush as Group | white
Tabs withing a ContextualGroup (mouse-over) | brightended accent brush | white
Tabs withing a ContextualGroup (active) | same as normal tabs | same as normal tabs
ApplicationMenu | #f1f1f1 (same as RibbonTabControl.Content) | black
ApplicationMenu (tabs) | accent brush | white
ApplicationMenu TabItem (active) | darkened accent brush (same as ContextualGroup) | white
ApplicationMenu TabItem (hover) | brightended accent brush (same as RibbonTabItem on mouse-over) | white

## dark gray theme

Control | Background | Foreground
-- | -- | --
Title bar | #444444 | white
Menu button | #444444 | white
RibbonTabControl.TabsGrid | #444444 | -
RibbonTabItem (active) | #b2b2b2 (same as RibbonTabControl.Content) | black
RibbonTabItem (mouse-over)| accent brush | white
RibbonTabControl.Content | #b2b2b2 | black
RibbonGroupBox.Header | - | black
RibbonGroupBox Separator | #969696 | -
RibbonButton | transparent | black
RibbonButton (mouse-over) | #969696 | black
RibbonButton (clicked) | #808080 | black
Ribbon.Border (bottom only) | - | -
ContextualGroup | #363636 | #b2b2b2
Tabs withing a ContextualGroup (not active) | #363636 (same as ContextualGroup) | white
Tabs withing a ContextualGroup (mouse-over) | accent brush | white
Tabs withing a ContextualGroup (active) | same as normal tabs | same as normal tabs
ApplicationMenu | #666666 (not same as RibbonTabControl.Content) | white
ApplicationMenu (tabs) | #262626 | white
ApplicationMenu TabItem (active) | accent brush  | white
ApplicationMenu TabItem (hover) | brightended accent brush | white

## black theme

Control | Background | Foreground
-- | -- | --
Title bar | #0a0a0a | white
Menu button | #0a0a0a | white
RibbonTabControl.TabsGrid | #0a0a0a | -
RibbonTabItem (active) | #363636 (same as RibbonTabControl.Content) | white
RibbonTabItem (mouse-over)| #363636 (same as RibbonTabItem) | white
RibbonTabControl.Content | #363636 | white
RibbonGroupBox.Header | - | white
RibbonGroupBox Separator | #666666 | -
RibbonButton | transparent | white
RibbonButton (mouse-over) | #505050 | white
RibbonButton (clicked) | #666666 | white
Ribbon.Border (bottom only) | - | -
ContextualGroup | #1e1e1e | ??
Tabs withing a ContextualGroup (not active) | #1e1e1e (same as ContextualGroup) | white
Tabs withing a ContextualGroup (mouse-over) | #363636 (same as active tab) | white
Tabs withing a ContextualGroup (active) | same as normal tabs | same as normal tabs
ApplicationMenu | #262626 | white
ApplicationMenu (tabs) | #363636 | white
ApplicationMenu TabItem (active) | accent brush  | white
ApplicationMenu TabItem (hover) | brightended accent brush | white

## white theme

Control | Background | Foreground
-- | -- | --
Title bar | white | black
Menu button | accent brush | white
RibbonTabControl.TabsGrid | white | -
RibbonTabItem (active) | white | accent brush
RibbonTabItem (mouse-over)| white | accent brush
RibbonTabControl.Content | #363636 | white
RibbonGroupBox.Header | - | black
RibbonGroupBox Separator | #e6e6e6 | -
RibbonButton | transparent | black
RibbonButton (mouse-over) | brightended accent brush | black
RibbonButton (clicked) | darkened accent brush | black
Ribbon.Border (bottom only) | #d5d5d5 | -
ContextualGroup | specified by user | specified by user
Tabs withing a ContextualGroup (not active) | (same as ContextualGroup) | black
Tabs withing a ContextualGroup (mouse-over) | (same as ContextualGroup) | (same as ContextualGroup header)
Tabs withing a ContextualGroup (active) | black | (same as ContextualGroup header)
ApplicationMenu | white | white
ApplicationMenu (tabs) | accent brush | white
ApplicationMenu TabItem (active) | darkened accent brush  | white
ApplicationMenu TabItem (hover) | brightended accent brush | white

Note: the white theme has borders around the TabItems

Disclaimer: this list is not complete and will be completed over time.

**Comment by batzen** [comment]
@frostieDE ping

**Comment by batzen** [comment]
For me "theme" equals different styles and templates for controls.

If you want to start your work the starting points would be:
- Colors.xaml (just a reference file which contains all color and brush resources)
- BaseLight.xaml and BaseDark.xaml (base color schemes, in ThemeManager these are called AppTheme)
- Accent.Template.xaml (used as a template to generate the accent resource dictionaries from GeneratorParameters.json)

- BaseLight and BaseDark contain a resource named `Fluent.Ribbon.AppTheme` which is, indirectly, used in various style triggers. This is achieved by first setting the attached property `Fluent:RibbonProperties.AppTheme` to `{DynamicResource Fluent.Ribbon.AppTheme}` and then triggering on `Fluent:RibbonProperties.AppTheme`. Most of these triggers then set some attached property like `Fluent:RibbonProperties.MouseOverForeground` and don't use a special brush in the control style for the mouse over foreground. That way we are able to use different resources based on the current "app theme". I guess you'll need to introduce a few more attached properties, judging from the list you posted above. This "workaround" is need if, for one "app theme" an accent color should be used for something and in the other an "app theme" color should be used.

If you have any questions feel free to ask them here or DM me on gitter/twitter.

**Comment by frostieDE** [comment]
Thanks, I will work on this in my spare time (which is currently not that much 😞) ;-)

**Comment by atlastodor** [comment]
Is there any progress on this issue? I tried by hand to see if this is doable, and it appears that Fluent.Ribbon already defines all the colors as resources, which are changeable. Unfortunately, there are 50+ items that will need to be modified, and if I miss any, it will look strange.

How much effort is to fix the **Showcase app** => **Tab "Styles"** tool (described in https://github.com/fluentribbon/Fluent.Ribbon/issues/447) to generate Office 2016/2019 accent styles? Alternatively, is there an accent style that was produced by hand?

**Comment by batzen** [comment]
Totally forgot to answer. There is the Colorful.Blue theme which was contributed. If you use the generator to generate the theme you don't have to change that much. I still plan to add a sync mode for the current windows accent colors. But I have no planned date for that.

**Comment by znakeeye** [comment]
So in order to mimic `Office 365` style we should use the `Colorful.Blue` theme and modify with colors listed above?

**Comment by batzen** [comment]
You could try to use that, yes.
Then you at least get something like the blue theme for Office 365.
Which other things would you need?

**Comment by frostieDE** [comment]
I really like the colorful theme, so in my opinion, this issue can be closed (even though we should add all other colors other than blue and gray) :-)
