### ISSUE TITLE
Implement RibbonGroupBox header template

### ISSUE THREAD

**Issue by Ochibooh** [fluentribbon/Fluent.Ribbon#549]
RibbonGroupBox  to have custom view. Maybe a Usercontrol

**Comment by batzen** [comment]
@Ochibooh Documentation can be found here http://fluentribbon.github.io/documentation/controls/ribbon-group-box#customizingHeader

**Comment by OchiengPhelix** [comment]
When is the 7.0.0 going to be out?

**Comment by batzen** [comment]
I currently have no date scheduled.
