### ISSUE TITLE
Changing menu font size in Windows mess ups ribbon

### ISSUE THREAD

**Issue by pekspro** [fluentribbon/Fluent.Ribbon#55]
It’s possible to change the menu font size in the screen settings in Windows. But this could mess up the Ribbon quite a bit I think. It could look like this:

![menufonterror](https://cloud.githubusercontent.com/assets/3163293/5887391/74ff3ffe-a3cd-11e4-960b-a25f9ba53b81.png)

Personally I think it’s a good idea to respect the Window settings, but maybe not in this case. Interestingly the ribbon in Office 2013 do this, but not the ribbon used in Windows 8 (and also in Windows 10 preview).

**Comment by batzen** [comment]
This collides with https://github.com/fluentribbon/Fluent.Ribbon/issues/28
But now I'm no longer sure if it was a good idea to accept the PR connected to that issue...
Getting dynamic font sizes to work correctly in all conditions seems impossible and introduces a lot of problems in many areas.

**Comment by batzen** [comment]
@innostory I fear i will have to revert everything changed in your PR and any subsequent changes which were done to support dynamic font sizing. Any thoughts from your side?

**Comment by innostory** [comment]
This is a requirement from my client, so if you refuse to support it, I will have some trouble :d I agree that it may be impossible because we don't thinking about scaling from beginning, so it hard to do it correctly.

But it still is a good requirements. I don't know why MS drop it in Win8 and Win10 preview, it hard to say this to my client as the reason :(

**Comment by pekspro** [comment]
I also like the idea about making things larger automatically as long as I could disable it :-).

However, it doesn’t need to be that hard if the problem is solved with a different approach. WPF by itself has really good support for scaling and if that is used instead of changing font size on a tons places this may be achieved relative easily. I added this in the test project to make everything 25% larger and its looks just fine:

        <Fluent:Ribbon AutomaticStateManagement="True"
                       x:Name="ribbon"
                       RenderTransformOrigin="0,0">
            <Fluent:Ribbon.RenderTransform>
                <TransformGroup>
                    <ScaleTransform ScaleX="1.25"
                                    ScaleY="1.25" />
                    <SkewTransform />
                </TransformGroup>
            </Fluent:Ribbon.RenderTransform>

**Comment by batzen** [comment]
Making it possible to disable the feature adds even more complexity and room for error, so i will just remove it completely.

You are totally correct.
You got multiple choice to scale your WPF UI.
1. Just tell your clients to use the Windows DPI settings.
2. Add a LayoutTransform to your Window. A RenderTransform will cause problems.
One thing to note when using a ScaleTransform as a LayoutTransform is to change the TextOptions.TextFormattingModeProperty from Display to Ideal when your zoom is != 1.0

**Comment by batzen** [comment]
I reverted all changes made to support SystemFonts with commit 3938dbaeff86bca2333188624d19a916ed8d3168

**Comment by pekspro** [comment]
I must correct myself even if it doesn’t change anything. The ribbon in Windows 8 actually does change its size when the menu size is changed. I must did something wrong first time I tested this.

**Comment by batzen** [comment]
I already reverted the changes and won't add them back because i can't support everything related to dynamic font sizes.
