### ISSUE TITLE
RibbonGroupBox should resize when font family or size are changed

### ISSUE THREAD

**Issue by chrfin** [fluentribbon/Fluent.Ribbon#552]
This is in relation to #551:
After I change the font size the ribbon does not automatically "re-arrange" the items and it looks the following - again crazy example to make it obvious:
![image](https://user-images.githubusercontent.com/1186179/38073124-fe106f72-3329-11e8-8eff-0426fdbaab4f.png)
If you then somehow trigger a "redraw", e.g. by changing the window size just 1px it is correct again:
![image](https://user-images.githubusercontent.com/1186179/38073158-202739f6-332a-11e8-8c87-2507217d7238.png)

To fix this "by code" I did the following (`window` is our window which inherits `RibbonWindow` and has a `Ribbon` property which grants access to the actual ribbon control):
Until yesterday we targeted .NET 4.6.1 and the following worked:

    window.UpdateLayout();
    window.Ribbon.Measure(new Size(window.Ribbon.ActualWidth, window.Ribbon.ActualHeight));

Then we updated to target .NET 4.7.1 and it got stuck on the `Measure` call, but the following does work now:

	window.Ribbon.UpdateLayout();
	window.Ribbon.OnApplyTemplate();

**Is this the correct way to do this or is there a better way?**

**Comment by batzen** [comment]
Forcing the template to be applied again might cause issues.
You will face a lot of issues when trying to fully allow dynamic font sizes.
Why don't you simply add zooming to your application? That way icons also get larger etc.

I will have a look at how to improve the situation out of the box as it should manly be caused by caching measures for RibbonGroupBox and it's children.

**Comment by chrfin** [comment]
It's not a use case, that the font-size is "fully dynamic" or changed "all the time" it's more or less a "one time setting" and we just want to allow our customers to change them in some degree (the extreme examples I postet where just for testing) as we had some requests from customers and it was a "nice by-product" of the themes we just implemented and aside from these two issues it worked "out of the box".
But "zooming" is also a good (additional) idea - especially when using our software in a presentation via a projector.
Very likely the font(-size) options will become only a hidden feature we just change for customers "on request" to avoid "glitches", but non the less it should basically work IMO...

Thanks for looking into it!
