### ISSUE TITLE
No Keytips on templated ribbon items.

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#554]
This is related to issue #533. I add a new issue as the original post is closed already.

I use a MVVM ViewModel-First approach to create the ribbon items. Meaning that I add a list of item ViewModels to the data source of ribbon groups. By using data templates a matching view is automatically created for each ViewModel type in the list. 

The issue that I have is that Keytips are not shown when I define them in the DataTemplate.

Attached is a sample project demonstrating the issue:

[WpfFluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1866601/WpfFluentTest.zip)

---
### Environment

Fluent.Ribbon 6.1.0.233
Windows 10
.NET Framework 4.5

**Comment by batzen** [comment]
Totally forgot about that outstanding issue.
That's the risk of talking about "secondary" issues in other issues. ;-)
