### ISSUE TITLE
RibbonWindow not fully maximized with high DPI

### ISSUE THREAD

**Issue by vojan** [fluentribbon/Fluent.Ribbon#555]
Set the screen to High DPI (f.e. 150% or more). Start the Ribbon ShowCase .NET 4.5 with WindowState: Maximized

A black Border is visible and Maximized size is about 5 pixels short on all sides.

Restore window size and go back to Maximized state: Border is OK.

Pinpointed down to one private member function (InitializeWindowChromeBehavior) in RibbonWindow.cs, then the problem does not occur.

---
### Environment

- Fluent.Ribbon __v5.0.2__
- Windows __7__
- .NET Framework __4.6.01055
<img width="72" alt="2018_04_04_11_01_47_fluent ribbon_5 0 2 0_src_" src="https://user-images.githubusercontent.com/38067866/38298448-a812ad4c-37f7-11e8-9459-ef471c59f622.png">
__

**Comment by batzen** [comment]
Could you try to reproduce this using version 6 or later?

**Comment by vojan** [comment]
Fixed in 6.1.0
Issue can be closed
