### ISSUE TITLE
Wrong Window Resize-Border Sensitivity

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#556]
The sensitivity of the window's resize border is wrong (too small) on some parts of the window. The illustration below shows a test window and the resize border. The places marked with red, the resize border sensitivity is only 1-2 pixels wide (difficult to grab with the mouse) while the remaining part (in green) the sensitivity is wider and easy to use.

![image](https://user-images.githubusercontent.com/22751987/38300375-e27780ca-37fc-11e8-991e-6f6eb3d8797e.png)

Some debugging showed that the issue may be a combination between ControlzEx WindowChomreWorker._HandleNCHitTest() and the WindowChrome.IsHitTestVisibleInChrome property. The Ribbon has the property and this makes it HT_CLIENT instead of resize border. I am not sure if this is a Fluent issue or ControlzEx issue. Removing if from the Ribbon makes the border wider, but may have side effects. Also, this does only fixes part of the problem, because the RibbonTitleBar and other controls have the same issue.

---
### Environment

- Fluent.Ribbon 6.1.0
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
I'm trying to improve this for ages now.
Setting IsHitTestVisibleInChrome to false on the ribbon causes other issues...
The ideal solution would be to get the resize border to work "outside" of the window, like windows explorer etc. do. But i couldn't find a way to achieve this...

**Comment by atlastodor** [comment]
OK. I will try some ideas as well and hopefully we can work together to fix this. I believe the issue is probably 75% in ControlzEx and 25% in Fluent. If I have little time this weekend, I will debug. I have an idea what may be wrong.

**Comment by batzen** [comment]
I will try to port the Glow from MahApps.Metro to ControlzEx.
That should eliminate the resize border problem.
And it's the same technique which is used in visual studio.

**Comment by batzen** [comment]
Will be able to solve this issue as soon as https://github.com/ControlzEx/ControlzEx/issues/49 is done.

**Comment by batzen** [comment]
GlowWindow branch + PR merged. This should be fixed now.

**Comment by atlastodor** [comment]
Thanks Bastian.

I see that ver. 7.0 is in preview now. Should I interpret this that all items on the TO-DO for v. 7 are closed and that it is in QA test now? If so, would you recommend that we update and test our app as well?


Is there a list of changes, especially breaking changes in 7.0?


Thanks.

**Comment by batzen** [comment]
The preview version is still not on nuget but only on the appveyor nuget feed. I will try to release the first preview on nuget during this weekend.
All issues planned for 7.0 are done. I still have to do some testing especially regarding the GlowWindowBehavior.
If you want to give 7.0 a try in your test app feel free to do so. I would really like to hear/see some feedback.
The changelog is, as always, here https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md and it should contain all breaking changes i made.

**Comment by atlastodor** [comment]
Hi Bastian,

I have updated our app to v7.0.0-alpha0388 and ControlzEx to v4.0.0-alpha0161. I can confirm that the border issue is gone.

I must mention that there is a side-effect of the new implementation. The border is drawn as part of the window's client area. This means that the app and the app's UI thread is responsible for this task. If the app is complex (layouting takes some time) and the user resizes vigorously, it is visible that the app lacks a little behind before updating the window. This was not the case with the native non-client implementation. However, both Visual Studio and MS Office apps exhibit this behavior - so I guess we will have to live with it.

Thanks for the help.

**Comment by batzen** [comment]
The lag behind is something i can't really fix as those borders are made possible by 4 support windows around the main window...
The previous border was also part of the client area which was the reason for it only being so thin.
There was no native border implementation as we have to use all non-client area as client are to even be able to render inside/on top of the titlebar.
