### ISSUE TITLE
Populating Fluent.SplitButton with ItemsSource doesnt update text in menu when MenuItems added/removed to ItemsSource collectionview

### ISSUE THREAD

**Issue by PaulMcLeish** [fluentribbon/Fluent.Ribbon#558]
- In XAML bind ItemSource of SplitButton to a public ICollectionView property in viewmodel.
- add/remove items from underlying List<MenuItem> in viewmodel
- Number of MenuItems under SplitButton is updated, but header text is not displayed.

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Windows 10
- .NET Framework 4.5.2
- Visual Studio 2015

**Comment by PaulMcLeish** [comment]
The idea is to be able to populate a menu from user config at runtime. This menu can change per user. So I need to refresh/rebuild the menu on login/logout.
Sorry Fluent v6.1.0.233

**Comment by batzen** [comment]
Tried to reproduce your issue but it works as expected.
Could you provide a small repro showing your issue?

**Comment by batzen** [comment]
@PaulMcLeish ping

**Comment by batzen** [comment]
@PaulMcLeish ping

**Comment by batzen** [comment]
@PaulMcLeish ping

**Comment by batzen** [comment]
@PaulMcLeish ping

**Comment by batzen** [comment]
@PaulMcLeish ping

**Comment by batzen** [comment]
@PaulMcLeish ping
