### ISSUE TITLE
How to use Fluent.Ribbon along with Prism Regions?

### ISSUE THREAD

**Issue by acrolink** [fluentribbon/Fluent.Ribbon#565]
Especially, how to set a main content region which can be assigned views (content views) by clicking fluent ribbon buttons? Any online tutorial available?

**Comment by batzen** [comment]
At least i don't have such information as i don't use prism at all.
Maybe someone else watching this project has experience using prism.
You could also try to ask your question on gitter https://gitter.im/fluentribbon/Fluent.Ribbon

**Comment by acrolink** [comment]
@batzen May I ask how do you decalre a region to be filled with various content views? Do you use View Injection to do that?

**Comment by ZmorzynskiK** [comment]
@acrolink check out here:
https://github.com/fluentribbon/Fluent.Ribbon/issues/1#issuecomment-378696217
