### ISSUE TITLE
How to use Ribbon in WPF Pages?

### ISSUE THREAD

**Issue by SalehGladius** [fluentribbon/Fluent.Ribbon#567]
I'm using WPF pages to create a **single window** apps, so I need to design a page (not window) that has a ribbon. and then present it in MainWindow!

How I do it?

**Comment by batzen** [comment]
You should be able to use the ribbon without a RibbonWindow, if that's your question.

**Comment by SalehGladius** [comment]
Yes. I did it! Thanks. 
Thats my fault.

**Comment by batzen** [comment]
Ok. Will close this issue then.
