### ISSUE TITLE
Empty context menu on controls and ribbon

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#573]
In one project I disabled every option that would have a context menu entry for any control on the ribbon or the ribbon itself. It turned out that this results in an empty context menu:
![image](https://user-images.githubusercontent.com/7498367/40533695-d9242684-6003-11e8-9997-8072fd1761e3.png)

I could build a workaround by adding a context menu that is collapsed to every control by style and a ContextMenuOpening event handler that closes the ribbons context menu immediately (because somehow the added context menu does not solve the problem on the ribbon itself ...).

Did I miss any option to disable the context menu?

---
### Environment

- Fluent.Ribbon __v6.1.0.233__
- Windows __8.1__
- .NET Framework __4.5__

**Comment by batzen** [comment]
You did not miss an option.
I just never thought about that path. ;-)

**Comment by the-madcat** [comment]
A very valid explanation ;)

And I found out why my collapsed context menu did not work for the tabitems ... I simply misspelled the static ressource key and I have no idea why the IDE did not mark it ... we never talk about that again :P

**Comment by batzen** [comment]
And i will add code that simply closes the context menu immediately if it's empty.

**Comment by the-madcat** [comment]
Thank you.
