### ISSUE TITLE
Does RibbonGroupBox set Foreground invalid?

### ISSUE THREAD

**Issue by once86** [fluentribbon/Fluent.Ribbon#576]
<Fluent:RibbonGroupBox IsLauncherVisible="False" Header="test" Foreground="Red">
Does RibbonGroupBox set Foreground invalid? Foreground Do not work.. plz help

---
### Environment

- Fluent.Ribbon v6.1.0.233
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
Nearly every control sets it's own foreground color.
What do you expect to happen when you set the foreground of your RibbonGroupBox?

**Comment by batzen** [comment]
@once86 ping

**Comment by batzen** [comment]
@once86 ping

**Comment by once86** [comment]
I'm sorry so long.
![tim 20180705100433](https://user-images.githubusercontent.com/8371669/42298923-ffd50c4c-803a-11e8-82f0-20255cb68ea3.png)
As shown in the picture. set Header-Foreground Red. but not work

**Comment by batzen** [comment]
You have to overwrite the brush resource named `Fluent.Ribbon.Brushes.RibbonGroupBox.Header.Foreground` to change the header color.
There was an inconsistency which i just fixed.
