### ISSUE TITLE
Compatibility across Windows versions

### ISSUE THREAD

**Issue by ThunderChild-001** [fluentribbon/Fluent.Ribbon#577]
Has anyone experienced problems running compiled projects on different versions of Windows?
For example I compiled a project using Windows Server 2012. Everything works fine on this version of Windows but if I try to run the compiled code on Windows 10 or 7 it either crashes when the ribbon loads or the fluentribbon is missing.

If I re-compile the source code for example on Windows 10 it will then work on this version. The project without the ribbon works cross Windows 7, 8, server 2012 and 10.

**Comment by batzen** [comment]
There shouldn't be any problems like these.

Could you add some details about the crashes/errors you get?

**Comment by KarlAbson** [comment]
Many thanks for the fast reply. It's very hard to give details as I don't get any errors as such. On the machine where the program was compiled everything works fine (Windows Server 2012). On the other machine with windows 10 however the resultant compiled program simply quits.

As soon as I go to open the window with the ribbon the program crashes / closes with out giving an error. For a few seconds fonts etc get slightly bigger and slightly blured and then everything stops responding but this is all.

I had a similar problem a couple of months back. In this case a program complied on Windows 10 would not run on Windows 7. I solved this by having and referencing a local copy of "PresentationFramework.Aero2.dll". It may also have had something to do with the ControlzEx.dll. I replaced this with a newer version.

**Comment by batzen** [comment]
Are there any event log entries? Does procmon report any filesystem errors during app or window launch?

**Comment by batzen** [comment]
@KarlAbson ping

**Comment by batzen** [comment]
@KarlAbson ping
