### ISSUE TITLE
Theming of selected context ribbon tab

### ISSUE THREAD

**Issue by stylefish** [fluentribbon/Fluent.Ribbon#578]
Hey,
first of all: thanks for this awesome component :)
i'm trying to create a custom theme with the new ThemeManager.
My Question is: How do i change the ForeColor of a selected ContextTabItem?

the default tab looks ok:
![image](https://user-images.githubusercontent.com/3922885/41787845-f484dde0-7649-11e8-8fac-d8f5c3205da9.png)

but the contextual tab doesnt change the fore color like the normal tab:
![image](https://user-images.githubusercontent.com/3922885/41787878-120beff2-764a-11e8-83f4-205ae7bad5d2.png)

as far as i can tell both tabs should use the same colors for selected etc, right?

if you could point me in the right direction, that would be really nice :)

thanks a lot
greetings

---
### Environment

- Fluent.Ribbon __v6.1.0__
- Windows __10__
- .NET Framework __4.7.1__

**Comment by batzen** [comment]
The group's foreground color is used. Have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Controls/RibbonTabItem.xaml

I guess there should be a dedicated property for that case on group. Something like SelectedTabForeground. Would that help?

**Comment by stylefish** [comment]
oh i see, so theres no way to change the color via theme i guess?
yeah a new property or we could use the color from RibbonTabItem:

```<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground" Color="{StaticResource BlackColor}" options:Freeze="True" />```

it seems to be unused or overriden by something else, i already set that one to "Black" but my foreground on the selected tabs is either blue:
![image](https://user-images.githubusercontent.com/3922885/41809850-c6a0c1ae-76f4-11e8-90fc-6f248f525140.png)
or light gray (so thats the group color you mentioned i guess):
![image](https://user-images.githubusercontent.com/3922885/41809858-f6e68722-76f4-11e8-82fa-4c42bba3a021.png)
but for context tabs it behaves different:
![image](https://user-images.githubusercontent.com/3922885/41809891-5c62f5b8-76f5-11e8-92ca-73cd1d4fbcaa.png)
so imho both types of tabs should use the same fore color and may be set by the theme (either by the one i suggested above, if its really unused, or by a new one).

it would also be great when you could change the title background from theme, because now i have to do the following in code behind:

```TitleBackground = new SolidColorBrush(Color.FromArgb(255, 1, 115, 199));```

thanks for your quick reply! :)

**Comment by batzen** [comment]
`Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground` not being used is a bug.
I mistakenly used the mouse over brush in that case.

Actions i will take to solve this:
- Fix the used selected brush
- Restructure and cleanup triggers in RibbonTabItem to make it easier to understand to conditions
- Introduce a separate `Fluent.Ribbon.Brushes.RibbonTitleBar.Background` resource

**Comment by stylefish** [comment]
any plans on when version 7 will be released? or on publishing the dev branch to nuget as a prerelease? :)
thank you very much!
greetings

**Comment by batzen** [comment]
@stylefish Will publish a prerelease to nuget during the weekend, at least i hope so. But did you know that you can grab a prerelease from the appveyor feed at https://ci.appveyor.com/nuget/fluent-ribbon ?

**Comment by stylefish** [comment]
uh nice! looking forward to the nuget prerelease. 
the appveyor feed is great also, i'll try to test the changes with that version! :)
thanks a lot!

**Comment by stylefish** [comment]
okay, sorry for the late reply, haven't found the time to test your changes until now.
i checked and it seems almost perfect for my use case :) but i still got one awkward behavior and i'm not sure why this happens, its quite similar to the issue i posed above, so i chose to post it in this issue, hope that's ok for you.

my desired behavior is:
selected tab 
-> background: "white" (works)
-> foreground: "black" (works)
unselected tab
-> background "blue" (works)
-> foreground "white" (works)
mouse over tab
-> background "blue" with light transparent white overlay (works)
-> foreground: "white" **(doesn't work, see "Edit" tab in image)**
![image](https://user-images.githubusercontent.com/3922885/42821725-8378bc54-89d9-11e8-8480-807c8d8a1c0e.png)

in addition, when i select a context tab and leave the tab and the group with the mouse the foreground color changes to the background color:

mouse withing context tab or group container:
![image](https://user-images.githubusercontent.com/3922885/42821811-b0e19e68-89d9-11e8-852c-2bc5d56503e6.png)

mouse somewhere else:
![image](https://user-images.githubusercontent.com/3922885/42821830-bd0fb09e-89d9-11e8-87e6-23f80e218362.png)

i'm using the attached Accent "BlueAccent" and Theme "Light".
maybe you can point me to the right direction.
using the newest 7.0.0 alpha available in the appveyor nuget feed: **7.0.0-alpha0334**
and **controlzex 4.0.0-alpha0119**

my used theme: [Theme.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2201940/Theme.zip)

**Comment by batzen** [comment]
Wil have a look at this on saturday.

**Comment by batzen** [comment]
- The first issue happens because you have to overwrite the attached property `Fluent:RibbonProperties.MouseOverForeground` on `RibbonTabItem` with a style override
- The second issue is most likely caused because you have not overwritten `TabItemSelectedForeground` on `RibbonContextualTabGroup`

You currently can't overwrite these two brushes by only using theme resources but i got an idea on how to make this possible while still maintaining the current way it works.

Currently, for the first case, the mouse over foreground brush being used differs between the light and dark theme. Using a resource here wasn't possible because the highlight brush being used for light is not really visible on the dark theme.

Currently, for the second case, the first case also partially applies for this but in addition to that `TabItemSelectedForeground` is bound to `Foreground`.

**Comment by batzen** [comment]
@stylefish Could you have a look at the latest changes? Instructions are in the changelog. Feel free to ask any questions and give feedback on the features and changelog.

**Comment by stylefish** [comment]
Hey!Thanks for your feedback, will have a look next week, currently on a festival ;) Thank you! Am 21.07.2018 12:58 schrieb Bastian Schmidt <notifications@github.com>:@stylefish Could you have a look at the latest changes? Instructions are in the changelog. Feel free to ask any questions and give feedback on the features and changelog.

**Comment by stylefish** [comment]
ok, sorry for the delay i just tested with the newest appveyor package, my own "light" theme with own blue accent now looks mostly perfect, but the context tabs still dont have a foreground when theyre **not** hovered:
![image](https://user-images.githubusercontent.com/3922885/43256453-08917e5e-90cd-11e8-9259-b7041edd7a6b.png)

it would also be nice to have the "hover foreground color" as a theme resource:
![image](https://user-images.githubusercontent.com/3922885/43256397-dd1cb950-90cc-11e8-98a5-c9dbf711f856.png)

because in the hover state i would like the text to be black, not blue.

am i missing something? :/ i only tried theming these things with the "Theme" and "Accent" files. i you want i could provide them to you again, but theyre mostly unchanged to the last ones (just updated with your styles from the base themes).

thanks for your help! :)

**Comment by batzen** [comment]
Just add your new style files and i will have a look at whats wrong with your styles or with the lib ;-)

**Comment by stylefish** [comment]
here you go! thank you! :) 
[Themes.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2231676/Themes.zip)

**Comment by stylefish** [comment]
btw sth i noticed in your recent change:
```
<Trigger Property="Fluent:RibbonProperties.AppTheme"
                      Value="BaseLight">
                 <Setter Property="Fluent:RibbonProperties.MouseOverForeground"
                        Value="{DynamicResource Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Foreground.Light}" />
```
you're checking the current theme and are setting the corresponding colors, but in my case i have a completely different theme, so this wont work, because my theme has another name. 
why don't you integrate these colors into the apptheme xaml (introduce new variables), so it would be changeable for a theme developer (e.g. me ;))?
maybe this has to do sth with the behavior i'm seeing?

**Comment by batzen** [comment]
Basically the theme defines some base colors and the accents build on top of that.
That causes the problems you are experiencing and the problems i had to work around in some places.
Having everything in one file would solve all issues.
I could then produces files like Blue.BaseDark.xaml, Blue.BaseLight.xaml etc.

It would require some work but it would solve all problems as there would be no dependency between two resource files like it's now the case.

**Comment by batzen** [comment]
@stylefish The separation between AppTheme and Accent is gone and only Theme is left. Everything is now contained in single files named "Dark.Blue" for example.
Could you test the changes and see if you can theme everything like you want to?

**Comment by stylefish** [comment]
hey,
thanks for your continuous support. :) i've tested your changes with the newest appveyor package and the issue i reported originally is working fine! really nice theming experience now with a single file! :)
for me this issue is closed, anyhow it would be nice to theme the active tab mouseover independent from inactive tabs mouseover, but thats optional for me and may also be a new issue. however i wanted to elaborate and then you can decide what to do or not to do: :)

you can theme these properties nicely:
```
    Fluent.Ribbon.Brushes.RibbonTabItem.Foreground
    Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush
```
which will be correctly overriden by
```
    Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Background
    Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Foreground
```
but these will also override 
```Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground```
now you can argue that the selected item should never be overriden by a mouse over (that would be best for my theme, and also because the "mouse over" is also triggered when you hover anywhere over the complete group):

hovered inactive tab (correctly whiter background and white foreground):
![image](https://user-images.githubusercontent.com/3922885/43721792-1c3fbb26-9994-11e8-9ee7-73d60ecb82f2.png)

hovered active tab (incorrect white foreground, this should stay black, correct: background does not change)
![image](https://user-images.githubusercontent.com/3922885/43721684-c7a13f90-9993-11e8-9edc-229510dd4530.png)

in my case i changed the hover fore color to be "black" so if you hover an item the fore and background colors change. but thats ok for me.

but somebody else may have a different opinion on this - so i'll leave it to you.
possible solutions imho would be:
- ignore MouseOver for Selected items (tabs)
- add Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.**Selected**.Foreground and Background

but, like i said, for me this issue is resolved, the result is close enough to the office colorful theme. :)

PS: do you have a new ETA for the pre-release on nuget? :)

**Comment by batzen** [comment]
Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Selected.Foreground would be my favorite here.
Will have a look.

It's already on nuget since saturday. ;-)
Announced it on twitter. Should have also done that in the gitter channel.

**Comment by batzen** [comment]
@stylefish Brush is added

**Comment by stylefish** [comment]
@batzen nice! it works! but for contextual tabs i haven't seen anything to set it... so there is the "black" foreground when you hover it or the white when its selected, like the above screenshots but with the contextual tab group. i used:
Fluent.Ribbon.Brushes.RibbonContextualTabGroup.TabItemMouseOverForeground
so should there be a 
Fluent.Ribbon.Brushes.RibbonContextualTabGroup.**Selected**.TabItemMouseOverForeground or am i doing it wrong?

**Comment by batzen** [comment]
@stylefish Brush is added

**Comment by stylefish** [comment]
@batzen, nice. trying it out in a few secs. if you're at it right now, a
Fluent.Ribbon.Brushes.RibbonWindow.TitleForeground would be nice too, because on dark backgrounds you may want to change to sth more bright than black :)

**Comment by batzen** [comment]
@stylefish There you go

**Comment by stylefish** [comment]
nice, my themes look like this now:

Light:
![image](https://user-images.githubusercontent.com/3922885/43855751-e883a61c-9b46-11e8-855e-3ffb188fb197.png)

Gray:
![image](https://user-images.githubusercontent.com/3922885/43855917-51ac2290-9b47-11e8-8374-c38eaf68cf12.png)

thats as close as i wanted to get to the office 2016 colorful theme and "gray" looks good too ;)
thank you very much for your continuous support and the patience! if anyone is interested i would share the "Light" and "Gray" theme files we produced in this issue :)

looking forward to version 7 release! :)
issue resolved and more!

**Comment by batzen** [comment]
Would be nice if you could share those. Maybe i can include them in the library then.

**Comment by stylefish** [comment]
of course, here they are. or should i create a PR to integrate them?
[Themes.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2271685/Themes.zip)

**Comment by batzen** [comment]
If you like to try to integrate go ahead.
Feel free to ask any questions you have along the way. Best channel would be private chat on gitter.

**Comment by batzen** [comment]
Now that your themes are included in the library, i consider this issue resolved.
Do you think so too?

**Comment by stylefish** [comment]
yes, resolved! great! thanks for your support and the integration! :)

**Comment by batzen** [comment]
@DenZuck that's currently not possible as it's a hard coded path to a png. Could you create a new issue for this?
