### ISSUE TITLE
Fluent 6.1.0 Ribbon color

### ISSUE THREAD

**Issue by chayaw** [fluentribbon/Fluent.Ribbon#583]
Do we have an option for one more color for the ribbon? the dark is too dark, and the light is too light.
Do you have something like light gray? Or do you plan to create such?

thanks!

**Comment by batzen** [comment]
I have no plans on adding a new color theme.
Could you be a bit more specific regarding "too dark" and "too light"?
I get and know that there is still room for improvement, especially in the dark theme.

**Comment by chayaw** [comment]
Thanks.

We want something like office 2013 silver theme, because the dark is too black, and not so comfortable.

**Comment by batzen** [comment]
I won't add color schemes from office 2013 as that's way too old.
I might consider the dark gray theme from the current office version.
But it might take a few weeks or even months till i've got enough spare time for that.
And i would have to figure out how that would work when someone is using the ribbon together with MahApps.Metro as we share some brush names...

**Comment by saragenzel** [comment]
Is there any expectation when this feature will be supported?

**Comment by batzen** [comment]
There is currently something like that. The color scheme name should be "Colorful.Gray" but that name might change. You could try it and give feedback about it. Will make one slight adjustment to that theme today as i noticed a small color glitch.

**Comment by batzen** [comment]
Name is still Colorful.Gray. Closing.
