### ISSUE TITLE
The Bug #433 seems not to be fixed.

### ISSUE THREAD

**Issue by svendu** [fluentribbon/Fluent.Ribbon#584]
The Bug #433 does still exist in the latest version available with nuget. You can still reproduce it with the sample attached to the old bug.
If both GroupBoxes are not collapsed, clicking one button will uncheck the others. If one GroupBox is set to collapsed clicking a button in the uncollapesed GroupBox will leave the button in the collapsed GroupBox checked and vice versa.

---
### Environment

- Fluent.Ribbon __v6.1.0.233__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
It behaves exactly the same as a regular RadioButton.
Removing the dependency on `KeyboardNavigation.GetVisualRoot` will cause `ToggleButton` to behave differently than `RadioButton`.
Please have a look at https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/RadioButton.cs,136.

I don't know how this should be fixed for the regular `RadioButton`. Any suggestions?

**Comment by batzen** [comment]
@svendu ping

**Comment by svendu** [comment]
Sorry, for replying so late. To be honest, I have no idea either. I'll take a look and we'll see if I can come up with something.
