### ISSUE TITLE
BackstageTabItem IsEnabled=False still displays content

### ISSUE THREAD

**Issue by shandoosheri** [fluentribbon/Fluent.Ribbon#586]
After setting the first BackstageTabItem to IsEnabled=False. It is still automatically displays its content upon opening backstage. Is there a away to make it skip not enabled items.

Great Library by the way, Amazing work. Thank you.

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.7.1

**Comment by batzen** [comment]
That's a bug. Will have a look and fix it for version 7.0.
