### ISSUE TITLE
DisplayMemberPath no longer working on DropDownButton/MenuItem as of version 6.0

### ISSUE THREAD

**Issue by DavidPerez18** [fluentribbon/Fluent.Ribbon#587]
`<Fluent:DropDownButton  
 ItemsSource="{Binding Settings.ActivitySettings.Activities}"   
DisplayMemberPath="Name">`

I created a drop down button with an item source containing my own custom objects. Each object has a "Name" property. I set the DisplayMemberPath to equal this property. 

This works fine on version 5.0 and earlier, but it broke on version 6.0. Instead of showing the value of the Name property, it just shows the class/method name. Adding an overload ToString method on my class fixes it, but I never had to do this before.

**Comment by batzen** [comment]
That might be related to the changed inheritance of `DropDownButton` as it now inherits from `ItemsControl` instead of `MenuBase`.
Will have a look at this on saturday.
