### ISSUE TITLE
Delay and black background when maximizing window

### ISSUE THREAD

**Issue by ghord** [fluentribbon/Fluent.Ribbon#589]
Steps to reproduce:

1. Open RibbonWindow with fluent ribbon control.
2. Double click on window title bar to maximize it (works ok)
3. Double click on window title bar to restore it (also works ok)
4. Double click again on restored window title bar. It should maximize as before, but this time maximizing it breaks the title bar (you can see my desktop background where upper part of title bar should be)

![obraz](https://user-images.githubusercontent.com/10825459/43075499-603c6554-8e81-11e8-9765-6b5e8ed96b32.png)

Moving the window anywhere between steps 3 and 4 fixes the issue for the next double click.

---
### Environment

- Fluent.Ribbon __v6.1.0__
- Windows 10
- .NET Framework 4.6

**Comment by batzen** [comment]
Which version of ControlzEx (a dependency of Fluent.Ribbon) are you using?
Could you try to update that dependency?

**Comment by ghord** [comment]
It's latests version 3.0.2.4 of ControlzEx

**Comment by batzen** [comment]
Will release a preview of Fluent.Ribbon version 7.0 during the next days. Would be nice if you could give that version a test as we changed a lot of window code in version 4.0 of controlzex.

**Comment by batzen** [comment]
@ghord Released the first preview version for 7.0 yesterday. Could you give it a try?

**Comment by ghord** [comment]
The issue is fixed in preview version, thanks!

I've noticed that first window maximize (with double click on title bar) now hangs the app for some seconds with black background taking most of the screen, but I guess this is a separate issue.

**Comment by batzen** [comment]
Does the showcase application hang on maximize or your own application?

**Comment by ghord** [comment]
I've checked the showcase app, It's the same.
