### ISSUE TITLE
Little style bug in Windows 8 theme

### ISSUE THREAD

**Issue by FranzPacher** [fluentribbon/Fluent.Ribbon#59]
Hi,
in the new version 3.3.0.0 (SRC ) is available with the Theme Windows 8 in the backstage area again the button style bug.
And the backstage style is from Office 2010 , which is intentional?

![screenshot](https://cloud.githubusercontent.com/assets/10328910/6005376/28281ef0-ab0a-11e4-856c-4a1a1354775f.png)

**Comment by batzen** [comment]
The button sizes will be fixed.
Regarding the backstage, Windows 8 has no backstage in the ribbon so i don't know which style should be used there. Please ask that question here: https://github.com/fluentribbon/Fluent.Ribbon/issues/48

**Comment by pekspro** [comment]
Ups, I totally missed those controls when doing the Windows 8 theme. I will dig into it.
