### ISSUE TITLE
Show 2 buttons and hide arrow button in QuickAccessToolBar

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#591]
Hello. Thank you for your library! It is amazing!
I want show two buttons in QuickAccessToolBar. And hide drop down arrow for change buttons.
I try this:
```
<fluent:Ribbon xmlns:fluent="urn:fluent-ribbon" 
                       IsQuickAccessToolBarMenuDropDownVisible="False">

            <fluent:Ribbon.QuickAccessItems>
                <fluent:QuickAccessMenuItem IsChecked="true">
                    <fluent:Button Header="Undo"
                                   Command="{Binding UndoCommand}"
                                   Icon="Resources/undo_button.png"/>
                </fluent:QuickAccessMenuItem>
                <fluent:QuickAccessMenuItem IsChecked="true">
                    <fluent:Button Header="Redo"
                                   Command="{Binding RedoCommand}"
                                   Icon="Resources/redo_button.png"/>
                </fluent:QuickAccessMenuItem>
            </fluent:Ribbon.QuickAccessItems>
</fluent:Ribbon>
```

But I get this:
![1111](https://user-images.githubusercontent.com/6030335/43186471-666d25cc-8ff7-11e8-9517-916a918faf6a.PNG)

Please help me. I did not find solution.
Thank you!

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
As far as i remember i fixed that issue in version 7.0.
You can wait till the weekend when i will publish the first preview to nuget or grab the current preview from the appveyor nuget feed at https://ci.appveyor.com/nuget/fluent-ribbon.

And it's not the dropdown button you see there, it's the expander that shows up when there is not enough space to render all buttons in the quick access. There was an issue where the size calculation was wrong on startup.

**Comment by balkarov** [comment]
Cool! 
Thank you for fast answer!
I will try your nuget. And after will be waiting new release 7.0.

**Comment by balkarov** [comment]
Where I can read changelog for 7.0 now?

**Comment by batzen** [comment]
https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md

**Comment by balkarov** [comment]
Thanks a lot!

**Comment by batzen** [comment]
You also have to add https://ci.appveyor.com/nuget/controlzex to your sources.
Sorry for not telling you that in advance.

**Comment by balkarov** [comment]
Thank you for your fast answer, but I get error again
Unable to resolve dependencies. 'ControlzEx 4.0.0-alpha0145' is not compatible with 'Fluent.Ribbon 7.0.0-alpha0345 constraint: ControlzEx (> 4.0.0 && < 5.0.0)'

**Comment by batzen** [comment]
Strange. Might be a nuget issue. I am using paket everywhere but will test it with nuget as soon as i got some spare time.

**Comment by balkarov** [comment]
Fluent.Ribbon `7.0.0-alpha0346` works. Thank you for your fast commit

**Comment by balkarov** [comment]
But I will wait release. Because alpha has bug.
```
<fluent:RibbonGroupBox Header="Some"
                       IsEnabled="{Binding IsSelected}"
                       Icon="tab.png">
    <ItemsControl ItemsSource="{Binding MyList}">
        <ItemsControl.ItemTemplate>
            <DataTemplate>
                <fluent:Button Header="{Binding Name}"
                               Width="93"
                               Icon="{Binding ImageUri}"
                               LargeIcon="{Binding ImageUri}"
                               Command="{Binding MyCommand}"
                               CommandParameter="{Binding}" />
            </DataTemplate>
        </ItemsControl.ItemTemplate>
        <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
                <StackPanel Orientation="Horizontal" />
            </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
    </ItemsControl>

</fluent:RibbonGroupBox>
```

After click button - panel change alpha and after click again on panel panel change alpha back. (`IsSelected` in my case always true). In version 6 it works

**Comment by batzen** [comment]
I don't fully understand the issue you describe.
Could you create a new issue and add a repro for the issue you discovered?

**Comment by balkarov** [comment]
Yes, of course

**Comment by batzen** [comment]
Does version 7.0 solve the issue with the quickaccesstoolbar?

**Comment by balkarov** [comment]
Yes, it does

**Comment by balkarov** [comment]
When you submit 7.0 to nuget?

**Comment by batzen** [comment]
The first preview is on nuget. Will probably take some weeks for the final version.

**Comment by balkarov** [comment]
Hello. 
I tried to install 7.0.0-alpha0624 but it does not work.
My code
```
<fluent:Ribbon CanCustomizeRibbon="False"
                       IsQuickAccessToolBarMenuDropDownVisible="False"
                       CanMinimize="False"
                       CanCustomizeQuickAccessToolBarItems="False"
                       CanCustomizeQuickAccessToolBar="False"
                       CanQuickAccessLocationChanging="False">
```

And I have the problem
![image](https://user-images.githubusercontent.com/6030335/56566435-4dcbc380-65bb-11e9-9dbd-23a22336ec86.png)

**Comment by balkarov** [comment]
And after update to 7.0.0-alpha0624 I have this problem:
![Безымянный](https://user-images.githubusercontent.com/6030335/56566733-0db91080-65bc-11e9-816f-338105c65013.png)

**Comment by batzen** [comment]
It's working fine in the showcase application.
If you still have the issue it would be nice if you could create a new issue and add a small repro project showcasing your issue to the new issue.

**Comment by balkarov** [comment]
But button show. I need hide this button. 
IsQuickAccessToolBarMenuDropDownVisible Does not help me.

**Comment by balkarov** [comment]
@batzen this is small project
[WpfApp2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3126979/WpfApp2.zip)

and result
![Снимок](https://user-images.githubusercontent.com/6030335/56890561-7869c080-6a82-11e9-8eba-100aa83ec864.PNG)

**Comment by batzen** [comment]
Very strange what's happening.
Will investigate and fix it.

**Comment by balkarov** [comment]
Hello. Did you fix it? 
What’s the version number?

**Comment by batzen** [comment]
It's on the appveyor nuget feed. Didn't release to nuget as i am on vacation starting today. Will release a new preview to nuget on 13.th may.

**Comment by balkarov** [comment]
@batzen hello. What about fix the bug?

**Comment by Itee** [comment]
In case this help, 
i notice that if you have more than 1 Ribbon element in your UI, you will need to set `IsQuickAccessToolBarMenuDropDownVisible="False"` on every instance/declaration. 
@batzen Is this a static member ?!?

Hope this help,
Best regards.

**Comment by batzen** [comment]
You should be able to override the default value when you use a style which is based on the default ribbon style or if you use an inherited ribbon control you could set the property value in the constructor, or override the default dependency property metadata.
