### ISSUE TITLE
Disable context menu on Ribbon 

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#592]
Hello. Thank you for your library.
How to disable main context menu on Ribbon?
![111](https://user-images.githubusercontent.com/6030335/43244610-28af2772-90b4-11e8-9e77-5c2f72509077.png)

I tried this:
```
<fluent:Ribbon xmlns:fluent="urn:fluent-ribbon"
                       ContextMenu="{x:Null}">
```

Sorry, I did not find solution.

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
There are various switches which control which items are visible in the ContextMenu.
To get rid of these two options you have to set `CanQuickAccessLocationChanging` and `CanMinimize` to `false`.
To get rid of all context menu options you also have to set `CanCustomizeQuickAccessToolBar`, `CanCustomizeQuickAccessToolBarItems` and `CanCustomizeRibbon` to `false`.
I hope i didn't forget any option.

**Comment by balkarov** [comment]
If I set CanMinimize = false, then I lost button for minimize.
But I want leave minimize button and hide context menu

**Comment by batzen** [comment]
I will add a new property to fully disable the context menu as you are not the first one requesting such a feature.

**Comment by balkarov** [comment]
Thank you very much!
I will wait.

**Comment by batzen** [comment]
That's an issue i fixed in version 7.0. ;-)

But i will add an option to disable the context menu completely.

**Comment by balkarov** [comment]
Why you closed? Did you add this feature?

**Comment by batzen** [comment]
Yes, i did.

**Comment by balkarov** [comment]
What is the naming?

**Comment by batzen** [comment]
Have a look at https://github.com/fluentribbon/Fluent.Ribbon/commit/5b4126b8294126e216eeb8e572d605b16032acf6

**Comment by balkarov** [comment]
Thank you very much! 👍
