### ISSUE TITLE
Disable state selected in InRibbonGallery after click

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#593]
Hello. Thank you for your library! 
Is it possible disable state selected GalleryItem in InRibbonGallery after click on Item as like button?

![default](https://user-images.githubusercontent.com/6030335/43246290-db002a48-90b9-11e8-8076-53bb0f4f36d2.PNG)

And after click panel change alpha. Is it possible disable too?
![sdfsdf](https://user-images.githubusercontent.com/6030335/43246507-8490412e-90ba-11e8-944e-908edfae2126.PNG)

My code:
```
<fluent:InRibbonGallery ItemHeight="55"
                        ItemWidth="80"
                        ItemsSource="{Binding SomeList}">
    <fluent:InRibbonGallery.ItemTemplate>
        <DataTemplate>
            <fluent:GalleryItem Tag="{Binding DisplayName}">
                <StackPanel>
                    <Image Source="{Binding ImageUri}"/>
                    <TextBlock Text="{Binding DisplayName}"/>
                </StackPanel>
            </fluent:GalleryItem>
        </DataTemplate>
    </fluent:InRibbonGallery.ItemTemplate>
</fluent:InRibbonGallery>
```

Sorry I did not find solution.
Thank you!

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
GalleryItems are meant to be selected and not work as regular buttons.
You could try to set IsSelected=false or add a click event handler and reset the selection from there.

I am not sure if i fully understood your question however.

**Comment by balkarov** [comment]
Hm... maybe you have idea?
Look. I want group dinamic elements (40-50) on the Ribbon. And group it. Show max 7 elements in Rows and in Dropdown show all elements. But I want this elements works as like buttons after click. Click and remove background selected.

I try ovveride fluent GalleryItem
```
protected override void OnClick(object sender, RoutedEventArgs e)
        {
            base.OnClick(sender, e);
            ((GalleryItem) sender).IsSelected = false;
        }
```

But this works not fully. Because sometime fluent:InRibbonGallery still leave selected item.

**Comment by balkarov** [comment]
If you open outlook. You can see what I want. 
This is Gallery too, but all items work as like buttons
![default](https://user-images.githubusercontent.com/6030335/43258909-2b2dc03e-90dd-11e8-8a80-9c9c56c052a3.PNG)

**Comment by batzen** [comment]
If it's something outlook offers as a feature i will add this feature here too.

**Comment by balkarov** [comment]
Thanks a lot!

**Comment by batzen** [comment]
Just noticed that this should already be possible.
Could you try to set `Selectable` on your `InRibbonGallery`?

**Comment by balkarov** [comment]
I will check

**Comment by balkarov** [comment]
`Selectable` (False/True) does not help

**Comment by batzen** [comment]
It's broken. Will fix it.

**Comment by balkarov** [comment]
Hello. Did you fix this problem?

**Comment by balkarov** [comment]
I tried install 7.0.0-alpha0624 but it does not work. 
I mean `Selectable` on your `InRibbonGallery`

**Comment by batzen** [comment]
It's working in the showcase application.
Could you create a small repro project which showcases your issue?

**Comment by balkarov** [comment]
@batzen this is my small project
[WpfApp2_gallery.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3127073/WpfApp2_gallery.zip)

Result is

![image](https://user-images.githubusercontent.com/6030335/56891590-aa305680-6a85-11e9-965c-0b139a17ac2b.png)


I use `GalleryItem` in `DataTemplate` of `InRibbonGallery`. I think in this problem. But I need `Command` when click `GalleryItem`

**Comment by batzen** [comment]
By using a `DataTemplate` you are generating a `GalleryItem` inside a `GalleryItem`.
If you don't want that to happen you should use `ItemContainerStyle` for your command and command parameter and use a grid/stackpanel etc. as the item template.

I have also run into this issue a few times, but it's the default WPF behavior and i can't do much about it.

**Comment by balkarov** [comment]
Could you send me example how use InRibbonGallery with command by click?

**Comment by batzen** [comment]
Will do so after my vacation. Please ping me here if i didn't send you an example by may 14th.

**Comment by balkarov** [comment]
Ok, thank you! I will. Have a good time!

**Comment by batzen** [comment]
You could use something like this:
```
<Fluent:InRibbonGallery.ItemContainerStyle>
    <Style TargetType="{x:Type Fluent:GalleryItem}">
        <Setter Property="Command"
                Value="{Binding MyCommand}" />
    </Style>
</Fluent:InRibbonGallery.ItemContainerStyle>
```
