### ISSUE TITLE
RibbonGroupBox disable after click button

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#595]
Hello.

Panel disable after click button in it. After click to Panel again then will enable.
**In version 6.1.0.233 it works**
![1](https://user-images.githubusercontent.com/6030335/43323884-81829a2a-91bb-11e8-8fff-34f6eed166a2.gif)

Code:
```
<fluent:RibbonGroupBox Header="Example">
    <ItemsControl ItemsSource="{Binding MyList}">
        <ItemsControl.ItemTemplate>
            <DataTemplate>
                <fluent:Button Header="{Binding Name}"
                               LargeIcon="{Binding ImageUri}"
                               Command="{Binding MyCommand}"
                               CommandParameter="{Binding}">
                </fluent:Button>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
        <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
                <StackPanel Orientation="Horizontal" />
            </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
    </ItemsControl>
</fluent:RibbonGroupBox>
```

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0346
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Could you add your code behind?
Will be much easier to reproduce this with a full repro (a small project showcasing the issue).

**Comment by balkarov** [comment]
Code behind is empty. 
I have only view model. 
But view model have one observable collection and empty command

**Comment by batzen** [comment]
You at least have some kind of viewmodel and some kind of icommand implementation.
Without these i am not able to reproduce your issue.
I tested this with the showcase application by adding a case for your issue and can't reproduce your issue.

**Comment by balkarov** [comment]
Did you test on 7.0.0-alpha0346?

**Comment by batzen** [comment]
@balkarov ping

**Comment by balkarov** [comment]
I will check my ViewModel and will inform you

**Comment by balkarov** [comment]
It was problem in viewModel
