### ISSUE TITLE
MahApps.Metro dialog on backstage

### ISSUE THREAD

**Issue by TheGian82** [fluentribbon/Fluent.Ribbon#599]
Hello All
using Fluent Ribbon with MahApp I found that the Dialog are not shown if the backstage is open. This problem is a layer problem; because if i close the backstage the dialog is shown.
Is it possible to fix this?

thanks
Gian

---
### Environment

- Fluent.Ribbon __6.1.0.233__
- Windows __10__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
Yes, it's a layer problem and i plan on trying to fix it.
The current priority is updating/rewriting the theming in Fluent.Ribbon and MahApps.Metro.
So it might take a while till i have time to fix this.

**Comment by batzen** [comment]
Feel free to give it a try if you like.

**Comment by batzen** [comment]
I also added some documentation for this at https://fluentribbon.github.io/documentation/interop_with_MahApps.Metro
