### ISSUE TITLE
Warning when installing FluentRibbon with NuGet

### ISSUE THREAD

**Issue by JohnyL** [fluentribbon/Fluent.Ribbon#600]
When installing FluentRibbon with NuGet, I get the following warning:

> Warning NU1602 Fluent.Ribbon 6.1.0.233 does not provide an inclusive lower bound for dependency ControlzEx (> 3.0.1.66 && < 4.0.0). An approximate best match of ControlzEx 3.0.2.4 was resolved.

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10 Home x64
- .NET Framework 4.7.2

**Comment by batzen** [comment]
Will release an updated nuget package for this

**Comment by batzen** [comment]
Release version 6.1.0.326 on nuget to fix the version constraint issue.
Thanks for pointing this out.
I use paket everywhere so i don't notice such issues.

**Comment by JohnyL** [comment]
Thanks, Bastian! Now everything is OK! :)
