### ISSUE TITLE
Menu item binding issue

### ISSUE THREAD

**Issue by shandoosheri** [fluentribbon/Fluent.Ribbon#601]
when attempting to use binding the following way. it doesnt seem that the checked status is updated, nor does the variable update when i click on the menu item

`<Fluent:DropDownButton x:Name="itemsButton" Header="items">
                    <Fluent:MenuItem x:Name="menuItem1" Header="First Item" IsCheckable="True" IsChecked="{Binding menuChecked, Mode=TwoWay}">
                </Fluent:DropDownButton>`

---
### Environment

- Fluent.Ribbon 6.1.0
- Windows 10
- .NET Framework 4.7.1

**Comment by batzen** [comment]
Could you try to reproduce this using the alpha of version 7.0?
Can't reproduce your issue using that version.

**Comment by shandoosheri** [comment]
oh ok, should i get that from the develop branch or the master branch.

**Comment by shandoosheri** [comment]
i pulled the source code from the master branch and used that one but still i cant get it to work. i have bindings attached to the togglebutton and that one works just fine using the same method.

**Comment by batzen** [comment]
The master branch only contains the current stable version which is 6.1.
To get version 7.0 you can either clone the develop branch or use the current preview of 7.0 from nuget.

**Comment by batzen** [comment]
If that still doesn't work it would be nice if you could attach a small repro to this issue.

**Comment by batzen** [comment]
Have you read the development requirements?
You need the latest version of VS2017 to compile.

**Comment by shandoosheri** [comment]
i do have that ver. 15.7.6

**Comment by batzen** [comment]
That's strange.
Could you try to run the powershell script "Build.ps1" and see if that works?

**Comment by shandoosheri** [comment]
I get the same error
`
========================================
Build
========================================
Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\Shady\.nuget\packages\gitlink\3.1.0\build\GitLink.targets(9,5): warning : Unable to find file in git: "c:\user
s\shady\onedrive\desktop\fluent\fluent.ribbon\fluent.ribbon\obj\release\net462\generatedinternaltypehelper.g.cs". [C:\U
sers\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent.Ribbon\Fluent.Ribbon.csproj]
  Fluent.Ribbon -> C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\bin\Fluent.Ribbon\Release\net462\Fluent.dll
C:\Users\Shady\.nuget\packages\msbuild.sdk.extras\1.6.46\Build\ReferenceAssembly.targets(71,61): error MSB4057: The tar
get "GetAssemblyAttributes" does not exist in the project. [C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent
.Ribbon\Fluent.Ribbon.csproj]
C:\Users\Shady\.nuget\packages\msbuild.sdk.extras\1.6.46\Build\ReferenceAssembly.targets(71,61): error MSB4057: The tar
get "GetAssemblyAttributes" does not exist in the project. [C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent
.Ribbon\Fluent.Ribbon.csproj]
C:\Users\Shady\.nuget\packages\gitlink\3.1.0\build\GitLink.targets(9,5): warning : Unable to find file in git: "c:\user
s\shady\onedrive\desktop\fluent\fluent.ribbon\fluent.ribbon\obj\release\net45\generatedinternaltypehelper.g.cs". [C:\Us
ers\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent.Ribbon\Fluent.Ribbon.csproj]
  Fluent.Ribbon -> C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\bin\Fluent.Ribbon\Release\net45\Fluent.dll
C:\Users\Shady\.nuget\packages\msbuild.sdk.extras\1.6.46\Build\ReferenceAssembly.targets(71,61): error MSB4057: The tar
get "GetAssemblyAttributes" does not exist in the project. [C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent
.Ribbon\Fluent.Ribbon.csproj]
C:\Users\Shady\.nuget\packages\msbuild.sdk.extras\1.6.46\Build\ReferenceAssembly.targets(71,61): error MSB4057: The tar
get "GetAssemblyAttributes" does not exist in the project. [C:\Users\Shady\OneDrive\Desktop\fluent\Fluent.Ribbon\Fluent
.Ribbon\Fluent.Ribbon.csproj]
An error occurred when executing task 'Build'.
Error: One or more errors occurred.
        MSBuild: Process returned an error (exit code 1).
`

**Comment by batzen** [comment]
I guess you'll have to use the nuget version for now. Will still try to figure out why you get that error.

**Comment by batzen** [comment]
Do you have the .net core sdk installed as part of visual studio?

**Comment by shandoosheri** [comment]
Yes I do. Could there be a conflict

**Comment by batzen** [comment]
The target that it says is missing is from the dotnet sdk (https://github.com/dotnet/sdk) which is the base for the sdk-based csproj format which Fluent.Ribbon uses.
Which sdk version do you have installed?

**Comment by batzen** [comment]
@shandoosheri ping
