### ISSUE TITLE
Double Tap on RibbonWindow doesn't put Window in "Normal" mode

### ISSUE THREAD

**Issue by mporcaro** [fluentribbon/Fluent.Ribbon#605]
**When double tapping the RibbonWindow's titlebar on a trackpad, the window will not go to a normal state from maximized state.  Double clicking the titlebar does however function as expected.**

---
### Environment

- Fluent.Ribbon 6.1.0.326
- Windows 10
- .NET Framework 4.0

**Comment by batzen** [comment]
Will try to reproduce this next week at work. Don't have a trackpad at home.

**Comment by batzen** [comment]
@mporcaro 
I finally had time to try this and i can't reproduce your issue. Sorry that it took so long.

As far as i remember i changed something according to the WindowSteering in version 7.0.

Could you try the prerelease of version 7.0 and report back if you could reproduce the issue using that version?
