### ISSUE TITLE
Submenu contained in DropDownButton closes too slow

### ISSUE THREAD

**Issue by stylefish** [fluentribbon/Fluent.Ribbon#607]
If you create a structure like this:

```
<fluent:RibbonTabItem Header="Home">
    <fluent:RibbonGroupBox Header="Group">
        <fluent:DropDownButton Header="Button">
            <fluent:MenuItem Header="Sub 1">
                <fluent:MenuItem Header="Sub 1.1" />
```

and hover the the "Sub 1" item a menu opens, this menu closes too slow, when you add 2 subitems (Sub 1, Sub 2) the menus are overlapping each other on mouse hovering.

repro demo proj attached:
[WpfApp1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2294172/WpfApp1.zip)

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0388__
- Windows __10__
- .NET Framework __4.7.1__

**Comment by stylefish** [comment]
@batzen would be nice if you could release a new preview on nuget these days :) thank you!

**Comment by batzen** [comment]
Yeah, had no time to do so during the last two weekends.
Will publish now.
https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0419
