### ISSUE TITLE
How to set a image as button background?

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#611]
Hi I am new in fluent ribbon.
I have to add image as button background but I always get a exception "File 'Images/Ex.png' cannot be found".

I paste the images in ...fluent ribbon showcase/images/  but I get that error. 
---
### Environment

- Fluent.Ribbon 4.5
- Windows 7 Enterprise 
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
Hi,
 have you embedded the images as resources? If yes are they contained in your exe project or some dll?
Have you tried using the full resource path?

If you pasted your image to the showcase you most likely forgot to embed it as a resource.

**Comment by Mathanvj44** [comment]
Yes I didn't embed the images. How to embed the images?

**Comment by batzen** [comment]
You have to set the build action for your image to Resource in it's properties.

**Comment by batzen** [comment]
@Mathanvj44 Did that answer your question?
