### ISSUE TITLE
How to extend the ribbon?

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#612]
Hi,
    I want to extend the ribbon. It is like single row. But I want double row size. 
    I have more controls to be placed in ribbon so if I want to see then I scrolled. But I want extend them and see the whole controls in single ribbon.

 How to do that?  

---
### Environment

- Fluent.Ribbon 4.5
- Windows 7
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
You'd have to change all hard coded heights in the source code.
Will have a look at what has to be changed and see if i can introduce resources for those settings.

**Comment by batzen** [comment]
Totally forgot that this is already supported by `ContentHeight` on `Ribbon`.
