### ISSUE TITLE
Binding path error: Description property not found on MenuItem

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#614]
There is an annoying bug in FluentDefaultSystemMenuItemStyle that floods the output window in VS with "System.Windows.Data Error: 40 : BindingExpression path error" 

The bus is in the line:
DataTrigger Binding="{Binding Description, RelativeSource={RelativeSource Self}, Converter={x:Static converters:IsNullConverter.Instance}}" Value="False"

The standard MenuItem does not have a Description, only the Fluent menu items have one. So either is the style defined for the wrong type or if the style should be generic, add FallbackValue to suppress the cases where the source does not have a Description property.

Thanks
-Todor

### Environment

- Fluent.Ribbon __v7.0.0-alpha0388__
- Windows __10__
- .NET Framework __4.7__

**Comment by atlastodor** [comment]
Sorry … forget that. My fault. We misused the FluentDefaultSystemMenuItemStyle for all MenuItems, because it had some nice features we wanted. I re-implemented the contents of that style without the affected bindings and all-is-good.

**Comment by batzen** [comment]
But you are totally correct.
The target type of the style is misleading.
Will change the target type and the name of the style.
