### ISSUE TITLE
RibbonBackstageTabItem

### ISSUE THREAD

**Issue by the-madcat** [fluentribbon/Fluent.Ribbon#615]
Hi

I am using the Fluent Ribbon for longer and I used this XAML pattern to extend the theme for a `RibbonBackstageTabItem`:

```xml
<Style TargetType="TabItem" x:Key="RibbonBackstageTabItem" BasedOn="{StaticResource InnerBackstageTabControlItem}">
	<Setter Property="Foreground" Value="{DynamicResource {x:Static SystemColors.ActiveCaptionTextBrushKey}}"/>
	<Style.Triggers>
		<Trigger Property="IsSelected" Value="True">
			<Setter Property="Foreground" Value="White"/>
		</Trigger>
	</Style.Triggers>
</Style>
```

It worked very well but out of the blue VS tells me that the ressource `InnerBackstageTabControlItem` cannot be resolved and the whole Designer ignores everything related to the Ribbon ... I tried to restart everything, to reinstall the nuget package and to look for it by myself but I cannot open the currently downloadable version ... maybe you use a newer version of VS as I do (2015 Express).

It would be great if you had any idea on what happend since I didn't even update the nuget package when the error occured (I did it after that but it obiously did not fix it -.-')

Many thanks
the-madcat

---
### Environment

- Fluent.Ribbon __v6.1.0.326__
- Windows __10__
- .NET Framework __4.5__

**Comment by batzen** [comment]
If you haven't updated Fluent.Ribbon and it suddenly stopped working it guess it's not an issue with Fluent.Ribbon.

Maybe you changed some resource dictionary-chain?
Have you tried clearing the designer cache and your temp folder?
Is it just the designer throwing errors or does this happen at runtime?

To develop/compile Fluent.Ribbon yourself you need VS 2017 and the .net core sdk.

**Comment by the-madcat** [comment]
Hi

I do also not think its Fluent.Ribbon itself. I just hoped that you might
have encountered a similar problem before.

To your questions:


   -
*Maybe you changed some resource dictionary-chain? *No I did not touch the
   ressource dictionary chain and every other style in this ressource works
   fine.
   - *Have you tried clearing the designer cache and your temp folder?*
   I searched on every dictionary that the internet told me to delete but
   not a single one existed on my PC ...
   - *Is it just the designer throwing errors or does this happen at
   runtime?*
   I can compile it and everything works fine but changing something
   without seeing it in the designer is aweful ... -.-'


Thanks for the quick reaction and I am sorry that I could not answer
yesterday.

**Comment by batzen** [comment]
I stopped using the designer years ago due to issues like this one. Maybe running procmon while opening the designers reveals the cache directory of the designer?

**Comment by the-madcat** [comment]
I found the shadow cache and I feel a bit dump ...

Because I use the express version it is not like every tutorial tells you here:
`%LOCALAPPDATA%\Microsoft\VisualStudio\[VERSION]\Designer\ShadowCache`

... no it has to be on a slightly different place:
`%LOCALAPPDATA%\Microsoft\WDExpress\[VERSION]\Designer\ShadowCache`

Unfortunately it did not help.

And yes I agree with you that the designer is a bit of a pain in the ass but 70% of my work is creating GUIs that show the status and eveything about our hardware and without the designer preview I would have to compile big projects all over in order to see if I did it right in order to place everything I also stopped dragging and dropping everthing in the designer and switched to writing it in XAML ... For now I just stay with it because I am still able to compile and hope that an update to the newest Visual Studio version in near future will do the trick for me.

**Comment by the-madcat** [comment]
I just want to inform you that with the newest revision of VS I was able to identify a broken binding in design mode that was not recognized before. After I fixed it now I can see the window again with a working ribbon.
