### ISSUE TITLE
ContextMenu auto hidden after right click 

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#616]
Hello. Thank you for your library!

Sometimes ContextMenu auto hidden after right click.
![3](https://user-images.githubusercontent.com/6030335/44526036-72e5fa80-a6eb-11e8-8712-a9c0f5c86c57.gif)

My code:
```
<fluent:DropDownButton Header="{Binding Name}"
                       LargeIcon="theme.png">
    <ItemsControl ItemsSource="{Binding MyList}">
        <ItemsControl.ItemTemplate>
            <DataTemplate>
                <fluent:MenuItem Header="{Binding Name}">
                    <fluent:MenuItem.ContextMenu>
                        <fluent:ContextMenu StaysOpen="true">
                            <fluent:MenuItem Header="Delete" />
                        </fluent:ContextMenu>
                    </fluent:MenuItem.ContextMenu>
                </fluent:MenuItem>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
    </ItemsControl>

</fluent:DropDownButton>
```

---
### Environment

- Fluent.Ribbon 6.1.0.233
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
Finally found out what's causing this. Will fix it.

**Comment by batzen** [comment]
Just as a reference for myself, this is somewhat related to #439.

**Comment by batzen** [comment]
@balkarov Should be fixed in the latest source version. Could you give it a try?

**Comment by balkarov** [comment]
Thanks!
Last version in nuget?

**Comment by batzen** [comment]
No, not on nuget currently. Willtry to publish there later.

**Comment by batzen** [comment]
Forgot to inform you that it's now on nuget https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0419

**Comment by batzen** [comment]
@balkarov ping

**Comment by balkarov** [comment]
@batzen thank you for your fix. Sorry, I cannot checking now beta version. I will wait release 7.0. You can close this issue if you fixed it. I will check it on release 7.0. If I will found some problem I will inform you. Thank you!

**Comment by balkarov** [comment]
Hello. When you release 7.0 version?

**Comment by balkarov** [comment]
Hello. Why you did not publish 7.0 version yet?

**Comment by balkarov** [comment]
Hello. When you release 7.0 version?
