### ISSUE TITLE
How to dynamically change the buttons while click the button? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#617]
Hi, 
   I want to change the button from one to another button which is different activity  in dynamically .
   Which button I used like toggle button or button or anything?  
  

---
### Environment

- Fluent.Ribbon 4.5
- Windows 7
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
I don't understand your question.

**Comment by batzen** [comment]
I need a stacktrace or sample code of what you are trying to do to help you.

**Comment by batzen** [comment]
@Mathanvj44 ping

**Comment by batzen** [comment]
@Mathanvj44 ping
