### ISSUE TITLE
Dll corrupted 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#618]
Hi,
     I am new in wpf and fluent ribbon 
     While I was coding, I build the project lot of times.
     So lot of properties set into {x:null} automatically.
     For ex,  in styles xaml file the background property  is set into {x:null}.
     So I get error in binding .

How to revert that??  

---
### Environment

- Fluent.Ribbon 4.5
- Windows 7
- .NET Framework 4.6.01590:

**Comment by batzen** [comment]
The build of Fluent.Ribbon does not introduce {x:null} just by building.
I don't know what you did.
If you mean that you changed things and want to revert your changes, it depends on how you grabbed the sources.
If you used git you should be able to revert your changes by using git commands, if you used the zip download of the sources you will have to download and extract the zip again to start fresh.

**Comment by Mathanvj44** [comment]
Hi,
     I reverted all those things which made by me.  And my one more doubt
is can i edit the things in the downloaded fluent ribbon code .....

   I don't have any aware of this. But i can't create a new one that's why
i edit the downloaded version...

  Can i do that??

**Comment by batzen** [comment]
I don't really understand what you are trying to do.
What do you mean with "But i can't create a new one that's why i edit the downloaded version..."?

**Comment by Mathanvj44** [comment]
Hi,

     How to change the background color for ribbon.
    If we created ribbon tabs ,some places didnt  fill the same color like
below pics.
   How to do that?
   In below pics the tab items has one color but rest of the tab contains
some other color.
   I want the same color on whole ribbon tab,  how to do that??

**Comment by batzen** [comment]
Please have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Themes/Theme.Template.xaml for an overview of which brush/color resource are available for you to overwrite.

You will most likely want to overwrite things like `Fluent.Ribbon.Brushes.RibbonTabControl.Background` and `Fluent.Ribbon.Brushes.RibbonTabControl.Content.Background`.

**Comment by batzen** [comment]
@Mathanvj44 Did that answer your question?

**Comment by batzen** [comment]
@Mathanvj44 ping
