### ISSUE TITLE
Dll file could not be found

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#619]
Hi
      While I build the project I get this error. 
      'G:\.........\Fluent.dll' could not be found error
      How to solve this error? 

---
### Environment

- Fluent.Ribbon 4.5
- Windows 7
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
I don't know what you did and Fluent.Ribbon does not contain a reference to any drive, i don't think this is an issue caused by Fluent.Ribbon.

**Comment by batzen** [comment]
@Mathanvj44 Did that answer your question?

**Comment by batzen** [comment]
@Mathanvj44 ping
