### ISSUE TITLE
How to set the mouse over background? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#620]
Hi, 
I designed a ribbon tab using ribbon group box and buttons. 
It automatically gets blue color for mouse over and dark blue for pressed. 
But I want to change that color.  
How to do that? 
---
### Environment

- Fluent.Ribbon 4.6.2
- Windows 7
- .NET Framework4.6.01590

**Comment by batzen** [comment]
Theming got a lot better in version 7.0 these things.
It's currently available as a preview version on nuget.

To change the selected foreground when your item is not part of a contextual group you can overwrite the resource `Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground`.
For mouse over foreground you can overwrite `Fluent.Ribbon.Brushes.RibbonTabItem.MouseOver.Foreground`.

When your tab is inside a contextual group you can use the properties `TabItemSelectedMouseOverForeground`, `TabItemMouseOverForeground` and `TabItemSelectedForeground` on the group.

**Comment by batzen** [comment]
@Mathanvj44 ping

**Comment by batzen** [comment]
@Mathanvj44 ping
