### ISSUE TITLE
How to set the max item in a row in gallery tag? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#624]
I create the drop down button, and if I click that drop down button it shows 5 buttons. 
But it shows the  buttons in 2rows. But I wanted in single row. 
I changed the maxitemsinrow property into 5.
But it doesn't shows in single line. 
I don't know what's happening. Lease help me out. 

---
### Environment

- Fluent.Ribbon4.6.2
- Windows 7
- .NET Framework 4.6.01590
![15359665424351892150654](https://user-images.githubusercontent.com/42540652/44978724-fecc1200-af88-11e8-8485-e7d77f91103e.jpg)

**Comment by batzen** [comment]
Could you try this with Fluent.Ribbon version 7? As far as i remember i fixed some issues regarding this in that version.
