### ISSUE TITLE
RibbonItem MenuItem Icons

### ISSUE THREAD

**Issue by PJonHar** [fluentribbon/Fluent.Ribbon#627]
Icons in designer show as red circles with a white cross, however the application is able to run and the icons show correctly.

When typing the icon resource path the XAML reports the error 'A value of type 'RibbonTabItem' cannot be added to a collection or dictionary of type 'ObservableCollection'.', however this can be cleared with a Build.

This is better than what was happening on Fluent v6, whereby the error cannot locate resource would not go away in designer, but the application ran fine (showing icons).

Any ideas?
[icons designer](https://www.dropbox.com/s/3xwaixf5vt07ouy/icons%20designer.png?dl=0)
[icons running](https://www.dropbox.com/s/2tc33680odqd9pw/icons%20ok.png?dl=0)
---
### Environment

- Fluent.Ribbon __v7.0.0.419__
- Windows __Windows 10 1803__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
That's intentional because we can't resolve those references during design time. It should display correctly in the designer if you use full pack:// Uri's.

**Comment by PJonHar** [comment]
Fairly new to WPF. Could you give an example of how I would go about achieving this? Thanks.

**Comment by batzen** [comment]
For example pack://application:,,,/YOUR_ASSEMBLY_NAME;component/Properties/Resources/AddFile.png

**Comment by PJonHar** [comment]
I have changed the path to the following. The Icon shows when running but still does not show in designer?

`<Fluent:Button Header="Login" Icon="pack://application:,,,/KUKA.RGI v3;component/Icons/user_go.ico" LargeIcon="pack://application:,,,/KUKA.RGI v3;component/Icons/user_go.ico" Height="Auto" Width="65" Margin="0,0,-1,0">
                            <Fluent:Button.ToolTip>
                                <Fluent:ScreenTip Title="User Login" Width ="250"
                                    Image="Images\user_go.png"
                                    Text="This control is disabled and has fixed width 250px"                                  
                                    HelpTopic="Help for Orange ScreenTip"
                                    DisableReason="This control is disabled to show 'disable reason' section"/>
                            </Fluent:Button.ToolTip>
                        </Fluent:Button>`

**Comment by batzen** [comment]
You could try to clear the designer cache (google for the location, i don't remember the path) and your temp folder. If that also doesn't help you are out of luck. The WPF designer is very buggy.

**Comment by GoneUp** [comment]
I had the same problem. Using the full pack: path and exchanging my .png with a .ico file cleared the error for me.

**Comment by PJonHar** [comment]
still no joy, I have tried both .png and .ico ??

**Comment by batzen** [comment]
Have you tried to clear the designer cache?

**Comment by PJonHar** [comment]
Yes, i tried deleting everything in: %LOCALAPPDATA%\Microsoft\VisualStudio\15.0_5e181f87\Designer\ShadowCache

**Comment by batzen** [comment]
Could you add a repro then? Will have a look at it when my PC is working again.

**Comment by batzen** [comment]
@PJonHar ping

**Comment by PJonHar** [comment]
Hi, what does 'Could you add a repro then?' mean?

**Comment by batzen** [comment]
A repro is a small project showing/reproduction your issue. "repro" is short for "reproduction".

**Comment by batzen** [comment]
@PJonHar ping

**Comment by PJonHar** [comment]
I have uploaded a project in the other Issue #630

**Comment by batzen** [comment]
Had a look at your application and everything looks fine at runtime.
The designer is very buggy.
Don't know what the issue should be.

**Comment by PJonHar** [comment]
so you think it is a visual studio/wpf issue?

**Comment by batzen** [comment]
sorry for the late response: Yes i think it's a bug in the designer.

**Comment by PJonHar** [comment]
Hi, I'm still having this issue within Visual Studio? Did you ever find out if it was an actual bug in designer? Do other peoples design time projects render correctly?

**Comment by batzen** [comment]
I could not reproduce your issue back then, so it's probably a bug in the designer.

> Do other peoples design time projects render correctly?

I don't know for sure, but i guess quite a few people have issues with things not rendering correctly during design time but rendering fine during runtime.

As i said: If it works at runtime but does not during design time it's a bug in the designer and you should report that issue to Microsoft.

**Comment by langeth** [comment]
I have the same problem and reported it to microsoft: 
https://developercommunity.visualstudio.com/t/xaml-designer-vs-2022-not-working-with-fluent-ribb/1658933
