### ISSUE TITLE
RibbonTabControl

### ISSUE THREAD

**Issue by PJonHar** [fluentribbon/Fluent.Ribbon#630]
Trying to use a RibbonTabControl however, the content of the RibbonTabItem does not display in either designer or application running. When the application is ran the tabcontrol does not display either?

`<Fluent:RibbonTabControl Grid.Row="0" Grid.Column="0" ContentHeight="{Binding ElementName=MainContentRow, Path=ActualHeight}" Width="{Binding ElementName=LeftTabWidth, Path=ActualWidth}" CanMinimize="False">
                        <Fluent:RibbonTabItem Header="Programs" Width="{Binding ElementName=LeftTabColumnWidth, Path=ActualWidth}">
                            <Fluent:RibbonGroupBox Header="User" HorizontalAlignment="Left" VerticalAlignment="Top">
                                <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="*"/>
                                        <RowDefinition Height="Auto"/>
                                        <RowDefinition Height="Auto"/>
                                    </Grid.RowDefinitions>
                                    <GroupBox Grid.Row="0" Header="Programs">
                                        <DataGrid/>
                                    </GroupBox>
                                    <GroupBox Grid.Row="1" Header="Program Information">
                                        <TextBlock TextWrapping="Wrap" Height="50" HorizontalAlignment="Stretch">...</TextBlock>
                                    </GroupBox>
                                    <DockPanel Grid.Row="2">
                                        <Button HorizontalAlignment="Left" Width="100">Sub Programs</Button>
                                        <Button HorizontalAlignment="Right" Width="100">Select</Button>
                                    </DockPanel>
                                </Grid>
                            </Fluent:RibbonGroupBox>
                        </Fluent:RibbonTabItem>
                    </Fluent:RibbonTabControl>`

---
### Environment

- Fluent.Ribbon __v7.0.0.419__
- Windows __Windows 10 1803__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
@PJonHar ping

**Comment by PJonHar** [comment]
Not sure what snoop is?

**Comment by batzen** [comment]
It's an application that lets you inspect wpf guis at runtime. You can find it at https://github.com/cplotts/snoopwpf

**Comment by batzen** [comment]
@PJonHar ping

**Comment by PJonHar** [comment]
Sorry for the late response, i've been on holiday.
Please see the outline of my project below. this can be used for the Icon issue also.
[KUKA.RGI v3.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2441471/KUKA.RGI.v3.zip)

**Comment by batzen** [comment]
Had a look at your application and everything looks fine.
Don't know what the issue should be.

**Comment by PJonHar** [comment]
so you think it is a visual studio/wpf issue?

**Comment by PJonHar** [comment]
@batzen do you know of another way to achieve what i i'm looking to do?

**Comment by batzen** [comment]
I don't know what you are trying to achieve as the sample application you provided looks fine.
What are you trying to achieve?
