### ISSUE TITLE
Is it possible to bind the data from external source ?

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#631]
Hi, 
     I created lot of controls like button, toggle, split buttons. And typically these controls headers are written in coding but  I need to bind the header's data from external source like excel sheet. 

    Isn't possible to do that?  

---
### Environment

- Fluent.Ribbon 4.6.2
- Windows7
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
Would be nice if you would first respond on all other of your open issues.

**Comment by Mathanvj44** [comment]
Yeah sure.....

**Comment by Mathanvj44** [comment]
@batzen I closed all the issues.  I need your answer for this issue.  Please help to sort out this issue........

**Comment by batzen** [comment]
You could use viemodels and bind the header to some property of those.
For a how to on reading data from excel you'd have to research that on your own. I'd bet there are quite a few when asking google.

**Comment by Mathanvj44** [comment]
Yeah k,  is it possible to do this using XML file instead of excel file?  I need to bind the buttons header data from XML file tags

**Comment by batzen** [comment]
That should also be possible.
