### ISSUE TITLE
How to bind the data from XML file? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#633]
Hi, 
I created a XML file with lot of tags. I need to bind that XML data into xaml button header.  Is it possible to do this? 

Ex:
XML file :
<xmlDataProvider x:key="Headerdata" XPath="/header">
<x:XData>
      <x:XData>
            <header xmlns="">
                <Bookmark>
                       <Header1>File<Header1>
                </Bookmark>
            </Header>
    </x:XData>
</Xmldataprovider>
---
This is my XML file named as 'Header_data.xml'.
I need to bind <header1> tag into button's header in run time. 

Is it possible? 
### Environment

- Fluent.Ribbon __4.6.2
- Windows 7
- .NET Framework 4.6.01590

**Comment by batzen** [comment]
It is possible, of course.
But please note that this is not a general purpose .NET/WPF/MVVM support forum.

If you want to learn the basics about WPF and bindings i suggest something different than the issue tracker here.
