### ISSUE TITLE
Null reference when pressing left or right arrow keys in bound DropDownButton

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#636]
When using a data-bound DropDownButton, the Escape button doesn't work and pressing left or right while the menu is open causes a NullReferenceException:

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Fluent
>   StackTrace:
>    at Fluent.MenuItem.OnKeyDown(KeyEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at VidCoder.App.Main()

Using this menu item:

	<fluent:DropDownButton
		x:Name="windowsRibbonButton"
		Header="{x:Static res:MainRes.WindowsMenu}"
		ItemsSource="{Binding WindowMenuItems}"
		LargeIcon="/Icons/Windows.png"
		Size="Large">
		<fluent:DropDownButton.ItemContainerStyle>
			<Style TargetType="fluent:MenuItem">
				<Setter Property="Header" Value="{Binding Definition.MenuLabel}" />
				<Setter Property="IsCheckable" Value="True" />
				<Setter Property="IsChecked" Value="{Binding IsOpen}" />
				<Setter Property="IsEnabled" Value="{Binding CanOpen}" />
				<Setter Property="InputGestureText" Value="{Binding Definition.InputGestureText}" />
				<Setter Property="Command" Value="{Binding Command}" />
			</Style>
		</fluent:DropDownButton.ItemContainerStyle>
	</fluent:DropDownButton>

---
### Environment

- Fluent.Ribbon 6.1.0.326
- Windows 10, 17134.228
- .NET Framework 4.7.2

**Comment by batzen** [comment]
This should already be fixed in version 7.0 which is currently available as a preview on nuget.
Could you try to reproduce your issue with that version?

**Comment by RandomEngy** [comment]
Yes, looks like it's fixed in 7.0 alpha. I'll open a separate issue about the escape button not working.
