### ISSUE TITLE
Setting AreTabHeadersVisible="False" on startup makes entire ribbon disappear

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#638]
When I set AreTabHeadersVisible="False" on the Ribbon, the whole thing disappears, not just the tab headers.

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0419
- Windows 10, 17134.228
- .NET Framework 4.7.2

**Comment by batzen** [comment]
I can't reproduce this using the showcase application.
Could you provide a small repro for this issue?

**Comment by RandomEngy** [comment]
Repro:
https://drive.google.com/file/d/1-ZLYoEvmpCeZr2k6gmfNBh5oU4x___wY/view?usp=sharing

**Comment by batzen** [comment]
The thing causing the issue is that it's false on start, thus no tab gets selected.
Will have a look at this.
