### ISSUE TITLE
hiding keytips

### ISSUE THREAD

**Issue by bombaymg** [fluentribbon/Fluent.Ribbon#64]
Dear sir,

i am using document editor from codeplex.it has 3 buttons on top,new open and close.all these 3 buttons show 1,2,3 as keytip.when i try to change and remove that keytips nothing happens.i use the code in vb.net.

OpenMenuItem.KeyTip = "aa"
OpenMenuItem.KeyTip = nothing

thanks

**Comment by batzen** [comment]
The quick access keytips can't be changed and are numbered automatically, in case you are talking about quick access items.
This is done in the UpdateKeyTips method of QuickAccessToolBar.

**Comment by batzen** [comment]
Do you have any further questions?

**Comment by bombaymg** [comment]
Dear sir,
no, my problem is solved,thanks for reply.

 

     On Friday, February 20, 2015 6:33 PM, Bastian Schmidt <notifications@github.com> wrote:
   

 Do you have any further questions?—
