### ISSUE TITLE
Narrator doesn't read out button headers

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#640]
1) Turn on Narrator with Ctrl+Win+Enter
2) Tab through the buttons

Expected result:
Narrator reads out headers for the buttons

Actual result:
Nothing is read out, or just "button"

Setting AutomationProperties.Name explicitly on a fluent:Button makes it work, but it would be handy to have the control be accessible "by default".

Setting AutomationProperties.Name on a fluent:DropDownButton or fluent:SplitButton doesn't work. It just never reads out anything on it.

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0419
- Windows 10, 17134.228
- .NET Framework 4.7.2

**Comment by RandomEngy** [comment]
What some of the .NET controls do to get automation text is just call .ToString() on the object. It's always there and the author of the type can decide how to implement it.

**Comment by RandomEngy** [comment]
Thanks! Is there going to be a new alpha out soon?

**Comment by batzen** [comment]
Will release a new preview to nuget tomorrow.

**Comment by batzen** [comment]
Here you go https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0529

**Comment by RandomEngy** [comment]
Thanks! Though I ran into another blocking issue. Opened https://github.com/fluentribbon/Fluent.Ribbon/issues/680 .
