### ISSUE TITLE
StackOverFlow exception on clicking Application menu button

### ISSUE THREAD

**Issue by mayankkarki90** [fluentribbon/Fluent.Ribbon#643]
I am facing a crash with StackOverFlow exception on clicking Application menu when Ribbon tab is open but not in pinned state. To better explain the steps, I am attaching a video and sample code.

(https://1drv.ms/u/s!Ahr8XhqVvaXgeToh9As-hCr2FBA)

(https://1drv.ms/u/s!Ahr8XhqVvaXgerCxr-Yds0Mlmac)

- Fluent.Ribbon __6.1.0.326__
- Windows __10__
- .NET Framework __net45__

**Comment by batzen** [comment]
This is already fixed in version 7.0 which will most likely be released in november.

**Comment by mayankkarki90** [comment]
Is there any way I can fix it at my end, any patch for it.

**Comment by batzen** [comment]
The changes needed were made in https://github.com/fluentribbon/Fluent.Ribbon/commit/c41103d7efbf2f5e2d71df3ff1b89946aebc019f
Should be possible to use that as a patch.

**Comment by mayankkarki90** [comment]
Thanks @batzen
