### ISSUE TITLE
The command ""G:\........\paket.exe" restore--reference-file "G:\.......\paket.references"" exited with code 1 . What type of error is this? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#644]
Hi, 
    I am using fluent ribbon.  But once I used this fluent ribbon in my project , I got this error. 

 #"The command ""G:\........\paket.exe" restore--reference-file "G:\.......\paket.references"" exited with code 1
 
What type of error is this??  
---
### Environment

- Fluent.Ribbon 6.1
- Windows 10
- .NET Framework 4.6.0190

**Comment by batzen** [comment]
I'd need the full error/log to say more.
What did you do before this error started to appear?

**Comment by Mathanvj44** [comment]
I just copy the folders from fluent ribbon project folder to another
project folder for using the fluent ribbon onto another project. This is
only thing I do before appear this error....

Error:

The command ""G:\..\.paket\paket.exe" restore --references-file
"G:\..\Fluent.Ribbon\paket.references"" exited with code 1.
Fluent.Ribbon.NET <http://fluent.ribbon.net/> 4.5
The command ""G:\..\.paket\paket.exe" restore --references-file
"G:\..\Fluent.Ribbon.Showcase\paket.references"" exited with code 1.
 Fluent.Ribbon.Showcase.NET <http://fluent.ribbon.showcase.net/> 4.5
The command ""G:\..\.paket\paket.exe" restore --references-file
"G:\..\Fluent.Ribbon.Tests\paket.references"" exited with code 1.
Fluent.Ribbon.Tests.NET <http://fluent.ribbon.tests.net/> 4.5

The above are the error list.

**Comment by batzen** [comment]
Which command are you executing?
Which version of the source code are you using?
Have you made any modifications to the source code? Especially in any build related files?
Have you copied all files from fluent.ribbon?
Are there any Directory.build.props files in folder levels above the ribbon code?

**Comment by Mathanvj44** [comment]
Problem solved....
I just copy the all folders and files from the fluent ribbon and paste it
into my project and then the problem is solved now.
