### ISSUE TITLE
How to use Fluent:ribbon as MDI parent?  

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#645]
Hi, 
     Is there any possible to use ribbon as MDI Parent.  
     If yes, how to use?? 
     In my existing project I had used normal ribbon as MDI Parent . And now I want to use the Fluent:Ribbon as MDI Parent. 

     Is there any possible to use as MDI Parent? 

---
### Environment

- Fluent.Ribbon 6.1.0
- Windows10
- .NET Framework 4.6.0190

**Comment by batzen** [comment]
I have never tried to use it as an MDI parent, so you would have to try that yourself. ;-)
