### ISSUE TITLE
Problems when layout is scaled

### ISSUE THREAD

**Issue by pekspro** [fluentribbon/Fluent.Ribbon#65]
I’ve added this in the test project TestWindow.xaml

        <FluentTest:TestContent.LayoutTransform>
            <TransformGroup>
                <ScaleTransform ScaleX="1.5" />
                <ScaleTransform ScaleY="1.5" />
            </TransformGroup>
        </FluentTest:TestContent.LayoutTransform>

This will make everything 50% larger. And it looks pretty good in all themes. But one problem occur when ribbon is minimized and then a tab is pressed the ribbon popups up slightly to low:

![scalingproblem](https://cloud.githubusercontent.com/assets/3163293/6175650/efaacdba-b2f8-11e4-993d-91f8106ec877.png)

I’ve figure out that the problem is the PlacementAttribute in the PART_Popup PopUp in RibbonTabControl (all themes). But I don’t know what to do next :-).

Even weirder things happens if RotateTransform is used with 15 degrees or so. But that’s not important I think :-). But scaling could actually be useful. This is something I want to use in my application someday in a distant future :-)

**Comment by batzen** [comment]
Hmm... will have a look at this at work as I think we don't have that issue...

**Comment by pekspro** [comment]
Is just noticed that if I go in Windows display settings and choice to make all object 125% or 150% I get a similar result.

**Comment by batzen** [comment]
Also got this issue at work. Will fix it soon.

**Comment by batzen** [comment]
Added zooming to the showcase application to prevent issues in the future.

**Comment by pekspro** [comment]
Nice work, the pop up seems to work better now :-). But I see a similar problem if you open a combo box, the list with the items seems also be a bit offset.

**Comment by batzen** [comment]
Fixed.

**Comment by pekspro** [comment]
Brilliant! Nice work.
