### ISSUE TITLE
Backstage right panel text is white on the BaseLight theme

### ISSUE THREAD

**Issue by jeuxjeux20** [fluentribbon/Fluent.Ribbon#651]
When the BaseLight theme is used, the backstage right panel text foreground is still white, it should be black. A possible workaround would be to set the Foreground property to black.

---
### Environment

- Fluent.Ribbon __6.1.0.326__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Could you try the pre-release of version 7? It should be fixed there.

**Comment by batzen** [comment]
@jeuxjeux20 ping

**Comment by jeuxjeux20** [comment]
**PONG**

yes fixed 
![image](https://user-images.githubusercontent.com/16415180/48014215-799ae000-e126-11e8-885c-21f5dbdf8ad8.png)

**Comment by batzen** [comment]
Great.
