### ISSUE TITLE
Can't set foreground color in showcase app

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#654]
https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon.Showcase/RibbonWindowColorized.xaml

Altering the foreground color away from black here doesn't work.

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0456
- Windows 10
- .NET Framework 4.7

**Comment by batzen** [comment]
Which foreground color do you mean?

**Comment by RandomEngy** [comment]
I'm trying to change the color of the text on the ribbon buttons. I'm not sure which resource is supposed to control it but I tried changing every one of them and none of them had any effect on it.

**Comment by batzen** [comment]
It should be Fluent.Ribbon.Brushes.LabelTextBrush

**Comment by RandomEngy** [comment]
Thanks! That should probably be one of the resources listed in the file.

If I try to set it in a child resource dictionary (My theme dictionary) it doesn't seem to work. But if I keep an entry in the base resource dictionary and update it programmatically it does work.

    this.Resources["Fluent.Ribbon.Brushes.LabelTextBrush"] = new SolidColorBrush(Colors.White);
