### ISSUE TITLE
Backstage icons not showing

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#656]
- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __7__
- .NET Framework __4.5.2__

The title says it all. I also attached a repro.
[CTabsTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2505665/CTabsTest.zip)

**Comment by batzen** [comment]
The mouseover should be fixed with https://github.com/fluentribbon/Fluent.Ribbon/commit/f2c89aff1b362f8c3421c11bdadd7a556b7c5972 which was made after alpha0456.

I don't know what you mean with the icons part.

**Comment by bochelie1000** [comment]
I thougth that I could place some icons on the left side of buttons in the Backstage menu. I cant see any of my icons showing. I you look at the code, there should be some icons.
