### ISSUE TITLE
fluent:Button.LargeIcon are rendered for only first RibbonTabItem

### ISSUE THREAD

**Issue by madmonk88** [fluentribbon/Fluent.Ribbon#658]
I have three RibbonTabItem's. Each with a RibbonGroupBox containing few buttons.
I am setting all buttons with large icons using mahapps icon packs or an image.
**But by default the icons are visible for only the first RibbonTabItem.**
I also change the RibbonTabItems order to confirm all the icons pointed are correct.

---
### Environment
- Fluent.Ribbon  v6.1.0.233
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
Could you try to reproduce this issue using the preview of version 7.0?

**Comment by dsmprojects** [comment]
![fluentissue](https://user-images.githubusercontent.com/25492265/49822404-0bf85a00-fd4b-11e8-9a60-ffe7c55be7fb.png)
I have a similar issue where only the last icon is showing.

 <Fluent:RibbonTabItem Header="Home">
                <Fluent:RibbonGroupBox Header="Group">
                    <Fluent:Button Header="Red" Icon="{StaticResource Gears}" LargeIcon="{StaticResource Gears}" />
                    <Fluent:Button Header="Green" Icon="{StaticResource Gears}" LargeIcon="{StaticResource Gears}" />
                    <Fluent:Button Header="Blue" Icon="{StaticResource Gears}" LargeIcon="{StaticResource Gears}"/>
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>

In the code only the last button displays the icon.
The icons are SVG data in the StaticResouce which works fine with normal WPF controls.

Attached is a picture of the test app running.
This also happens is in 7.0 version.
![fluentissue](https://user-images.githubusercontent.com/25492265/49822427-216d8400-fd4b-11e8-882f-5a163217e04b.png)

**Comment by batzen** [comment]
Could you attach that test app?

**Comment by dsmprojects** [comment]
Yes

[FluentSVG.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2669420/FluentSVG.zip)

**Comment by batzen** [comment]
So i just had a look.
Just try to change your test app by removing the ribbon elements and change the inner buttons to
```
                <Button Width="100" Height="100" Content="{StaticResource Gears}" />
                <Button Width="100" Height="100" Content="{StaticResource Gears}" />
                <Button Width="100" Height="100" Content="{StaticResource Gears}" />
```
It will also only render the last button "icon" because a control, which `Path` is, can only have one parent.
If you change the ribbon button icons to the same code you used for the other brushes (Rectangle and VisualBrush) they will work as intended. Or you could try to use a `DrawingImage` instead of a simple `Path`.

Why do you expect the ribbon to allow this while you work around the issue on regular buttons?

@madmonk88 Would be nice to get a reply from you to verify the issue you reported, in case it's not the same as the one @dsmprojects has.

**Comment by batzen** [comment]
@dsmprojects In fact i could make using a path/shape on the ribbon buttons work out of the box. I'll try to extend the ObjectToImageConverter.

**Comment by dsmprojects** [comment]
Thank you.

I'm just switching to StaticResource and I do not understand what it is really doing.  I was thinking it was being replaced by the full path to the resource.  I was using Images\picture.png before and it worked fine.  I'm going to try and see what your ObjectToImageConverter is doing now.  I'm updating a monitor program I wrote for work that uses the Fluent Menu and I wanted a more consistent look to the button artwork so I wanted to switch to SVG.  Thanks for the help and for a really nice Ribbon Menu!!!

**Comment by batzen** [comment]
If you set Icon to a file/resource path the converter creates a new Image object.
If you set Icon to a Path object the converter essentially does nothing and just returns that object as it is. As Path is a FrameworkElement it can only have one parent. When using the same Path object in multiple places the last user/consumer of that object gets the parent and this causes your Path object only to be visible in one place.
If i extend the converter to convert Path/Shape objects to a DrawingImage, or something like that, it should be possible to display it in multiple places.

There is also more logic inside the converter to return frozen instances of images to enable reuse and also logic to extract images in the desired size from multi-frame images.

**Comment by madmonk88** [comment]
HI @batzen ,

I updated the nuget packaged to recent version and still face this issue. 
When using physical image, icon is rendered for other tabs. But when I am using xaml icons as visual brush then for only first tab the icons are rendered. 
Read through your above explanations. Could you please update if its the same case even though I am using different visual brush/icons for each items (unlike the above example of all being same gear icon).

FYR, I have provided sample screenshots for clear understanding.
Actual Tab Order
![image](https://user-images.githubusercontent.com/18680716/49880372-06396c00-fe52-11e8-9d96-7ff5abbb581e.png)

After Changing Tab Order 
![image](https://user-images.githubusercontent.com/18680716/49880486-4a2c7100-fe52-11e8-9418-63cff0d70d6c.png)

As you can see except the first tab item, the remaining visual brush are empty.

![image](https://user-images.githubusercontent.com/18680716/49881983-99c06c00-fe55-11e8-8590-52f95a4c1aa2.png)

**Comment by batzen** [comment]
Could you attach your project so in can check what's wrong in your case also?

**Comment by batzen** [comment]
@madmonk88 ping
