### ISSUE TITLE
ContextualTabs visibility problem

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#660]
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456 and before__
- Windows __7__
- .NET Framework __4.6.1 and lower__

There is an issue that ContextualTabs or Tabs will not be drawn correctly or even be shown if the visibility is set in begin code on startup.

I attached a repro.  To reproduce:

-Start the application.
-Click on Buttons 1 and 2 on the home tab. 
-This will change the next tabs. 
-This works fine. You will see the Tab with header 11111 and the tab with header 22222 depending which button you click.

-Now stop the application.
-Go to the behind code and activate the 3 lines after the InitializeComponent method.

-Restart the application.

-Click button 1 and 2 on the Home tab. 
-See how the next tab is not working correctly.

Once again I realy appreciate all the effort you put into this great Ribbon. 

Regards

[CTabsTest 2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2514077/CTabsTest.2.zip)

**Comment by batzen** [comment]
Well, i am not sure i really should consider this a bug in the ribbon.
The problem with your code is that it sets a local value for `Visibility` and there are style triggers which try to modify the value, but as it's a local value the triggers can't modify the value as it's impossible to overwrite local set properties from style triggers.

What's your use case for this? What are you trying to achieve?
One way to solve your issue would be to use an inherited style and set the values from style setters instead of using a local value.

**Comment by bochelie1000** [comment]
Well I was just trying to change the visibility of the tabs when the user clicks on a button in the ribbon. My solution was to not change the visibility in the Initialize method. After the app is loaded I can change the visibility in behind code without any problem as you can see in the button_click method. That is why I thought it was a bug.

**Comment by batzen** [comment]
In your app the button click only modifies the groups visibility.
You can control/trigger visibility in two ways:
- hiding the group hides all tabs contained in the group
- hiding all tabs of a group hides the group

If visibility is set manually on a tab or group that value can't be overwritten be the style triggers.

**Comment by bochelie1000** [comment]
Ok, good to know.

**Comment by batzen** [comment]
Do have any further questions or can we close this issue?

**Comment by bochelie1000** [comment]
No. It can be closed. Thanks.

**Comment by batzen** [comment]
As this issue was reported again with #673 i had another look and found a solution.

**Comment by bochelie1000** [comment]
Great! Thanks!
