### ISSUE TITLE
In ribbon gallery

### ISSUE THREAD

**Issue by JimDepoorter** [fluentribbon/Fluent.Ribbon#661]
Hello, 

I have some problems with the in ribbon gallery items. The content is center aligned in the in ribbon gallery and the popup of it. Is it possible to set the horizontal alignment to the left? Is it also possible to stretch the horizontal alignment in the popup window?

![2018-10-25 14_59_25-](https://user-images.githubusercontent.com/44469623/47501798-ab7a8f80-d866-11e8-9f80-73d0affae124.png)

Thanks!
Jim

**Comment by batzen** [comment]
Will track this issue in #666.
