### ISSUE TITLE
SplitButton.IsChecked deleting binding upon click.

### ISSUE THREAD

**Issue by jeuxjeux20** [fluentribbon/Fluent.Ribbon#664]
When `SplitButton.IsChecked` is bound, the binding works correctly until the button is clicked, the binding gets deleted and is then no longer updated (to the viewmodel for example).

Example where the problem happens:

```<fluent:SplitButton IsCheckable="True" IsChecked="{Binding IsButtonChecked, Mode=OneWay}"/>```

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by jeuxjeux20** [comment]
Wait nevermind i forgot how oneway bindings are getting removed when changed. lol. i'm dumb

**Comment by batzen** [comment]
What's your use case for using a oneway binding in this case?

**Comment by jeuxjeux20** [comment]
In this case it was for  being a shortcut to a gallery item, but i totally forgot about setters in properties.

**Comment by batzen** [comment]
Happens to all of us ;-)
