### ISSUE TITLE
Fluent.Ribbon.Showcase.exe not working ( 7.0.0-alpha0486 )

### ISSUE THREAD

**Issue by Drachenkaetzchen** [fluentribbon/Fluent.Ribbon#665]
When building `Fluent.Ribbon` from `git devel`, Fluent.Ribbon.Showcase.exe throws the following error upon launch:

![image](https://user-images.githubusercontent.com/162974/48579655-66092980-e91d-11e8-8d5b-1861bc477424.png)

The URL I get redirected to when clicking the `YES` button is:

`http://dotnetsocial.cloudapp.net/redir?o1=SHIM_NOVERSION_FOUND&version=(null)&processName=Fluent.Ribbon.Showcase.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0`

Noteworthy information:

- The dialog box pops up twice
- It seems that the version number refers to the .net framework CLR 4.0, when I attempt to install the runtime, I get the info that it is already installed
- I could not find any reference to that framework version in the project

### Steps to reproduce
- Clone the repository with the `devel` branch
- Open the solution file `Fluent.Ribbon.sln`
- Use "Rebuild solution" to rebuild
- Run `bin\Fluent.Ribbon.Showcase\Release\net45\Fluent.Ribbon.Showcase.exe` or `bin\Fluent.Ribbon.Showcase\Release\net462\Fluent.Ribbon.Showcase.exe`

---
### Environment

- Fluent.Ribbon 7.0.0-alpha.486+Branch.develop.Sha.f7319f264a5d7a8d9eb71e39a0f2a8c87aecbafb
- Windows 10 Home Edition OS Build 17134.407
- .NET Framework 4.5 and 4.6.2 installed

**Comment by batzen** [comment]
Fixed this issue https://ci.appveyor.com/project/batzen/fluent-ribbon/builds/20336881/artifacts.
Was a bad combination of an outdated Fody version (which i already updated locally) and a mistake i made while moving thing from Directory.build.props to Directory.build.targets.
