### ISSUE TITLE
InRibbonGallery DropDown not layouting correctly

### ISSUE THREAD

**Issue by MenzenJ** [fluentribbon/Fluent.Ribbon#666]
In f2c89aff1b362f8c3421c11bdadd7a556b7c5972 (current revision in develop branch) the InRibbonGallery DropDown is not sizing and placing its children correctly.

This behavior has changed since version 6.1.0. 
I guess this was unintended, thats why i created this issue.

Steps to reproduce:
1. Open ShowCase App
2. Change to "Gallery"-Tab
3. Open any InRibbonGalery DropDown
4. Resize the drop down
5. See items centered and "jumping elements" on initial resize
 - Items centered see any grouped InRibbonGallery DropDown
 - To make the jumping more visible change the MaxItemsInDropDownRow to 1 for the last  InRibbonGallery in the "Without Grouping" RibbonGroupBox
 
![before resize](https://user-images.githubusercontent.com/44610481/48624871-e4ada780-e9ad-11e8-96b1-e2c749557929.PNG)
![after resize](https://user-images.githubusercontent.com/44610481/48624873-e7100180-e9ad-11e8-9ba2-836e59b0feac.PNG)

---
### Environment

- Fluent.Ribbon __Commit f2c89aff1b362f8c3421c11bdadd7a556b7c5972__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
That's of course not intended ;-)

**Comment by jeuxjeux20** [comment]
666 😓

**Comment by batzen** [comment]
This issue was introducing by 82351d868a0ddeec3b036ed8db2aa5388305188e and 8b458b1cfc5e440f54778c808142fffa67a23978.
Now i just have to find a way to fix all at once...

**Comment by batzen** [comment]
As a reference for me #542
