### ISSUE TITLE
Backstage below caption bar?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#669]
Just upgrade an old project to v6.1. Backstage displayed below caption:
![backstage-offset](https://user-images.githubusercontent.com/958469/49027673-06264480-f1a1-11e8-98b6-7d6f5cc313f5.png)

I looked through all styles, and I can't find any setting that differs from your showcase project. Ideas?

---
### Environment

- Fluent.Ribbon __v6.1.0.326__
- Windows __7 SP1__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Are you using a `RibbonWindow`?
The backstage in the screenshot is also missing the back button, or am I missing something?

**Comment by znakeeye** [comment]
Yes, actually I inherit `RibbonWindow` for my shell view. The ribbon looks good. Only the backstage shows this caption bar issue, and **only before the ribbon has initialized**. Using v3.6 I could not drag the caption bar (but it looked correct) which has now been resolved.

Thus, the first time - before the `MainView` is shown - my `RibbonWindow` shell is displayed without the "Back" button. _After_ the main view with the ribbon has shown, clicking the `File` menu indeed shows a correct backstage.

**Comment by batzen** [comment]
Could you try to use `StartScreen` for your start experience?
It's designed to be used for that purpose.

If you can't use the `StartScreen` for whatever reason it would help a lot to get a repro showcasing your issue, so i can fix it.

**Comment by znakeeye** [comment]
Will use `StartScreen`. Thanks. (Turned out this view was not a backstage...)

**Comment by znakeeye** [comment]
I analyzed this a bit further. Something changed between `v3.6` and `v7`.

**v3.6** has a `Grid` containing both `Part_TitleBar`, `PART_ContentPresenter` and `PART_WindowCommands` - all placed at `Grid.Row="0"`. Thus, the content will indeed place itself at the top.

**v7** has a `DockPanel` for the caption bar and below it there is this `PART_ContentPresenter`. Thus, the content will be placed below the caption bar.

**Is this change by design?**

**Comment by batzen** [comment]
This was changed in version 5.0.0 with https://github.com/fluentribbon/Fluent.Ribbon/issues/349 to allow usage of `Ribbon` outside of a `RibbonWindow`.
