### ISSUE TITLE
TextOptions.TextFormattingMode="Display" implies pixel error

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#672]
After upgrading from v3.6 I got this pixel error. As you can see, the letter `'g'` is not completely visible (both when unselected and selected).

<img alt="button-size-problem" src="https://user-images.githubusercontent.com/958469/49148459-bada7600-f307-11e8-943f-3899c542b463.png">

Note that this problem only occurs if the following conditions apply:

- <ShellView ... **`TextOptions.TextFormattingMode="Display"`** ... >. More about this setting [here](https://blogs.msdn.microsoft.com/llobo/2009/10/21/new-wpf-features-textformattingmode-for-clear-text/).
- Button has its `BorderThickness` set to `1`.

Using `Snoop` I can see that the `TwoLineLabel` is rendered correctly. Its parent is a `StackPanel`, and then there is a `Border` with `BorderThicknes="1, 1, 1, 1"`. Using Snoop, I can change that thickness to `0` and the problem is resolved!

**Where does this new border come from?** Maybe I can remove the border until further notice...

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
I can't reproduce this using the latest preview and the showcase application.
Any chance you could provide a repro for that?
The border is used for mouse over effects etc..
