### ISSUE TITLE
Fluent Button adding text

### ISSUE THREAD

**Issue by lightlike** [fluentribbon/Fluent.Ribbon#675]
Fluent Button is adding the Text "Translated" to the end of all Fluent Buttons and ToggleButtons.

`Header="{lang:Translate Painter.Pencil}"`

Complete Xaml code at: [Drachenhorn](https://github.com/Drachenhorn-Team/Drachenhorn/blob/master/Drachenhorn.Desktop/Views/CoatOfArmsPainterView.xaml)

![image](https://user-images.githubusercontent.com/12970722/49233134-a379b680-f3f5-11e8-8e8c-2f95da0db302.png)

Translate Extension only returns "Stift" this also does not happen on all Fluent-Controls.

---
### Environment

- Fluent.Ribbon v6.1.0.326
- Windows 10
- .NET Framework 4.6.1

Maybe also relevant: MahApps.Metro (I do not remember if this was the case before I added Metro)

**Comment by lightlike** [comment]
Sorry. My mistake. I forgot to remove testing code.

**Comment by batzen** [comment]
No problem. ;-)
