### ISSUE TITLE
Caption bar height is incorrect!

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#676]
In `v7` the height of the caption bar is **incorrect**. Maybe it is correct on a system with `DPI` set to 100%, but that's quite rare these days (Windows 10 usually defaults to 125% or 150%).

Refer to the `RibbonWindowStyle`:
```xml
<Setter Property="TitleBarHeight"
        Value="{DynamicResource {x:Static SystemParameters.WindowCaptionHeightKey}}" />
```

This value must be converted using the system's `DPI` setting. E.g.:

```c#
double captionBarHeight = SystemParameters.WindowCaptionHeight;

Matrix? matrix;
var source = PresentationSource.FromVisual(element);
if (source != null)
{
    matrix = source.CompositionTarget?.TransformToDevice;
}
else
{
    using (var src = new HwndSource(new HwndSourceParameters()))
    {
        matrix = src.CompositionTarget?.TransformToDevice;
    }
}

if (matrix.HasValue)
{
    captionBarHeight *= matrix.Value.M22;
}

// use captionBarHeight
```

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
I just tried scaling it and it looks awful as it gets way too high.
Have you tried it yourself?
