### ISSUE TITLE
Ways to contribute?

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#678]
Hello,

We would like to contribute to your package, as a thank you for your hard work. Could you please create an open collective page or do you prefer a different method to take donations?

**Comment by batzen** [comment]
@GeertvanHorrik It's been a while but as github now offers/will offer sponsoring (https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/) i will try it that way and already registered myself.

Will post here again as soon as i am accepted.

**Comment by batzen** [comment]
I can finally, after my employer gave his ok, participate in github sponsors.
So if you want to contribute using that way you can now do so ;-)
https://github.com/sponsors/batzen

**Comment by GeertvanHorrik** [comment]
I already sent an email to GitHub if we can be a sponsor as a company instead of one of us personally having to sponsor. Hopefully we will be able to do this soon :)
