### ISSUE TITLE
Issue setting Button LargeIcon

### ISSUE THREAD

**Issue by goto3** [fluentribbon/Fluent.Ribbon#681]
Hello, I have an issue trying to set a button Icon, my XAML code:

![image](https://user-images.githubusercontent.com/16456164/50517466-3c503000-0a8f-11e9-9fb0-d63de1552a80.png)

Notice the line is showing a problem, the strange thing is, the image is displayed correctly but it throws a compile error: 

![image](https://user-images.githubusercontent.com/16456164/50517518-6dc8fb80-0a8f-11e9-96b3-97ecb496869a.png)

I tried with LargeIcon="pack://application:,,,/resources/addUser.png", it displays the image but same compile error.

![image](https://user-images.githubusercontent.com/16456164/50517700-3d359180-0a90-11e9-801f-5295c829b222.png)

Thanks

---
### Environment

- Fluent.Ribbon 6.1.0.326
- Windows 10
- .NET Framework 4.6

**Comment by batzen** [comment]
I made some improvements to the converter responsible for converting these shortcut paths to real images in version 7.0. Could you try the pre-release from nuget and check if you see an improvement?
The converter now will, if it can't locate a resource, display a warning icon at design time and an exception at runtime if it really can't find the resource.

Aside from that what you describe is not a compile time error but an intellisense/designer error instead.

**Comment by goto3** [comment]
> I made some improvements to the converter responsible for converting these shortcut paths to real images in version 7.0. Could you try the pre-release from nuget and check if you see an improvement?
> The converter now will, if it can't locate a resource, display a warning icon at design time and an exception at runtime if it really can't find the resource.
> 
> Aside from that what you describe is not a compile time error but an intellisense/designer error instead.

Yeah, that fixed the intellisense error but it shows like this: 
![image](https://user-images.githubusercontent.com/16456164/50518601-38bfa780-0a95-11e9-8136-8339595bac73.png) as you said.

I must be doing something wrong, nobody seems to have this issue.

Thanks

**Comment by batzen** [comment]
Guess why i implemented that "error" icon. Many people ran into this issue.
One thing you could try is to use a hard resource path.
So changing `"pack://application:,,,/resources/addUser.png"` to `"pack://application:,,,/Arcomat;component/resources/addUser.png"` should fix the issue.

**Comment by goto3** [comment]
> pack://application:,,,/Arcomat;component/resources/addUser.png

you are the man! that fixed it thank you very much
