### ISSUE TITLE
Update Fluent 5 to 6.1

### ISSUE THREAD

**Issue by langeth** [fluentribbon/Fluent.Ribbon#682]
Fluent:Button Icon="/Assemblyname:component/Folder/icon.png" will not show at DesignView 

<Fluent:Button x:Name="TestName"
                                       Fluent:KeyTip.Keys="A"
                                       CanAddToQuickAccessToolBar="False"
                                       Click="Handle_Button_Click"
                                       Header="Test"
                                       Icon="/test.assembly;component/Images/icon.png"
                                       Size="Middle"
                                       Tag="Test">
at Errorlist are show: File or Assembly "test.assembly, Culture=neutral" or a Dependency not found.
with Version 5.0.2.46 are no errors shown.

---
Visual Studio 2017

- Fluent.Ribbon __v6.1.0__
- Windows __10__
- .NET Framework __4.6__

**Comment by batzen** [comment]
Could you test the same with the preview version of 7.0?
It should display an error icon at design time if an icon can not be found during design time and throw an error at runtime if an icon can not be found.

The icon was not visible during design time in version 5.0.2.46 too, or was it visible?

The converter responsible for converting these "short" resource paths to real resource paths returns a frozen instance of the image starting with version 6.0 to avoid problems in case icons are re-used. When the frozen instance is created WPF trys to access the resource which causes the error you see. If you use the full `pack` URI the error should go away in all versions.

**Comment by langeth** [comment]
At 7.0 i don't see the real icons but all red X-Cross icons and I don't get Errors at Errorlist. At runtime is all ok. I must at first create a sample project. I test it a the moment at my real project.

**Comment by langeth** [comment]
I found the issue. There is a hidden folder .vs with sqlite Databases. I delete this folder and now all icons will be shown.

**Comment by batzen** [comment]
So your issue is resolved?

**Comment by langeth** [comment]
Yes it is resolved.
