### ISSUE TITLE
Ribbon Menu not working inside user control

### ISSUE THREAD

**Issue by surajlk** [fluentribbon/Fluent.Ribbon#684]
I am using a user control to place the ribbon using a ContentPresenter via my main WPF window. Everything seems to be perfectly working except when clicking a ribbon menu button from the backstage, it does not slide off automatically.

When I place the ribbon directly on the main window everything works fine as usual. How to fix this issue please. Thanks
[RibbonTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2752431/RibbonTest.zip)

---
### Environment

- Fluent.Ribbon __v6.1.0.326_
- Windows 7
- .NET Framework 4.6

**Comment by batzen** [comment]
That's strange. Will investigate this issue.

**Comment by surajlk** [comment]
Great… it works with ContentControl.

Perhaps as you said it might be a behavior of ContentPresenter as it is supposed to be used with templates not to host content directly!

 

Nevertheless it’s working. Thank you so much.

Suraj
