### ISSUE TITLE
The Twoline Header was not worked?

### ISSUE THREAD

**Issue by Mathanvj** [fluentribbon/Fluent.Ribbon#687]
I am using the lot of buttons, dropdowns and splitbuttons. And i want to set the header as Twolines for some Buttons. Below was the code for one button but it not worked. Please resolve this.

<Fluent:Button LargeIcon="pack://application:,,,/Fluent.Ribbon.Showcase;component/Images/Yellow.png"
SizeDefinition="Middle"
Icon="pack://application:,,,/Fluent.Ribbon.Showcase;component/Images/Yellow.png                       x:Name="btn_North">
<Fluent:Button.Header>
<Fluent:TwoLineLabel Text="North Direction"
    HasTwoLines="True">                                               
 </Fluent:TwoLineLabel>
</Fluent:Button.Header>
</Fluent:Button>
---
### Environment

- Fluent.Ribbon 4.6.2
- Windows10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
You can't use a two line label when your control is set to middle size.
