### ISSUE TITLE
Open Fluent error

### ISSUE THREAD

**Issue by VratislavBelsky** [fluentribbon/Fluent.Ribbon#689]
Open Fluent error
 I am sorry I can't English
after download Fluent.Ribbon develop and unpacking open project
get this error message and project not open

Bělský
![fluent ribbon error1](https://user-images.githubusercontent.com/32303088/51807780-d45a5880-228b-11e9-98be-c47469ff0223.jpg)
![fluent ribbon error2](https://user-images.githubusercontent.com/32303088/51807781-d45a5880-228b-11e9-94be-cbe97ba10b4e.jpg)

**Comment by batzen** [comment]
You need at least Visual Studio 2019 and the preview of .NET core 3.0.
You can get the .NET core 3.0 preview from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe
