### ISSUE TITLE
Ribbon Title not update its position

### ISSUE THREAD

**Issue by QuantumDeveloper** [fluentribbon/Fluent.Ribbon#69]
If I make window very small - less than length of title, then after restoring window size, ribbon title will stay in the left corner instead of moving to the center of the ribbon.
This issue still reproducing in 3.3.0. 
To move title to the center, you need to hide/show ribbon content with arrow in rigth corner. After that title moves in center of the window.

**Comment by batzen** [comment]
I can't reproduce this issue.
Could you create a repro for this issue?

**Comment by QuantumDeveloper** [comment]
https://onedrive.live.com/?cid=650F345C1F75A314&id=650F345C1F75A314%21105

here is my app.
You dont actually need to make window small, you need just start resizing window with right side and Titile will jump to the left side immediately.
To restore you need hide/show ribbon.

**Comment by batzen** [comment]
Strange. Can reproduce this in your application but not in the showcase application. Will take me some time to figure out whats causing this.
