### ISSUE TITLE
Problem with theming and Backstage button 

### ISSUE THREAD

**Issue by vogelor** [fluentribbon/Fluent.Ribbon#690]
i created a theme and activated it.
the theme itself works BUT NOT at the Backstage - Tab. this tab remains blue

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0586
- Windows 10
- .NET Framework 4.7.2

### Anhänge
[theme.xaml
![ribbon](https://user-images.githubusercontent.com/1830557/52216180-f9efef00-2895-11e9-9a2e-e69e00803c4d.png)
](https://github.com/fluentribbon/Fluent.Ribbon/files/2828528/theme.txt)

**Comment by batzen** [comment]
That's not a full theme you have there.
There are separate brushes/colors for many things in the ribbon.
It's not only the backstage button but also the tab header which has a wrong color.
The showcase application has a theme generator which generates themes the same way it's done during compile time of the ribbon.

Just open the showcase application and select the "Styles" tab inside the window and create your theme there. ;-)

**Comment by vogelor** [comment]
yes - you are right. i did not get the showcase of v7 working. so i downloaded showcase of v6. now i see, they are NOT compatible. but i can't get showcase of v7 working. can you please be so kind and generate me a theme with the primary color #8FC033. That is all i need ;-)

**Comment by vogelor** [comment]
C:\tmp\Fluent.Ribbon-develop\Fluent.Ribbon\Fluent.Ribbon.csproj : error  : Die Projektdatei ist unvollständig. Die erwarteten Importe sind nicht vorhanden.

**Comment by batzen** [comment]
You need VS2019 to build version 7.0 as i am already using the .net core 3.0 sdk in the projects. But you can download a compiled version from the appveyor build. There ulis a separate showcase zip in the artifacts.

**Comment by vogelor** [comment]
i am already using VS2019 - but i had no chance to open it. i can open the v6 Showcase but NOT the v7. i took a look at the theme - files and made it "by hand". Now it works fine!

DANKE DIR!

**Comment by batzen** [comment]
You need VS2019 and the .net core 3.0 sdk from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe. ;-)

Bitteschön! ;-)
