### ISSUE TITLE
Ribbon Area Height question

### ISSUE THREAD

**Issue by wslpdgg** [fluentribbon/Fluent.Ribbon#693]
**Place your issue description here.**
![image](https://user-images.githubusercontent.com/7911356/52391699-90602280-2ad9-11e9-9f99-bb1639b56f49.png)
when i  click the RibbonMinisizeButton, is active "IsMinimizedChanged" event ,  the RibbonArea Status is minimize, but in this event ,i got the wrong ActualHeight: like this pic show:

![image](https://user-images.githubusercontent.com/7911356/52391748-e1701680-2ad9-11e9-8fc6-db09ab292470.png)

when i click the minisizeButton again, the RibbonArea is Minimized ,but the actualHeight is like this:
![image](https://user-images.githubusercontent.com/7911356/52391805-2bf19300-2ada-11e9-88a8-daad5371499e.png)

so, in the "IsMinimizedChanged" , i can get right isMinimizeStatus, but opposite the actualHeight.

how  can i get the right value?

thanks

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v6.1.0__
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
The event is fired at the right time.
The problem you have here is that the bound value, which controls the visual state, is not yet updated.

If you need the updated size values one possible solution would be to listen to `IsMinimizedChanged` and run your size dependent code asynchronous in the current dispatcher.

**Comment by wslpdgg** [comment]
thanks,it's has been resolved
