### ISSUE TITLE
KeyTips DropDownButtons

### ISSUE THREAD

**Issue by langeth** [fluentribbon/Fluent.Ribbon#694]
Not all KeyTips will show at DropDownButtons

<Fluent:Ribbon>
            <Fluent:RibbonTabItem Header="Test">
                <Fluent:RibbonGroupBox Header="Test1">
                    <Fluent:DropDownButton Header="AuswahlA"
                                           KeyTip="A">
                        <Fluent:Button Header="Text1"
                                       KeyTip="A"/>
                        <Fluent:Button Header="Text2"
                                       KeyTip="B"/>
                        <Fluent:Button Header="Text3"
                                       KeyTip="C"/>
                        <Fluent:Button Header="Text4"
                                       KeyTip="D"/>
                    </Fluent:DropDownButton>

                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
        </Fluent:Ribbon>

Result:
![image](https://user-images.githubusercontent.com/20537969/52570236-3205ad80-2e13-11e9-9a80-e716262ab3e7.png)

---
### Environment

- Fluent.Ribbon __v6.1.0236__
- Windows __10__
- .NET Framework __4.6__

**Comment by batzen** [comment]
As far as i remember i fixed this in version 7.0. Could you try to reproduce this with the preview of version 7.0?

**Comment by langeth** [comment]
Yes it is fixed with version 7.0 Alpha. Is there a timescale when version 7.0 will go to stable?

**Comment by batzen** [comment]
Early in march. Had to delay it from early January because i found some issues which are fixed now but i have to do some final testing and am on vacation next week.

**Comment by langeth** [comment]
Thanks a lot.
