### ISSUE TITLE
[Feature] Simplified Ribbon

### ISSUE THREAD

**Issue by Splitwirez** [fluentribbon/Fluent.Ribbon#695]
As discussed on Gitter, I think it might be worth looking into adding support for a Simplified Ribbon. For reference, that's this variant of the Ribbon:
![image](https://user-images.githubusercontent.com/34009058/52874728-61bcfa00-3120-11e9-9acc-8de1e324db6a.png)
It's more compact, simpler, and is intended only to display more popular commands.

I believe this could be implemented through an additional property on the Ribbon control, to specify whether or not the Ribbon is in Simplified mode. RibbonGroupBoxes would then use a DataTrigger in their style to use a different template, which contains only a separator and a Panel (either a horizontal StackPanel or some kind of specialized panel, depending on how hiding less popular commands is dealt with). Speaking of hiding less popular commands, I suspect that that could be done using either a new property in IRibbonControl or a new AttachedProperty, coupled with either a specialized panel which acts like a horizontal StackPanel but hides children based on the property, or though a trigger in each control's style (which sets Visibility to Collapsed as needed, and likely also supply custom templates for the Simplified mode...for some, we could get away with forcing the size to "middle", but this would probably look...sub-par, at best).

One other thing to note is that the Simplified Ribbon - Microsoft's version, atleast - uses an icon size inbetween the traditional "small" and "large" sizes. I can't say for sure but they appear to be 24x24 in resolution. I suppose this would warrant a third "MediumIcon" property for the Ribbon controls?

As I said, I'm game to try to implement this myself, but prior discussion necessitated creating an Issue which explains my plan.

**Comment by batzen** [comment]
Will answer on the 26th as i am on vacation right now. If don't answer on that day feel free to ping me as i might have forgotten that i wanted to answer. 😉

**Comment by Splitwirez** [comment]
@batzen Today is the 26th, pinging as requested :P

**Comment by batzen** [comment]
Just had a look at how it works in Outlook.
These are the things i noticed so far:
- We'd need the new icon size you already mentioned
- I guess the current triggers for the sizes would need to be context aware as in aware of the current mode for the ribbon "full" or "simplified" as the controls in outlook are 
- The new panel control would have to have an overflow button/area. We could copy the overflow logic from the quick access control for this.
- If a group gets collapsed it's moved to the overflow panel and it's children become regular menu items. I have no idea how we should implement this. It wouldn't be a problem for button like controls that have a command, but if people rely on the click event it might get difficult/impossible. But the same, regarding click etc. already applies to the quick access items.
- There seems to be a new group like concept (just have a look at the quick steps "group". It's like a group with some kind of direct menu items. I'd consider this a new type of control or maybe we could solve this by using a Gallery with menu items.
- TextBox like controls would need an watermark. We could copy the code from MahApps.Metro for this or move the code from MahApps.Metro to ControlzEx so it could be shared. Styling would have to be done on our side either way.
- In Outlook the items displayed in the full vs simplified ribbon are not the same. We could solve this by adding flags like "VisibileInSimplifiedView" and "VisibleInFullView" to each control.
- Add a way to switch between the full and the simplified view if switching should be allowed (should also be a new flag somewhere) by the app developer.

If you want to give the implementation a try and want to start i'd suggest the following:
- Create a new WIP (work in progress PR)
- Create a new Window in the showcase application and use the simplified view there
- Add the basics (panel, overflow logic etc.)
- Modify the styles for button, splitbutton and dropdownbutton (those should be the easiest ones) and add samples to the new showcase window
- Ask for feedback as often as you want during your progress ;-)

This way i can keep track of your progress and raise suggestions as soon as possible and you don't waste much time implementing things which might collide with my general idea of the ribbon code.

**Comment by Splitwirez** [comment]
Sorry for the lack of follow-up, I've done a bit of toying around with this feature, but hadn't yet figured out how to create a WIP PR. That has changed now.

https://github.com/fluentribbon/Fluent.Ribbon/pull/707

I shall await confirmation as to whether or not I'm on the right track so far.

**Comment by Razzile** [comment]
Has anyone had a look at integrating the PR yet, or at least investigating the new ribbon style? It seems interesting

**Comment by Splitwirez** [comment]
> Sorry for bumping a somewhat old issue but has anyone had a look at integrating the PR yet, or at least investigating the new ribbon style? It seems interesting

The PR didn't get very far tbh, certainly not far enough to warrant integration (at least IMO). I've since largely moved my efforts from WPF to a similar framework called Avalonia, in the interest of producing cross-platform software. That said, I agree that the Simplified Ribbon definitely has merit...
