### ISSUE TITLE
Style the minimize button?

### ISSUE THREAD

**Issue by Phantamoss** [fluentribbon/Fluent.Ribbon#697]
Is there anyway to change the color or the icon of the ribbon minimize button?
I don't see anything in
 Fluent.Ribbon/Fluent.Ribbon/Themes/Themes/Theme.Template.xaml

---
### Environment
- Fluent.Ribbon 7.0.0-alpha0532
- Windows 10
- .NET Framework 4.6.2

**Comment by batzen** [comment]
The icons/images are located at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Images.xaml
It should be possible to overwrite that image.

**Comment by Phantamoss** [comment]
That works perfectly. Thanks.
