### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by nicwe** [fluentribbon/Fluent.Ribbon#699]
Application crashes by the following steps:

1. Start Showcase application
2. Switch from backstage menu to application menu
3. Minimize the ribbon menu
4. Click on the "Toolbars" tab (tab will be opened)
5. Click on the Application menu button "File" while the "Toolbars" tab is open -> Application crashes

---
### Environment

- Fluent.Ribbon v6.1
- Windows 10
- .NET Framework 4.5

**Comment by batzen** [comment]
Should be fixed in version 7.0.

**Comment by nicwe** [comment]
Yes, I tried it with version 7.0 and the problem is fixed
