### ISSUE TITLE
How to close the backstage view in code?

### ISSUE THREAD

**Issue by nvkokorin** [fluentribbon/Fluent.Ribbon#70]
Hi everybody!
I trying to do a behaviour which provide me to auto-close the backstage view when an command-buttons there are executed (for example - the open command or properties, etc.)
How I can clearly to close the backstage view via code? I look any properties like "IsOpen" etc., but can not found those.
Thanks.
PS and sorry for my English

**Comment by batzen** [comment]
Hi,
have you tried setting IsDefinitive="true" on your buttons?

**Comment by nvkokorin** [comment]
Hi, thanks for your reply!
Just now I tried set the IsDefinitive property - it's works perfectly in case when the button placed in the <fluent:BackstageTabControl/> visual tree.
In my case, I want achieve same behaviour when my own buttons are placed in the <fluent:BackstageTabItem/> visual tree. For example the simplest tab:
<fluent:BackstageTabItem Header="MyTab">
    <Grid>
        <Button bla-bla-bla>
        ....
    </Grid>
</fluent:BackstageTabItem>

**Comment by batzen** [comment]
You could call 
``` csharp
PopupService.RaiseDismissPopupEvent(this, DismissPopupMode.Always);
```
when your button is clicked, while "this" should be your button instance.

**Comment by GeertvanHorrik** [comment]
Can we create a similar solution as "ClosePopupOnMouseDown" like we did for the DropDownButton? Happy to do a pr.

**Comment by batzen** [comment]
I thought about converting IsDefinitive to an attached property and listening to routed (button-click) events in the backstage maybe. MouseDown would be way too generic i think.

**Comment by GeertvanHorrik** [comment]
When calling RaiseDismissPopupEvent, do we really have to specify a button / element inside the ribbon backstage?

**Comment by GeertvanHorrik** [comment]
@batzen , can you please reply?

**Comment by batzen** [comment]
Totally forgot this. Will reply within 24 hours.

**Comment by batzen** [comment]
DismissPopup is a routed event, so yes you have to call it on a control that's inside the backstage to close the backstage.

**Comment by GeertvanHorrik** [comment]
Thanks for the reply. Is there any other way to dismiss the backstage?

**Comment by batzen** [comment]
- When you got an instance of the backstage at hand you can always set it's IsOpen property to close it
- There also exists RibbonCommands.OpenBackstage, but i never tried it
- Raising RequestBackstageClose on the RibbonTabControl should work
- Raising KeyDown for Key.Escape on the Window should work

**Comment by GeertvanHorrik** [comment]
According to a quick code review of OpenBackstage, I think that must work :-)

https://github.com/fluentribbon/Fluent.Ribbon/search?utf8=%E2%9C%93&q=OpenBackstage

**Comment by GeertvanHorrik** [comment]
I couldn't get it to work quickly, decided to register the ribbon in the ioc container so I can always access it.

**Comment by QuantumDeveloper** [comment]
@batzen Hello. Seems binding to IsOpen property on BackStage is not working at all
Could this be fixed?

**Comment by QuantumDeveloper** [comment]
@batzen  Only Key.Escape is working correctly.

**Comment by GeertvanHorrik** [comment]
@QuantumDeveloper It is working here:

```
                    var backstage = _ribbon.Menu as Backstage;
                    if (backstage != null)
                    {
                        backstage.IsOpen = false;
                    }
```

**Comment by QuantumDeveloper** [comment]
@GeertvanHorrik and what about MVVM scenario? Seems binding doesnt work

**Comment by GeertvanHorrik** [comment]
We use MVVM. You can automate everything through services (that you can use in your view models). Great way to work around such issues.

**Comment by QuantumDeveloper** [comment]
@GeertvanHorrik didnt understand what you talking about

**Comment by GeertvanHorrik** [comment]
Just register it inside a service, then you can use the service (and mock it in your tests).

**Comment by QuantumDeveloper** [comment]
I dont need any service and also test. I want to use it in my ViewModel. I dont want to create service for only one property. Its weird.

**Comment by GeertvanHorrik** [comment]
Then I have a great idea: PR with a fix

**Comment by QuantumDeveloper** [comment]
What to be somethong done, do it yourself, right?

**Comment by batzen** [comment]
@QuantumDeveloper Seems to be the case with non payed open source software.
@GeertvanHorrik "prevent closing on escape" there seems to be a missing check for already handled events.
