### ISSUE TITLE
MenuItem does not show all text

### ISSUE THREAD

**Issue by uwebraunholz** [fluentribbon/Fluent.Ribbon#700]
Hi,
I use a DropDownButton to show a few data bound MenuItems and one fixed MenuItem.
The issue is, that the text of all data bound MenuItems is only displayed to the text width of the very first MenuItem. If there is a long text, most other fit. If a short one is on top, all others get cut to that lenght. The mouse over highlighting uses full available width.
```
<Fluent:DropDownButton Header="{x:Static res:Resources.Account}" SizeDefinition="Large,Middle,Small" ClosePopupOnMouseDown="False">
	<Fluent:Gallery ItemsSource="{Binding MyItems}" MaxItemsInRow="1" Selectable="False">
		<Fluent:Gallery.ItemTemplate>
			<DataTemplate>
				<MenuItem IsChecked="{Binding IsChecked}" Header="{Binding Text}" Command="{Binding ToggleCommand}" Margin="0" />
			</DataTemplate>
		</Fluent:Gallery.ItemTemplate>
	</Fluent:Gallery>
	<MenuItem Header="{x:Static res:Resources.All}" Command="{Binding CheckAllCommand}" />
</Fluent:DropDownButton>
```

![image](https://user-images.githubusercontent.com/7031553/53017943-6bf93400-3451-11e9-9a13-cb0e0151c98d.png)

---

### Environment

- Fluent.Ribbon 6.1.0.326
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
You have to add `Orientation="Vertical"` to the gallery. Otherwise it's horizontal which means the width of the first item defines the width of all following items.

**Comment by uwebraunholz** [comment]
Great, that solved the issue! Thanks!
