### ISSUE TITLE
Interop with MahApps.Metro: TitleBar property is not a thing

### ISSUE THREAD

**Issue by jherby2k** [fluentribbon/Fluent.Ribbon#703]
Following the guide, with the latest previews of Fluent and MahApps.Metro
https://fluentribbon.github.io/documentation/interop_with_MahApps.Metro

Second screenshow wants me to set the TitleBar property, but it seems to have been removed. Is there another way to do this?

```c#
void MainWindow_OnLoaded(object sender, RoutedEventArgs e)
{
    this.TitleBar = this.FindChild<RibbonTitleBar>("RibbonTitleBar"); // TitleBar ain't a thing
    titleBar.InvalidateArrange();
    titleBar.UpdateLayout();
}
```

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0623
- Windows 10 1809
- .NET Core 3.0

**Comment by batzen** [comment]
The documentation lacks the info that your window has to implement IRibbonWindow. Will add that tomorrow.

**Comment by jherby2k** [comment]
Ah, I see. It’s in the example project. Thanks for your hard work! The theme syncing stuff in the guide is also out of date I believe.

**Comment by batzen** [comment]
The theme synching depends on the versions being used. I am bad at writing documentation...
