### ISSUE TITLE
CheckBox.Header - InvalidCastException

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#704]
Invalid cast exception in Fluent.CheckBox.Header (https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Controls/CheckBox.cs line 74).

Why does it cast to string, when both the DP and the Property are both of type Object? The issue is apparent after the new automation peer improvement.

PS: If you fix it, is it possible to create a new NuGet with the fix? We'd love to update from the ancient Alpha we are currently running.
---
### Environment

- Fluent.Ribbon __v7.0.0__alpha0623
- Windows __10__
- .NET Framework __4.7__

**Comment by atlastodor** [comment]
Forgot to mention, we have a StackPanel for the Header property.

**Comment by batzen** [comment]
Uh. Forgot to remove that cast when i changed the type. Will fix it and release a new preview in about seven hours.

**Comment by atlastodor** [comment]
The same bug is found in those classes as well: Checkbox, ComboBox, RadioButton, RibbonControl and ToggleButton. Could you fix them too. Danke dir!

**Comment by batzen** [comment]
Damn. Thanks for pointing those out.
Will have a look at how i can prevent such mistakes by using an analyzer in the future.

**Comment by batzen** [comment]
Package is uploaded. You'll just have to wait for the nuget indexing to finish https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0624

**Comment by batzen** [comment]
@atlastodor FYI
