### ISSUE TITLE
ApplicationMenu header can't be set to text

### ISSUE THREAD

**Issue by jherby2k** [fluentribbon/Fluent.Ribbon#705]
I'm trying to create a "File" menu on my ribbon (see: mspaint.exe). If I set the "Header" property to "File", I get an exception. Seems it wants an icon there, not a header. If I don't set it to anything, I get that weirdo default icon. I can set it to {x:Null} to clear it, but that's not ideal. Can I set a simple text label?

```xaml
        <fluent:Ribbon>
            <fluent:Ribbon.Menu>
                <fluent:ApplicationMenu  Header="File">
                    <fluent:MenuItem Header="Open"/>
                </fluent:ApplicationMenu>
            </fluent:Ribbon.Menu>
         </fluent:Ribbon>
```

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Cannot locate resource 'file'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

Inner Exception 1:
IOException: Cannot locate resource 'file'.

```

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0624
- Windows 10 1809
- .NET Core 3.0 (preview 4)

**Comment by batzen** [comment]
You seem to be the first one trying to use something different than an icon for the application menu.
Currently there is no way to use a string for the header here.
Changing this would mean a breaking change.
May i ask why you are using the application menu instead of a backstage?

**Comment by jherby2k** [comment]
My application really just needs an Open, Save and Exit buttons. Putting them right on the ribbon looks weird, but the backstage seems like overkill. Have a look at mspaint or wordpad for what i'm looking for. Simple utilities I think benefit from a simple "File" menu, and I can't really find any examples that use an icon. I think it would confuse people.

**Comment by batzen** [comment]
I get that use case. Will have a look at how i can solve this issue.

**Comment by jherby2k** [comment]
You rule! If I understood WPF better I'd contribute. This has been a learning experience for me.

**Comment by jeuxjeux20** [comment]
This was possible before.
