### ISSUE TITLE
ApplicationMenu has no SeparatorTabItem equivalent

### ISSUE THREAD

**Issue by jherby2k** [fluentribbon/Fluent.Ribbon#706]
I'd like to be able to separate items in the ApplicationMenu visually, like in the "File" menu in Wordpad or mspaint. The backstage has a SeparatorTabItem control for this, but AFAICT there is no ApplicationMenu equivalent (and the SeparatorTab item seems to do nothing in that context).

The built-in System.Windows.Controls.Separator works almost right, except its a dotted line and the color is off. Not sure if you're open to just styling the built-in control.

Would this be a possible feature request? Thanks so much.

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0624
- Windows 10 1809
- .NET Core 3.0 preview 4

**Comment by batzen** [comment]
I personally don't use the ApplicationMenu, if you want to you can create a PR adding styles/templates for that.
