### ISSUE TITLE
Starting application with backstage menu open causes problems

### ISSUE THREAD

**Issue by kmorgannn** [fluentribbon/Fluent.Ribbon#71]
Hi,
I am trying to create an application that displays the backstage menu when the application is launched. I have tried two approaches, and they have both failed. 

The first was adding IsOpen=True to the Backstage item in the xaml file. This actually works when I run the program, but crashes visual studio every time I try to build the project.

The second approach I tried was opening the backstage in the code. I tried both backstage.Click() and backstage.IsOpen = true, and these also only partially worked. Adding backstage.IsOpen = true worked with all of my helper functions (to keep the backstage open at all times), but would not work upon application startup. With backstage.Click(), the menu was launched at startup but all of the buttons and the backstage view would be red instead of the usual blue. I tried modifying the background/button colors and still could not get it to be blue. I am working with the Generic theme and/or the Office 2010 theme, if that makes a difference.

Is there a better way to do this? I'm not sure if this is a bug or if I am missing something.
Thanks.

**Comment by batzen** [comment]
Didn't test every combination you tried but setting IsOpen=true in the xaml file works now and your designer shouldn't crash anymore.

**Comment by kmorgannn** [comment]
Just tried it with no problems. Thanks!
