### ISSUE TITLE
Icons are too small

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#710]
**Would like small icons to be a bit larger.**

In general the small Icons appear way too small. This have been the case in all versions. Can you make the small icons to appear a bit larger?

Regards,
Jason

**Comment by batzen** [comment]
@bochelie1000 I don't need them to be larger and it would require quite some work as the sizes are all hard coded.
Are there does not seem to be much interest from others i'll close this.
