### ISSUE TITLE
DropDownButton's MenuItem not showing tick mark

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#711]
In my `DropDownButton` I cannot see the tick mark for checked menu items. **What am I missing here?** Not sure if this is a pure Fluent ribbon problem. Perhaps just some weird issue with dynamic resources?

![No check box visible :(](https://user-images.githubusercontent.com/958469/56140401-1e093400-5f9b-11e9-9532-a4c1c95ab43e.png)

I have this in `app.xaml`:
```xaml
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/themes/Styles.xaml" />
```

Then I try to add a large dropdown button with checkable menu items in my ribbon:
```xaml
<fluent:DropDownButton Header="Some Options"
                       ClosePopupOnMouseDown="True"
                       ClosePopupOnMouseDownDelay="250">
    <fluent:MenuItem Header="Automatic" IsCheckable="True" IsChecked="True" />
    <fluent:MenuItem Header="Manual" IsCheckable="True" IsChecked="False" />
</fluent:DropDownButton>
```

Using `Snoop` I can see the checked image in the visual tree. Why can't I see it in my ribbon?

![Checkbox is there, somewhere...](https://user-images.githubusercontent.com/958469/56140491-50b32c80-5f9b-11e9-9900-efbddb548fd0.png)

If I explicitly set the `Icon` it **does** show the tick mark:

```xaml
<fluent:MenuItem Icon="{StaticResource MenuCheckedImage}" ... />
```

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Could you try to update to the latest preview?
`MenuCheckedImage` doesn't even exist in the newest version as all shipped icons are now vector images.

One note: Setting `Icon` on a `MenuItem` will disable the embedded checked image behavior as those menu items (having icon and `IsCheckable`) would require two vertical columns.

**Comment by znakeeye** [comment]
I can't easily upgrade to alpha0624 due to some conflicts with System Interaction DLL and stuff...

**Comment by batzen** [comment]
7.0 does not reference System.Windows.Interactivity anymore. Instead it references Microsoft.Xaml.Behaviors from https://github.com/Microsoft/XamlBehaviorsWpf.
