### ISSUE TITLE
ComboBox is displaying the object name and not the defined itemtemplate, when an item is selected

### ISSUE THREAD

**Issue by badlegg** [fluentribbon/Fluent.Ribbon#712]
**ComboBox is displaying the object name and not the defined itemtemplate, when an item is selected**
The fluent ComboBox is not displaying the selected DataTemplate for the case when the ItemTemplate is defined. Attached is a demo application of the defined use cases. Case 1: Using the displaymemberpath, Case 2: Setting the ItemTemplate for the fluent ribbon combobox, and Case 3: Setting the ItemTemplate for the windows combobox.
[RibbonComboBox demo.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3080849/RibbonComboBox.demo.zip)

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0624__
- Windows __10.0.17134__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
The default for `IsEditable` in Fluent.Ribbon is `true`.
That decision, using `true` as the default, was made before i took over this project in 2012 and i never wanted to break the existing usages.
If you use `IsEditable="False"` on the `ComboBox` everything is fine.

**Comment by badlegg** [comment]
Thanks for the response and the fix.
