### ISSUE TITLE
Newline in ScreenTip?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#713]
Trying to add some paragraphs in a `ScreenTip`. Tried both `\r\n` and `\n`. None worked. Instead the backslashes become visible. Ideas?

```xaml
<fluent:Button.ToolTip>
    <fluent:ScreenTip Title="Title" Text="Important text.\r\n\r\nLess relevant tips here." />
</fluent:Button.ToolTip>
```

---
### Environment

- Fluent.Ribbon __v7.x.x__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
&#x0a; should work.

**Comment by batzen** [comment]
`&#x0a;` should work.

**Comment by znakeeye** [comment]
Thanks. Would be nice though, if the `Text` property accepted some rich text equivalent. E.g. `<Run />`.

**Comment by batzen** [comment]
@znakeeye Could you create a new issue for that? Then i can flag it as a feature request.
