### ISSUE TITLE
Making a ribbon similar to the new office

### ISSUE THREAD

**Issue by ahmedkhalf** [fluentribbon/Fluent.Ribbon#715]
**Hello I would like to have a colorful theme similar to the new office versions. How can I do that?**

[Image Here!](https://ibb.co/WpFTt7L)

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0624__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
You can use the Colorful.Blue theme.

**Comment by pschimmel** [comment]
I just tried the Colorful.Blue theme for the first time and it's really nice.

The only thing that might be improved is that the StatusBar has a blue background. I don't know about the other versions of office, but on my office 365, the StatusBar is light gray.

**Comment by batzen** [comment]
You can overwrite `Background` on `StatusBar` to get that. There is no separate brush resource for the background of the status bar. It simply uses `Fluent.Ribbon.Brushes.AccentBaseColorBrush`.

**Comment by batzen** [comment]
@pschimmel Did that answer your question?

**Comment by pschimmel** [comment]
Yes. Indeed.
