### ISSUE TITLE
Unable to use rich content for ScreenTip

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#716]
`ScreenTip` does **not** support rich content, like e.g. `ToolTip` does.

```xaml
<fluent:Button.ToolTip>
  <fluent:ScreenTip Title="Title">
    <fluent:ScreenTip.Text>
      <!-- This does NOT work! -->
      <Run Text="Hello"> <Run Text="World!" FontWeight="Bold" />
      <!-- Or some other UI thing. E.g. a user control or image... -->
    </fluent:ScreenTip.Text>
  </fluent:ScreenTip>
</fluent:Button.ToolTip>
```

Thus, you cannot produce nice screen tips like in Excel:

![Rich tooltip](https://user-images.githubusercontent.com/958469/56808624-36e2d680-6832-11e9-89a3-21c003a539a5.png)

---
### Environment

- Fluent.Ribbon __v6.x__
- Windows __10__
- .NET Framework __4.x__

**Comment by batzen** [comment]
I totally forgot to mention that you can, at least, use an image on the left side by setting `Image` on a `ScreenTip`.
