### ISSUE TITLE
Icon align left and two inscriptions in DropButton

### ISSUE THREAD

**Issue by Sakavik** [fluentribbon/Fluent.Ribbon#717]
![step4c](https://user-images.githubusercontent.com/12526857/57225970-7c638880-7016-11e9-9672-42c40dda65c3.png)
I try to make Drop Button like this, but i don't know, how to make icon align to left and make two subscriptions. 

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0624__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
The best way to implement this would be to use an ItemTemplate for your DropDown.
