### ISSUE TITLE
Weird Behaviors with RibbonToolBar and LayoutDefinitions

### ISSUE THREAD

**Issue by andychung0096** [fluentribbon/Fluent.Ribbon#718]
I'm new to WPF and Fluent so, I'm sorry in advance if there is something that I missed. With the following codes below, I'm trying to smoothly resize a RibbonGroupBox into the 'Collapsed' state. Here, I encountered a weird behavior using SizeDefinition. As I reduce the main window horizontally from the initial state, 'Cut' button gets resized to a large icon, then both buttons disappear, then they get collapsed. When I enlarge the window or click the collapsed RibbonGroupBox, 'Cut' button remains to be a large icon.
[Image](https://imgur.com/sC0j6FO)
```
<Fluent:RibbonTabItem Header="Tab" ReduceOrder="Clipboard, Clipboard, Clipboard">
    <Fluent:RibbonGroupBox Header="Group" Name="Group">
        <Fluent:RibbonToolBar>
            <Fluent:Button Header="Paste" Name="Paste" SizeDefinition="Large"
            Icon="pack://application:,,,/Paint;component/Images/2-1.png"
            LargeIcon="pack://application:,,,/Paint;component/Images/2-1.png">

            <Fluent:Button Header="Cut" Name="Cut" SizeDefinition="Medium"
            Icon="pack://application:,,,/Paint;component/Images/2-2.png"
            LargeIcon="pack://application:,,,/Paint;component/Images/2-2.png">
        </Fluent:RibbonToolBar>
    </Fluent:RibbonGroupBox>
</Fluent:RibbonTabItem>
```

I tried to fix this behavior by setting LayoutDefinitions. This fixed most of the problems from the code above but, when I click the collapsed RibbonGroupBox, the pop up box doesn't correctly display the buttons. Also, it seems like 'Cut' button is getting resized to a large icon again,
[Image](https://imgur.com/Kvz0sLe)
```
<Fluent:RibbonTabItem Header="Tab" ReduceOrder="Clipboard, Clipboard, Clipboard">
    <Fluent:RibbonGroupBox Header="Group" Name="Group">
        <Fluent:RibbonToolBar>
            <Fluent:RibbonToolBar.LayoutDefinitions>
                <Fluent:RibbonToolBarLayoutDefinition Size="Large">
                    <Fluent:RibbonToolBarRow>
                        <Fluent:RibbonToolBarControlDefinition Target="Paste" Size="Large"/>
                        <Fluent:RibbonToolBarControlDefinition Target="Cut" Size="Middle"/>
                    </Fluent:RibbonToolBarRow>
               </Fluent:RibbonToolBarLayoutDefinition>
            </Fluent:RibbonToolBar.LayoutDefinitions>

            <Fluent:Button ... />
            <Fluent:Button ... />
        </Fluent:RibbonToolBar>
    </Fluent:RibbonGroupBox>
</Fluent:RibbonTabItem>
```
Am I doing anything wrong here? Thanks!

---
### Environment

- Fluent.Ribbon __v6.1.0.233__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Will try to have a look at this next week as i am on vacation right now.

**Comment by batzen** [comment]
Ok, it's horribly broken when using `RibbonToolBar`.
Didn't notice this as i don't use that control myself.
Will have a look.

**Comment by andychung0096** [comment]
Thank you again for looking in to this. 
I love that this is still supported by developers. MS Ribbon gave me so much headaches xD

**Comment by batzen** [comment]
Could you try the latest preview from the appveyor feed?
Will release the next preview to nuget tomorrow, so if you don't want to use the appveyor feed you can also wait till then.

**Comment by batzen** [comment]
And the correct way to define the sizes is the second code block you wrote in the issue.

**Comment by batzen** [comment]
@andychung0096 finally found time to publish the preview. would be nice if you could have a look.

**Comment by andychung0096** [comment]
I'm sorry. I couldn't find an update and just forgot about this for a while. By looking at the nuget list, is it the 7.0.0-alpha0661? I'll check it out as soon as I'm done with my finals. Thanks!

**Comment by batzen** [comment]
Yes, that's the right version.
Good luck with your finals.

**Comment by andychung0096** [comment]
Sorry for keep you waiting. I'm trying to replicate the same behavior I had but, it seems like I'm missing something. This is what I got right now:

The first group box doesn't get reduced into a tab item. The second group box works perfectly.
[Fluent_Sample.txt](https://github.com/fluentribbon/Fluent.Ribbon/files/3295328/Fluent_Sample.txt)

![Untitled](https://user-images.githubusercontent.com/19895649/59579752-23f6c080-9083-11e9-982f-d65f61e3d125.png)

When I deleted the first group box codes, the second group box didn't get reduced as well. I was wondering if this has something to do with ReduceOrder property in RibbonTabItem. Also, this isn't related but, is there a way to stack the cut and copy buttons vertically using LayoutDefinitions? It seems like there isn't something like RibbonToolBarColumn inside RibbonToolBarLayoutDefinition.

Thanks!

**Comment by batzen** [comment]
That should be because there is still enough space for the first group and the ribbon itself gets collapsed before it can reduce the size for the first group.
You can try this by adding a third group. Then the second and third group should get collapsed but as long as there is enough space for the first group it won't get collapsed.

You can't stack the items vertically as far as i know.

**Comment by batzen** [comment]
@andychung0096 Do you still have issues with this?

**Comment by andychung0096** [comment]
Thank you for the reminder and all the supports! I'll close the ticket.
