### ISSUE TITLE
SplitButton.IsButtonEnabled doesn't disable drop-down part

### ISSUE THREAD

**Issue by Pyth0ff** [fluentribbon/Fluent.Ribbon#720]
The property `IsButtonEnabled` of the `SplitButton` doesn't disable the drop-down part of the control, instead the main action is disabled.

Why can the main action not disable the complete control, if the main action cannot be executed?

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0624__
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
Because it's supposed to work that way.
I could add a property like IsDropDownEnabled if that would help.

**Comment by Pyth0ff** [comment]
Ok, than I misinterpreted [this comment.](https://github.com/fluentribbon/Fluent.Ribbon/blob/407ceac8c7abe5fe39bf56edff0c680302f900d5/Fluent.Ribbon/Controls/SplitButton.cs#L228)

https://github.com/fluentribbon/Fluent.Ribbon/blob/407ceac8c7abe5fe39bf56edff0c680302f900d5/Fluent.Ribbon/Controls/SplitButton.cs#L228

**Comment by batzen** [comment]
You don't, the comment is just wrong and the xml documentation for the dependency property is also wrong.
If you want to disable the whole SplitButton you could simply set IsEnabled=false.

**Comment by batzen** [comment]
Updated the documentation for IsButtonEnabled.
