### ISSUE TITLE
Theme reverts to default on WM_SETTINGCHANGE

### ISSUE THREAD

**Issue by yoshiask** [fluentribbon/Fluent.Ribbon#721]
### Details

I noticed that the ribbon theme reverts to default light whenever I A) unplug or plug in my laptop to charge or B) set an environment variable (User). My best guess is that the theme resets whenever the WM_SETTINGCHANGE message is broadcasted.
---
### Environment

- Fluent.Ribbon 7.0.0-alpha0624
- Windows 10 b. 17763.503
- .NET Framework 4.6.1

**Comment by batzen** [comment]
- How do you set your current theme?
- Do you disable theme sync after you set your theme manually?

**Comment by batzen** [comment]
@yoshiask ping

**Comment by yoshiask** [comment]
This is from OnStartup() in App.xaml.cs:

`ThemeManager.IsAutomaticWindowsAppModeSettingSyncEnabled = true;
ThemeManager.SyncThemeWithWindowsAppModeSetting();
ThemeManager.ChangeTheme(Application.Current, "Dark.Steel");`

**Comment by batzen** [comment]
And which Windows theme do you have set? Light or Dark?

**Comment by yoshiask** [comment]
The app theme is light

**Comment by batzen** [comment]
You set the app to dark on startup but have theme/appmode sync enabled. Once you disable the automatic sync it'll stay dark.

**Comment by yoshiask** [comment]
That makes sense. So Windows fires a theme change when the power state changes to 'charging'. Interesting.
