### ISSUE TITLE
Fluent Ribbon BackstageTabItem Icon

### ISSUE THREAD

**Issue by redcican** [fluentribbon/Fluent.Ribbon#723]
Can we add an Icon to BackstageTabItem like Office 365?

---
### Environment

- Fluent.Ribbon v6.1.0.326
- Windows 10
- .NET Framework 4.6.1
![icon](https://user-images.githubusercontent.com/10456402/59434916-c5181980-8dec-11e9-98d4-52d096c9f08c.PNG)

**Comment by batzen** [comment]
That's already possible in version 7.0:
![image](https://user-images.githubusercontent.com/1971030/59451668-4337e880-8e0c-11e9-8cf6-d58cce40689f.png)
Is that what you are asking for? Or did you mean the vertical layout?

**Comment by redcican** [comment]
That's what I mean. Thank you.
But the version 7.0 is not avaible by NuGet,right?

**Comment by batzen** [comment]
Currently only as a preview. https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0661

**Comment by redcican** [comment]
Vielen Dank! 
After updating to the latest version. I can now add icons. But the background color of backstage turn to blue. I didn't change any code. Any idea? It should be kind of orange.
` <Fluent:Backstage Header="File"  Background="{StaticResource OrangeBrush}" Foreground="{StaticResource DarkGrayBrush}">
`
![backstage](https://user-images.githubusercontent.com/10456402/59456209-23a5bd80-8e16-11e9-9723-39b291f01f87.PNG)

**Comment by batzen** [comment]
That's because the background only applies to the open/close button. You have to set ItemsPanelBackground on your BackstageTabControl to get what you want.

**Comment by batzen** [comment]
Another alternative to changing the single colors would to use the orange accent theme.

**Comment by redcican** [comment]
Thank you very much. It works for me. 
I had another issue. Wenn I clicked the 'File' button. The backstage menu showed, but it doesn't have the window command (minimize, restore, close...) How can I reset these command?

Herzlich vielen dank!
![snipppe](https://user-images.githubusercontent.com/10456402/59459142-5e125900-8e1c-11e9-88fd-085d3e28e61f.PNG)

By the way, where can I check the document of version 7.0.

**Comment by batzen** [comment]
Do you have any further questions or can we close this issue?
