### ISSUE TITLE
Manifest definition does not match the assembly reference?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#724]
When loading views with `Fluent` controls, I get this silent exception on load. You see it in the output and the debugger breaks if you break on `FileLoadException`. Why this silent error?

> Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
> Could not load file or assembly '**Fluent, Version=0.0.0.0**, Culture=neutral, PublicKeyToken=3e436e32a8c5546f' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 
> Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
> Could not load file or assembly '**ControlzEx, Version=0.0.0.0**, Culture=neutral, PublicKeyToken=69f1c32f803d307e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 

The references look like this:

```xml
<package id="ControlzEx" version="4.0.0-alpha0189" targetFramework="net452" />
<package id="Fluent.Ribbon" version="7.0.0-alpha0456" targetFramework="net452" />
```

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0456__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
That was a strong naming issue which has been resolved in a later preview version. You just have to update to the latest preview for example.

**Comment by znakeeye** [comment]
Ah, thanks!

**Comment by Shujee** [comment]
Facing the same issue with exactly the same public key token (3e436e32a8c5546f) when using version 7.1.0.
