### ISSUE TITLE
GroupSeparatorMenuItem is shown like a disabled MenuItem in ApplicationMenu

### ISSUE THREAD

**Issue by nicwe** [fluentribbon/Fluent.Ribbon#726]
If you add a GroupSeparatorMenuItem in ApplicationMenu, it is shown like a disabled MenuItem. It does not matter if it is on first or second level.

---
### Environment

- Fluent.Ribbon __v7.0.0.0__ (develop)
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
Have you tried using a simple `<Separator />` instead?

**Comment by nicwe** [comment]
A simple `<Separator />` is working but it has no `Header` Property to show a Text.

**Comment by batzen** [comment]
I personally don't use the ApplicationMenu, if you want to you can create a PR adding styles/templates for that.
