### ISSUE TITLE
Weird tooltip behavior in RibbonTabItem

### ISSUE THREAD

**Issue by balkarov** [fluentribbon/Fluent.Ribbon#728]
Hello!
Thank you for your library!

I have incorrect tooltip position when hover on TabItem
![1](https://user-images.githubusercontent.com/6030335/60881813-2e097a80-a24f-11e9-9a02-19f99e6a3c77.gif)

How to fix it? Or how to disable this tooltips?

Thank you!

---
### Environment

- Fluent.Ribbon __v6.1.0.326__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
I think that's the regular behavior for regular tooltips.
Once you move the mouse over a control that has a tooltip wpf starts a timer (which is controlled by `ToolTipService.InitialShowDelay`).
Once that timer fires the tooltip is opened at some point around the position the mouse had at some point in time during that delay.
