### ISSUE TITLE
Customize the Startscreen Leftcontent width and background color

### ISSUE THREAD

**Issue by redcican** [fluentribbon/Fluent.Ribbon#731]
Is there any way that we can customize the width and background color of left content from startscreen?
### Environment

- Fluent.Ribbon  v7.0.0-alpha0586
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
You can use `ItemsPanelMinWidth` and `ItemsPanelBackground` on `BackstageTabControl` for that.

**Comment by redcican** [comment]
Hi, my application needs backstage and start screen. If I insert the code like below for start screen. It just simply creates a new backstage for me. It won't change the original left content background and width for the start screen leftcontent.

`                
                <Fluent:Ribbon.StartScreen>
                    <Fluent:StartScreen IsOpen="True" UseHighestAvailableAdornerLayer="False">
                        <Fluent:BackstageTabControl ItemsPanelMinWidth="200" ItemsPanelBackground="Orange">
                        <Fluent:StartScreenTabControl>
                            
                               <Fluent:StartScreenTabControl.LeftContent>
                                    <..../>
                                </Fluent:StartScreenTabControl.LeftContent>
                                    <..../>
                              <Fluent:StartScreenTabControl.RightContent>
                               
                              </Fluent:StartScreenTabControl.RightContent>
                            
                        </Fluent:StartScreenTabControl>
                        </Fluent:BackstageTabControl>
                    </Fluent:StartScreen>
                </Fluent:Ribbon.StartScreen>`

**Comment by batzen** [comment]
It creates a new `BackstageTabControl` for you because you told it to do so by adding a `BackstageTabControl` to the `StartScreen`.
Just move ` ItemsPanelMinWidth="200" ItemsPanelBackground="Orange"` to `StartScreenTabControl` and remove the `BackstageTabControl`.

**Comment by batzen** [comment]
And you can also use `LeftContentMargin` to remove the margin.

**Comment by redcican** [comment]
That's very kind of you. Thank you very much!
