### ISSUE TITLE
Backstage Textbox loses focus.

### ISSUE THREAD

**Issue by StevenW1969** [fluentribbon/Fluent.Ribbon#732]
**Trying to use Fluent.Ribbon.Backstage, which opens fine. In BackstageTabItem we have a User control which includes a Textbox. When opening the the Backstage by setting IsOpen = true (Or clicking the File menu item) We want the focus to go to the TextBox on the UserControl.  The TextBox gets the focus briefly then loses it.**

**Anytime a user select a BackstageTabControl or opens of closes the BackStage We want to be able to set the focus to a give control, so the user can just start typing**
[COAP_WPF - Copy.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3448033/COAP_WPF.-.Copy.zip)
---
### Environment

- Fluent.Ribbon v7.0.0-alpha0661
- Windows 10 1903
- .NET Framework 4.5

**Comment by batzen** [comment]
You could use `Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.ApplicationIdle, new Action(() => Search.Focus()));` to make it work.
