### ISSUE TITLE
Ribbon icon padding + RibbonTabItem width decreased in 7.0.0-alpha0687?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#733]
Just upgraded from `7.0.0-alpha0456` to `7.0.0-alpha0687`. It seems the `RibbonTabItem` tabs now have a measured width that is less than before? Why is this, and how do I get the old style back?

Also, note that the icon padding seems wrong after updating. Please advise!

![image](https://user-images.githubusercontent.com/958469/63153956-dd382f00-c00f-11e9-9935-d759ac0f6402.png)

### Environment

- Fluent.Ribbon __v7.0.0-alpha0687__
- Windows __10__
- .NET Framework __4.5.2__

**Comment by znakeeye** [comment]
I believe the icon alignment was changed here: b4fd7d7ba193315ebb98a903c782e56c7c1df8ca
Not sure about the tab item width though.

**Comment by znakeeye** [comment]
By the way. Looking at the ribbon in Explorer, it seems like the icon is stretched with a margin of around "4,4,4,4". There's no need to force it to 16x16.

**Comment by batzen** [comment]
Will have a look at the icon styling. It looks perfectly fine in the showcase application and in my apps.
Did you change anything else on your side? Like the height of the titlebar?

I changed the padding of the tab items because it felt like a lot of wasted space and the latest office versions also have their padding reduced a lot.
If you want the "old" padding back you can set `Indent` on your style for `RibbonTabItem`.
I guess i should rename that property to `HeaderPadding` to clarify it's use and also allow users to control the top and bottom, and not only left and right.

**Comment by znakeeye** [comment]
The only thing I can think of is DPI setting in windows. It's 100% here. Or perhaps this:

```xaml
AutomaticStateManagement="True"
IsQuickAccessToolBarVisible="False"
```

**Comment by batzen** [comment]
I still can't reproduce that icon issue.
Any chance you can provide a small repro for that?

**Comment by znakeeye** [comment]
I'll try this week. I hope I manage to reproduce it before v7.0 😛

**Comment by batzen** [comment]
@znakeeye any news from you? My plan was to release 7.0 this weekend.

**Comment by znakeeye** [comment]
It doesn't appear in my sample project, for some reason. Anyway, when I select `PART_Icon` in `Snoop` I see the following:

```
Margin="2,0,0,0"
```
Changing it to `4,2,0,0` fixes the problem. Where did this other margin come from?

**Comment by batzen** [comment]
The padding of `PART_Icon` only changes when the window is maximized.
That padding indeed is `2 0 0 0`, where it should be `2 2 0 0`.

**Comment by batzen** [comment]
Aside from that, there is no code in Fluent.Ribbon that touches `PART_Icon`.
Maybe you have a custom style or some code changing it?

**Comment by lennartb-** [comment]
We observe the same behavior. I assume this is related to [this](https://github.com/fluentribbon/Fluent.Ribbon/commit/b4fd7d7ba193315ebb98a903c782e56c7c1df8ca#diff-653f1fe3cd757cd178e85afcc722973f) change, where the icon was top-aligned. Can you remember why you made this change? I checked some other applications and the icon generally seems to be vertically centered and not aligned at the top.
