### ISSUE TITLE
Revision not set in file version of the Fluent.dll

### ISSUE THREAD

**Issue by Pyth0ff** [fluentribbon/Fluent.Ribbon#736]
The file revision of the `Fluent.dll` has been removed with release of v7.0.0-alpha0623, which cause that our patch installer build is no longer able to patch the `Fluent.dll`, because the file revision is now smaller than before.

The current workaround is that we build our own version of the `Fluent.dll`, where we set the file revision explicitly in the `Directory.build.targets` file and commit the build output for the patch installer build.

Can you please explain, why the file revision was reset to zero?

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0586__
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
Which file revision do you mean exactly? I don't remember removing something in that area, so if there is something missing now it's most likely a mistake on my side and not intentional.

**Comment by Pyth0ff** [comment]
The `AssemblyFileVersion` of the `Fluent.dll` for build 586 was _7.0.0.586_ and since the build 623 the `AssemblyFileVersion` has been changed to just _7.0.0_ not containing the build number (e.g. 623) as file revision.

**Comment by batzen** [comment]
Will fix that tomorrow. Should be related to the changes to the gitversion config i copied from MahApps.Metro.

**Comment by batzen** [comment]
Should be fixed now. Could you check if i got it right this time?

**Comment by Pyth0ff** [comment]
I used the latest checkout and it is now working again. The `AssemblyFileVersion` of the `Fluent.dll` is now 7.0.0.707 including the build number 707.
