### ISSUE TITLE
Caliburn Micro MVVM Support ?

### ISSUE THREAD

**Issue by redcican** [fluentribbon/Fluent.Ribbon#737]
I was wondering If Fluent Ribbon is now fully supported for Caliburn Micro. I have used Fluent Ribbon to create a GUI, I am trying to use Caliburn Micro for MVVM, but it doesn't work!

**Comment by batzen** [comment]
I don't use caliburn micro.
What's preventing you from using it with the ribbon?

**Comment by redcican** [comment]
@batzen Thanks, I fixed it.

**Comment by kharabyasser** [comment]
> @batzen Thanks, I fixed it.

Can you share with us your solution please?

I would like to know if we can use the contentControl of CM inside a BackstageTabControl as @batzen is providing the same answer to this question for years now.
