### ISSUE TITLE
[Question] 7.0 release timeline

### ISSUE THREAD

**Issue by tomguilbault** [fluentribbon/Fluent.Ribbon#739]
I was wondering if there was any idea on when the 7.0 version will graduate from preview to a main release?

**Comment by pschimmel** [comment]
Me too! 
I can't wait using version 7.0 in production code.

**Comment by batzen** [comment]
I already planned to release it for, i think, 4 times...
Then found some issue i consider critical and delayed the release date.
The last thing i found like a week ago was a potential endless loop when resizing.
That's fixed now and until now i couldn't find any major remaining issues.

I will try to get it released on Sunday, but don't nail me on that.
If i happen to find anything major i will have to delay it again...
My time is very limited as i am also working on XamlColorSchemeGenerator, Snoop (which i now also maintain) and some tools i didn't open source so far. I don't seem be good at getting one thing done and then start the next thing. Instead i always get distracted and try to work on everything simultaneously... Will have to work on that. ;-)

**Comment by batzen** [comment]
To keep you updated: I will try to release this weekend.

**Comment by batzen** [comment]
@pschimmel Forgot to comment here.
Version 7.0 was released 3 weeks ago.
https://www.nuget.org/packages/Fluent.Ribbon/7.0.0
