### ISSUE TITLE
Fluent.Ribbon.Brushes.RibbonWindow.TitleForeground not working for caption buttons?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#740]
In my theme I try to set the background color of the caption bar:

```xml
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonWindow.TitleBackground" Color="Black" options:Freeze="True" />
<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonWindow.TitleForeground" Color="White" options:Freeze="True" />
```

The problem is that the minimize/maximize/close buttons are now completely black.

![image](https://user-images.githubusercontent.com/958469/63855877-b8916f00-c9a0-11e9-8193-887ddc61464b.png)

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0687__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
Was it your mistake or did you close by accident?

**Comment by znakeeye** [comment]
I found the answer immediately after posting :P

**Comment by kezara** [comment]
@znakeeye @batzen what's the solution? I've lost all day looking to change color of caption buttons and can't find the solution.

**Comment by batzen** [comment]
@kezara You can find a list of all resource keys Fluent.Ribbon uses at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/ReferenceData/vCurrentResourceKeys.txt

The resource keys for the brushes of the window buttons are:
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Background
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Foreground
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.MouseOver.Background
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Pressed.Background
Fluent.Ribbon.Brushes.WindowCommands.CloseButton.MouseOver.Background
Fluent.Ribbon.Brushes.WindowCommands.CloseButton.Pressed.Background

I hope that helps you.

**Comment by kezara** [comment]
@batzen
thanks for quick reply. It works now.
