### ISSUE TITLE
Need different accent colors for ribbon buttons and command buttons

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#741]
When you create a theme as shown below (title bar and ribbon tab control has the same black color), the accent color is reused for both ribbon and command buttons. The result is that the minimize/maximize/close buttons get a too light accent color. Can this be fixed using the current template/design?

![image](https://user-images.githubusercontent.com/958469/64025798-ca5c4900-cb3d-11e9-9f92-456afad9c83a.png)

---
### Environment

- Fluent.Ribbon __v7.0.0-alpha0687__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
Have a look at `CaptionButtonStyle`.
It uses `Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Background` and `Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Foreground`.

**Comment by batzen** [comment]
And the ribbon minimize button has `RibbonTabControlToggleButtonStyle`. But there are no separate brushes you can set for that one.

**Comment by znakeeye** [comment]
Ok, thanks. So instead of changing some brushes I need to override some styles here?

**Comment by batzen** [comment]
Yes, at least for `RibbonTabControlToggleButtonStyle`.
