### ISSUE TITLE
Pin button not clickable when Ribbon in collapsed state

### ISSUE THREAD

**Issue by JasonXu-YK** [fluentribbon/Fluent.Ribbon#742]
Issue:
Problem with pin button for pinning ribbon when in collapsed state.
Expected behaviour:
Pin button should be clickable, and ribbon should be pinned after clicking the pin button.
Encountered behaviour:
Pin button is not clickable. Shortcut (Ctrl + F1) still works.
Recreating issue:
Create a new project and add the ribbon with one or more menu items.
Collapse the ribbon using the collapse button or shortcut.
Click on a menu item to display the ribbon so that the collapse button changes to a pin.
Pin button is displayed, but not clickable.
Other notes:
As mentioned, shortcut (Ctrl + F1) still works.
There is no code behind for the Window except the initialisation component.

Environment
Fluent.Ribbon 6.1.0.326
Windows 10 Enterprise
.NET Framework 4.7.2

**Comment by JasonXu-YK** [comment]
https://github.com/fluentribbon/Fluent.Ribbon/issues/602
This bug is closed but the nuget package version is not updated.

**Comment by batzen** [comment]
It's updated, but currently only as a pre-release version.
Will try to release the final version this weekend.
