### ISSUE TITLE
BorderThickness of RibbonTabControlControlTemplate

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#743]
`RibbonTabControlControlTemplate` should have customizable border thickness. I'd like to remove the border (like in modern Office), but it seems quite tricky due to a mistake in the control template.

I believe you should have `BorderThickness="{TemplateBinding MarginPropertyOfYourChoice}"` instead of hard-coding it to `"0,1,0,1"`:

```xml
<Border x:Name="border"
        HorizontalAlignment="Stretch"
        Margin="0,-1,0,0"
        Width="Auto"
        BorderThickness="0,1"
```

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
Will consider this for a future version.

**Comment by znakeeye** [comment]
A workaround is to set a margin on `RibbonTabItem`:

```xml
<Style TargetType="{x:Type fluent:RibbonTabItem}" BasedOn="{StaticResource RibbonTabItemStyle}">
    <Setter Property="Margin" Value="0 0 0 1" />
</Style>
```
