### ISSUE TITLE
Update in TitleBar

### ISSUE THREAD

**Issue by fialo4ka** [fluentribbon/Fluent.Ribbon#744]
Hello!
could you please add to the  RibbonWindowControlTemplate some container for user name... Like in Word from right part before "PART_WindowCommands..." 

And also I have other visual color change issues, now, I just overwrite elements in my solution... But I can overwrite it and to pull it here too :)   but don't understand how to run app... It show me an error in C++ library... :( If you will be so kind and explain me, it will helps if someone need to change schema of colors completely for all elements...  For example from light to dark...

### Environment

- Fluent.Ribbon __v 6.1.0.326__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
You can just add items to `WindowCommands`.
Any item added to that control is shown before the real window commands.

For example:
```xaml
    <Fluent:RibbonWindow.WindowCommands>
        <Fluent:WindowCommands>
            <Button Content="Test" Foreground="{DynamicResource Fluent.Ribbon.Brushes.LabelTextBrush}" />
        </Fluent:WindowCommands>
    </Fluent:RibbonWindow.WindowCommands>
```

I don't understand your question about the color changes.
Could you explain that a bit more?
