### ISSUE TITLE
SplitButton.IsEnabled based on Command.CanExecute?

### ISSUE THREAD

**Issue by MenzenJ** [fluentribbon/Fluent.Ribbon#745]
Hi,

is there a way to bind SplitButton.IsEnabled to the command.canExecute?
My goal is to disable the SplitButton completly if the button command cannot be executed.

I think if the internal ToggleButton would have a TwoWay-Binding for IsButtonEnabled it might work delegating IsButtonEnabled in the SplitButtonsStyle:
`<fluent:SplitButton.Style>`
    `<Style TargetType="fluent:SplitButton">`
        `<Style.Triggers>`
            `<Trigger Property="IsButtonEnabled" Value="False">`
                `<Setter Property="IsEnabled" Value="False"/>`
            `</Trigger>`
        `</Style.Triggers>`
    `</Style>`
`</fluent:SplitButton.Style>`

But I don't know if that would have any side effects, and I'm not sure if I'm overlooking something really simple to achieve this behavior, hence the question.

Related: 
#467 (This behavior was once integrated as default but got reverted)
#720 

---
### Environment
- Fluent.Ribbon __v7.0.0-alpha0661__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
That's true. The binding of `IsButtonEnabled` on the internal ToggleButton should be two way.

**Comment by batzen** [comment]
Will delay this for the next version as i absolutely want to get 7.0 released tomorrow.
