### ISSUE TITLE
Support for .net core 3

### ISSUE THREAD

**Issue by JP75012** [fluentribbon/Fluent.Ribbon#749]
**Place your issue description here.**
It would be great to support .net core 3 as it supports Wpf and it is the future framework.

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon  v7.0.0
- Windows 10
- .NET core 3

**Comment by batzen** [comment]
Fluent.Ribbon 7.0 already supports .NET Core 3.0.
Did you experience any issues using it there?

**Comment by JP75012** [comment]
Dear Bastian.
Thank you for your email.
Unfortunately, we had a problem.
On a wpf .netcore application, we encounter a problem with a NuGet that is used in your library :


Thanks by advance 
Jp Poli




Envoyé de mon iPhone

**Comment by batzen** [comment]
If you are talking about the nuget warning about XamlBehaviors, that one can be ignored or you can update that library to it's latest version, which is also built for .net core now.

**Comment by JP75012** [comment]
Ok i stopped when I saw the warning but it seems ok.
Thank you very much !
Jpp

Envoyé de mon iPhone
