### ISSUE TITLE
Ribbon not loaded or/and selected TabItem at Start when "NO" QuickAccessItem" set

### ISSUE THREAD

**Issue by loewnzaan** [fluentribbon/Fluent.Ribbon#75]
Hello,

when i create a Ribbon without set QuickAccessItem, the Ribbon has no Selected TabItem after Start and Show no Controls!! When i move over the TabItemHeader with the Cursor then the Ribbon Show the Tab correctly.

 <Fluent:Ribbon Name="ribbon">
                <Fluent:Ribbon.QuickAccessItems>
                </Fluent:Ribbon.QuickAccessItems>
....

This Code make the Error!
When you add one QuickAccessMenuItem as sample, then it works.. 

Thx, Flo

**Comment by loewnzaan** [comment]
Sorry, sorry, sorry... When "ShowQuickAccessToolBarAboveRibbon = False" is set on Ribbon, then it works perfectly!!

**Comment by batzen** [comment]
Can't reproduce your issue in the showcase application. If you feel this needs further attention from my side please provide a small repro or if you don't feel so just close this issue please.

**Comment by batzen** [comment]
No further attention needed?

**Comment by loewnzaan** [comment]
No, is ok! When I set ShowQuickAccessToolBarAboveRibbon to false all is ok! Thx
