### ISSUE TITLE
QuickAccessMenuItem - IsChecked doesn't work for Target

### ISSUE THREAD

**Issue by mpolewaczyk** [fluentribbon/Fluent.Ribbon#751]
I want to display items in Quick Menu, but they are always hidden, I need to click expand button and check them manually to see them

```
<fluent:Ribbon Name="RibbonMenu" Background="WhiteSmoke" HorizontalAlignment="Stretch" VerticalAlignment="Top">
    <fluent:Ribbon.QuickAccessItems>
        <fluent:QuickAccessMenuItem Target="{Binding ElementName=MenuConnect}" IsChecked="true"/>
    </fluent:Ribbon.QuickAccessItems>
    <fluent:RibbonTabItem Header="Home">
        <fluent:RibbonGroupBox x:Name="ClipboardGroup" Header="Connection">
            <fluent:ToggleButton Name="MenuConnect" LargeIcon="/Resources/Off.png" Icon="/Resources/Off.png" Click="ButtonConnect_Click" />
        </fluent:RibbonGroupBox>
    </fluent:RibbonTabItem>
</fluent:Ribbon>
```

---
### Environment

- Fluent.Ribbon __v7.0.0__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
The code in the showcase application works as it should.
Could you create a small repro app? I currently don't have enough time to do this myself.

**Comment by mpolewaczyk** [comment]
I created repro application: https://github.com/mpolewaczyk/TestFluent

After loading application you will see the image as below
![image](https://user-images.githubusercontent.com/8502960/70223131-7455fd80-174b-11ea-9d0c-31193e5a88a7.png)


After uncommenting the second item, it will work as needed
![image](https://user-images.githubusercontent.com/8502960/70223191-8cc61800-174b-11ea-8811-1d50281d63f7.png)

**Comment by mpolewaczyk** [comment]
At first I thought it was working, but after adding Ribbon.Menu to the code QuickAccessItems are hidden again. 
Now, even after commenting Ribbon.Menu, QuickAccessItems are randomly displayed or not, so there is probably a race condition somewhere

**Comment by batzen** [comment]
Just pulled the changes from your test project and the bug is still gone.
So i can't reproduce your issue anymore using your test application.

**Comment by mpolewaczyk** [comment]
You are right, after pulling changes it will works, but if you modify the code, it will stop working

I modified QuickAccessItems as follows
```xaml
<fluent:Ribbon.QuickAccessItems>
    <!--<fluent:QuickAccessMenuItem Target="{Binding ElementName=MenuConnect}" IsChecked="True"/>-->
    <fluent:QuickAccessMenuItem Target="{Binding ElementName=MenuDisconnect}" IsChecked="True"/>
    <fluent:QuickAccessMenuItem IsChecked="True">
        <fluent:Button Header="test"/>
    </fluent:QuickAccessMenuItem>
</fluent:Ribbon.QuickAccessItems>
```

First item is commented but it's still displayed in TitleBar, on the other hand newly added item isn't displayed
![image](https://user-images.githubusercontent.com/8502960/70503251-4db90d80-1b23-11ea-8bbd-93825056d3d1.png)

**Comment by batzen** [comment]
That's because of AutomaticStatemanagent being 'true'. If we you to completely define the QAT in code and don't want user state to be persisted you should set it to 'false'.

**Comment by mpolewaczyk** [comment]
Thanks, after setting AutomaticStateManagement it works
