### ISSUE TITLE
Backstage content not being unloaded first time

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#752]
We have backstage views that need to receive the loaded / unloaded events (so we can dispose some classes). There are a few things that we found and hope can be verified by others:

1. The backstage controls are eagerly loaded (so when the shell is loaded, all the backstage components are already being loaded)
2. The first time the backstage closes, the unloaded event is not fired

I will try to create a small repro. If this is desired behavior, we will implement workarounds in our apps.

---
### Environment

- Fluent.Ribbon 7.0.0
- Windows 10
- .NET Framework 4.7.2

**Comment by GeertvanHorrik** [comment]
Created the repro: https://github.com/GeertvanHorrik/FluentRibbonBackstage

**Comment by batzen** [comment]
I don't know what i could do to prevent/improve this.
If you, for example, replace the backstage with:
```
        <TabControl>
            <TabItem>

            </TabItem>
            <TabItem>
                <local:BackstageControl />
            </TabItem>
        </TabControl>
```
the behavior is exactly the same.

**Comment by batzen** [comment]
@GeertvanHorrik Any ideas? I don't have any...

**Comment by GeertvanHorrik** [comment]
Sorry, have been busy in December and January. I will investigate this in the next consolidation week (first week of February).
