### ISSUE TITLE
Align RibbonGroupBox to the right

### ISSUE THREAD

**Issue by EmbeddedAndMore** [fluentribbon/Fluent.Ribbon#754]
Is it possible to align the RibbonGroupBox inside RibbonTabItem to the right?

if yes, then how ??

Thanks in advance

---
### Environment

- Fluent.Ribbon __v7.0.0__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
That's currently not possible out of the box.
What's your use case for that?

**Comment by EmbeddedAndMore** [comment]
There are some situations when user wants to have buttons on the right side because it is not coherent with other buttons on the left side. in my case, the reason is :
I have a **Help** button which I need to be on the right side of the ribbon.
this **Help** button should be inside each Tab. I mean I have 3 tabs and in each tab, I need this help button to be on the right side. separately from other buttons that are on the left side.

if you can suggest any possible solution that can align button on the right side without setting an explicit width between the left buttons and right buttons, that would be great.

Thanks in advance

**Comment by batzen** [comment]
Couldn't you use the use way it's done in the showcase app?
![image](https://user-images.githubusercontent.com/1971030/70377393-4bcd2f80-1914-11ea-949d-85ef9f6d8fab.png)

You could just add your button to `Ribbon.ToolBarItems`.

**Comment by EmbeddedAndMore** [comment]
interesting idea!
