### ISSUE TITLE
ComboBox.Height fixed at 22

### ISSUE THREAD

**Issue by mir4colix** [fluentribbon/Fluent.Ribbon#755]
Why is the ComboBox Template (ComboBox.xaml)  => Grid.Height set to 22?

Sure i can override it with a custom template, but why not set it auto or bind it to the ComboBox.Height ?
---
### Environment

- Fluent.Ribbon __v7
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
Because setting it to auto would cause all kinds of layout issues, as it won't align with all other controls.

Making the ribbon work with `Auto` for all controls would require a massive amount of work and the result would still have alignment issues for various controls.

**Comment by mir4colix** [comment]
ok. got it.

**Comment by batzen** [comment]
I had another look and you are indeed right. The height should be set on the style instead of the template.
