### ISSUE TITLE
Ribbon right-click menu offsetted for DPI=150% (or more)

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#757]
Set DPI to 150%. Restart the system and start the showcase app. Right-click on the caption...

![image](https://user-images.githubusercontent.com/958469/68859332-5155a200-06e7-11ea-90b5-c6c628677949.png)

---
### Environment

- Fluent.Ribbon __v7.0.0.0__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by znakeeye** [comment]
Any chance for a `7.0.1` nuget update? Or an "alpha"? This one is quite important for us :/

**Comment by batzen** [comment]
Will publish during the weekend.
