### ISSUE TITLE
Auto menu expanding not working for MenuItems with ItemSource binding

### ISSUE THREAD

**Issue by madenaras** [fluentribbon/Fluent.Ribbon#758]
Auto opening the submenu is not working for MenuItems with ItemsSource bindings.

Having a DropDownButton with ItemsSource binding, that binds to a collection of objects that themselves contain collections of objects (like "**Dropdown (auto close on click) g**" button, but with ItemsSource binding, not manually adding MenuItem elements in XAML).

Adapting the style with 
```
                        <Fluent:DropDownButton.ItemContainerStyle>
                            <Style TargetType="Fluent:MenuItem" BasedOn="{StaticResource Fluent.Ribbon.Styles.MenuItem}">
                                <Setter Value="{Binding Name}" Property="Header"/>
                                <Setter Value="{Binding MoreStuff}" Property="ItemsSource"/>
                            </Style>
                        </Fluent:DropDownButton.ItemContainerStyle>
```

Problem is pinpointed to File : Fluent.Ribbon\Controls\MenuItem.cs, line 434 and line 
450: `this.Parent` is null.

---
### Environment

- Fluent.Ribbon __v7.0.0
- Windows 7/10
- .NET Framework 4.61

**Comment by batzen** [comment]
Could you create a small repro app? I currently don't have enough time to do this myself.

**Comment by madenaras** [comment]
Hello,

Please find a demo app here: 
https://github.com/madenaras/FluentTest

Thanks!
