### ISSUE TITLE
Tabbing between spinners goes via spinner buttons

### ISSUE THREAD

**Issue by cbytte** [fluentribbon/Fluent.Ribbon#76]
* FluentTest program - Toolbars tab - Spinners group
* Set keyboardfocus in the first enabled spinner (named Right)
* press Tab to tab out of it

Result: keyboard focus moves to spinner buttons, before entering the next spinner text box.

It seems more intuitive to jump directly to the next spinner textbox, when filling out values in stacked spinners (or input boxes).
What do you think?

**Comment by batzen** [comment]
Sounds good.
