### ISSUE TITLE
Ribbon doesn't react to Theme change

### ISSUE THREAD

**Issue by shessrte** [fluentribbon/Fluent.Ribbon#762]
I'm using the ribbon in a MahMetro Window, synced the Theme Managers as per the showcase demo. While I can see in debug that the managers both are switching to the new theme (as does the window), the ribbon however doesn't. When looking at the ribbon state in Snoop, in the showcase demo I can see the Foreground and Background colors change as the theme is switched. In my application, no change happens on theme change. Anyone have any idea what might be causing this?

Thanks,
Stefan
---
### Environment

- Fluent.Ribbon __v7.0.0__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
Any chance you could provide a repro?

**Comment by shessrte** [comment]
I’m trying to separate the problem into a single project (our solution consists of more than 100 single projects, which I cannot provide). So far I have not been able to reproduce the issue.
 
Von: Bastian Schmidt <notifications@github.com> 
Gesendet: Donnerstag, 5. Dezember 2019 17:52
An: fluentribbon/Fluent.Ribbon <fluent.ribbon@noreply.github.com>
Cc: shessrte <s.hess.extern@rte.de>; Author <author@noreply.github.com>
Betreff: Re: [fluentribbon/Fluent.Ribbon] Ribbon doesn't react to Theme change (#762)
 
Any chance you could provide a repro?

**Comment by shessrte** [comment]
It took me some time to finally get around to this.  The attached project shows the issue. Window changes theme, but ribbon keeps a white background even with a dark theme.  At first I thought that it was due to us adding the tabs via code and not in the ribbon definition, but when I tested this out it showed that the same happens with the tab defined in Xaml.  What I want is the Ribbon to behave the same as in your showcase, i.e. also go to a dark theme if one is selected.
 
Thanks,
Stefan
 
 
Von: Bastian Schmidt <notifications@github.com> 
Gesendet: Donnerstag, 5. Dezember 2019 17:52
An: fluentribbon/Fluent.Ribbon <fluent.ribbon@noreply.github.com>
Cc: shessrte <s.hess.extern@rte.de>; Author <author@noreply.github.com>
Betreff: Re: [fluentribbon/Fluent.Ribbon] Ribbon doesn't react to Theme change (#762)
 
Any chance you could provide a repro?

**Comment by batzen** [comment]
@shessrte Your attachment got lost while replying by mail. Github doesn't show mail attachments. Could you attach it to this issue manually? You should be able to just drag and drop the file on the area where you write your reply and then hit "Comment".

**Comment by shessrte** [comment]
[RibbonTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4046679/RibbonTest.zip)

**Comment by batzen** [comment]
Well you are changing themes on the application level but include the resources on the window level.

You can solve this in two ways:
- move the resource includes from the window to app.xaml
- or change your thememanager code to not use Application.Current but your current window instead

I would suggest you use the first way as you'd have to do this for every window you want to change themes on if you'd go for way two.

**Comment by shessrte** [comment]
Thank you very much. I already thought that I was overlooking something.
