### ISSUE TITLE
Adding QuickAccessItems in code requires InvalidateMeasure()?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#763]
I'm trying to understand an issue that we finally solved with a call to `InvalidateMeasure()`. It feels like a bug in `Fluent Ribbon`, but I'm not sure.

1. We add `QuickAccessItems` from code **after** the ribbon has been initialized/loaded:

```c#
ribbon.QuickAccessItems.Add(quickAccessMenuItem);
```

2. We have enabled automatic state management:

```xml
<fluent:Ribbon AutomaticStateManagement="True" ...
```

3. And the result is that our quick access menu items are never added to the visually tree. On some machines (it seems). Seems like a race condition of some kind.

**The workaround**
Anyway, if we add the following before adding our `QuickAccessItems` the items are indeed present in the visual tree:

```c#
ribbon.TitleBar.InvalidateMeasure();
ribbon.QuickAccessItems.Add(quickAccessMenuItem);
```

**Is this expected?** Is there a good explanation for this?

**Comment by batzen** [comment]
It might be the case that automatic statemanagement interferes here as all QAT items are cleared when the saved state is loaded. Could you share a repro for this?

**Comment by znakeeye** [comment]
Actually, we reproduced it after setting the `AutomaticStateManagement` flag to `false`. We will try to reproduce it in an isolated sample. So far we have failed.

**Comment by batzen** [comment]
You could try to debug the removal of your item by listening to changes of QuickAccessItems and share the stacktrace. Maybe that's enough information to fix the issue.

**Comment by batzen** [comment]
I guess this might be related to #751 which i just fixed.
Could you have a look if that also fixes your issue?

**Comment by znakeeye** [comment]
Can you publish a nuget? Then we can verify this on Monday!

**Comment by batzen** [comment]
Will, most likely, publish version 7.0.1 tomorrow.

**Comment by znakeeye** [comment]
Unfortunately, `7.0.1` actually made it worse :(

Now our workaround has no effect. The problem now is that the Quick Access Items are initially gone, then they **appear on window sizing**. As you can see, there is an arrow with an empty (?!) menu:

![quick-access-bug](https://user-images.githubusercontent.com/958469/70424907-6e745b00-1a70-11ea-908f-702a8223750d.png)

**Comment by batzen** [comment]
That's strange. As the fix i made was to call `this.TitleBar?.ForceMeasureAndArrange();` once the ribbon itself is loaded.
Were you able to reproduce the issue in isolation?
If you can't create a isolated repro i could also do some testing/debugging on your real application.
If you can't share your application publicly here feel free to contact me on gitter.
