### ISSUE TITLE
GalleryPanel does not resize properly on apply of filter

### ISSUE THREAD

**Issue by SuperLeiyan** [fluentribbon/Fluent.Ribbon#769]
I'm currently working on a project that uses the InRibbonGallery control. The control has a number of items it hosts, each item has a string property called "Folder" and the entire collection is grouped by "Folder" in the drop-down.

**What I would like to achieve is the following:**
- Filter "InRibbonGallery" down to items in the same "Folder" as the currently selected item.
- The filter needs to be disabled when drop-down appears, allowing the user to see all the groups/"Folder"s.
- A filter is reapplied upon user selecting an item in the drop-down.

So far everything works fine except the scroll down button would not disable when filtering down to a "Folder" with an item count less than or equal to "MaxItemsInRow".

The enable/disable logic for the scroll buttons are based on "ScrollableHeight" property in the "ScrollViewer", which doesn't change at all, and it looks like it's due to GalleryPanel height not adjusting to the new filtered down collection

I hope I've described my issue clear enough as I'm unable to provide zipped code

---
### Environment

- Fluent.Ribbon v7.0.1
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Why are you unable to provide zipped code?

**Comment by batzen** [comment]
Was able to reproduce this in the showcase application.
