### ISSUE TITLE
How to bind the IsSelected property to RibbonTab in viewmodel?

### ISSUE THREAD

**Issue by dswfort** [fluentribbon/Fluent.Ribbon#771]
Sorry for my poor English...

Previously I used the IsSelected property in code behind, it worked correctly.

But recently I was developing a new software based on the MVVM mode , I tried to bind the `IsSelected` property of ribbon tab with my view model.

For example, I have defined an enumeration like this.

```C#
enum RibbonTabNames : int
{
    None = -1,
    Start = 0,
    Setting = 1,
    Qc = 2,
    Om = 3,

    EditOm = 4
}
```

And Then, I created a converter.

```C#
[ValueConversion(typeof(RibbonTabNames), typeof(bool))]
public class SelectRibbonContextualTabGroupConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        RibbonTabNames currentTab = (RibbonTabNames)value;
        RibbonTabNames requiredTab = (RibbonTabNames)System.Convert.ToInt32(parameter);

        return currentTab == requiredTab;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        bool isSelected = (bool)value;
        if (!isSelected)
        {
            return RibbonTabNames.None;
        }
        return (RibbonTabNames)int.Parse(parameter.ToString());
    }
}
```

At last, the view model code like below.

```C#
public MainViewModel()
{
    SelectedRibbonTab = RibbonTabNames.Data;
}
```

The xaml code is like this.

```XAML
IsSelected="{Binding SelectedRibbonTab, ConverterParameter=1, Converter={StaticResource selectRibbonContextualTabGroupConverter}}"
```

What I want to achieve is `Setting`  tab to be selected, but actually still got the `Start` tab selected

![2020012001](https://user-images.githubusercontent.com/57698521/72693684-db4d3b80-3b6c-11ea-83af-23a3d5b4a093.PNG)

Here is my test demo, I don't know if I can use `IsSelected` property just like bind `Selected`  to radio button.

[WpfApp3.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4084141/WpfApp3.zip)

Waiting for your reply, thanks.

---
### Environment

- Fluent.Ribbon v7.0.1
- Windows 10
- .NET Framework 4.5

**Comment by batzen** [comment]
The issue with using `IsSelected` as the driver for tab selection is that, before selecting a new tab, the ribbon de-selects the previous one. In addition to that you now have multiple potential sources for the selected tab item as your property also binds two-way. As soon as the ribbon says one tab got de-selected or selected your converter triggers multiple times, thus potentially changing the value back and forth.
This causes your binding value to "flipper" around.

A better approach would be to use the selection properties like `SelectedTabItem` or `SelectedTabIndex` from `Ribbon`. That way you got one binding point instead of multiple.

**Comment by dswfort** [comment]
Thank you, I will try it soon~

**Comment by dswfort** [comment]
I still have some troubles...

Now, I am trying bind `SelectedTabIndex` with `SelectedIndex` property defined in my viewmodel. When I set`SelectedIndex`= `1`, actually the selected tab in ribbon did not change. It still seleced the first tab.

Here is my code.

```C#
private int m_SelectedIndex = 1;
public int SelectedIndex
{
    get { return m_SelectedIndex; }
    set
    {
        if (m_SelectedIndex != value)
        {
            m_SelectedIndex = value;
            OnPropertyChanged(nameof(SelectedIndex));
        }
    }
}
```

``` XAML
<Fluent:Ribbon AutomaticStateManagement="True" IsQuickAccessToolBarVisible="False" SelectedTabIndex="{Binding SelectedIndex}">
```

**Comment by batzen** [comment]
Could you try to set the BindingMode to TwoWay on your binding?

**Comment by dswfort** [comment]
Thank you very much, my problem has been solved!
