### ISSUE TITLE
Backstage & Keyboard navigation

### ISSUE THREAD

**Issue by robertmuehsig** [fluentribbon/Fluent.Ribbon#772]
I tried to use the keyboard to navigate through the Fluent.Ribbon.Showcase application. 

The backstage area is easy to open with the keyboard, but unfortunately it seems not possible to navigate with "Tab" properly. 

Sometimes it seems that the underlying elements are still focusable. Even the menu items (e.g. "Introduction" can be focused sometimes using Tab, I can't navigate with [Space] or [Enter].

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows 10 1903
- .NET Framework 4.6.2

**Comment by batzen** [comment]
@robertmuehsig i made the first changes for better keyboard navigation. It's not perfect yet, but a lot better.
While implementing the changes i also noticed that there is no real visual feedback for the current focus.
Will track the improvements to that through #792.
