### ISSUE TITLE
Hide RibbonGroupBox if it has no content

### ISSUE THREAD

**Issue by CodCase** [fluentribbon/Fluent.Ribbon#773]
Hi :)

I would like to hide/remove empty RibbonGroupBoxes but leave the tabs with their names.
Something like Height 0 or visibility hidden.

How can I achive that?

Thank you

---
### Environment

- Fluent.Ribbon __v7.0.1__
- Windows __10__
- .NET Framework __Core 3.1__

**Comment by batzen** [comment]
You can just set `Visibility` to `Collapsed` on your group to achieve this.
