### ISSUE TITLE
Text is cut off when increasing Windows font size

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#774]
When you increase the Windows font size, the control looks like this:

![image](https://user-images.githubusercontent.com/9450861/73124735-7d956680-3f53-11ea-8f46-49617706cfad.png)

I don't have a fixed height set for the ribbon control.

---
### Environment

- Fluent.Ribbon v7.0.1
- Windows 10 v1903
- .NET Framework 4.7

**Comment by batzen** [comment]
That's something i have no idea on any path to fix it.
The ribbon has to make certain guarantees about layout sizes, especially heights.
Making it adapt to dynamic font sizes was requested in the past already and would require a huge amount of work.
To be honest i won't invest the required time for that. If you or someone else has any ideas on how to solve this or wants to jump in, feel free. In the past everyone stepped back when i said that. ;-)

**Comment by RandomEngy** [comment]
Looks like Word increases the ribbon height when font size is increased:

![image](https://user-images.githubusercontent.com/9450861/77483173-bf704b00-6de4-11ea-9934-2ba22e0f35db.png)

Though, I understand it being a difficult issue. You'd probably need to update the places that depend on the ribbon being a guaranteed height. And the project does seem a little too large for me to take on right now.

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
