### ISSUE TITLE
First underscore missing in drop down menu header text

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#775]
The first underscore is missing in the `Header` text given to a `Fluent.MenuItem`.

![image](https://user-images.githubusercontent.com/9450861/73719998-cd9fc600-46d5-11ea-905a-b722c45faa0b.png)

I verified it was being given the correct text in the debugger.

---
### Environment

- Fluent.Ribbon v7.0.1
- Windows 10 v1903
- .NET Framework 4.7.1

**Comment by batzen** [comment]
That's by design as it's an AccessText and the underscore is the marker for access keys/shortcuts.
I will try to add a property with which you can disable this behavior for ribbon menuitem.

**Comment by RandomEngy** [comment]
Thanks!

**Comment by RandomEngy** [comment]
Just tried it out. Works great.
