### ISSUE TITLE
RibbonGroupBox image rendering

### ISSUE THREAD

**Issue by fialo4ka** [fluentribbon/Fluent.Ribbon#776]
Could you please help me to resolve an image rendering in RibbonGroupBox 
My problem is when group has enough space to show icon inside, it work perfect, but when it has no space, and RibbonGroupBox  is collapsed image is not shown, but it exist.
![image](https://user-images.githubusercontent.com/36087929/74155719-5a3a0f00-4c15-11ea-9fa7-f34164b4b938.png)
![image](https://user-images.githubusercontent.com/36087929/74155793-6f16a280-4c15-11ea-8d4d-a0b1b0afd37b.png)

```
RibbonGroupBox newGroup = new RibbonGroupBox
{ 
   Header = childMenu.Name, 
   Name = ribbonGroupName, 
   Icon = childMenu.LargeIcon
 };
newTab.Groups.Add(newGroup);
```

---
### Environment

- Fluent.Ribbon __v7.0.1__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
This works fine in the showcase application so i guess there is something wrong with your icon/image.
Could you create a repro and attach it to this issue?

**Comment by fialo4ka** [comment]
O...
I'm very sorry, I create a separate solution only with ribbon, and found the bug!
Thank you very much!
