### ISSUE TITLE
Loading Themes/Generic.xaml from a sub-assembly / non-WPF application?

### ISSUE THREAD

**Issue by DaveInCaz** [fluentribbon/Fluent.Ribbon#777]
My application uses Fluent.Ribbon from within a sub-assembly; ie it is compiled into a DLL rather than an EXE. Also, the main application is not WPF but actually is unmanaged.

Reading the documentation https://fluentribbon.github.io/documentation/basic-setup it says:

> To setup the required resources you first have to add the following code to your App.xaml:
> 
> ```
> <Application.Resources>
>     
>     <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
> </Application.Resources>
> 
> ```

So in my case where the WPF components are hosted in an unmanaged program, there is no defined `Application` object by default. So there is no `App.xaml`. 

As a workaround, it is possible to create it manually, and that works... But it feels a bit like a hack (details below). So my question is - _is there any alternative to loading the generic resources into the Application resources?_

My impression is that Fluent.Ribbon is specifically looking in the global `Application` object for its resources, which is why this approach is necessary. But maybe there is some other manual way to configure it to look elsewhere..?

If not, this might be something to consider for the future. For instance, why not have an option to load the resources into the Window itself rather than the entire application?

Thanks!

---

Notes - what I am doing right now is:

First - manually initialize `Application`:

```
            if (System.Windows.Application.Current == null)
            {
                new System.Windows.Application();
            }
```

Second - create a resource dictionary for the assembly:

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
   >

    <ResourceDictionary.MergedDictionaries>

...
        <!-- Fluent Ribbon themes: -->
        <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />

    </ResourceDictionary.MergedDictionaries>

```

Finally - load the resources xaml:

```
            var rd = new ResourceDictionary();
            rd.Source = new Uri("pack://application:,,,/myapp;component/path/Resources.xaml", UriKind.Absolute);
            Application.Current.Resources.MergedDictionaries.Add(rd);

```

Like I said, this all works. But manually taking ownership of the `Application `object like this doesn't seem quite right. Or at least, this has more maintenance overhead.

---
### Environment

- Fluent.Ribbon 7.0.1
- Windows Version	10.0.17763 Build 17763
- .NET Framework 4.72

**Comment by batzen** [comment]
Looking up resources at the application level is nothing special to Fluent.Ribbon.
It's simply one step in the default resource lookup of WPF.
You can, of course, include the resources at the window level, but you shouldn't do that as it causes performance issues as resources included at the window level have to be loaded every time your show your window.

Fluent.Ribbon has no special code for looking up resources and relies entirely on the way WPF works.
When looking for resources WPF looks at the closest scope first and they works it's way up to the application level.

I don't consider the way you are doing it, in code behind, as hacky. That's the way you should do it if you own the application and care about performance and memory consumption.
It's exactly the same way i use at work where the host application is written in VB6 and parts of the UI are written in WPF.
The only difference is that i use
```
var source = new Uri("........");
var rd = (ResourceDictionary)Application.LoadComponent(source);
Application.Current.Resources.MergedDictionaries.Add(rd);
```

**Comment by DaveInCaz** [comment]
Hi @batzen, thanks for your comments & feedback. Interesting to hear your work app is VB6 because that's exactly what mine is also. We're gradually porting most of it to C# but have mixed releases for a while.

Regarding your comment about how WPF loads from local upwards -- does that mean I was taking the documentation statement "you first have to add the following code to your App.xaml" too literally?

I take your point though about performance, that is definitely something I'll keep an eye on wrt resource loading.

**Comment by batzen** [comment]
Yes, you took it too literally. The docu just shows the way it's supposed to be done in 99% of the cases. Embedding wpf in a vb6 application, as we both do, is not the 99% case 😉

If you have any questions about working in this mixed world feel free to ask. I am living in this mixed world since 2009 already.

**Comment by DaveInCaz** [comment]
Thanks for all the input!
