### ISSUE TITLE
Titlebar should be transparent if backstage is open

### ISSUE THREAD

**Issue by frostieDE** [fluentribbon/Fluent.Ribbon#780]
After opening the backstage menu, the titlebar should be transparent and should not match the accent color as it currently does. Also, the foreground color of the header as well as the color of the windows commands need to be changed.

Only the "Colorful" base color is affected. "Light" and "Dark" work as expected.

Currently:

![grafik](https://user-images.githubusercontent.com/3764924/75681109-35c0d800-5c93-11ea-8486-73bd06b86e0a.png)

Desired: the marked section in the following screenshot should be gray (or transparent):

![grafik](https://user-images.githubusercontent.com/3764924/75681394-c992a400-5c93-11ea-8818-d49e4b783eb3.png)

This is a screenshot taken from Visio:

![grafik](https://user-images.githubusercontent.com/3764924/75681197-66087680-5c93-11ea-9f9d-77396a9ba96d.png)

---
### Environment

- Fluent.Ribbon v7.0.1 (installed from NuGet)
- Windows 10 1909 (Build 18363.657)
- .NET Framework Core 3.1

**Comment by frostieDE** [comment]
I was digging through the code... I guess the problem is, that the RibbonTitleBar does not know about any backstage that opened, does it? Thus, it is not possible for the RibbonTitlebar to detect whether it should be transparent.

**Comment by batzen** [comment]
Which office version are you using? As far as i remember the version that was current when the colorful themes were added office kept the color.
The ribbon itself doesn't know about the backstage. But the backstage does know about the ribbon and already controls various aspects of the ribbon.

**Comment by frostieDE** [comment]
I am currently using Office 365, but Office 2019 already behaves the same way:

![grafik](https://user-images.githubusercontent.com/3764924/75695917-0ddd6e80-5cab-11ea-9101-7ea71ed370a2.png)

**Comment by frostieDE** [comment]
> The ribbon itself doesn't know about the backstage. But the backstage does know about the ribbon and already controls various aspects of the ribbon.

Okay, if I find some time, I will dig further into the code and take a look at the backstage. But I am afraid that we might need to add `Fluent.Ribbon.Brushes.RibbonWindow.BackstageOpen.TitleBackground` and `Fluent.Ribbon.Brushes.RibbonWindow.BackstageOpen.TitleForeground` brushes.

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
