### ISSUE TITLE
Exception when manually creating the RibbonWindow

### ISSUE THREAD

**Issue by Oliver2710** [fluentribbon/Fluent.Ribbon#781]
Hi!
Instead of using App.xaml's StartupUri, I want to create the RibbonWindow in the OnStartup function of my application. But when calling Show(), I get a NullReferenceException. This is thrown in RibbonProperties.GetLastVisibleWidth(DependencyObject element) when called with RibbonWindow.WindowsCommands.ItemsControl as parameter.

Here is how I create the RibbonWindow (MainWindow is derived from Fluent.RibbonWindow):
  public partial class App : Application
  {
    [STAThreadAttribute ()]
    [GeneratedCodeAttribute ( "PresentationBuildTasks", "4.0.0.0" )]
    public static void Main ()
    {
      var app = new App ();
      app.Run ();
    }

    protected override void OnStartup ( StartupEventArgs e )
    {
      base.OnStartup ( e );
      var window = new MainWindow ();
      window.Show ();
    }
  }
[FluentRibbonTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4319622/FluentRibbonTest.zip)

---
### Environment

- Fluent.Ribbon __v7.0.1__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
The only case i know this happens is if the Generic.xaml from Fluent.Ribbon is not included as a merged dictionary in app.xaml, or by using code or in the windows merged dictionaries.

**Comment by Oliver2710** [comment]
Thanks for the quick response. Even though it does not directly solve the problem, it points to the right direction. When creating the RibbonWindow manually (like in my example in App.OnStartup()), the Generic.xaml must be added to the window's resources instead to the app.xaml resources. This solves the problem!

**Comment by batzen** [comment]
If you plan to use more than one RibbonWindow you are better off adding generic.xaml to the merged dictionaries of your app. You can also do that in your startup method.
If you load the file in every window you get quite a performance issue and changing themes, in case you plan to add that, would have to be done for every single window.

**Comment by Oliver2710** [comment]
Thanks! Adding it in App.OnStartup() to the merged dictionaries works fine and should avoid the performance issues you mentioned!

**Comment by batzen** [comment]
Glad I could help.
