### ISSUE TITLE
Recommended icon size - too much time to display RibbonTabItem 

### ISSUE THREAD

**Issue by mystery123sk** [fluentribbon/Fluent.Ribbon#785]
It takes about 7 seconds (!!) to display next RibbonTabItem with many icons. That's very long, is it possible to improve this? I suspect the problem is, the icon size is not good and the library needs to resize them.

My ribbon:
![ribbon](https://user-images.githubusercontent.com/47751249/78773377-6d5a2880-7993-11ea-9f0d-0fb57355f5d2.PNG)

---
### Environment

- Fluent.Ribbon __v7.0.0.0__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
I would suggest using a profiler to find the culprit of your issue.
Do you have a repro for this?

**Comment by mystery123sk** [comment]
Seems like the problem is in some external code:

![image](https://user-images.githubusercontent.com/47751249/78786677-781fb800-79a9-11ea-9e36-ee71836c819b.png)

But now I think, since I've updated Windows 10 to latest version, everything slowed down. I've also tested on virtual PC and there it works all fine. 

Thanks for the suggestion though.

**Comment by batzen** [comment]
That just points to WPF. Maybe you can use the UI profiling tool in visual studio to get better information about what's causing the perf issue.

**Comment by mystery123sk** [comment]
Seems like the problem is in the buttons when using bitmap. As you can see, the layout took 8 seconds... 

![image](https://user-images.githubusercontent.com/47751249/79001894-a0e1b200-7b4f-11ea-932f-070ef164a439.png)

**Comment by batzen** [comment]
Are you able to share a repro? Then i could have a look at it.

**Comment by batzen** [comment]
@mystery123sk ping

**Comment by mystery123sk** [comment]
Can't share for this one, sorry, lot of company "secret" stuff inside :( ...

**Comment by batzen** [comment]
If you can't share a repro there is little to nothing i can do to help you.
Could you isolate parts of your application, like creating a new small one, add some of your icons to it and check if that also has performance issues? Maybe that works and you could share that small sample project.

**Comment by mystery123sk** [comment]
I made a simple app, here is the application timeline from VS:
[Report20200423-0700.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4520338/Report20200423-0700.zip)

**Comment by batzen** [comment]
@mystery123sk Sorry for taking so long to respond. Could you share your simple app? The timeline alone does not reveal what's taking so long.
