### ISSUE TITLE
InRibbonGallery: Dynamic ItemWidth / use translated Text in items

### ISSUE THREAD

**Issue by MenzenJ** [fluentribbon/Fluent.Ribbon#786]
I'm trying to achieve an InRibbonGallery where you can select an option and use Icon + Text for those options. I basically convert the Gallery to a list by setting MaxItemsInRow to 1.
It should look like this:
![InRibbonTemplates](https://user-images.githubusercontent.com/44610481/78781587-d300e180-79a0-11ea-8796-2bbcc63da94b.PNG)
The text of the options is translated, so I do not know the ItemWidth.
The issue is: If the first item of the gallery is not the longest the other items get cut off:
![InRibbonGallery](https://user-images.githubusercontent.com/44610481/78781038-db0c5180-799f-11ea-98d5-54a88c7be940.PNG)
The same is true for the Popup. Even if I resize the popup, the items remain the same fixed size:
![InRibbonGalleryFixedSize](https://user-images.githubusercontent.com/44610481/78781627-e6ac4800-79a0-11ea-8075-64f8f8593c33.PNG)
The Xaml used for the Screenshots:
```<fluent:RibbonTabItem Header="Gallery Test">
<fluent:RibbonGroupBox Header="Actual">
    <fluent:InRibbonGallery Header="Templates" MaxItemsInRow="1" MaxItemsInDropDownRow="1" ResizeMode="Both" Selectable="False">
        <TextBlock Text="Hallo"/>
        <TextBlock Text="Hallo text text"/>
        <TextBlock Text="Hallo text"/>
   </fluent:InRibbonGallery>
</fluent:RibbonGroupBox>
<fluent:RibbonGroupBox Header="Expected">
    <fluent:InRibbonGallery Header="Templates" MaxItemsInRow="1" MaxItemsInDropDownRow="1" ResizeMode="Both" Selectable="False">
        <!-- spaces as workaround -->
        <TextBlock Text="Hallo                "/>
       <TextBlock Text="Hallo text text"/>
       <TextBlock Text="Hallo text"/>
    </fluent:InRibbonGallery>
</fluent:RibbonGroupBox>
```
I currently use spaces in the first item to fill it up to the longest item's text, which of course is not ideal.
Do you consider this as a use case for the InRibbonGallery or should I use another control to achieve the list with DropDown i.e. a SplitButton or something else?

PS: I thought this was an issue caused by #666

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Framework __4.7.1__

**Comment by batzen** [comment]
I consider this a bug in Fluent.Ribbon. Will investigate.
