### ISSUE TITLE
Side by side issues when applying themes

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#787]
We have issues with backwards compatibility with plugins that use Fluent 6.x, but we have upgraded our shell to Fluent 7.x.

The first thing that happened was that there were issues with `ThemeManager.` We solved them by explicitly adding the version to the xaml loading:

```
                var assembly = typeof(ThemeManager).Assembly;
                var name = assembly.GetName();
                var assemblyName = name.Name;
                var assemblyVersion = name.Version;
                var resourceNames = assembly.GetManifestResourceNames();

                ...

                           var resourceDictionary = new ResourceDictionary
                            {
                                Source = new Uri($"pack://application:,,,/{assemblyName};v{assemblyVersion};component/{stringKey.Replace(".baml", ".xaml")}")
                            };
```

This seems to fix *part of* the problem. Will continue to do more research and hopefully provide a PR with some fixes.

**Comment by GeertvanHorrik** [comment]
When we try to do assembly forwarding *and* remove the 6.x lib from the output, we get this:

```
System.TypeLoadException: 'Could not load type 'XamlGeneratedNamespace.GeneratedInternalTypeHelper' from assembly 'Fluent, Version=7.0.0.0, Culture=neutral, PublicKeyToken=3e436e32a8c5546f'.'
```

**Comment by batzen** [comment]
I don't fully understand your issues as major versions are not meant to be backwards compatible.
For example, version 8 will not contain the ThemeManger anymore as it's being moved to ControlzEx.

**Comment by GeertvanHorrik** [comment]
Yeah, I think it was naïve of me to think we could support a smooth upgrade path. Let's close this ticket and just bump our shell in major version as well.

Thanks.
