### ISSUE TITLE
Maximize icon is incorrectly drawn on high-dpi displays

### ISSUE THREAD

**Issue by Razzile** [fluentribbon/Fluent.Ribbon#788]
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Framework __4.6.2__

![image](https://user-images.githubusercontent.com/5256381/78843211-1b002280-79fa-11ea-9157-769c432f36d7.png)

The square for maximize is incorrectly drawn.

MahApps.Metro had a similar issue previously too https://github.com/MahApps/MahApps.Metro/issues/3329

**Comment by batzen** [comment]
I guess it's exactly the same issue as i copied the code for the WindowCommands from MahApps.Metro a few years ago.

**Comment by punker76** [comment]
@batzen I can re-update this 😉

**Comment by batzen** [comment]
@punker76 thx for offering, but i am already done locally. Will take the win10 path data etc. 👍
