### ISSUE TITLE
Opening gallery messes up InRibbonGallery resizing.

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#789]
There is a problem with the resizing of the InRibbonGallery. As long as the gallery is closed, there is no problem. But once it is opened and closed again, the sizing is messed up. See the following screenshots. The gallery is set to MaxItemsInRow="5" and MinItemsInRow="1". For the first screenshot I reduced the width of the window that the number of shown gallery items are reduced to 3. Then I just open and close the gallery.

![Layouts1](https://user-images.githubusercontent.com/9028723/78924547-57835b00-7a9a-11ea-81e3-d7017c85c31b.png)

Open gallery:
![Layouts2](https://user-images.githubusercontent.com/9028723/78924555-5a7e4b80-7a9a-11ea-9c37-a0cd0d539aaf.png)

Close gallery: 
![Layouts3](https://user-images.githubusercontent.com/9028723/78924563-5ce0a580-7a9a-11ea-992b-d3177c5b1903.png)

Now more items are shown in the gallery than before and the size of the remaining controls is reduced to adjust the sizing.

This is probably related to issue #765.

- Fluent.Ribbon v7.1.0
- Windows 10
- .NET Framework 4.7.2

**Comment by pschimmel** [comment]
Here's a sample project. It can be reproduced with InRibbonGalleries within DataTemplates and without (Button 1 and Button 2).

[GalleryTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4457836/GalleryTest.zip)

**Comment by batzen** [comment]
Can also reproduce this in the showcase application. Don't know how this slipped through...

**Comment by pschimmel** [comment]
Hi Bastian,

I saw that you closed the issue, so I did some testing. The resizing itself seems to be fixed, However, there are still problems with the layouting of items inside the InRibbonGallery. 

Please see the following screenshots taken from the latest Showcase application:

![Screenshots](https://user-images.githubusercontent.com/9028723/79053938-6d7f5000-7c41-11ea-9171-3f5ff736b6e3.png)

I reduced the width of the window that the eight items of the 2nd grouped gallery is displayed in two rows.

Then I just opened the gallery and closed it again.

After that, on the 3rd image, the orange item is gone and the scrollbars are disabled.

Even worse, when I open the gallery again, the size is completely different and the scrollbars are still disabled. When I now resize the opened gallery, I see that all items are still there.

I think the issue should be reopened.

All the best,
Patrick

**Comment by batzen** [comment]
I can't reproduce the issue in the showcase application.
Do you have any additional steps to reproduce?

![fluent ribbon #789](https://user-images.githubusercontent.com/1971030/79062425-97189580-7c9a-11ea-9adf-b539539c6653.gif)

**Comment by pschimmel** [comment]
I don't know. It looks like I did the same steps as you.
See following video.

[FluentGalleries.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4466498/FluentGalleries.zip)

I build the code from the development branch of 11 April. I tried with debug builds and release builds of net462 and core.

**Comment by batzen** [comment]
I can't open the video, every player i have says it's corrupted...

**Comment by batzen** [comment]
Could you try to download the compile showcase application from the appveyor feed to see if that version also has the buggy behavior?

**Comment by pschimmel** [comment]
How can I get the showcase application from appveyor? I added the NuGet feed https://ci.appveyor.com/nuget/fluent-ribbon to my NuGet package manager, but with that I only get Fluent.dll.

About my video: You're right I can also not play it with Media Player. VLC media player seems to work.

**Comment by batzen** [comment]
You can get it from https://ci.appveyor.com/project/batzen/fluent-ribbon/branch/develop/artifacts

**Comment by pschimmel** [comment]
The problem is still reproducible with the executable downloaded from the link. I tested version Fluent.Ribbon-v7.2.0-alpha0017.

I think I found what could make a difference. I changed the windows font scaling from 100% to 125% and then it works OK. With font scaling of 100% the problem is there.

[Showcase FontScaling.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4466796/Showcase.FontScaling.zip)

I uploaded two new videos one with font scaling 100% and one work 125%. In the 125% version, the gallery items don't disappear, but when opening the first gallery in that group, the popup size seems different. in the 100% version, the problem described earlier is fully reproducible.

**Comment by batzen** [comment]
That's very strange. My system runs with 100% scaling all the time. Not being able to reproduce the issue on my machine will make fixing very difficult and you will have to test every iteration i make. Could we chat on gitter or twitter for that? That way i can send you test versions instead of pushing my changes.

**Comment by batzen** [comment]
It seems to be a rounding issue. I changed the item width for those two galleries from 50 to 52 as i noticed that "Orange" was cut off at the "e" partially. With that change i am able to reproduce your issue. Will investigate.

**Comment by pschimmel** [comment]
Great. Just send me a new version via Gitter once you have found a solution.
