### ISSUE TITLE
Disabled combobox does not display disabled font color

### ISSUE THREAD

**Issue by cbytte** [fluentribbon/Fluent.Ribbon#79]
Repro:
* FluentTest v3.4
* Edit code: set  IsEnabled="False" for combobox "FilterComboBox" in the 'Insert' tab
* Run

Actual result: The first item 'Show all' is displayed with non-disabled font

**Comment by batzen** [comment]
Can't reproduce.
Which theme are you using?
A screenshot would help a lot. ;-)

**Comment by batzen** [comment]
Any news on this one?
