### ISSUE TITLE
LargeIcon error

### ISSUE THREAD

**Issue by khaled-sowaid** [fluentribbon/Fluent.Ribbon#790]
**I couldn't add an icon, always the same error message
System.Windows.Markup.XamlParseException: 'Cannot locate resource 'images/001-accident.png'.' **
**https://mega.nz/file/wRJzXQDC#r5c-vjqTNOaJoLywv8_DsWFVuKFp1GXBf2ZNgCW08o8**

---
### wpf c#
- Fluent.Ribbon __v7.1.0__
- Windows __10__
[WpfApp2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4464880/WpfApp2.zip)

- .NET cor __3.1__

**Comment by batzen** [comment]
In order to use that shortcut syntax for images/icons in Fluent.Ribbon you have to either copy your images to a folder in your output path or embed them as resources.
Otherwise there is no way to resolve those images/icons.

**Comment by khaled-sowaid** [comment]
I have added pictures to windw Resource 
<ResourceDictionary>
            <BitmapImage x:Key="Im1" UriSource="/images/001-accounting.png"/>
</ResourceDictionary>

*****
 LargeIcon="{StaticResource Im1}"

********
It works perfectly in .net framework 
But it does not work in .net core 
********
Or do you mean adding an additional resource in a different way, please give me an example
I would be grateful to you

**Comment by batzen** [comment]
You could try adding the following to your project file:
```
<ItemGroup>
    <Resource Include="images/*.png" />
</ItemGroup>
```
That should do the trick to get your images embedded as resources.

**Comment by khaled-sowaid** [comment]
It worked, thank you

**Comment by batzen** [comment]
Glad i could help. 👍
