### ISSUE TITLE
Problem with dynamic items in InRibbonGallery 

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#791]
Hi! 

I'm afraid I have found some more issues with the InRibbonGallery. This is a follow-up of issue #789 . I used Fluent version 7.2.0 alpha 18 from https://ci.appveyor.com/project/batzen/fluent-ribbon/branch/develop/artifacts
I've used my test app, but I could also reproduce it in the Showcase application by adding a similar scenario there. 
Mainly, I used an ObservableCollection to hold the gallery items and add and remove the items dynamically.

please take a look at the following video:

[AnotherGalleryTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4489661/AnotherGalleryTest.zip)

You can see that I add items to the last gallery until there is not enough space available. 
Then I add another item and the other galleries in the same group are reduced => Awesome!

But when I clear the items in the gallery after that, the available space is not used by the other galleries.

There is also one more problem, which is a bit hard to see in the video:
Although the items are gone in the underlying collection, I can still see the items for a split-second when opening the gallery pop-up. Therefore the gallery popup is also wider than necessary at the end of the video.

This is the test application I used in the video:

[FluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4489679/FluentTest.zip)

To start the window, click on the 2nd button.

**Comment by pschimmel** [comment]
This video was taken during a debugging session that the issue is better visible: 

[AnotherGalleryTest2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4489771/AnotherGalleryTest2.zip)

**Comment by batzen** [comment]
I already know what's causing a part of this. The snapped image does not get updated if the size of the gallery is zero. But the real issue is that the snapped image is kept in memory after the dropdown is closed. That should be the cause for the flicker. Not sure about the resizing and popup size issue.
Will have a look at this when i am finished with fixing the item width issue reported in a different issue.
