### ISSUE TITLE
Check mark of menuitem not visible

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#795]
Hi!

In our application the check mark of menu items is not visible. The reason for that is that we mainly use opaque colors in our custom theme.

I think the problem is that the check mark of menu items (checkedImage), e.g. QuickAccessMenuItem is behind the iconImageBorder. That means in order to be visible, the ToggleButton.Checked.Background brush needs to be semi transparent.

**Comment by pschimmel** [comment]
Currently the Quick Access menu items look like this:
![b4](https://user-images.githubusercontent.com/9028723/80793515-9dae7480-8b97-11ea-8661-7b9a63482159.png)
By changing the order of controls checkedImage and iconImageBorder in the MenuItemTemplate, the problem is gone:
![after](https://user-images.githubusercontent.com/9028723/80793570-c9315f00-8b97-11ea-949c-21b11043d884.png)

**Comment by batzen** [comment]
Will have a look during the weekend.
