### ISSUE TITLE
Fluent Combox converter doesn't work on SelectedItem

### ISSUE THREAD

**Issue by Drexel2k** [fluentribbon/Fluent.Ribbon#797]
Hello,

I have an WPF/MVVM app and and a Fluent ComboBox which is filled by enum values. I use the DescriptionAttribute for display text and use a converter on the UI to read the texts:

`
<fluent:ComboBox Grid.Row="0" Grid.Column="1" VerticalAlignment="Bottom"  ItemsSource="{Binding UploadStatuses}" SelectedItem="{Binding RemoveUploadStatus}" Width="150">
                        <fluent:ComboBox.ItemTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Converter={local:EnumConverter}}"/>
                            </DataTemplate>
                        </fluent:ComboBox.ItemTemplate>
                    </fluent:ComboBox>
`
When I click on the Combox and all values are listed, this works fine, but for the SelectedItem it doesn't work, the control is showing the enum value text and not the description text.
With "normal" comboboxes this works totally fine..

Please see a working example in the archvie:
[WpfApp1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4603361/WpfApp1.zip)

Is this an issue or am I doing anything wrong?

Kind regards and thank you in advance for your help!
Matthias

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10.0.18363.778__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
You have to set IsEditable to false on the ComboBox as the default value is true for the ribbon ComboBox. I don't know why the original devs of Fluent.Ribbon decided to choose a different default value for that.

**Comment by Drexel2k** [comment]
Ah ok that was easy. :) Now it works and it makes sense that for editing the real value is shown. I noticed that the box is editable and wanted to change it, but I haven't done it yet.... Thank you die your support!

**Comment by batzen** [comment]
You are welcome 👍
