### ISSUE TITLE
Slow resize

### ISSUE THREAD

**Issue by kalatchev** [fluentribbon/Fluent.Ribbon#799]
**Resize of Ribbon window is slow and not very responsive**

I am not sure if this issue is related to Ribbon or other underlaying library. Anyway, I found that there is a big difference in resposivnes in three different frameworks, and Fluent.Ribbon has a slowest responce time of a resize action. Here is the animated gifs with my experiments. 

1. Syncfusion Ribbon (and other their controls);

![FR-Syncfusion](https://user-images.githubusercontent.com/10154711/82003828-0999de00-966a-11ea-8df8-21c22d728859.gif)

2. MahApps.Metro

![FR-MahApp Metro](https://user-images.githubusercontent.com/10154711/82004093-bd02d280-966a-11ea-8ef6-dc755f0c9f7b.gif)

3. Fluent.Ribbon

![FR-Fluent Ribbon2](https://user-images.githubusercontent.com/10154711/82004542-d8221200-966b-11ea-8439-c4071e7a64ed.gif)

---

So, it is a kind of defect? Or I do something wrong? Is it possible to speed it up somehow? One more thing - I think v6.x was faster in this particular aspect.

P.S. However, project is awesome!

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
Which version of MahApps.Metro are you using?
Any chance you could provide those three applications?
Does this also happen with the latest showcase application of Fluent.Ribbon on your machine?

**Comment by kalatchev** [comment]
Hi @batzen , thanks for responce. 
At you questions: 

- MahApps in the screenshots above is **1.6.5** (latest release).
 - Yes, I can give you the source code for apps, but I will need some time to prepare them for you. Meanwhile, **you can get running version of first application from the MS Store** (it's free) - https://www.microsoft.com/store/productId/9N8XS2CTKVXM . Tell me if it doesn't work for you, as I published it only for Bulgarian market.
 - Yes, **showcase app has similar behaviour** as my own app on my computer. My maschine is i7 (6th gen), DDR4 (16GB) and GeForce 960M video card. Not the fastest laptop, but above mean user's enviroinment. Anyway, all the screenshots are taken at same hardware and OS, simultaneously running.

**IMPORTANT**: Righ now, I compared it with older version of my app (same UI), wich is built **with Fluent.Ribbon v6.1.0 and it's much faster** (same as Syncfusion). This give us a clue, that mentioned slowness appeared beteween v6 and v7. I hope that helps.

**Comment by batzen** [comment]
@kalatchev Can't download your app.
The thing causing the slowdown should be the glow window behavior, which got added in version 7.
You could try to set `GlowBrush` to `null` to verify that. That way to glow window behavior should be disabled.
This does, of course, not really solve the issue.
As long as i am unable to reproduce the issue in some way it's very difficult to find out which part of the glow window is causing this slowdown.

**Comment by batzen** [comment]
Maybe you could run your app with an attached profiler to find out which part of the code is causing the slowdown.

**Comment by batzen** [comment]
Just did some tests and setting the glow brush to null is currently not a workaround.
I found a way to at least have bad performance on my machine, not as bad as in your videos, but still bad.

**Comment by batzen** [comment]
As this issue is caused by code from `ControlzEx` i created a new issue there.

**Comment by kalatchev** [comment]
Thanks, @batzen.  

Setting 
```XAML
<Fluent:RibbonWindow x:Class="MainWindow"
   ...
   GlowBrush="{x:Null}">
</Fluent:RibbonWindow>
```
solves the problem! I can't say why, but obviously ```GlowBrush``` somehow causes mentioned slowness.

Thanks again for the tip!

**Comment by kalatchev** [comment]
Just a detail - I think I have some problems with a driver of my video card. It may be the reason that in my case slowness is much worst that in ussual case.

**Comment by batzen** [comment]
> Just a detail - I think I have some problems with a driver of my video card. It may be the reason that in my case slowness is much worst that in ussual case.

That really seems to be the case here.
As you said setting `GlowBrush` to `null` solved your issue.
The main regular performance bottleneck caused by the glow windows is setting/updating their window positions. In the version of ControlzEx you are using the windows positions were still updated because we forgot to if case those.
This means your issue is caused by the rendering of the half transparent glows around the window which happens through the GPU.

**Comment by kalatchev** [comment]
Thanks @batzen for your efforts.
