### ISSUE TITLE
Non-Client Border is drawn in a color that makes it invisible in certain conditions

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#800]
When a window is styled, the non-client border has a semi-transparent shading based on the apps main color (in our case, blue). When two windows of the same app are overlapped, the border becomes invisible (because it is blue on blue, as seen on the screenshot)
![image](https://user-images.githubusercontent.com/22751987/82045074-bdbd5800-96ae-11ea-80bd-7251cc3cb9f5.png)

Is it possible to change the border to gray(ish) or add a gray component to it, so it will be visible when overlapping a sibling window.
---
### Environment
- Fluent.Ribbon v7.1.0, ControlzEx v4.2.2

**Comment by batzen** [comment]
You can use whatever color you like by using `GlowBrush` and `NonActiveGlowBrush` on `RibbonWindow`. ;-)

**Comment by atlastodor** [comment]
Thanks. That did the trick. 

For those who may want to play with the border, the following properties may be of interest:
- BorderBrush
- NonActiveBorderBrush
- GlowBrush
- NonActiveGlowBrush


similar
