### ISSUE TITLE
How to hide RibbonTabItem whithout content?

### ISSUE THREAD

**Issue by jonny-xhl** [fluentribbon/Fluent.Ribbon#801]
## My Code
```.xml
<Fluent:Ribbon Grid.Row="0" AutomaticStateManagement="True"
                       x:Name="ribbon">
            <Fluent:Ribbon.QuickAccessItems>
                <Fluent:QuickAccessMenuItem Target="{Binding ElementName=BtnSecManager}"/>
                <Fluent:QuickAccessMenuItem Target="{Binding ElementName=BtnModifyPassword}"/>
            </Fluent:Ribbon.QuickAccessItems>
            <Fluent:RibbonTabItem Header="Home"  ReduceOrder="(P),(P),(P),(P),(P)">
            </Fluent:RibbonTabItem>
</Fluent:Ribbon>
```
## The Reult
How to hide or not show this circle space?
![image](https://user-images.githubusercontent.com/29520329/82066291-c7bc7680-9701-11ea-9790-4ecabc5a4139.png)

**Comment by batzen** [comment]
I don't understand what you are trying to achieve.
You could set the visibility of the tab to collapsed to fully hide it.
Only hiding the content area is only possible by setting IsMinimized to true on the ribbon itself.

**Comment by jonny-xhl** [comment]
Setting  sMinimized to true on the ribbon itself not my achieve result.

I hope the RibbonTabItem have button can show this  area,but have't botton don't show this  area!

**Comment by batzen** [comment]
Then there is currently no built-in way to achieve what you want.
What's your use case for this? Why do you want to add an empty tab and hide it's content?

**Comment by jonny-xhl** [comment]
I see，thks! @batzen
