### ISSUE TITLE
Ribbon Window's Icon Not Centered

### ISSUE THREAD

**Issue by kalatchev** [fluentribbon/Fluent.Ribbon#804]
**When custom height is set, icon is not vertically centered.**

I found, that when I use custom height of a window title, icon is is not vertically centered (as on screenshot bellow). Here is my code:

```XAML
<Fluent:RibbonWindow x:Class="WindowLanguage"
        ... 
        xmlns:Fluent="urn:fluent-ribbon"
        Title="Language"
        TitleBackground="{DynamicResource PrimaryBrush}" TitleForeground="White"
        TitleBarHeight="25"
        ResizeMode="NoResize"
        ShowInTaskbar="False"
        WindowStartupLocation="CenterScreen" 
        Background="White" 
        Icon="pack://application:,,,/iLabCourier;component/Images/iLabCourier.ico">

...

</Fluent:RibbonWindow>
```

![image](https://user-images.githubusercontent.com/10154711/82357386-b4fdb680-9a0d-11ea-9bb6-bd5ae2f5ad37.png)

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Framework __8.8__

**Comment by batzen** [comment]
That's intentional.
I changed this back and forth a few times in the past.
Will add a new property or some other way to enable everyone to control this from the outside.

**Comment by kalatchev** [comment]
Thanks @batzen . 
In cuurent version, what is best way to center?

**Comment by batzen** [comment]
In the current version the best way would be to somehow get `PART_Icon` from the template of `RibbonWindow` and modify the `VerticalAlignment`.

**Comment by kalatchev** [comment]
Thanks for info @batzen
