### ISSUE TITLE
How to change WindowCommands(Minimize,Close,Shrink window buttons) color?

### ISSUE THREAD

**Issue by zboyanov** [fluentribbon/Fluent.Ribbon#805]
How can I change the color of the top bar buttons?
 SolidColorBrush x:Key="Fluent.Ribbon.Brushes.WindowCommands.CloseButton.Foreground" Color="White" 
I'm trying that way but it's not working.

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows 10
- .NET Core 3.1

**Comment by batzen** [comment]
It doesn't work because that resource does not exist.
The available brushes for the window commands are:
```
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Foreground
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Background
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.MouseOver.Background
Fluent.Ribbon.Brushes.WindowCommands.CaptionButton.Pressed.Background
Fluent.Ribbon.Brushes.WindowCommands.CloseButton.MouseOver.Background 
Fluent.Ribbon.Brushes.WindowCommands.CloseButton.Pressed.Background
```

Does that solve your issue?

**Comment by zboyanov** [comment]
Yes, thank you for the fast response.
