### ISSUE TITLE
How to add user name next to command buttons?

### ISSUE THREAD

**Issue by juniorRetard** [fluentribbon/Fluent.Ribbon#806]
Is it possible to add user name that's logged in, just like in word next to the command buttons?
If it is can I get a hint :)
---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Core __3.1__

**Comment by batzen** [comment]
You can add any item you want to `RibbonWindow.WindowCommands`.
Items added there appear on the left side of the window buttons.
Or you can add any item to `Ribbon.ToolBarItems`.
Items added there appear on the right side of the ribbons minimize button.

**Comment by juniorRetard** [comment]
Can you please write an example for RibbonWindow.WindowCommands?
