### ISSUE TITLE
GroupBox Separator Color Change?

### ISSUE THREAD

**Issue by juniorRetard** [fluentribbon/Fluent.Ribbon#807]
How can I change the Separator Color between the RibbonGroupBox and the bottom border of the [picture ](https://ibb.co/8BK0t5w)?

---
### Environment

Fluent.Ribbon v7.1.0
Windows 10
.NET Core 3.1

**Comment by juniorRetard** [comment]
Image was deleted so I uploaded a new one [here](https://ibb.co/2v95syJ).

**Comment by batzen** [comment]
You have to overwrite the following resources:
```
        <SolidColorBrush x:Key="Fluent.Ribbon.Brushes.GroupSeparator.Background" Color="Red" />
        <SolidColorBrush x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush" Color="Red" />
```
