### ISSUE TITLE
[Breaking change] Theming changed once more

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#811]
`ThemeManager` was moved from `Fluent.Ribbon` to `ControlzEx`.
This was done to be able to share one common `ThemeManager` between `Fluent.Ribbon` and `MahApps.Metro`.

This breaking change will be part of version 8.0.

**Comment by pschimmel** [comment]
Hi! 
Does that influence the way the ThemeManager is used?
If I upgrade Fluent from version 7.0.1 to 8.0.0, will I have to change my code?

**Comment by batzen** [comment]
You will have to change your code as ThemeManger is no longer a static class. So you have to use ThemeManger.Current in 8.0.

**Comment by pschimmel** [comment]
Hi! 

To do some testing, I updated our application to version 8.0.0 today, but I did not manage to load the theme file. Before (version 7.0.1), Before, I loaded the theme at runtime from a resource file and switched to it:

```csharp    
ThemeManager.AddTheme(new Uri("pack://application:,,,/RibbonStuff;component/RibbonTheme.xaml"));
ThemeManager.ChangeTheme(Application.Current, "MyTheme");
```  

In the new Manager the AddTheme overload that takes an Uri is not there anymore. What is the preferred way to accomplish the same?

**Comment by batzen** [comment]
That depends on what's in your theme and what you want to modify. Is it a complete theme, or did you use it to add additional things?

**Comment by pschimmel** [comment]
It is supposed to be an complete, independent theme, not containing anything else.
I basically took the file Theme.Template.xaml, renamed and modified it manually to match out color scheme.

**Comment by batzen** [comment]
Then it's quite easy and the following code should be enough:
```csharp
var source = new Uri("pack://application:,,,/RibbonStuff;component/RibbonTheme.xaml");
var newTheme = new Theme(new LibraryTheme(source, null));
ThemeManager.Current.ChangeTheme(Application.Current, newTheme);
```

**Comment by pschimmel** [comment]
Thank you for the quick response.

When using your code snippet, I first got an exception in RuntimeThemeGenerator, line 100.

In the ControlzEx source code, I saw that the problem is that the BaseColor is not set and I added the following lines to my RibbonTheme.xaml file:

```xml
<system:String x:Key="Theme.BaseColorScheme">Light</system:String>
<system:String x:Key="Theme.ColorScheme">Blue</system:String>
<system:String x:Key="Theme.AlternativeColorScheme">Amber</system:String>
```
I had no idea what to put there, so I just picked names from the built-in themes.

Then there is no exception anymore and Ribbon resources are added to the resources of my application. However the resources defined in my theme are not used. 

To test this, I defined the Fluent.Ribbon.Brushes.Button.MouseOver.Background brush with a green color, but the value contained in the resource dictionary is #330078D7

**Comment by batzen** [comment]
At which level do you load the regular ribbon resources? If it's on the window level you have to change the theme there and not on the application level, which i suggested.
Could you also check the return value of ChangeTheme? It should return your newly applied theme on success.
If your issue persists a repro would help.

**Comment by pschimmel** [comment]
I'm setting the resources only once, on the application level.
The theme returned by ChangeTheme also contains the wrong colors.

**Comment by batzen** [comment]
Could you create a small repro then?

**Comment by pschimmel** [comment]
Here's the repo:

[FluentTest_Theming.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5003895/FluentTest_Theming.zip)

Just start the application it will show two message boxes containing one sample color.
After creating the theme, the sample color I added is OK.
But after changing the theme, that color is not used.

**Comment by batzen** [comment]
Ah, ok.
That's because you have to use `var newTheme = new Theme(new LibraryTheme(source, RibbonLibraryThemeProvider.DefaultInstance));` passing `RibbonLibraryThemeProvider.DefaultInstance` here is important as otherwise the `ThemeManager` thinks your theme is for a different component and provides a theme that matches `Theme.BaseColorScheme` and `Theme.ColorScheme` from `RibbonLibraryThemeProvider.DefaultInstance`.
I forgot to mention that when posting my sample code.
Beside that, your theme is not complete and is missing things like `WhiteColor`, `BlackColor` etc. ;-)
