### ISSUE TITLE
Make DropDownButton checkable (has IsChecked property)

### ISSUE THREAD

**Issue by tondo8881** [fluentribbon/Fluent.Ribbon#814]
Use Case:
I have Checkable items in menu. I want DropDownButton to have IsChecked style when some of the items in the menu are Checked.

**Comment by batzen** [comment]
I don't think that's something i will add as it would require the control to keep track of all child menu items and their state. In addition to that i am not sure what the use case for this would be.

**Comment by tondo8881** [comment]
Sorry for the wrong description. It would be pretty enough to just add IsChecked property. I would handle the value of IsChecked property on my own in the code of my app. I just described this use case which is typical for me.
Once again, sorry for the missunderstanding and thank you! You are doing a great job.

**Comment by batzen** [comment]
You are welcome. 👍
I don't think it's necessary that I add such a property. You could use your own attached property. That way you can add every property you want. 😉

**Comment by tondo8881** [comment]
Ok, thanks for your advice! :)
