### ISSUE TITLE
How to use ttf font in Fluent Robbion?

### ISSUE THREAD

**Issue by meisongdai** [fluentribbon/Fluent.Ribbon#817]
**Place your issue description here.**
How to use ttf font in Fluent Robbion?
**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
There is nothing special in Fluent.Ribbon about how it handles fonts. So you should be able to use the default WPF way for that.
Did you encounter any issues while trying to use custom fonts in Fluent.Ribbon?
