### ISSUE TITLE
Is there a way to disable default tooltip when RibbonGroupBox is disabled?

### ISSUE THREAD

**Issue by tondo8881** [fluentribbon/Fluent.Ribbon#819]
When hovering on disabled RibbonGroupBox (IsEnabled == False), tooltip with the name of selected RibbonTabItem shows up. The behaviour is the same as hovering on some empty space in ribbon. Is there a way to prevent this behaviour?

**Comment by batzen** [comment]
I completely removed this behavior in 84a37f737f6d1284fb9f45c361a80ebf9d0a6295 which is part of the upcoming version 8.0 release.
