### ISSUE TITLE
NET45 lib folder doesn't contain Microsoft.Windows.Shell

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#82]
Is this a bug or should I do something else to fix this?

**Comment by batzen** [comment]
It's simply not needed when targeting .NET 4.5 as the classes (WindowChrome etc.) we use from there when targeting .NET 4.0 are now part of .NET 4.5.

**Comment by batzen** [comment]
#if NET40
    using Microsoft.Windows.Shell;
#else
    using System.Windows.Shell;
#endif

**Comment by GeertvanHorrik** [comment]
Interesting. I had a customer referencing Orchestra (which references 4.0 version) in a NET45 app. We have now manually referenced the NET40 one, so that works. Thanks for the info.
