### ISSUE TITLE
RibbonTitleBarControlTemplate grid actual size always zero

### ISSUE THREAD

**Issue by maomiaoyan** [fluentribbon/Fluent.Ribbon#820]
the grid in RibbonTitleBarControlTemplate actual size always zero，the window title cant set to align left

### Environment

- Fluent.Ribbon __v8.0.0
- Windows __10__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
The layout of the window title is centered intentionally to be consistent with office.
What's your use case for making it left aligned?

**Comment by maomiaoyan** [comment]
I want to set it to left like normal application,look the explorer,the title is on left side,you should let user to select it alignment for more customize

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Bastian Schmidt<mailto:notifications@github.com>
发送时间: 2020年7月30日 23:29
收件人: fluentribbon/Fluent.Ribbon<mailto:Fluent.Ribbon@noreply.github.com>
抄送: mao.miaoyan<mailto:mao.miaoyan@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [fluentribbon/Fluent.Ribbon] RibbonTitleBarControlTemplate grid actual size always zero (#820)


The layout of the window title is centered intentionally to be consistent with office.
What's your use case for making it left aligned?

―

**Comment by batzen** [comment]
I edited my answer after the github mail went out to you. Please have a look at that. I forgot that it's already possible to change the alignment.
