### ISSUE TITLE
Different visual of menu item and submenu item

### ISSUE THREAD

**Issue by tondo8881** [fluentribbon/Fluent.Ribbon#821]
In top level menu item, there is no separator between space for icon and text. In submenu item, there is a separator.

![submenu](https://user-images.githubusercontent.com/32441007/86096793-09d42880-bab4-11ea-97df-3ba0afd751ee.png)

**Comment by batzen** [comment]
Will remove the separator from submenus as this will be consistent with other menus (in windows, office, browsers etc.).
