### ISSUE TITLE
Quick access Toolbar don't work 

### ISSUE THREAD

**Issue by richardnogueira** [fluentribbon/Fluent.Ribbon#824]
Following the example given in documentations, I had tryed to implement quick access toolbar, but unsucefully. The bar only appears on bottom of Ribbon. In the above nothing happen. 

<Window x:Class="Regia.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:Fluent="urn:fluent-ribbon"
        xmlns:local="clr-namespace:Regia"
        mc:Ignorable="d"
        Title="Regia" WindowStartupLocation="CenterScreen" Height="900" Width="1600">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
            <RowDefinition Height="25" />
        </Grid.RowDefinitions>
        
        <Fluent:Ribbon Grid.Row="0">

            <Fluent:Ribbon.QuickAccessItems>
                <Fluent:QuickAccessMenuItem IsChecked="True">

                    <Fluent:Button Header="Teste" Size="Small" Icon="/Resources/Imagens/salvar.png"/>

                </Fluent:QuickAccessMenuItem>

                <Fluent:QuickAccessMenuItem IsChecked="True" Target="{Binding ElementName=butNovoProjeto}"/>
            </Fluent:Ribbon.QuickAccessItems>
---
### Environment

- Fluent.Ribbon __v8.0.0__
- Windows __10__
- .NET Framework __4.7.2__

![image](https://user-images.githubusercontent.com/24223667/87474505-937a0f00-c5f9-11ea-98a2-cffc4321a280.png)

**Comment by batzen** [comment]
Could you provide a full repro project for this issue?

**Comment by richardnogueira** [comment]
Yes I Can.
[TesteRibbon.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5012224/TesteRibbon.zip)

**Comment by batzen** [comment]
That's by design as you are using a regular window instead of a `RibbonWindow`.
When you don't use a `RibbonWindow` the quick access toolbar is not present.
If you don't want to use `RibbonWindow` the only way to show a quick access toolbar above the ribbon is to set `TitleBar` on the `Ribbon` to some `RibbonTitleBar`.
