### ISSUE TITLE
CLS compliance

### ISSUE THREAD

**Issue by YetAnotherCodeMaker** [fluentribbon/Fluent.Ribbon#825]
Why removing CLS compliance? Isn't it a breaking change?

---
### Environment

- Fluent.Ribbon 8.0.0

**Comment by batzen** [comment]
The major version was increased.
Did this break anything for you?
Being CLS compliant in a WPF library is of no use as the only runtime is .NET / .NET core on Windows.

**Comment by YetAnotherCodeMaker** [comment]
I’m rather strict when I’m coding, and that’s include writing CLS compliant code. Until now, that wasn’t a problem with Fluent Ribbon and I was surprised by this change. Altogether, adding an attribute to all of my Window classes is not a big issue (just a little disturbing)…

**Comment by batzen** [comment]
Will have a look at why i removed it.

**Comment by batzen** [comment]
I think i removed it because ControlzEx is not CLS compliant.
Will try to get ControlzEx CLS compliant and the update Fluent.Ribbon to be CLS compliant.
