### ISSUE TITLE
InRibbonGallery resizing issue when changing `Visibility`

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#834]
I tried to integrate the latest version of your fantastic library in our application by upgrading from version 7.0.1 to 8.0.0. 

I'm very sorry that I have not tested that scenario earlier (before release of 8.0.0), but I'm afraid, I have found another issue with the resizing of InRibbonGalleries.

I can't publish our application, so I tried to create a simple sample project that uses the ribbon and the galleries roughly in the same way.

I created a video explaining the problem:
[AnotherGalleryTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4997179/AnotherGalleryTest.zip)

![AnotherGalleryTest](https://user-images.githubusercontent.com/9028723/88850235-5c0b8500-d1eb-11ea-9ad5-8f95eb3b85d2.gif)

I've created two galleries in one group. In both galleries I have set MinItemsInRow=1 and MaxItemsInRow=3.
I also added a ToggleButton to the ribbon, with which I can hide the first gallery.

The first thing that you see is that when one gallery is hidden, the other gallery does not take advantage of the available space. It width just stays the same.

The second issue is when one gallery is hidden and I resize my window, the resizing of the visible window is correct. But when the other gallery is made visible again, it will refuse to resize which breaks the layout. 

Here is the test project that I used:

[FluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/4997254/FluentTest.zip)

Thanks a lot for your work on the library!

---
### Environment

- Fluent.Ribbon __v8.0.0__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
That looks like another caching issue. Will try to have a look during the weekend.

**Comment by pschimmel** [comment]
Hi batzen,
I saw that you fixed the issue. 
By playing around with the same test project that I attached earlier, I saw that the main issues are gone. however the gallery resizing still seem to behave strange:

![NewGalleryTest](https://user-images.githubusercontent.com/9028723/89111292-519ff400-d454-11ea-922e-8e4dee2fa949.gif)

[NewGalleryTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5011354/NewGalleryTest.zip)

In the video you see that I reduced the size of the main window until both galleries reduce to two columns -> OK
Without changing the size of the window, I make one gallery invisible. Then the other gallery is enlarged -> Great
After making the first gallery visible again, it has two columns. The other gallery still shows 3 columns. There is enough space for that, so I assume this is OK,
But the problem is that there is no way to show the first gallery with more than two columns.

Can you reopen the issue, or should I write a new one?

**Comment by batzen** [comment]
@pschimmel I hope those changes finally fix your issues. Would be nice if you could test again and report back your results. :-)

**Comment by pschimmel** [comment]
Hi batzen!
I just tested with the current sources and indeed the resizing of the InRibbonGallery has significantly improved.
That's awesome. Thank you very much.
I'm sorry for poking you again, but there is still an issue that I found while testing:

![RibbonResizingBehavior](https://user-images.githubusercontent.com/9028723/90558746-dc932500-e19c-11ea-968c-b27d83beb7d2.gif)

When I reduce the width of window and make one of the hidden galleries  visible, the remaining controls in Group 3 won't resize anymore.

Here's the sample project:
[GalleryTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5092525/GalleryTest.zip)
I build the Fluent.dll from the sources.

**Comment by batzen** [comment]
And one more caching issue... 😭

**Comment by batzen** [comment]
@pschimmel Could you give it another try? I hope i fixed all known issues this time.

**Comment by pschimmel** [comment]
@batzen 
That's really great. Thank you for working so hard on the problem. I have the impression that it has improved much since the last time I tested it.
I tried with my little sample application and still found another issue. Presumably another caching thing?

Please take a look at the following video:

![FluentGalleryAnotherTry](https://user-images.githubusercontent.com/9028723/93688869-93026680-fac9-11ea-8767-528a09c4a198.gif)

I used the same sample application as before. The first thing that I realized is that after making all galleries visible, the first (previously hidden) gallery of the second group shows with one column. After hiding and unhiding the same gallery again, it appears as  DropDown-Button although the width of the window has not changed.

When I make the window wider, that gallery will be displayed again as one-column gallery. So not a big deal so far, but the gallery will not resize anymore until I reduce the width of the window significantly and then make it larger again.

**Comment by batzen** [comment]
@pschimmel That should also be fixed now.

**Comment by pschimmel** [comment]
@batzen I tested the new version. Thumbs up. I found no issues in resizing of the galleries anymore. Thank you so much.

However, after testing for a while some odd thing happened. Here's the short version:

![FluentGalleryButtonHighlighing](https://user-images.githubusercontent.com/9028723/93713914-479a9780-fb5f-11ea-86bc-293f673a07dd.gif)

While dragging the right border of the the window, mouse over highlighting appears in the 3rd group. Those are just normal buttons, no toggle buttons. After releasing the mouse button, the highlighting is gone.

This could perfectly be not related to the original problem. Should I open a new issue report?

**Comment by batzen** [comment]
@pschimmel That's no a Fluent.Ribbon issue, but an issue with the GlowWindowBehavior from ControlzEx. Could you create an issue there? Then i can track and fix it there. The new, experimental, GlowWindowBehavior does not show that issue, but it's not finished yet because i had no real reason, aside from performance, to invest more time for that. Your issue clearly shows that i need to finish the work on that one.
