### ISSUE TITLE
Pull Request Suggestion

### ISSUE THREAD

**Issue by abdelkarim** [fluentribbon/Fluent.Ribbon#84]
I am working right now on a pull request to reduce the visual tree of of the `RibbonTabItem` control template.

I will get rid off the various grids and rectangles and replace them with a single element that will achieve the same result: here is my initial [Commit](https://github.com/abdelkarim/Fluent.Ribbon/commit/12e4ef9448310c0c5c50da5058e356a9d0d72612)

Will my PR be accepted and continue or should I drop the idea ?

my result:
![image](https://cloud.githubusercontent.com/assets/1153480/6771535/138e9ba2-d0e1-11e4-9726-ee0aae2c61f7.png)

current:
![image](https://cloud.githubusercontent.com/assets/1153480/6771538/20995be8-d0e1-11e4-8073-48e584d75d8d.png)

**Comment by batzen** [comment]
Looks interesting. Could make it easier to maintain styles across different themes.

But I have to ask:
Is it worth the effort? What's the difference in terms of performance and memory consumption? In know those things are difficult to measure...

If you manage to take all the various triggers into account this looks good to me.
Will have a closer look at your fork sometime this week.

A few things about your code:
- please add spaces to calculations "2 * 2" instead of "2*2"
- better names for variables "p7" does not tell much
- the result of "(isFilled ? 0 : borderThickness)" could be cached
- the large code blocks in GetBorderGeometry could be refactored to two methods
- please always use "this." when accessing members

**Comment by abdelkarim** [comment]
If it wasn't worth the effort I wouldn't have bothered writing it in the first place. For me the [Grid](http://referencesource.microsoft.com/#PresentationFramework/Framework/System/Windows/Controls/Grid.cs,f9ce1d6be154348a) is among the complex panels in WPF. I try to avoid it as much as possible, unless the return of investment is obvious.

* so the gain in performance is obvious, if you analyze the code that gets executed in both cases, consider as well how many measure/arrange/render passes during the lifetime of an application.
* simple templates to maintain.
* less elements in the template means less memory

I will handle the various trigger cases, I just needed an Ok to keep going. Thanks by the way :)

I will take your notes into consideration, except for the p variable names, those are the points needed to draw our border, I start at p0 the bottom left corner all the way to the bottom right p7: p0 curve to p1 line to p2 curve to p3.....

I will probably add a comment to clarify their meanings.

**Comment by abdelkarim** [comment]
I guess that I am mostly done, I will later document my code and review it more.

Please take a look at my fork in regards to what I suggested here. The only issue I am having is summarized in the below picture. The issue occur after re-sizing the window. Initially they're displayed fine.
![image](https://cloud.githubusercontent.com/assets/1153480/6874692/aa9b1d78-d4b9-11e4-89a5-ffa141080718.png)

Drilling down in the issue I found a measure bug there, probably in **RibbonTabItem.MeasureOverride**. For example for KeyTips tab, the **ActualWidth** is ***75***, where the internal **Grid** actual width is ***77***.

Once this PR is integrated, I have another PR in mind that I will discuss with you. The idea came after reviewing where the above bug is coming from.

should I send you PR and have the discussion there, or are you fine here ?

**Comment by abdelkarim** [comment]
First, don't try to fix the above issue, because I have prepared another Pull Request that will take care of it.

### Motivation
During my work on this suggestion Pull Request, I didn't understand the reason for the following:
![image](https://cloud.githubusercontent.com/assets/1153480/6987188/8e5a7d56-da3c-11e4-98b9-3d21243f8294.png)

I tried to optimize it directly by taking rid off all of this and just using a `ContentPresenter` with `HorizontalAlignment="Center"`, to my surprise what I did broke the end result.

What I understood is that everything as it is in the picture is needed to correctly position the header. I believe it is wrong for two things:
* This is not how items are centered in WPF, `HorizontalAlignment="Center"` should do the job.
* Users might get confused when they try to customize the look. I was.

## Solution
The solution I will discuss is up and running just fine, I will push it in a Pull Request right after this #89 is merged.

![image](https://cloud.githubusercontent.com/assets/1153480/6988631/3aea0538-da4b-11e4-8542-8bcd5364a5e2.png)

I took rid off the `RibbonTabItem.MeasureOverride` and the **PART_ContentContainer** dependency, they're no longer needed. The idea is to manipulate the `Padding` of the `RibbonTabItem` and the available space.
I mainly refactored the `RibbonTabsContainer` to:
1. Reduce the Padding value during re-size, we start with the value 17 on both the left and right, after this step we end at 5. 12 is for the default indent.
2. After that we start reducing the width of the control, by width I mean the available space reserved for the control.

For contextual tabs, we have three steps in some cases, because some tabs might be extended to accommodate the length of their enclosing Contextual Group, we reduce it during the second step above.

After you take a look at the final implementation, you will notice that what we have now is similar to what was there.

I talked briefly about my solution, it is already up and fully implemented in the [TabsContainerRewrite](https://github.com/abdelkarim/Fluent.Ribbon/tree/TabsContainerRewrite) branch. It is based on the changes in #89 .

Please take a look and give me some feedback before I push my changes in a Pull Request.

**Comment by abdelkarim** [comment]
@batzen you didn't gave an answer to my last comment here ?

**Comment by batzen** [comment]
As much as i appreciate your effort I have to say some things. Please don't get me wrong, please don't take it personally. Nothing I say is meant to sound mean. My answer is a mix of comments to the PR you made and your TabsContainerRewrite changes.

- You are trying to fix performance problems with your PR which never were problems (premature optimization).

- The way you did this in your PR is by doing this for one theme, maintaining multiple themes is difficult and time consuming and the more they diverge the more time it takes, by introducing your new control they just diverge even more and now we not only have to take care of the xaml files but also a separate class/control which is only there for one theme.

- Now that you have taken the effort to do all that, I have a hard time rejecting your PR and I am still unsure if I should accept it. But please separate the changes into separate branches (so I can accept/reject them separately) and I need some time to check all the changes you made in your PR and in your TabsContainerRewrite branch. I will try to comment everything that does look problematic.

- Taking on your argument "Users might get confused when they try to customize the look. I was." try to apply that argument to the changes in the PR you made and you might get what i mean with my above comments.

- I don't say the current code in this project is perfect, in fact it's often far from perfect, but it has been working for years now. And yes I hate the argument "It has been working for years" but it's a sad fact.

- Please read the "Contributing -> Settings that should be used" section of Readme.md. I will extend that section to mention the ReSharper-Settings used in case someone does not have ReSharper.

**Comment by abdelkarim** [comment]
Don't worry @batzen nothing personal :)

I see that you've now mixed feelings about my Pull Requests, I believe that what cause this is you expected more from my Pull Request. I didn't pay much attention to what you said in the first comment "Could make it easier to maintain styles across different themes." --> my PR goals were to optimize the shape of the Office 2010 theme, and to get to know your repository better and contribute on a regular basis.

Why I asked first ? to avoid this situation we are right in. I previously sent a [PR](https://github.com/icsharpcode/SharpDevelop/pull/564) to the SharpDevelop project with something that I felt will be highly welcomed. I will let you analyze the thread submitted on Sept 16, reviewed and close on Dec 29. during that time frame a few PRs were considered and merged and not mine. --> I found it not worth my time. so I looked for other projects to contribute to, and found you and another one.

Is it premature ? if you were paying for this, I would have agreed with you, your return of investment is ZERO. From a developer side, I myself will see this as a welcome change because it is making something good, better. I reduced the Visual Tree from 30 element to just 13.

Why is it just for the Office 2010 theme ? The tab item for this theme needed corner radius in 4 places, and inner and an outer border, so I decided to optimize how it is implemented. For the other themes, I wanted to review theme separately. We can use my element in other themes, just set **CornerRadius** to 0 and never render the **InnerBorder** and you're good to go. As I said previously this is for another Pull Request, Because I like to discuss things with you before committing to work.

I agree with you that maintaining multiple themes is difficult, and I am here to help as well. I believe this what open source is all about, community involvement.

Saying that my changes diverged the themes implementation is wrong. The themes as they're are diverged. I see it as a normal thing, because different themes have different UI requirements.

A final word, I didn't break anything, I improved what is existing. Whether you accept the PRs or reject them is up to you.

Thanks.

**Comment by abdelkarim** [comment]
One last thing to add, let's not look to the Ribbon as if it is the only element on the users screen. Improvements on our side will contribute to the improvements of user applications when developers decide to update.

In fact, the WPF team in the Connect (Live) Q&A sessions, demoed something similar to this, reducing the visual tree. You can check it [here](http://channel9.msdn.com/Events/Visual-Studio/Connect-Live/Visual-Studio-WPF-Team-What-we-are-up-to#time=27m10s) (The link will take you straight to the demo)

**Comment by batzen** [comment]
Of course improvements on our side contribute to improvements on the user side, but we still have to find a good mix, in this case, between maintainability and performance.

The thing the WPF team demoed was deferred content and as soon as we are able to use it here it will be used. There are many things in this library that would benefit (in terms of performance) from deferred loading.

I still have to take a look at your TabsContainerRewrite branch. Could you create a separate issue for that one? This thread already got quite lengthy.

**Comment by abdelkarim** [comment]
I have to say @batzen that you're rejecting me without solid arguments. That's my feeling, as if, it is working don't touch it and don't try to improve it at all. Now I think that I have wasted my time working on what I suggested.

The **TabsContainerRewrite** code is independent from the submitted Pull Request, though it contains the PR changes, because I branched from my local master. You can clone the repository and see what I did there, if you feel like merging it I will clean the previous PR code and send you a new Pull Request.

I really appreciate all the time you spent with me. Thanks.

**Comment by batzen** [comment]
Hi, i know it's been a while but I finally had the time to have a look at your changes for your TabsContainerRewrite.
It looks much cleaner than the current implementation and I would like to see the changes in a separate PR. I don't know if you still want to invest time for that...

**Comment by abdelkarim** [comment]
Hi, I will later, for now I am busy with work.

**Comment by batzen** [comment]
Nice to hear that you are still some kind of interested.
Good luck with your work.
