### ISSUE TITLE
NullReferenceException in PrePostDescendentsWalker on App Exit

### ISSUE THREAD

**Issue by korneliuscode** [fluentribbon/Fluent.Ribbon#841]
For my app I get a lot of crash reports from an exception 
> System.NullReferenceException: Object reference not set to an instance of an object.

```PrePostDescendentsWalker`1._VisitNode (DependencyObject d, Boolean visitedViaVisualTree)```

Please find the stack trace here.
[report.txt](https://github.com/fluentribbon/Fluent.Ribbon/files/5078602/report.txt)

Based on the events this happens on App Exit. 
I post this here as Fluent is in there as well

```
  at Fluent.Backstage.DestroyAdorner()
  at Fluent.Backstage.OnBackstageUnloaded(Object sender, RoutedEventArgs e)

```

Any ideas what this could be?

---
### Environment

- Fluent.Ribbon __v7.1.
- Windows 10.0.19041 (but happens on others as well)
- .NET Framework .Net Core 3.1

**Comment by batzen** [comment]
Are you doing anything special on application exit?
The code inside the method that throws the NRE might fail if:
- Application.Current is null
- Application.Current.Resources is null
