### ISSUE TITLE
Fluent.Ribbon.Brushes.Backstage.Background brush in a Dark mode possible issue

### ISSUE THREAD

**Issue by ceo1647** [fluentribbon/Fluent.Ribbon#843]
In [GeneratorParameters.json] https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Themes/GeneratorParameters.json )

in a **light** theme Fluent.Ribbon.Brushes.Backstage.Background is AccentColor; 
but in a **Dark** theme it's WhiteColor 

wondering is it mistake or it was made intentionally... because looks inconsistent.

light theme:
![image](https://user-images.githubusercontent.com/5163834/91459152-6165f900-e897-11ea-8faf-b72860ec1bf9.png)

dark theme:
![image](https://user-images.githubusercontent.com/5163834/91459064-498e7500-e897-11ea-80a5-5e61fb7c11da.png)

- Fluent.Ribbon v8.0.0
- Windows 10
- .NET Framework netcoreapp3.1

**Comment by batzen** [comment]
That's intentional as Office does the same when using the dark theme or did they change that in a newer version?

**Comment by GeertvanHorrik** [comment]
Here is a recent office thing:

![image](https://user-images.githubusercontent.com/1246444/91477979-72b30380-e89f-11ea-9fda-38ea4fb89a19.png)

**Comment by ceo1647** [comment]
yes...i should check office themes first. 
Thanks for the explanation, totally makes sense.
