### ISSUE TITLE
The QuickAccessToolBar alway show in 

### ISSUE THREAD

**Issue by GuangZhouDekang** [fluentribbon/Fluent.Ribbon#844]
Environment

- Fluent.Ribbon 7.1
- Windows  10
- .NET Framework 4.6.2

Where is the ribbon quick access toolbar setting file save in the compute.
my issue is whatever I set the QuckAccessToolBar alway stay below the ribbon menu.

How can I changed that?

**Comment by batzen** [comment]
It's saved in the isolated storage under `%LOCALAPPDATA%\IsolatedStorage`.
If the user changes the location of the QuickAccessToolbar during runtime it should be saved and restored on the next run.
If it stays at one location it might be that it's overwritten in the application itself.

**Comment by GuangZhouDekang** [comment]
Thanks.
