### ISSUE TITLE
QuickAccessToolBar issues in Colorful variant

### ISSUE THREAD

**Issue by kalatchev** [fluentribbon/Fluent.Ribbon#845]
**Background of items in QuickAccessToolBar is not changed when mouse is over them (Colorful theme variant). The dropdown button of QuickAccessToolBar is not visible when is shown bellow ribbon**

Light theme (correct behaviour):

<img src="https://user-images.githubusercontent.com/10154711/92139905-1c9f0c80-ee19-11ea-9676-347019f4af67.gif" width="500"/>

Light Colorful theme (**incorrect behaviour**):

<img src="https://user-images.githubusercontent.com/10154711/92140615-03e32680-ee1a-11ea-96e3-8007d1162d80.gif" width="500"/>

Light Colorful theme (**dropdown button is not visible**):

<img src="https://user-images.githubusercontent.com/10154711/92140882-5de3ec00-ee1a-11ea-8e00-09dce11e1beb.gif" width="500"/>

In version 7.1.0 it works, however background color change was pretty pale.

---
### Environment

- Fluent.Ribbon __8.0.0__
- Windows __10__
- .NET Framework __3.1 Core__

**Comment by kalatchev** [comment]
Hello,

I believe that the problem is in the background of the title bar. 

What I've found is that, when one uses Fluent.Ribbon and MahApps (which share the same theming), the MetroWindow and the RibbonWindow have different title bar colors. In the case of MetroWindow (MahAapps) it's the Accent color (``"MahApps.Colors.Accent": "#CCxxxxxx"``), on the other hand Fluent.Ribbon uses the AccentBaseColor (``"Fluent.Ribbon.Colors.AccentBaseColor": "#FFxxxxxx"``). I believe that the hover effect is to be achieved by using a color, darker then the current one (AccentBaseColor). Having in mind theming, I suggest transition of color from  Fluent.Ribbon.Colors.AccentColor80 to Fluent.Ribbon.Colors.AccentBaseColor. And, of course, RibbonWindow should use AccentColor80 as a title bar background in colorful themes. 

Another issue related to that one, is that if one uses both libraries together, particularly with the colorful theme of Fluent.Ribbon, and has child windows inherited from MetroWindow (MahApps), he will end up with windows that have different title bar colors. Recently I had such an issue and I fixed it just by setting MahApps's MetroWindow title bar background to the AccentBase (in my case I have generated my own custom color themes for both libraries with the same parameters).

As I can see, MS Office uses the same approach and deals with accent colors in that way.
<img src="https://user-images.githubusercontent.com/10154711/103439493-1fcecb80-4c46-11eb-8cd5-efb48cb9577a.png" width="500">

I hope that somehow helps :-)

**Comment by batzen** [comment]
Will change TitleBackground to AccentColor80 to be aligned with MahApps.Metro. Don't know why i never noticed this difference.

There is one change that would solve all these color issues: 
Switching from RGBA to pure RGB colors instead of using transparency and then fix all accent color usage to look good again.
But it would solve all issues caused by transparency/opacity used in the colors.
Will experiment a bit to see how much work this would require.

**Comment by kalatchev** [comment]
Thanks a lot, @batzen
