### ISSUE TITLE
Change Backstageitem width and color?

### ISSUE THREAD

**Issue by zboyanov** [fluentribbon/Fluent.Ribbon#846]
Hello,is it possible to change the white font with other color, and also decrease the width of the window?
![image](https://user-images.githubusercontent.com/47523601/92237556-38a9b900-eec0-11ea-9ff3-7c95c8dad2bc.png)

---
- Fluent.Ribbon __v7.1.0__
- Windows 10
- .NET Core__3.1__

**Comment by batzen** [comment]
You can change the foreground color by overwriting `Fluent.Ribbon.Brushes.BackstageTabItem.Header.Foreground`.
The width of the window is controlled by your code. Or did you mean the width of the backstage headers?

**Comment by zboyanov** [comment]
![image](https://user-images.githubusercontent.com/47523601/92439113-e06e0200-f1b2-11ea-94d8-9f467099e2d3.png)
I'm sorry i guess u didn't understand what I asked. I'm asking about this white background and white background width.

**Comment by batzen** [comment]
You can use `ItemsPanelMinWidth` on the `BackstageTabControl` to control the width of the left part.

**Comment by zboyanov** [comment]
I'm asking about the right part. How can I change the color and the width of it? Is it possible?

**Comment by batzen** [comment]
If you change the width of the left pane the width of the right pane automatically changes.
Wouldn't that work for you?
