### ISSUE TITLE
 tabitem click event

### ISSUE THREAD

**Issue by lsaejn** [fluentribbon/Fluent.Ribbon#847]
I get that SelectedTabChanged event is fired after tab has changed.
But how to catch tabitem click event(MouseLeftButtonDown)? I have to verify the data to decide whether to Change Tab. 
It's completely baffling to me.

**Comment by batzen** [comment]
Preventing the click does not prevent other ways to select the tab. In addition to a mouse click it can be a key tip, mouse wheel scrolling or other keyboard input.
The only reliable way to prevent tab selection is by disabling or hiding the tab.

**Comment by DaveInCaz** [comment]
Sounds like a case where a cancel-able "TabSelectionChanged" sort of event might be useful.

**Comment by lsaejn** [comment]
> Sounds like a case where a cancel-able "TabSelectionChanged" sort of event might be useful.

Yes, Sometimes, a dialog box contains selections will pop up when the user clicks a tabitem.  May be i needs a event TabSelectionChangedBefore, I'm still trying to find a solution. Thanks a lot!

**Comment by lsaejn** [comment]
> Preventing the click does not prevent other ways to select the tab. In addition to a mouse click it can be a key tip, mouse wheel scrolling or other keyboard input.
> The only reliable way to prevent tab selection is by disabling or hiding the tab.

Thank you for your reminding. I'll think about it. Maybe there are other ways to solve my problem.

**Comment by DaveInCaz** [comment]
@batzen just another thought... I wonder if adding a command to the tab would be a good approach? In my app I use an attached property to set a command on each tab. If the command cannot be executed, the tab is disabled. This might be a nice feature to eventually have built-in (though the AP works perfectly fine).

maybe this could work for you also.

```
 public class CommandAttachedProperties : DependencyObject
    {
        //////////////////////////////////////////////////////////////////////////////////

        /// <summary>
        ///  This attached property allows you to bind it to any ICommand, and then it
        ///  will set IsEnabled based on the executable status of the command. This is
        ///  useful to de/activate controls which don't take a command natively.
        /// </summary>

        public static readonly DependencyProperty IsEnabledCommandProperty =
            DependencyProperty.RegisterAttached("IsEnabledCommand", typeof(ICommand), typeof(CommandAttachedProperties), new PropertyMetadata(IsEnabledCommandChanged));

        public static ICommand GetIsEnabledCommand(DependencyObject d) => (ICommand)d.GetValue(IsEnabledCommandProperty);
        public static void SetIsEnabledCommand(DependencyObject d, ICommand value) => d.SetValue(IsEnabledCommandProperty, value);

        private static void IsEnabledCommandChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            EventHandler handler = (o, e) => SetIsEnabled((ICommand)o, d);

            var oldCmd = args.OldValue as ICommand;
            if (oldCmd != null)
            {
                oldCmd.CanExecuteChanged -= handler;
            }

            var newCmd = args.NewValue as ICommand;
            if (newCmd != null)
            {
                newCmd.CanExecuteChanged += handler;
                handler(newCmd, EventArgs.Empty);
            }
        }

        private static void SetIsEnabled(ICommand cmd, DependencyObject d)
        {
            var u = d as UIElement;

            if (u != null)
            {
                u.IsEnabled = cmd.CanExecute(null);
            }
        }

        //////////////////////////////////////////////////////////////////////////////////
    }

```

(I probably found or adapted this code from somewhere else, so credit is owed elsewhere; though any errors are probably mine!)

Here it is in use on a tab item:

```
            <local:SomeDerivedTabItem
                View:CommandAttachedProperties.IsEnabledCommand="{Binding Commands.GeneralTab_SelectTab}"
                />
```

IIRC the AP could be used on any `UIElement`, not only `RibbonTabItems.`

**Comment by batzen** [comment]
I don't think i will add a command to tab items.
Your solution seems like a good fit for your use case.

**Comment by lsaejn** [comment]
@DaveInCaz , thanks a lot! 

> I don't think i will add a command to tab items.
> Your solution seems like a good fit for your use case.

Thanks! Seems I need to modify the tabitem's LeftMouseDown event in the code.

**Comment by lsaejn** [comment]
> @batzen just another thought... I wonder if adding a command to the tab would be a good approach? In my app I use an attached property to set a command on each tab. If the command cannot be executed, the tab is disabled. This might be a nice feature to eventually have built-in (though the AP works perfectly fine).
> 
> maybe this could work for you also.
> 
> ```
>  public class CommandAttachedProperties : DependencyObject
>     {
>         //////////////////////////////////////////////////////////////////////////////////
> 
>         /// <summary>
>         ///  This attached property allows you to bind it to any ICommand, and then it
>         ///  will set IsEnabled based on the executable status of the command. This is
>         ///  useful to de/activate controls which don't take a command natively.
>         /// </summary>
> 
>         public static readonly DependencyProperty IsEnabledCommandProperty =
>             DependencyProperty.RegisterAttached("IsEnabledCommand", typeof(ICommand), typeof(CommandAttachedProperties), new PropertyMetadata(IsEnabledCommandChanged));
> 
>         public static ICommand GetIsEnabledCommand(DependencyObject d) => (ICommand)d.GetValue(IsEnabledCommandProperty);
>         public static void SetIsEnabledCommand(DependencyObject d, ICommand value) => d.SetValue(IsEnabledCommandProperty, value);
> 
>         private static void IsEnabledCommandChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
>         {
>             EventHandler handler = (o, e) => SetIsEnabled((ICommand)o, d);
> 
>             var oldCmd = args.OldValue as ICommand;
>             if (oldCmd != null)
>             {
>                 oldCmd.CanExecuteChanged -= handler;
>             }
> 
>             var newCmd = args.NewValue as ICommand;
>             if (newCmd != null)
>             {
>                 newCmd.CanExecuteChanged += handler;
>                 handler(newCmd, EventArgs.Empty);
>             }
>         }
> 
>         private static void SetIsEnabled(ICommand cmd, DependencyObject d)
>         {
>             var u = d as UIElement;
> 
>             if (u != null)
>             {
>                 u.IsEnabled = cmd.CanExecute(null);
>             }
>         }
> 
>         //////////////////////////////////////////////////////////////////////////////////
>     }
> ```
> 
> (I probably found or adapted this code from somewhere else, so credit is owed elsewhere; though any errors are probably mine!)
> 
> Here it is in use on a tab item:
> 
> ```
>             <local:SomeDerivedTabItem
>                 View:CommandAttachedProperties.IsEnabledCommand="{Binding Commands.GeneralTab_SelectTab}"
>                 />
> ```
> 
> IIRC the AP could be used on any `UIElement`, not only `RibbonTabItems.`

Thank you, i will try it. Good luck!!

**Comment by lsaejn** [comment]
@batzen 
wow! I found that previewmousedown has taken effect and can perfectly meet my needs. It's great!!
Thank you!
