### ISSUE TITLE
QuickAccessToolBar not editable anymore

### ISSUE THREAD

**Issue by chrfin** [fluentribbon/Fluent.Ribbon#849]
I think since v8 (at least it did work in a previous version, as we did use that without a problem in the past) we cannot dynamically update the QuickAccessToolBar anymore. Adding or removing items from `QuickAccessItems` (or any other list containing those items) does not change the GUI anymore.

For adding I found a workaround by calling `QuickAccessToolBar.OnApplyTemplate()`, but I found no way to remove items.

To easily reproduce place the following at the end of the `TestContent.xaml.cs`-constructor of the showcase app:
```
this.buttonGreen.Click += (s, e) =>
{
    var item = new QuickAccessMenuItem();
    item.SetBinding(QuickAccessMenuItem.TargetProperty, new Binding() { Source = this.buttonGreen });
    this.ribbon.QuickAccessItems.Add(item);
    this.ribbon.QuickAccessToolBar.OnApplyTemplate(); // workouround to get it to show up
};
this.buttonYellow.Click += (s, e) => this.ribbon.QuickAccessItems.Remove(this.ribbon.QuickAccessItems.Last());
```
And then press the green/yellow button in the showcase app.  
Green button will add an item to the drop-down-list, but only with the call to `OnApplyTemplate`, but the yellow button does not remove any item.

---
### Environment

- Fluent.Ribbon v8.0
- Windows 10
- .NET Core 3.x

**Comment by batzen** [comment]
You are totally right i broke that with 0a214c1ae512c3300abf96323a7cf5c154b85ba3
