### ISSUE TITLE
ComboBox Items don t get a overlay color when mouse over items ...

### ISSUE THREAD

**Issue by LordDragonR** [fluentribbon/Fluent.Ribbon#85]
When i use the version 3.0.3, you drop down the list of a ComboBox, if you move the mouse over items you will see some background color to show you wich item you re pointing ...
That doesn t work anymore on the latest version i DLed 2 weeks ago.
Any clue on it ?
How it should work :
![comboboxselecteditem](https://cloud.githubusercontent.com/assets/11539337/6868967/6081b4be-d490-11e4-88cc-671b71d7943b.PNG)

**Comment by batzen** [comment]
I can't reproduce this in the current version.
Any more details?

**Comment by abdelkarim** [comment]
I am having this issue as well on the office 2010 theme.
![image](https://cloud.githubusercontent.com/assets/1153480/6986145/6f904b80-da32-11e4-87a3-61f520de27f5.png)

**Comment by batzen** [comment]
I can't reproduce this in the current version.
Any more details?

**Comment by abdelkarim** [comment]
Leave it to me, I will send a Pull Request shortly for this issue.

**Comment by batzen** [comment]
Nice to hear that.
