### ISSUE TITLE
Tab KeyTips Are Shown Together With Tab-Item KeyTips (different to 7.0.0)

### ISSUE THREAD

**Issue by OldCsc1** [fluentribbon/Fluent.Ribbon#851]
In version 7.0.0, when initiating keyboard navigation using the ALT key, (only) the KeyTips specified for the ribbon-tabs will be shown - the KeyTips for the item of a tab will follow when the tab has been choosen.
First key ( ALT ):
![grafik](https://user-images.githubusercontent.com/72034382/94457797-5adbe180-01b5-11eb-8fa5-d7ddc58d0802.png)
Second key ( H ):
![grafik](https://user-images.githubusercontent.com/72034382/94457968-97a7d880-01b5-11eb-902e-db659cecde90.png)

Now (in 8.0.0) tab KeyTips and (current) tab-item KeyTips will be shown at once ( on ALT ):
![grafik](https://user-images.githubusercontent.com/72034382/94458149-d63d9300-01b5-11eb-98c1-05dcbc165124.png)

This increases the effort to coordinate all tab-KeyTips with all tab-item-KeyTips.

Please allow us to switch back to the step-by-step keyboard navigation.

---
### Environment

- Fluent.Ribbon __v8.0.0__
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
Will have a look as that was not intentional.

**Comment by batzen** [comment]
This bug was introduced while fixing #782.
