### ISSUE TITLE
Error:DesiredSizeBinding

### ISSUE THREAD

**Issue by njypx** [fluentribbon/Fluent.Ribbon#853]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	XDG0025	声明的构造函数参数类型不能分配给相应的属性“DesiredSizeBinding”。	Fluent.Ribbon	Styles.xaml	110

**Comment by batzen** [comment]
Please report issues with the WPF designer to Microsoft. The code works when you run the application.
