### ISSUE TITLE
Arrow button not displayed when ribbon wider than window width

### ISSUE THREAD

**Issue by MarcelVersteeg** [fluentribbon/Fluent.Ribbon#854]
When the window containing the ribbon is resized such that the minimum ribbon width is larger than the window width, small arrows should appear on the ribbon to allow scrolling of the ribbon inside the window.

I have downloaded the latest code base of Fluent.Ribbon to see whether the ShowCase application behaves the same. I found out that the issue is solved in the latest code base, but when I replace the compiled Fluent.dll with the binary from the version 8.0.0 NuGet package, the arrow also disappears in the ShowCase application.

This image is of the ShowCase application with the latest code base of Fluent compiled using the complete solution
![Latest codebase](https://user-images.githubusercontent.com/72593247/95649849-10753180-0ae0-11eb-9b54-a1eca8573596.png)

This image is of the ShowCase application, when the Fluent.dll is replaced with the assembly delivered through the NuGet package with version 8.0.0.
![NuGet 8 0 0](https://user-images.githubusercontent.com/72593247/95649851-110dc800-0ae0-11eb-9340-755ed1930d22.png)

### Environment

- Fluent.Ribbon __v8.0.0__
- Windows __10 (version 2004)__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
That's, as you noticed, already fixed in the develop branch. Will try to release as soon as possible as there are quite a few things i broke in version 8.0.

**Comment by MarcelVersteeg** [comment]
Do you have any idea when you will release the new version?

**Comment by batzen** [comment]
Hopefully by next weekend.
