### ISSUE TITLE
Backstage colour won't change on 2013 theme.

### ISSUE THREAD

**Issue by jfhorton** [fluentribbon/Fluent.Ribbon#86]
Unless I've missed something obvious, I can't seem to change the backstage colour on the Office 2013 theme.. It stays the same colour as the Word 2013 backstage.

This is the code I have:
```xml
<!-- In MainWindow.xaml-->
<Window x:Class="WpfApplication5.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Fluent="clr-namespace:Fluent;assembly=Fluent"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <Fluent:Ribbon>
            <Fluent:Ribbon.Menu>
                <Fluent:Backstage Background="#cb0928">
                    <Fluent:BackstageTabControl ItemsPanelBackground="#cb0928">
                        <Fluent:Button Header="Item 1" />
                        <Fluent:Button Header="Item 2" />
                        <Fluent:Button Header="Item 3" />
                    </Fluent:BackstageTabControl>
                </Fluent:Backstage>
            </Fluent:Ribbon.Menu>
        </Fluent:Ribbon>
    </Grid>
</Window>
```
```xml
<!-- In App.xaml-->
<Application x:Class="WpfApplication5.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
    </Application.Resources>
</Application>
```
I found [this](https://fluent.codeplex.com/discussions/350025) question back on the old Codeplex site and have made the change in my own project but this hasn't done anything.

Image of the ribbon:
![screenshot 2015-03-31 16 02 12](https://cloud.githubusercontent.com/assets/8021144/6921962/e8892ac2-d7bf-11e4-8faf-e358811cf0dd.png)

Image of the backstage:
![screenshot 2015-03-31 16 02 14](https://cloud.githubusercontent.com/assets/8021144/6921963/e8a57d94-d7bf-11e4-8bb3-81705edb3d48.png)

**Comment by batzen** [comment]
Currently you have to use
```
<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">#2B579A</Color>
```
I know that's far from perfect, feel free to suggest improvements or create a PR. ;-)

**Comment by jfhorton** [comment]
Where do I place that? I'm a little bit new to WPF. >.<

**Comment by batzen** [comment]
Currently, and that's one of the problems with that solution, you have to place it in your App.xaml or in one of your own ResourceDictionary (which has to be loaded after the Fluent.Ribbon ResourceDictionary).

This means that you can only set one Color for your whole application and not per Window.

Example for App.xaml (just modified the one from our showcase application):
```
<Application xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:Fluent="urn:fluent-ribbon"
             x:Class="FluentTest.App"
             StartupUri="TestWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!--<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />-->
                <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
                <!--<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Windows8/Generic.xaml" />-->
            </ResourceDictionary.MergedDictionaries>
			
			<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">Red</Color>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by jfhorton** [comment]
Well it lets me change it to the colour I need, and that'll do me for now. Thanks. :+1:

**Comment by batzen** [comment]
So this can be closed?

**Comment by jfhorton** [comment]
Yeah, that's fine.  if I ever know enough WPF to make ItemsPanelBackground work properly, I'll create a PR.

**Comment by batzen** [comment]
It's not only the panel background. The color is used throughout ~60 places...

**Comment by batzen** [comment]
Beside that, you should better use the RibbonWindow instead of a regular window to get full ribbon features.

**Comment by jfhorton** [comment]
Yeah, I've got it as a RibbonWindow in my main app. I just pulled it out into a blank WPF window to make sure it wasn't something I'd done accidently.

**Comment by batzen** [comment]
Good to hear that. Will close this issue now. ;-)
