### ISSUE TITLE
Close icon looks wierd

### ISSUE THREAD

**Issue by frostieDE** [fluentribbon/Fluent.Ribbon#861]
The close icon looks wiered - at least on a high dpi screen (currently at 125%). It looks normal at 100%. 

![grafik](https://user-images.githubusercontent.com/3764924/97740581-c5987980-1ae1-11eb-907f-0f9a181409e2.png)

---
### Environment

- Fluent.Ribbon at master (d1a3c7f)
- Windows 10 2004 (Build 19041.572)
- .NET Framework Core 3.1.4

**Comment by batzen** [comment]
Already fixed that yesterday with 8cf688c5c460614e2bd4e74a0a28585bbd47495b. Thanks for reporting. ;-)

**Comment by frostieDE** [comment]
Thank you!
