### ISSUE TITLE
Can't change colorful theme(only can change to "Dark" or "Light")

### ISSUE THREAD

**Issue by drakedoglife** [fluentribbon/Fluent.Ribbon#867]
**Place your issue description here.**
Hi,I just want to change the theme of my project. But when I add 
`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Themes/Light.Blue.xaml" />`
to app.xaml.It seems that only can change theme's "Dark" or "Light",But "blue" can't display.
![image](https://user-images.githubusercontent.com/37531000/98662214-6c063980-2382-11eb-9676-dd109fe7dc97.png)
[Light.Blue]
![image](https://user-images.githubusercontent.com/37531000/98662304-8a6c3500-2382-11eb-95df-5acf4b22c2da.png)
[Dark.Blue]
[code.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5516564/code.zip)

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v8.0.1__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
@drakedoglife If you want to use one of the colorful themes you have to use something like `Dark.Blue.Colorful.xaml` or `Light.Blue.Colorful.xaml`.
`Dark.Blue.xaml` the "blue" part here only defines the accent color which affects the backstage, statusbar etc..

**Comment by drakedoglife** [comment]
@batzen Well, thank u very much! It's starting working!
