### ISSUE TITLE
App crashes When pressing alt multiple times..

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [fluentribbon/Fluent.Ribbon#868]
App crashes When pressing alt multiple times..

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: associatedElement
  Source=Fluent
  StackTrace:
   at Fluent.KeyTipInformation..ctor(String keys, FrameworkElement associatedElement, Boolean hide)
   at
   at

### Environment

- Fluent.Ribbon __v8.0.1__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
Can't reproduce this locally.
Could you provide a repro application or more information about where, when and how often you press ALT?

**Comment by batzen** [comment]
A complete StackTrace would have been enough to find this issue.
Will change some things to try to prevent this issue.
Not sure if my changes fix this issue.
