### ISSUE TITLE
Fluent Namespace problem

### ISSUE THREAD

**Issue by ChangedHourly** [fluentribbon/Fluent.Ribbon#87]
Hi,
I have just updated to the latest package from NuGet and have noticed that when I try to add the Fluent Namespace in xaml the intellisense does not give me the Fluent namespace, only "Fluent.Extensibility", "Fluent.Internal" and "Fluent.Metro.Native". I looked at the Fluent.dll assembly with Object Browser and all seemed OK. What I was actually trying to do was re-template the fluent:RadioButtonn so I was trying to add the Fluent.Converters namespace but couldn't find that.

I have tried resetting VS settings (VS2013 Ultimate) but that has not helped. Any ideas?

**Comment by batzen** [comment]
I never experienced such issues.
You could try to use
```
xmlns:Fluent="urn:fluent-ribbon"
```
If that still doesn't work you should create a repro and attach it to this issue.

**Comment by ChangedHourly** [comment]
Hi, thanks for the quick reply. The "urn:fluent-ribbon" appears in the intellisense and I can add it as a namespace. I can also then add a ribbon to the window, but the project won't compile, giving error "The tag Ribbon" does not exist in XML namespace "urn:fluent-ribbon". Interested to if you see the same with my repro - I am guessing it will work and there must be an issue with my VS installation. Slight problem - really sorry but I can't work out how to attach the file.

**Comment by batzen** [comment]
Just post a link to a shared item in OneDrive or your favorite cloud/upload storage provider.

**Comment by ChangedHourly** [comment]
http://1drv.ms/1OWfizk

**Comment by batzen** [comment]
You got a few mistakes here:
- Your XAML file says it's a "Window" whereas your code behind file says it's a "RibbonWindow"
- You are using the namespace "System.Windows.Controls.Ribbon" in code behind, but the fluent components live in "Fluent"

You got two choices now:
- Remove the inheritance from "RibbonWindow" in your code behind file if you wish to use a regular WPF window
- Change your XAML file from using "<Window" to "<fluent:RibbonWindow" if you wish to use our RibbonWindow

**Comment by ChangedHourly** [comment]
Hi, I think I must have been playing around with the test project and left it in that erroneous state by accident. I have corrected the errors you point out. I still do not get the fluent namespace appearing with the intelli-sense. I have also now tried with a new installation of VS2015 on a virtual machine and that has the same issue. It's no big deal - you can just type in the correct namespace (xmlns:fluent="clr-namespace:Fluent;assembly=Fluent") and all works, just wondering if anybody knew why that might be or even if anyone else has seen this problem.

**Comment by batzen** [comment]
You always need to specify the xmlns part. Without that part no third party library will work/provide intellisense in WPF.

**Comment by ChangedHourly** [comment]
I don't think we are understanding each other! Just to be clear, when I type "xmlns:fluent=" intell-sense gives me a list of available namespaces, as normal. However, "Fluent;assembly=Fluent" is not there.
