### ISSUE TITLE
Disable SplitButton completly if command cannot execute

### ISSUE THREAD

**Issue by MenzenJ** [fluentribbon/Fluent.Ribbon#874]
Hi,

i'm trying to disable the SplitButton completly (i.e. the DropDown, too) if the main command is not executable.

The use case is quite simple: 
Have a main function and additional, more detailed functions for the most common cases. 
(for example Filter, Filter By Name, Filter By Age, ...). If the Filter cannot be used all other functions cannot be used either. Showing the user an active drop down suggests there is still something he can filter.

I've already tried to achieve this behavior with #745 (for technical fix see #761) but was unable to get it right with the current possibilities. As I read in #720 you state that this is the intended behavior but i think the dissapointment you get from clicking a menu and realizing there are no options available weighs heavier.
I tried to look up something suitable in the MS Design Guide, but could not find an appropriate place.

So the questions are:
- Is there a workaround I am missing?
- Would you like to change your mind? :-)

PS: I'm using v7.1.0 so not the latest version but the changelog does not suggest there's something relevant for this topic.

---
### Environment

- Fluent.Ribbon __v7.1.0__
- Windows __10__
- .NET Framework __4.6.2__

**Comment by batzen** [comment]
It's not working for you as #745 was fixed in v8.0. 😉
Could you try it with v8.0?

**Comment by MenzenJ** [comment]
Nice. Read the patch notes and didn't noticed the ticket was moved to v8.
I will try to update and solve the issue on Monday :-)

Thank you!

**Comment by batzen** [comment]
Oh. I forgot to add it to the changelog. Will add it tomorrow.

**Comment by batzen** [comment]
Just fixed the changelog.
Did the changes fix your issue?

**Comment by MenzenJ** [comment]
Yes it works.

![image](https://user-images.githubusercontent.com/44610481/102087064-4bb21a80-3e19-11eb-9ac0-3d9f95b2f351.png)
As you can see none of the command can execute.
The SplitButton B1 is still enabled allowing you to see that all Commands are disabled.
The SplitButton B2 is disabled through IsEnabled="{Binding IsAnyEnabled}"

As soon as i enable any of the commands, the split button gets active:
![image](https://user-images.githubusercontent.com/44610481/102087471-e3b00400-3e19-11eb-98ec-bb5b6168f9b3.png)

If only the "main"-Command can execute the drop down still gets enabled but I think this is fine, letting the user know in the current configuration he cannot access the more specific commands.

![image](https://user-images.githubusercontent.com/44610481/102087708-3b4e6f80-3e1a-11eb-847e-201a2aaac801.png)

Thank you for your feedback and providing an easy fix by making the binding two way in the first place!
