### ISSUE TITLE
Fluent BackstageTabControl Issue

### ISSUE THREAD

**Issue by ukshukla** [fluentribbon/Fluent.Ribbon#88]
Hi,

I have just updated Fluent Ribbon 3.0 in my project.After updating it first issue in my project that was appearing black window which I have fixed after using generic.xaml.

Now I am here giving code in which I am using Fluent BackstageTabControl control.
                      

                    <Fluent:Ribbon.Menu>
                    <Fluent:Backstage Name="backstage"
                                      Background="#FF0F81CB"
                                      Header="Info">
                        <Fluent:BackstageTabControl>
                            <Fluent:Button Name="btnChangeAdminPassword"
                                           Click="btnChangeAdminPassword_Click"
                                           Header="Change Password"
                                           Icon="/TestApp;component/Icons/Num_Lock.png"
                                           VerticalAlignment="Center"
                                           Visibility="Collapsed"
                                           Size="Small" />
                            <Fluent:Button Name="btnAbout"
                                           Click="btnAbout_Click"
                                           Header="About BI360"
                                           Icon="/TestApp;component/Icons/info.png"
                                           Size="Small" />
                            <Fluent:Button Name="btnExit"
                                           Click="btnExit_Click"
                                           Header="Exit"
                                           Icon="/TestApp;component/Icons/ExitLarge.png"
                                           Size="Small" />
                            
                        </Fluent:BackstageTabControl>
                    </Fluent:Backstage>
               </Fluent:Ribbon.Menu>

using generic.xaml these buttons are not visiible,if I mouse hover then I seems that buton is there but their header and icon are not visible.

I am using these Fluent's resources
Generic.xaml
Office2010/Blue.xaml

Please suggest me solution for this.
Thanks in advance.

**Comment by ukshukla** [comment]
![invisible_buttons](https://cloud.githubusercontent.com/assets/11771181/6980404/bfde87c4-da0e-11e4-8544-e0bdee69e375.png)

**Comment by batzen** [comment]
A repro would be nice.

**Comment by batzen** [comment]
Any news on this one?

**Comment by batzen** [comment]
Any news on this one?

**Comment by dparsons86** [comment]
I'm having a similar issue - I'm not able to get any images to display on the backstage (on the left bar or the main body of the page). Also, the corner bit of color doesn't show up.
In the main part of the backstage area, unless I specify the foreground color, it is white text until I hover over it.

The lack of corner color and lack of images/icons exists in my code and also when I run the Fluent Test examples (.net 4.0 and 4.5).

I'm seeing this in the output window in Visual Studio:
```
'WpfApplicationPOC.vshost.exe' (CLR v4.0.30319: WpfApplicationPOC.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Cannot find or open the PDB file.
System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Remove'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='51085567'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='Fluent.BackstageTabControl Items.Count:3'; TargetElement.HashCode='54205966'; TargetElement.Type='Fluent.BackstageTabControl'
```

Here is my code, which started from the .net 4.5 Fluent test:
```xml
<!--Backstage-->
<Fluent:Ribbon.Menu>
   <Fluent:Backstage>
       <Fluent:BackstageTabControl>
           <Fluent:BackstageTabItem Header="Start Processes">
               <Grid Margin="50"
                         MinWidth="0"
                         Width="Auto"
                         HorizontalAlignment="Left"
                     VerticalAlignment="Top">
                   <Grid.RowDefinitions>
                       <RowDefinition/>
                       <RowDefinition/>
                   </Grid.RowDefinitions>
                   <Grid.ColumnDefinitions>
                       <ColumnDefinition/>
                       <ColumnDefinition/>
                   </Grid.ColumnDefinitions>
                   <Fluent:Button Grid.Row="0" Grid.Column="0" Name="StartProc1" Click="StartNewProcess1" Foreground="Black"  >
                       <Image Source="images/water_plus.png" ></Image>
                   </Fluent:Button>
                   <Fluent:Button Grid.Row="0" Grid.Column="1" Name="StartProc12" Header="Start Process 1" Click="StartNewProcess1" Foreground="Black" />
                   <Fluent:Button Grid.Row="1" Name="StartProc2" Header="Start Process 2" Icon="images\marker_add.png" LargeIcon="images\marker_add.png" Click="StartNewProcess2" Foreground="Black" />
               </Grid>
           </Fluent:BackstageTabItem>
           <Fluent:BackstageTabItem Header="Print"/>
           <Fluent:Button Header="Blue" Icon="Images\Blue.png"/>
       </Fluent:BackstageTabControl>
   </Fluent:Backstage>
</Fluent:Ribbon.Menu>
```

![image](https://cloud.githubusercontent.com/assets/8174006/8339235/8b36e8a6-1a62-11e5-9c65-12bb7f0b747e.png)

**Comment by dparsons86** [comment]
Update to my comment: The answers on here fixed my issue:
https://github.com/fluentribbon/Fluent.Ribbon/issues/111

**Comment by batzen** [comment]
- The warning about the missing pdb is fully correct because the assembly is part of the .NET framework.
- The storyboard warning is a known issue but I don't see a reason to fix it because it's just a warning and does no harm.
- The icons are not displayed because there are no icons in office 2013 too.
- I don't know what you mean by corner color.

We tried to rebuild the office 2013 as good as possible.

**Comment by dparsons86** [comment]
Thanks! I appreciate the explanation. 

The "corner color" was right corner of the whole screen being blue, but that was just which theme it was using.
