### ISSUE TITLE
Problem after update to version 8.1

### ISSUE THREAD

**Issue by achia70** [fluentribbon/Fluent.Ribbon#882]
Hi, I updated to version 8.1 (WPF) but there's an problem. the error "The name RibbonWindow does not exist in the namespace urn:fluent-ribbon." error showed up. I don't know what to do now.
Here is the screen shot:
![image](https://user-images.githubusercontent.com/65407363/101871586-6afd3d80-3bb6-11eb-8416-d74b6131e521.png)

---
### Environment

- Fluent.Ribbon __v8.1.?__
- Windows __10.0.17763__
- .NET Framework __4.7.2__

**Comment by batzen** [comment]
I guess you mean version 8.0.2.
Have you ran a nuget restore after updating?

**Comment by achia70** [comment]
It worked again after downgrade to version 7.1
However, all icon showed as (X) even though I entered the right image source
![image](https://user-images.githubusercontent.com/65407363/101875394-1e693080-3bbd-11eb-866d-12141fee1233.png)

**Comment by batzen** [comment]
If the icons/images render correctly during runtime please file an issue for the WPF designer of Visual Studio.
There is nothing wrong with Fluent.Ribbon in that case, but with the designer itself instead.
