### ISSUE TITLE
GroupBy not working anymore on Fluent:Gallery?

### ISSUE THREAD

**Issue by GinoDerycke** [fluentribbon/Fluent.Ribbon#883]
I updated to Visual Studio 2019 and Fluent.Ribbon 8.0.2, but it seems that the GroupBy function is not working anymore on the Gallery.

Previously, the grouped items had a header with the groupname, but now all items are all in one list.

I am 100% sure that the GroupName for each item is filled in.

My XAML code:
 
<Fluent:Gallery x:Name="gallery" MaxHeight="450" ItemHeight="100" ItemWidth="300" MaxItemsInRow="3" 
                    ItemsSource="{Binding CollectionViewSource.View}" ItemTemplateSelector="{StaticResource GalleryItemTemplateSelector}"
                    GroupBy="GroupName" Grid.Row="1" BorderThickness="0">
        </Fluent:Gallery>

Thanks in advance!

**Comment by batzen** [comment]
I broke grouping in `Gallery` in early 2019 by changing the default value of `IsGrouped` on `GalleryPanel` from `true` to `false`.
To fix this i will add a new `IsGrouped` property to `Gallery`.

**Comment by GinoDerycke** [comment]
OK, thank you!
