### ISSUE TITLE
gallery autosize

### ISSUE THREAD

**Issue by mijq1** [fluentribbon/Fluent.Ribbon#884]
I have a listview inside a gallery that can grow in width on user input.
Problem is the gallery does not scale to reflect this.

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v8.0.2__
- Windows __10__
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
Could you attach a repro for that?

**Comment by mijq1** [comment]
Sent you a link to a test program with the  problem.
Forgot to mention that the the gallery comes down when the drop down button is clicked.
If the user checks the gradient option. The listview expands in width to include a new column.
Unfortunately, the gallery doesn't seem to auto scale.

Best

Mikkel

**Comment by batzen** [comment]
Where did you send the link to?

**Comment by mijq1** [comment]
Sorry, 
Forgot that my outlook won’t send unless I’m at work.
Will send tomorrow 
Regards
Mikkel

**Comment by mijq1** [comment]
https://www.dropbox.com/sh/vzpu5b9i8bs6mep/AADXdTkjKPHN2_zCbyl4JzOva?dl=0

here is the link

**Comment by mijq1** [comment]
and here is the source code:
https://www.dropbox.com/sh/ju85hl4qfrd32io/AAD8TvLinnL45Zr7_HQOYS4Na?dl=0

**Comment by batzen** [comment]
May i ask why you are using a `Gallery` in the first place?
You don't seem to make use of any of the features it offers.
It might be a lot easier to just use a `StackPanel` or some other container.

**Comment by mijq1** [comment]
Didn’t realize that I could do that
Will test it thanks
Mikkel

**Comment by batzen** [comment]
You can place whatever you want inside a `DropDownButton` ;-)

**Comment by mijq1** [comment]
Tried your suggestion worked like a charm 
thanks.

/mikkel
