### ISSUE TITLE
When a window is maximized its 'Restore down' icon gets distorted

### ISSUE THREAD

**Issue by vmarinov32** [fluentribbon/Fluent.Ribbon#885]
Hi,

Recently I've updated to 8.0.2 and noticed that the maximize button's icon gets distorted when the window is fully maximized.
![image](https://user-images.githubusercontent.com/76511906/102971381-f903ed00-4501-11eb-8a8f-823a444b74a9.png)

---
### Environment

- Fluent.Ribbon 8.0.2
- Windows 10.0.19041
- .NET Framework 4.7.2

**Comment by batzen** [comment]
Argh...
