### ISSUE TITLE
Just a UI Element Idea

### ISSUE THREAD

**Issue by nkrs200** [fluentribbon/Fluent.Ribbon#886]
For a while now, I've been using a custom checkbox control to act as a switch element and I've also been using a custom Slider control for a while now as well that acts similarly to the one found in Office 2016 and beyond as well as Office 365 (visually, that is).  I think it would be cool to see if these were implemented in the Fluent.Ribbon library as it would add a bit more options for people to use when it comes to UI Elements.

Attached is sample code of the controls that I created.
[ExampleControls.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5754565/ExampleControls.zip)

I am currently using the following:
- Fluent.Ribbon V8.0.0
- Windows 10 x64 Build 1903
- .NET Framework 4.6.1

**Comment by batzen** [comment]
Will have a look at these during the next few days.
Thanks for sharing those!
