### ISSUE TITLE
Item Highlight in backstage when clicking outside the window.

### ISSUE THREAD

**Issue by Offline-R503B** [fluentribbon/Fluent.Ribbon#893]
Simple repro : Open Application-> Go to backstage click anywhere in the backstage ->  Click out of the window -> Reopen from taskbar >  One item will be bright highlighted.
![image](https://user-images.githubusercontent.com/11785451/104965369-e2589500-59de-11eb-9148-5f62917a877c.png)

---
### Environment

- Fluent.Ribbon __
![image](https://user-images.githubusercontent.com/11785451/104965297-b9d09b00-59de-11eb-8dbd-7d3785bceaf2.png)

- Windows __10__
- .NET Framework __5.0__

**Comment by batzen** [comment]
@Offline-R503B Sorry for my late response.
I investigated this and in my opinion this is a bug/misbehavior of WPF itself as the button does not have keyboard focus when leaving the window but gets keyboard focus from WPF itself as soon as the window is activated again.
There is, as far as i found out (and i tried a lot of mitigations), nothing i can do to prevent this...

**Comment by Offline-R503B** [comment]
Ahh! That solves the mystery then, thanks for looking we can close this issue then :)
