### ISSUE TITLE
Quick Access Toolbar items not saved 

### ISSUE THREAD

**Issue by mparrella** [fluentribbon/Fluent.Ribbon#895]
Items in the Quick Access Toolbar do not reappear when the program is restarted

---
### Environment

- Fluent.Ribbon __v8.0.3__
- Windows _10_
- .NET Framework __4.5__

**Comment by batzen** [comment]
Persisting the selected quick access items was removed in version 8.0 as it was too fragile. Please have a look at #810 for details.

**Comment by mparrella** [comment]
Thans so much
