### ISSUE TITLE
RibbonContextualTabGroup does not Expand when Header is Wider than Content

### ISSUE THREAD

**Issue by dartt** [fluentribbon/Fluent.Ribbon#899]
If the header of a RibbonContextualTabGroup is wider than the tabs it contains, then it will not expand to show the group header text.

I've attached a small window XAML demonstrating the issues.

[MainWindow.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5933534/MainWindow.zip)

I expect to see the full 'A Long Header Text' header text but instead it is only as wide as the 'Tab 1' tab and the header text is truncated.

---
### Environment

- Fluent.Ribbon v8.0.3
- Windows 10
- .NET Framework 4.8

**Comment by dartt** [comment]
![image](https://user-images.githubusercontent.com/41622/107054330-e3a00500-67c7-11eb-8375-9aef2ff2bb03.png)

**Comment by batzen** [comment]
That's intentional as i expect it to not be larger than the horizontal space available above the tabs it belongs to.
But i would be happy to accept a PR that adds an optional switch to `RibbonContextualTabGroup` to allow it to use it's desired size instead of being limited by it's tabs.

**Comment by dartt** [comment]
Hi Batzen,

Thanks for the quick response. I think we will work around this issue for now.

We just upgraded from version 5 to version 8 and this behaviour seems to be new - our tabs previously seemed to keep much more of their desired width. Here is a picture of the same test app using v5.
![image](https://user-images.githubusercontent.com/41622/107244686-3545cb00-6a26-11eb-94e6-a5e1c03a30eb.png)

If we have the resource, we may try and create a PR to add a flag to change this behaviour but I don't think we will be able to right now.

Thanks again.

**Comment by dartt** [comment]
For anyone else who is trying to work around this issue:

Our solution was to simply pad either side of the small tab header string with enough spaces to match the width of the contextual tab header string.

e.g. Header="   VIEW    "
![image](https://user-images.githubusercontent.com/41622/107248529-4a245d80-6a2a-11eb-905d-2a9ec28808b2.png)

**Comment by batzen** [comment]
Closing because no one seems interested in helping with this.
