### ISSUE TITLE
Application freezes when opening collapsed groups with galleries

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#900]
Hi @batzen!

I'm afraid I found another bug in the context of InRibbonGalleries and resizing.
With your hint above, I managed to activate correct resizing of the galleries, also resizing of the dropdown buttons.
However when I reduce the size even more that the group which contains the gallery reduces to a dropdown button and I try to open that dropdown, the application freezes.

Here's a video and my sample application:

![Frozen](https://user-images.githubusercontent.com/9028723/107085364-b0299e80-67f8-11eb-9dd9-d4ecea8a70a6.gif)

[GalleryTests.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/5935136/GalleryTests.zip)

**Comment by batzen** [comment]
Will try to have a look at this during the weekend.
