### ISSUE TITLE
Recolor the scrollbar

### ISSUE THREAD

**Issue by ahmad-devlop** [fluentribbon/Fluent.Ribbon#901]
Can I recolor the scrollbar? How?

**Comment by batzen** [comment]
Which scrollbar do you mean?

**Comment by ahmad-devlop** [comment]
Actually, in the whole of application (**globally**).

**Comment by batzen** [comment]
Fluent.Ribbon does not provide application wide themes/styles, but primarily themes/styles for the controls it provides.
If you are really talking about application wide styles you should read some WPF styling tutorial.
Something like https://wpf-tutorial.com/styles/using-styles/.
Or more specifically with scrollbar styles https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollbar-styles-and-templates?view=netframeworkdesktop-4.8
