### ISSUE TITLE
ThemeManager.ChangeTheme missing in v8.0.3

### ISSUE THREAD

**Issue by RandomEngy** [fluentribbon/Fluent.Ribbon#904]
The [styles documentation](https://fluentribbon.github.io/documentation/styles_since_7) says:

```cs
// now set the Green color scheme and dark base color
ThemeManager.ChangeTheme(Application.Current, "Dark.Green");
```

But there does not appear to be any ThemeManager static method anymore. There is an instanced method at `ControlsEx.Theming.ThemeManager`, but I'm getting a runtime error when I try this code:

```cs
var manager = new ControlzEx.Theming.ThemeManager();
manager.ChangeTheme(this, "Dark.Cobalt");
```

`System.ArgumentNullException: 'Value cannot be null. (Parameter 'newTheme')'`

It appears to have chosen this overload, despite the fact that I passed it a string for the second param:
![image](https://user-images.githubusercontent.com/9450861/109430011-d84d8d00-79b3-11eb-8de0-41b61ee9ec0b.png)

**Comment by batzen** [comment]
Uh, i totally forgot to update the documentation after releasing v8.

You have to use `ControlzEx.Theming.ThemeManager.Current` to make it work.
Will update the documentation as fast as i can.

**Comment by batzen** [comment]
The error message could also be improved to tell the caller that the desired theme with name "xy" could not be found.
In your case the theme is not found because you created a new `ThemeManager` instead of using `ThemeManager.Current`.

**Comment by RandomEngy** [comment]
Thanks, that works!

**Comment by batzen** [comment]
Updated the documentation. It's now here https://fluentribbon.github.io/documentation/styles_since_8
You can read more about the `ThemeManager` capabilities at https://github.com/ControlzEx/ControlzEx/blob/develop/Wiki/ThemeManager.md

**Comment by batzen** [comment]
Changelog is also more clear about these changes now.
Thanks for bringing this up.
