### ISSUE TITLE
How to disable RibbonTabItem's Header content clipping?

### ISSUE THREAD

**Issue by ValentinMarinov** [fluentribbon/Fluent.Ribbon#91]
Hi, guys!
I tried to modify the xaml part of RibbonTabItem so that its "Header" contains a StackPanel, which contains an Image and a TextBlock, but for some reason the content is "clipped". I tried to set the Height of several grids and borders up the visual tree, but none of these seems to be the source of the problem.

**Comment by batzen** [comment]
So what's the question/request/issue here?
Any repro you could send in?

**Comment by batzen** [comment]
Any news on this one?
