### ISSUE TITLE
No resizing of buttons when resizing the ribbon.

### ISSUE THREAD

**Issue by Perpete** [fluentribbon/Fluent.Ribbon#912]
**Environment**
• Fluent.Ribbon 8.0.3
• Windows 10
• .NET Framework 4.8
• Visual studio 16.9.0
• Project WPF in VB.net

Hello,
I use the SizeDefinition ’property of the buttons to change their sizes when resizing the ribbon. 
Apparently it doesn't work in my program.
However, I think I have followed the example of the documentation.

`<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Fluent:Ribbon Grid.Row="0" >
            <Fluent:RibbonTabItem Header="Fonctions de tests">
                <Fluent:RibbonGroupBox Header="Connexion">
                    <Fluent:Button x:Name="rbbtConnect" Header="Connecter" Icon="Images/Connect_16.png" LargeIcon="Images/Connect_32.png" SizeDefinition="Large, Large, Small"/>
                    <Fluent:Button x:Name="rbbtDisConnect" Header="Déconnecter" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png" SizeDefinition="Large, Large, Small"/>
                    <Fluent:Button Header="Essai-1" SizeDefinition="Large, Large, Small" Icon="Images/Connect_16.png" LargeIcon="Images/Connect_32.png"/>
                    <Fluent:Button Header="Essai-2" SizeDefinition="Large, Large, Small" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png"/>
                    <Fluent:Button Header="Essai-3" SizeDefinition="Large, Large, Small" Icon="Images/Connect_16.png" LargeIcon="Images/Connect_32.png"/>
                    <Fluent:Button Header="Essai-4" SizeDefinition="Large, Large, Small" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png"/>
                </Fluent:RibbonGroupBox>
                <Fluent:RibbonGroupBox Header="Connexion2">
                    <Fluent:Button Header="Essai-1" SizeDefinition="Large, Large, Small" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png"/>
                    <Fluent:Button Header="Essai-2" SizeDefinition="Large, Large, Small" Icon="Images/Connect_16.png" LargeIcon="Images/Connect_32.png"/>
                    <Fluent:Button Header="Essai-3" SizeDefinition="Large, Large, Small" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png"/>
                    <Fluent:Button Header="Essai-4" SizeDefinition="Large, Large, Small" Icon="Images/Connect_16.png" LargeIcon="Images/Connect_32.png"/>
                    <Fluent:Button Header="Essai-5" SizeDefinition="Large, Large, Small" Icon="Images/Disconnect_16.png" LargeIcon="Images/Disconnect_32.png"/>
                </Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
        </Fluent:Ribbon>

        <Grid Grid.Row="1" Background="#FFE6E6E6"/>
    </Grid>`

![Rezise](https://user-images.githubusercontent.com/66659162/110344231-92389f00-802d-11eb-91b6-35fcecba142b.gif)

**Comment by batzen** [comment]
You must set the `ReduceOrder` on the `RibbonTabItem` to enable resizing. 😉

**Comment by Perpete** [comment]
Thank you
it works.
