### ISSUE TITLE
Keep tooltip on screen

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#913]
In office applications the tooltips remain open when you hover the mouse over them.
Is this possible without creating my own ScreenTip control?

**Comment by batzen** [comment]
As ScreenTip inherits from ToolTip you can use the same settings you can use for ToolTip.
Things like ToolTipService.ShowDuration should achieve what you want.

**Comment by pschimmel** [comment]
You're probably right. I've not tried yet, but thank you!
