### ISSUE TITLE
Add ability to vertically align items in Backstage

### ISSUE THREAD

**Issue by nlogozzo** [fluentribbon/Fluent.Ribbon#936]
I followed issue #896 to align some items to the bottom of the backstage below is my xaml

```xml
<ribbon:Backstage>
    <Grid>
        <ribbon:BackstageTabControl>
             <ribbon:Button Header="Open"/>
         </ribbon:BackstageTabControl>

         <ribbon:BackstageTabControl VerticalAlignment="Bottom" Margin="0,0,0,4" IsBackButtonVisible="False">
             <ribbon:BackstageTabItem Header="Settings">
                  <ui:Frame Content="{Binding SettingsPage}"/>
              </ribbon:BackstageTabItem>
              <ribbon:Button Header="Exit" Click="BtnExit_Click"/>
         </ribbon:BackstageTabControl>
    </Grid>
</ribbon:Backstage>
 ```
 
However it ends up looking like this:
![image](https://user-images.githubusercontent.com/17648453/118362920-d9786a00-b55f-11eb-8b98-2488810f4473.png)

How can i get it so the items stay all the way at the bottom and for the settings page to take up the entire screen. Thanks in advanced

**Comment by batzen** [comment]
@nlogozzo You can easily achieve this starting with version 9.0 by setting `VerticalAlignment="Bottom"`
