### ISSUE TITLE
Backstage does not respect RibbonWindow.LayoutTransform

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#940]
In my ribbon app, I managed to get decent zoom functionality using a `LayoutTransform` on my top-level `Window`. Everything seems to work. However, the `Backstage` does not respect this transform.

```c#
var transform = new ScaleTransform(4, 4);
window.LayoutTransform = transform;
ribbonWindow.LayoutTransform = transform;
```

How do you get the `Backstage` to respect the applied transform?

---
### Environment

- Fluent.Ribbon __v7.0.0__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
This works perfectly fine in the showcase application.
Are you using a regular window or a RibbonWindow?
