### ISSUE TITLE
Minimize button misplaced

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#948]
Can we restyle it to get `Office 2016` look?

![image](https://user-images.githubusercontent.com/958469/120775311-61301380-c523-11eb-8d1c-b3e233b96131.png)

The current placement is problematic when you add multiple toolbar items. The minimize button then ends up near the center. It seems hard to re-template the problematic `XAML`:

```xml
<StackPanel HorizontalAlignment="Right"
            Grid.Column="3"
            Orientation="Horizontal"
            Margin="0,0,0,1">
    <Fluent:ToggleButton x:Name="PART_MinimizeButton"
                         Margin="0"
                         Width="22"
                         Height="22"
                         Size="Small"
                         Style="{DynamicResource RibbonTabControlToggleButtonStyle}"
                         IsChecked="{Binding Path=IsMinimized, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}}"
                         Visibility="{TemplateBinding CanMinimize, Converter={StaticResource boolToVisibilityConverter}}" />

    <StackPanel x:Name="PART_ToolbarPanel"
                Visibility="{Binding IsToolBarVisible, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource boolToVisibilityConverter}}"
                Orientation="Horizontal" />
</StackPanel>
```

---
### Environment

- Fluent.Ribbon __v7.0.0__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
@znakeeye As a first step to improve consistency across application i will move the minimize button to right hand side of the toolbar.

**Comment by batzen** [comment]
@znakeeye I thought about this again and think the current solution (having it moved to the right side) looks and feels better than the Office version where the button is shown/hidden depending on state.
What do you think?

**Comment by znakeeye** [comment]
Do you have a screenshot? Don't have my ribbon app at hand :D

**Comment by batzen** [comment]
![image](https://user-images.githubusercontent.com/1971030/173242419-66bd1150-5668-4dad-bb8d-da29f2b75789.png)
![image](https://user-images.githubusercontent.com/1971030/173242435-467375c9-6af9-477a-bd8b-2cb27c23adf5.png)
![image](https://user-images.githubusercontent.com/1971030/173242448-9bbea0aa-21ea-4527-a8a4-5a7e38a7d717.png)

**Comment by znakeeye** [comment]
I agree with you. I actually "struggled" with this in Office 365 the other day. Hiding a button is not ideal 🙂

**Comment by batzen** [comment]
So can we close this or do you think there should be other changes made to the minimize button?
