### ISSUE TITLE
Help with IsSelectionRequired property setting on "File" tab for accessibility purposes

### ISSUE THREAD

**Issue by cprivera** [fluentribbon/Fluent.Ribbon#952]
Hello, I'm working on making WinDbgNext more accessible by resolving errors that are flagged with Accessibility Insights for Windows. I've come across an error flagged on the Fluent.Ribbon we've integrated that says "An element of the given ControlType must have the IsSelectionRequired property set to TRUE". I'm hoping someone might have some experience working on accessibility for the Fluent.Ribbon that might be able to help, perhaps in giving pointers to what could be causing this issue and how it relates to the Fluent.Ribbon.

I've attached the test file with the error that can be opened with Accessibility Insights for Windows in case that helps.
[TestResults 02-22-21_Main.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/6649530/TestResults.02-22-21_Main.zip)

---
### Environment

- Fluent.Ribbon __v8.0.3__
- Windows __10__
- .NET Framework __6.0__

**Comment by batzen** [comment]
Thanks for reporting this and please feel free to report all accessibility issues, and of course all other kinds of issues too, you find. 
I put quite some work into writing custom automation peers and want them to really help.
