### ISSUE TITLE
Tooltip / Screentip appears after a menu item in a split button has been clicked

### ISSUE THREAD

**Issue by atlastodor** [fluentribbon/Fluent.Ribbon#953]
**Given:** 
- A split button with a tooltip or screentip.
- And a menu item in that split button, which also contains a tooltip or screentip 
- And a logic (command or click handler) that opens a dialog / runs a new dispatcher loop.

**When clicking on the menu item, the dialog is shown and a moment later, the tooltip for the split button is shown (overlapping whatever is on the screen)** 

See video: [https://www.screencast.com/t/szioTWRk04Z](https://www.screencast.com/t/szioTWRk04Z)

```
<Fluent:SplitButton
    Header="Action"
    Icon="{DynamicResource Fluent.Ribbon.Images.Paste}"
    LargeIcon="{DynamicResource Fluent.Ribbon.Images.Paste}">
    <Fluent:SplitButton.ToolTip>
        <Fluent:ScreenTip Text="Lorem ipsum dolor..." />
    </Fluent:SplitButton.ToolTip>
    <Fluent:MenuItem
        Command="{Binding TestCommand, ElementName=TestContentControl}"
        Header="Menu Item"
        Icon="{DynamicResource Fluent.Ribbon.Images.Paste}" 
        ToolTip="THIS MUST HAVE A TOOLTIP!"
    /> 
</Fluent:SplitButton>
```
---
### Environment

- Fluent.Ribbon Commit 82389273, but also in NuGet 8.0.3
- Windows 10.0.19042.1052
- .NET Framework net 5.0

**Comment by batzen** [comment]
@atlastodor That's not a bug in Fluent.Ribbon, but in WPF itself. Please have a look at https://github.com/dotnet/wpf/issues/4613
This bug was introduced by changes made to WPF which added ToolTip opening by keyboard focus.
You can also reproduce this by switching to a regular tooltip.

**Comment by atlastodor** [comment]
Thanks Bastian. This is an annoying one. Do you know of any hack to work around the bug?

**Comment by batzen** [comment]
You can use the app context switch mentioned in https://github.com/dotnet/wpf/issues/4172

**Comment by atlastodor** [comment]
Danke Bastian. Close the case for now, as we can't do much. I believe we will use the app context switch to disable this "feature" in 4.8. We will be migrating to .Net 6 later this year and I cross fingers that MS will fix it. Will they accept a PR in the WPF repository, if we implement the fix?

**Comment by batzen** [comment]
@atlastodor I implemented a fix, proposed a PR and they rejected it because "Your solution here isn't quite flexible enough.". But they seem to plan to fix this, don't know if it will be included in .NET 6.
