### ISSUE TITLE
Adding an InputBinding for Alt+Up or Alt+Down results in extra character

### ISSUE THREAD

**Issue by dgosbell** [fluentribbon/Fluent.Ribbon#954]
This is a bit of an edge case, but I was attempting to add hotkeys for Alt+Up and Alt+Down to my application which uses Fluent Ribbon, but I was getting extra characters entered and I managed to isolate the fact that this only happened when the window included Fluent Ribbon and I've been able to replicate this in the showcase application

![image](https://user-images.githubusercontent.com/8241830/122322334-a7946200-cf68-11eb-85f3-03704759087e.png)

(These characters are the same you would get from typing Alt+8 and Alt+2 and on English keyboards at least Num8 is the same as the Up key and Num2 is the same as the Down key if numlock is off)

I've been able to narrow the issue down to this one call, if I temporarily stub out this line I do not get the extra character
https://github.com/fluentribbon/Fluent.Ribbon/blob/797ced0bd35c8ebe2043d77004d0b8b5129e9591/Fluent.Ribbon/Internal/KeyEventUtility.cs#L21

Looking at the docs for the [ToUnicode](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicode) function it says _"If bit 0 is set, a menu is active."_ I tried setting this to 1 and it does fix this issue but there is no further explanation of what this means so I was not confident to just submit a pull request without raising this as an issue first.

I've manually tested this and the KeyTip navigation still works as do other accelerator keys (such as using alt-A to navigate to the other text box on the Test tab) so I think this is a safe change, but I wanted to open a discussion around this first to see if you had any feedback.

It's strange that if there is not an active input binding these extra characters are not generated

I've attached a copy of TestWindow.xaml.cs which includes some code to add some input bindings which reproduce this issue you just need put this in the Fluent.Ribbon.Showcase folder
[TestWindow.xaml.cs.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/6667213/TestWindow.xaml.cs.zip)

If you then edit line 21 of Fluent.Ribbon/Internal/KeyEventUtility.cs to pass a 1 instead of a 0 for the last parameter of ToUnicode( ) it "fixes" this issue.

---
### Environment

- Fluent.Ribbon __v8.0.0.0__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
That's indeed very strange. I guess i didn't pay enough attention when using that API.
Thanks for pointing out the correct way to fix this.

**Comment by dgosbell** [comment]
Thanks! I don't think it's your fault at all, those flags are VERY poorly documented
