### ISSUE TITLE
Changing background color of Fluent:TextBox input field

### ISSUE THREAD

**Issue by MattMoszczynski** [fluentribbon/Fluent.Ribbon#956]
Hi! I was wondering if it's possible to change the background of Fluent TextBox input control? The following code below didn't work for me sadly:

`<Fluent:TextBox Header="Sample header text" Background="Red"/>`

The result:
![textbox](https://user-images.githubusercontent.com/10995478/123514737-ad8af100-d694-11eb-9b67-ba67e8440b63.PNG)
The background of the input field wasn't changed.

---
### Environment

- Fluent.Ribbon __v8.0.3__
- Windows __10 x64__
- .NET Framework __4.8__

**Comment by batzen** [comment]
That's of course possible. 😉
You can set the resource Fluent.Ribbon.Brushes.TextBox.Background to change the background.
Have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Themes/Theme.Template.xaml for all available resources.

**Comment by MattMoszczynski** [comment]
> That's of course possible. 😉
> You can set the resource Fluent.Ribbon.Brushes.TextBox.Background to change the background.
> Have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon/Themes/Themes/Theme.Template.xaml for all available resources.

Thank you @batzen! Although I still wonder if it would be possible to change the background colour of one specific TextBox instead of editing the theme template? Also, I would like to add a Trigger that would change the background colour depending on a specified condition. Any ideas on how I could achieve this? ~~I'm sorry I'm still new to the WPF and XAML mechanics~~ 😅

**Comment by batzen** [comment]
You don't have to change the template. You can change the resource at the style or instance level.
I am currently away from a PC. Will provide a sample here later or tomorrow, depending on when I'm home again.

**Comment by MattMoszczynski** [comment]
@batzen Alright! Thank you so much! In the meantime, I'll be trying to figure it out by myself.

**Comment by MattMoszczynski** [comment]
I did manage to make it work with a custom made Converter. This is how it looks when binding in my XAML file:

```
<Fluent:TextBox Header="Price" IsReadOnly="True">
    <Fluent:TextBox.Resources>
        <SolidColorBrush x:Key="Fluent.Ribbon.Brushes.TextBox.Background" Color="{Binding IsPriceCorrect, Converter={StaticResource priceCheckConverter}}"/>
    </Fluent:TextBox.Resources>
</Fluent:TextBox>
```

**Comment by batzen** [comment]
Glad you found a solution. Sorry for not providing a sample. Totally forgot about this.
