### ISSUE TITLE
Synched Accent transparent at startup

### ISSUE THREAD

**Issue by 537mfb** [fluentribbon/Fluent.Ribbon#958]
I'm using both `Fluent.Ribbon` and `MahApps` in a small project. In `appsettings.json` i have a set of settings to determine both if i will sync the theme with the OS or use a specific theme.

This is what my `MetroWindow_Loaded` looks like:

```
        private void MetroWindow_Loaded(object sender, RoutedEventArgs e)
        {
            TitleBar = this.FindChild<RibbonTitleBar>("RibbonTitleBar");
            TitleBar.InvalidateArrange();
            TitleBar.UpdateLayout();
            ThemeManager.Current.ChangeTheme(this, ThemeManager.Current.DetectTheme(Application.Current));
            if (_config.CurrentValue.Theme.SyncWithWindows)
            {
                ThemeManager.Current.ThemeSyncMode = ThemeSyncMode.SyncAll;
                ThemeManager.Current.SyncTheme();
            }
            else
            {
                ThemeManager.Current.ChangeTheme(this, (_config.CurrentValue.Theme.DarkAppMode ? "Dark." : "Light.") + 
                    _config.CurrentValue.Theme.Accent + (_config.CurrentValue.Theme.IsColorful ? ".Colorful" : ""));
            }
            ThemeManager.Current.ThemeChanged += SyncThemes;
        }
```

When i have in my settings to sync with windows, any area that should have the accent is transparent (including the `File` button and the sidebar in the `backstage`.

![image](https://user-images.githubusercontent.com/1590767/124152814-c1b36180-da8b-11eb-9505-4afdd3a7ff88.png)

When i Have in my settings to use a specific theme, it works fine

![image](https://user-images.githubusercontent.com/1590767/124153957-e956f980-da8c-11eb-9098-7c7108f16199.png)

I have Managed to get it to work - but only until my next reboot of the machine - by going into `Windows Customization Settings -> Color` and making any change there, and then reverting it back to what it was before (like changing the color or from light to dark and back). For some reason after I do that, everytime I run the program it gets the accent from Windows with no issue, until I restart the PC again.

---
### Environment

- Fluent.Ribbon __v8.0.3__
- MahApps __2.4.7__
- Windows __10 21H1__
- .NET Core __3.0 & above (including 6.0 preview)__

**Comment by batzen** [comment]
That sounds strange and more like a bug in windows instead of our theme generator.
Can you post the value from HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor for both cases?

**Comment by 537mfb** [comment]
It doesn't look like a theme generator issue - only the ribbon has this  issue - everything else in the window gets the accent correctly (I have a `TabControl` in that window aswell and he get's the accent - and so does the window's `titlebar`)

![image](https://user-images.githubusercontent.com/1590767/124232922-2f9e6e00-db0a-11eb-912f-ff354434ec1e.png)

The value of that registry key is `0xc44e5e17` in both cases (i'm not changing it)
To get the accent to work i change windows into dark mode and back into light mode - after that next time i run it works - but i've tested turning of and on the options to use the color in the `start bar` and the one to use that color in `titlebars` - and those work too. Also changing the color to another color and back to the original also works)

So at the end the windows options remain the same but apparently the existence of a change fixes it - until next reboot

I just got to work - Give me some time and as soon as I have a moment I'll post a test solution here to exemplify the problem

**Comment by 537mfb** [comment]
[WindowsSync.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/6752810/WindowsSync.zip)

Here you are - this is a NET 3.1 project, but i tried with 3.0, 5.0 and even 6.0 preview (using VS 2022 Preview) with the same result - I tried to keep it as simple as I could while keeping as close to my actual use case (using the appsetting.json to load the configuration)

1. if you run it after you boot up the PC, the tabcontrol gets the Windows accent and if you've set that option in your `Windows Customization Settings -> Color`, so does the Titlebar - however the ribbon is transparent on all parts that use said accent (`File` button and the sidebar in the `BackStage` in this example). Mind you, if you click where the `File` button should be, it does open the `Backstage`, and once there, overing over any `BackstageTabItem` does highlight it and if you click where the `Back` button should be, it does close the `Backstage` - they are there and work as intended, they're just  transparent and therefore can't be seen.
2. if you make any change in Windows `Customization Settings -> Color` - even if you undo said changes right away - and then run it, everything works as expected

**Comment by batzen** [comment]
So i just tried this on my machine and in Windows Sandbox and everything works as expected.
The reason will most likely be that the color from HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor has an opacity of 0.
The backstage button etc. just use the color from that registry key while the titlebar etc. use that color with a custom opacity.
You can verify that, kind of, by using `RuntimeThemeGenerator.Current.Options.UseHSL = true;` which causes all colors to be fully opaque.
So i still think there is something wrong with your system and some app, maybe even windows, messes with the alpha value of the accent color.

What we could do to prevent such issues, as we obviously don't expect the windows accent color to have any transparency set, is that we just ignore the transparency from the windows accent color and always use 255 as it's alpha value.
Would that be ok for you @punker76?

**Comment by batzen** [comment]
Fixed in ControlzEx.

**Comment by 537mfb** [comment]
Thanks @batzen & @punker76 

odd though that it would work after i change between dark and light mode without it making any changes to that registry entry

**Comment by 537mfb** [comment]
Am on the Subway right now so can't test this but I have my settings set to pick a color from the background image rather than me picking a specific color - maybe that's what causes the issue?

**Comment by batzen** [comment]
The background image should be the reason why the accent color delivers a non opaque color.
So it might really be a bug in windows itself if it's fixed after changing the settings and then changing them back.
No need to further investigate as we fixed it in ControlzEx by just using an opaque color.

@punker76 could you release a new version of ControlzEx or should i do it this time?

**Comment by punker76** [comment]
@batzen I'll do this later today.

**Comment by punker76** [comment]
@batzen @537mfb ControlzEx v5.0.1 published

**Comment by batzen** [comment]
Fixed by updating ControlzEx
