### ISSUE TITLE
Overriding a theme color issue

### ISSUE THREAD

**Issue by abdelkarim** [fluentribbon/Fluent.Ribbon#96]
I tried to override theme color for for the **MenuItem** control in **Windows8/Colors/Colors.xaml** to make them compatible with the OS theme, but my changes are not picked up !!!

![image](https://cloud.githubusercontent.com/assets/1153480/7072098/b75f9296-dee1-11e4-911e-7dca43c2e90e.png)

**Comment by batzen** [comment]
What exactly did you try to change??????????????

**Comment by abdelkarim** [comment]
The ckeck mark and its surrounding rect color scheme, but it kept using the ones in the attached picture.

**Comment by batzen** [comment]
Which lines in which files exactly did you try to change?

**Comment by batzen** [comment]
Any news on this one?
