### ISSUE TITLE
Fluent.Button Header Binding not visible

### ISSUE THREAD

**Issue by PJonHar** [fluentribbon/Fluent.Ribbon#961]
I have added a binding to the header property of a fluent.button, however when the application is running the value is not seen?
I have used snoop and i can see that the binding is happy and with the correct value but it does not show?

the value 100 should be showing in the button header.

any ideas?

![image](https://user-images.githubusercontent.com/1200267/125078483-5b959280-e0ba-11eb-8788-f188003f3b60.png)

`<Fluent:Button
                            Command="{Binding ProgramSpeedCommand}"
                            Header="{Binding ApplicationRobotControl.Robot.ProgramSpeed, FallbackValue=0}"
                            Icon="pack://application:,,,/KUKA.RGI v3;component/Icons/hand.ico"
                            LargeIcon="pack://application:,,,/KUKA.RGI v3;component/Icons/hand.ico">
                            <Fluent:Button.ToolTip>
                                <Fluent:ScreenTip
                                    Title="Program Speed"
                                    Width="250"
                                    DisableReason="This control is disabled to show 'disable reason' section"
                                    HelpTopic="Help for Orange ScreenTip"
                                    Image="pack://application:,,,/KUKA.RGI v3;component/Images/hand.png"
                                    Text="This control is disabled and has fixed width 250px" />
                            </Fluent:Button.ToolTip>
                        </Fluent:Button>`

**Comment by batzen** [comment]
Could you remove the `FallbackValue` and try it again?
I have seen very strange behavior of bindings in combination with fallback values recently.

**Comment by PJonHar** [comment]
I have tried removing the FallbackValue but the value doesnt show on the ribbon button.

**Comment by batzen** [comment]
Could you share a repro?

**Comment by PJonHar** [comment]
Sure, see attached.
![image](https://user-images.githubusercontent.com/1200267/125417133-98e7af3d-4e52-4227-80f1-61155fb2595c.png)

[FluentRepro.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/6807089/FluentRepro.zip)

**Comment by batzen** [comment]
That's quite strange.
Most controls in Fluent.Ribbon use a TemplateBinding for the header, which does not seem to work when the bound value is not a string.
It works again if using a Binding with a relative source...

**Comment by PJonHar** [comment]
If possible could you show me a workaround please?

**Comment by batzen** [comment]
A workaround for you would be:
```
        public string ProgramSpeedString { get => programSpeed.ToString(); }
        public int ProgramSpeed { get => programSpeed; set { programSpeed = value; NotifyPropertyChanged(nameof(ProgramSpeed)); NotifyPropertyChanged(nameof(ProgramSpeedString)); } }
```

And then bind to ProgramSpeedString instead of ProgramSpeed.

**Comment by PJonHar** [comment]
Thanks.
I ended up using a converter to return the ToString() of an object.
