### ISSUE TITLE
Window title drawn at wrong position if TitleBar is collapsed

### ISSUE THREAD

**Issue by carloslubbers** [fluentribbon/Fluent.Ribbon#970]
While trying to create a start screen where the LeftContent is quite narrow, the application title bar starts to appear in the background.

Example in showcase application when the start screen left content is emptied and the ItemsPanelMinWidth = 0
![image](https://user-images.githubusercontent.com/33954216/132829650-f73026cc-6a71-4f7a-837a-a48f9bc057fa.png)

I think that in the RibbonTitleBar.xaml, the IsCollapsed trigger (line 40) should also hide the PART_HeaderHolder.

---
### Environment

- Fluent.Ribbon 3bce4ef
- Windows 10 21H1
- .NET 5

**Comment by batzen** [comment]
Will have a look at why it's the way it currently is.

**Comment by carloslubbers** [comment]
Any updates on this?

**Comment by batzen** [comment]
Not yet. Had to finish and release version 9.0 first.

**Comment by batzen** [comment]
So after some consideration, it's not that the title should be hidden but it should respect the set `HeaderAlignment` instead.
In your case, if you are using the default, it should be `Center` and thus not look cut-off after my fix.

**Comment by carloslubbers** [comment]
Would it be possible to add a way to hide it completely, or is there one already? Respecting the header alignment can be fine, but for smaller window sizes (or a wide LeftContent) it will still be placed below the LeftContent container and be cut off 
![image](https://user-images.githubusercontent.com/33954216/147362410-492b74fe-4ff3-46cd-b7b7-28e8d31cda90.png)

**Comment by batzen** [comment]
I will add `HeaderVisibility` as a new property on the title bar.
That way you can trigger header hiding yourself.
Would that be a solution for you?

**Comment by carloslubbers** [comment]
That probably sounds OK, I will be able to play around with it in the new year and let you know :)
