### ISSUE TITLE
 How to change the color of the title, I tried it, but it doesn’t work, the font size is ok

### ISSUE THREAD

**Issue by wangfeng10** [fluentribbon/Fluent.Ribbon#971]
**Place your issue description here.**

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Fluent.Ribbon __v?.?.?__
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
Which title are you referring to?
Which version are you using?

**Comment by wangfeng10** [comment]
Fluent.Ribbon v7.0.0
Windows 10
.NET Framework 4.5
this title
![image](https://user-images.githubusercontent.com/30644298/133249448-6759bcce-5c3b-4108-834c-5c4079ef741f.png)

**Comment by carloslubbers** [comment]
There is a property "TitleForeground" on the RibbonWindow which you should be able to use to change the color
