### ISSUE TITLE
Version 9.0 Stable Release?

### ISSUE THREAD

**Issue by nlogozzo** [fluentribbon/Fluent.Ribbon#985]
Version 9.0 seems to be completed via the GitHub milestone? Is there anything we are waiting for to release a stable build?

**Comment by batzen** [comment]
Will release a new preview/rc this week and most likely the final/stable next week.

**Comment by batzen** [comment]
FYI https://www.nuget.org/packages/Fluent.Ribbon/9.0.0-rc0278

**Comment by nlogozzo** [comment]
Ah ok no worries. Didn't see the beta package thanks for that :)

**Comment by nlogozzo** [comment]
Hey, any update on this? Or maybe an updated beta package?

**Comment by batzen** [comment]
Will release the final version this week.
Took me a bit longer to upgrade to the latest rc/alpha at work as i had to finish other things there first and found some bugs i just fixed this week.
