### ISSUE TITLE
QuickAccessToolbar - More Commands leaves open empty Popup when overflow gets empty

### ISSUE THREAD

**Issue by nielsbenecke** [fluentribbon/Fluent.Ribbon#989]
Hi!

When I remove an item from the Pop-Up "More Commands" Toolbar and maximize my Application again it leaves a white box behind. 
I guess this occurs because the DropDownButton is still open. 

![image](https://user-images.githubusercontent.com/53931052/141455826-a43630ed-7edd-4bfe-827d-739f0d3e061d.png)

---
### Environment

- Fluent.Ribbon __v8.0.3__
- Windows __10__
- .NET Framework __4.8__

**Comment by batzen** [comment]
I don't exactly understand what you did.
Could you explain the steps with a bit more detail or share a gif?
You can use the tool like ScreenToGif to record a gif.

**Comment by nielsbenecke** [comment]
I start with a small Application window and I do the following:

1. Open the "More Commands" Toolbar.
2. Remove one item from the Toolbar.
3. Maximize my window so the "More Commands" Button disappears and the normal QuickAccessToolbar DropdownButton reappears.

I get the white box as a result.

![Animation](https://user-images.githubusercontent.com/53931052/141738690-4e8db744-2b07-4d3a-90d9-c127a70fcb07.gif)
