### ISSUE TITLE
QuickAccessMenuItem Target Command bindings not working

### ISSUE THREAD

**Issue by Joekraft** [fluentribbon/Fluent.Ribbon#99]
My command bindings do not appear to reach my ViewModel, similar issue was posted a few years ago - https://fluent.codeplex.com/workitem/16452

For example the two Fluent:QuickAccessMenuItems below:

    <Fluent:Ribbon.QuickAccessItems>
        <Fluent:QuickAccessMenuItem IsChecked="true">
            <Fluent:Button Command="{Binding SaveChangesCommand}"
                            Icon="/proj;component/Resources/Icons/save_icon.ico"
                            Size="Small"/>
        </Fluent:QuickAccessMenuItem>

        <Fluent:QuickAccessMenuItem IsChecked="true" Target="{Binding ElementName=SaveButton}"/>   
    </Fluent:Ribbon.QuickAccessItems>

The first does not work, the second is bound to an identical button in a RibbonGroupBox and works correctly.

**Comment by batzen** [comment]
Could you send me a small repro for this issue?

**Comment by batzen** [comment]
Just tried to reproduce this in the showcase application with a ICommand created in the MainViewModel and it works as it should.

**Comment by batzen** [comment]
Any news on this one?
