### ISSUE TITLE
Window initialization slows down after upgrade to 9.0

### ISSUE THREAD

**Issue by AndersChen123** [fluentribbon/Fluent.Ribbon#995]
After upgrading from 8.0.3 to 9.0, the window initialization speed slows down.
[v8.png](https://postimg.cc/ygvrpRXV)
This is the initialization speed of the window using 8.0.3.

[v9.png](https://postimg.cc/CnRJvQxN)
This is the initialization speed of the window using 9.0.

The window content is simple, with just four ribbon tabs and an OxyPlot chart.
It was about 700 milliseconds slow after the upgrade.

---
### Environment

- Fluent.Ribbon v9.0
- Windows 10 pro 21H2
- .NET Framework 4.7.2

**Comment by batzen** [comment]
It shouldn't be that much slower.

Could you either share the profiling files or expand the call trees all the way down and then use "Copy Subtree to clipboard", put the results into text files and attach those to this issue?

FYI: you don't need to upload images on an external host, you can just drag&drop or copy&paste them in the text area here.

**Comment by AndersChen123** [comment]
Thank you for your reply. 
The attachment is profiling files. The file format is 7z, I changed it to zip for uploading.
[v9.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7750137/v9.zip)
[v8.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7750152/v8.zip)

**Comment by batzen** [comment]
That's quite strange. Something seems to run twice. As the main time consumer is `OnIsCheckedChanged` from `ToggleButtonHelper` which results in the content of some element to be changed.
From what i can tell it looks like the ribbon is minimized/expanded multiple times during loading.

Could you share your application, ideally with it's source code.
If you don't want to share it publicly, we can figure out a way  to do it privately.

**Comment by AndersChen123** [comment]
Sorry, this is an internal project of our company, so the code cannot be sent.
I create a demo to reproduce this problem. Although the slowness is not as obvious as the other project, it is also slower. Hope this helps you diagnose the problem.

Run the project and double-click the chart to open the child window. I started profiling when I opened the child window.
[FluentRibbonTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7751657/FluentRibbonTest.zip)

**Comment by batzen** [comment]
I can't see any performance problems in the provided test application, at least on my machine.
See my profiling results:
[8.0.3.dtt.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7757066/8.0.3.dtt.zip)
[9.0.0.dtt.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7757070/9.0.0.dtt.zip)

What's strange is that performance seems to be around 10 times slower on your machine.

**Comment by AndersChen123** [comment]
The slow part is mainly in AssociatedObject_SourceInitialized and OnIsCheckedChanged.
The OnIsCheckedChanged method in the demo executes quickly, but it is very slow in another project, probably because there are many buttons and menu items.
I suppose it was caused by the IsChecked property of Expand the Ribbon menu item changed many times. But I did not find what caused it to change many times.

**Comment by batzen** [comment]
Do you have set the `GroupName` on some `ToggleButton` or `MenuItem` by accident?
As the called method `ToggleButtonHelper.UpdateButtonGroup` only calls `SetCurrentValue` if there are other buttons with the same group. Maybe you have a second button that's bound to `IsMinimized` and that causes the toggling.
The toggling also seems to activate some style trigger which changes the content of something. The default style from Fluent.Ribbon does not change the content on triggers.

If you have Rider you can set a breakpoint inside the `ToggleButtonHelper.UpdateButtonGroup` to see if and which buttons are in the same group.

**Comment by AndersChen123** [comment]
Code from RibbonTabControlControlTemplate
`<Fluent:MenuItem GroupName="ShowRibbon"
                                         Header="{Binding Source={x:Static Fluent:RibbonLocalization.Current}, Path=Localization.ExpandRibbon, Mode=OneWay}"
                                         IsCheckable="True"
                                         IsChecked="{Binding IsMinimized, RelativeSource={RelativeSource TemplatedParent}, Converter={x:Static converters:StaticConverters.InverseBoolConverter}}"
                                         Visibility="{Binding CanMinimize, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource boolToVisibilityConverter}}" />
                        <Fluent:MenuItem GroupName="ShowRibbon"
                                         Header="{Binding Source={x:Static Fluent:RibbonLocalization.Current}, Path=Localization.MinimizeRibbon, Mode=OneWay}"
                                         IsCheckable="True"
                                         IsChecked="{Binding IsMinimized, RelativeSource={RelativeSource TemplatedParent}}"
                                         Visibility="{Binding CanMinimize, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource boolToVisibilityConverter}}" />`

The problem is related to the IsMinimized property of RibbonTabControl. If I delete the IsChecked binding in the above code or only delete the InverseBoolConverter, the problem is gone. 
But now I have no idea how to fix it.

**Comment by batzen** [comment]
You are totally right. That's my mistake. The menu items shouldn't have a group name. Argh...

**Comment by batzen** [comment]
Thanks for reporting, providing information and finding the culprit.. Will release version 9.0.1 next week.
If you need a fixed version via nuget ASAP you can use the appveyor nuget feed till i release to nuget.org.
