### ISSUE TITLE
.NET 6 support?

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#997]
Any chance for .NET 6 support?

Latest version seems to have support for .NET 5, so should be fairly simple to include v6 in the nuget package.

**Comment by batzen** [comment]
.NET 6 actually is supported. There just isn't a separate dll for .NET 6 as there is no code that depends on .NET 6 specific features and no code that depends on removed features. The same applies to ControlzEx and Snoop.

**Comment by znakeeye** [comment]
But `ControlzEz` depends on .NET 5? So what happens if you don't have v5 installed?

**Comment by batzen** [comment]
That's defined by your application and not the library.
Your application loads the runtime and defines things like roll-forward policies, the library just gets loaded into the loaded runtime.

**Comment by znakeeye** [comment]
Ah ok. So then Fluent Ribbon is fully .NET 6 compliant?

**Comment by batzen** [comment]
I didn't encounter any issues so far.
