### ISSUE TITLE
Window object not being recycled after ribbon window is closed

### ISSUE THREAD

**Issue by leixao** [fluentribbon/Fluent.Ribbon#999]
Hi, I'm having a very strange problem using this library, possibly a memory leak?
In my application, I need to create multiple ribbon windows, which contain some ribbon buttons and commands.
Defined as follows:
![image](https://user-images.githubusercontent.com/59323065/148632348-6e16ed62-26b0-4ce0-aa18-0dd4af1e68b1.png)
I need to create a lot of windows like this and when they are closed, in VS memory monitoring tool I found that the window object is not being recycled. After reading the source code and doing some tests, I found that there are three situations in which the window can be recycled.

1. Do not set commands for ribbon buttons;
2. In the window closed event, set the command to null;
3. Remove the IconPresenter from the button template.
![image](https://user-images.githubusercontent.com/59323065/148632680-e584bebb-f162-44b2-a4cb-7aa6dcd21974.png)
I didn't find the relation between IconPresenter and Command from the code.

Here is my test project:
[Ribbon.MemLeakTest-main.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/7832607/Ribbon.MemLeakTest-main.zip)

---
### Environment

- Fluent.Ribbon __v9.0.1__
- Windows __11__
- .NET Core __3.1__

**Comment by batzen** [comment]
This was caused by wrong code in the IconPresenter which caused all IconPresenters, that got disabled at least once, to be held in  memory by the GrayscaleEffect that's being used in IconPresenter.

**Comment by batzen** [comment]
Thanks for investigating and providing a repro.

**Comment by leixao** [comment]
Hi, I updated the version in the test project to 9.0.4, the memory leak problem still exists, the bug does not seem to be fixed.
![image](https://user-images.githubusercontent.com/59323065/167375425-61879a07-669f-49a9-a11f-a2d0404df235.png)

**Comment by leixao** [comment]
Aha probably because VS didn't recompile
Problem solved :) 
9.0.4 works fine
